### ISSUE TITLE
Redundant tooltip

### ISSUE THREAD

**Issue by Fyresparxx** [arkayenro/arkinventory#1000]
ArkInventory adds this redundant info to the bottom of all my tooptips. Is there any way to disable this second tooltip block? It doesn't appear to be in the tooltips options.
![ai tt](https://user-images.githubusercontent.com/36558355/36338251-a28faf48-136f-11e8-903d-1c96b10a046f.png)

**Comment by arkayenro** [comment]
thats not from AI

**Comment by Fyresparxx** [comment]
My bad! I swear I thought I disabled all my addons trying to narrow it down and wound up on AI. Apparently, I misclicked and had informant active, thinking it was disabled because auctioneer was disabled.  Sorry to have wasted your time! But thank you for making me look again!
