### ISSUE TITLE
Excessive ERROR Count: attempt to index local 'frame' (a nil value)

### ISSUE THREAD

**Issue by slickwalker** [arkayenro/arkinventory#1001]
4522x ArkInventory\ArkInventory-30740.lua:7668: attempt to index local 'frame' (a nil value)
ArkInventory\ArkInventory-30740.lua:7668: in function `Frame_Item_Update_Lock'
ArkInventory\ArkInventory-30740.lua:2632: in function `ObjectLockChanged'
ArkInventory\ArkInventoryStorage.lua:450: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `resume'
TradeSkillMaster\CoreAPI\Threading.lua:326: in function `RunThread'
TradeSkillMaster\CoreAPI\Threading.lua:430: in function <TradeSkillMaster\CoreAPI\Threading.lua:363>

Locals:
nil

**Comment by arkayenro** [comment]
should be fixed in the next release

**Comment by arkayenro** [comment]
fixed in 3.07.41
