### ISSUE TITLE
Frame_Item_Update_Lock

### ISSUE THREAD

**Issue by XuoMauz** [arkayenro/arkinventory#1002]
52x ArkInventory\ArkInventory-30740.lua:7668: attempt to index local 'frame' (a nil value)
ArkInventory\ArkInventory-30740.lua:7668: in function `Frame_Item_Update_Lock'
ArkInventory\ArkInventory-30740.lua:2632: in function `ObjectLockChanged'
ArkInventory\ArkInventoryStorage.lua:439: in function `?'
...urse\svn\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...urse\svn\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
...urse\svn\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
...y\Externals\curse\svn\Ace3-AceEvent\AceEvent-3.0-4.lua:120: in function <...y\Externals\curse\svn\Ace3-AceEvent\AceEvent-3.0.lua:119>
[C]: in function `resume'
ArkInventory\ArkInventory-30740.lua:10254: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
nil

**Comment by arkayenro** [comment]
fixed in 3.07.41
