### ISSUE TITLE
Performance problem while no bags are open

### ISSUE THREAD

**Issue by ilreberli** [arkayenro/arkinventory#1003]
I am using Arkinventory since years and it's a great addon to keep bags clean. 
But since a few week i have big performance problems in general while playing. So I tried to find out whats going on. While investigate this I recognized, that Arkinventory is my biggest CPU eater, even when there is no bag open. I understand when I have some delays while moving items in my bags, because I have a lot of rules, but why Arkinventory is using so much CPU, even when no Bag is open and no Items are gathered or stored in the bags.

![image](https://user-images.githubusercontent.com/37041620/36945963-d3b5cbe6-1fb5-11e8-858b-b4f8e8b65fcf.png)

**Comment by arkayenro** [comment]
try the latest alpha and see if theres a difference.

there were a couple of issues with the toybox code that might have caused it to constantly scan

**Comment by arkayenro** [comment]
fixed in 3.07.41 - if its not re-open this

**Comment by ilreberli** [comment]
Thank you, i have installed your patch and it works fine :)
