### ISSUE TITLE
Toybox and Pet collection scans calling wrong function

### ISSUE THREAD

**Issue by mgriner** [arkayenro/arkinventory#1004]
I have been experimenting with updating the search functionality and came across what I think is a bug.

In the functions ArkInventory.Collection.Toybox.Scan_Threaded (ArkInventoryCollectionToy.lua) and ArkInventory.Collection.Pet.Scan_Threaded (ArkInventoryCollectionPet.lua) at then end of the functions if the update flag is set it calls the corresponding collection scan function from ArkInventoryStorage.lua but it looks like they are reversed.

That is, in ArkInventory.Collection.Toybox.Scan_Threaded it calls ArkInventory.ScanCollectionPet( ) and in ArkInventory.Collection.Pet.Scan_Threaded it calls ArkInventory.ScanCollectionToybox( )

**Comment by arkayenro** [comment]
yep.  thats already been fixed in one of the latest alphas
