### ISSUE TITLE
items will be linked twice in chat

### ISSUE THREAD

**Issue by MisterT87** [arkayenro/arkinventory#1005]
Hey Guys,

First of all: thanks for this great addon - great work :)

Since last update: Items will be linked twice into chat and I did SHIFT+ left click only one time.
I dont have any proof hope someone can repoduce it ?

Have a nice day :)

**Comment by elphyne** [comment]
i'm having the same issue.. i even turned off all the other addons and it still did it

**Comment by arkayenro** [comment]
crap, it means i left some secure template test code in there.  thought i had removed it all

**Comment by arkayenro** [comment]
not test code, just rearranged code for that test i forgot to fix up.  new version will be up in a little bit

**Comment by arkayenro** [comment]
fixed in 3.07.42
