### ISSUE TITLE
ArkInventory_Mount: Default List Selection 'Use All'

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1006]
Updated to 3.07.42 today, went to mount and was super surprised to not get my selected mount.  After a little bit of investigation, the 'Use All' option was automatically checked on update.  Please consider changing this to not auto-select this option when the user already has a mount selection.  Thanks.

**Comment by arkayenro** [comment]
unfortunately due to the way the code now works it has to be the default or new users would have to select it or select a mount to get any mounts to work, which they shouldnt have to do.

it is mentioned in both the change logs and version history file

**Comment by Calesta** [comment]
Going to close this ticket as it sounds like it was a result of a major change and won't be reverted.  Thanks.
