### ISSUE TITLE
ArkInventory_Mount: Water Surface Mount is Selected on Land-Only Areas

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1007]
Updated to 3.07.42 today and went to Darkmoon Island.  Mounted and was put on my underwater mount.  I'm not sure if this is an issue or it's related to another issue that I'll be submitting -- no land mount selection because flying mounts don't appear in the list despite 'Include as Land mount selections' -- but it's not how it behaved before.

**Comment by arkayenro** [comment]
if you were put on an underwater mount then you were in the water so an underwater mount should have been summoned - if that didnt happen before (summon an underwater mount when underwater) then that was a bug, which is now fixed

if you dont want an underwater mount while you are underwater/swimming then you can hold down the shift key while clicking on the mount summon key to use the alternative type

**Comment by Calesta** [comment]
I wasn't swimming.  I had just entered the portal and mounted.

**Comment by arkayenro** [comment]
if you ended up on an underwater mount then the game allowed an underwater mount to be summoned there and there isnt much i can do.  i can only go off what the game says and its not like it hasnt been wrong before (theyre still having issues with flight status is azeroth)

which mount was it?  i can test it out when i get home if the faire is still running

**Comment by Calesta** [comment]
Reverting to 3.07.40 fixed my issue for now.  I'll keep an eye out on the status of this ticket and see when it's safe to update.

**Comment by arkayenro** [comment]
sorry, cant duplicate it.

location - darkmoon faire after exiting the portal

i have three land mounts selected
surface mounts are set to use all (ive only got the one strider - include as land mounts is not enabled)
underwater mounts are set to use all
i have one flying mount selected, and include as land mounts is enabled

its random between the three land mounts and the one flying mount.  the surface mount is never summoned

**Comment by arkayenro** [comment]
does the strider show up under the land or water surface menu?

ie have you re-categorised it from land to surface?

**Comment by Calesta** [comment]
It's under the Water Surface menu.  I haven't re-categorized it.

**Comment by arkayenro** [comment]
the only other thing i can think of is that you have no viable land mounts (either none are selected, or what is selected you cant actually use) so it has to fall back on surface mounts and flying mounts?

if you do have some selected can you mouse over them and ensure that Summon is not greyed out?

you can also edit arkinventory.ldb, line 743, and remove the two minus signs at the front, save the file, then reloadui in game, then try and mount and see if the warning about no land mounts comes up

**Comment by Calesta** [comment]
You're probably right.  I think I turned off the 'Use All' check on all the menus because it was new and seemed to cause the others issues I raised.  I did notice that it said 'None' in Land when I had the latest version installed and it says 'Random: (All)' in Land when I reverted back to a previous version / preference file.  I'll try to upgrade it again this weekend and choose the 'Use All' in the Land menu and see what happens.

**Comment by arkayenro** [comment]
i disabled all my land mounts, and went to silvermoon (no flying), and now i can duplicate the issue.

i've updated the code so that it should add the surface/flying (if enabled) mounts to the list of land mounts, even if no land mounts are selected (it was only adding them if there was at least one), before it moves on to the fallbacks

**Comment by arkayenro** [comment]
it should work like this https://github.com/arkayenro/arkinventory/wiki/Mounts#how-is-a-mount-selected in the next version

**Comment by Calesta** [comment]
Great!  Thanks for troubleshooting!

**Comment by arkayenro** [comment]
fixed in 3.07.43
