### ISSUE TITLE
ArkInventory_Mount: Flying Mounts Not Shown in Land Mounts List Despite Preference

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1008]
Updated to 3.07.42 today and now my flying mounts aren't shown in my list of land mounts despite having checked 'Include as Land mount selections' in the Flying list.  Was there a major code change to the mounts section?  I found three mount-related issues with this update.

**Comment by arkayenro** [comment]
i didnt think the code actually added all the flying mounts to the land mount list?  it was already a huge list, i wouldnt have thought id add more to it.  the point was to use whatever selected flying mounts you had selected and include them when summonining (which actually didnt work all that well)

the new code is the same, allow users to pick flying (and now surface) mounts to be included as land mounts when summoning - but not put them in the actual ground mount list to be selected there separately from their actual type

the change log comments and/or the version history both contain what has been updated for each version, and yes, mount selection was changed drastically

**Comment by Calesta** [comment]
I have 'Include as Land mount selections' selected and only 'Archmage's Prismatic Disc' selected in the Flying menu.  When I summoned a mount in either a land/flying area before, the Archmage's Prismatic Disc' was used for both.  Now when I'm in a land-only area, my water surface mount is used.

I'll just revert back to the previous version for now.  Looks like I'll have to pay more attention to change notes for this otherwise typically stable addon.  :)
