### ISSUE TITLE
Error with tooltips and new version of Opie

### ISSUE THREAD

**Issue by Fraktyl** [arkayenro/arkinventory#1010]
With the new version of Opie if you get a tooltip on items that aren't actually in your inventory you get an error.  These are items that could have been part of a slice for other characters.  e.g. Heal Pots, Mana Pots, bandages, etc.

The error is:
182x ArkInventory\ArkInventoryTooltip.lua:621: attempt to index field 'ARK_Data' (a nil value)
ArkInventory\ArkInventoryTooltip.lua:621: in function <ArkInventory\ArkInventoryTooltip.lua:604>
(tail call): ?
[C]: ?
[C]: ?
[C]: in function `tipFunc'
OPie\OPieUI.lua:170: in function <OPie\OPieUI.lua:152>
OPie\OPieUI.lua:253: in function <OPie\OPieUI.lua:225>

Locals:
tooltip = GameTooltip {
 0 = <userdata>
 default = 1
}
arg1 = 133575
arg2 = nil
arg3 = nil
arg4 = nil
(*temporary) = nil
(*temporary) = GameTooltip {
 0 = <userdata>
 default = 1
}
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'ARK_Data' (a nil value)"
type = <function> defined =[C]:-1

Going to let the Opie author know also.

**Comment by arkayenro** [comment]
what version of AI are you using?

**Comment by arkayenro** [comment]
copy and paste the line below into your chat window and let me know if it returns anything

/run ArkInventory.Output( { AltGameTooltip } )

**Comment by arkayenro** [comment]
i've altered my code so it wont barf when other mods create a tooltip object the way opie has

**Comment by Fraktyl** [comment]
Sorry about that.  Got tied up and away from a computer yesterday. 

I ran the command above:

[07:51:34]ArkInventory: { [1]={ [0]=**userdata**, [default]=1 } }

Also, this is with the latest alpha code you put out.  Apologies for the late response

**Comment by arkayenro** [comment]
can you test the [r706-alpha](https://www.wowace.com/projects/ark-inventory/files/2542004), the new tooltip code is in there

**Comment by hollo6** [comment]
Please don't rename Bag to Backpack, makes the tooltip huge if you have many alts and items scattered everywhere.

**Comment by arkayenro** [comment]
fixed in 3.07.43
