### ISSUE TITLE
Taint error caused by ArkInventory

### ISSUE THREAD

**Issue by Voska128** [arkayenro/arkinventory#1012]
3/16 23:16:42.785  Global variable UIDROPDOWNMENU_MENU_LEVEL tainted by ArkInventory - Interface\FrameXML\UIDropDownMenu.lua:813 ToggleDropDownMenu()
3/16 23:16:42.785      DropDownList1Button2:OnEnter()
3/16 23:16:42.785  Execution tainted by ArkInventory while reading UIDROPDOWNMENU_MENU_LEVEL - Interface\FrameXML\UIDropDownMenu.lua:737 UIDropDownMenu_GetSelectedID()
3/16 23:16:42.785      Interface\FrameXML\UIDropDownMenu.lua:467 UIDropDownMenu_AddButton()
3/16 23:16:42.785      Interface\FrameXML\UnitPopup.lua:695 UnitPopup_AddDropDownButton()
3/16 23:16:42.785      Interface\FrameXML\UnitPopup.lua:546 UnitPopup_ShowMenu()
3/16 23:16:42.785      Interface\FrameXML\TargetFrame.lua:1197 initFunction()
3/16 23:16:42.785      Interface\FrameXML\UIDropDownMenu.lua:69 UIDropDownMenu_Initialize()
3/16 23:16:42.785      Interface\FrameXML\UIDropDownMenu.lua:941 ToggleDropDownMenu()
3/16 23:16:42.785      DropDownList1Button2:OnEnter()
3/16 23:16:42.785  CloseDropDownMenus()
3/16 23:16:42.785  An action was blocked because of taint from ArkInventory - ClearFocus()
3/16 23:16:42.785      Interface\FrameXML\UnitPopup.lua:1691 func()
3/16 23:16:42.785      Interface\FrameXML\UIDropDownMenu.lua:791 UIDropDownMenuButton_OnClick()
3/16 23:16:42.785      DropDownList1Button3:OnClick()

**Comment by arkayenro** [comment]
read this https://github.com/arkayenro/arkinventory/wiki/Taint

AI doesnt touch that variable so its from another mod via one of the shared libraries

**Comment by Voska128** [comment]
I'm convinced its arkinventory. If I disable arkinventory.. The issue
doesn't occur. As soon as I enable it, it happens again. And its odd, I
think the issue is related to the item: champion's symbol. Issue seems to
occur everytime I receive one

**Comment by arkayenro** [comment]
follow the instructions i linked previously, setting the value to 2, reproduce the issue

attach the logs here

**Comment by Voska128** [comment]
Attached you will find taintlog level 2... sorry had to zip it as it was
too large to send.

I'm wondering if this might actually have more to do with bartender now.
Its odd though, like i said deactivating arkinventory seems to prevent the
issue.  So i wonder if maybe one can trigger the other in some fashion?

Thanks,

**Comment by arkayenro** [comment]
i dont think attachments come through via email, youll need to attach it to the ticket via a link

**Comment by Voska128** [comment]
[taint.log](https://github.com/arkayenro/arkinventory/files/1882713/taint.log)

Let me know if this works, thanks

**Comment by Voska128** [comment]
[taint.zip](https://github.com/arkayenro/arkinventory/files/1882858/taint.zip)

**Comment by arkayenro** [comment]
skada is libstub loaded (ace3 based) so its basically tainted by arkinventory instantly (it loads libstub)

line 2 in skada.lua is odd, i've not seen an addon defined like that, its possibly why its not showing as the cause of the taint

4/5 20:52:51.110  Global variable Skada tainted by ArkInventory - Interface\AddOns\Skada\Skada.lua:2

skada touched ToggleDropDownMenu() while in combat - the ui dropdowns have serious taint issues (its one of the reasons i use a 

4/5 20:54:06.481  Global variable UIDROPDOWNMENU_MENU_LEVEL tainted by ArkInventory - Interface\FrameXML\UIDropDownMenu.lua:813 ToggleDropDownMenu()
4/5 20:54:06.481      Interface\AddOns\Skada\Menus.lua:443 ModeMenu()
4/5 20:54:06.481      Interface\AddOns\Skada\BarDisplay.lua:45

youll need to speak to the author of skada
