### ISSUE TITLE
Enable plain search for string.find

### ISSUE THREAD

**Issue by mgriner** [arkayenro/arkinventory#1016]
Not a major issue but it might be useful to enable plain search for `string.find` in `ArkInventory.Search.Frame_Table_Refresh` .  It is an optional fourth argument, by default string.find allows a subset of regex.  By enabling plain search it disables the regex.  This is only a minor issue, to see the problem make sure lua errors are enabled in WoW and then  try entering a '(' or a '[' into the search bar.  This fires off some errors about the regex pattern being malformed.

`string.find(s, pattern [, index [, plain]])`
index can just be nil, it is just an index in the string to start the search at
`string.find( txt, filter, nil, true )`

**Comment by arkayenro** [comment]
will be fixed in the next alpha
