### ISSUE TITLE
new item glow clear not working

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1019]
I have the Clear option enabled under New Item Glow, but it does not seem to work. "New" items continue to glow after whatever many closings/openings of the bag, sometimes even after relog.
Sometimes they completely forget to glow at all.
I can't find any action I can do to trigger the switch between the two modes,
Just tried to reproduce it by crafting items. At first, the glow wouldn't cease, and after a few minutes (without me changing anything) all the items just stopped to glow altogether. Tried toggling the checkboxes on and off, /reload and relog. None of them made any difference.

**Comment by arkayenro** [comment]
are you sure youre updating the option in the layout being used by the bag?

**Comment by hollo6** [comment]
Yes, if I uncomment that line, the printout always appears when I close my bag.
Just managed to reproduce the issue: looted two containers then opened one of them (Traveler's Pet Supplies):

![image](https://user-images.githubusercontent.com/365584/37819964-75ccd8d4-2e7f-11e8-8261-871aa6a6cc8d.png)

Now one of the looted items (Battle Pet Bandage) stays glowing no matter how many times I close the bag:
![image](https://user-images.githubusercontent.com/365584/37820105-edfd5414-2e7f-11e8-9e18-0a74edae94f0.png)

But the other item (Pocket Lint) is not glowing. Unfortunately, I haven't checked if it was glowing or not before the first bag closing.

**Comment by arkayenro** [comment]
worked it out, will be fixed next alpha/release

**Comment by hollo6** [comment]
indeed it's all good now, thanks!

**Comment by arkayenro** [comment]
#1021
