### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Winterharat** [arkayenro/arkinventory#1020]
Could you add a number to the bag numbers in the lower left hand corner.  
My bag for example shows 71/104, meaning I have 74 slots out of 104 filled.  I really like to know how many empty slots I have without having to do the math.  
Could you do something like:

 ![bag count](https://user-images.githubusercontent.com/37464627/37845734-a9f00876-2e88-11e8-8326-d3a5119abaac.png)

Thank you for your time,
Winterhart

**Comment by arkayenro** [comment]
go into the config and edit the style youre using

under window > style > status - disable full display, it will just show the number of empty slots left
