### ISSUE TITLE
v3.07.42 New Item Glow -> Clear: option does not work (fix included)

### ISSUE THREAD

**Issue by DilectableBananaButterfly** [arkayenro/arkinventory#1021]
The 'clear' option should remove the IsNewItem-flag when the window is closed in function ArkInventory.Frame_Main_Clear_NewItemGlow (arkinventory.lua).

The problem is that the loop processing the "ArkInventory.Global.Location[loc_id].Bags" table does not produce a proper bag_id for "C_NewItems.RemoveNewItem( bag_id, slot_id )"

Replace the line: 
C_NewItems.RemoveNewItem( bag_id, slot_id )

With: 
local blizzard_id = ArkInventory.InternalIdToBlizzardBagId( loc_id, bag_id )
C_NewItems.RemoveNewItem( blizzard_id, slot_id )

Now the items will be cleared.

( SideNote: Wouldn't C_NewItems.ClearAll() be more efficient? )

**Comment by arkayenro** [comment]
probably, i just did a quick fix, its in one of the alphas that have been out for a while

the clearall is probably a better idea, less thinking required, so i'll probably change it to that

**Comment by arkayenro** [comment]
#1019

**Comment by arkayenro** [comment]
oh, the reason for not using clearall, i have to loop through and update my data anyway

**Comment by DilectableBananaButterfly** [comment]
Fair point. My thought was to C_NewItems.ClearAll() could be called before the loop updating ArkInv's internal data, this saves having to convert the _id to blizzard_id and the individual item call.

Doing it that way hasn't seemed to cause any problems -- so far -- and I couldn't think of any sync problems that could come up that wouldn't result in either Lua error. I'll defer to your comfort/paranoia level on that though. I'm just pleased to have it working.

**Comment by arkayenro** [comment]
fixed in 3.07.43
