### ISSUE TITLE
Removes Assigned Rules/Customs after Exporting

### ISSUE THREAD

**Issue by Trelander84** [arkayenro/arkinventory#1024]
Super frustrating, every time I export my profile - it removes all the rules / customs that have been assigned to separate sections and I have to go back thru it all again. This is for the account that is actually exporting, I have deleted, added, removed, and changed nothing - yet it removes all the settings. 

It's a great addon, and I suggest it to everyone , but this one gets old.

Thanks for looking into it.

**Comment by arkayenro** [comment]
how are you exporting your profile?

**Comment by Trelander84** [comment]
I right click green bag, config - settings, styles/layouts - select one I want and click export. Copy and paste to new account (I 5 box, so I do this frequently). Once I copy and close it removes my assignments, has happened a few times now. I have to go back and re-assign all the rules/customs back to their slots. It doesn't delete them or deactivate them, just takes them off the bag slots they are assigned. I have them named so I can fix it rather quickly, but still a hassle if its fixable - or if I am doing something wrong.

**Comment by PortableTech** [comment]
Just had the exact same issue happen, super annoying.

**Comment by arkayenro** [comment]
sorry, bad code on my part

if you have an editor that can show line numbers then edit ArkInventoryConfig\ArkInventoryConfig.lua line 405 and change it from

data.design = ArkInventory.ConfigInternalDesignGet( id )

to

data.design = ArkInventory.Table.Copy( ArkInventory.ConfigInternalDesignGet( id ) )

that should stop it from destroying your source data

**Comment by Trelander84** [comment]
Not seeing that line at 405 unfortunately, actually not seeing data.design at all in the file. Glad there is a fix incoming though =)

**Comment by arkayenro** [comment]
r720-alpha and onwards can run on the live servers
