### ISSUE TITLE
Little lag/delay, when hovering over items in the bags.

### ISSUE THREAD

**Issue by Manniala** [arkayenro/arkinventory#1025]
Hey, for a bit of time i have had a little freeze, when ever i hover over anything in the bags for the first time, until now i have judt thought yeah its probably some conflict with other addons, but today i removed all other addons, and went to see if that was the case, which it was not :(

Is this some thing you know off, and if so why is it happening?

I made a video to show you:
https://youtu.be/N8ctrWefYzM

And i did try the /console scriptErrors 1
but i do not get any lua error tho..
Version i have installed is: 3.07.43

After i made the video, i then saw i had an addone that was not in the standard package (yours), so i deleted that one, and logged in again, but now i get lua error (Presuming, this is due to the other addone, and the rules then no longer can be found (well the rule can but not the code that handles them))

> Message: Interface\AddOns\ArkInventory\ArkInventory.lua:10390: ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:209: [string "return( tmog() and not sb() and not collect..."]:1: attempt to call global 'tmog' (a nil value)
> Time: 04/24/18 23:05:43
> Count: 2
> Stack: Interface\AddOns\ArkInventory\ArkInventory.lua:10390: ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:209: [string "return( tmog() and not sb() and not collect..."]:1: attempt to call global 'tmog' (a nil value)
> [C]: ?
> [C]: ?
> Interface\AddOns\ArkInventory\ArkInventory.lua:10390: in function `ThreadResume'
> [string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>
> 
> Locals:

and

> Message: Interface\AddOns\ArkInventory\ArkInventory.lua:10390: ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:209: [string "return( tmog() and not sb() and collected()..."]:1: attempt to call global 'tmog' (a nil value)
Time: 04/24/18 23:05:43
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventory.lua:10390: ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:209: [string "return( tmog() and not sb() and collected()..."]:1: attempt to call global 'tmog' (a nil value)
[C]: ?
[C]: ?
Interface\AddOns\ArkInventory\ArkInventory.lua:10390: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>
Locals:

But the lag was not gone, so i went and deleted all data from all chars i have, so there only was the Hunter left, still the same lag :(

So i wanted to try one last thing, delete/rename the ArkInventory.lua and the .bak the size was at this point 3.7 mb, where the "original" was 7.1 mb, with 250228 lines in it, yeah a huge file, but the computer should still be able to handle this i guess.

The delay was gone, after i had deleted the files, but dos this mean i have to restart with all rules i use, and every thing ?
And if so, will i then not just end up with the lag again, when your addone starts collecting data from the alts and so on?

My computer should be strong enough to handle it
AMD Ryzan 7 1700X Eight-Core, 3,77 GHz
32 GB Ram
NVidia GeForce GTX 1080

Running WoW on an SSD drive... 
Win 10 (always up 2 date)
and so on, nothing really is outdated, no driver, not the hardware (or well ofc it can be better, but should be enough to run the game and the addone)

**Comment by Manniala** [comment]
Note, i found out if i go into Config, and disable the Item count and Gold amounts, i do no longer get that delay, but ofc also then loses the items information hmm

I think this might be the best solution for now, to let it stay on, and then use TSM info on items stored.

**Comment by arkayenro** [comment]
a lag spike when you hover over an item for the first time is normal, its basically going off and checking how many of it you, and all your other toons, have.

after the first mouseover its cached and wont need to be worked out again unless you gain or lose some of it

**Comment by Manniala** [comment]
Yeah, but this happens every time i re-log, so i can hover over the items, if i then do a /rl or logout and in again, the same items, regardless if i have looted any items or not, it then trickers the little lag again.

The TSM i have atm, i have no lag when i hover over the items, is there not a way you can cache it like TSM and a like does ?
I remember when i used the addone Altoholic i also did not have any problems.

But thx for reply.

**Comment by arkayenro** [comment]
yes, its a cache, its only temporary per session, reloading or logging out clears it.  the data would potentially be stale if it was saved across sessions (plus it would be huge)

**Comment by mgriner** [comment]
I have also noticed this issue and found the lag to be so bad from a user experience point of view that I also had to turn off item counts.  I don't remember it being this bad in the past.  I think that the lag could be avoided with a rework of how the item count lookup works but I haven't had time to look at it yet in much detail.

**Comment by arkayenro** [comment]
it looks like too much data was being cleared so the recounts were taking longer to recalculate.  i've fixed the code (i think) so it should be in the next release (and the next alpha for BFA)

**Comment by Manniala** [comment]
Thx, i will give it a go when it shows up on Curse / Twitch client :)

**Comment by arkayenro** [comment]
r720-alpha - item counts are now being calculated in the background

**Comment by Manniala** [comment]
Thx mate :)
