### ISSUE TITLE
FrameXML errors

### ISSUE THREAD

**Issue by AcidWeb** [arkayenro/arkinventory#1028]
Well 8.0 is not close yet but from that version FrameXML errors are displayed in-game. So I suggest to clean this up in free moment:

`4/28 10:10:22.632  Loading add-on ArkInventory
4/28 10:10:22.632  ** Loading table of contents Interface\AddOns\ArkInventory\ArkInventory.toc
4/28 10:10:22.632  ++ Loading file Interface\AddOns\ArkInventory\ArkInventory.xml
4/28 10:10:22.632  ARKINV_Frame1Changer: Couldn't find relative frame: $parentContainer
4/28 10:10:22.632  ARKINV_Frame3Changer: Couldn't find relative frame: $parentContainer
4/28 10:10:22.632  ARKINV_Frame4Changer: Couldn't find relative frame: $parentContainer
4/28 10:10:22.632  ARKINV_Frame5Changer: Couldn't find relative frame: $parentContainer
4/28 10:10:22.632  ARKINV_Frame6Changer: Couldn't find relative frame: $parentContainer
4/28 10:10:22.632  ARKINV_Frame7Changer: Couldn't find relative frame: $parentContainer
4/28 10:10:22.632  ARKINV_Frame8Changer: Couldn't find relative frame: $parentContainer
4/28 10:10:22.632  ARKINV_Frame9Changer: Couldn't find relative frame: $parentContainer
4/28 10:10:22.632  ARKINV_Frame10Changer: Couldn't find relative frame: $parentContainer
4/28 10:10:22.632  ARKINV_Frame11Changer: Couldn't find relative frame: $parentContainer
4/28 10:10:22.632  ARKINV_Frame12Changer: Couldn't find relative frame: $parentContainer
4/28 10:10:22.632  ARKINV_Frame13Changer: Couldn't find relative frame: $parentContainer
4/28 10:10:22.632  ARKINV_Frame14Changer: Couldn't find relative frame: $parentContainer
4/28 10:10:22.632  ARKINV_Frame15Changer: Couldn't find relative frame: $parentContainer`

**Comment by arkayenro** [comment]
i'd suggest you download an 8.0 ready alpha first :)

**Comment by AcidWeb** [comment]
I'm blind - sorry :-)
