### ISSUE TITLE
[BFA Beta] Cosmetic Issues

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1030]
Installed the latest alpha version (r717) for testing on the BFA Beta and it's been working quite well.  There is some sort of cosmetic issue with the squares where you can see what look like little parallel lines through the items.  Probably something minor that you'll fix quickly, but I thought I'd log it just case.

![wowscrnshot_051418_231018](https://user-images.githubusercontent.com/13042214/40089857-19524202-587c-11e8-9ec2-f6cbe06405f6.jpg)

**Comment by arkayenro** [comment]
i've seen those i just havent been able to work out where theyre coming from yet.

i presume its part of the azurite level, or something else new that blizzard have added to the item frame but dont hide by default.

could also be a bug in the border frame code as those appear to be broken in your screenshot

**Comment by Calesta** [comment]
Going to close this because in the latest build it's fixed.  Maybe it was something on their end.

**Comment by Calesta** [comment]
Got disconnected and logged back in and it returned.  Going to reopen for tracking.

**Comment by arkayenro** [comment]
should be fixed in the latest alpha.

blizzard are doing something weird when you set a border using the same image thats already being used
