### ISSUE TITLE
[BFA Beta] Error Hovering Over Mission Reward

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1031]
While hovering over a mission reward of 'Small Azerite Fragment', I receive the following error message.

Message: ...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:771: Usage:GetCurrencyLink(currencyType, currencyAmount)
Time: Fri May 18 20:52:42 2018
Count: 4
Stack: ...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:771: Usage:GetCurrencyLink(currencyType, currencyAmount)
[C]: in function `GetCurrencyLink'
...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:771: in function <...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:761>
(tail call): ?
[C]: in function `SetCurrencyByID'
...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:1028: in function `GarrisonMissionButtonRewards_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: (*temporary) = 1553

**Comment by Calesta** [comment]
Using the latest Alpha (r718-alpha).

**Comment by arkayenro** [comment]
fixed in r719-alpha
