### ISSUE TITLE
[BFA Beta] ArkInventory_Mounts Debug Messages

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1032]
Using the latest Alpha (r718-alpha) whenever I try to mount the following is shown each time.

ArkInventory: --- start mount check ---
ArkInventory: flight check - cannot fly here
ArkInventory: primary - check land
ArkInventory: primary - adding land
ArkInventory: primary - using land

Any chance we can turn this off?  I can't seem to find a setting to do so.

**Comment by arkayenro** [comment]
nope, still working on the mount code.  once its done it will go away

**Comment by Calesta** [comment]
Ok!  Thanks for letting us know.  You can close this if it's not needed for tracking purposes (i.e., to remember to take it out)

**Comment by arkayenro** [comment]
fixed in r719-alpha
