### ISSUE TITLE
Auto-sell equips the character with junk

### ISSUE THREAD

**Issue by Bachsau** [arkayenro/arkinventory#1035]
This always happens when you carry a lot of junk with you and turn in a quest for new equipment blueprints at the garrison's shipyard. After the quest is finished, WoW opens a non-working trade window, which triggers ArkInventory to equip the character with junk.

**Comment by arkayenro** [comment]
trust blizzard to do something weird like that.

ill need to see if theres a way to work of if a merchant window is actually valid or not, i just presumed they all were

**Comment by arkayenro** [comment]
do you recall if there was a buyback tab for that merchant?  i dont have any quests for them so i cant test those particular npcs

**Comment by Bachsau** [comment]
I think so. It indeed has this buyback box in the bottom right and it is as empty as the rest of the window, even if items for buyback should be available. Will check for tab next time.

**Comment by Bachsau** [comment]
There actually is a buyback tab. I made screenshots now. The window is completely disfunctional. I think it's missing its backend data and callbacks.
![wowscrnshot_053018_135935](https://user-images.githubusercontent.com/2454271/40751694-95d93848-646c-11e8-8fb0-33dbd68b0037.jpeg)
![wowscrnshot_053018_135938](https://user-images.githubusercontent.com/2454271/40751695-985d08a6-646c-11e8-825d-3d365897d9ac.jpeg)

**Comment by arkayenro** [comment]
if possible can you run the following command when it looks like that

/dump GetMerchantNumItems()

it should return a number for how many items the vendor has and as the game is showing nothing im hoping its nil or 0

**Comment by arkayenro** [comment]
fixed in 3.08.05 (hopefully)

**Comment by Bachsau** [comment]
I currently have no character leveling in this area and the quests needed to trigger this condition don't drop very often. But I will check as soon as I come back there.
