### ISSUE TITLE
[BfA Beta] ArkInventoryTooltip LUA Error

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1036]
Using the latest alpha build (r720) and looted my first kill for the session and the LUA error below popped up.

Also, happens when mousing over items in my inventory for the first time.  Looks like the tooltip adjusts for some sort of text beneath the sell price -- although nothing is shown.  Once I've mouseover an item once there's no LUA error again (even when looting the same item) but there is what appears to be a blank line under the sell price.

It appears to be related to seeing some item for the first time in the tooltip either in a loot window, inventory, quest reward, etc.

Message: Interface\AddOns\ArkInventory\ArkInventory.lua:10614: ...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:1143: bad argument #3 to 'format' (string expected, got boolean)
Time: Fri Jun  8 13:52:35 2018
Count: 4
Stack: Interface\AddOns\ArkInventory\ArkInventory.lua:10614: ...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:1143: bad argument #3 to 'format' (string expected, got boolean)
[C]: ?
Interface\AddOns\ArkInventory\ArkInventory.lua:10614: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: (*temporary) = "...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:1143: bad argument #3 to 'format' (string expected, got boolean)"

**Comment by arkayenro** [comment]
will be fixed next release

**Comment by arkayenro** [comment]
fixed in r721-alpha
