### ISSUE TITLE
[BfA Beta] Tooltip 'Stuttering'

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1037]
I'm using the latest alpha build (r721-alpha).  While on a longer flight path, I was mousing over an item in my inventory, moved to an adjacent item next to it, and noticed a slight hiccup before the tooltip appeared.  Easily seen when moving item to item in your inventory almost like its thinking about building the tooltip.  Is this related to the ArkInventory counts at the bottom of the tooltip?

**Comment by Calesta** [comment]
Actually, tried this on live and it does the same thing so it's probably not beta-related.  I guess I never noticed it before as we can fly everywhere ourselves right now.

**Comment by arkayenro** [comment]
its "normal" for the moment.  im trying to stop the massive lag spike you used to get when it was doing the item counts into smaller spikes but it means queueing the process so theres a delay before the item counts get added to the tooltip

im still not really happy with it but i havent worked out a better way yet

**Comment by Calesta** [comment]
It's more of a minor inconvenience.  I only opened the ticket because I never noticed it before and thought it was Beta-related.  Trying to make sure you get help catching all these things before expansion launch.  Thanks!

**Comment by arkayenro** [comment]
in the config under workarounds lower the out of combat thread timer down to 50ms, it should stop the spikes from being as severe
