### ISSUE TITLE
[BfA Beta] ArkInventory Tooltip Counts - Shows Character Count and then Location Count

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1038]
Hopefully this isn't an intentional change but rather a beta-related bug / issue.  Using the latest release version on the live client and mousing over an item shows something akin to the following.  It shows my character's name and the item count followed by a breakdown of that count by location.

![live](https://user-images.githubusercontent.com/13042214/41799922-48a2dcb4-7641-11e8-90a6-5c581d1da630.jpg)

Using the latest alpha (r721-alpha) on the Beta client and mousing over an item shows something akin to the following.  This is much different and seems redundant as it shows the count multiple times.  I'm not sure what it would look like with multiple locations as I didn't think to actually put something into the bank to test it.

![beta](https://user-images.githubusercontent.com/13042214/41799842-ed937946-7640-11e8-98fb-3480f66283e0.jpg)

If this is an intentional change, can you add an option to revert back to the original view?  It seems more compact and easier to quickly interpret.

**Comment by arkayenro** [comment]
its an intentional change but its not supposed to show the count on the right unless theres more than one location involved

i thought id fixed that but maybe its my working copy

**Comment by arkayenro** [comment]
more of a cosmetic thing.  it should still show the location if theres only one, just not the count (as it would be duplicating whats on the left)

![wowscrnshot_062318_144851](https://user-images.githubusercontent.com/11565511/41805870-c6c9bdb6-76f4-11e8-8748-b2cdbf47ff42.jpg)

**Comment by Calesta** [comment]
Thanks for sharing.  Now that I see it with a number of characters listed it's not at all like I first thought it might be.  It does look a bit cleaner with some whitespace between.  

Feel free to close this as it's really a non-issue.  Thanks again for all the hard work!

**Comment by Calesta** [comment]
I was on the Beta again today and found while most tooltips don't have the counts, some do.  Take a look at these two screenshots.

![with count](https://user-images.githubusercontent.com/13042214/41814825-18cab444-7727-11e8-9ad6-ce57ff10e1bb.jpg)

![without counts](https://user-images.githubusercontent.com/13042214/41814826-19bce98a-7727-11e8-95dd-8504c3fd1ed4.jpg)

Hope you can figure out why it happens intermittently.

**Comment by arkayenro** [comment]
found the problem, will be fixed next released
