### ISSUE TITLE
[BfA Beta] ArkInventory_Tracking_Currency 'No Known Currencies'

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1039]
With the latest Alpha (r723-alpha), the currency tracker on my broker bar now shows the text 'Currency' where before it showed the icons / counts of the various currencies I had selected.  When I hover over it, the tooltip says 'No Known Currencies'.  Clicking on it brings up my currency window and I can see War Resources and Seafarer's Dubloons there (although the icons are missing).  

![no currency](https://user-images.githubusercontent.com/13042214/42358657-b9c49b2a-80ab-11e8-83e7-80b2b01f93da.jpg)

I tried reloading the UI and it had no effect.

After reloading I also saw the following with the broker-based components ...

* Money tracker display changed.  It shows the text 'Money' instead of the gold / silver / copper icons / counts as before although when I hover over it, I see the amount of money on each character.

* The Reputation tracker display changed.  It showed no reputations when I hovered over it.  Opening the Reputation pane seems to have done something as the tooltip now displays the correct values.

* The mount display showed no selected mounts and didn't show any mounts.  A red error appeared when I hovered over it saying something akin to 'the journal wasn't available'.  Once I used the mouse shortcut I have setup through ArkInventory to mount, my selections returned.

**Comment by Calesta** [comment]
I was questing for about 20 minutes looked down and... currencies!  All the broker-based components are back to what they looked like before?  Is there some serious back-end stuff in the latest version that causes all of that stuff to recalculate and display?

**Comment by arkayenro** [comment]
server lag will leave them at their initialising state until something happens to trigger an update (like closing the reputation/pet/mount window)

i've changed the initial text for all the ldb objects to loading...  so its a bit more obvious

also fixed an issue with the mount object

i may have to add a timer to continually check their state and keep trying until they get past init

**Comment by arkayenro** [comment]
the empty icons typically means there was no data when i queried the server, so youre basically running on what was stored from the previous session

ie it knows you had those two currencies before, it just hasnt been told anything about those currencies yet so it cant display them properly

**Comment by Calesta** [comment]
I saw the 'Loading' messages the first few times, but with the latest Beta build I haven't.  Everything just loads as I'm used to seeing it in the broker bar.  Thanks!
