### ISSUE TITLE
LibSharedMedia error in 8.0

### ISSUE THREAD

**Issue by Eiltherune** [arkayenro/arkinventory#1042]
I tried loading AI as the only addon, also tried completely deleting and reinstalling AI, but I'm still getting these errors:

<pre>Message: ..\AddOns\ArkInventory\ArkInventoryConst.lua line 22:
   Cannot find a library instance of "LibSharedMedia-3.0".
Debug:
   [C]: error()
   !Swatter\Support\LibStub.lua:23: LibStub()
   ArkInventory\ArkInventoryConst.lua:22: in main chunk
Locals:
(*temporary) = "Cannot find a library instance of "LibSharedMedia-3.0"."
</pre>

This one is appearing for EVERY ArkInventory "Collection" lua file:
<pre>
Message: ..\AddOns\ArkInventory\ArkInventory.lua line 22:
   attempt to index field 'Const' (a nil value)
Debug:
   ArkInventory\ArkInventory.lua:22: in main chunk
</pre>

<pre>Message: ..\AddOns\ArkInventory\Locale\game.lua line 259:
   attempt to index field '?' (a nil value)
Debug:
   ArkInventory\Locale\game.lua:259: in main chunk
Locals:
L = <table> {
}
FormatForRegex = <function> defined @Interface\AddOns\ArkInventory\Locale\game.lua:202
FormatForCapture = <function> defined @Interface\AddOns\ArkInventory\Locale\game.lua:214
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = "WOW_ITEM_CLASS_WEAPON"
(*temporary) = nil
(*temporary) = "ItemClass"
(*temporary) = 132144
(*temporary) = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = 783
(*temporary) = "%+%d Item Levels"
(*temporary) = 0
(*temporary) = "attempt to index field '?' (a nil value)"

</pre>

**Comment by arkayenro** [comment]
do you use the no-lib version?

check the arkinventory\externals directory, make sure there is a sharedmedia folder in there

once you get a library error youll get hundreds of errors after it as the code cant work without them, just the first one is important
