### ISSUE TITLE
8.0.1 Error

### ISSUE THREAD

**Issue by AerriSylvanmist** [arkayenro/arkinventory#1043]
Hi, love your addon, I have been using it for years.  :)  Getting a strange error today whenever I open a merchant/vendor.  I disabled all other addons and still get the below error.

Message: Interface\AddOns\ArkInventory\ArkInventory.lua:11012: Interface\AddOns\ArkInventory\ArkInventoryLDB.lua:211: bad argument #2 to 'format' (string expected, got nil)
Time: Wed Jul 18 15:01:00 2018
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventory.lua:11012: Interface\AddOns\ArkInventory\ArkInventoryLDB.lua:211: bad argument #2 to 'format' (string expected, got nil)
[C]: ?
Interface\AddOns\ArkInventory\ArkInventory.lua:11012: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: (*temporary) = "Interface\AddOns\ArkInventory\ArkInventoryLDB.lua:211: bad argument #2 to 'format' (string expected, got nil)"

**Comment by arkayenro** [comment]
which reputation have you set to be watched?

i can add some extra logic around the display but in the mean time you can unwatch that rep or disable the reputation ldb object in your broker mod

**Comment by AerriSylvanmist** [comment]
Ahh, I hadn't noticed that rep bar wasn't working properly.  Thank you.  

It is the Anglers rep from Panderia.  I will unwatch tomorrow and see if that fixes the issue.

thanks for the response.

⁣Sent from TypeApp ​

**Comment by arkayenro** [comment]
ah, you can watch a header rep, i hadnt noticed - those have no data stored so it returned nil.

**Comment by arkayenro** [comment]
will be fixed next release

**Comment by arkayenro** [comment]
try the 737 alpha version and see if that fixes it or not

**Comment by ashkashlitwin** [comment]
Alpha version no longer throwing this error so far, for me. Tracking Bilgewater Cartel rep, which was throwing an error prior to alpha version 737.

**Comment by AerriSylvanmist** [comment]
Hi, I installed version r740 alpha today and gave it a try.  It doesn’t seem to be throwing the error anymore when I turn the rep monitoring back on and track the Anglers.

 

However it did give the following error message in the chat window on load:

 

ERROR> interface\AddOns\ArkInventory\ArkInventoryLDB.lua:211: attempt to index field ‘style’ (a number value)

 

b.

**Comment by arkayenro** [comment]
try the 741 alpha, should be fixed in there

**Comment by arkayenro** [comment]
fixed in 3.08.05
