### ISSUE TITLE
tsmgroup() rule throws error in 3.08.02

### ISSUE THREAD

**Issue by keramond** [arkayenro/arkinventory#1048]
Hello,

the tsmgroup() rule throws an error since last update 3.08.02. Bags can't be opened with this. It worked in the prior version in WoW 8.0.1.

> 11:22] ArkInventory: ERROR> [string "return( tsmgroup("Warlords of Draenor->Trad..."]:1: attempt to call global 'tsmgroup' (a nil value) 
> [11:22] ArkInventory: WARNING> Rule 1009 is now flagged as damaged and will no longer be used until repaired 
> [11:22] ArkInventory: ERROR> ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:219: [string "return( tsmgroup("Warlords of Draenor->Trad..."]:1: attempt to call global 'tsmgroup' (a nil value)

**Comment by arkayenro** [comment]
will be fixed next release

**Comment by keramond** [comment]
thank you for your your work! I can't live without this addon :)

**Comment by arkayenro** [comment]
fixed in 3.08.03
