### ISSUE TITLE
Communities issue

### ISSUE THREAD

**Issue by Talimar** [arkayenro/arkinventory#1052]
If I try to join a community link from chat I get an error saying Arkinventory has been blocked by an action only available to the Blizzard UI.

1x [ADDON_ACTION_FORBIDDEN] AddOn 'ArkInventory' tried to call the protected function 'RedeemTicket()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `RedeemTicket'
...\Blizzard_Communities\CommunitiesInvitationFrame.lua:162: in function `AcceptTicket'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>

Locals:
nil

**Comment by arkayenro** [comment]
ai does not touch any of the communities functions

disable ai and try again, it will pick another mod to blame

**Comment by arkayenro** [comment]
if you have a chat mod, like prat, then make sure its up to date
