### ISSUE TITLE
Rules not showing up 

### ISSUE THREAD

**Issue by johannesveje** [arkayenro/arkinventory#1053]
I just started using the addon and I get no rules showing evn though they are registered when I log in 
[https://i.imgur.com/lMyi3LS.png](url)
[https://i.imgur.com/GfvUiKd.png](url)
Any idea why?

I have tried to disable everything else, but it does not change anything.

**Comment by arkayenro** [comment]
those are rule functions, not rules themselves, and you dont need to load the example rules addon (thats for other authors to use as a base)

in the rules window click on the Add button if you want to add a rule

**Comment by johannesveje** [comment]
Thanks for the response, I misunderstod it.
