### ISSUE TITLE
Battle-Training Stones changed default category

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1054]
In r735, Battle-Training stones are in Consumables -> Other by default, while they were in System -> Soulbound before.
Can we have them back to where they were please? Or at least some other "other" category so I wouldn't have to reassign all of them one by one to move out of the bar dedicated to flasks/potions/etc ?
Thanks in advance. :)

(Yes I know I could define a rule for it but rules consume resources and slow loading of the bag windows down and this category seems to be a little off for these items.)

**Comment by arkayenro** [comment]
fixed/changed in 3.08.04 (currently alpha)

some items are still soulbound as they have companion pet, not battle pet, in the tooltip, mostly the vanity items, and theres no global for companion pet that i can find
