### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by dmsmith111** [arkayenro/arkinventory#1055]
Getting the below error since the last update:

20x ArkInventory\ArkInventory-30803.lua:11023: ...ns\ArkInventory\ArkInventoryCollectionReputation.lua:330: attempt to index field '?' (a nil value)
[C]: ?
ArkInventory\ArkInventory-30803.lua:11023: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = "...ns\ArkInventory\ArkInventoryCollectionReputation.lua:330: attempt to index field '?' (a nil value)"

**Comment by arkayenro** [comment]
try the 737 alpha version and see if that fixes it or not

**Comment by Idraelia** [comment]
I tryed the 737 but still having error :  ArkInventory: ERREUR> ...ns\ArkInventory\ArkInventoryCollectionReputation.lua:332: attempt to index field '?' (a nil value)

**Comment by Idraelia** [comment]
Perfect thank you :)
