### ISSUE TITLE
Stack & Reorder not using material storage

### ISSUE THREAD

**Issue by Bachsau** [arkayenro/arkinventory#1057]
When running stack & reorder on the bank, ArkInventory does not move mats to material storage, so they keep occupying bag space.

**Comment by Bachsau** [comment]
I didn't know I could right click on that icon. It works, but is not the desired behavior, because if I run the function on my bank it should only restack my bank in the most efficient way. But enabling those options also results in all the reagents in my bags being moved to the bank, which is not always desired.

**Comment by arkayenro** [comment]
close the bag window when at the bank, then restack.

i think i wrote it to not do those bits if the bag wasnt open

**Comment by arkayenro** [comment]
the 759 alpha includes fixes for the reagent bank to topup and move items from the bank

**Comment by arkayenro** [comment]
fixed in 3.08.09
