### ISSUE TITLE
Backpack type is unknown

### ISSUE THREAD

**Issue by dramallamabonanza** [arkayenro/arkinventory#1060]
ArkInventory: WARNING> bag [1] [1.2] [Backpack] type is unknown, queuing for rescan

I think perhaps the recent change to the Backpack to make it 20 slots is causing this?

**Comment by arkayenro** [comment]
no, its just a lag issue

you can turn that warning message off int he config if it becomes too annoying

**Comment by dramallamabonanza** [comment]
Thanks mate. Issue fixed.
