### ISSUE TITLE
Problem with the bottom padding between bars and window border

### ISSUE THREAD

**Issue by Draugor** [arkayenro/arkinventory#1062]
Hello,

i setup the anchor point of my bars to be in the bottom right of the ArkInventory window, but with this setting the padding from the bottom window border somehow is reduced. see screenshots:

Bottom Left anchor correct padding:
![padding_anchorpoint_botleft](https://user-images.githubusercontent.com/6240419/43334049-872966f0-91cc-11e8-949c-5b7b45ea6719.png)

Bottom Right anchor reduced padding to bottom border
![padding_anchorpoint_botright](https://user-images.githubusercontent.com/6240419/43334035-7ba2d28a-91cc-11e8-9e1f-45c931e00401.png)

cheers!

**Comment by arkayenro** [comment]
can you export your design and paste it into here, i'll import it and see if it happens on mine or not

**Comment by arkayenro** [comment]
could you also set all your borders to arkinventory - square 1 as i cant see any in the screenshot

**Comment by Draugor** [comment]
borders are already set to arkinventory square 1 :D but they're color-wise close to the background+a bit transparent so that may be why.

Exportstring: ^1^T^Sdesign^T^Sslot^T^Stransmogicon^T^Salternative^b^t^Sborder^T^Soffset^N3^Sstyle^SArkInventory~`Square~`1^Sscale^N1.2^Ssize^N16^t^Sempty^T^Sborder^b^Sicon^b^t^Sitemlevel^T^Sshow^B^Sfont^T^Sheight^N15^t^t^Sitemcount^T^Sfont^T^Sheight^N14^t^t^Sage^T^Scutoff^N120^t^Sdata^T^N1^T^Scolour^T^Sa^N1^Sb^N0.102^Sg^N0.102^Sr^N0.102^t^t^N0^T^Scolour^T^Sa^N1^t^t^N27^T^Scolour^T^Sa^N1^t^t^N15^T^Scolour^T^Sa^N1^t^t^N20^T^Scolour^T^Sa^N1^t^t^N14^T^Scolour^T^Sa^N1^t^t^t^Scooldown^T^Sglobal^B^t^t^Schanger^T^Shide^B^t^Swindow^T^Spad^N11^Sbackground^T^Scolour^T^Sa^N0.63^Sb^N0.102^Sg^N0.102^Sr^N0.102^t^t^Sborder^T^Soffset^N0^Sstyle^SArkInventory~`Square~`1^Ssize^N16^Scolour^T^Sb^N0.102^Sg^N0.102^Sr^N0.102^t^t^Swidth^N14^t^Stitle^T^Shide^B^Sfont^T^Sheight^N13^t^t^Ssearch^T^Sfont^T^Sheight^N15^t^t^Ssort^T^Smethod^N9998^Swhen^N1^t^Scategory^T^S1!445^N2^S1!412^N9^S1!431^N13^S1!405^N8^S1!512^N9^S1!415^N2^S1!501^N9^S1!414^N12^S1!401^N1^S1!308^N6^S1!416^N12^S1!503^N9^S1!423^N2^S1!513^N9^S1!438^N14^S1!502^N9^S1!506^N6^S1!504^N9^S1!505^N9^S1!402^N15^S1!443^N2^S1!428^N7^S1!441^N2^S1!442^N2^S1!444^N12^S1!408^N9^S1!427^N9^S1!409^N9^t^Sstatus^T^Semptytext^T^Sincludetype^b^t^t^Sused^SY^Sname^SBergbauJuwe^Sbar^T^Sper^N4^Sdata^T^N1^T^Sname^T^Stext^SGeneral^t^Swidth^T^Smax^N14^t^t^N2^T^Sname^T^Stext^SMounts/Pets^t^t^N5^T^Sname^T^Stext^SHearthstone^t^t^N6^T^Sname^T^Stext^SMining~`Stuff^t^t^N7^T^Sname^T^Stext^SReputation^t^t^N8^T^Sname^T^Stext^STokens^t^Swidth^T^Smax^N13^t^t^N9^T^Sname^T^Stext^SMats^t^t^N10^T^Sname^T^Stext^SChampion~`Equip^t^t^N11^T^Sname^T^Stext^SWeapons^t^t^N12^T^Sname^T^Stext^SArmor^t^Ssort^T^Smethod^N9999^t^t^N13^T^Sname^T^Stext^SBuffs^t^t^N14^T^Sname^T^Stext^SCurrency^t^t^N15^T^Sname^T^Stext^STrash^t^t^t^Spad^T^Sexternal^N0^Sinternal^N4^t^Sname^T^Sshow^B^Sheight^N12^t^Sborder^T^Soffset^N3^Sstyle^SArkInventory~`Square~`1^Ssize^N16^Scolour^T^Sb^N0.102^Sg^N0.102^Sr^N0.102^t^t^Sbackground^T^Scolour^T^Sa^N0.06^t^t^t^t^Scat^T^t^Ssort^T^t^t^^

**Comment by arkayenro** [comment]
looks like a combination of bad offsets and the wrong height set for the mini action buttons

should be fixed in the next release

**Comment by arkayenro** [comment]
found some other issues with the layout that should also be fixed next release

**Comment by arkayenro** [comment]
fixed in 3.08.08
