### ISSUE TITLE
TSM4 - ArkInventory conflict. 

### ISSUE THREAD

**Issue by shawnyve** [arkayenro/arkinventory#1063]
I've posted this up for TSM4 devs as well as here to cover the bases. If it is alright, I'll post the link to the pastebin for all the details and errors. Let me know if you need anything else.

https://pastebin.com/AxjMVnJR

**Comment by arkayenro** [comment]
did you have the AI mail window open at the time?

**Comment by shawnyve** [comment]
Yes. I cannot find a way to disable the AI mail window. Both the AI and TSM windows open every time I hit a mailbox.

Sent from Mail for Windows 10

**Comment by arkayenro** [comment]
have a  look under config > controls > mail

the override tab is greyed out because the AI mail interface hasnt been finished.  you can open it manually though but not automatically

im not sure what youre seeing when you open the mailbox but its not the AI mail window

do you mean the AI bag window?  in which case you can stop that from config  > general > auto open/close

**Comment by arkayenro** [comment]
so the actual blizzard mailbox is opening, well at least that makes more sense.

i'll need to check how TSM is doing it as were possibly doing the same thing

**Comment by shawnyve** [comment]
Yes. That’s it. I’m sorry. Meant to get back to you yesterday with a screenshot of what was going on.

Also, the same thing happens on shops, both reg ui and tsm shopui open BUT no errors come up. Maybe that will give a hint as to what is causing the error at least. If you do need more screenshots or info just let me know. I could send you my saved variable files etc.

Thanks for the attention to this. Love both addons!

Sent from Mail for Windows 10

**Comment by arkayenro** [comment]
mailbox and merchant use the same sort of code so it makes sense they would both cause issues.

both TSM and AI listen for the MAIL_SHOW event, i just pass it through because at this time i only need to check if the bag was open before the mailbox gets opened.

a quick fix i might be able to add another option that you can untick that will stop if from passing on that message tot he blizzard frame.  that way if you have TSM installed you can untick it and let TSM handle it

**Comment by arkayenro** [comment]
ive added some global options for this but it would be better if TSM provided access to these states via their API

**Comment by fubaBfA** [comment]
ok i'll try to report it to the TSM team too.

**Comment by fubaBfA** [comment]
As usual the TSM Team does not care anything...  
But the main thing is they have a Premium Feature ;)  

Anyways...  
It seems your workaround sometimes prevents that the TSM4 Mailing Frame does not update and just show the number of Mails but Open them is not possible anymore. :(

**Comment by arkayenro** [comment]
has TSM always been able to override the mailbox or is this new?

just trying to work out if they changed something as my code has always been the way it is for the mailbox and merchant

**Comment by Fraktyl** [comment]
Yeah, TSM4 has redone how they interact.  They don't add a tab to the mailbox anymore.  It's a completely separate window.

**Comment by fubaBfA** [comment]
> where can i find the workaround? since release of tsm4 the mailbox opens no longer the blizzard ui so arkinventory breaks all mail interaction in tsm4, not sure why tho

yeah it is very bad :(
I also like both AddOns very much and hopefully the TSM Team will care as soon as possible.

**Comment by fubaBfA** [comment]
dude please remove the "workaround" becasue TSM mailing is **completely**broken now.
I really love your AddOn but i can not use it until this is working again :(

**Comment by sparrowlab** [comment]
Came here to post about this — as of the latest update, sending or receiving mail is not possible with arkinventory and TSM enabled.

**Comment by arkayenro** [comment]
"dude" - there is no workaround released yet.  i said i wold add one next release but i've ben busy fixing other things.

if TSM is broken even worse then go see TSM

**Comment by arkayenro** [comment]
i think i found an actual fix so we'll see if it actually works

let me know if the 752 alpha has issues with tsm or not

**Comment by fubaBfA** [comment]
> if TSM is broken even worse then go see TSM

yeah i tried but... they dont care :(

> i think i found an actual fix so we'll see if it actually works
let me know if the 752 alpha has issues with tsm or not

It looks like it works! 👍
I will do some more tests but...
***Thank you very much***
It was damn hard to play without ArkInventory for just **one** day :P

**Comment by thehumandistraction** [comment]
I just wanted to chime in and confirm that the latest alpha has fixed the conflict between the two addons.  

Thanks a lot @arkayenro for taking the time to fix this and for the awesome work you do on this addon! 🎉

**Comment by sparrowlab** [comment]
Working now — thanks so much!
