### ISSUE TITLE
TSM4 ArkinventoryRules again (3.08.05)

### ISSUE THREAD

**Issue by keramond** [arkayenro/arkinventory#1064]
Hello, 

TSM4 update yesterday broke the Rules again.

```
6x ArkInventory\ArkInventory-30805.lua:11167: ...rfaceArkInventoryRules\ArkInventoryRules-10200.lua:219: ...rfaceArkInventoryRules\ArkInventoryRules.lua:1497: attempt to index field 'Item' (a nil value)
[C]: ?
ArkInventory\ArkInventory-30805.lua:11167: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = "...rfaceArkInventoryRules\ArkInventoryRules.lua:219: ...rfaceArkInventoryRules\ArkInventoryRules.lua:1497: attempt to index field 'Item' (a nil value)
```"

**Comment by arkayenro** [comment]
odd, their API code still has TSMAPI.Item so not sure how it can be nil unless something wiped it out?

if that is happening then there should be more reports on their web site about the issue

I dont think i can fix this as the issue doesnt appear to be on my side that i can see

youve tried with just TSM and AI enabled?

**Comment by arkayenro** [comment]
also, with just TSM loaded type in chat /dump TSMAPI.Item and see if theres any output

**Comment by keramond** [comment]
disabled all but arkinventory and tsm+apphelper

result of dump was:

> Dump: value=TSMAPI.Item
> empty result

**Comment by keramond** [comment]
not sure if it helps but in tsm changelog ([http://support.tradeskillmaster.com/display/KB/TSM4+Beta+Changelog](url)) 
they wrote something about added APIs, now there is an aditional API with "_" (TSM_API)

**Comment by arkayenro** [comment]
ok, i see, they made their entire addon use the private table so its inaccessible.

that would be nice but there is no TSM_API variable in their code at all, its still their issue

**Comment by arkayenro** [comment]
nvm, i must have downloaded the current version, not the beta.  at least i hope thats why its not in there

**Comment by arkayenro** [comment]
i will need to replace the following functions

tsm_itemstring = TSMAPI.Item:ToItemString( hyperlink )
tsm_itemstring = TSMAPI.Item:ToBaseItemString( hyperlink )
group = TSMAPI.Groups:FormatPath( TSMAPI.Groups:GetPath( tsm_itemstring ) )

once the code is released i can look through it to see whats available, i can also enbale it to at least make sure that there arent any errors with it

from the change logs i think it might be something along these lines

group = TSM_API.FormatGroupPath( TSM_API.GetGroupPathByItem( item ) )

presuming that item is an item hyperlink or itemstring

might have to remove the base item string check if its not available

**Comment by keramond** [comment]
hey i did a pastebin of the API file.
[TSM_API](https://pastebin.com/rAfYskNF) (all rights to TSM developers)

**Comment by arkayenro** [comment]
see if r745-alpha works with TSM4

**Comment by keramond** [comment]
still persists in r745

**Comment by SLOKnightfall** [comment]
To fix the api calls listed above for TSM4 it looks like you need to change the calls from TSMAPI to   TSMAPI_FOUR

**Comment by keramond** [comment]
yeah but sapu the author of tsm said in discord that tsmapi and tsmapi_four are getting removed. tsm_api will the right place to go

**Comment by arkayenro** [comment]
try r746-alpha see if that works - if theres an error please post it

**Comment by Everspace** [comment]
r746 is still giving it to me with the launch of TSM 4: using a rule like `tsm("boa drops")`

```
Date: 2018-07-28 17:45:51
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ArkInventory\ArkInventory.lua line 11167:
   ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua line 219:
   ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua line 1600:
   attempt to index field 'Item' (a nil value)
Debug:
   [C]: ?
   [C]: ?
   ArkInventory\ArkInventory.lua:11167: ThreadResume()
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1
Locals:

AddOns:
  Swatter, v7.3.1 (<%codename%>)
  Ace3, v
  AddonLoader, v2.0.1
  ArkInventory, v30805
  ArkInventoryRules, v10200
  ArkInventorySearch, v10200
  Bartender4, v4.8.1
  BrokerCurrency, v8.0.1.3
  CanIMogIt, v8.0.0v1.9
  ColorPickerPlus, v
  DBMCore, v8.0.1
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  HandyNotes, vv1.5.2
  idTip, v8.0.0
  LibIconPath, v1.6
  MoveAnything, v17.0.0
  NomiCakes, v8.0.0.1
  NugComboBar, v8.0.1
  OmniCC, v8.0.1
  Outfitter, v5.20.3
  Pawn, v2.2.22
  ProspectMe, v2.7.2.0
  Quartz, v3.4.0
  ShadowedUFSmoothBars, vv1.2.2
  ShadowedUnitFrames, vv4.2.1
  Skada, v1.7.3
  SlideBar, v7.3.1 (<%codename%>)
  SPTimers, v3.12.0
  Titan, v5.14.1.80000
  TitanBag, v5.14.1.80000
  TitanClock, v5.14.1.80000
  TitanCurrency, v7.3.5.a
  TitanGold, v5.14.1.80000
  TitanLootType, v5.14.1.80000
  TitanRepair, v5.14.1.80000
  TitanVolume, v5.14.1.80000
  TitanXP, v5.14.1.80000
  TomTom, vv80001-1.0.1
  TradeSkillMaster, vv4.0
  TradeSkillMasterAppHelper, vv4.0
  TransmogTokens, v1.4.9
  WeakAuras, v2.6.5
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=443)
```

**Comment by Everspace** [comment]
Dumping TSM_API reveals the following:

```
TSM_API={
GetGroupPaths=<function>
IsUIVisible=<function>
FormatGroupPath=<function>
GetGroupPathByItem=<function>
SplitGroupPath=<function>
}
```

**Comment by Everspace** [comment]
I am a goober, I thought I had updated.

**Comment by keramond** [comment]
arkayenro you can close that issue, you successfuly neutralized this issue!
Thanks for you work, as always.
