### ISSUE TITLE
Keeps giving me this error message on login, repeats until ArkInventory aborts

### ISSUE THREAD

**Issue by Pookah** [arkayenro/arkinventory#1065]
...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:323: attempt to index field 'db' (a nil value)
Time: Sat Jul 28 11:45:41 2018
Count: 7
Stack: ...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:323: attempt to index field 'db' (a nil value)
[C]: ?
...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:323: in function <...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:303>

[EDIT: error persists even when AI (and its dependencies) is the only addon loaded.]

**Comment by arkayenro** [comment]
that typically the result of an another error.  did you receive any other errors before this one?

**Comment by Pookah** [comment]
Yes:
Message: Interface\AddOns\ArkInventory\ArkInventoryRealms.lua:45: attempt to index global 'ArkInventory' (a nil value)
Time: Sat Jul 28 19:39:56 2018
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventoryRealms.lua:45: attempt to index global 'ArkInventory' (a nil value)
Interface\AddOns\ArkInventory\ArkInventoryRealms.lua:45: in main chunk

Locals: portal = "US"
ConnectedRealms = <table> {
}
addRealms = <function> defined @Interface\AddOns\ArkInventory\ArkInventoryRealms.lua:5
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'ArkInventory' (a nil value)"
==============

Also:

Message: ...ace\AddOns\ArkInventory\ArkInventoryStaticPopups.lua:10: attempt to index global 'ArkInventory' (a nil value)
Time: Sat Jul 28 19:39:55 2018
Count: 1
Stack: ...ace\AddOns\ArkInventory\ArkInventoryStaticPopups.lua:10: attempt to index global 'ArkInventory' (a nil value)
...ace\AddOns\ArkInventory\ArkInventoryStaticPopups.lua:10: in main chunk
===========
Also:
Message: Interface\AddOns\ArkInventory\ArkInventoryLDB.lua:12: attempt to index global 'ArkInventory' (a nil value)
Time: Sat Jul 28 19:39:55 2018
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventoryLDB.lua:12: attempt to index global 'ArkInventory' (a nil value)
Interface\AddOns\ArkInventory\ArkInventoryLDB.lua:12: in main chunk

And so on. All told, it gave me 137 separate errors upon login, each one relating to a different part of the ArkInventory lua.

**Comment by Pookah** [comment]
Sorry about the different font-sizes. I have no idea why it did that.

**Comment by Pookah** [comment]
One thing I'm noticing is that each error says "attempt to index global 'ArkInventory' (a nil value)"

**Comment by arkayenro** [comment]
yeah, that typically means it barfed really really early into the load process

can you re-install arkinventory with the game closed.  its possible the files have become corrupted

**Comment by Pookah** [comment]
Will do!

**Comment by Pookah** [comment]
Okay, that did the trick! Everything seems to be working a-okay now. Thanks, mate!
