### ISSUE TITLE
Settings Reset after Update v3.08.06

### ISSUE THREAD

**Issue by fubaBfA** [arkayenro/arkinventory#1068]
hi,

**all** my settings are resetted after installed the last Update v3.08.06!
Revert an old Settimgs file work until Re-Log or Reload the UI, after all Settings are resetted again...

**Comment by arkayenro** [comment]
the default profile is getting reset.  your data is still there its just not being assigned.

i've deleted the current version and it will get fixed next version

in the mean time you can create a new profile and use that.  you will need to set the blueprint options for each window but once you do that it should be fine

**Comment by arkayenro** [comment]
fixed in 3.08.07

**Comment by fubaBfA** [comment]
hmm, but it is not fixed in 3.08.08
but it's not that bad
everything is still there and i've created my own profile now ^^
