### ISSUE TITLE
Laggy Opening after 8.0.1

### ISSUE THREAD

**Issue by sciamatic** [arkayenro/arkinventory#1070]
Since 8.0.1, when I hit 'b', my bag opens about a second later.  The lag isn't *huge*, but it's enough to be noticed.  I don't get a LUA error, so I don't have anything to post, but I didn't have any problems before 8.0.1, only since then.

Thanks so much for all your hard work!  Your addon is the one addon I absolutely cannot live without!

**Comment by eunikitin** [comment]
Same for me, I use default settings. Also I noticed that the time increasing with the inventory size. When I open my bank, delay is much longer (about 3 - 5 seconds) then when i open my inventory (1 - 1.5 second). I turned off my other addons - didn't work. ElvUI bags and bagnon don't have any delay. I also tried older versions of ArkInventory (3.08.01, 3.07.43, 3.07.39) and they also have this delay, but for 3.07.43 and 3.07.39 it seems a bit shorter, but maybe I'm wrong.

Hope this will be useful. I've been using your addon for years.

**Comment by sciamatic** [comment]
Every time I open the bags/bank, not just the first opening, and the sorting is set to 'on-open.'

I hope this helps!  The lag is still happening, and as eunikitin said, it's more intense with the bank than the bag.  Thank you so much!

**Comment by bearlygeek** [comment]
I have this same issue, it drives me mad. Even on my absolute beast of a gaming rig, opening my bags = 5-10fps drop and a moment of the game lagging.

At first I thought it was elvui's Addonskins causing the problem, it isn't. No idea what it is.

Opening the guild bank, or my own bank causes it too.

Elvui's own bag system, nor bagon have the issue. I refuse to use either of those solutions for bags because their both awful and ugly.

**Comment by arkayenro** [comment]
check your profile, make sure you have non default blueprint settings - the system default is set to instant sort so it would kick in if you did.

you can get this if you deleted a design at some point and never changed the profile.  i used to display the name of the deleted design so it wasnt obvious it was no longer being used and had reverted to the default

the later versions no longer do this and just show "default" if its set to a deleted design

**Comment by arkayenro** [comment]
also, make sure youve set the sorting to manual in the design assigned to your location having the issue

**Comment by bearlygeek** [comment]
I'm not entirely sure what you mean about non default blueprint in config/controls. I made a new profile and it made no difference. So I completely uninstalled the addon and deleted all the files for it, and it's still doing it :\

**Comment by eunikitin** [comment]
With new 3.08.10 version the issue seems to be solved for me - when I open bags or bank for the first time it has a little lag, but after that it opens without any delay. Thank you for your work @arkayenro!

**Comment by arkayenro** [comment]
do the borders show the corners, but not the sides?  and the icons dont show for a while either?

i get that sometimes but i also have the game ui not drawing either, eg the mailbox is completely unskinned, the minimap has no background, world maps are empty for a couple of seconds, etc, etc

theres that issue, and i think it be causing something funky in the threaded frame draw but i need to do some more testing to see if my code thinks its finished, or if its still going

**Comment by arkayenro** [comment]
can you try it with just arkinv running?

**Comment by bearlygeek** [comment]
There wasn't any difference with all my other addons off. I disabled the
rules part of ark and it helped slightly (i don't use any rules anyway).

Will run a scan/repair on the game itself and see if there is something
amiss there too.
