### ISSUE TITLE
Tooltip error

### ISSUE THREAD

**Issue by halfreak** [arkayenro/arkinventory#1072]
Hello! There's a tooltip error when hovering over item links or other "virtual" items in other addons. I've tested it with TradeSkillMaster and All The Things on a completely clean WoW install and it is consistent. I've also experienced it when hovering over item links in Prat 3.0. Here are the logs from BugGrabber and Swatter. I hope it can be fixed. Thank you for this beautiful addon and have a good day!

[AI_TSM_BGBS.txt](https://github.com/arkayenro/arkinventory/files/2259030/AI_TSM_BGBS.txt)
[AI_TSM_Swat.txt](https://github.com/arkayenro/arkinventory/files/2259031/AI_TSM_Swat.txt)

**Comment by arkayenro** [comment]
what version are you running?

i thought i broke it in one of 3.08.08 alphas but its fixed in the later ones

**Comment by halfreak** [comment]
Oh, sorry, forgot to mention, it's r754-alpha

**Comment by mabnp** [comment]
Happens in version: r755-alpha.
Did not happen in r753-alpha.

**Comment by arkayenro** [comment]
definitely ownerless tooltips as i fixed that line and its working in my local version

will be in the next alpha/release

**Comment by halfreak** [comment]
Fixed in the latest r756-alpha. Thanks, @arkayenro, you rock! Closing this one.
