### ISSUE TITLE
Error Version r756-Alpha

### ISSUE THREAD

**Issue by Dephi73** [arkayenro/arkinventory#1075]
Hello I get this error

51x ArkInventory\ArkInventoryTooltip.lua:1721: attempt to index local 'owner' (a nil value)
ArkInventory\ArkInventoryTooltip.lua:1721: in function `TooltipAddOnUpdate'
ArkInventory\ArkInventoryTooltip.lua:1263: in function <ArkInventory\ArkInventoryTooltip.lua:1247>
[C]: ?

Locals:
InCombatSkipped

**Comment by arkayenro** [comment]
i cant get it to fail, what were you doing at the time?

**Comment by arkayenro** [comment]
fixed in 3.08.08
