### ISSUE TITLE
Custom Sort, Copy From, copies wipeonreload attribute

### ISSUE THREAD

**Issue by RussLeeIV** [arkayenro/arkinventory#1076]
After creating a custom sort and using a default as the base, the wipeonreload attribute is copied from the default and the sort is lost after reload.

1. Create a new Custom Sort
2. Copy From a default sort, i.e. one of the 999#.
3. Modify the Custom Sort to be different from the default.
4. Reload UI
5. Notice the Custom Sort is now gone.

There is no setting in the UI to clear this flag that I can find.

**Comment by arkayenro** [comment]
will be fixed next alpha/release

**Comment by arkayenro** [comment]
fixed in 3.08.08

**Comment by RussLeeIV** [comment]
I just updated and tested confirming that this is fixed.
Thank you and well done.
