### ISSUE TITLE
Back/Cloak Rule

### ISSUE THREAD

**Issue by BaturalNoobs** [arkayenro/arkinventory#1077]
I'm having trouble creating a back/cloak rule. I've tried:
- `equip( "back" )`
- `equip( "cloak" )`
- `type( "armor") and subtype( "back" )`
- `type( "armor") and subtype( "cloak" )`

Each of these rules are enabled.

When I try to apply any of the above rules to a bar my cloaks are not added to that bar.

Any ideas how to get this rule working?

v.3.08.07

Thank you!

**Comment by arkayenro** [comment]
go into edit mode and click on a back item
does it say its assigned to the correct rule or not?

on a bar, if you go to assign the rule doe sit say its enabled in there?  creating a rule is not enough to enable it

**Comment by BaturalNoobs** [comment]
https://imgur.com/a/LB7uuaD

**Comment by BaturalNoobs** [comment]
It says it's assigned to my Soulbound Cloth rule:
type( "armor") and subtype( "cloth" ) and equip( ) and soulbound( )

**Comment by BaturalNoobs** [comment]
@arkayenro that fixed it - thank you!

Keep up the great work on your amazing addon!
