### ISSUE TITLE
3.08.08 opens wrong bank tabs

### ISSUE THREAD

**Issue by speedwaystar** [arkayenro/arkinventory#1078]
click on a bank tab X. notice that it's display tab Y.
click on a different bank tab Z. notice that it's now displaying tab X.

the first bank tab clicked on appears to be the one you wanted+1
the next bank tab you click on consistently displays the one you wanted on the previous click.

tested with Arkinventory as sole loaded addon.

going back though the versions, the issue first appears in r-752 alpha and all subsequent updates.

rolling back to 3.08.07 for now.

**Comment by ImmortalPony** [comment]
Confirm.

**Comment by arkayenro** [comment]
i think its more of a data lag issue.  do you get the right data if you click on the refresh icon?

**Comment by arkayenro** [comment]
found a few other issues with the vault, especially the updating, should be fixed and much better in the next release

**Comment by arkayenro** [comment]
fixed in 3.08.10
