### ISSUE TITLE
constant tooltip errors and disappearing tooltips

### ISSUE THREAD

**Issue by Xvs87** [arkayenro/arkinventory#1079]
Message: ...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:1701: Usage: GameTooltip:SetUnit("unit"[, hideStatus])
Time: Sun Aug  5 21:48:50 2018
Count: 36
Stack: ...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:1701: Usage: GameTooltip:SetUnit("unit"[, hideStatus])
...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:614: in function <...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:571>
[C]: ?
[C]: in function `?'
...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:1701: in function `UpdateTooltip'
Interface\FrameXML\GameTooltip.lua:500: in function <Interface\FrameXML\GameTooltip.lua:477>
[C]: ?
[C]: ?

Locals: errMsg = "...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:1701: Usage: GameTooltip:SetUnit("unit"[, hideStatus])"
errorTime = 40724203.234867
tsmErrMsg = nil
notOld = false
oldModule = nil
private = <table> {
 AddonBlockedEvent = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:375
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:105
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:295
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:355
 SantizeErrorReportString = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:383
 errorFrame = <unnamed> {
 }
}
MAX_STACK_DEPTH = 50
TSM = <table> {
}

**Comment by arkayenro** [comment]
disable tsm and tell me it still happens

**Comment by Xvs87** [comment]
So I disabled TSM and it did seem to occur again.

I cannot seem to pinpoint what exactly triggers it, I looted after combat that triggered it once.

Also it occurred once combat was commenced on a boss fight also.

This is the error log I received with TSM disabled.


Message: ...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:1701: Usage: GameTooltip:SetUnit("unit"[, hideStatus])
Time: Sun Aug  5 23:54:06 2018
Count: 11
Stack: ...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:1701: Usage: GameTooltip:SetUnit("unit"[, hideStatus])
[C]: ?
[C]: in function `?'
...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:1701: in function `UpdateTooltip'
Interface\FrameXML\GameTooltip.lua:500: in function <Interface\FrameXML\GameTooltip.lua:477>
[C]: ?
[C]: ?

Locals:

**Comment by Xvs87** [comment]
I can confirm the Tooltip issue inside All the things addon seems to occur when hovering over achievements but not sure if that is a related issue.

**Comment by nalimleinad** [comment]
I have same problem. Using both TSM and Prat. Please fix this issue, so It will be compatible with other addons.

**Comment by Xvs87** [comment]
This guy.... thanks for the valuable input there bud

**Comment by sir-wilhelm** [comment]
I've been getting a similar error at the beginning of old boss fights. I'll try disabling TheUndermineJournal and see if it still happens.
 
``` 
Message: ...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:1701: Usage: GameTooltip:SetUnit("unit"[, hideStatus])
Time: Sun Aug  5 10:01:40 2018
Count: 16
Stack: ...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:1701: Usage: GameTooltip:SetUnit("unit"[, hideStatus])
[C]: in function `?'
...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:1701: in function `UpdateTooltip'
Interface\FrameXML\GameTooltip.lua:500: in function <Interface\FrameXML\GameTooltip.lua:477>

Locals: (*temporary) = GameTooltip {
 0 = <userdata>
 SetCurrencyByID = <function> defined =[C]:-1
 SetText = <function> defined =[C]:-1
 UpdateTooltip = <function> defined @Interface\AddOns\ArkInventory\ArkInventoryTooltip.lua:1682
 default = 1
 SetExistingSocketGem = <function> defined =[C]:-1
 SetHyperlink = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetGuildBankItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetVoidItem = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 comparing = false
 SetQuestRewardSpell = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetQuestLogRewardSpell = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetRecipeReagentItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 ClearLines = <function> defined =[C]:-1
 SetSocketGem = <function> defined =[C]:-1
 ARKTTD = <table> {
 }
 TopOverlay = <unnamed> {
 }
 SetPetAction = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetQuestItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetShapeshift = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetToyByItemID = <function> defined =[C]:-1
 SetQuestLogSpecialItem = <function> defined =[C]:-1
 Show = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
 SetInboxItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetBuybackItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 shoppingTooltips = <table> {
 }
 SetTrainerService = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetMerchantItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetQuestLogItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetBackpackToken = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetTalent = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetTradePlayerItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetRecipeResultItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetSendMailItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetQuestCurrency = <function> defined =[C]:-1
 updateTooltip = 0.2
 SetInventoryItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetMerchantCostItem = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetLootRollItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:402
 SetCurrencyTokenByID = <function> defined =[C]:-1
 SetAuctionSellItem = <function> d 
 ...
 }
 ```

**Comment by sir-wilhelm** [comment]
It did:
```

**Comment by mabnp** [comment]
It happens with all addons except ArkInv disabled (the tooltip disappears after 1s)

**Comment by arkayenro** [comment]
rebuilding all the tooltip code at the moment

you can try disabling the battlepet tooltip options for the moment as those are the setunit related ones, not sure if it will help or not

**Comment by arkayenro** [comment]
try the 759 alpha, should be up shortly, let me know if the tooltips are still broken or not

they work with prat now, but i dont have tsm

**Comment by halfreak** [comment]
r759-alpha works for me in all the previously affected addons. Thanks!

**Comment by Dyonovan** [comment]
Thanks for the quick fix. Just to confirm I was getting the same error with different addons then I have seen in the reports. The fix seemed to work for me too.

Thanks for keeping this must have addon going!
