### ISSUE TITLE
Auto sell does not work for custom trash items

### ISSUE THREAD

**Issue by Bachsau** [arkayenro/arkinventory#1081]
When assigning items to the trash category by hand, ArkIventory does not sell those items to a vendor.

**Comment by arkayenro** [comment]
can you try it with just arkinv running?  i use that method all the time and it works ok

**Comment by Tacti86** [comment]
This seems to be a problem with TSM4. I tried to deactivate the Vendor Operation but only after disabling TSM4 the trash category and autosell works.

**Comment by Bachsau** [comment]
No. The only other AddOns I was using were Mapster and Storyline.

**Comment by arkayenro** [comment]
do the items have the gold coin/junk icon displayed?

**Comment by Tacti86** [comment]
Only when I go to the Edit Mode and check the assigned category. There is autosell enabled. Should the Items itself also have a gold coin/junk icon displayed?

**Comment by arkayenro** [comment]
yes, the junk icon is an indicator of what items AI would sell

**Comment by Tacti86** [comment]
Hmm no Icon on the Items itself
[Imgur](https://i.imgur.com/9sIXMSV.jpg)
[Imgur](https://i.imgur.com/G0ZNCUN.jpg)

**Comment by arkayenro** [comment]
oh, check the item option in the style, make sure the junk icon is enabled

**Comment by Tacti86** [comment]
Ok found the option, now the junk icon displayed, but the autosell still doesn't work
[Imgur](https://i.imgur.com/Un1Emmn.jpg)

**Comment by arkayenro** [comment]
i've got a custom group called auto sell and its working for me so im not sure why yours wouldnt be selling

**Comment by Tacti86** [comment]
As I said before, It works fine as long Tradeskillmaster4 is deactivated ;)

**Comment by arkayenro** [comment]
oh, missed that.  disable the autosell option in TSM then? or disable it in AI and let TSM handle it

**Comment by arkayenro** [comment]
ok, auto sell should work with TSM in the next release

**Comment by arkayenro** [comment]
r766-alpha has the fix in it if you want to test/confirm

**Comment by Tacti86** [comment]
Works like a charm, thank you for your effort ;)

**Comment by Bachsau** [comment]
Now that you mentioned it, I think the rarity cutof was my problem. I did not use a custom category but assigned the item to the default junk category. However, it was a white item and that's why it was not sold. I forgot about that.
