### ISSUE TITLE
Item-Tooltips in other Addons disappear because of item count

### ISSUE THREAD

**Issue by samot1** [arkayenro/arkinventory#1082]
When I move the cursor over an item displayed in some other addons (as e.g. in "AllTheThings"), it vanishs after about 0.2 - 0.5 seconds. If I disable ArkInventory this does not happen. It is not a fault in AllTheThings, because it happens in other addons as TradeSkillMaster 4 too.

When I have only ArkInventory enabled and move over e.g. food or flasks in my inventory, it shows me the tooltip and refreshs it after some milliseconds to update it with the total number in my bank / guildbank / other charakters. 

So I think, this update-feature is the culprint, because other addons are not able to interpret it correctly and "reopen" the updated tooltip.

PS: tooltips of quests etc. are affected too.

**Comment by samot1** [comment]
PS: when I disable the tooltips completly in ArkInventory settings, the item tooltips in the other addons do not longer disappear

**Comment by arkayenro** [comment]
duplicate, please see #1079
