### ISSUE TITLE
Tooltip error in 3.08.08

### ISSUE THREAD

**Issue by b3n9ti** [arkayenro/arkinventory#1083]
3x ArkInventory\ArkInventoryTooltip.lua:1701: Usage: GameTooltip:SetUnit("unit"[, hideStatus]) [C]: in function `?' ArkInventory\ArkInventoryTooltip.lua:1701: in function `UpdateTooltip' FrameXML\GameTooltip.lua:500: in function <FrameXML\GameTooltip.lua:477> [C]: ?  Locals: InCombatSkipped

**Comment by arkayenro** [comment]
duplicate, please see #1079
