### ISSUE TITLE
Weird Issue with update via Twitch Client

### ISSUE THREAD

**Issue by Azunella** [arkayenro/arkinventory#1086]
Hey i have the weird problem, that if i install/update the Arkinventory via Twitch Client. It is completly broken, same issue like "25th May 2017 - Arkinventory completely broke for me-failsafe error". I also get the failsafe error, never ending lua error with bugsack/buggrabber. But if i install it by hand there is no problem. I already reinstalled WoW and also the Twitch client. Nothing helped. Everytime i want to use the Twitch client ArkInventory will be broken again.
this happens especially only with arkinventory other addons i can normally update/install via Twitch client

**Comment by Azunella** [comment]
Nerverminded, after given twitch adminstration permissions it works again :D

**Comment by arkayenro** [comment]
check the permissions on the arkinventory folder, or just delete it and re-install.

i've seen some of my folders get flagged as needing admin permissions to touch which shouldnt be the case
