### ISSUE TITLE
Can't use Arkinventory with TSM4

### ISSUE THREAD

**Issue by deuxbebes** [arkayenro/arkinventory#1088]
We installed a new driver, freshly installed WoW along with Arkinventory, TSM4, and Tomtom.  (No other addons.)  When I mouse hover over an item in the TSM window, the info about that item shows up for a split second and then disappears.  The only way to correct it is to disable Arkinventory.

![ark issue](https://user-images.githubusercontent.com/42205988/43832765-7eb27594-9ad6-11e8-96e6-2da8bc016bb9.jpg)

**Comment by halfreak** [comment]
Are you using the latest version? It's fixed in version 3.08.10. Also, you should update TSM, current is v.4.0.13

**Comment by arkayenro** [comment]
please tell me youre using an older version because im not in the mood to rewrite the tooltip code again

**Comment by deuxbebes** [comment]
Updated both and everything is working-thanks!
