### ISSUE TITLE
Reverse Clean up Bags is always clear when reload

### ISSUE THREAD

**Issue by dmsierra** [arkayenro/arkinventory#1089]
No addons loaded but ArkInventory

I set "Reverse Clean Up Bags" flag in AI Options (right click on the bag), then typed /reload, then the option is shown as cleared.

**Comment by arkayenro** [comment]
i didnt realise i had an option there.  right click on the restack icon for the moment until i can update that one as well (its still asking blizzard how its set)

**Comment by arkayenro** [comment]
should be fixed in the next release

**Comment by dmsierra** [comment]
Didnt realise I can right click on the restack icon :D

Thank you very much!

**Comment by arkayenro** [comment]
fixed in 3.08.11
