### ISSUE TITLE
guild bank 

### ISSUE THREAD

**Issue by Ibglitrbug** [arkayenro/arkinventory#1090]
it was working fine till yesterday now i cant open the guild bank on any of my toons not sure what happened hope you can take a look at it soon had turning stuff on and off lol thanks again great add on

**Comment by arkayenro** [comment]
should be fixed in the r767-alpha

**Comment by Ibglitrbug** [comment]
but as i said every time i turn one off a new one replaces it so its saying
its not working with any other addons i have.
*Anyone can be a Pawn. But it takes a true ?itch to be a Queen.*

**Comment by arkayenro** [comment]
youre going to need to specifically describe your issue as im not understanding what youre saying

**Comment by Ibglitrbug** [comment]
OK on version 3.08.11 when i install it i can open my bags but the guild bank wont open at all. I just did it again to check it and same thing wont open guild bank so what i had to do was go to the last version that its showing on the add on site which is twitch r769-alpha i can then open the guild bank but i cant deposit gold into it with out shutting off the add on. I hope that was clearer. thanks for your time.
