### ISSUE TITLE
this is the lua error

### ISSUE THREAD

**Issue by Ibglitrbug** [arkayenro/arkinventory#1091]
i went back to the one before your latest reliece , i turned off cant mog it then it popped up with breakables so i turned that off and it keeps coming up with one after another.
with this version 7.0.3 that i'm running now i can see the guild bank but i can't deposit or withdraw funds

Message: Interface\AddOns\CanIMogIt\Plugins\arkinventory.lua:22: attempt to call field 'InternalIdToBlizzardBagId' (a nil value)
Time: Fri Aug 10 16:57:34 2018
Count: 848
Stack: Interface\AddOns\CanIMogIt\Plugins\arkinventory.lua:22: attempt to call field 'InternalIdToBlizzardBagId' (a nil value)
Interface\AddOns\CanIMogIt\Plugins\arkinventory.lua:22: in function `ArkInventoryItemButton_CIMIUpdateIcon'
Interface\AddOns\CanIMogIt\Plugins\arkinventory.lua:92: in function <Interface\AddOns\CanIMogIt\Plugins\arkinventory.lua:92>

Locals: self = CIMIOverlayFrame_ARKINV_Frame4ScrollContainerBag1Item17 {
 0 = <userdata>
 CIMIIconTexture = CIMITextureFrame {
 }
 timeSinceCIMIIconCheck = 0.2860000114888
}
frame = ARKINV_Frame4ScrollContainerBag1Item17 {
 0 = <userdata>
 CanIMogItOverlay = CIMIOverlayFrame_ARKINV_Frame4ScrollContainerBag1Item17 {
 }
 BattlepayItemTexture = <unnamed> {
 }
 ArkBorder = ARKINV_Frame4ScrollContainerBag1Item17ArkBorder {
 }
 IconOverlay = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 flash = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 count = 1
 IconBorder = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 hasItem = 1
 icon = ARKINV_Frame4ScrollContainerBag1Item17IconTexture {
 }
 locked = false
 JunkIcon = <unnamed> {
 }
 timeSinceUpgradeCheck = 0
 ArkBagHighlight = ARKINV_Frame4ScrollContainerBag1Item17ArkBagHighlight {
 }
 ExtendedOverlay = <unnamed> {
 }
 UpdateTooltip = <function> defined @Interface\AddOns\ArkInventory\ArkInventory.lua:7043
 ARK_Data = <table> {
 }
 Count = ARKINV_Frame4ScrollContainerBag1Item17Count {
 }
 ArkAgeText = ARKINV_Frame4ScrollContainerBag1Item17ArkAgeText {
 }
 flashAnim = <unnamed> {
 }
 UpgradeIcon = <unnamed> {
 }
 BagStaticBottom = <unnamed> {
 }
 ExtendedSlot = <unnamed> {
 }
 searchOverlay = ARKINV_Frame4ScrollContainerBag1Item17SearchOverlay {
 }
 NewItemTexture = <unnamed> {
 }
 SplitStack = <function> defined @Interface\AddOns\ArkInventory\ArkInventory.lua:7632
}
itemLink = nil
bag = nil
slot = nil
(*temporary) = nil
(*temporary) = 4
(*temporary) = 1
(*temporary) = "attempt to call field 'InternalIdToBlizzardBagId' (a nil value)"

**Comment by arkayenro** [comment]
thats a CanIMogIt error
