### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by dsanches81** [arkayenro/arkinventory#1092]
Date: 2018-08-11 17:43:49
ID: 91
Error occured in: Global
Count: 1
Message: ..\AddOns\ArkInventory\ArkInventory.lua line 4866:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: ?
   [C]: PlaySound()
   ArkInventory\ArkInventory.lua:4866: Frame_Main_OnShow()
   [string "*:OnShow"]:1:
      [string "*:OnShow"]:1
   [C]: Show()
   ArkInventory\ArkInventory.lua:4839: Frame_Main_Show()
   ArkInventory\ArkInventory.lua:4818: Frame_Main_Toggle()
   ArkInventory\ArkInventory.lua:9199:
      ArkInventory\ArkInventory.lua:9194
   (tail call): ?
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:

**Comment by arkayenro** [comment]
what version are you running?  there havent been playsound issues since blizzard changed it almost a year ago
