### ISSUE TITLE
Lua Error when mouseovering a battlepet(?) but not always

### ISSUE THREAD

**Issue by Draugor** [arkayenro/arkinventory#1093]
The last few days i was farming huolon and sometimes while standing their i would get the following error from Ark:
```
ArkInventory\ArkInventoryTooltip.lua:1100: Usage: UnitBattlePet("unit")
[C]: in function `UnitIsWildBattlePet'
ArkInventory\ArkInventoryTooltip.lua:1100: in function `?'
ArkInventory\ArkInventoryTooltip.lua:1355: in function <ArkInventory\ArkInventoryTooltip.lua:1327>
[C]: ?
[C]: ?
[C]: ?

Locals:
(*temporary) = nil

```

But i can't reliable reproduce it sorry :/ it just happens sometimes. Because it says "UnitBattlePet" and "UnitIsWildBattlePet" i thought it has something to do with the pets walking around in the background but when i mouseover them normally, no error is thrown so not sure where it comes from exactly.

cheers

**Comment by arkayenro** [comment]
fixed in 3.08.11
