### ISSUE TITLE
Items not gray when put into mail

### ISSUE THREAD

**Issue by deuxbebes** [arkayenro/arkinventory#1096]
Items used to turn gray so you knew it was attached to outgoing mail but now they aren't which makes it hard to tell what I already put in.  

I also used to be able to CTRL+left click to put all like items in a letter but must do one at a time now.

**Comment by arkayenro** [comment]
i dont touch the shift/ctrl click actions so if that no longer works then i dont know why

if you just pick up and item does it fade for lock?

**Comment by deuxbebes** [comment]
Item does not fade when put into a letter.

**Comment by arkayenro** [comment]
yes, yes, youve said that.  does it fade when you just pick it up?

im not seeing it so i presume its a conflict with another mod
