### ISSUE TITLE
Activating Rule

### ISSUE THREAD

**Issue by VacaTonta** [arkayenro/arkinventory#1097]
Can anybody tell me how - after the last redesign update of the options window - I can activate a new rule?
Before, I could create one, goto options>categories>rules and activate it for each specific profile.
Now that activate "button" is gone.
And I can't see which rules are active for which profiles. Neither can I activate any new rule at all...
:(
need help

**Comment by arkayenro** [comment]
go into edit mode, click on the bar with the rule and enable/disable it.

im working on putting the option back in i just need to make it more obvious that its just for that profile

**Comment by VacaTonta** [comment]
Hey :)
First of all, thanks for the quick response!
2. Great Addon!
Now to my problem.
When I create a rule for example for "Great Sea Catfish", i create a new rule, call it "Great Sea Catfish" and below I put "itemstring( 152547 ).
Now in the options-window under settings>categories>rules it will be listed under "active".
But when I go into edit mode and click on that item it will NOT be assigned to this rule, even after relog or restart of WoW. And in the options window I cannot activate it. Neither for a specific profile nor for all profiles.
When I do as you say and go into edit mode, click on the bar I want the rule to be assigned to it (of course) is not listed under the assigned rules. But when I go to the general "rules" part of the little popup window where ALL rules appear I (probably) could activate it. However since I have more than 3k rules I would have to scroll down for like 10 minutes just to activate 1 rule for 1 profile.
With an item like this it would only be 1 rule for 1 profile, but it would still take like 10 minutes to find that rule and activate it.
But I have rules for - let's say - all the Portal-Items which I want to have active on ALL profiles. Then I would have to do a scroll down on EVERY profile (which are about 45) where activating 1 new rule would take me about 1 day.
The old way it was just 2 clicks. Search for the rule. Click on "activate". Select next profile. Click on "activate".

**Comment by VacaTonta** [comment]
Here is a link to the rule in the options window:

https://picload.org/view/dlloclda/ruleinoptions.jpg.html

**Comment by VacaTonta** [comment]
it is listed, no errors, under "active"

**Comment by VacaTonta** [comment]
here is a link to the item tooltip in edit mode:

https://picload.org/view/dllocldl/unactiverule.jpg.html

it is NOT assigned to this rule.
or the rule is NOT active.

This pic was taken AFTER a complete relog and restart of WoW.

**Comment by VacaTonta** [comment]
Here is a link to what it looks like, when I do as you told me:

https://picload.org/view/dlloclrw/activatinrule.jpg.html

As you can see, it woul take me HOURS to activate 10 rules in a profile...

I really! hope you can help me, or reactivate the "old" way of activating rules in the options window.
Because the way it is now, if I have to do it like this in edit-mode, the addon won't be usable anymore and I put like hundreds of hours in it, since I play since 12 years, have 40+ guilds and 40+ profiles....

PLEASE ARK!!!

PLEEEAAASE HELP ME!

**Comment by VacaTonta** [comment]
i case im getting you right here:

"im working on putting the option back in i just need to make it more obvious that its just for that 
profile"

i will just wait for the next update/version and keep on using the previous one till then :)

thanks for all the work ark!

**Comment by arkayenro** [comment]
the latest alpha has some more rearrangements, you still cant enable/disable rules yet but the tabs are in place for it, i just have to populate them with the data

**Comment by VacaTonta** [comment]
thanks a lot :)
waiting for the new version :)

**Comment by VacaTonta** [comment]
WoW! THANKS SO MUCH! Seems to work perfectly!!! :)
Well done and THANK YOU AGAIN AND AGAIN!
