### ISSUE TITLE
Item category not updated correctly under certain conditions

### ISSUE THREAD

**Issue by antarek** [arkayenro/arkinventory#1098]
Hi,

I added a rule to ArkInventory to have all items from 3 different sets under the Set gategory and if all is ok when i place an item tagged as being part of one of these 3 sets when i change this item to replace him with a bette one and untag him as part of one of these 3 sets then the item remains into the Set category as if ArkInventory failed to update its status. I tried to switch the sorting option to instantly but it doesn't seem to solve the issue.

My rule to group all items from my 3 different sets is:

- outfit( "impie", "givre", "sang" )

I don't understand why items that aren't anymore tagged as being part of any of these 3 sets remain in my Set category.

**Comment by arkayenro** [comment]
if you go into edit mode and click on the item which category is it assigned to?

**Comment by arkayenro** [comment]
are you using an outfit mod, if so which one, or just the blizzard equipment manager?

**Comment by antarek** [comment]
No outfit mod at all. I m using the blizzard one.

Here are the mods that i have installed in addition to ArkInventory:

- Deadly Boss Mods (DBM)
- Deadly Boss Mods (DBM) - BC & Vanilla/Classic mods
- Deadly Boss Mods (DBM) - Wrath of the Lich King mods
- Deadly Boss Mods (DBM) - Cataclysm mods
- Deadly Boss Mods (DBM) - Mist of Pandaria (MoP) mods
- Deadly Boss Mods (DBM) - Warlords of Draenor (WoD) mods
- Can I Mog It?
- ColorPickerPlus
- Details! Damage Meter
- Grail
- Immersive
- LibSharedMedia-3.0
- LiteMount
- Mapster
- MoveAnything
- PhanxChat
- RepSwitch
- Scrap (Junk Seller)
- The Undermine Journal
- TipTac
- TullaRange
- WeakAuras 2
- Wholly
- World Quests List
- WorlfFlightMap

**Comment by arkayenro** [comment]
its possible there is a delay between the item being placed back into your bags - which is when it gets categorised - and the equipment set being updated.

you should be able to just pick it up and move it to any other slot to regenerate its category again, and if that works then there is enough of a delay in the equipment sets getting updated to cause the issue

**Comment by antarek** [comment]
Just tested to move the item to the default category but it moves it back to the set one so ArkInventory continues to think of the item as if it was still part of any of my 3 equipment sets. Really weird.

**Comment by arkayenro** [comment]
ok, i'll take a look at the code when i get home.  its possible blizzard changed something in the equipment manager and as i use outfitter i didnt notice

**Comment by arkayenro** [comment]
i think its was the delay as i immediately recalcualte so if its even slightly off it wont update correctly

i've changed the code to flag the window for redraw, not actually redraw it so by the time it gets redrawn it should have had time for the equipment sets to have updated

**Comment by antarek** [comment]
A little update, i just noticed that pressing the "empiler les objets" (stack items) button moves items that do not belong anymore to any of my 3 sets to their correct category.

**Comment by arkayenro** [comment]
found the problem, will be fixed next release

**Comment by hollo6** [comment]
With r782 still need to reopen the bag (it did update right away before) but now at least reload is not necessary.

**Comment by arkayenro** [comment]
you might also just want to double check and disable every single mod except arkinventory and see if it still has issues

**Comment by antarek** [comment]
Removing the "--" before the line 972 to have this "ArkInventory.Output( setid, " = [", setname, "] [", type( setname ), "]" )" taken into account worked. My set items are placed into the correct category.

Thanks a lot arkayenro.

**Comment by arkayenro** [comment]
you can put the -- back in front of line 972 if you want as that line wont make any difference, its just output.  like 973 was added to try and fix it, which it appears to have done.

did the output show every set id having a name and a type of String?

**Comment by antarek** [comment]
Ok, thanks and yes, here is what it says:

https://i.imgsafe.org/f8/f8c75773f7.jpeg

But how comes that the problem got solved after removing the "--" before line 972 if this is just used to output IDs given to sets as far as i don't remember the twitch app downloading an update for ArkInventory yesterday?

**Comment by arkayenro** [comment]
fixed in 3.08.13
