### ISSUE TITLE
BFA - "scrappable" attribute

### ISSUE THREAD

**Issue by jleonard99** [arkayenro/arkinventory#1099]
I'd like to build a rule that identifies "scrappable" equipment, a new attribute type in BFA.

When standing next to the open "scrap-o-matic 1000", the word "scrappable" appears in item text and the rule function tt("scrappable") works just fine.

However, when NOT at the scrap-o-matic (e.g., questing), the word "scrappable" does not appear in the item text and the rule no longer works. 

Any suggestions for identifying items that are "scrappable" when not in town?  Can a new function be created, something like is_scrappable()?

**Comment by arkayenro** [comment]
scrappable is like disenchantable, as far as i know theres nothing to tell you unless youre doing the action

`equip( ) and expansion( 7 )`

should work though as you can only scrap wearable items from BFA
