### ISSUE TITLE
Inventory locked in combat, cannot swap weapons or move items.

### ISSUE THREAD

**Issue by zcourge** [arkayenro/arkinventory#1100]
So if you try to swap weapons while in combat (let's say you're out fishing and need your sword in your hand all of a sudden), the inventory just locks and you need to RE-LOG (getting out of combat isn't enough, neither is /reload
) to be able to use that slot at all. Can't move it somewhere else if it's in the inventory, and the equipment slot cannot be swapped out for another item. 

This is primarily connected to weapons, as you can swap them out in combat, while other equipment isn't possible.

This need to be fixed ASAP.

**Comment by arkayenro** [comment]
are the slots all purple?

youre probably better off using the character pane

**Comment by zcourge** [comment]
No, the afflicted slot turns grey, as if they're being moved.

I am using the character pane, but the problem is that the item has to end up in the inventory, causing this to crash somewhat.

**Comment by arkayenro** [comment]
AI can stop you from using an item its showing in its own window, it shouldnt have any impact on it being used via the character pane or action bar.

i'll have a look when i get home

**Comment by arkayenro** [comment]
just tested in combat, wearing my fishing pole

i can right click on weapons in the bag and it will equip them
i can click on them to pick them up and move them to the character pane

are you using outfitter? i get an error when i try to manually swap out weapons and the slots go grey

**Comment by zcourge** [comment]
Not using outfitter...

**Comment by arkayenro** [comment]
you should bet getting an error

you could also disable everything except AI and confirm it does not happen
