### ISSUE TITLE
Auto sell only sells a small number of items at a time. I have unchecked Limit to Buyback

### ISSUE THREAD

**Issue by Talvox** [arkayenro/arkinventory#1102]
https://puu.sh/BhSsu/66646404d0.png is my current setting. It funtions semi properly as it does auto sell things but I have to close and open the merchant window several times to get everything gone

**Comment by arkayenro** [comment]
yes, its not perfect, the game doesnt always accept the item so it gets stuck and you have to sell again

**Comment by arkayenro** [comment]
next version will have a delay value you can adjust if the items arent all getting sold

**Comment by arkayenro** [comment]
config option added to 3.08.12
