### ISSUE TITLE
Error during pet battles on r773-alpha

### ISSUE THREAD

**Issue by Fraktyl** [arkayenro/arkinventory#1103]
Getting the following error message whenever I initiate a pet battle with a trainer:

3x ...ceArkInventory\ArkInventoryCollectionPet.lua:728: attempt to call field 'Scan' (a nil value)
...ceArkInventory\ArkInventoryCollectionPet.lua:728: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...aceTomTom\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...aceTomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by arkayenro** [comment]
will be fixed next alpha/release

**Comment by arkayenro** [comment]
fixed in 3,.08.12
