### ISSUE TITLE
Can soulbound() check for an integer?

### ISSUE THREAD

**Issue by MrUzagi** [arkayenro/arkinventory#1104]
Hi

When looking at the debug for items there's the property soulbound. Sometimes it simply says yes or no, but sometimes it can say something like "2 (binds on equiped)". I don't know if it is Blizzard reporting this to AI or if AI keeps a record of it itself.

What I've seen are (so far I haven't come across 1 in AI):
0 (Never)
2 (Binds on equiped)
3 (Soulbound)
4 (Accountbound)

According to https://wow.gamepedia.com/API_GetItemInfo the return values for bindType can be "Number - Item binding type: 0 - none; 1 - on pickup; 2 - on equip; 3 - on use; 4 - quest." which isn't identical to what I've seen in AI.

I've tried to make a rule with soulbound(2) in the hopes of getting BoE items but it had no effect. Am I doing it wrong or isn't it implemented? The wiki makes no mention that it should work and all my googling in to the matter has turned up zilch so far, so I'm guessing it's the latter.

If it isn't implemented, could it be? Pretty please?
If it is implemented and my google-fu just failed me, please enlighten me how to do it.

In either case, please put me out of my misery. :-)

*Edit: Silly typo.

**Comment by arkayenro** [comment]
well those returns are new, and very helpful, will need to update the code again


current AI soulbound constants

Never = 0
Use = 1
Equip = 2
Pickup = 3
Account = 4

**Comment by arkayenro** [comment]
https://github.com/arkayenro/arkinventory/wiki/RuleFunction_Bound

will be in the next release

**Comment by MrUzagi** [comment]
Awesome. Very nice. Thank you.

**Comment by arkayenro** [comment]
added in 3.08.12
