### ISSUE TITLE
Druid Travel Form

### ISSUE THREAD

**Issue by Mythris29** [arkayenro/arkinventory#1105]
I'm running into a strange issue with the mount feature...it just started up with this latest version (possibly the one version previous to this newest one).

I have bound a hotkey to mount "z" and I have selected travel form on my druid instead of mounts. Usually, this setup works perfectly however recently the behavior has changed.

After switching specs...and sometimes at random, the hotkey stops putting me into travel form and instead just changes me to human from whatever form I'm in.
Reload UI doesn't fix the issue

Changing specs back to the previous spec doesn't fix the issue.

Logging out and then back usually fixes the issue.

If I change it to use mounts instead of travel form it works with regular mounts but then switching back to travel form mode continues to not work so I think it's a druid specific problem with travel form.

No errors are being caught by bugsack. Let me know if I can provide some more information to help troubleshoot this issue.

Thanks!

**Comment by Mythris29** [comment]
Quick comment...sometimes using the hearthstone to go to Boralas fixes the issue...I'm not sure what's going on but maybe it's getting confused or stuck on what kind of environment I'm in? Inside, outside, water etc...and going to the Capitol somehow resets that?

**Comment by arkayenro** [comment]
if you change the option to use travel form you must reload as its secure macro based and only loads once, i cant change it once youre playing (the secure thing)

if its changing you to human form then at least part of the macro, the /cancelaura is working

i havent played my druid yet but i'll take a quick look and see if its happening for me too

**Comment by arkayenro** [comment]
its working ok so far pre-zandalar, just have to get the druid there to test it

**Comment by Mythris29** [comment]
Yeah sorry, I should have specified when I switched from mount mode to travel form mode I did a reload UI between those.

No matter what I did I couldn't get travel form working (via hotkey the action button for travel mode worked fine) then I used my hearthstone to teleport back to Boralus and it was working via hotkey again. The only other thing that seems to fix this for me is logging out of the game and then logging back in.

That makes sense about the macro. If I'm understanding things correctly I think something is preventing the macro from running the shapeshift part of the macro but it's doing the /cancelaura part. 

If this matters I have Glyph of the Stag and Glyph of Treant on my druid so there are 2 extra shapeshifts available than normal.

Using a hotkey to shift into travel form (via arkinventory) has been working well for me for years now so it's been really strange to just have it break out of the blue like this and require logging out to fix it.

I appreciate your time and effort you put into this mod I've been using it for years now and won't be switching anytime soon :)

**Comment by arkayenro** [comment]
try it with just AI loaded and see if there are issues or not

if you want to, you can also open arkinventory.lua and go to line 2484 which should be
--ArkInventory.Output( macrotext )

if you remove the -- from the front, save the file, then reloadui it should spit out the macro its using, which should look something like

	/dismount [combat, mounted, noflying]
	/stopmacro [combat]
	/cancelform [noform:0]
	/cast [indoors] Cat Form; Travel Form

actually mine was missing a line break after the first line but that shouldnt really matter, i'll add it into the code just in case it does impact some users but you were getting the form cancelled so it seemed to have gone past that and was failing on the /cast

**Comment by Mythris29** [comment]
Okay sorry for the delay in response.

So here is what I tried as detailed as possible.

I switched specs in the Braxton Lodge area of StormSong. The travel form arkinventory macro broke. 

I tried disabling all other addons, didn't fix the issue.
I tried logging out and then back in, Issue fixed.
I tried switching specs with Arkinventory as the only addon enabled, broke the macro.
I tried making the changes to arkinventory.lua like you suggested and reloaded, still broken

After making those changes I did see this though:
Unknown macro option: exsists
failsafe kicked in - aborting arkinventory translations due to an error of some sort

**Comment by arkayenro** [comment]
when you made the change to arkinventory.lua it would have started printing the macro to the chat window after you logged in, what was the output?

**Comment by arkayenro** [comment]
finally got it to fail for me after a spec change

its not an AI issue, it looks like a blizzard bug as when it happens i cant even type in /cast Travel Form and have it work

**Comment by arkayenro** [comment]
now it seems to be broken completely even after a uireload its not working

**Comment by arkayenro** [comment]
ended up having to logout and back in to get travel form to work again

you may want to raise a bug with blizzard - test with no mods at all first and see if /cast travel form ever fails

**Comment by Mythris29** [comment]
Yeah good catch there. I'm going to submit a ticket and see where it goes.

**Comment by Mythris29** [comment]
I haven't seen this come up for a while now so I'm going to assume they quietly fixed this :) Either way, it's not the addon so thank you for your help I'm going to close this issue.
