### ISSUE TITLE
lua error in 8.0.1

### ISSUE THREAD

**Issue by countzero666** [arkayenro/arkinventory#1106]
Hi there,

I'm running 3.08.11 and Keep getting lua errors from Arkinventory in Wow 8.0.1. Any idea what's causing those? I'll post the error message below.

Regards,

Chris

Message: ...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:311: attempt to index global 'ArkInventory' (a nil value)
Time: Sat Aug 25 16:44:07 2018
Count: 119
Stack: ...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:311: attempt to index global 'ArkInventory' (a nil value)
...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:311: in function <...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:303>

Locals: self = <unnamed> {
 loopmax = 5
 loop = 0
 0 = <userdata>
 timermax = 5
}
elapsed = 0.034000001847744
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'ArkInventory' (a nil value)"
updateTable = <table> {
 WOW_SKILL_SKINNING = <function> defined @Interface\AddOns\ArkInventory\ArkInventoryTranslate.lua:32
 WOW_SKILL_HERBALISM = <function> defined @Interface\AddOns\ArkInventory\ArkInventoryTranslate.lua:20
 WOW_SKILL_MINING = <function> defined @Interface\AddOns\ArkInventory\ArkInventoryTranslate.lua:26
}
lang = "Deutsch"
GetTranslations = <function> defined @Interface\AddOns\ArkInventory\ArkInventoryTranslate.lua:291
table = <table> {
 setn = <function> defined =[C]:-1
 insert = <function> defined =[C]:-1
 getn = <function> defined =[C]:-1
 foreachi = <function> defined =[C]:-1
 maxn = <function> defined =[C]:-1
 foreach = <function> defined =[C]:-1
 concat = <function> defined =[C]:-1
 removemulti = <function> defined =[C]:-1
 sort = <function> defined =[C]:-1
 wipe = <function> defined =[C]:-1
 remove = <function> defined =[C]:-1
}
spellTable = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
}
itemTable = <table> {
}
tooltipTable = <table> {
}
pairs = <function> defined =[C]:-1

**Comment by arkayenro** [comment]
there have to be more errors before that one - this is just a side effect of something else being broken

**Comment by countzero666** [comment]
First error after logging in:

Message: Interface\AddOns\ArkInventory\ArkInventoryExternals.lua:7: '<eof>' expected near 'end'
Time: Sat Aug 25 19:47:55 2018
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventoryExternals.lua:7: '<eof>' expected near 'end'

Locals: **

**Comment by countzero666** [comment]
Then:

Message: Interface\AddOns\ArkInventory\ArkInventoryCodex.lua:31: attempt to index global 'ArkInventory' (a nil value)
Time: Sat Aug 25 19:47:56 2018
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventoryCodex.lua:31: attempt to index global 'ArkInventory' (a nil value)
Interface\AddOns\ArkInventory\ArkInventoryCodex.lua:31: in main chunk

Locals: _G = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @Interface\FrameXML\ActionButton.lua:70
 ERR_OUT_OF_CHI = "Nicht genügend Chi"
 DH_HAVOC_CORE_ABILITY_2 = "Starker Nahkampfangriff. Verbraucht Jähzorn. Kritische Treffer erstatten einen Teil des Jähzorns zurück."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Namen von Einheiten einfärben."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 StoreMicroButtonAlertGlowBottom = StoreMicroButtonAlertGlowBottom {
 }
 SPELL_FAILED_CUSTOM_ERROR_71 = "Dieser Partygast möchte mit Euch tanzen."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 398
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Für diese Community können keine weiteren Einladungslinks generiert werden."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "Mit von Euch angelegten Taschen könnt Ihr nicht handeln."
 PVP_RANK_6_1 = "Fußknecht"
 BOOKTYPE_PROFESSION = "professions"
 AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture {
 }
 VideoOptionsFrameDefaults = VideoOptionsFrameDefaults {
 }
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Vordefinierte Tastaturbelegungen für Aktionen reagieren bei gedrückter statt bei losgelassener Taste."
 BINDING_NAME_NAMEPLATES = "Plaketten für Gegner einblenden"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s kann nicht eintreten. Diese Instanz ist vorübergehend gesperrt."
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 IsReferAFriendLinked = <function> defined =[C]:-1
 MAIL_LETTER_TOOLTIP = "Klicken, um eine dauerhafte
Kopie dieses Briefs anzufertigen."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @Interface\FrameXML\UnitFrame.lua:787
 PaperDollTitlesPaneButton10BgTop = PaperDollTitlesPaneButton10BgTop {
 }
 DUNGEON_FLOOR_UPPERBLACKROCKSPIRE3 = "Schwarzfausthalle"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 FCFDockOverflowButton_OnClick = <function> defined @Interface\FrameXML\FloatingChatFrame.lua:2372
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 ChatFrame6EditBoxFocusMid = ChatFrame6EditBoxFocusMid {
 }
 BN_UNABLE_TO_RESOLVE_NAME = "'%s' kann nicht angeflüstert werden. Möglicherweise sind die Blizzard-Dienste nicht verfügbar."
 LE_GAME_ERR_RECRUIT_A_FRIEND_FAILED = 947
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 32
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 ToggleEncounterJournal = <function> defined @Interface\FrameXML\UIParent.lua:909
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Verängstigt"
 Graphics_QualityText = Graphics_QualityText {
 }
 TalentMicroButtonAlertShadowTopLeft = TalentMicroButtonAlertShadowTopLeft {
 }
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 ROGUE_COMBAT_CORE_ABILITY_4 = "Nahkampfangriff. Verbraucht Combopunkte."
 JoinSkirmish = <function> defined =[C]:-1
 Advanced_GraphicsAPIDropDownButtonHighlightTexture = Advanced_Graphics

**Comment by countzero666** [comment]
More error text, which I hope will be helpful:

Message: Interface\AddOns\ArkInventory\Locale\game.lua:273: attempt to index global 'ArkInventory' (a nil value)
Time: Sat Aug 25 19:47:56 2018
Count: 1
Stack: Interface\AddOns\ArkInventory\Locale\game.lua:273: attempt to index global 'ArkInventory' (a nil value)
Interface\AddOns\ArkInventory\Locale\game.lua:273: in main chunk

Locals: L = <table> {
}
FormatForRegex = <function> defined @Interface\AddOns\ArkInventory\Locale\game.lua:212
FormatForCapture = <function> defined @Interface\AddOns\ArkInventory\Locale\game.lua:224
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = "WOW_ITEM_CLASS_WEAPON"
(*temporary) = nil
(*temporary) = "Const"
(*temporary) = 132144
(*temporary) = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = 783
(*temporary) = "%+%d Gegenstandsstufen"
(*temporary) = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'ArkInventory' (a nil value)"

**Comment by arkayenro** [comment]
looks like one of the files may have gotten corrupted.  you may want to re-install AI

**Comment by countzero666** [comment]
Ahhhh...reinstalling fixed my issue. Should've tried that first before bothering you. Sorry bout that. This can be closed. :)
