### ISSUE TITLE
Bank Override and bag opening bug

### ISSUE THREAD

**Issue by TheRealTostitoes** [arkayenro/arkinventory#1109]
HI,

I'm an Elvui user and I prefer the elvui all in one bank tab over arkinventory's one because it lets me access my reagents tab. After trying things out I figured I couldn't have elvui's bags for my bank without having 2 windows pop up (one from arkinventory and one from elvui) whenever I'd open my bags. So I went ahead and disabled elvui's bag because I prefer the arkinventory sorting for my personnal bag and disabled the override for the bank tab (Sadly I prefer the vanilla wow interface over the arkinventory's one) but I found myself unable to open my bags afterwards. I've tried clicking on my bags and the open all bags keybind but nothing works except turning the override for the bank tab back on.

Any help?

**Comment by arkayenro** [comment]
i cant duplicate it.  i can disable the bank and the bags still open/close fine, the bank is default ui - but i dont have elvui

its possible elvui is doing something weird but its also not really a good idea to have multiple mods installed that manage the bags as theres typically only one way to control them and that means taking it away completely from other mods
