### ISSUE TITLE
where is this button?

### ISSUE THREAD

**Issue by Drui7** [arkayenro/arkinventory#1110]
![default](https://user-images.githubusercontent.com/3121957/44831685-1598fe80-ac41-11e8-9d41-863dc00d2a1e.PNG)

**Comment by arkayenro** [comment]
with the bag changer open right click on the last bag (the reagent tab)
or right click on the restack icon (it might be there as well)

**Comment by Drui7** [comment]
@arkayenro functional needed, but it's hard to find! I suggest in the bank below to create a button, similarly as done in a standard bank. I put a picture, it is enclosed, where it can be placed. and another button "sorting" pulls things out of the bank of materials into an ordinary bank. in the standard interface there is no such thing, sorting the bank and the bank of materials separately.
![default](https://user-images.githubusercontent.com/3121957/44891977-ba781200-acfb-11e8-9bc3-c32aa9d82365.PNG)

**Comment by arkayenro** [comment]
its only that large in your setup, other have it much smaller

**Comment by Raidfather** [comment]
Looks like this button disappeared again with the wacky bank changes they snuck in
