### ISSUE TITLE
Category Copying

### ISSUE THREAD

**Issue by VacaTonta** [arkayenro/arkinventory#1111]
Hey :) I just recently started my drk iron dwarf and made a new profile. when I want to copy the category set from my other character i get the following message:

23:38 ArkInventory: FEHLER> bad code. settings:categoryset does not have an arg value.  requested from settings:categoryset:1022:action_copy

**Comment by VacaTonta** [comment]
Need help! :(

**Comment by arkayenro** [comment]
sorry, missed that when i moved that section.

fixed in the r781-alpha if you want to download that

**Comment by VacaTonta** [comment]
Thanks!
