### ISSUE TITLE
Enable/Disable Rules Based on Layout?

### ISSUE THREAD

**Issue by artibyrd** [arkayenro/arkinventory#1113]
I have begun creating and experimenting with a lot of rules, and have noticed that my inventory load times are starting to bog down now - it takes about 5 seconds when I first open the bank or guild bank for things to load.  Would it be possible to have Rules enabled only on a per Layout basis?  For example, I have created a set of rules to group my ~~pokemon~~ battle pets by type, which is very handy!  But I only need these Rules active on my Pet Location and my concern is maybe all these superfluous Rules I created being enabled on all my other Locations is contributing to the loading delay when I open my bank?

**Comment by arkayenro** [comment]
rule are already enabled/disabled per layout

checking against a disabled rule would be microseconds, its the enabled rules that will bog it down

**Comment by artibyrd** [comment]
Thanks for the reply!  I'm probably doing something wrong then - when I disable the rules on one layout they seem to disable everywhere!  What am I missing?

**Comment by artibyrd** [comment]
Just checked this again this morning to be sure I'm not crazy...  I have a "Bags" Style and Layout applied to my Backpack and a "Pets" Style and Layout applied to my Pets, but when I disable a Rule from my bags, it also disables the Rule for my Pets.  Where am I going wrong?

The issue isn't really with viewing my pets, it's with opening my Bank or Guild Bank and having all these extra rules running there - it will sort itself out and be OK for a little while after the first time I open my bank due to the cached results like you say, but it really hinders Guild Bank access most.

**Comment by artibyrd** [comment]
OMG I see it now, I completely missed it in the config!  Thanks for getting me sorted out, I just somehow never clicked on that tab, I get how this works now.  I can already see the difference after unloading all my Pet rules to another Category Set but it's still slow so I think I must have screwed up one of my other rules...  This at least puts me on the right path to getting it figured out on my own from there though, thanks!
