### ISSUE TITLE
Sort by custom Rule Variable?

### ISSUE THREAD

**Issue by artibyrd** [arkayenro/arkinventory#1114]
I have created a set of Rules to group all my pets by type, which is great!  Now I want to sort them by level, but there is no way I can find to do this.  Would it be possible to add the ability to sort by a custom Rule Variable?  If I could sort by i.osd.level somehow my problem would be solved, for example.  This addon is great with grouping items, but this could add a great deal of extra flexibility to the sorting options in arkinventory if this could be implemented.

**Comment by arkayenro** [comment]
item level is the pet level so you can use that in your sort method

**Comment by artibyrd** [comment]
I was hoping that would be so and tried that first, but when I try to sort them by item level they don't appear to change order.  I will try this again later and take a screenshot.

**Comment by artibyrd** [comment]
![wowscrnshot_090918_110848](https://user-images.githubusercontent.com/13245703/45267427-ed6b8580-b420-11e8-8cfd-7c927369790b.jpg)

I created a user defined "Pets" Sorting Method and applied it to my Pets in Designs(Styles/Layouts).  I tried sorting by either item (stat) level or item (use) level, but neither changed the sort order at all from what you see in the screenshot for my pets.  Sorting by id, item name, or item rarity seem to be the only options that do anything for pets.

This is when I got to thinking that adding a row to the sorting methods where you could add a user defined rule variable could work here, and might add a lot of extra flexibility and depth to the sorting possibilities with this addon.

**Comment by arkayenro** [comment]
try assigning teh sorting directly to the bar and see if that makes any difference

**Comment by arkayenro** [comment]
found the bug, will be fixed in the next release

**Comment by artibyrd** [comment]
Brilliant, it works now!  Sorting by item (stat) level works perfectly with pets in the latest release.  Thank you so much!  This is one of the few addons I simply can't play WoW without, I'm thrilled you so actively maintain it.  :-)

This solves my particular issue, but I think a sort by custom rule variable option would be cool.  ;-)
