### ISSUE TITLE
Custom Catagory option not working

### ISSUE THREAD

**Issue by Hermagesty** [arkayenro/arkinventory#1115]
Tried to make a Custom Cat for my Hearthstone. A blank page came up. Turned off all addons. still just a blank page.

got error 
Date: 2018-09-09 19:04:12
ID: 1
Error occured in: Global
Count: 1
Message: ...ceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua line 1543:
   attempt to index local 'group' (a nil value)
Debug:
   ...ceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1543: FeedGroup()
   ...ceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1863: Open()
   ArkInventory\ArkInventoryConfig.lua:21: Frame_Config_Show()
   ArkInventory\ArkInventoryMenu.lua:1540: func()
   ...e\AddOns\ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua:727:
      ...e\AddOns\ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua:666
Locals:
self = <table> {
 ConfigTableChanged = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1760
 CloseAll = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1741
 Close = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1751
 SetDefaultSize = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1771
 Open = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1786
 AddToBlizOptions = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1917
 OpenFrames = <table> {
 }
 GetStatusTable = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:406
 BlizOptions = <table> {
 }
 Status = <table> {
 }
 frame = <unnamed> {
 }
 FeedGroup = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1531
 SelectGroup = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:436
}
appName = "ArkInventory"
options = <table> {
 childGroups = "tab"
 type = "group"
 name = "ArkInventory"
 args = <table> {
 }
}
container = <table> {
 OnRelease = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\widgets\AceGUIContainer-Frame.lua:93
 OnWidthSet = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\widgets\AceGUIContainer-Frame.lua:98
 SetStatusText = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\widgets\AceGUIContainer-Frame.lua:123
 sizer_se = <unnamed> {
 }
 sizer_e = <unnamed> {
 }
 base = <table> {
 }
 EnableResize = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\widgets\AceGUIContainer-Frame.lua:135
 userdata = <table> {
 }
 status = <table> {
 }
 LayoutFunc = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\AceGUI-3.0.lua:600
 SetStatusTable = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\widgets\AceGUIContainer-Frame.lua:143
 Hide = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\widgets\AceGUIContainer-Frame.lua:127
 OnHeightSet = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\widgets\AceGUIContainer-Frame.lua:108
 type = "Frame"
 AceGUIWidgetVersion = 26
 OnAcquire = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\widgets\AceGUIContainer-Frame.lua:83
 children = <table> {
 }
 SetTitle = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\widgets\AceGUIContainer-Frame.lua:118
 ApplyStatus = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\widgets\AceGUIContainer-Frame.lua:149
 titletext = <unnamed> {
 }
 Show = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\widgets\AceGUIContainer-Frame.lua:131
 statustext = <unnamed> {
 }
 events = <table> {
 }
 frame = <unnamed> {
 }
 sizer_s = <unnamed> {
 }
 titlebg = <unnamed> {
 }
 content = <unnamed> {
 }
 localstatus = <table> {
 }
}
rootframe = <table> {
 OnRelease = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\widgets\AceGUIContainer-Frame.lua:93
 OnWidthSet = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\widgets\AceGUIContainer-Frame.lua:98
 SetStatusText = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\widgets\AceGUIContainer-Frame.lua:123
 sizer_se = <unnamed> {
 }
 sizer_e = <unnamed> {
 }
 base = <table> {
 }
 EnableResize = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\widgets\AceGUIContainer-Frame.lua:135
 userdata = <table> {
 }
 status = <table> {
 }
 LayoutFunc = <function> defined @Interface\AddOns\ArkInventory\Externa
AddOns:
  Swatter, v7.7.6095 (SwimmingSeadragon)
  AllTheThings, v1.7.0
  ArkInventory, v30812
  ArkInventoryConfig, v10200
  ArkInventoryRules, v10200
  ArkInventorySearch, v10200
  AucAdvanced, v7.7.6112 (SwimmingSeadragon)
  AucFilterBasic, v7.7.6081 (SwimmingSeadragon)
  AucScanData, v7.7.6082 (SwimmingSeadragon)
  AucStatHistogram, v7.7.6083 (SwimmingSeadragon)
  AucStatiLevel, v7.7.6087 (SwimmingSeadragon)
  AucStatPurchased, v7.7.6084 (SwimmingSeadragon)
  AucStatSimple, v7.7.6085 (SwimmingSeadragon)
  AucStatStdDev, v7.7.6086 (SwimmingSeadragon)
  AucUtilFixAH, v7.7.6088 (SwimmingSeadragon)
  AutoRepair, v
  BeanCounter, v7.7.6110 (SwimmingSeadragon)
  Coordinates, v2.03
  Enchantrix, v7.7.6104 (SwimmingSeadragon)
  Informant, v7.7.6092 (SwimmingSeadragon)
  LibDFramework10, v
  LiteMount, v8.0.8
  MountSpy, v8.0.0-2
  Pawn, v2.2.28
  SexyMap, vv8.0.8
  SlideBar, v7.7.6093 (SwimmingSeadragon)
  Storyline, v3.0.2
  Stubby, v7.7.6094 (SwimmingSeadragon)
  SYH, v
  TomTom, vv80001-1.0.2
  WorldQuestTab, v8.0.08c
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=42b)

**Comment by arkayenro** [comment]
its fixed in one of the 3.08.13 alphas, there was another ticket for this but i cant find it

**Comment by arkayenro** [comment]
fixed in 3.08.13
