### ISSUE TITLE
itemtype/type in rule not working

### ISSUE THREAD

**Issue by mrbryo** [arkayenro/arkinventory#1116]
I've created a rule:

![20180910-arkrule-type-gem](https://user-images.githubusercontent.com/1635119/45284606-d7e47300-b495-11e8-89f4-eb7da06549a4.PNG)

Here are the details for one of the gems but they all have the same type or "pt".

![20180910-gem-details](https://user-images.githubusercontent.com/1635119/45284607-d7e47300-b495-11e8-8116-88ec6c41b209.PNG)

I've tried "item", "itemtype" and "pt" all separately. I've read through the wiki trying to see if I missed something but don't think I have. Happy to help troubleshoot.

**Comment by arkayenro** [comment]
that rule should work as just item("gem") - or you could just use the system category

double check youve actually enabled that rule.  go into edit mode, click on any bar number, under Assignable Categories click on Rules, click on the rule, make sure the status is enabled, if its not then click on the status to swap it

**Comment by mrbryo** [comment]
Drat! Yeah that was it. Once I enabled the rule it worked. But then I deleted it and used the System category I missed. Thanks!
