### ISSUE TITLE
Item Tracking

### ISSUE THREAD

**Issue by Kirbdawg** [arkayenro/arkinventory#1118]
After a restart of the wow client, the icons that are displayed on my broker-display are generic icons instead of the icons that would normally represent the item that I'm tracking.  If I add something else to item tracking, these generic icons will revert back to what they are supposed to be.  

The icons for currency tracking work properly.  I've tried this using both TitanPanel and Bazooka.  This problem persist with only Arkinventory and my broker-display addons enabled.

**Comment by arkayenro** [comment]
might be fixed in the 3.08.15, not sure

**Comment by Kirbdawg** [comment]
Ty.  Not a problem now.
