### ISSUE TITLE
Cannot Split Stacks In Guild Bank Window

### ISSUE THREAD

**Issue by nomisuke** [arkayenro/arkinventory#1127]
Greetings!

Shift-clicking a stack in the guild bank window does not split the stack anymore after patch 8.1. Players must move the stack to their bags, split it, and then move it back to the guild bank. Not a big problem and most likely only noticeable for GMs or players with unlimited access. This was not an issue until after 8.1 was released. Otherwise, everything looks great!

Included is the Swatter! file. I ran arkinventory with no other addons first, then enabled Swatter! so I could record the event for your records.

Thank you!

Date: 2018-12-17 01:20:40
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ArkInventory\ArkInventory.lua line 8106:
   attempt to call global 'OpenStackSplitFrame' (a nil value)
Debug:
   ArkInventory\ArkInventory.lua:8106: Frame_Item_OnMouseUp()
   [string "*:OnMouseUp"]:1:
      [string "*:OnMouseUp"]:1
Locals:
frame = ARKINV_Frame4ScrollContainerBag7Item87 {
 GetItemLocation = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:168
 ArkTransmogIcon = ARKINV_Frame4ScrollContainerBag7Item87ArkTransmogIcon {
 }
 BattlepayItemTexture = <unnamed> {
 }
 SetItemMatchesItemContext = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:182
 IconOverlay = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 icon = ARKINV_Frame4ScrollContainerBag7Item87IconTexture {
 }
 ArkBagHighlight = ARKINV_Frame4ScrollContainerBag7Item87ArkBagHighlight {
 }
 ExtendedOverlay = <unnamed> {
 }
 ARK_Data = <table> {
 }
 UpgradeIcon = <unnamed> {
 }
 UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:191
 NewItemTexture = <unnamed> {
 }
 SplitStack = <function> defined @Interface\AddOns\ArkInventory\ArkInventory.lua:8614
 BagStaticBottom = <unnamed> {
 }
 ArkBorder = ARKINV_Frame4ScrollContainerBag7Item87ArkBorder {
 }
 ItemContextOverlay = <unnamed> {
 }
 ArkListEntry = ARKINV_Frame4ScrollContainerBag7Item87ArkListEntry {
 }
 GetItemContextMatch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:187
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 hasItem = 1
 ArkItemTinted = ARKINV_Frame4ScrollContainerBag7Item87ArkItemTinted {
 }
 JunkIcon = <unnamed> {
 }
 SetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:173
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:205
 0 = <userdata>
 count = 200
 locked = false
 timeSinceUpgradeCheck = 0
 UpdateTooltip = <function> defined @Interface\AddOns\ArkInventory\ArkInventory.lua:7963
 Count = ARKINV_Frame4ScrollContainerBag7Item87Count {
 }
 flash = <unnamed> {
 }
 ArkAgeText = ARKINV_Frame4ScrollContainerBag7Item87ArkAgeText {
 }
 searchOverlay = ARKINV_Frame4ScrollContainerBag7Item87SearchOverlay {
 }
 flashAnim = <unnamed> {
 }
 GetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:178
}
button = "LeftButton"
loc_id = 4
i = <table> {
 q = 1
 bag_id = 7
 h = "[Sumptuous Fur]"
 slot_id = 87
 sb = 0
 count = 200
 loc_id = 4
 did = 41
 age = 25724516
}
tab_id = 7
slot_id = 87
(*temporary) = nil
(*temporary) = 200
(*temporary) = ARKINV_Frame4ScrollContainerBag7Item87 {
 GetItemLocation = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:168
 ArkTransmogIcon = ARKINV_Frame4ScrollContainerBag7Item87ArkTransmogIcon {
 }
 BattlepayItemTexture = <unnamed> {
 }
 SetItemMatchesItemContext = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:182
 IconOverlay = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 icon = ARKINV_Frame4ScrollContainerBag7Item87IconTexture {
 }
 ArkBagHighlight = ARKINV_Frame4ScrollContainerBag7Item87ArkBagHighlight {
 }
 ExtendedOverlay = <unnamed> {
 }
 ARK_Data = <table> {
 }
 UpgradeIcon = <unnamed> {
 }
 UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:191
 NewItemTexture = <unnamed> {
 }
 SplitStack = <function> defined @Interface\AddOns\ArkInventory\ArkInventory.lua:8614
 BagStaticBottom = <unnamed> {
 }
 ArkBorder = ARKINV_Frame4ScrollContainerBag7Item87ArkBorder {
 }
 ItemContextOverlay = <unnamed> {
 }
 ArkListEntry = ARKINV_Frame4ScrollContainerBag7Item87ArkListEntry {
 }
 GetItemContextMatch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:187
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 hasItem = 1
 ArkItemTinted = ARKINV_Frame4ScrollContainerBag7Item87ArkItemTinted {
 }
 JunkIcon = <unnamed> {
 }
 SetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:173
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:205
 0 = <userdata>
 count = 200
 locked = false
 timeSinceUpgradeCheck = 0
 UpdateTooltip = <function> defined @Interface\AddOns\ArkInventory\ArkInventory.lua:7963
 Count 
AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  ArkInventory, v30816
  ArkInventoryRules, v10300
  ArkInventoryRulesExample, v10000
  ArkInventorySearch, v10300
  BlizRuntimeLib_enUS v8.1.0.80100 <none>
  (ck=c6)

**Comment by Obsurd** [comment]
Finally decided to try to figure out what was causing this and came here to report the same.

**Comment by arkayenro** [comment]
looks like blizzard changed OpenStackSplitFrame, will be fixed in the next release

**Comment by nomisuke** [comment]
Thank you so much for the timely response! I have every confidence that this will be taken care of. Love the addon!

**Comment by nomisuke** [comment]
I saw. You rock.
