### ISSUE TITLE
Implement caching around ObjectStringDecode for significant performance benefits

### ISSUE THREAD

**Issue by ascott18** [arkayenro/arkinventory#1128]
I recently got to the point where I was fed up with how much of a performance hit I was taking when hovering over items, due to the time that ArkInventory takes to populate the tooltips of item counts (related: #1025). I turned on CPU profiling, reloaded, opened my bags (without mousing over anything), reset CPU usage numbers, and then proceded to mouse over every item in my bags (108 items total).

This was the result: 
![image](https://user-images.githubusercontent.com/5017521/50380922-1eb53d80-062d-11e9-923d-e317e460d019.png)

That's 6 seconds spent just parsing item hyperlinks, which is a function that will always produce the same output for a given input. I realize there's a second parameter `i` in that method that may throw off caching, but it should be possible to pull the parts of the function out that aren't dependent on that parameter, and cache those results. 

There also appears to be a table allocation in this function, `local z = { strsplit( ":", s ) }`, which is identical to another allocation `local v = { strsplit( ":", s ) }`, but `z` is only ever used exactly once. I can't see a good reason for the usage of `z` to not be a usage of `v` instead.

I'd also question why there needs to be 462,391 hyperlink parses in order to populate the tooltips for 108 items in my bags, but maybe that's a question for another day.

**Comment by ascott18** [comment]
After adding in some basic caching (ignoring caching with a value is provided for `i`), these are the results:

https://gist.github.com/ascott18/c5e8044b9bf5ab383b2bd2cca8f03889

![image](https://user-images.githubusercontent.com/5017521/50386995-785a4e00-06a7-11e9-9c63-3b324e8041d2.png)

6 seconds of ObjectStringDecode reduced to 121ms.

**Comment by ascott18** [comment]
With caching on `ObjectIDCount` in addition to `ObjectStringDecode`: 

![image](https://user-images.githubusercontent.com/5017521/50387141-0afbec80-06aa-11e9-9f45-8aaa664a6bdf.png)

Total usage between `ObjectStringDecode` and `ObjectIDCount` reduced from 7635ms to 73ms, for a 100x improvement.

**Comment by arkayenro** [comment]
how did you get the cpu profiling?  is it inbuilt or an addon?

i is for empty slots so a virtual hyperlink can be created, i can probably move that chunk of code up into that section and it doesnt get run that often, mostly when youre in edit mode

z is for reputation data but i can probably rearrange the code to work around it

i wouldnt worry about ObjectIDCount, its just a wrapper to generate a table key that pulls data from ObjectStringDecode and does a string.format - making ObjectStringDecode faster will automatically make it faster as well

**Comment by ascott18** [comment]
CPU profiling is built in, but you need an addon if you want a UI. The screenshots of of Resource Tools (https://www.wowinterface.com/downloads/info7175-ResourceTools.html#info) - [ResourceTools.zip](https://github.com/arkayenro/arkinventory/files/2706443/ResourceTools.zip) is my own copy because the latest update at that link is from 2009, and I've updated my local copy to keep it working through the patches.

`/rt cpu` to turn on profiling, then reload, then `/rt ui` to show the window. Make sure to turn profiling back off when you're done, because it will slow down your game when its on. `/rt reset` to reset statistics.

There are noticeable savings when putting caching around both methods - around 800ms. This is largely because you avoid the overhead of two function calls and at least one string allocation when you get a cache hit on ObjectIDCount. This adds up when you have 400k calls of the method.

**Comment by arkayenro** [comment]
[r796-alpha](https://www.wowace.com/projects/ark-inventory/files/2651854) is available if you want to test that

**Comment by ascott18** [comment]
Definitely an improvement, but there is still noticeable FPS drop without the caching on `ObjectIDCount`. When I add caching to `ObjectIDCount`, FPS drop is virtually non-existent.

A function call - in this case, the calls to `ObjectStringDecode` and then to `string.format` inside `ObjectIDCount`, have a non-trivial amount of overhead - especially when you're talking about over 400k calls. If you add caching to `ObjectIDCount`, there will be a marked improvement.

I also want to address the way that you implemented the caching in `ObjectStringDecode`. The cache is only checked _after_ at least 3, and potentially up to 5, function calls. Those function calls have their own overhead, but there's lots of code in between that also has overhead. Lets look at the bytecode for the following bit of the code:

``` lua
local h = string.trim( h or "" )

if h == "" and i and not i.h then
    -- virtual hyperlink for empty slots passed via i
    h = ArkInventory.ObjectIDCategory( i )
end

local n = string.match( h, "|h%[(.-)]|h" ) or ""
local s = string.match( h, "|H(.-)|h" ) or string.match( h, "^([a-z]-:.+)" ) or "empty:0:0"

if ArkInventory.Global.Cache.OSD[s] then
    return ArkInventory.Global.Cache.OSD[s]
end
```

The Lua bytecode that comes from this:
```
function <.\osd.lua:10,26> (55 instructions, 220 bytes at 00821DD8)
2 params, 7 slots, 1 upvalue, 5 locals, 13 constants, 0 functions
        1       [12]    GETUPVAL        2 0     ; string
        2       [12]    GETTABLE        2 2 -1  ; "trim"
        3       [12]    TESTSET         3 0 1
        4       [12]    JMP             1       ; to 6
        5       [12]    LOADK           3 -2    ; ""
        6       [12]    CALL            2 2 2
        7       [14]    EQ              0 2 -2  ; - ""
        8       [14]    JMP             10      ; to 19
        9       [14]    TEST            1 0 0
        10      [14]    JMP             8       ; to 19
        11      [14]    GETTABLE        3 1 -3  ; "h"
        12      [14]    TEST            3 0 1
        13      [14]    JMP             5       ; to 19
        14      [16]    GETGLOBAL       3 -4    ; ArkInventory
        15      [16]    GETTABLE        3 3 -5  ; "ObjectIDCategory"
        16      [16]    MOVE            4 1
        17      [16]    CALL            3 2 2
        18      [16]    MOVE            2 3
        19      [19]    GETUPVAL        3 0     ; string
        20      [19]    GETTABLE        3 3 -6  ; "match"
        21      [19]    MOVE            4 2
        22      [19]    LOADK           5 -7    ; "|h%[(.-)]|h"
        23      [19]    CALL            3 3 2
        24      [19]    TEST            3 0 1
        25      [19]    JMP             1       ; to 27
        26      [19]    LOADK           3 -2    ; ""
        27      [20]    GETUPVAL        4 0     ; string
        28      [20]    GETTABLE        4 4 -6  ; "match"
        29      [20]    MOVE            5 2
        30      [20]    LOADK           6 -8    ; "|H(.-)|h"
        31      [20]    CALL            4 3 2
        32      [20]    TEST            4 0 1
        33      [20]    JMP             8       ; to 42
        34      [20]    GETUPVAL        4 0     ; string
        35      [20]    GETTABLE        4 4 -6  ; "match"
        36      [20]    MOVE            5 2
        37      [20]    LOADK           6 -9    ; "^([a-z]-:.+)"
        38      [20]    CALL            4 3 2
        39      [20]    TEST            4 0 1
        40      [20]    JMP             1       ; to 42
        41      [20]    LOADK           4 -10   ; "empty:0:0"
        42      [22]    GETGLOBAL       5 -4    ; ArkInventory
        43      [22]    GETTABLE        5 5 -11 ; "Global"
        44      [22]    GETTABLE        5 5 -12 ; "Cache"
        45      [22]    GETTABLE        5 5 -13 ; "OSD"
        46      [22]    GETTABLE        5 5 4
        47      [22]    TEST            5 0 0
        48      [22]    JMP             6       ; to 55
        49      [23]    GETGLOBAL       5 -4    ; ArkInventory
        50      [23]    GETTABLE        5 5 -11 ; "Global"
        51      [23]    GETTABLE        5 5 -12 ; "Cache"
        52      [23]    GETTABLE        5 5 -13 ; "OSD"
        53      [23]    GETTABLE        5 5 4
        54      [23]    RETURN          5 2
        55      [26]    RETURN          0 1
```

That's 54 instructions just to check the cache. If we ignore caching when `i` is non-nil, then we can skip the branch that calls to `ObjectIDCategory`. This then makes `s`, your current cache key, a deterministic result of `h`, which means we could skip the usage of `s` as the cache key and instead go straight to using `h` as the cache key instead (again, only if `i == nil`)

We're now down to this:
``` lua
h = h or ""
if not i then
    if ArkInventory.Global.Cache.OSD[h] then
        return ArkInventory.Global.Cache.OSD[h]
    end
end
-- Continue on to the rest of the code...
--[[
h = string.trim( h or "" )

if h == "" and i and not i.h then
    -- virtual hyperlink for empty slots passed via i
    h = ArkInventory.ObjectIDCategory( i )
end

local n = string.match( h, "|h%[(.-)]|h" ) or ""
local s = string.match( h, "|H(.-)|h" ) or string.match( h, "^([a-z]-:.+)" ) or "empty:0:0"

]]
```

With the following bytecode produced from it:
```
function <.\osd.lua:10,17> (19 instructions, 76 bytes at 007E1DD8)
2 params, 3 slots, 0 upvalues, 2 locals, 5 constants, 0 functions
        1       [11]    TEST            0 0 1
        2       [11]    JMP             1       ; to 4
        3       [11]    LOADK           0 -1    ; ""
        4       [12]    TEST            1 0 1
        5       [12]    JMP             13      ; to 19
        6       [13]    GETGLOBAL       2 -2    ; ArkInventory
        7       [13]    GETTABLE        2 2 -3  ; "Global"
        8       [13]    GETTABLE        2 2 -4  ; "Cache"
        9       [13]    GETTABLE        2 2 -5  ; "OSD"
        10      [13]    GETTABLE        2 2 0
        11      [13]    TEST            2 0 0
        12      [13]    JMP             6       ; to 19
        13      [14]    GETGLOBAL       2 -2    ; ArkInventory
        14      [14]    GETTABLE        2 2 -3  ; "Global"
        15      [14]    GETTABLE        2 2 -4  ; "Cache"
        16      [14]    GETTABLE        2 2 -5  ; "OSD"
        17      [14]    GETTABLE        2 2 0
        18      [14]    RETURN          2 2
        19      [17]    RETURN          0 1
```

Down from 54 instructions to 18, with zero function calls needed to check for a cache hit.

The final thing we can do is remove the GETGLOBAL call (which is relatively expensive) and GETTABLE chaining that result from your cache being stored at `ArkInventory.Global.Cache.OSD`. If you reduce this down to just a local declared above the function, then you drop quite a few additional instructions:

``` lua
local osdCache = {}
function ArkInventory.ObjectStringDecode( h, i )
    h = h or ""
    if not i then
        if osdCache[h] then
            return osdCache[h]
        end
    end
    -- Continue on to the rest of the code...
end
```

We're now down to 12 instructions:
```
function <.\osd.lua:11,18> (13 instructions, 52 bytes at 007A1CB0)
2 params, 3 slots, 1 upvalue, 2 locals, 1 constant, 0 functions
        1       [12]    TEST            0 0 1
        2       [12]    JMP             1       ; to 4
        3       [12]    LOADK           0 -1    ; ""
        4       [13]    TEST            1 0 1
        5       [13]    JMP             7       ; to 13
        6       [14]    GETUPVAL        2 0     ; osdCache
        7       [14]    GETTABLE        2 2 0
        8       [14]    TEST            2 0 0
        9       [14]    JMP             3       ; to 13
        10      [15]    GETUPVAL        2 0     ; osdCache
        11      [15]    GETTABLE        2 2 0
        12      [15]    RETURN          2 2
        13      [18]    RETURN          0 1
```

We can get down to 10 instructions if we only perform one table lookup:
``` lua
local osdCache = {}
function ArkInventory.ObjectStringDecode( h, i )
    h = h or ""
    if not i then
        local cached = osdCache[h]
        if cached then 
            return cached 
        end
    end
    -- Continue on to the rest of the code...
end
```

```
function <.\osd.lua:11,19> (11 instructions, 44 bytes at 00831CB0)
2 params, 3 slots, 1 upvalue, 3 locals, 1 constant, 0 functions
        1       [12]    TEST            0 0 1
        2       [12]    JMP             1       ; to 4
        3       [12]    LOADK           0 -1    ; ""
        4       [13]    TEST            1 0 1
        5       [13]    JMP             5       ; to 11
        6       [14]    GETUPVAL        2 0     ; osdCache
        7       [14]    GETTABLE        2 2 0
        8       [15]    TEST            2 0 0
        9       [15]    JMP             1       ; to 11
        10      [16]    RETURN          2 2
        11      [19]    RETURN          0 1
```
 

So, you can see why I did things the way I did in the gist the I linked in my [second comment](https://github.com/arkayenro/arkinventory/issues/1128#issuecomment-449659381) - we've reduced 54 instructions and 3 to 5 function calls down to 10 instructions and 0 function calls in order to check the cache.


`ObjectIDCount` has 22 instructions in its current form, including two function calls:
``` lua
function <.\osd.lua:22,29> (22 instructions, 88 bytes at 00988F38)
1 param, 6 slots, 1 upvalue, 2 locals, 8 constants, 0 functions
        1       [23]    GETGLOBAL       1 -1    ; ArkInventory
        2       [23]    GETTABLE        1 1 -2  ; "ObjectStringDecode"
        3       [23]    MOVE            2 0
        4       [23]    CALL            1 2 2
        5       [24]    GETTABLE        2 1 -3  ; "class"
        6       [24]    EQ              0 2 -4  ; - "keystone"
        7       [24]    JMP             7       ; to 15
        8       [25]    GETUPVAL        2 0     ; string
        9       [25]    GETTABLE        2 2 -5  ; "format"
        10      [25]    LOADK           3 -6    ; "item:%s"
        11      [25]    GETTABLE        4 1 -7  ; "id"
        12      [25]    TAILCALL        2 3 0
        13      [25]    RETURN          2 0
        14      [25]    JMP             7       ; to 22
        15      [27]    GETUPVAL        2 0     ; string
        16      [27]    GETTABLE        2 2 -5  ; "format"
        17      [27]    LOADK           3 -8    ; "%s:%s"
        18      [27]    GETTABLE        4 1 -3  ; "class"
        19      [27]    GETTABLE        5 1 -7  ; "id"
        20      [27]    TAILCALL        2 4 0
        21      [27]    RETURN          2 0
        22      [29]    RETURN          0 1
```

If you cache `ObjectIdCount` in the same way, you can similarly reduce the hot path of that function down to 10 instructions and zero function calls. Right now, I'm still getting nearly 800ms spent on `ObjectIDCount`, which as I mentioned above is causing VERY noticeable framerate drops as I move my cursor around on my bags.


This sort of instruction-level optimization normally isn't needed, but you have a function that is getting called over 400k times - this is an extraordinary circumstance that warrants extraordinary optimzation.

**Comment by arkayenro** [comment]
try [r798-alpha](https://www.wowace.com/projects/ark-inventory/files/2652147)

**Comment by ascott18** [comment]
Pretty good - not noticeable framerate drops now. Thanks.
