### ISSUE TITLE
bag icons and Deposit all Reagents option missing

### ISSUE THREAD

**Issue by PaigePB** [arkayenro/arkinventory#1130]
With BFA the bag icons at the bottom of the ark inventory screen (with the ability to one-click 'deposit all reagents') has gone missing.

![image](https://user-images.githubusercontent.com/30805995/50388825-d2cacd00-06ee-11e9-80a1-dc13b401f51a.png)

**Comment by arkayenro** [comment]
you need to enable the changer frame for that location

not in game at them moment but i think theres a shortcut for doing that somewhere or its in the config

pretty sure you can also right click on the restack icon to get at the deposit all reagents action
