### ISSUE TITLE
Bar settings not saving for different profiles

### ISSUE THREAD

**Issue by dehumanize** [arkayenro/arkinventory#1131]
I set up a profile called plate for my warrior. I then created bar 6 to use the ' type( "armor" ) and subtype( "plate" ) ' rule. Then logged onto my rogue, set up a 2nd profile called leather. Using the same armor rule and changing the field from plate to leather and set bar 6 to use that rule under the leather profile. However when I logged back to my warrior he was still using the plate profile, but the leather rule for the bar was active. I checked the default profile, and the bar setup is still maintained from the leather profile, even though I set up bar 6 to be BOP on the default profile.

Here is an imgur showing me under the leather profile, but in bar 6 it's showing the plate rule active and the bar is named Plate Gear - https://imgur.com/a/DzRi9Dp

**Comment by arkayenro** [comment]
the rules are global.  enabling/disabling them is per profile

so create two rules, one for plate one for leather and then in each profile only enable the appropriate rule, leave the other one disabled

**Comment by arkayenro** [comment]
sorry, its not per profile its per category set, make sure that the two profiles are using completely different category sets (currently under controls)

im moving the control options into the profiles area to make it more obvious
