### ISSUE TITLE
Bag auto closing

### ISSUE THREAD

**Issue by xEgdodx** [arkayenro/arkinventory#1132]
For the last couple of days my bags will only stay open for a few seconds then close automatically

**Comment by arkayenro** [comment]
what version are you running?

and can you disable all other mods and test.

if it works then enable addons in chunks until it doesnt work to find out which mod is causing it

**Comment by xEgdodx** [comment]
3.08.20  When I logged back on after getting your response it seems to be working fine, so not sure what the issue was.  I'm only running Recount and DBM in addition to yours.  There have been times my game gets really laggy, and when I turn of your mod it seems to help, but I guess that's not very scientific.  Anyway, ever since Bagnon went dead I've been using yours, it's great, thanks for making it.

    On Thursday, January 10, 2019, 6:03:27 PM PST, arkayenro <notifications@github.com> wrote:  
 
 
what version are you running?

and can you disable all other mods and test.

if it works then enable addons in chunks until it doesnt work to find out which mod is causing it

**Comment by arkayenro** [comment]
reopen this or create a new one if it starts up again
