### ISSUE TITLE
CanIMogIt users and 3.08.21 or higher - read this first

### ISSUE THREAD

**Issue by arkayenro** [arkayenro/arkinventory#1136]
i changed the code around in 3.08.21 which sort of broke CanIMogIt working with ArkInventory

to make it work again you need to move or copy `...\Addons\ArkInventory\Plugins\CanIMogIt\arkinventory.lua` to `...\Addons\CanIMogIt\Plugins\arkinventory.lua`

at least until CanIMogIt has been updated to match the new code

**Comment by Calesta** [comment]
I'm not sure if the project owners at CanIMogIt know that there are changes needed to work with ArkInventory as it was working perfectly fine before.  It's not clear what they need to update but someone with some understanding of the changes made will probably have to post in the 'Issues' section of the CanIMogIt project.

**Comment by arkayenro** [comment]
they probably dont, all i've done is update the file thats needed to work with arkinventory.  they can either just use it as is or double check and re-code as required

**Comment by Calesta** [comment]
I posted something on the CanIMogIt project page.  Thanks.

**Comment by Calesta** [comment]
Arkayenro, I haven't seen the referenced release yet but FYI.

https://wow.curseforge.com/projects/can-i-mog-it/issues/202

> Thank you very much for your report.  This will be fixed in our release for 8.2 on Tuesday.  GitLab ticket: https://gitlab.com/toreltwiddler/CanIMogIt/issues/205
