### ISSUE TITLE
layout not updating for new items

### ISSUE THREAD

**Issue by Loqy0815** [arkayenro/arkinventory#1139]
Hi there,

since 1-2 weeks I'm getting a strange behavior.

for most new items it looks like the layout, positions, size are not updating as expected.
See screenshot:
![image](https://user-images.githubusercontent.com/46353929/52630379-025ab200-2eb4-11e9-9545-6b5da8b7bb04.png)

after a while (i guess after the "new item glow" has faded) they show up fine.

Could very likely be a user error, but.. I have no idea what i've done.. xD

**Comment by arkayenro** [comment]
try the latest alpha build, 815 i think, there were some issues with item drawing that wouldnt notice unless you also scaled them

**Comment by Loqy0815** [comment]
sorry for the late reply (thought I'd get an email notification or something)

just updated to r815-alpha and everything worked fine in a quick test.
thanks!
