### ISSUE TITLE
How to make Arkinventory use profession bags

### ISSUE THREAD

**Issue by billi95** [arkayenro/arkinventory#1140]
I use the https://de.wowhead.com/item=54446/hyjalexpeditionstasche the https://de.wowhead.com/item=44446/tasche-der-endlosen-f%C3%A4cher and the https://de.wowhead.com/item=60218/k%C3%B6dermeister-spinnerkasten
All 3 are not recognised by arkinventory.

I want to edit arkinventory in a way so it moves the fitting items into the bag when I press the sorting button. How can I do that

**Comment by arkayenro** [comment]
youd have to download the last alpha version, its in there

**Comment by billi95** [comment]
and how do I do that? Or to be more precisely where can I find the new alpha?

**Comment by arkayenro** [comment]
from the curse project site, or you can set the twitch client to check for beta versions for arkinventory
https://www.wowace.com/projects/ark-inventory/files

**Comment by arkayenro** [comment]
added to 3.08.23
