### ISSUE TITLE
Anchor points don't change

### ISSUE THREAD

**Issue by dodspringer** [arkayenro/arkinventory#1141]
Changing the anchor point does nothing, returns this error:

ArkInventory: ERROR> bad code. myprofiles:profiles:1004:control does not have an arg value.  requested from myprofiles:profiles:1004:control:3:anchor

Doesn't matter which profile I'm in as it didn't work when there was just one, either.

**Comment by arkayenro** [comment]
will be fixed in the next release

**Comment by dodspringer** [comment]
Thanks! I'll keep my eyes peeled :)

**Comment by arkayenro** [comment]
fixed in 3.08.23
