### ISSUE TITLE
Weird stuttering/FPS drop issues in r816-r817

### ISSUE THREAD

**Issue by halfreak** [arkayenro/arkinventory#1143]
Hi! Now this is a tricky one I guess. Since the r816 update I've been having these stuttering/micro freezing issues in some situations. It's most apparent in tortollan WQs (mostly shell game I think) and when sprinting with my rogue. When I roll back to r815 the issue goes away. 

I couldn't replicate this issue with only ArkInventory installed. My guess is AI is calling for some API event every second or so and some other addon(s) start doing their things based on this event, thus affecting performance. And I know I'm an addon junkie, and have too many of them installed.

I don't know if this is making any sense, so I've recorded a small video: https://youtu.be/jF8_CXd51KU Sorry, my loading times are abysmal (too many addons + an HDD is a bad combo), r815 sprint test is at about 1:40 mark.

**Comment by arkayenro** [comment]
that really is weird, you dont have AI open and youre not really doing anything that would trigger any events that AI would need to do something about (mousing over items sort of thing where an item count would kick in)

all i can think of is perhaps one of the background threads got stuck in a loop somehow so keeps running.  can you enable thread debug in the config and see if they all die nicely or not.

**Comment by arkayenro** [comment]
815 to 816 was just display code and a new restack option, so only stuff that impacts active drawing.  i dont recall changing anything at the background/event level

816 to 817 was a code syntax error in the rules so its not in that

**Comment by joevt** [comment]
Try a code profiling add-on like CPUThieves to find the code that is causing the problem.

**Comment by halfreak** [comment]
OK, I've tried to look for anything suspicious for about 10 minutes, and the only thing that jumped at me was this output from r817:

`[15:06:44] ArkInventory: THREAD> p4-draw-13 aborting, not visible
[15:06:44] ArkInventory: THREAD> p4-draw-7 aborting, not visible
[15:06:44] ArkInventory: THREAD> p4-draw-1 aborting, not visible
[15:06:44] ArkInventory: THREAD> p4-draw-4 aborting, not visible
[15:06:44] ArkInventory: THREAD> p4-draw-8 aborting, not visible
[15:06:44] ArkInventory: THREAD> p4-draw-16 aborting, not visible
[15:06:44] ArkInventory: THREAD> p4-draw-9 aborting, not visible
[15:06:44] ArkInventory: THREAD> p4-draw-5 aborting, not visible
[15:06:44] ArkInventory: THREAD> p4-draw-10 aborting, not visible
[15:06:44] ArkInventory: THREAD> p4-draw-3 aborting, not visible
[15:06:44] ArkInventory: THREAD> p4-draw-6 aborting, not visible
[15:06:44] ArkInventory: THREAD> p4-draw-15 aborting, not visible
[15:06:44] ArkInventory: THREAD> p4-draw-14 aborting, not visible
[15:06:45] ArkInventory: THREAD> p2-scan-reputation starting
[15:06:45] ArkInventory: THREAD> p2-scan-reputation dead after 3.06ms (3.06ms)
[15:06:45] ArkInventory: THREAD> p2-scan-reputation: clearing (state is dead)`

It's repeating at seemingly random invtervals every couple minutes. I'm not getting this from r815.

**Comment by halfreak** [comment]
No, scratch that, just got this from r815 too, has something to do with nearby WQ.

**Comment by arkayenro** [comment]
if p2-scan-reputation starting keeps coming up then i wonder if the game is triggering an event on your side when other players within range of you gain rep.

i know when another player mounts it will trigger an event you can see which is why i had to stop using it.

**Comment by arkayenro** [comment]
havent found the cause but have found something to test it with

stand in an azerite pool, every tick of that buff will lag

its almost like the tier piece bonus buff back in broken isles used to do weird things and trigger the wrong events

**Comment by arkayenro** [comment]
something in rules is causing it, or at least with rules enabled the lag kicks in with that buff

**Comment by arkayenro** [comment]
not rules, those just make it significantly worse

its tripping a cooldown so is constantly trying to update but its not visible so shouldnt be doing much of anything

**Comment by halfreak** [comment]
OK, so finally I was able to reproduce the issue with just AI installed. I ran WoW on a pretty much potato PC (AMD A4-5300 CPU) and the stuttering is present with r817. I also tried running CPUThieves as @joevt suggested and here's it's output, maybe it'll prove useful. It is sprinting with a rogue and then standing in an azerite pool:

>  		"14:24:17 CPUThieves:    145  8.9s ArkInventory", -- [123]
> 		"14:24:19 CPUThieves:    151  9.0s ArkInventory", -- [124]
> 		"14:24:19 CPUThieves:    141  9.2s ArkInventory", -- [125]
> 		"14:24:21 CPUThieves:    145  9.3s ArkInventory", -- [126]
> 		"14:24:24 CPUThieves:    150  9.5s ArkInventory", -- [127]
> 		"14:24:25 CPUThieves:    163  9.6s ArkInventory", -- [128]
> 		"14:24:28 CPUThieves:    180  9.8s ArkInventory", -- [129]
> 		"14:24:28 CPUThieves:    110  0.1s Function574C1BD0()  C_Timer started from ArkInventory\\ArkInventoryStorage.lua:1242: in function `?'", -- [130]
> 		"14:24:28 CPUThieves:    109  5.9s xpcall()", -- [131]
> 		"14:24:29 CPUThieves:    144  9.9s ArkInventory", -- [132]
> 		"14:24:31 CPUThieves:    144 10.1s ArkInventory", -- [133]
> 		"14:24:33 CPUThieves:    145 10.2s ArkInventory", -- [134]
> 		"14:24:36 CPUThieves:    157 10.4s ArkInventory", -- [135]
> 		"14:24:37 CPUThieves:    105  0.1s Function631256A0()  C_Timer started from ArkInventory\\ArkInventoryStorage.lua:1242: in function `?'", -- [136]
> 		"14:24:37 CPUThieves:    105  6.4s xpcall()", -- [137]
> 		"14:24:38 CPUThieves:    165 10.6s ArkInventory", -- [138]
> 		"14:24:39 CPUThieves:    160 10.7s ArkInventory", -- [139]
> 		"14:24:39 CPUThieves:    100  0.1s Function6312A0A0()  C_Timer started from ArkInventory\\ArkInventoryStorage.lua:1242: in function `?'", -- [140]
> 		"14:24:41 CPUThieves:    144 10.9s ArkInventory", -- [141]

**Comment by arkayenro** [comment]
r818 should hopefully fix it

**Comment by halfreak** [comment]
Man, you're _fast_!

**Comment by joevt** [comment]
The stuttering is gone now, thanks. 

CPUThieves is a simple add-on. By default, it does not profile functions unless they are global and available before the add-on loads. Very few add-ons will load before an add-on that has a name starting with '!' like !CPUThieves. Also, most add-ons have local functions that are not global.

The code of an add-on can be easily modified to explicitly add to the list of functions that CPUThieves is tracking. I might consider trying this the next time a problem occurs, in the case where the output only shows the add-on name like in the example given by halfreak.
