### ISSUE TITLE
[FIX] 8.1.5 ItemButton stopgap fixes

### ISSUE THREAD

**Issue by Koviko** [arkayenro/arkinventory#1149]
I'm consolidating the fixes to this Git issue since Twitch's mod manager is making it tough for people to all be on the same version and I anticipate needing to update this.

---

### Update
**I've uploaded the full addon with the fixes to Google Drive, so you no longer have to deal with the gists.**

»» https://drive.google.com/open?id=1bBlc3EqDqSyAUH5Lg6JTJMrFDg92bJMv ««

Unzip the entire ArkInventory directory to your `WoW/_retail_/Interface/AddOns/` directory and overwrite your existing installation of ArkInventory.

---

> For both of these Gists: **download as ZIP, then extract the two files (`ArkInventory.lua` and `ArkInventory.xml`) to the ArkInventory addon directory and overwrite the existing files.**
> 
> ### IMPORTANT: Do not delete your SavedVariables. This will not help as nothing in your config is causing the issues in 8.1.5!
> 
> # Release
> 
> The Release version is the latest version marked as Stable and is the least likely to have bugs. I recommend using this version, but Twitch's mod manager will recommend the opposite.
> 
> ![Twitch mod manager settings for Release](https://i.imgur.com/170T31i.png)
> 
> If you are using the latest **Release** version `r812` from 2019-01-26:
> 
> »» https://gist.github.com/Koviko/ba5e77d1cd5512019b1b687f9c4c35e0 ««
> 
> Download as ZIP and extract the two files to the ArkInventory addon directory.
> 
> # Alpha
> 
> If you press "Refresh" in the Twitch mod manager, it will probably recommend that you download the latest Alpha version. I'm guessing they assume that post-patch, you want the Alpha version. However, it might have issues simply by virtue of being an Alpha, so I recommend using the Release version if you can. **Take care that you are using `r818-alpha` and not `r818-alpha-nolib`. Twitch may not install the libraries for you.**
> 
> ![Twitch mod manager settings for Alpha](https://i.imgur.com/8v7QpRS.png)
> 
> If you are using the latest **Alpha** version `r818-alpha` from 2019-03-03, you want this Gist:
> 
> »» https://gist.github.com/Koviko/32fd92a848370b67cfc1ac9e556b59bc ««
> 
> Download as ZIP and extract the two files to the ArkInventory addon directory.

**Comment by joevt** [comment]
Did you mean r818-alpha?

**Comment by Ibglitrbug** [comment]
r188-alpha is what you said did you mean r818 ? cause i could not find a 188

**Comment by Ibglitrbug** [comment]
ok removed my saved var, and any other addons i had for bags and reinstalled 818 and put in the download and it still does not work for me. "crys"

**Comment by Koviko** [comment]
Yeah, I meant r818, as in the screenshot. I fixed the description.

**Comment by Ibglitrbug** [comment]
ok .... still didnt work so i went in to the older versions dled 3.08.21 used the fix  you had for that and still nothing guess i will be waiting for him to get home lol ... i want to take a cruse... oh and get home soooooon lol thanks for trying either way.

**Comment by kaseyd24** [comment]
Not working at all.. Box appears, but contents are phased out.. no lines, or method of choosing anything..
Getting error messages
x ArkInventory\ArkInventory.lua:11203: FrameXML\ItemButtonTemplate.lua:65: attempt to index local 'icon' (a nil value)
[C]: ?
ArkInventory\ArkInventory-30821.lua:11203: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = "FrameXML\ItemButtonTemplate.lua:65: attempt to index local 'icon' (a nil value)"

![Screeshot](https://user-images.githubusercontent.com/31021551/54335628-f15ea700-45ff-11e9-8166-7fcb635a598b.jpg)

**Comment by arkayenro** [comment]
thanks to all the people helping.  pinning this so its a bit more obvious

i will be back home on thursday 23rd, so another week, before i can fix anything myself, sorry

note1 - please dont delete your saved variables file, that will just lose your config.  once its fixed/working again the saved variables (your config) will be needed

note2 - feel free to try other bag mods in the mean time, i wont hate you.  you never know, one of them might be better for you

note3 - i also cant access curse or curseforge, twitch is being a pita with authy and wont accept my code so wont authenticate me so i cant post there

**Comment by Caedis** [comment]
@arkayenro tried many other bag addons and nothing compares to Ark

**Comment by KaareGravesen** [comment]
Thank you @Koviko for making this comprehensive solution.
And thank you @arkayenro for this amazing addon - can't live without it. Kick back and have a few drinks, enjoy your holiday 🍺

**Comment by Koviko** [comment]
@kaseyd24 That error implies that the ItemButtons weren't replaced in `ArkInventory.xml`. Were you sure to download the appropriate Gist as a ZIP and then extract both `ArkInventory.lua` *and* `ArkInventory.xml` to the ArkInventory addon directory?

**Comment by Hlabarr** [comment]
What I did was went to the main page and "installed" (overwrote) arkinventory:

https://www.curseforge.com/wow/addons/ark-inventory

Then installed this fix:

https://gist.github.com/Koviko/ba5e77d1cd5512019b1b687f9c4c35e0

The bags worked and my config was saved.

**Comment by kaseyd24** [comment]
> What I did was went to the main page and "installed" (not reinstall) arkinventory:
> https://www.curseforge.com/wow/addons/ark-inventory
> Then installed this fix:
> https://gist.github.com/Koviko/ba5e77d1cd5512019b1b687f9c4c35e0
> The bags worked and my config was saved.

This worked..  I can access my bags now.. My only gripe is that the bags icons at bottom aren't loading... but that's much less of a deal.. thank you

**Comment by kaseyd24** [comment]
> @kaseyd24 That error implies that the ItemButtons weren't replaced in ArkInventory.xml. Were you sure to download the appropriate Gist as a ZIP and then extract both ArkInventory.lua and ArkInventory.xml to the ArkInventory addon directory?

Yes.. I am outstanding at being a idiot.. thank you.. I love me this addon..

**Comment by kaseyd24** [comment]
@Koviko Yes.. I am outstanding at being a idiot.. thank you.. I love me this addon..

**Comment by guice** [comment]
I still get the following issue: 
```
Message: ...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:311: attempt to index global 'ArkInventory' (a nil value)
Time: Thu Mar 14 20:01:41 2019
Count: 17
Stack: ...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:311: attempt to index global 'ArkInventory' (a nil value)
[C]: ?
...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:311: in function <...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:303>

Locals: 
```

I have installed the two files: the lua _and_ xml file after "updating" ArkInventory via the Curse (Twitch) client.

Very first error of 186 is: ```
Message: Interface\AddOns\ArkInventory\ArkInventoryConst.lua:10: Cannot find a library instance of "AceAddon-3.0".
Time: Thu Mar 14 19:59:43 2019
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventoryConst.lua:10: Cannot find a library instance of "AceAddon-3.0".
[C]: in function `error'
...terface\AddOns\ArkInventory\Libs\LibStub\LibStub.lua:38: in function `LibStub'
Interface\AddOns\ArkInventory\ArkInventoryConst.lua:10: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "AceAddon-3.0"."
```

Then, ```
Message: Interface\AddOns\ArkInventory\ArkInventoryCPU.lua:24: attempt to index global 'ArkInventory' (a nil value)
Time: Thu Mar 14 19:59:43 2019
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventoryCPU.lua:24: attempt to index global 'ArkInventory' (a nil value)
Interface\AddOns\ArkInventory\ArkInventoryCPU.lua:24: in main chunk

Locals: (*temporary) = nil
(*temporary) = <function> defined @Interface\AddOns\ArkInventory\ArkInventoryCPU.lua:24
(*temporary) = "attempt to index global 'ArkInventory' (a nil value)"
```
(I have over 180 errors in this log)

**Comment by jeffv2011** [comment]
@Koviko 
I just wanted to take a moment to thank you for fixing this - especially on your vacation. I have to admit, I forgot how blessed I was to use you program because I had to use AdiBags while Ark was down. I'm not dissing Adi...I just am really thankful for Ark and was going crazy using other bags.

Ps: Is there some way to donate to you?

**Comment by Koviko** [comment]
I'm not the addon creator. Don't donate to me. lol

**Comment by DantePT** [comment]
Thank you for the help. Worked perfectly

**Comment by mroswald** [comment]
@guice I had the same issue and installed LibStub manually using Twitch. (Release + fixes from Gist). Now it works. Give it a try!

**Comment by wacopiper** [comment]
> @guice I had the same issue and installed LibStub manually using Twitch. (Release + fixes from Gist). Now it works. Give it a try!

This worked for me too.  Thanks ya'll

**Comment by guice** [comment]
> @guice I had the same issue and installed LibStub manually using Twitch. (Release + fixes from Gist). Now it works. Give it a try!

That did not work. *However*; the recent update above _did_ work for me. :)

**Comment by adamrosz** [comment]
> thanks to all the people helping. pinning this so its a bit more obvious
> 
> i will be back home on thursday 21st (not 23rd), so another week, before i can fix anything myself, sorry
> 
> note1 - please dont delete your saved variables file, that will just lose your config. once its fixed/working again the saved variables (your config) will be needed
> 
> note2 - feel free to try other bag mods in the mean time, i wont hate you. you never know, one of them might be better for you
> 
> note3 - i also cant access curse or curseforge, twitch is being a pita with authy and wont accept my code so wont authenticate me so i cant post there

Thanks for making the amazing addon! Glad to hear it's going to be fixed, enjoy your vacation.

**Comment by spiralofhope** [comment]
Thanks for the bundled .zip, it's working fine for me.

Today I learned I can barely even understand the default bank UI..

**Comment by Koviko** [comment]
@arkayenro has released an official fix on Curse and, after a bit of testing, this post is no longer needed! I'm closing this issue!

**Comment by kaseyd24** [comment]
I downloaded from curse, and its still not working

**Comment by Koviko** [comment]
@kaseyd24 Did you restart WoW after updating?

**Comment by kaseyd24** [comment]
> @kaseyd24 Did you restart WoW after updating?

Wow wasn't started, but I did just to test.. getting wow interface bags

**Comment by kaseyd24** [comment]
Getting these error messages
2x ArkInventory\ArkInventoryConst.lua:10: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceBucket-3.0".
[C]:: ?
...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0-12.lua:189: in function 'EmbedLibrary'
...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0-12.lua:171: in function 'EmbedLibraries'
...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0-12.lua:138: in function 'NewAddon'
ArkInventory\ArkInventoryConst.lua:10: in main chunk

2x ArkInventory\ArkInventoryCPU.lua:24: attempt to index global 'ArkInventory' (a nil value)
ArkInventory\ArkInventoryCPU.lua:24: in main chunk

2x ArkInventory\ArkInventoryCodex.lua:31: attempt to index global 'ArkInventory' (a nil value)
ArkInventory\ArkInventoryCodex.lua:31: in main chunk

2x ArkInventory\Locale\game-Game.lua:1: Cannot find a library instance of "AceLocale-3.0".
[C]:: in function 'error'
!Swatter\Support\LibStub.lua:23: in function 'LibStub'
ArkInventory\Locale\game-Game.lua:1: in main chunk

2x ...rface\ArkInventoryRules\ArkInventoryRules-10300.lua:102: attempt to index global 'ArkInventory' (a nil value)
...rface\ArkInventoryRules\ArkInventoryRules-10300.lua:102: in function <...rface\ArkInventoryRules\ArkInventoryRules.lua:97>
[C]:: ?
...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function 'EnableAddon'
...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]:: in function 'LoadAddOn'
FrameXML\UIParent.lua:446: in function 'UIParentLoadAddOn'
FrameXML\UIParent.lua:489: in function 'CombatLog_LoadUI'
FrameXML\UIParent.lua:1194: in function <FrameXML\UIParent.lua:1090>

2x ...rface\ArkInventoryRules\ArkInventoryRules-10300.lua:2014: attempt to index global 'ArkInventory' (a nil value)
...rface\ArkInventoryRules\ArkInventoryRules-10300.lua:2014: in function 'Register'
...InventoryRules_Example\ArkInventoryRules_Example-10000.lua:11: in function <...InventoryRules_Example\ArkInventoryRules_Example.lua:5>
[C]:: ?
...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function 'EnableAddon'
...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0-12.lua:540: in function 'EnableAddon'
...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]:: in function 'LoadAddOn'
FrameXML\UIParent.lua:446: in function 'UIParentLoadAddOn'
FrameXML\UIParent.lua:489: in function 'CombatLog_LoadUI'
FrameXML\UIParent.lua:1194: in function <FrameXML\UIParent.lua:1090>

2x ...ace\ArkInventorySearch\ArkInventorySearch-10300.lua:24: attempt to index global 'ArkInventory' (a nil value)
...ace\ArkInventorySearch\ArkInventorySearch-10300.lua:24: in function <...ace\ArkInventorySearch\ArkInventorySearch.lua:22>
[C]:: ?
...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function 'EnableAddon'
...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]:: in function 'LoadAddOn'
FrameXML\UIParent.lua:446: in function 'UIParentLoadAddOn'
FrameXML\UIParent.lua:489: in function 'CombatLog_LoadUI'
FrameXML\UIParent.lua:1194: in function <FrameXML\UIParent.lua:1090>
815x ...erface\ArkInventory\ArkInventoryTranslate.lua:311: attempt to index global 'ArkInventory' (a nil value)
...erface\ArkInventory\ArkInventoryTranslate.lua:311: in function <...erface\ArkInventory\ArkInventoryTranslate.lua:303>

**Comment by kaseyd24** [comment]
I disabled angry assignments as well, to see if that was breaking it.... Still wow interface bags..

**Comment by guice** [comment]
@kaseyd24 

I ran into a slew of errors again as well. What fixed it for me: deleting all ArkInventory folders and reinstalling from there.

I had at least one extra "legacy" folder I think was causing the issue.

**Comment by kaseyd24** [comment]
dds

> @kaseyd24
> I ran into a slew of errors again as well. What fixed it for me: deleting all ArkInventory folders and reinstalling from there.
> I had at least one extra "legacy" folder I think was causing the issue.

That actually worked... deleting the addon, and reinstalling.. Thanks homie....
*I cant pull homie off*
thank you

**Comment by tttttttttttttttttaaaa** [comment]
I have the error since weak please fix it

**Comment by arkayenro** [comment]
> I have the error since weak please fix it

buy me a plane ticket and i'll come around and fix it for you personally, otherwise just follow the other instructions and to a clean re-install/upgrade like every other normal person has done

**Comment by MrUzagi** [comment]
> I have the error since weak please fix it

This issue is closed since it has been fixed.

If you had read the related issues you would also have noticed that a clean install (delete the addon folders first) might also be necessary. This is generallt a good practice to do anyway, but something that most add-on managers don't do.

If you have still have a problem it is most likely a different one. No need to be rude about it.

**Comment by kaseyd24** [comment]
People are just nasty bastards eh???

**Comment by arkayenro** [comment]
i think its more a combination of laziness and possibly english not being their native language.  or at least i hope it is.
