### ISSUE TITLE
This keeps popping up

### ISSUE THREAD

**Issue by nudesmurf** [arkayenro/arkinventory#1152]
Date: 2019-03-14 21:10:16
ID: 1
Error occured in: Global
Count: 1
Message: ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua line 180:
   Attempting to rehook already active hook SetAuctionSellItem.
Debug:
   [C]: ?
   ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:180:
      ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:118
   ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:341: SecureHook()
   ArkInventory\ArkInventory.lua:10332: BlizzardAPIHook()
   ArkInventory\ArkInventory.lua:2523:
      ArkInventory\ArkInventory.lua:2513
   [C]: ?
   ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:70:
      ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65
   ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:527: EnableAddon()
   ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:620:
      ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:446: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:489: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:1194:
      ..\FrameXML\UIParent.lua:1090
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  ArkInventory, v30821
  ArkInventoryRules, v10300
  ArkInventorySearch, v10300
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  DBMCore, v8.1.11
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Omen, v3.2.0
  SexyMap, vv8.0.8
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=2ff)

**Comment by Koviko** [comment]
Check #1149 for a fix.

**Comment by arkayenro** [comment]
please upgrade to 3.08.23
