### ISSUE TITLE
Arkinventory Error

### ISSUE THREAD

**Issue by Omega1102** [arkayenro/arkinventory#1153]
I get following error if i start wow with only arkinventory activated:
"FEHLER>Interface\FrameXML\ItemButtonTemplate.lua:65: atttempt to index local 'icon' (a nil value)"
![WoWScrnShot_031519_063549](https://user-images.githubusercontent.com/30471308/54410822-5cd27280-46ed-11e9-9399-15840288441e.jpg)

I tryed allready a new installation.
I hope you can fix that ;)

**Comment by gOOvER** [comment]
#1149

**Comment by arkayenro** [comment]
upgrade to 3.08.23
