### ISSUE TITLE
unable to view bags....stuck on loading

### ISSUE THREAD

**Issue by shemeric** [arkayenro/arkinventory#1154]
after the patch on Tuesday 12th March 2019 I have been unable to view my bags.  I have tried disabling all other addons, no change.  I have unistalled ArkInvntory and reinstalling fresh, no change.

ERROR>Interface\FrameXML\ItemButtonTemplate.lua:65:attempt to index local 'icon' (a nil value)

Sorry I know nothing about the technical stuff and have tried googling the error with no help.
![Uploading screenshot.png…]()

**Comment by Koviko** [comment]
Check issue #1149 for a fix.

**Comment by arkayenro** [comment]
upgrade to 3.08.23
