### ISSUE TITLE
Interface\FrameXML\

### ISSUE THREAD

**Issue by BRangerOP** [arkayenro/arkinventory#1155]
Date: 2019-03-15 13:48:14
ID: 2
Error occured in: Global
Count: 1
Message: ..\FrameXML\ItemButtonTemplate.lua line 65:
   attempt to index local 'icon' (a nil value)
Debug:
   ..\FrameXML\ItemButtonTemplate.lua:65: SetItemButtonTextureVertexColor()
   ArkInventory\ArkInventory.lua:6730: Frame_Bar_Edit_OnLoad()
   [string "*:OnLoad"]:1:
      [string "*:OnLoad"]:1
   [C]: resume()
   ArkInventory\ArkInventory.lua:11194: ThreadResume()
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1
Locals:
button = ARKINV_Frame1ScrollContainerBar1Edit {
 0 = <userdata>
 ArkTransmogIcon = ARKINV_Frame1ScrollContainerBar1EditArkTransmogIcon {
 }
 BagStaticBottom = <unnamed> {
 }
 ArkBorder = ARKINV_Frame1ScrollContainerBar1EditArkBorder {
 }
 BagStaticTop = <unnamed> {
 }
 flash = <unnamed> {
 }
 GetItemContextMatchResult = <function> defined @Interface\FrameXML\ContainerFrame.lua:1425
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 ArkItemTinted = ARKINV_Frame1ScrollContainerBar1EditArkItemTinted {
 }
 JunkIcon = <unnamed> {
 }
 ArkBagHighlight = ARKINV_Frame1ScrollContainerBar1EditArkBagHighlight {
 }
 ExtendedOverlay = <unnamed> {
 }
 ARK_Data = <table> {
 }
 ArkListEntry = ARKINV_Frame1ScrollContainerBar1EditArkListEntry {
 }
 UpgradeIcon = <unnamed> {
 }
 BattlepayItemTexture = <unnamed> {
 }
 ArkAgeText = ARKINV_Frame1ScrollContainerBar1EditArkAgeText {
 }
 NewItemTexture = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
}
r = 0.500000
g = 0.100000
b = 0.100000
icon = nil
(*temporary) = "ARKINV_Frame1ScrollContainerBar1EditIconTexture"
(*temporary) = nil
(*temporary) = "ARKINV_Frame1ScrollContainerBar1Edit"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'icon' (a nil value)"

AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  ArkInventory, v30821
  ArkInventoryRules, v10300
  ArkInventoryRulesExample, v10000
  ArkInventorySearch, v10300
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  DBMCore, v8.1.11
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.1.6237 (SwimmingSeadragon)
  GatherMate2, v1.43.6
  HandyNotes, vv1.5.5
  HandyNotesLegionRaresTreasures, v1.1
  Hekili, vv8.1.0-25
  Informant, v8.1.6246 (SwimmingSeadragon)
  Pawn, v2.2.39
  Skada, v1.7.5
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  WoWGatheringNodes, v02.18.19
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=3ff)

**Comment by Koviko** [comment]
Go to #1149 for a fix.

**Comment by arkayenro** [comment]
upgrade to 3.08.23
