### ISSUE TITLE
error upon opening bags

### ISSUE THREAD

**Issue by bluathena** [arkayenro/arkinventory#1156]
Error message received when opening bags.

in chat box:
ERROR> Interface\FrameXML\ItemButtonTemplate.lua:65:attempt to index local 'icon' (a nil value)

Lua Error popup:
Message: ///\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua: 180: Attempting to rehook already active hook
SetAuctionSellItem.

no other addons are active at the time of this error.

![image](https://user-images.githubusercontent.com/47277780/54469292-1ff59280-4764-11e9-8105-0b94855bd267.png)

**Comment by arkayenro** [comment]
see #1149

**Comment by arkayenro** [comment]
upgrade to 3.08.23
