### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by pixie4933** [arkayenro/arkinventory#1157]
is not working at all this error pops when loading wow..failsafe kicked in-aborting ark inventory due to an error of some sort please help. i did shut off all addons and tried it and it still didn't work so it is not a problem with my other addons

**Comment by arkayenro** [comment]
see #1149

**Comment by arkayenro** [comment]
upgrade to 3.08.23

**Comment by pixie4933** [comment]
thank you for doing the upgrade it is appreciated. your quick response was amazing and I do hope you had an awesome vacation. I tried different bag addons and nothing compares to ark..
