### ISSUE TITLE
Template LUA 65 error

### ISSUE THREAD

**Issue by JackUrFace** [arkayenro/arkinventory#1158]
So I just randomly started gettig this error .WOrked fie yesterdy, and now this. The bag frame just sits stuck on "loading".

Error:
Date: 2019-03-16 22:17:17
ID: 1
Error occured in: Global
Count: 1
Message: ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua line 180:
   Attempting to rehook already active hook SetAuctionSellItem.
Debug:
   [C]: ?
   ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:180:
      ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:118
   ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:341: SecureHook()
   ArkInventory\ArkInventory.lua:10332: BlizzardAPIHook()
   ArkInventory\ArkInventory.lua:2523:
      ArkInventory\ArkInventory.lua:2513
   [C]: ?
   ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:527: EnableAddon()
   ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:620:
      ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:446: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:489: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:1194:
      ..\FrameXML\UIParent.lua:1090
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  Altoholic, vr190
  ArkInventory, v30821
  ArkInventoryRules, v10300
  ArkInventorySearch, v10300
  AtlasLoot, vv8.09.00
  AtlasLootBattleforAzeroth, vv8.09.00
  AtlasLootBurningCrusade, vv8.09.00
  AtlasLootCataclysm, vv8.09.00
  AtlasLootClassic, vv8.09.00
  AtlasLootLegion, vv8.09.00
  AtlasLootMistsofPandaria, vv8.09.00
  AtlasLootWarlordsofDraenor, vv8.09.00
  AtlasLootWrathoftheLichKing, vv8.09.00
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  Auctionator, v8.1.0
  AuctionMaster, v8.1.0
  Bartender4, v4.8.2
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  Carbonite, vv8.1.2.1
  CarboniteNotes, vv8.1
  CarboniteQuests, vv8.1.2
  CarboniteWarehouse, vv8.1-1-g6cc02c0
  DataStore, vr65
  DataStoreAchievements, vr47
  DataStoreAgenda, vr29
  DataStoreAuctions, vr50
  DataStoreCharacters, vr43
  DataStoreContainers, vr59
  DataStoreCrafts, vr82
  DataStoreCurrencies, vr38
  DataStoreGarrisons, vr24
  DataStoreInventory, vr53
  DataStoreMails, vr52
  DataStorePets, vr44
  DataStoreQuests, vr46
  DataStoreReputations, vr43
  DataStoreSpells, vr32
  DataStoreStats, vr31
  DataStoreTalents, vr61
  DBMCore, v8.1.12-4-ga67ece71f
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Postal, vv3.6.0
  Prat30, vr1195      
  Prat30Libraries, v
  Recount, vv8.1.0d
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  WIM, v595
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=6f2)

**Comment by Koviko** [comment]
Check #1149 for a fix.

**Comment by arkayenro** [comment]
upgrade to 3.08.23
