### ISSUE TITLE
ArkInventory issue

### ISSUE THREAD

**Issue by Scooba72** [arkayenro/arkinventory#1159]
Message: Interface\AddOns\ArkInventory\ArkInventory.lua:11203: Interface\FrameXML\ItemButtonTemplate.lua:65: attempt to index local 'icon' (a nil value)
Time: Sun Mar 17 17:08:33 2019
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventory.lua:11203: Interface\FrameXML\ItemButtonTemplate.lua:65: attempt to index local 'icon' (a nil value)
[C]: ?
Interface\AddOns\ArkInventory\ArkInventory.lua:11203: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: (*temporary) = "Interface\FrameXML\ItemButtonTemplate.lua:65: attempt to index local 'icon' (a nil value)"

**Comment by arkayenro** [comment]
see #1149

**Comment by arkayenro** [comment]
upgrade to 3.08.23
