### ISSUE TITLE
WoW 8.15 Bug

### ISSUE THREAD

**Issue by EdLaingLV** [arkayenro/arkinventory#1161]
When I try to open my bags, either as one bag, or individually (I use Bartender). it opens the frame of the bag, and then just sits there forever.  In chat, I get this message:

ArkInventory: ERROR> Interface\FrameXML\ItemButtonTemplate.lua:65: attempt to index local 'icon' (a nil value)

Can you help me fix this please?

**Comment by arkayenro** [comment]
see #1149

**Comment by arkayenro** [comment]
upgrade to 3.08.23
