### ISSUE TITLE
Completely broken can not open my bags

### ISSUE THREAD

**Issue by Zebrakiller** [arkayenro/arkinventory#1162]
[![Screenshot from Gyazo](https://gyazo.com/d436b05f4b629cc7df997995ab8cd9d1/raw)](https://gyazo.com/d436b05f4b629cc7df997995ab8cd9d1)

**Comment by Koviko** [comment]
Check the pinned issue #1149 for a fix to the addon.

**Comment by waterluver** [comment]
It wont let me use the Fix, it keeps saying Download Failed Zip Failed

**Comment by arkayenro** [comment]
upgrade to 3.08.23
