### ISSUE TITLE
WoW LUA Error

### ISSUE THREAD

**Issue by Lizeth913** [arkayenro/arkinventory#1163]
Message: Interface\AddOns\ArkInventory\ArkInventory.lua:11203: Interface\FrameXML\ItemButtonTemplate.lua:65: attempt to index local 'icon' (a nil value)
Time: Mon Mar 18 15:45:04 2019
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventory.lua:11203: Interface\FrameXML\ItemButtonTemplate.lua:65: attempt to index local 'icon' (a nil value)
[C]: ?
Interface\AddOns\ArkInventory\ArkInventory.lua:11203: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: (*temporary) = "Interface\FrameXML\ItemButtonTemplate.lua:65: attempt to index local 'icon' (a nil value)"

Error I keep seeing since last Tuesday World of Warcraft update.

**Comment by Koviko** [comment]
Go to issue #1149 for a fix. There won't be an officially released one for a while.

**Comment by arkayenro** [comment]
upgrade to 3.08.23

**Comment by Lizeth913** [comment]
Thank you! Working once again


Sent from my iPhone

On Mar 21, 2019, at 1:32 AM, arkayenro <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1163<https://github.com/arkayenro/arkinventory/issues/1163>.
