### ISSUE TITLE
Arkinventory issue

### ISSUE THREAD

**Issue by wuvdogs** [arkayenro/arkinventory#1164]
Message reads:     ERROR>Interface\FrameXML\ItemButtonTemplate.lua:65:attempt to index local 'icon' (a nil value)

**Comment by Hermagesty** [comment]
Im getting the same thing

**Comment by arkayenro** [comment]
see #1149

**Comment by signtrname** [comment]
I'm getting this same error msg. I can not see my bags at all :(

**Comment by arkayenro** [comment]
upgrade to 3.08.23

**Comment by wuvdogs** [comment]
Hi, your fix on #1149 worked for me. Tyvm!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
