### ISSUE TITLE
Totally broken can't use bags

### ISSUE THREAD

**Issue by riotgirl81** [arkayenro/arkinventory#1165]
Date: 2019-03-18 18:40:19
ID: 1
Error occured in: Global
Count: 1
Message: ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua line 180:
   Attempting to rehook already active hook SetAuctionSellItem.
Debug:
   [C]: ?
   ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:180:
      ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:118
   ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:341: SecureHook()
   ArkInventory\ArkInventory.lua:10257: BlizzardAPIHook()
   ArkInventory\ArkInventory.lua:2523:
      ArkInventory\ArkInventory.lua:2513
   [C]: ?
   ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:70:
      ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65
   ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:527: EnableAddon()
   ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:620:
      ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:446: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:565: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:1192:
      ..\FrameXML\UIParent.lua:1090
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  ArkInventory, v30822
  ArkInventoryRules, v10300
  ArkInventorySearch, v10300
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  BadBoy, vv8.1.4
  BagBrother, v
  BarrelsOEasy, v1.1.11
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  DBMCore, v8.1.12
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  ElvUI, v11.00
  HealBot, v8.1.0.7
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  NPCScan, v8.0.1.13
  PetBattleMaster, v8.0.0
  Quartz, v3.4.0
  Rarity, v1.0 (r686-release)
  RarityOptions, v
  Skada, v1.7.5
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  Titan, v5.17.0.80100
  TitanBag, v5.17.0.80100
  TitanClock, v5.17.0.80100
  TitanGold, v5.17.0.80100
  TitanLocation, v5.17.0.80100
  TitanLootType, v5.17.0.80100
  TitanPerformance, v5.17.0.80100
  TitanRepair, v5.17.0.80100
  TitanVolume, v5.17.0.80100
  TitanXP, v5.17.0.80100
  TomTom, vv80100-1.0.1
  XPBarNone, v80000-2
  ZPerl, v5.7.2
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=638)

**Comment by arkayenro** [comment]
see #1149

**Comment by arkayenro** [comment]
upgrade to 3.08.23
