### ISSUE TITLE
Arkinventory ERROR NOT working!!!!

### ISSUE THREAD

**Issue by Hermagesty** [arkayenro/arkinventory#1166]
ERROR> Interface\FrameXML\ItemButtonTemplate.lua:65: attempt to index local 'icon' (a nil value)
![WoWScrnShot_031819_174617](https://user-images.githubusercontent.com/43124238/54570840-c4b2e280-49a5-11e9-971c-8370a2922d98.jpg)

**Comment by arkayenro** [comment]
see #1149

**Comment by arkayenro** [comment]
upgrade to 3.08.23
