### ISSUE TITLE
AI hides item tooltip at scrapper

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1167]
When at the scrapper, item tooltips are being hidden after ~1s. I have the 8.1.5 stopgatp fix applied. The issue is not present if AI is disabled and didn't exist in any previous versions.

**Comment by arkayenro** [comment]
upgrade to 3.08.23, let me know if its still there or not

**Comment by hollo6** [comment]
I have upgraded AI and when testing this, I found out that this actually just happens with the extra frame of Easy Scrap. But I'm still convinced that AI is doing something with the tooltips there because with AI disabled, the tooltips are all fine.

**Comment by arkayenro** [comment]
AI refreshes the tooltip every couple of seconds (closes and re-opens) so that item counts will turn up but it just calls the same API that any normal tooltip generation would use so other addons should just end up adding their text again

**Comment by hollo6** [comment]
Since this was not an issue before 8.1.5, I guess it's caused by one of its API changes. Could you please point out which one so I can fix it?

**Comment by arkayenro** [comment]
any one of these tooltip functions, theyre all hooked by AI and regenerated

		"SetAuctionSellItem",
		"SetBagItem", "SetInventoryItem", "SetItemByID",
		"SetCraftItem",
		"SetBackpackToken", "SetCurrencyByID", "SetCurrencyToken", "SetCurrencyTokenByID",
		"SetGuildBankItem",
		"SetHeirloomByItemID",
		"SetHyperlink", "SetHyperlinkCompareItem",
		"SetInboxItem", "SetSendMailItem",
		"SetLootItem", "SetLootRollItem",
		"SetMerchantItem", "SetMerchantCostItem", "SetBuybackItem", 
		"SetQuestItem", "SetQuestLogSpecialItem", "SetQuestLogItem", 
		"SetQuestCurrency", "SetQuestLogCurrency", "LogCurrency",
		--"SetQuestLogRewardSpell","SetQuestRewardSpell",
		"SetTradePlayerItem", "SetTradeTargetItem",
		"SetVoidItem", "SetVoidDepositItem", "SetVoidWithdrawalItem",
		"SetRecipeReagentItem", "SetRecipeResultItem",
		"SetAuctionItem",
		"SetToyByItemID",
		"ClearLines", "FadeOut",
