### ISSUE TITLE
Ark Inventory fails to load bag display screen

### ISSUE THREAD

**Issue by Eastshire** [arkayenro/arkinventory#1168]
I get the first two errors on load and the second two errors when pressing "b" to open my bags.  The bag screen opens to just a black screen with no inventory displayed. It says loading at the bottom left.

Message: Couldn't find inherited node: ItemButtonTemplate
Time: Tue Mar 19 16:34:38 2019
Count: 88

Message: ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:180: Attempting to rehook already active hook SetAuctionSellItem.
Time: Tue Mar 19 16:34:41 2019
Count: 1
Stack: ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:180: Attempting to rehook already active hook SetAuctionSellItem.
[C]: ?
...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:180: in function <...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:118>
...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:341: in function `SecureHook'
Interface\AddOns\ArkInventory\ArkInventory.lua:10332: in function `BlizzardAPIHook'
Interface\AddOns\ArkInventory\ArkInventory.lua:2523: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:2513>
[C]: ?
...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:70: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65>
...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:527: in function `EnableAddon'
...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:620: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1192: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: <none>

Message: Interface\FrameXML\ItemButtonTemplate.lua:65: attempt to index local 'icon' (a nil value)
Time: Tue Mar 19 16:35:43 2019
Count: 45
Stack: Interface\FrameXML\ItemButtonTemplate.lua:65: attempt to index local 'icon' (a nil value)
Interface\FrameXML\ItemButtonTemplate.lua:65: in function `SetItemButtonTextureVertexColor'
Interface\AddOns\ArkInventory\ArkInventory.lua:6730: in function `Frame_Bar_Edit_OnLoad'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>
[C]: in function `resume'
Interface\AddOns\ArkInventory\ArkInventory.lua:11194: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: button = ARKINV_Frame1ScrollContainerBar45Edit {
 0 = <userdata>
 ArkTransmogIcon = ARKINV_Frame1ScrollContainerBar45EditArkTransmogIcon {
 }
 BagStaticBottom = <unnamed> {
 }
 ArkBorder = ARKINV_Frame1ScrollContainerBar45EditArkBorder {
 }
 BagStaticTop = <unnamed> {
 }
 flash = <unnamed> {
 }
 GetItemContextMatchResult = <function> defined @Interface\FrameXML\ContainerFrame.lua:1425
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 ArkItemTinted = ARKINV_Frame1ScrollContainerBar45EditArkItemTinted {
 }
 JunkIcon = <unnamed> {
 }
 ArkBagHighlight = ARKINV_Frame1ScrollContainerBar45EditArkBagHighlight {
 }
 ExtendedOverlay = <unnamed> {
 }
 ARK_Data = <table> {
 }
 ArkListEntry = ARKINV_Frame1ScrollContainerBar45EditArkListEntry {
 }
 UpgradeIcon = <unnamed> {
 }
 BattlepayItemTexture = <unnamed> {
 }
 ArkAgeText = ARKINV_Frame1ScrollContainerBar45EditArkAgeText {
 }
 NewItemTexture = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
}
r = 0.500000
g = 0.100000
b = 0.100000
icon = nil
(*temporary) = "ARKINV_Frame1ScrollContainerBar45EditIconTexture"
(*temporary) = nil
(*temporary) = "ARKINV_Frame1ScrollContainerBar45Edit"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'icon' (a nil value)"

Message: Interface\AddOns\ArkInventory\ArkInventory.lua:11203: Interface\FrameXML\ItemButtonTemplate.lua:65: attempt to index local 'icon' (a nil value)
Time: Tue Mar 19 16:35:43 2019
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventory.lua:11203: Interface\FrameXML\ItemButtonTemplate.lua:65: attempt to index local 'icon' (a nil value)
[C]: ?
Interface\AddOns\ArkInventory\ArkInventory.lua:11203: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: (*temporary) = "Interface\FrameXML\ItemButtonTemplate.lua:65: attempt to index local 'icon' (a nil value)"

**Comment by Eastshire** [comment]
Downloaded the files from #1149 and it's working for me.

**Comment by signtrname** [comment]
That is what mine says also
