### ISSUE TITLE
Lua Error, Will not load

### ISSUE THREAD

**Issue by GreenNite** [arkayenro/arkinventory#1169]
Message: ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:180: Attempting to rehook already active hook SetAuctionSellItem.
Time: Wed Mar 20 21:09:17 2019
Count: 1
Stack: ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:180: Attempting to rehook already active hook SetAuctionSellItem.
(tail call): ?
[C]: ?
...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:180: in function <...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:118>
...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:341: in function `SecureHook'
Interface\AddOns\ArkInventory\ArkInventory.lua:10332: in function `BlizzardAPIHook'
Interface\AddOns\ArkInventory\ArkInventory.lua:2523: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:2513>
[C]: ?
...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:70: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65>
...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:527: in function `EnableAddon'
...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:620: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:605>
[C]: ?
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1192: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: <none>

**Comment by Koviko** [comment]
What shows in chat when you run this command:

`/dump ArkInventory.Global.Version`

![/dump ArkInventory.Global.Version](https://i.imgur.com/P3OVkC0.png)

If your main chat log doesn't show "v3.08.23", then your addon manager hasn't properly updated you to the latest version. If you're using the Twitch addon manager, hit refresh and then hit update, again. Make sure you're allowing it to use the Alpha version.

![Twitch addon manager ArkInventory v3.08.23](https://i.imgur.com/QsgBrrX.png)

**Comment by GreenNite** [comment]
![image](https://user-images.githubusercontent.com/20548766/54734048-5ebb8c00-4b5a-11e9-8fc4-1b7c83c68239.png)

Incase the Pic does not show, I am running v3.08.21
I just went in and changed to the Alpha release type. 
Closed out of the game all the way
restarted the game
loaded a toon that only has ArkInventory running
same looking error came up
closed the game
checked to make sure I am pulling Alpha
told Twitch to reload anyway
stared the game
same looking error came up
![image](https://user-images.githubusercontent.com/20548766/54734305-d1793700-4b5b-11e9-8578-12f75caa7806.png)
v3.08.22|cffff2020(r818-alpha)|r

I did not get v3.08.23 from Twitch

Lua Error Below

Message: ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:180: Attempting to rehook already active hook SetAuctionSellItem.
Time: Wed Mar 20 21:58:06 2019
Count: 1
Stack: ...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:180: Attempting to rehook already active hook SetAuctionSellItem.
[C]: ?
...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:180: in function <...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:118>
...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:341: in function `SecureHook'
Interface\AddOns\ArkInventory\ArkInventory.lua:10257: in function `BlizzardAPIHook'
Interface\AddOns\ArkInventory\ArkInventory.lua:2523: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:2513>
[C]: ?
...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:70: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65>
...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:527: in function `EnableAddon'
...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:620: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1192: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: <none>

**Comment by GreenNite** [comment]
Lua Error when I try to open my backpack

Message: Interface\FrameXML\ItemButtonTemplate.lua:65: attempt to index local 'icon' (a nil value)
Time: Wed Mar 20 22:12:35 2019
Count: 55
Stack: Interface\FrameXML\ItemButtonTemplate.lua:65: attempt to index local 'icon' (a nil value)
Interface\FrameXML\ItemButtonTemplate.lua:65: in function `SetItemButtonTextureVertexColor'
Interface\AddOns\ArkInventory\ArkInventory.lua:6682: in function `Frame_Bar_Edit_OnLoad'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>
[C]: in function `resume'
Interface\AddOns\ArkInventory\ArkInventory.lua:11127: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: button = ARKINV_Frame1ScrollContainerBar55Edit {
 0 = <userdata>
 ArkTransmogIcon = ARKINV_Frame1ScrollContainerBar55EditArkTransmogIcon {
 }
 BagStaticBottom = <unnamed> {
 }
 ArkBorder = ARKINV_Frame1ScrollContainerBar55EditArkBorder {
 }
 BagStaticTop = <unnamed> {
 }
 flash = <unnamed> {
 }
 GetItemContextMatchResult = <function> defined @Interface\FrameXML\ContainerFrame.lua:1425
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 ArkItemTinted = ARKINV_Frame1ScrollContainerBar55EditArkItemTinted {
 }
 JunkIcon = <unnamed> {
 }
 ArkBagHighlight = ARKINV_Frame1ScrollContainerBar55EditArkBagHighlight {
 }
 ExtendedOverlay = <unnamed> {
 }
 ARK_Data = <table> {
 }
 ArkListEntry = ARKINV_Frame1ScrollContainerBar55EditArkListEntry {
 }
 UpgradeIcon = <unnamed> {
 }
 BattlepayItemTexture = <unnamed> {
 }
 ArkAgeText = ARKINV_Frame1ScrollContainerBar55EditArkAgeText {
 }
 NewItemTexture = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
}
r = 0.500000
g = 0.100000
b = 0.100000
icon = nil
(*temporary) = "ARKINV_Frame1ScrollContainerBar55EditIconTexture"
(*temporary) = nil
(*temporary) = "ARKINV_Frame1ScrollContainerBar55Edit"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'icon' (a nil value)"

**Comment by Koviko** [comment]
That's odd. I'm not sure how or why Twitch does what it does, but since it's still recommending `r818-alpha` to you, I recommend downloading the fixed version of `r818-alpha` from #1149. The first link will be the fixed ArkInventory directory.

When Twitch finally decides to give you `r821`, you'll make a seamless transition and the addon will continue to work as expected.

**Comment by arkayenro** [comment]
upgrade to 3.08.23

make sure the game is NOT running when you do it

**Comment by GreenNite** [comment]
Killed the game.
downloaded and over wrote the old file with the new one.
started up the game and loaded my testing toon, no issues/errors
loaded my main toon, no issues/errors

looks to be all fixed

Thanks, You Rock!!
