### ISSUE TITLE
Chain Lua Errors at Launch

### ISSUE THREAD

**Issue by Xzygy** [arkayenro/arkinventory#1171]
Having these errors spawn when I enter the game, and they just chain spawn.  I've isolated ArkInventory alone, and still get these errors.  The previous fix by Koviko worked, but each time I update it now, I have to go and apply Koviko's fix.

`Message: ...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:311: attempt to index global 'ArkInventory' (a nil value)
Time: Thu Mar 21 20:06:09 2019
Count: 16
Stack: ...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:311: attempt to index global 'ArkInventory' (a nil value)
...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:311: in function <...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:303>

edit: trimmed for clarity

**Comment by arkayenro** [comment]
close the game
close twitch
delete all the `...\_retail_\Interface\AddOns\ArkInventory...` folders
re-install arkinventory via twitch
start the game

**Comment by Bill18xx** [comment]
This worked perfectly for me.

**Comment by vinotamu** [comment]
Thank you arkayenro .   That worked.   Everyone, remember not to just update the addon.  Remove it first.   Thats what made mine work.

**Comment by Xzygy** [comment]
I'm not 100% sure why, but deleting the folders, then selecting "reinstall" in the twitch right click menu did not work.  I deleted it from twitch, made sure the folders were deleted, then searched for ArkInventory and installed it, spun up the game and it's working like a charm.  

Thank you for helping me out, and thanks for keeping this great addon running.  With all the junk cluttering this game, the ability to categorize and group items based on any criteria I like is incredible.  It's tools like this that take the sting out of clunky, dated game systems.

**Comment by spiralofhope** [comment]
I'm still seeing these errors myself, even after the wipe/install others suggest.  From what I gather, the code is referring to a very specific revision of the Ace3 libraries and appears to be falling back to an earlier (but compatible) version.

I just get errors on first load, but nothing thereafter.

**Comment by arkayenro** [comment]
the code doesnt care which version of ace3 it gets, it just loads whichever ace3 you have installed (or was included from curse).
