### ISSUE TITLE
Restack @ Bank: Item is Locked

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1172]
I mentioned this in another thread but in all the chaos I think it got lost as it doesn't seem to have been fixed in 3.08.23.  When I open my bank, clicking the 'Restack' button shows an error message saying that the 'Item is Locked'.  I *think* it's referencing my reagent bank because that's where I dropped items from my bags to be combined with like items.  Not a showstopper, but it's not working as intended.  This behavior *doesn't* happen when I restack my bags -- maybe another indicator that's related to the reagent bank.

I've already tried a fresh install by removing all the ArkInventory folders and reinstalling using the Twitch client as suggested in the other 8.1.5-related threads.

Welcome back from your cruise. :)

**Comment by arkayenro** [comment]
im not seeing it only of my toons but i have seen that issue before where the game has actually locked an item.

if you havent already could you try logging into another character, then back into the one having an issue and try restack again?

**Comment by Calesta** [comment]
I tested this on three other characters and all have the same issue when I click 'Restack' in the bank.

None of my bank items are shown in grey and I don't see any indicators that they are locked when I hover over them.

Any other information I can provide that might help troubleshoot?

**Comment by arkayenro** [comment]
can you screenshot the error?

**Comment by Calesta** [comment]
Screenshot from one character attached.  The 'Item is Locked' message appears in red in the upper middle of the screen.

![WoWScrnShot_032319_201421](https://user-images.githubusercontent.com/13042214/54873279-95d3ac80-4da9-11e9-9821-de77afaa5792.jpg)

**Comment by arkayenro** [comment]
will be fixed in the r825 alpha when its released

**Comment by arkayenro** [comment]
you could also change to restack instead of blizzards cleanup in the mean time (right click on the restack icon and change the type)

**Comment by arkayenro** [comment]
workaround added to 3.08.24
