### ISSUE TITLE
Bar names does not always update correctly when inventory changes

### ISSUE THREAD

**Issue by MrUzagi** [arkayenro/arkinventory#1173]
I searched for an existing issue for my problem but couldn't find one.

I have AI v3.08.23 recently reinstalled via Twitch after first deleting the AI files and folders.
The problem still exists with only AI enabled, and we are two people on different computers in the household with the same problem

For the past few days I've had an odd thing where my bar names does not update correctly. Frequently when i open my bags, and AI does a reshuffle of the bars, the labels doesn't stay with the correct bar. I need to hit the refresh button or close and reopen the bags 1-3 times before the names are in their correct places again.

If the inventory is unchanged the names usually stay in their correct places for a while. But sooner or later it's wrong again until a refresh, even if the inventory is unchanged. After zoning, or a reload for example.

There are no lua-errors in bugsack.

Here's an example with the wrong names.
![AI-wrong-names](https://user-images.githubusercontent.com/21023158/54869580-00c9b700-4d9b-11e9-9bd6-f330fd069fd8.png)

Here are the same bags after a refresh.
![AI-correct-names](https://user-images.githubusercontent.com/21023158/54869448-a2033e00-4d98-11e9-98f8-8c3d80dc6de4.png)

Any idea what's going on here?

**Comment by arkayenro** [comment]
the issue was mentioned on curse last night but not here

was bad code positioning, the labels were being drawn too early and their bar_ids hadnt been updated

will be fixed in the next alpha / release.  in the mean time a refresh will fix them

**Comment by MrUzagi** [comment]
Good to hear. I can live with it in the mean time. It's an annoyance at worst.

Thank you for an awesome addon.

**Comment by arkayenro** [comment]
fixed in the r824 alpha

**Comment by Manniala** [comment]
Yep, alpha fixed this for me also.

Thx :)

**Comment by MrUzagi** [comment]
I got the release today. It looks good. Thank you!
