### ISSUE TITLE
Ark inventory not opening

### ISSUE THREAD

**Issue by aremidolren** [arkayenro/arkinventory#1174]
Hi I disabled all my addons but Ark Inventory still get this Message: ...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:311: attempt to index global 'ArkInventory' (a nil value)
Time: Fri Mar 29 14:33:39 2019
Count: 2
Stack: ...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:311: attempt to index global 'ArkInventory' (a nil value)
...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:311: in function <...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:303>

edit: cleared the extra error stuff that wasnt required

**Comment by arkayenro** [comment]
your code is corrupted or youre missing the libraries

close the game
close your installer
delete all the `...\World of Warcraft\_retail_\Interface\AddOns\ArkInventory...` folders
re-install arkinventory via your installer, or manually
start the game

 

if you install without libraries then its up to you, or your installer, to ensure that all required libraries are also installed - if they arent installed then AI will fail.  if you are even slightly unsure then make sure you are downloading and installing the libraries included version

**Comment by aremidolren** [comment]
Thank you so much. I now know to watch what version twitch is installing. I love your addon.
