### ISSUE TITLE
"Open All Bags" doesn't work with certain config settings

### ISSUE THREAD

**Issue by TylerR909** [arkayenro/arkinventory#1176]
I love this addon for managing my bags but I prefer default Blizzard Bank UI (skinned to ElvUI, bag management disabled) for Bank stuff. I went into config settings, under profile, went to Bank, and unchecked "Override," and now my "B" key which is bound to "Open All Bags" simply doesn't work. Shift+B, bound to "Toggle Backpack," is required for me to open my bags. Re-checked the Override for Bank and "B" started working again. Unchecked it again - Same error. Not sure how those two are tied up.

Disabled ElvUI+AddOnSkins and the issue persists.

**Comment by arkayenro** [comment]
i have shift-B assigned to Open All Bags and that doesnt seem to work at all, no matter what i try, its not even calling the hook function.

it does work if i run it manually

**Comment by arkayenro** [comment]
ah, the game is actually calling ToggleAllBags instead of OpenAllBags.

i'll check that function to see whats wrong with it

**Comment by arkayenro** [comment]
will be fixed next alpha/release

**Comment by arkayenro** [comment]
fixed in 3.08.24
