### ISSUE TITLE
Ark just seems to not open after new patch

### ISSUE THREAD

**Issue by ender444** [arkayenro/arkinventory#1178]
Couple of errors linked below. Also see an error in chat:
"failsafe kicked in - aborting arkinventory translations due to an error of some sort"

Date: 2019-04-17 20:34:35
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ArkInventory\ArkInventoryConst.lua line 18:
   Cannot find a library instance of "LibPeriodicTable-3.1".
Debug:
   [C]: error()
   !Swatter\Support\LibStub.lua:23: LibStub()
   ArkInventory\ArkInventoryConst.lua:18: in main chunk
Locals:
(*temporary) = "Cannot find a library instance of "LibPeriodicTable-3.1"."

edited for brevity

**Comment by arkayenro** [comment]
close the game
delete all the arkinventory folders
reinstall arkinventory - making sure to pick the libraries included version
start the game
