### ISSUE TITLE
Undesired Forced Instant Sorting

### ISSUE THREAD

**Issue by lloydBl** [arkayenro/arkinventory#1179]
I have all of my bags/bank/ect set using the "On Window Open" for when to sort, however the behavior is acting as if I have chosen "Instantly" (everything is immediately moved back when dragged to a new spot). Changing the "When" drop down doesn't seem to change the behavior even when put on "Manually."  Is there a setting I'm missing to fix this?

**Comment by lloydBl** [comment]
Still an issue with no resolution

**Comment by Bachsau** [comment]
What is it that you are trying to achieve? ArkInventory is designed as a full abstraction of the traditional bags system. You categorize your items and ArkInvetory places them according to the rules you've set.

**Comment by arkayenro** [comment]
i think i eventually figured out what causes this.  one of the blueprint options in the profile has been deleted and its defaulting back to the default which triggers a full rebuild.   i cant fix that as the full rebuild is needed in that case, but i have added a warning about missing/deleted blueprints on load.
