### ISSUE TITLE
Aceaddon error

### ISSUE THREAD

**Issue by Madlander78** [arkayenro/arkinventory#1181]
I started getting this error.

Date: 2019-06-20 12:06:21
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ArkInventory\ArkInventoryConst.lua line 10:
   Cannot find a library instance of "AceAddon-3.0".
Debug:
   [C]: error()
   !Swatter\Support\LibStub.lua:23: LibStub()
   ArkInventory\ArkInventoryConst.lua:10: in main chunk
Locals:
(*temporary) = "Cannot find a library instance of "AceAddon-3.0"."

Suggestions please?

**Comment by arkayenro** [comment]
sounds like your files have become corrupt.  you may want to delete the arkinventory folders and re-install

**Comment by Madlander78** [comment]
Thank you very much, worked like a charm.
