### ISSUE TITLE
8.2 edit mode menus / setpoint errors

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1182]
Given the sheer number of zone-specific items in 8.2, I'm trying to assign them to custom categories so I can place them in the assigned bags.  I'm able to do it for one item by right-clicking on the item in Edit Mode.  When I try to do it for the next item, the menu doesn't appear when you right-click.  I have to manually /reload the UI for it to work again.

ArkInventory 3.08.24

**Comment by behub** [comment]
I guess this is the same problem, but unsure without the error report

https://github.com/arkayenro/arkinventory/issues/1184

**Comment by Calesta** [comment]
I tried updating to 3.08.25 and the issue is still there.

**Comment by laerwen** [comment]
I have the same issue. I have to relog or reload after each category assignment. I also can no longer get into config, or interact with any AI ui features once this has happened.   Updating to the most current arkinventory has not fixed the problem.

**Comment by arkayenro** [comment]
its an issue with the dewdrop library that i have to figure out how to fix that setpoint issue.

it doesnt use worldframe, just uiparent, so im not sure why its having an issue at the moment

**Comment by Calesta** [comment]
Arkayenro, I'm not a programmer but I had another addon working strangely and it turned out the author knew about the issue and it had to do with a new secure anchoring system.

https://us.forums.blizzard.com/en/wow/t/ui-changes-in-rise-of-azshara/202487

If this is helpful, then great.  If it's not or irrelevant, then sorry for the spam. :)

**Comment by arkayenro** [comment]
that is the issue i just cant work out why the menu objects are generating that error as im not anchoring them to nameplate or worldframe, just uiparent and my own frames (which are themselves anchored to uiparent)

**Comment by arkayenro** [comment]
whats worse is the damn things will sometimes work.  if you mouse over the second level menus (just mouse up and down over them) they will fail/error and then start working again

**Comment by behub** [comment]
Is the fix i keep seeing about these issues related at all?

Seen a few addon devs make comments like .. "try and add a :ClesrAllPoints() before :SetPoint"

**Comment by behub** [comment]
Seems to be a often suggested fix to these new anchor frame issues with non-nameplate frames

**Comment by behub** [comment]
Can see a similar fix here:
https://git.tukui.org/elvui/elvui/commit/a3539e0be8481ef3a16fe83925792072424df175

Like I said, not sure if related but figured it can't hurt to throw it out there.

**Comment by arkayenro** [comment]
i think its fixed, try [r832-alpha](https://www.wowace.com/projects/ark-inventory/files/2731275)

**Comment by laerwen** [comment]
Fixed! Works like a charm. I'll report if any issues arise but seems fixed. Thanks a ton!

**Comment by Calesta** [comment]
Yep!  Works for me as well!  Thanks Arkayenro!

**Comment by Recanna** [comment]
Working for me as well! Thank you for fixing it. And since it can never be said enough - thank you for making this amazing addon.

**Comment by legend00wl** [comment]
once I use the 832alpha version instead of 3.08.25, it doesnt work at all and I can just see the blizzard default bag.whats wrong with it?

**Comment by arkayenro** [comment]
fixed in 3.08.26
