### ISSUE TITLE
Twitch not updating to most recent version after patch 8.2

### ISSUE THREAD

**Issue by moolric** [arkayenro/arkinventory#1183]
I came to say AI wasn't working at all, but I went to check what version I was on in the Twitch updater and I saw that I was not on the most recent version and Twitch did not have an Update button for AI.

I went to the versions tab and chose to download version 3.08.25. Now AI works.

I just wanted to say how I got it working for anyone else having the same trouble.

**Comment by Bulliwyfthetank** [comment]
Just wanted to add to this - Twitch updater is showing that it is installing the most recent version, but whatever it is installing is causing 100's of errors when logging in and the addon to not even load.

I physically had to download the folder, unzip, drop the new files into the addon folder to replace the new files before this worked.

Now running smoothly (as far as I can tell). Thank you Arkayenro for the work you put into this.

**Comment by arkayenro** [comment]
twitch can be, erratic, if it happens again its probably simpler to delete the arkinventory folders, then let twitch re-install, thats seems to always work
