### ISSUE TITLE
Forbidden Action

### ISSUE THREAD

**Issue by dboyraz** [arkayenro/arkinventory#1185]
`1x [ADDON_ACTION_FORBIDDEN] AddOn 'ArkInventory' tried to call the protected function 'UseToy()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `UseToy'
...faceBlizzard_Collections\Blizzard_ToyBox.lua:170: in function `ToySpellButton_OnClick'
[string "*:OnClick"]:4: in function <[string "*:OnClick"]:1>`

Renders toy box unusable after bug occurred.

**Comment by arkayenro** [comment]
the usetoy function in arkinventory has been disabled since it went secured.

do you have any other mod that uses toys? or changes the toybox interface?

**Comment by dboyraz** [comment]
Nope,nothing related to toys or toybox interface.
