### ISSUE TITLE
Using ArkInventory:Restack when personal bank is open causes stacked items to be swapped between bag and personal bank.

### ISSUE THREAD

**Issue by speedwaystar** [arkayenro/arkinventory#1187]
To reproduce, have a 200 stack in your bags, and a 100 stack of the same item in your bank. open the bank, and initiate ArkInventory:Restack. result: the stacks swap position. your bags now contain the 100 stack, and your bank contains the 200 stack. also reproducible for items that stack in lower amounts. Blizzard:Cleanup does not cause this behaviour.

NOTE: both my bag and my personal bank are (or were afaik) using the same Design, which I set up back in the day when there was a Config pane which allowed you to assign the same Design to multiple inventory types. This pane doesn't seem to exist anymore, so maybe the addon now expects different bag types to have different Design templates and is having restack issues if they inherit the same one?

**Comment by MrUzagi** [comment]
You are sure AI isn't just filling up the stack in the bank and then just doesn't start a new stack? (Which would look like a swap with the stack sizes you mentioned.) What happens if you have 120 in the bank and 180 in your bags? Does it still swap (i.e. 180 in the bank and 120 in your bags) or is it still 200 in the bank and 100 in the bags after a restack? I would hazard a guess for the latter.

If this is intended or not I don't know. (I can't remember if AI used to fill more slots even outside the reagent bag. I guess I don't use that very often.) However I have noticed that I have to start a new stack manually in the bank if my reagent bag is full.

**Comment by speedwaystar** [comment]
it should not be transferring items from my bags to the bank at all when I
do a restack. this is not the expected behaviour of restack.

**Comment by MrUzagi** [comment]
It is if you use ArkInventory:Restack. If you do not want that behavior you need to change it back to Blizzard:Cleanup.
See: https://github.com/arkayenro/arkinventory/wiki/UserGuide_Restacking

**Comment by speedwaystar** [comment]
>
> The Restack variant ignores the Fill Leftmost Bags option


According to your flowchart,

>
>    -
>
>    (optional) fill up empty reagent bank slots with items from your
>    normal bag slots
>    -
>
>    (optional) fill up empty bank slots with items from your normal bag
>    slots
>
>  should only occur if Fill Leftmost Bag is enabled.

I've checked with AdvancedInterfaceOptions and "Loot to Leftmost Bag" is
*not* enabled.



Nevertheless, ArkInventory:Restack will still silently restack (for
instance) the last 5 battle elixirs from my bag back in my bank, a fact I
will only discover some time later in a raid much to my annoyance.

Is there a way to make this either user configurable, or at least
double-check that it's obeying Fill Leftmost Bags? I understand that I can
use Blizzard:Cleanup, and I am doing so now, but I think this bug report
stands.

**Comment by speedwaystar** [comment]
I'm assuming "Loot to Leftmost Bag" == "Fill Leftmost Bags". if it doesn't
I have now idea where the second option is defined.

**Comment by MrUzagi** [comment]
I'm not the author so I cannot vouch for the correctness of the wiki page. Also I might misunderstand your issue, so I'll mull over it for a bit and see if I can come up with a better answer, or if someone else can jump in. :-)

**Comment by arkayenro** [comment]
> To reproduce, have a 200 stack in your bags, and a 100 stack of the same item in your bank. open the bank, and initiate ArkInventory:Restack. result: the stacks swap position. your bags now contain the 100 stack, and your bank contains the 200 stack. also reproducible for items that stack in lower amounts. Blizzard:Cleanup does not cause this behaviour.

if you have the topup option enabled then this is supposed to happen.

> so maybe the addon now expects different bag types to have different Design templates and is having restack issues if they inherit the same one?

restack/cleanup are global options, they dont care about how your windows are setup

> I've checked with AdvancedInterfaceOptions and "Loot to Leftmost Bag" is
*not* enabled.

** loot ** to leftmost bag is only for loot, i do not check its state when restacking but the restack code starts in the highest (rightmost) numbered bag and slot and works it way down to the first

> Nevertheless, ArkInventory:Restack will still silently restack (for
instance) the last 5 battle elixirs from my bag back in my bank, a fact I
will only discover some time later in a raid much to my annoyance.

that would be the deposit all reagents (bank) option.

> Is there a way to make this either user configurable,

it already is, right click on the restack icon.  the options will change depending on what type you have selected

> or at least double-check that it's obeying Fill Leftmost Bags?

there is no fill leftmost bags option that i am aware of.  nor do i want to go to the effort of changing the restack code to allow for left/right filling as the entire point of a bag mod is to not look at your original blizzard bags - ie it does not matter where they are in your bags, you've told AI where you want them in your AI window so thats where they will always be displayed.

**Comment by speedwaystar** [comment]
not looking at your bags is one thing. not differentiating between your
bags and your bank is quite another. however, i shall simply grit my teeth
and use the Blizzard sort. you can close the ticket.

**Comment by arkayenro** [comment]
there are options, you could use them, but if not then im ok with closing the ticket
