### ISSUE TITLE
LUA error when clicking on empty bag slot

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1188]
I get the following error upon accidentally right-clicking any empty bag slot:

Date: 2019-07-21 15:28:45
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ArkInventory\ArkInventory.lua line 8044:
   Usage: GetItemInfo(itemID|"name"|"itemlink")
Debug:
   [C]: ?
   [C]: GetItemInfo()
   ArkInventory\ArkInventory.lua:8044: Frame_Item_PreClick()
   [string "*:PreClick"]:1:
      [string "*:PreClick"]:1
Locals:

**Comment by arkayenro** [comment]
that was lazy of me, i wasnt checking if there was an actual item there

will be fixed next release

**Comment by arkayenro** [comment]
fixed in 3.08.29
