### ISSUE TITLE
[v30828] Cannot find a library instance of "AceAddon-3.0".

### ISSUE THREAD

**Issue by outlying** [arkayenro/arkinventory#1189]
Removing Ark and reinstalling it did **not** help

```
Date: 2019-07-24 15:36:02
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ArkInventory\ArkInventoryConst.lua line 10:
   Cannot find a library instance of "AceAddon-3.0".
Debug:
   [C]: error()
   !Swatter\Support\LibStub.lua:23: LibStub()
   ArkInventory\ArkInventoryConst.lua:10: in main chunk
Locals:
(*temporary) = "Cannot find a library instance of "AceAddon-3.0"."

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ArkInventory, v30828
  BattlePetBreedID, vr199
  BlizRuntimeLib_enUS v8.2.0.80200 <none>
  (ck=84)
```

**Comment by outlying** [comment]
Well, the second reinstall did the trick ... weird 

However, you are the only addon developer(s) that have problems like this one ...

**Comment by arkayenro** [comment]
hard to have problems with text files.  plus if it eventually works then its not the files.

**Comment by magus424** [comment]
I just had this problem; the twitch client was installing the -nolib version, so it did not include aceaddon (just adding this here in case someone else has the same problem later)
