### ISSUE TITLE
ArkInventory Error

### ISSUE THREAD

**Issue by KayliaHunter** [arkayenro/arkinventory#1191]
I've been using ArkInventory consistently for years. It just broke down some time ago. Everything works fine on my main Char and ArkInventory was not found at the twinks. Unfortunately, before I found this page, I deleted everything that has something to do with ArkInventory. I thought a complete reinstallation helps. I would redo my pocket settings. (But I have the ArkInventory.lua and .bak). I have reinstalled version 3.08.21. ArkInventory will open now, but I get this error:
Error> interface \ FRAMEXML \ ItemButton Template.lua65: attempt to index local 'icon' (a nil value)
Unfortunately, the other comments did not really help me. I'm such a noob ....
I hope someone can help me, because otherwise I do not know very well about such things ....

**Comment by arkayenro** [comment]
i think you needed to upgrade to 3.08.25 (at the time) but .29 now,not .21

there were changes to the xml code that meant that older versions would never work
