### ISSUE TITLE
(Question) Rings and trinkets Rule not working

### ISSUE THREAD

**Issue by AsmodeusCruentus** [arkayenro/arkinventory#1192]
Hello. 

so i've been trying for like 3 hours reaching on 4 now to get This rule to work.

I've written it up a few different ways, and currently only 2 trinkets get moved into the assigned bag

these are the rules that i have at the moment

tt( "finger", "trinket" ) and ilvl(380 , 460)
equip( "trinket", "finger" ) and ilvl( 380 , 460 )

For some reason the TT one moves 2 trinkets which are 380 and 385 ilvl
but ignores all other trinkets, and i honestly can not for the life of me, find anything on the wiki
or these forums to help me fix this.

if anyone... has any clue on how to help me fix this, it would be greatly appreciated.

Thanks in advance.
Asmodeus

**Comment by arkayenro** [comment]
with either rule active go into edit mode and check the debug for an item that isnt being assigned to it that should be

check what the current assignment is and if its another rule then you need to give these rules a higher priority value

if its another category then click on the default category assignment to reset it back, then the rule can pick it up

**Comment by AsmodeusCruentus** [comment]
> check what the current assignment is and if its another rule then you need to give these rules a higher priority value

How would I go about giving it a higher priority value? 
can't seem to find anything regarding priority anywhere

**Comment by arkayenro** [comment]
when you edit the rule, change the order

the lower the number the higher the priority it has

**Comment by AsmodeusCruentus** [comment]
> when you edit the rule, change the order value
> 
> the lower the number the higher the priority it has

ohhh, There we go, love you <3

10/10 Support

Ubisoft aint got nothing on you!
