### ISSUE TITLE
Make an item glow from another addon with ArkInventory installed

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [arkayenro/arkinventory#1193]
Hello,

I'm trying to make an item glow inside the bags of the player, based on the bag ID and the slot ID. I'm doing it like this (this is working with vanilla bag) : 

```
local function SetBagItemGlow(bagID, slotID, color)
	for i = 1, NUM_CONTAINER_FRAMES, 1 do
		local frame = _G["ContainerFrame"..i]
		if frame:GetID() == bagID and frame:IsShown() then
			item = _G["ContainerFrame"..i.."Item"..(GetContainerNumSlots(bagID) + 1 - slotID)]
		end
	end
	if item then
		item.NewItemTexture:SetAtlas(color)
		item.NewItemTexture:Show()
		item.flashAnim:Play()
		item.newitemglowAnim:Play()
	end
end
```

My guess is that I need another way to get the item in ArkInventory. Do you have any idea how I can get the item with their bag id and slot id (ie position in wow official bag) when ArkInventory is installed ?

Thank you in advance, this is my first addon and I've been using Ark for a very long time so thank you for making my life easier all those years :)

**Comment by Pierre-Sassoulas** [comment]
I tried to access the global value of ArkIventory, like I did for OneBag3 
```
if IsAddOnLoaded("OneBag3") then
    item = _G["OneBagFrameBag"..bagID.."Item"..slotID]
```
but without success.

**Comment by arkayenro** [comment]
ArkInventory.API.ItemFrameGet( loc_id, bag_id, slot_id )

or if you want to iterate over all, or a specific location and/or bag

ArkInventory.API.ItemFrameLoadedIterate( loc_id, bag_id )

**Comment by Pierre-Sassoulas** [comment]
Wow, this helps a lot, apparently, I suck at reading code! Thank you very much !

**Comment by Pierre-Sassoulas** [comment]
So for the record, after some research this mostly works :
````
       -- bagID, slotID are blizzard ID
        local loc_id, bag_id = ArkInventory.BlizzardBagIdToInternalId(bagID)
        local framename, item = ArkInventory.API.ItemFrameGet( loc_id, bag_id, slotID)
       -- framename is the name of the frame, item is an "ItemButton" frame containing the object in ArkInventory interface
````

I need to read some doc about `ItemButton` in order to make it glow as if it was a traditional bag space (ie glow temporarily as long as the user did not mouseover). So far the previous `item.newitemglowAnim:Play()` does not seem to works, but I managed to use `ActionButton_ShowOverlayGlow(item)` makes it glow permanently.

Closing :)

**Comment by arkayenro** [comment]
it should act just like a normal item/slot button, its just got some extra bits attached to it.

the only issue is that if AI sees an update for that location then its possible it will refresh that button and strip away any changes you made to it as it sets everything on an update

**Comment by Pierre-Sassoulas** [comment]
ho, I see. Is this linked to the "remove glow from new item" option in ArkInventory? Or is this more complicated?

**Comment by arkayenro** [comment]
it depends on whats triggering your code, if AI triggers on that same thing and triggers an update, or if you have that clear new item glow on window open option enabled

ie, when/why are you new item glowing the item?  if its an item based trigger then AI will probably see it as well and update, ie it could just be a timing issue.  your actions need to go after AI, not before - how to do that though could be problematic

**Comment by Pierre-Sassoulas** [comment]
The trigger is typing ctrl when the shift key is down. The addon does this  (simplified but everything important is there):
```
if key == "LCTRL" and state == 1 and IsShiftKeyDown() then
    OpenAllBags()
    for bagID = 0, NUM_BAG_SLOTS do
        for bagSlot = 1, GetContainerNumSlots(bagID) do
             now = -- The cheapeast grey item
    ...
    PickupContainerItem(now.bag, now.slot)
    ...
    local loc_id, bag_id = ArkInventory.BlizzardBagIdToInternalId(now.bag)
    local _, item_frame = ArkInventory.API.ItemFrameGet( loc_id, bag_id, now.slot)
    item_frame.NewItemTexture:SetAtlas("orange")
    item_frame.NewItemTexture:Show()
    item_frame.flashAnim:Play()
    item_frame.newitemglowAnim:Play()
end
```

So I don't think it's the same trigger than Ark? Is there an API to change the glow options in ArkInventory? I'm going to try to change them manually first to see if it works better.

**Comment by arkayenro** [comment]
its probably the timing between when you do the openallbags to when the ark interface is drawn.  your code runs instantly, my code is staggered so it doesnt lock up the game

the `PickupContainerItem` will trigger an AI update on that particular item (it needs to grey it out)

you may be able to get around it by using a combination of what you already have plus secure hooking `ArkInventory.API.ItemFrameUpdated( ... )` with a new function of your own that does a check for control and shift being down and updating the itemtexture if it is

eg, put this somwhere in your onload or oninititize
`hooksecurefunc( ArkInventory.API, "ItemFrameUpdated", YourMod.AIGlow )`

then add this function to your mod (replace YourMod with the name of your mod)
```
local function YourMod.AIGlow( ... )
  --need to set key and state or ensure they are either global, or better local to this file
  if key == "LCTRL" and state == 1 and IsShiftKeyDown() then
    local item_frame, loc_id, bag_id, slot_id = ...
    item_frame.NewItemTexture:SetAtlas("bags-glow-orange")
    item_frame.NewItemTexture:Show()
    item_frame.flashAnim:Play()
    item_frame.newitemglowAnim:Play()
  end
end
```

**Comment by Pierre-Sassoulas** [comment]
Hello again, just a quick update, I managed to fix it thanks to your help. Thanks a lot again. It's a bit laggy because I'm calculating everything for every item frame update. Bagnon also forces me to use the same brute force approach and I think really showing that I'm not used to the event paradigm. I should probably store the result in something global, but I don't know when to update this result (when the user launch the addon seems not enough, for every item frame update seems a bit too much, the best would probably be for inventory changes). Anyway, I digress, I'll refine later, thank you for your time !
