### ISSUE TITLE
Error when opening bank in wow classic with r844 alpha

### ISSUE THREAD

**Issue by Nevyr28** [arkayenro/arkinventory#1197]
8x ArkInventory\ArkInventory-30900.lua:11410: ArkInventory\ArkInventory.lua:7303: attempt to index global 'C_TransmogCollection' (a nil value)
[C]: ?
ArkInventory\ArkInventory-30900.lua:11410: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = "ArkInventory\ArkInventory.lua:7303: attempt to index global 'C_TransmogCollection' (a nil value)"

**Comment by arkayenro** [comment]
should be fixed next release
