### ISSUE TITLE
Deutsch translations faild to load

### ISSUE THREAD

**Issue by banks2337** [arkayenro/arkinventory#1198]
I can't use the addon because I get this message all the time :(

I hope that you can solve the problem quickly, because there is no comparable good addon for bags. 

Edit: classic btw

**Comment by arkayenro** [comment]
roll back to a previous alpha for the moment if you need to keep going

**Comment by arkayenro** [comment]
you were running the 3.09 alpha?  i dont get any translation failures if i swap to DE

**Comment by banks2337** [comment]
> you were running the 3.09 alpha? i dont get any translation failures if i swap to DE

Oh, damn, I used the version you get from the twitch client. That was apparently a 3.08. Now everything works perfectly.

Thanks a lot for the quick help!
