### ISSUE TITLE
Soul Shard Bag - Classic

### ISSUE THREAD

**Issue by fpatten** [arkayenro/arkinventory#1199]
Receiving error "WARNING> bag [4] [1.5] [Backpack] type is unknown, queuing for rescan" when Small Soul Pouch is in slot 4. Moved Shard bag to slot 3, and same error reported on slot 3. Tested with r845-r847 alpha builds.

**Comment by arkayenro** [comment]
you can disable that message in the config

i dont have a soul bag yet so cant test properly to work o ut whats happening

**Comment by arkayenro** [comment]
is it still doing it in the r848-alpha?

**Comment by fpatten** [comment]
Unknown bag error seems to be fixed in r849.
