### ISSUE TITLE
Lua error when sorting Bags

### ISSUE THREAD

**Issue by Aergernis** [arkayenro/arkinventory#1200]
Hi,
whe clicking on sort i get the folowing error. German classic client (but also happens when set to english), Alpha r847:

`1x ArkInventory\ArkInventory-30900.lua:11460: ArkInventory\ArkInventoryRestack.lua:1236: attempt to call global 'SortBags' (a nil value)
[C]: ?
ArkInventory\ArkInventory-30900.lua:11460: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = "ArkInventory\ArkInventoryRestack.lua:1236: attempt to call global 'SortBags' (a nil value)"
`

**Comment by arkayenro** [comment]
will be fixed next relase
