### ISSUE TITLE
[request]Show free bag space

### ISSUE THREAD

**Issue by Talimar** [arkayenro/arkinventory#1204]
Hey. Is it possible to show free bag space on the backpack like you can on retail?
Ammo does show up:
https://i.imgur.com/i5slNOD.png

**Comment by Liberatorz** [comment]
I found the setting.  You'll want to go into config, then settings tab, then Designs (Styles/Layouts), then Window, then Status, and uncheck the box Full Display.  That'll switch it from the used/total to unused space number.

**Comment by Talimar** [comment]
No that is a different thing. Anyway I found this addon that does it instead called BagFreeSpaceCounter.
