### ISSUE TITLE
Throws error when using Warlock Soul Pouch

### ISSUE THREAD

**Issue by michaelvolz** [arkayenro/arkinventory#1206]
`using 1.00.04 release`

When using a shard bag / warlock `soul pouch`, following error will be displayed over and over and over again:

> ArkInventoryClassic: WARNING> bag [4] [1.5] [Backpack] type is unknown, queuing for rescan

btw: I love this AddOn, keep up the good work

**Comment by arkayenro** [comment]
should be fixed in r849-alpha
