### ISSUE TITLE
not placing soul shards into soul pouch

### ISSUE THREAD

**Issue by vampyricus** [arkayenro/arkinventory#1207]
When using a soul pouch ark is not placing all the soul shards ONLY into the soul pouch and custom rule for that is not working

**Comment by arkayenro** [comment]
should be fixed in r849-alpha (possibly earlier but thats the latest at the moment)

**Comment by arkayenro** [comment]
this should be fixed but re-open if it isnt.  my warlock isnt level 20 yet so dont have a soul bag to confirm
