### ISSUE TITLE
Restack frame rate drop.

### ISSUE THREAD

**Issue by AndieOz** [arkayenro/arkinventory#1208]
If I use the **'Restack'**  feature, then enter combat my frame rate drops to 9 FPS and only a /reload solves the problem. I using this feature on my warlock and have a 16 slot soul bag. I'm pretty sure the problem is linked with the soul bag and I know you have had other reported problems with soul bags. The error message I see is **'Only Soul Shards can be placed in that'**

**Comment by arkayenro** [comment]
should be fixed in r849-alpha, possibly r850 (which i havent uploaded yet)
