### ISSUE TITLE
Projectiles category not working (Classic)

### ISSUE THREAD

**Issue by Kezwo** [arkayenro/arkinventory#1212]
Hi, I tried to set up a bar that contains all my bullets and empty ammo pouch slots in WoW Classic. The Category Empty -> Quiver is working fine for the empty slots, but System -> Projectile does not move my bullets to the assigned bar. I don't know if it is working for arrows.

**Comment by arkayenro** [comment]
yeah, looks like i setup the empty slots but missed the actual items

will be fixed next release

**Comment by arkayenro** [comment]
fixed in 3.09.00
