### ISSUE TITLE
herbs assigned to wrong category

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1214]
All herbs now categorized as "Crafting Reagent" instead of "Trade Goods > Herb". First noticed this issue in r846, still exists in 3.09.00. Had to revert to 3.08.29 again where it's still good.

**Comment by hollo6** [comment]
Potions also went to System > Default.

**Comment by crichton32** [comment]
Most herbs are categorized as "Trade Goods > Other"  on the latest alpha (r857) in Classic.

**Comment by arkayenro** [comment]
fixed in 3.09.01
