### ISSUE TITLE
Rockscale Cod miscategorized

### ISSUE THREAD

**Issue by Malevola** [arkayenro/arkinventory#1215]
Items 3632 & 2458 appear as "Explosives & Devices"

**Comment by arkayenro** [comment]
those ids are for fangore's paw (quest item) and elixir of minor fortitude?  rockscale cod is 4594

go into edit mode and click on the item, select debug then copy the itemstring

you can also just select a new category assignment for them youself while youre in edit mode.  theres lots of items that blizzard have in the wrong categories.

**Comment by Malevola** [comment]
Rockscale Code item string: item:6362::::::::34:::::::
Category: 1!426

Couldn't edit the category. Could modify the item string, the short ID and the PT sets.
