### ISSUE TITLE
Items not moving to assigned bars / moving back to unassigned bar inconsistently (Classic)

### ISSUE THREAD

**Issue by crichton32** [arkayenro/arkinventory#1216]
I've been having this issue on all the classic builds (Just updated to r857-alpha, 3.09.01). Sometimes I will get items that just hang out in the default unassigned bar instead of the bar that they are assigned to. Then sometimes they'll move to the correct bar and sometimes back to the unassigned one again, it's pretty inconsistent so I haven't been able to narrow it down much. 

Here you can see a handful of items just hanging out in the bottom right bar 1, and then while I was trying to take a screenshot showing the leather was assigned on bar 19, they all corrected and followed their assignments again. But this has been happening quite a lot on classic with random items, sometimes it's all of the leather, sometimes its just 1 stack of light leather, but it's not all or nothing and happens with the default categories or custom rules. 

Thanks

https://imgur.com/a/HB57mkE

**Comment by arkayenro** [comment]
make sure you dont have new items enabled, that will put things into the new items category for X number of minutes, then they go back to their normal category/rule.

you may also want to try the latest alpha

**Comment by crichton32** [comment]
Thank you! There's always some setting I'm missing. Between turning off new items and the latest alpha it's feeling a lot better so far!
