### ISSUE TITLE
Error on Startup.

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1218]
Hello, love your addon. Just reporting some issues that I see when I sign in. Not sure if it's with your addon or some combination of addons, but I've got time while I wait for the queue. I've already uninstalled and reinstalled (including removing saved variables), so what's here should be the latest and greatest at time reporting.

Date: 2019-09-15 01:42:01
ID: -2
Error occured in: Global
Count: 1
Message: ...rkInventory\Externals\Ace3\AceEvent\AceEvent-3.0.lua line 33:
   Attempt to register unknown event "GUILDBANKFRAME_OPENED"
Debug:
   [C]: ?
   [C]: RegisterEvent()
   ...rkInventory\Externals\Ace3\AceEvent\AceEvent-3.0.lua:33: OnUsed()
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:142: RegisterEvent()
   FreeRefills\FreeRefills.lua:190:
      FreeRefills\FreeRefills.lua:181
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.2
  ArkInventory, v30901
  ArkInventoryRules, v20000
  ArkInventoryRulesExample, v20000
  ArkInventorySearch, v20000
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AutoLootPlus, v2.0.0-11302
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  ClassicCastbars, vv1.0.5
  ClassicCastbarsOptions, v
  ClassicThreatMeter, v1.06
  Details, v
  DetailsTinyThreat, v
  ElvUI, v1.08
  Enchantrix, v8.2.6392 (SwimmingSeadragon)
  FreeRefills, v116
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixMaps, v1.13.30
  LeatrixPlus, v1.13.30
  MapCoords, v1.4
  Memoria, v8.2
  MerInspect, v1.0.1
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  oGlow, v2.2.8
  QuestAnnounce, v8.0.2.1
  Questie, v4.0.18 BETA
  QuestLogEx, v1.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v1.0.5
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TrackingEye, v1.0
  TradeSkillMaster, vv4.8.7
  VendorPrice, v1.2.4
  WeakAuras, v2.14.6
  WIM, v3.7.33
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=570)

**Comment by arkayenro** [comment]
thats an issue with FreeRefills - its just calling the ace library in arkinventory

**Comment by Gogo1951** [comment]
Cool, thanks!
