### ISSUE TITLE
`Restack` tries to put Soul Shards into a Herb Pouch

### ISSUE THREAD

**Issue by Rosto75** [arkayenro/arkinventory#1220]
I have equipped a 12-slot Herb Pouch and hit `Restack`, but addon tries to put Soul Shards into it, and is stuck in the loop, with the message: `That item doesn't go in that container.` Only `Reload` helps.

**Comment by arkayenro** [comment]
which version do you have?  earlier versions had that issue, but it was fixed in one of the later alphas

**Comment by Rosto75** [comment]
> which version do you have? earlier versions had that issue, but it was fixed in one of the later alphas

Classic 1.00.04

**Comment by arkayenro** [comment]
can you delete that, i merged it into arkinventory.

you can just install arkinventory in classic and it will work, its also got all the updates/fixes in there.
