### ISSUE TITLE
What's the correct place to download (classic)?

### ISSUE THREAD

**Issue by nmonterroso** [arkayenro/arkinventory#1221]
I really like this addon, but I have a super old version (don't remember where I got it from) and it suffers from the soul shard issue in #1220. I'm trying to update from the Twitch client but WoW Classic says the addon is out of date. I've tried installing `3.09.00`, `3.09.00-nolib`, `r859-alpha`, and `	r859-alpha-nolib` through the Twitch client but they all have the same issue.

Any ideas?

**Comment by arkayenro** [comment]
its meant to be out of date for classic, as the toc version is set for retail and you cant have two toc versions, and if i set the toc to classic it wont load at all in retail (as it thinks it too old)

just tick the box to load out of date addons at the loading menu for classic and youll be fine

just make sure youre downloading arkinventory, not arkinventoryclassic

**Comment by nmonterroso** [comment]
OK, that did it. Initially I thought it wasn't working, but my mistake was that while I was checking the boxes for arkinventory, I wasn't clicking the "load out of date addons" checkbox in the top right. 

Thanks!
