### ISSUE TITLE
Recategorization of crafting mats has broken sorting

### ISSUE THREAD

**Issue by DaveB1977** [arkayenro/arkinventory#1222]
Crafting mats default category is now "Crafting Reagent" but it seems that items that are not reagents are part of tradeskill categories. To give one example, Gilded Seaweave cloth that used to use "Trade Goods -> Cloth" are now NOT assigned to that group meaning a lot of painful setup having to be re-done for this change.

This is only a single example, but it seems to have affected multiple items. Very frustrating.

**Comment by arkayenro** [comment]
which version do you have installed?  theres been a lot of category code changes in the last lot of alphas due to classic

**Comment by DaveB1977** [comment]
It's V3.09 I have, I guessed it'd be something to do with classic... What are my options, roll back a little or something else?

Thanks for the assist :)

**Comment by arkayenro** [comment]
if its 3.09.01 but not an alpha you could download the latest alpha

if you use twitch i think you right click on the arkinventory entry and select release type to change it to look for alpha versions

**Comment by DaveB1977** [comment]
I do use the twitch client, and also have the release type set to Alpha, but 3.09.01 doesn't show up. I'm not overly concerned if it's to be "fixed" in the next release, just saves me having to manually re-assign 30+ toons worth of inventory, then having to change it all back ><

**Comment by arkayenro** [comment]
its been pretty stable for a couple of days so i'll probably set it to release in the next hour or so

**Comment by DaveB1977** [comment]
Legend, this is the one addon I just could not live without now, used it for as long as I can remember and have pimped it out to anyone that I could. Best in it's class in my humble opinion, a hearty thank you for all the effort it must take <3

**Comment by arkayenro** [comment]
try 3.09.01 and let me know if the categories are better

**Comment by DaveB1977** [comment]
Updated to 3.09.02 and all seems to be ok now, thanks for the quick fix.
