### ISSUE TITLE
Sorting not working for cloth or disenchanted materials in Classic

### ISSUE THREAD

**Issue by padensplace** [arkayenro/arkinventory#1224]
Probably other ones as well but these are the two not working.

Oddly all my other custom sorts still work fine.

I saw in another thread (https://github.com/arkayenro/arkinventory/issues/1222) to make sure I'm using version 3.09.01 and that is indeed what I'm currently using alongside WoW classic 1.13.2.

Thank you.

**Comment by arkayenro** [comment]
what professions do you have?
what categories are the items getting assigned to?

**Comment by padensplace** [comment]
My professions are tailoring and enchanting.

The groups I had set were Trade Goods > Cloth for group 3 and Trade Goods > Enchanting for Group 2.

It seems items are going to Skill > Enchanting and Skill > Tailoring.

I tried changing the groups to to match the items (Skills instead of Trade Goods) and it kind of worked except it also groups in other stuff like leathers into the Tailoring one, and my enchanting wand and a wildvine(??) along with enchanting.

Including a screenshot for reference.

![WoWScrnShot_092019_221449](https://user-images.githubusercontent.com/55607642/65366605-30dffe80-dbf4-11e9-92f8-3531860c067e.jpg)

**Comment by padensplace** [comment]
Update: After checking my bank I also noticed that Runecloth is set as Consumable > Reputation

**Comment by arkayenro** [comment]
runecloth should be fixed next release, reputation was higher than tradegoods

in the config under general > professions, set the priority to ignore, that will ignore your skills when categorising an item and leave it in tradegoods (or consumable)

**Comment by padensplace** [comment]
Hmm there doesn't seem to be an option to ignore. There's 1 dropdown menu with only 1) Enchanting and 2) Tailoring.

![WoWScrnShot_092119_032108](https://user-images.githubusercontent.com/55607642/65369739-f3449b00-dc1e-11e9-9141-886d18873757.jpg)

**Comment by arkayenro** [comment]
try 3.09.02 (or the alpha after it)

**Comment by padensplace** [comment]
Upgraded to the alpha and that seems to do the trick! Thank you for the assistance and awesome mod!
