### ISSUE TITLE
Repeated warnings (Aborted scan of bag 0, location 1) since Patch 8.2.5

### ISSUE THREAD

**Issue by Toabo** [arkayenro/arkinventory#1226]
With the release of Patch 8.2.5, I'm getting the following warning message every time I have a loading screen (raid/dungeon entrance, portals, hearthstone, initial login, etc.)

> WARNING> Aborted scan of bag 0, location 1 [Backpack] size returned was 0, rescan has been scheduled for 5 seconds.  This warning can be disable in the config menu.

I don't actually get any errors.  The only (admittedly minor) issue is that when my bags are re-opened, about 90% of my inventory gets flagged as "New Items" until either I manually reset New Items or the standard timer passes.  

As such, it's a mild annoyance at worst.  Still, it's strange new behavior in the aftermath of a Patch, so I thought I should report it

**Comment by arkayenro** [comment]
try swapping the bags in the slots around, spoecifcally the first one

basically i can tell theres a bag in that slot but the game isnt returning any data for it so i just ignore it and try again later. it should eventually clear itself up but im not sure why it would keep happening unless your local item cache went weird?

theres a way to delete the local item cache (its in the WTF folder) but i cant remember which specific file it is.

**Comment by Toabo** [comment]
I've tried swapping bags multiple times, but I still seem to get the WARNING message above each time I took a portal.  (That was the easiest way to test this multiple times in a row.) 

Now I've found that the new item New Item reset isn't consistent.  It's never 100% of inventory classified as New; there are always a dozen items (~10% of the total) that remain in their proper categories.  After some loading screens, I only get a partial reclassification as New (say ~25% New).  And then on some transitions, I'll get the WARNING message but not items are transformed.  (Taking the portal to Stormwind seems to be most consistently cause no reclassification for some reason.) 

I also tried deleting Arkinventory (but not the Saved Variables) and re-installing.  No change.  Still the warnings and New Item resets.

Now once after an extended session of portal-taking and bag swapping and item resetting, I did manage to get an ArkInventory error.  Since that only ever happened the one time, I assume it's probably unrelated.  I'll include it here just in case, though.





> 1x ArkInventory\ArkInventory-30826.lua:7953: attempt to index local 'i' (a nil value)
> ArkInventory\ArkInventory-30826.lua:7953: in function `Frame_Item_OnEnter'
> [string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>
> 
> Locals:
> frame = ARKINV_Frame1ScrollContainerBag2Item31 {
>  0 = <userdata>
>  PostOnLoad = <function> defined @FrameXML\ItemButtonTemplate.lua:169
>  BattlepayItemTexture = <unnamed> {
>  }
>  IconOverlay = <unnamed> {
>  }
>  BagStaticTop = <unnamed> {
>  }
>  GetItemContextMatchResult = <function> defined @FrameXML\ContainerFrame.lua:1463
>  IconBorder = <unnamed> {
>  }
>  newitemglowAnim = <unnamed> {
>  }
>  icon = ARKINV_Frame1ScrollContainerBag2Item31IconTexture {
>  }
>  ArkBagHighlight = ARKINV_Frame1ScrollContainerBag2Item31ArkBagHighlight {
>  }
>  LevelLinkLockTexture = <unnamed> {
>  }
>  ARK_Data = <table> {
>  }
>  RegisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:175
>  UnregisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:182
>  PostOnHide = <function> defined @FrameXML\ItemButtonTemplate.lua:198
>  NewItemTexture = <unnamed> {
>  }
>  BagStaticBottom = <unnamed> {
>  }
>  ArkBorder = ARKINV_Frame1ScrollContainerBag2Item31ArkBorder {
>  }
>  itemContextChangedCallbackIsSet = true
>  ItemContextOverlay = <unnamed> {
>  }
>  PostOnShow = <function> defined @FrameXML\ItemButtonTemplate.lua:189
>  flash = <unnamed> {
>  }
>  itemContextMatchResult = 3
>  count = 1
>  flashAnim = <unnamed> {
>  }
>  ExtendedSlot = <unnamed> {
>  }
>  ExtendedOverlay2 = <unnamed> {
>  }
>  hasItem = 1
>  ArkItemTinted = ARKINV_Frame1ScrollContainerBag2Item31ArkItemTinted {
>  }
>  itemContextChangedCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:170
>  JunkIcon = <unnamed> {
>  }
>  SetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:202
>  UpdateItemContextOverlay = <function> defined @FrameXML\ItemButtonTemplate.lua:222
>  locked = false
>  timeSinceUpgradeCheck = 0
>  UpdateTooltip = <function> defined @ArkInventory\ArkInventory.lua:7940
>  ArkListEntry = ARKINV_Frame1ScrollContainerBag2Item31ArkListEntry {
>  }
>  ArkTransmogIcon = ARKINV_Frame1ScrollContainerBag2Item31ArkTransmogIcon {
>  }
>  ArkAgeText = ARKINV_Frame1ScrollContainerBag2Item31ArkAgeText {
>  }
>  Count = ARKINV_Frame1ScrollContainerBag2Item31Count {
>  }
>  ExtendedOverlay = <unnamed> {
>  }
>  UpgradeIcon = <unnamed> {
>  }
>  GetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:207
>  UpdateItemContextMatching = <function> defined @FrameXML\ItemButtonTemplate.lua:211
>  searchOverlay = ARKINV_Frame1ScrollContainerBag2Item31SearchOverlay {
>  }
> }
> loc_id = 1
> bag_id = 2
> blizzard_id = 1
> i = nil
> reset = true
> (*temporary) = 1
> (*temporary) = 2
> (*temporary) = 31
> (*temporary) = <table> {
>  toon = <table> {
>  }
>  workpad = <table> {
>  }
>  profile_id = 1001
>  layout = <table> {
>  }
>  profile = <table> {
>  }
>  catset = <table> {
>  }
>  style = <table> {
>  }
>  style_id = 1001
>  catset_id = 1001
>  layout_id = 1001
>  player = <table> {
>  }
>  loc_id = 1
> }
> (*temporary) = "attempt to index local 'i' (a nil value)"
>

**Comment by arkayenro** [comment]
according to that error message youre running 3.08.26, could you upgrade to 3.09.02 and see if it still happens?

**Comment by Toabo** [comment]
Bingo.  No problems after that.  Thanks.
