### ISSUE TITLE
Adding the junk icon to itemFrame of junk item if Scrap addon is used

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [arkayenro/arkinventory#1229]
Hello, while doing it for GreyHandling I found a way to add the Junk Item icon (little gold coin at the top left of an icon, used for Grey in wow vanilla bag), in ArkIventory. Would you be interested in a merge request? Maybe a patch? Is the code on something else than github? The way I would do it is this :

```lua
function ArkInventory.API.ItemFrameUpdated(itemFrame, loc_id, bag_id, slot_id)
    if "itemIsGrey" or (IsAddOnLoaded("Scrap") and Scrap:IsJunk(id, bag, slot)) then
        itemFrame.JunkIcon:SetShown(true)
    else
        itemFrame.JunkIcon:SetShown(false)
    end
end
```

The result look like this. The red border is for the cheapest junk in my addon but I hope you get the idea :
![Junk icon in ArkIventory](https://raw.githubusercontent.com/Pierre-Sassoulas/grey-handling/master/examples/arkinventory.jpg "Junk icon in ArkIventory")

**Comment by arkayenro** [comment]
probably better to include the scrap check in the ArkInventory.JunkCheck function, that way it will just work as i already display the junk icon if you enable that option

**Comment by Pierre-Sassoulas** [comment]
Ho, I did not know it was already an option in ArkInventory! That's nice. Maybe you could make it the default because it's already the default in Wow and is very useful. How can I make a merge request for the Scrap integration?

**Comment by arkayenro** [comment]
i thought it was enabled by default but maybe i didnt do that.  i'll double check when i get home

theres no code in github so nothing to merge.  you just ask for something to get changed and if i like the idea i'll change it.

in the case of this one, i'll add it whern i get home

**Comment by arkayenro** [comment]
seems i set the default for the junk icon to disabled so i'll swap that around

i've also moved some of the trash rule code into the JunkCheck function so its all in one place, plus this way it checks Scrap, SellJunk, or ReagentRestocker, if you use one of those instead

**Comment by Pierre-Sassoulas** [comment]
I will keep you updated on something very similar : Peddler integration. A user asked me to do it and but their API is not public yet. I'll open another ticket for that if the Peddler dev can make it public.

**Comment by Pierre-Sassoulas** [comment]
@arkayenro Do you know how to activate this option in ArkIventoryClassic? I swear I searched everywhere :( (I have too much config I want to keep to be able to just reset everything). I also want to test if my GreyHandling is breaking the feature (it did for Bagnon).

**Comment by arkayenro** [comment]
settings > design > your design > items > style > status icons > junk
