### ISSUE TITLE
Issues in Latest PTR Build 

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1231]
Arkayenro,

ArkInventory was working fine in the early PTR builds, but the latest build changed something that causes it to stop working.  I have the latest version (3.09.03) installed. 

4x ...rkInventory\Externals\Ace3\AceEvent\AceEvent-3.0-4.lua:33: Attempt to register unknown event "AUCTION_OWNED_LIST_UPDATE"

From the LUA error message, I'm guessing it has to do with the changes to the auction house?

Please consider this a 'heads up' for investigation before the update happens.

Thanks!

**Comment by arkayenro** [comment]
the entire auction house API has changed

**Comment by Calesta** [comment]
Understood!  This is exactly the reason I was bringing it to your attention as early as possible.  I'm sure it takes time to update all your code when Blizzard makes these changes.

Thanks for continued efforts on this great addon!

**Comment by arkayenro** [comment]
the current 870 alpha has support for the new auction house, but you have to currently open the action list for it to scan them

**Comment by Calesta** [comment]
I installed the latest alpha and tested it on the PTR and everything seems to be working well.  Thanks so much for the continued updates!

**Comment by Calesta** [comment]
Oops!  I closed this without thinking that you might want to keep it open for tracking purposes.  Sorry!
