### ISSUE TITLE
Feature Request: Separate gold and item count configs

### ISSUE THREAD

**Issue by nmonterroso** [arkayenro/arkinventory#1233]
Love ArkInventory and how configurable it is. One thing I think would be super useful though would be to separate the option for displaying gold count tooltips across characters from the item count tooltip addition. As it is now, in order for me to view my gold across characters I also need to have the item count in my tooltips, which is redundant with the counts from TSM.

This is for ArkInventory 3.09.03 in Classic.

Thanks for all the hard work on such an amazing addon.

**Comment by arkayenro** [comment]
i'll see what i can do

**Comment by arkayenro** [comment]
should be in the next release
