### ISSUE TITLE
Can't Remove Data from Previous Guild Bank

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1234]
I have 3.09.02 installed.  While in my current guild bank, I click 'Switch Character' and the menu shows options to delete the data for my current guild and an alt's guild as described in the Wiki.  I don't have an option to delete the data of my old guild and it still shows up in the tooltip.  Any thoughts?

**Comment by arkayenro** [comment]
not sure. if it shows up in the tooltip then it should show up in the switch character menu

**Comment by Calesta** [comment]
I tried on a few different characters and the old guild just doesn't show up.  You can see three (3) different guilds listed at the bottom of the tooltip below.

![Tooltip](https://user-images.githubusercontent.com/13042214/67168655-6eab8080-f374-11e9-8174-9ba2fe8850aa.png)

But when I go to a guild bank and select the 'Switch Character' only 2 are shown as seen below.

![Switch Character Menu](https://user-images.githubusercontent.com/13042214/67168658-6fdcad80-f374-11e9-8c8f-a85a089eb5f9.png)

I know I've deleted old guild data in the past, but I haven't switched guilds in over 3 years so it's clearly not something I have to do often.  That said, I have no idea if it's unique to this build or not.

It's not a game-breaker as I can live with an extra line of text in the tooltip, but it's entirely possible that these extra lines of text will build up over time if there are multiple guild swaps.

As always, thanks for the support as you're able.

**Comment by arkayenro** [comment]
any chance you could email me your (zipped) arkinventory.lua saved variables file?  arkayenro @ gmail dot com

im not sure why it wouldnt show up

**Comment by arkayenro** [comment]
if you have 3.09.03 there should be an accounts tab in the config.  you should be able to find the old guild in there and erase its data

**Comment by Calesta** [comment]
I downloaded / installed 3.09.03.  The accounts tab is easy to use and worked beautifully!  Thank you so much!
