### ISSUE TITLE
[Request] Destroy items having no sell price from auto sell groups

### ISSUE THREAD

**Issue by eFse7en** [arkayenro/arkinventory#1235]
I have a custom group with items I don't need, with "auto sell" feature enabled.
Some items do not have a sell price (Hearthstone, Tooth Pick, etc.), so I want to destroy them instead.

Scrap addon already has this feature and automatically destroys items after opening a vendor window. I was wondering if ArkInventory could implement too. 
Items could be even destroyed after looting them - both options are good.

**Comment by arkayenro** [comment]
the option is already there, but you have to enable it, and it still has to meet the quality cutoff

**Comment by eFse7en** [comment]
Ah, I'm sorry. I didn't think it's already implemented. Thanks!
