### ISSUE TITLE
Addon isn't loading

### ISSUE THREAD

**Issue by Jean77f** [arkayenro/arkinventory#1237]
The whole things just straight up isn't loading.  I have tried removing the folder and reinstalling fresh even and it just acts like it doesn't exist.  I have shut down all of my other addons and removed them and still it just doesn't exist.  There used to be a file somewhere in these forums I could use to down load and swap out when this happened but it seems to be gone now.  That page has the comments shut off and the link has been shut off as well :(  (I can't even get to the configuration menu)

**Comment by arkayenro** [comment]
the only page that allows comments is the curseforge one, simply because i want the comments in one place so i can manage them

it also has a files tab where you can download all the versions from for manual installation

does arkinventory even show up in the addons list before you pick a character?

**Comment by Jean77f** [comment]
It does, but I finally found the old zip file I had been using to fix the
issue and got it back.  Still no idea why the current Curse and Twitch
downloads won't work for me.

The only place it shows up is in the addon list.  It is there, I can turn
it on and off, but when I get in game and it is the only addon I have the
addon tab within the interface is gone.  If I have other addons then it
just isn't in the list.  If I try /ARKINV I just get the typical Bliz /help
info prompt suggestion.  I can go through my computer and find the folder
properly placed within the addons folder, within the interface, folder,
etc.

I've attached a copy of the zip drive I am using that fixes the issue for
me.  Maybe you can see in there what the difference is.  This Zip drive was
on the Git page for a while and that is where I got it.  The place where it
is posted now has the link deactivated and the posting/comments shut down.
I nearly cried when I updated by accident and couldn't find my copy of this
file.  I know some other people in my guild have the same issue. We are
super careful to just never update our ArkInventories.  Others have just
switched to other bag addons.

Thanks for your response!  I have really bad eyesight and your addon is a
life saver!  I am one of those who has sorted every last thing into a
different tab!

Many Thanks,
Linda Lawrence
aka Gracemom-Antonitis

**Comment by arkayenro** [comment]
theres no attachment attached so i cant check that, but from what you describe it was either sourced someone elses github page or it was an early version of arkinventoryclassic before that got merged into arkinventory (except that is rather obvious).

the only place you can download arkinventory from is curseforge.  any other location i wouldnt trust in the slightest

**Comment by Jean77f** [comment]
Not sure why it didn't attach
