### ISSUE TITLE
twitch app not showing any version since 8.08.29

### ISSUE THREAD

**Issue by stevietv** [arkayenro/arkinventory#1240]
I wonder if you aware that the twich app doesn't show any of your updates since 8.09 released?
Is this something to do with the way you are tagging them as also working for classing

![curseforge](https://user-images.githubusercontent.com/1117625/68074246-4c185f00-fd99-11e9-9213-6e08670a672e.png)
![Twitch App](https://user-images.githubusercontent.com/1117625/68074247-4c185f00-fd99-11e9-96c1-695eabcd2ccc.png)

**Comment by arkayenro** [comment]
that looks like a bug in the twitch app

**Comment by HealingLoa** [comment]
I got the same Problem but Twitch close every time my tickets without an answer about this issue ....

**Comment by stevietv** [comment]
Yeah, I've had a look through a number of mods that have both retail and classic versions. Any release file that is tagged for both releases doesn't show as a retail addon in twitch app. It seems that there are very little mods tagging releases for both versions now so maybe they also experienced the same problem.

I have also raised a ticket with twitch yesterday but felt the need to also raise the issue here so that author is aware that their updates are potentially not reaching the retail users.

**Comment by stevietv** [comment]
here is the reply that I have received from Twitch support. Does this make any sense to you @arkayenro on how you upload the mods?

> I think this may be more due to the way that the author has updated the addon.
> 
> While it is possible that 3.09.03 works for both versions, the way they uploaded it links to the same file on their CurseForge page.
> It is possible that they did not upload it correctly for both Retail and Classic, or they may have only updated the Classic listing for this mod.
> 
> In the meantime, since it looks like both versions should be compatible, based on the page:
> https://www.curseforge.com/wow/addons/ark-inventory/files/2801212
> 
> You can copy and paste the mod into your Retail instance if you download it for Classic.
> However, you will need to change your Addon management settings to not delete orphaned mods under profile photo > settings > addons > game specific > WoW retail
> 
> Please reach out to the Mod Author and let them know about the issue!!

**Comment by arkayenro** [comment]
i only upload a single file, it works in both clients so its tagged in curseforge that way.

im not going to upload it twice (i'd need two separate workflows on my end, and i'd have to create another project in curseforge) and tag one for each client, that would be daft.

they even say that they can see its compatible with both clients, yet the twitch app cant see that - and somehow the problem is with how i upload the file and not the twitch app?

**Comment by stevietv** [comment]
As I suspected. I gave this feedback to twitch on my ticket, pushing them in the direction that as the functionality is present in curseforge but not working in twitch then its a missing feature in the twitch client. Hopefully they will take that on board.

In the mean time, you are also now aware that via your current workflow, updates to your addon are likely not reaching the retail users via the twitch app, which I expect is how most users are maintaining their addons.

**Comment by HealingLoa** [comment]
BTW its updating since yesterday :)

**Comment by arkayenro** [comment]
only because i didnt tag is as working in classic, only retail

twitch havent responded to my ticket from 2 weeks ago

**Comment by stevietv** [comment]
this was the response that twitch gave me last:

> Thank you for taking the time to give us additional information about the issue you are encountering.  We are currently looking into the situation and have raised this with the appropriate Developers for review.
> 
> We understand that this is frustrating and can be a major inconvenience. We deeply apologize for the nature of the issue. We appreciate you taking the time to report the issue.

of course, no news since 2 weeks :D

**Comment by arkayenro** [comment]
it seems that setting the classic version to 1.13.2, instead of 1.13.3, in curseforge allows twitch to see it for both retail and classic so i'll do that for a while until it breaks

3.09.09 is tagged for both and appears to be visible for both

**Comment by gizmola** [comment]
I was having an issue where even if I deleted and reinstalled arkinventory, I was still getting classic, or perhaps the uninstall wasn't working.  I manually deleted all the arkinventoryclassic directories and lua files.  When I went back to twitch and installed, it worked perfectly the first time.
