### ISSUE TITLE
Doesn't autosell items by rules

### ISSUE THREAD

**Issue by kawaiinya2278** [arkayenro/arkinventory#1241]
I dont know why, but some rules autosells items, and some are not.

Example:
type(0) and not expansion(7) <- this must filter (and it does) and autosell (does not) all pre-BfA crafting mats.

**Comment by arkayenro** [comment]
does the rule show the gold icons next to it?

do the items also meet the junk sell requirements?

**Comment by kawaiinya2278** [comment]
> does the rule show the gold coins icon next to it?
No, it does not, and by my logic it should.

> do the items also meet the junk sell requirements?
Junk sell requirements? What requirements rule need to meet to auto sell items, that filtered correctly by that rule?

Maybe I dont get how it works?
That rule example above correctly filter what i need to be filtered. And if autosell enabled - all filtered items should be sold, no?

**Comment by arkayenro** [comment]
if the rule doesnt show the gold coins icon next to it then its not flagged as autosell - you need to set that first

the rule will just collect items that match the rule

the junk options cover what can be automatically sold

think of them as filters.  the autosell options are the final filter they have to pass through to be sold

if you have the junk options set to poor and your rule collects items all all qualities then the autosell will only sell the items from that rule that are poor quality

**Comment by kawaiinya2278** [comment]
Ahhh... so, to autosell lowlevel epics i need to set quality cutoff to epic. Thanks!
