### ISSUE TITLE
Rule problems.

### ISSUE THREAD

**Issue by laric** [arkayenro/arkinventory#1242]
![image](https://user-images.githubusercontent.com/2378120/68527967-85972000-02ed-11ea-821d-d833354c921e.png)

The rule text is as follows:

sb() and not equip()

**Comment by arkayenro** [comment]
that was the old classic version before it was merged, i presume you upgraded to the current version which handles both retail and classic?

**Comment by laric** [comment]
That is correct. I noticed that I was on an old version and upgraded and redid all my rules and it works.
Thanks.
