### ISSUE TITLE
Current version update 3.09.04 breaks addon for ClientIsArtifactPowerItem error

### ISSUE THREAD

**Issue by Trelander84** [arkayenro/arkinventory#1243]
This only applies to toons that do not have their neck im guessing? Works fine on my 120 toons, completely broken on low level alts.

![image](https://user-images.githubusercontent.com/37942320/68999907-4718dc80-087c-11ea-85b8-063b15c1366f.png)

**Comment by arkayenro** [comment]
that api only exists in retail, and the code blocks it from being called in classic, so it should always work.

its a test for an item that is AP, not an item that uses AP, so isnt neck related

i tested it in retail on a level 10 and had no issues, also on a level 13 in classic an no issues

can you paste the whole error stack?

**Comment by Trelander84** [comment]
Hmm, I had already downgraded so that I could continue working my auctions (was using an auction toon that generated that error). However I went and re-updated to current one to get your requested info and it seems fine now. Maybe bad installation?

I promise I checked multiple toons both 111+ and sub 100's.

**Comment by arkayenro** [comment]
does sound like something went wrong with the first download/install and the next one was ok
