### ISSUE TITLE
ArkInventory is currently not functioning at all.

### ISSUE THREAD

**Issue by noostere** [arkayenro/arkinventory#1245]
I currently get a blank Bag, with "Loading..."  The errors in the image are what I see when I first start the WoW client.  Please help!  NOTE:  BfA/Retail, MacOSx Mojave.

<img width="579" alt="Screen Shot 2019-11-17 at 5 29 00 PM" src="https://user-images.githubusercontent.com/13897267/69015471-2460f380-0962-11ea-9063-cbc0d04cbd2d.png">

**Comment by arkayenro** [comment]
uninstlal and re-install.  someone else had a similar issue
