### ISSUE TITLE
Strangeness after last update.

### ISSUE THREAD

**Issue by Kirbdawg** [arkayenro/arkinventory#1246]
Some of the default categories have changed.  For instance:  if you entered edit mode and look at the property sheet for Platinum Ore, it shows:  "Default:  Skill > [0109] Jewelcrafting".   It used to be classified under trade goods.   I'm not sure if this "default" is a blizzard issue, or an Arkinventory assignment.   

This isn't the only example.  Some trade goods are still correct, some are not.  I'm not sure if this happened before the last arkinventory or the last mini-patch blizzard pushed.   I'm also wondering if this is in prep for the AH changes in 8.3 by either.

Nevertheless, it's pretty much screwed up a lot of my AI organizations.   Just FYI.

**Comment by arkayenro** [comment]
do you have jewelcrafting as a skill?

what is config > general > professions > priority set to?

**Comment by Kirbdawg** [comment]
It's is currently set to Enchanting.

**Comment by Kirbdawg** [comment]
Never noticed this before.  And, yes, I do have JC as a skill.

**Comment by Kirbdawg** [comment]
I set it to ignore.   Everything is back to normal. hehe

**Comment by Kirbdawg** [comment]
Interesting.  I can use this new feature.  Tyvm

**Comment by Kirbdawg** [comment]
Appreciate the last effort.   But, more details in the change log would be helpful.   I do read them... the once on curse, that is.
