### ISSUE TITLE
Elemental trade goods categorized under Jewelcrafting

### ISSUE THREAD

**Issue by ZeShmoutt** [arkayenro/arkinventory#1249]
ArkInventory v3.09.03 (latest from the Twitch client).

A large part of (but not all) elemental trade goods are categorized under "Trade goods/Jewelcrafting" instead of "Trade goods/Elemental", even with the new profession priority set to "Ignore".

On the screenshot, the top right category ("Joaillerie") is set to "Trade goods/Jewelcrafting" + "Profession/Jewelcrafting", and the bottom ("Éléments") is set to "Trade goods/Elemental".

![image](https://user-images.githubusercontent.com/36408045/69911692-69cff700-141f-11ea-8aca-fbf70bc9dd88.png)

**Comment by arkayenro** [comment]
will be fixed next release
