### ISSUE TITLE
Error when achieving a level

### ISSUE THREAD

**Issue by wow-player-dalaran** [arkayenro/arkinventory#1250]
This happens on all my characters when they achieve a level.

Message: [ADDON_ACTION_BLOCKED] AddOn 'ArkInventory' tried to call the protected function 'MainMenuBar:ClearAllPoints()'.
Time: Mon Dec  9 11:15:48 2019
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'ArkInventory' tried to call the protected function 'MainMenuBar:ClearAllPoints()'.
Interface\FrameXML\MainMenuBar.lua:122: in function <Interface\FrameXML\MainMenuBar.lua:65>

Locals: <none>

**Comment by arkayenro** [comment]
arkinventory doesnt touch the mainmenubar so you have another mod installed that has tainted one of the shared libraries.

see https://github.com/arkayenro/arkinventory/wiki/Taint-and-ADDON_ACTION_BLOCKED

you can disable arkinventory just before you level up and one of the other mods will be blamed.  it could be that mod or it could be one of the others.  best bet is to follow those taint instructions just before a level up to work out which one it is.
