### ISSUE TITLE
Unknown Blizzard Bag id -- 2

### ISSUE THREAD

**Issue by rbpaiett** [arkayenro/arkinventory#1251]
I've been getting strange errors since the update for battlegrounds.  Among them is just after looting something, I get in chat the error Unknown Blizzard Bag id -- 2.

bugsack spits out:

Date: 2019-12-10 15:02:55
ID: 1
Error occured in: Global
Count: 1
Message: ...s\ArkInventoryClassic\ArkInventoryClassicStorage.lua line 394:
   table index is nil
Debug:
   ...s\ArkInventoryClassic\ArkInventoryClassicStorage.lua:394:
      ...s\ArkInventoryClassic\ArkInventoryClassicStorage.lua:383
   [C]: ?
   ...ryClassic\Externals\Ace3\AceBucket\AceBucket-3.0.lua:73:
      ...ryClassic\Externals\Ace3\AceBucket\AceBucket-3.0.lua:71
   ...ryClassic\Externals\Ace3\AceBucket\AceBucket-3.0.lua:87: func()
   ...toryClassic\Externals\Ace3\AceTimer\AceTimer-3.0.lua:57:
      ...toryClassic\Externals\Ace3\AceTimer\AceTimer-3.0.lua:50
Locals:
None

I have no idea what's happening, sry.

**Comment by arkayenro** [comment]
you have ArkInventoryClassic installed, you need to delete it and install just ArkInventory

**Comment by rbpaiett** [comment]
Yea, I noticed that, tx.  Guess I have to do my settings all over but I can deal.
