### ISSUE TITLE
Classic issues since patch today

### ISSUE THREAD

**Issue by lrdcollins** [arkayenro/arkinventory#1252]
Getting an error for the backpack only -- unknown blizzared bag --2.  Any items in any other bags work. Anything getting moved into the backpack or out causes it to freeze up temporarily

**Comment by arkayenro** [comment]
sounds like #1251 

make sure you have ArkInventory installed and not ArkInventoryClassic

**Comment by lrdcollins** [comment]
i have arkinventory in twitch but I bet both are installed in the game ill take a look thx

**Comment by kkatee** [comment]
I'm running the latest classic release 3.09.03 and im definitely having these errors.
