### ISSUE TITLE
Bug: Filter not working correctly

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1253]
Hey Guys,

When you filter, it's not doing partial matches and it's only looking at the first few letters. It used to, if I recall correctly, do partial matches. Here's an example of the issue:

Screen 1 - note I have a few "of the Eagle" items...

![WoWScrnShot_121019_210510](https://user-images.githubusercontent.com/55365231/70634745-61827380-1bf8-11ea-8d66-3d0c8666d677.jpg)

Screen 2 - with filter applied, not showing any "of the Eagle" items...

![WoWScrnShot_121019_210516](https://user-images.githubusercontent.com/55365231/70634781-74954380-1bf8-11ea-8c83-a5469c3111cc.jpg)

**Comment by Gogo1951** [comment]
Works in the latest, thanks!

**Comment by arkayenro** [comment]
it shouldnt be fixed.  i was looking at a way to make it work but hadnt got very far.

the reason its not finding them is because the search data is based off the base item (same as item counts) so the suffix isnt in the name to add it into the text that would be searched

**Comment by arkayenro** [comment]
should actually be fixed - its two config options - in the next release

**Comment by Gogo1951** [comment]
It was weird, it worked on "Armor Kit" when I searched for "kit" but it didn't work on "... of the Owl" when I searched for "Owl" -- thanks for fixing this! (=

**Comment by arkayenro** [comment]
yeah, its not the space in the name, armor kit is the entire base item name but of the owl, of the monkey, etc are suffixes that get added onto the end by suffix ids and bonus ids and as i was only checking the base item those were never seen so you couldnt search on them

**Comment by Gogo1951** [comment]
Hey @arkayenro,

Is this still in an upcoming release?

**Comment by arkayenro** [comment]
yes, its currently in one of the alpha versions that are available, like [r886-alpha](https://www.curseforge.com/wow/addons/ark-inventory/files/2848797)

**Comment by arkayenro** [comment]
or in 3.09.09

**Comment by Gogo1951** [comment]
Not seeing this working properly in Classic WoW, even with alpha build linked.

**Comment by arkayenro** [comment]
it will only use the item suffix in search if youve ticked that option in the config

**Comment by Gogo1951** [comment]
Cool, works! But why not on by default? (=

**Comment by arkayenro** [comment]
because most people wont care about it
