### ISSUE TITLE
Keyring not working in classic

### ISSUE THREAD

**Issue by kekwin** [arkayenro/arkinventory#1255]
In wow classic when opening the keyring via the keybind, no keys are shown, instead an empty window with "ERR" is presented instead.

I included an image of the window below.
![image](https://user-images.githubusercontent.com/1212975/70847649-f4284a00-1e66-11ea-9175-f03f0fff1b62.png)

**Comment by arkayenro** [comment]
not 100% sure but if you have no keys then you dont get a keyring, although it should show at least four slots

**Comment by tronics-glitch** [comment]
Can confirm keyring is not working, though the issue appears different for me.
I have 7 keys in my keyring and a total of 12 slots currently (as confirmed by disabling ArkInventory and using blizzard UI).
However, this is what I see when I open the ArkInventory keyring via keybind:

![image](https://user-images.githubusercontent.com/58891415/70854358-72e1af00-1e88-11ea-9cb2-f22aab5d8fdd.png)

**Comment by arkayenro** [comment]
@tronics-glitch could you try this version https://www.curseforge.com/wow/addons/ark-inventory/files/2842831 and let me know if that works properly

**Comment by tronics-glitch** [comment]
@arkayenro it works, thanks!

![image](https://user-images.githubusercontent.com/58891415/70857521-0681a280-1ebe-11ea-9c2d-bf34cdd87942.png)

**Comment by arkayenro** [comment]
fixed in 3.09.09
