### ISSUE TITLE
Restack behavior

### ISSUE THREAD

**Issue by Kirbdawg** [arkayenro/arkinventory#1256]
After a wild goose chase trying to find out why my pet bandages were disappearing, I discovered that when I restack my bank, it actually removes items from my bags to complete stacks in my bank.  I'm using Arkinventory's restack.

This is not a show stopper.  Just wanted to make you aware of it.

**Comment by arkayenro** [comment]
its meant to do that

open your bags
right click on the restack icon
click on options
click on top up (so its not ticked)

should work how you want now and not move items into the bank to top up partial stacks there

**Comment by Kirbdawg** [comment]
Oh, lol.   I noticed you changed the icon, but never noticed it had a right-click menu.  Hidden features!

Yeah, not crazy about that one.  But, i see where your heading.  There's an addon called Reagent Restocker.  It's not working anymore, but it's still on Curse.  You should take a look at it.  When it comes to "topping off", it was the best.  You could configure any item to go to bank or bag in any quantity you needed.  lol, I pray to the addon gods that they will make it live again.  It'd be nice to have that functionality in AI.   

Thank you for all you do.       "Fill Priority:  Profession Bags" looks interesting!
