### ISSUE TITLE
Can't click on items in bag

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1258]
Since the latest patch of WoW, every so often I can't click on items in my inventory. Not sure if that's related. Logging out doesn't fix it, but signing out and signing back in again does.

It could be a compatibility issue between them. I got to drink, and I can't click on stuff in my bag. Action bars work fine. Running ArkInventory, ElvUI, and Questie. What can I provide to help track down this issue?

**Comment by arkayenro** [comment]
disable everything except arkinventory.  if you cant get the issue to happen then its a conflict with on of the other mods and you'll have to enable them one at a time (or in batches) to see when it comes back

**Comment by Gogo1951** [comment]
I haven't found the root cause. Disabled Elv... no issue. Disabled Ark... no issue. Put them together... issue.

**Comment by arkayenro** [comment]
you mean you fount it?  if disabling elv ui stops the issue and enabling it starts it again then theres a conflict in elv ui.  does it have any bag/item options you can disable?
