### ISSUE TITLE
Unknown blizzard bag id - -2

### ISSUE THREAD

**Issue by Lith1959** [arkayenro/arkinventory#1259]
With all addons disabled, when I buff Rockbiter Weapon I receive the following error every time:

Date: 2019-12-18 16:19:01
ID: 1
Error occured in: Global
Count: 1
Message: ...s\ArkInventoryClassic\ArkInventoryClassicStorage.lua line 394:
   table index is nil
Debug:
   ...s\ArkInventoryClassic\ArkInventoryClassicStorage.lua:394:
      ...s\ArkInventoryClassic\ArkInventoryClassicStorage.lua:383
   [C]: ?
   ...ryClassic\Externals\Ace3\AceBucket\AceBucket-3.0.lua:73:
      ...ryClassic\Externals\Ace3\AceBucket\AceBucket-3.0.lua:71
   ...ryClassic\Externals\Ace3\AceBucket\AceBucket-3.0.lua:87: func()
   ...toryClassic\Externals\Ace3\AceTimer\AceTimer-3.0.lua:57:
      ...toryClassic\Externals\Ace3\AceTimer\AceTimer-3.0.lua:50
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ArkInventoryClassic, v10004
  ArkInventoryClassicRules, v10000
  ArkInventoryClassicRulesExample, v10000
  ArkInventoryClassicSearch, v10000
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=e3)

b

**Comment by arkayenro** [comment]
you have ArkInventoryClassic installed, please delete it and install ArkInventory instead

**Comment by Lith1959** [comment]
Thank you
