### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by skomarz** [arkayenro/arkinventory#1260]
Essentially every single crafted item/AV item, honestly it's basically every item that goes into my inventory at this point I get 'ERROR> unknown blizzard bag id - -2' 

I've disabled all of my addons and this problem still happens. It started happening after the latest Blizzard patch. The items don't appear in my inventory until I do a /reload. 

//

After reloading and on login to the game I get the following error sequence:
English (US) translations - attempt 1 of 5.  
English (US) translations - attempt 2 of 5.  
English (US) translations - attempt 3 of 5.  
English (US) translations - attempt 4 of 5.  
English (US) translations - attempt 5 of 5.  
English (US) translations - attempt 6 of 5.  
English (US) translations - attempt 7 of 5. 
Failsafe kicked in - aborting Arkinventory translations due to an error of some sort.

**Comment by arkayenro** [comment]
uninstall arkinventoryclassic and install arkinventory

**Comment by skomarz** [comment]
Am I going to lose my configuration if I do that? I've definitely put a stupid amount of time into the config :\ 

Also, I'm currently using ArkInventory-3.09.08 - Classic isn't in the name of addon.

**Comment by arkayenro** [comment]
3.09.08 should be fine.  could you check you dont have both installed?  you may have to check the actual addons folder, it might not show up in twitch

**Comment by skomarz** [comment]
So I ended up just purging all of my configs/settings; deleted the folder from addons and reinstalled. 

This has resolved all of my issues so far- I'm guessing there was an issue with the configuration(s) I had made while using the 'classic' version of the addon as they carried over to v3.x.x 

At any rate, ty for your help! I'll close/resolve this.
