### ISSUE TITLE
Items in bags randomly not being where they should (Classic)

### ISSUE THREAD

**Issue by hotluck** [arkayenro/arkinventory#1261]
It has taken a couple of days to get some example screenshots (as it has been working more often than not for once). 

My bags are set to sort on Window Open, and as I stated in Curse (or Twitch as it now is), it is random as to when or how the items will sort into their correct groups.

The first example shows some items not sorted -

![WoWScrnShot_122219_112316](https://user-images.githubusercontent.com/11139297/71355285-75be5d00-2576-11ea-8159-82f30d6ccc29.jpg)

When I then click on the setup button, they are suddenly in their correct groups -

![WoWScrnShot_122219_112338](https://user-images.githubusercontent.com/11139297/71355303-84a50f80-2576-11ea-93d9-704e33c8cdf2.jpg)

On another character, again, some items are not in their correct groups -

![WoWScrnShot_122319_111130](https://user-images.githubusercontent.com/11139297/71355313-8e2e7780-2576-11ea-8efd-99883e1579d2.jpg)

When I click on the setup button, this time there is no change -

![WoWScrnShot_122319_111140](https://user-images.githubusercontent.com/11139297/71355321-95ee1c00-2576-11ea-9fdb-89b29b298206.jpg)

As you can see looking at the category of this item, it is equippable items -

![WoWScrnShot_122319_111200](https://user-images.githubusercontent.com/11139297/71355342-ae5e3680-2576-11ea-8208-84c858d2d456.jpg)

And this is the group that holds that category -

![WoWScrnShot_122319_111249](https://user-images.githubusercontent.com/11139297/71355360-bcac5280-2576-11ea-8d6e-9e8b3fad9fb6.jpg)

This time when I click on the setup button to get out of setup, it is finally showing in the correct group -

![WoWScrnShot_122319_111317](https://user-images.githubusercontent.com/11139297/71355391-d6e63080-2576-11ea-8b33-c7bcd873ef81.jpg)

As I said, this is random as to when items appear in the correct groups. Sometimes it will be correct when I select a vendor, sometimes the bank, sometimes the mail etc. There is no pattern to this at all.

**Comment by arkayenro** [comment]
it looks like when they are in the wrong spot they always end up in the general bar?

is the default category assigned to that bar?

next time it happens go into edit mode and click on one of the items in the wrong spot and check its assignment

could you check the bag settings.  config > settings > design > design being used > items > style > new items - is enabled ticked or not?

**Comment by hotluck** [comment]
It is ticked. Any items that are not in their correct group are always showing in the general bar, yes. The screenshots I put above show you an example assignment of incorrect item and the group that it should  in.
P.S. There are no categories assigned to the general group.

**Comment by arkayenro** [comment]
could you untick it - its why your items are ending up in the "wrong" bar.

when that option is ticked new items end up in the System > New Items category for X number of minutes, once that time has elapsed they return to their normal category.  its why nothing you do puts them into the correct bar but eventually they do end up in the correct bar (after it passes the timer value)

they end up on the general bar because thats where you have assigned the default category.  i doubt you've assigned the New Items category anywhere so its getting the default bar

**Comment by hotluck** [comment]
This has nothing to do with new items. It is doing it for existing items too. For example, yesterday I opened my chars bags to check I had everything I needed and everything was where it should be. I closed it down and then realised I hadn't checked for something so I opened my bag again and everything was in the general bar!

**Comment by arkayenro** [comment]
humour me. turn it off and try it for a while.

**Comment by hotluck** [comment]
Before I do that, you seem convinced it has something to do with new items defaulting to the general bar (because of this flag), so if that is the case, why has one of the new items I had just created in this screenshot gone into a completely random group (not even the correct group I might add) when the only 2 went into the general bar (1st is the right bracers, 2nd is in the random group, and 3rd is in the middle of the bottom line)?-

![WoWScrnShot_122919_184530](https://user-images.githubusercontent.com/11139297/71562976-4630b880-2a80-11ea-93f1-a5f7c667324a.jpg)

**Comment by arkayenro** [comment]
look, all i know is this is only happening to you.  i've never been able to duplicate it.  the only times things go out of whack with categories are when the new items option is enabled.

from your screenshot you havent refreshed the window so it hasnt been sorted yet

**Comment by hotluck** [comment]
Okay, next time I go in I will turn off that flag and see what happens. If it works then we know the bug is coming from that flag.

**Comment by jasoncurnow** [comment]
I had this problem too - All trade goods ended up in the Engineering slot.  It turned everything into a mess and it seems to have happened randomly.  

Somehow Engineering had become the priority profession.  Once I set that back to the default (Ignore) everything went back to where it should be - Settings / General / Professions, choose Ignore.

**Comment by hotluck** [comment]
I have switched off the New Items flag and everything seems to be a lot better, so the problem is to do with that flag.
