### ISSUE TITLE
ERROR> unknown blizzard bag id - -2

### ISSUE THREAD

**Issue by Scooba72** [arkayenro/arkinventory#1262]
Latest version 3.09.08 with all other addons disabled i get this:   ERROR> unknown blizzard bag id - -2    

The only time the error goes away is when i disable the ArkInventoryClassic File.

Date: 2019-12-24 22:35:44
ID: 1
Error occured in: Global
Count: 1
Message: ...s\ArkInventoryClassic\ArkInventoryClassicStorage.lua line 394:
   table index is nil
Debug:
   ...s\ArkInventoryClassic\ArkInventoryClassicStorage.lua:394:
      ...s\ArkInventoryClassic\ArkInventoryClassicStorage.lua:383
   [C]: ?
   ...ryClassic\Externals\Ace3\AceBucket\AceBucket-3.0.lua:73:
      ...ryClassic\Externals\Ace3\AceBucket\AceBucket-3.0.lua:71
   ...ryClassic\Externals\Ace3\AceBucket\AceBucket-3.0.lua:87: func()
   ...toryClassic\Externals\Ace3\AceTimer\AceTimer-3.0.lua:57:
      ...toryClassic\Externals\Ace3\AceTimer\AceTimer-3.0.lua:50
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ArkInventoryClassic, v10004
  ArkInventoryClassicRules, v10000
  ArkInventoryClassicRulesExample, v10000
  ArkInventoryClassicSearch, v10000
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=e3)

**Comment by arkayenro** [comment]
you have ArkInventoryClassic installed, you need to uninstall it and install ArkInventory instead

**Comment by arkayenro** [comment]
same as #1259

**Comment by Scooba72** [comment]
FIXED =)   
TY for my fav bag addon and the quick response.
