### ISSUE TITLE
Bank Bags Also Open

### ISSUE THREAD

**Issue by syd146** [arkayenro/arkinventory#1263]
When I open my bank the default blizzard bags also open and cannot be closed except for reloading the UI or selecting the system button. The ArkInvetory bags close if you click the X on the default bags, but they won't close.

There seems to be a conflict with CTMod (both addons function correctly when not used together). Through disabling various addons, this issue only appears once CT_Core is enabled.

**Comment by arkayenro** [comment]
have you disabled all the bank and bag handling options in ct_core?

**Comment by syd146** [comment]
I just checked (honestly didn't know CT Core had options) and disabled all open/close bag options and its working great now.

Thanks.
