### ISSUE TITLE
TSM Group no longer working

### ISSUE THREAD

**Issue by pquerner** [arkayenro/arkinventory#1264]
My rule:

```
tsmgroup( "60 Classic Herbs" )
```

no longer works and doesnt assign the items to a specific slot in my inventory.
Versions:
3.09.09 Arkinventory
TSM 4.8.24

Also tried it with only named "Herbs" (in TSM and Ark)

It used to work, but I couldnt tell you which version broke it.

**Comment by arkayenro** [comment]
error message?

it was broken when TSM changed their API - i added a fix in 3.0.7 so unless theyve changed their API again it should work

**Comment by pquerner** [comment]
I dont get any error messages.

**Comment by arkayenro** [comment]
/reim using tsm 4.8.24 and its working fine with a group named "60 Classic Herbs" and a rule with tsmgroup( "60 classic herbs" )

if you added items to the TSM group youll need to /reload for arkinventory to pick them up

**Comment by pquerner** [comment]
There are items in the group, yes. And its existed well before I added the rule for Ark.

![image](https://user-images.githubusercontent.com/4364044/71494930-2b293300-284b-11ea-9794-cc8d6d397275.png)

![image](https://user-images.githubusercontent.com/4364044/71494935-39774f00-284b-11ea-8214-3e76a25386ca.png)

![image](https://user-images.githubusercontent.com/4364044/71494941-46943e00-284b-11ea-8b13-4f15fa84cd8b.png)

**Comment by pquerner** [comment]
![image](https://user-images.githubusercontent.com/4364044/71494997-ad195c00-284b-11ea-8187-e61a9a02d207.png)

Should be in Group 11 but isnt.

**Comment by arkayenro** [comment]
while the rule is assigned to bar 11 its also disabled so it wont do anything

see the last image in the 2nd post up - https://github.com/arkayenro/arkinventory/issues/1264#issuecomment-569157594

click on the status: disabled entry to toggle it to enabled and then it should work the way you want

**Comment by pquerner** [comment]
Wow.. that makes sense. ;) Thanks for the quick help.
