### ISSUE TITLE
Pick inventories

### ISSUE THREAD

**Issue by johnnydement** [arkayenro/arkinventory#1266]
I love arkinventory in my bank and inventory, but would love guild bank to be vanilla.

Or, would like to have different rules for each of the tree... not sure if possible...

**Comment by arkayenro** [comment]
did they add the guild bank to classic?  it was never part of it so i've left it disabled.

you can have different rules apply to each location by setting the blueprint (categoryset) options for each location differently

**Comment by johnnydement** [comment]
No, I meaned in retail sorry, where's the option in config? coudln't find (although I remember having it "standalone" before 

I'll check category sets... thanks!

**Comment by arkayenro** [comment]
config > settings > profiles > the profile you are using > guild bank > override (untick)
