### ISSUE TITLE
Getting LUA error

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1268]
Date: 2020-01-07 11:52:07
ID: 4
Error occured in: AddOn: ArkInventory
Count: 1
Message: Note: AddOn ArkInventory attempted to call a protected function (UNKNOWN()) during combat lockdown.
Debug:
   [C]: ?
   [C]: ?
   WIM\Modules\WhisperEngine.lua:746: SendChatMessage()
   QuestAnnounce\QuestAnnounce.lua:121: SendMsg()
   QuestAnnounce\QuestAnnounce.lua:72: ?()
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:119:
      ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:119
   [C]: ?
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:29:
      ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:25
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:64: Fire()
   ...rkInventory\Externals\Ace3\AceEvent\AceEvent-3.0.lua:120:
      ...rkInventory\Externals\Ace3\AceEvent\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3-3-g58f2fa4
  ArkInventory, v30910
  ArkInventoryRules, v20000
  ArkInventoryRulesExample, v20000
  ArkInventorySearch, v20000
  AtlasLootClassic, vv1.4.4
  AtlasLootClassicData, vv1.4.4
  AtlasLootClassicDungeonsAndRaids, vv1.4.4
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AutoDismount, v1.0.3
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v2.9
  ClassicCastbars, vv1.2.2
  ClassicCastbarsOptions, v
  DBMCore, v1.13.28-1-g0f19a50
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  ElvUI, v1.19
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  FreeRefills, v116
  GTFO, v4.51
  InFlight, v1.13.003
  InFlightLoad, v1.13.003
  Informant, v8.2.6374 (SwimmingSeadragon)
  InstanceResetAnnouncer, v1.0
  ItemTooltipProfessionIcons, v1.1.5
  LeatrixMaps, v1.13.43.alpha.1
  LeatrixPlus, v1.13.43
  Memoria, v8.2-2
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  Outfitter, v5.22.1.classic
  Pawn, v2.3.15
  QuestAnnounce, v8.0.2.1
  Questie, v5.4.1
  RealMobHealth, v2.17
  RecipeRadarClassic, v1.0.0.23
  RepByZone, v1.0.5
  ReturnBuffTracker, v0.6.3
  RollTrackerClassic, v2.11
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SimpleInterruptAnnounce, v1.0.0
  SimpleTauntAnnounce, v1.0.0-beta.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpeedyAutoLoot, v2.1.0-Alpha191024
  Spy, v1.0.20
  Stubby, v8.2.6376 (SwimmingSeadragon)
  Talented, vv191206
  TalentedData, v
  TankWarningsClassic, v1.1.2
  TFTB, v1.10
  ThreatClassic2, v2.07
  TidyPlatesThreatPlates, v1.2.8
  TownsfolkTracker, v1.0.7
  TrackingEye, v1.1.1
  TradeSkillMaster, vv4.9.5
  TurnIn, v2.1
  VendorPrice, v1.3.0
  WeakAuras, v2.15.5-85-g7e8c8a8
  WIM, v3.8.4-1-g541f7a1
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=8d3)

**Comment by arkayenro** [comment]
thats an issue with quest announce, its just using the ace libraries from arkinventory
