### ISSUE TITLE
REQUEST: Special sorting option for Cards

### ISSUE THREAD

**Issue by Arturis** [arkayenro/arkinventory#1269]
First off, I love ArkInv, its one of the few mods I simply cant play without. That being said, I found a "fringe case" scenario where I cant get the custom sorting system to do what I want, and so I figured I would suggest it here as a possible enhancement.

Currently, I have a Rule that simply stacks all of the various Darkmoon Fair cards into one custom group - name("Ace of","Two of","Three of","Four of","Five of","Six of","Seven of","Eight of") - It's rough, but it gets the job done. However, I was hoping to be able to sort the cards into decks so I can easily tell my progress in collecting each - Ace through Eight of Swords, Ace through Eight of Warlords, etc etc - and that currently isn't possible. The closest I've been able to get is sorting by Vendor price, and even that is far from what I'm looking for.

What would be needed is a way to sort by the Nth word in a particular string (in this case, the third word of [name]), or an addition of a "deck sort" option to the sorting choices. If either of these could be added, my minor OCD would be eternally grateful. ^_^ 

This isn't vastly important or game breaking, but I figured it was worth putting out there.

Thanks again for all your hard work.

**Comment by arkayenro** [comment]
im at work so this isnt tested but i think it will do what you want

crate a rule for pt( "Misc.QuestMats.Darkmoon Faire.Deck" )
that should pick up all the cards (so long at perodic table is up to date)

put that on a bar, and enable it -  dont add anything else to that bar
change the sorting for that bar to name reversed (not sure if thats a default or if you'll need to create it)

**Comment by Arturis** [comment]
I attempted adding that as an additional rule ("Card Test" instead of "Card") and toggled the bar over to using it. Unfortunately, it didn't work and that group is now blank, with the items all returning to the "misc" group. I'm not sure if its a typo or what, but I will set it back to how it was for now. That at least gets all the cards in one place, even if they aren't sorted how I want.

**Comment by arkayenro** [comment]
custom categories override rules, so if youve used one youd have to remove them first - but it doesnt really matter how you collect them, just so long as they all end up on that bar.  then you can change the sorting used just for that bar

**Comment by Arturis** [comment]
Well, getting the items into their own bar isn't the issue, its the sort order that is the thing that I'm hoping to address.

As of right now, sorting alphabetically is only by the start of the string. So with a collection of, lets say, 6 cards (Ace through 3 of both Swords and Warlords) sorting alphabetically gets me:

[Ace of Swords]
[Ace of Warlords]
[Three of Swords]
[Three of Warlords]
[Two of Swords]
[Two of Warlords]

What I'm looking for the more natural/easier to keep track of sorting order of a deck of cards:

[Ace of Swords]
[Two of Swords]
[Three of Swords]
[Ace of Warlords]
[Two of Warlords]
[Three of Warlords]

Which I don't believe is possible with any of the current sorting options, either built in or custom.

**Comment by arkayenro** [comment]
crate a new sort method, enable at least name, there should be a tick box there to reverse the name

so instead of "Ace of Swords" it sees "Swords of Ace"

at least i think thats how i coded the reverse name

**Comment by Arturis** [comment]
That is much closer! Now they at least are grouped together by Deck type. They still arent going to sort in the proper order due to the fact that the alphabetic order of spelled out numbers is not the same as the numeric order.

Numeric: Two, Five, Seven, Eight
Alphabetic: Eight, Five, Seven, Two

But as I said, this is at least a big step in the right direction! At least this gets similar icons grouped together.

![CardCluster](https://user-images.githubusercontent.com/6211355/71976367-befbe700-31db-11ea-9633-c80e8ee97f46.png)
