### ISSUE TITLE
TSM rules do not work for battle pets

### ISSUE THREAD

**Issue by burnonator** [arkayenro/arkinventory#1270]
No matter what I did, I couldn't get the rules to work for battlepets, so I dug in to the code and found the problem. They're literally not checked. So, its an easy fix, as documented below (probably need to fix the other 3 functions as well). I'd really appreciate this change being made official.

ArkInventoryRules.lua -- line 1872 in function ArkInventoryRules.System.boolean_tsm4(...)

`if not ArkInventoryRules.Object.h or (ArkInventoryRules.Object.class ~= "item" and ArkInventoryRules.Object.class ~= "battlepet") then`

**Comment by arkayenro** [comment]
will be in the next release

```
	if not ArkInventoryRules.Object.h or not ( ArkInventoryRules.Object.class == "item" or ArkInventoryRules.Object.class == "battlepet" or ArkInventoryRules.Object.class == "keystone" ) then
		return false
	end
```

**Comment by arkayenro** [comment]
added to 3.09.11
