### ISSUE TITLE
New bag items added are invisible

### ISSUE THREAD

**Issue by butter-nut** [arkayenro/arkinventory#1271]
After logging in to 8.3, new inventory items do not appear in bags. If I go into edit mode, an inventory square will blink as if it has the item in it. I can right click or left click on the square and use the item, however there are no tooltips or anything to show what the item is. I can see bag contents from before 8.3 with no problem, but new items added from quest turn ins or vendor purchases are invisible. From what I can tell the issue is caused by an addon library from C:\Program Files (x86)\World of Warcraft\_retail_\Interface\Addons\ArkInventory\Externals\Ace3\AceAddon. I also noticed from https://wow.gamepedia.com/Patch_8.3.0/API_changes that a new event called OWNED_AUCTION_EXPIRED was added to 8.3. If I want to play today it appears I'm going to have to disable Arkinventory. It also appears to affect Angry Assignments and Altoholic I assume because they too use the Ace 3 library. But since bag interaction is so critical to the game Arkinventory is my priority. I realize this appears to be a library dependency you might not be able to control, but since this may be a critical issue for your addon, is there anything you can do to help?

ERROR:

1x ...rkInventory\Externals\Ace3\AceEvent\AceEvent-3.0-4.lua:33: Attempt to register unknown event "OWNED_AUCTION_EXPIRED"
[string "=[C]"]: in function `RegisterEvent'
[string "@ArkInventory\Externals\Ace3\AceEvent\AceEvent-3.0-4.lua"]:33: in function `OnUsed'
[string "@AppearanceSets_HideHelm\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:168: in function `RegisterEvent'
[string "@ArkInventory\ArkInventory-30907.lua"]:2996: in function <ArkInventory\ArkInventory.lua:2908>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@AppearanceSets_HideHelm\Libs\AceAddon-3.0\AceAddon-3.0-12.lua"]:558: in function `EnableAddon'
[string "@AppearanceSets_HideHelm\Libs\AceAddon-3.0\AceAddon-3.0-12.lua"]:651: in function <...anceSets_HideHelm\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:457: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:580: in function `TimeManager_LoadUI'
[string "@FrameXML\UIParent.lua"]:1257: in function <FrameXML\UIParent.lua:1155>

**Comment by arkayenro** [comment]
try the last alpha version, see if it works in that.

**Comment by butter-nut** [comment]
1. ALPHA VERSION ISSUE: Using the Twitch client I installed r894-alpha-nolib release 1/13/20. Then I re-enabled Ark Inventory before logging in my character but the game didn't seem to recognized the addon at all. After a bit I decided to restore my game to where it was prior to any addon updates and the patch day game update. When I went to install the latest alpha the 1/13/20 version was missing from the twitch list. The latest alpha in twitch is now r886-alpha-nolib from 12/24/19. 
2. SEEMS FIXED: After re-adding the game day patch to my restored backup and updating all addons with a Twitch update I decided to take the latest update of 3.09.10.zip Jan 5, 2020 for 8.25 from https://www.curseforge.com/wow/addons/ark-inventory/files. This does not appear in twitch by the way. The twitch install redirect was a fail, so I downloaded manually, extracted and manually replaced matching folders in C:\Program Files (x86)\World of Warcraft\_retail_\Interface\Addons. After I opened the game my bags appeared normal and I was able to buy from a vendor and see my item in bag. I could resort bag and the item went into proper category. Then interacted with item to resell back to vendor successfully. The bug tracker shows no errors in game at all from any addons. Soooo, all seems to work at the moment, however I'll continue to watch for any additional updates. Thanks for responding so fast so I can now go get my new legendary cloak!

**Comment by nalis44** [comment]
I had the same problem and going to try the fix above

**Comment by nalis44** [comment]
fix above worked well for me too

**Comment by mcloude52** [comment]
dont understand how he fixed it i tried but it didnt work any help would appreciated thanks

**Comment by arkayenro** [comment]
they manually downloaded the latest alpha version

ion twitch you can set arkinventory to download alpha versions and try to download it from there (but they mentioned there were issues and it might not work)

alternatively you can download it manually download [r894-alpha](https://www.curseforge.com/wow/addons/ark-inventory/files/2859960)

**Comment by butter-nut** [comment]
I just updated to the  r894-alpha 1/13/20 version which now shows up on Twitch. So far everything is still working.

**Comment by NHDriver4** [comment]
Also confirming the 894-alpha version resolved the issue.

**Comment by deuxbebes** [comment]
I also had the problem with invisible items in my backpack; I updated to the alpha and now I have the 5 individual backpacks as if I never had an addon.  Will there be a fix?

**Comment by arkayenro** [comment]
@deuxbebes did you upgrade while the game was running?

**Comment by deuxbebes** [comment]
No, but I did end up deleting and reinstalling the addon and this morning it is back-whew!  Just a day without the addon made me appreciate it all that much more.  Thanks!
