### ISSUE TITLE
Right click sub menu commands not functional.

### ISSUE THREAD

**Issue by Mishobu** [arkayenro/arkinventory#1273]
Before anything, thanks for the addon it is great and I love it, but I just recently found an annoying problem: 

When I turn on edit mode and try to assign a category to a segment or to an item the "click" is ignored, it just exits the pop up menu and does nothing, you can create categories in config mode just fine, but you cant assign a category to an item or segment of the bags, enabling and disabling it is also not possible. The only thing "doable" in edit mode is move objects to bag segments but nothing more. 

Edit: I also tried to use the reagent bank "deposit all reagents" and wont work at all. So it seems that any command from the right click sub menus are not functional.

(Tried deleting the addon and using different versions of it but still has the issue, what I have not done is deleting the savedvariables files, but that would mean deleting all my config, which i dont want to.)

Thanks.

**Comment by arkayenro** [comment]
fixed in 3.09.12

**Comment by Mishobu** [comment]
Thank you very much. :D
