### ISSUE TITLE
Menu stacking on top of it self

### ISSUE THREAD

**Issue by NudeSocks** [arkayenro/arkinventory#1274]
![arkinventory](https://user-images.githubusercontent.com/43509247/72539687-b2b40180-384d-11ea-841f-da94d2418aec.jpg)

Hope this helps some on what is happening to me. the menu is staying in side Arkinventory frame making hard to use .. unless it can flip from opening on right side to opening on left. only resolves some of the time.

**Comment by arkayenro** [comment]
if you pick something more to the left side of your screen does it happen there?  or is it only on the far right side?

it almost looks like its got your screen size wrong and it thinks thats the edge

**Comment by arkayenro** [comment]
could you type this in the chat window and let me know what the number is ( 3 decimal places is fine)
`/dump GetScreenWidth() / GetScreenHeight()`

whats causing the action bars to be outside the game window?  is that a window thing or just a black background?

**Comment by NudeSocks** [comment]
only far right when menu not fitting in

**Comment by NudeSocks** [comment]
oh i have addon that made the black-bar and moves game screen

/dump GetScreenWidth() / GetScreenHeight()
[1]=3.5165938805548

**Comment by NudeSocks** [comment]
the addon is sunart

**Comment by arkayenro** [comment]
ok, i think its the dual monitor code that seems to screw it up instead of fix some issue there may have been with dual monitors a long time ago.

should be fixed in the next release unless theres also a viewport component to it

**Comment by arkayenro** [comment]
you can try [r898-alpha](https://www.curseforge.com/wow/addons/ark-inventory/files/2862073) to see if it fixes the problem

**Comment by NudeSocks** [comment]
that worked ... Thanks Arkayenro

**Comment by NudeSocks** [comment]
u have to love Ultra wide Monitors ... only looks like dual monitor

**Comment by arkayenro** [comment]
fixed in 3.09.13
