### ISSUE TITLE
Enhancement Request:  Full label titles in a tooltip on mouseover

### ISSUE THREAD

**Issue by rbpaiett** [arkayenro/arkinventory#1276]
I have labels enabled for groups like leatherworking, etc. and when a group is reduced to one or two slots, the label gets truncated.  I'd like it if I mouseover the truncated title, a tooltip will appear with the full title.  Not a deal breaker, just a nice feature.

Great addon, thanks!

**Comment by arkayenro** [comment]
will be in the next release.  will only create a tooltip if the name has been truncated

**Comment by arkayenro** [comment]
you could also set the bars min width if the labels not too large (say 2-4 items wide) so it always displays

**Comment by rbpaiett** [comment]
Thank you very much!  It's perfect.
