### ISSUE TITLE
Ark Inventory classic keyring?

### ISSUE THREAD

**Issue by belurien** [arkayenro/arkinventory#1277]
Keyring is active in classic now but I can't see any button yet

**Comment by arkayenro** [comment]
it should be on the location dropdown with all the others

**Comment by pquerner** [comment]
It is 
![image](https://user-images.githubusercontent.com/4364044/73129150-49ff1e80-3fdd-11ea-981a-473f1cdea214.png)

Then a new window opens up which lets you see the keys.
