### ISSUE TITLE
Rule - Issue Making one for Herbs

### ISSUE THREAD

**Issue by lissabunbun2** [arkayenro/arkinventory#1278]
I want to create a rule that is similar to the Trade Good [0501] but have it exclude soul bound items. Is there a source to help us with these rules besides examples of gems? Is there a way to see what the default rules are to help modify? Appreciate any help on this. Thanks.

**Comment by arkayenro** [comment]
the default rules are based on different item properties and periodic table sets.

non soulbound trade goods would be `type( "tradeskill" ) and not sb( )`

you can check the debug properties of an item in edit mode to work out what values to use

**Comment by lissabunbun2** [comment]
Thank you so much that debug helped tie the missing pieces! Thank you so much for your prompt help!!
