### ISSUE TITLE
Window Anchor

### ISSUE THREAD

**Issue by Thortok** [arkayenro/arkinventory#1280]
I'm able to set anchors for bars and for items but the entire window itself I'd like to set the anchor as the bottom right corner and I cannot. x.x

I remember this being a function back when I used to play WoW before. But now that I'm back to play classic, I can't figure out how and I think it might be missing.

![image](https://user-images.githubusercontent.com/14281289/73113655-0aeca280-3ee3-11ea-864b-abff5842072a.png)

This is where I'm looking. Or is it somewhere else?

**Comment by arkayenro** [comment]
its under settings > profile.  just make sure you set it in the correct profile

**Comment by a1chera** [comment]
> its under settings > profile. just make sure you set it in the correct profile

It's actually under General > Profiles > Controls  for anyone else who was confused by this comment.
