### ISSUE TITLE
Bag Contents Not Displayed

### ISSUE THREAD

**Issue by TronWoWGamer** [arkayenro/arkinventory#1281]
Getting all sorts of errors with both version 3.09.12 and 3.09.13 and this is when I am attempting to open my bags immediately after upgrading.

1 - Error ArkInventoryStorage 1831: attempt to call field ClientIsReagentBankUnlocked (a nil value)
2 - Error Arkinventory 3612: attempt to call field PT_ItemInSets (a nil value)

Both of these errors are keeping the window from displaying the contents of my bags.

Actually I am getting issues all the way back to 3.9.0 so I am going to continue to rollback until I can figure out which is the last version working for me.

Okay, so 3.08.29 seems to be the last version without errors keeping me from opening my bags.

Update:
Tried 3.09.03 and got an error with ClientIsArtifactItem (a nil value) in Arkinventory line 3591, which I assume refers to the new items I picked up that aren't being drawn.  The space blinks at me where the items are, but the icon is not visible. 

3.09.04 same error as 3.09.03
3.09.05 same error as 3.09.03
3.09.06 same error as 3.09.03
3.09.07 same error as 3.09.03
3.09.08 same error as 3.09.03

Tried 3.09.11 Alpha (r894) and it was worse. Same errors as before and also another one
call to ClientGetContainerItemQuestIngo (a nil value) in Arkinventory line 7756

So, back to 3.08.09 but I can't see items from current WoW update having to do with the new Heart of Azeroth quest line (the whole Uldum thing)
-------------------------------------------------------------------------------------------------
**Here is the error caught by swatter:** - this is actually a separate error I think

Message: ..\AddOns\ArkInventory\Locale\game.lua line 254:
   attempt to call field '?' (a nil value)
Debug:
   [string "@ArkInventory\Locale\game.lua"]:254: in main chunk
Locals:
L = <table> {
}
FormatForRegex = <function> defined @Interface\AddOns\ArkInventory\Locale\game.lua:4
FormatForCapture = <function> defined @Interface\AddOns\ArkInventory\Locale\game.lua:16
(*temporary) = "WOW_TOOLTIP_ANCIENT_MANA"
(*temporary) = nil
(*temporary) = 1155
(*temporary) = "attempt to call field '?' (a nil value)"

-------------------------------------------------------------------------------------------------

**Comment by arkayenro** [comment]
delete all the arkinventory folders from the interface folder
download it manually from curseforge
unzip it into the interface folder

theres either something corrupt in the download youre using, or something in the folders causing it.  if youre using twitch then its possibly an issue there as well.
