### ISSUE TITLE
Use "CHAT_MSG_COMBAT_FACTION_CHANGE" to detect reputation changes

### ISSUE THREAD

**Issue by semecan** [arkayenro/arkinventory#1282]
Currently the addon uses the "UPDATE_FACTION" event to detect reputation changes. To read collapsed reputation groups, the group headers have to be expanded, which causes new "UPDATE_FACTION" events. If another addon scans reputations and expands headers, this will cause ArkInventory to scan again unnecessarily. If both addons use "UPDATE_FACTION", this will even cause an infinite event loop, as both addons will trigger each other.

I checked the "CHAT_MSG_COMBAT_FACTION_CHANGE" event and it fires on all kinds of reputation changes, but not when expanding/collapsing headers in the reputation pane. Therefor it is better suited to detect reputation changes, as it is easier to use and not prone to errors as is not triggered by actions in the reputation pane.

I encountered this problem due to a bug report in my addon that scans reputation the same way ArkInventory does and caused ArkInventory to go into an infinite scan loop.

**Comment by arkayenro** [comment]
does it still fire if youve turned off rep messages for the chat window?

**Comment by semecan** [comment]
I don't use ArkInventory myself, so I don't know. 
I only installed the addon to check the cause of the lags a user described and saw they were caused by ArkInventory reacting to the "UPDATE_FACTION" event caused by my addon which was expanding the reputation headers and collapsing them again. I changed my addon to use the "CHAT_MSG_COMBAT_FACTION_CHANGED" event instead of the "UPDATE_FACTION" event, so it will only react to actual reputation changes.

**Comment by arkayenro** [comment]
i'll test/check when i get home from woirk but thats in about 9 hours.

if it does work with rep chat messages disabled then im happy to change to that event

**Comment by semecan** [comment]
Awesome! I actually didn't think about if those events are fired without reputation messages being enabled in chat, but I hope they are, because otherwise it would be kinda tricky to get two addons to behave properly alongside each other.

**Comment by arkayenro** [comment]
seems to work fine with both rep and the combat log disabled

**Comment by arkayenro** [comment]
changed in 3.09.14
