### ISSUE TITLE
Item tooltips on new AH don't show # of items you already have

### ISSUE THREAD

**Issue by jcai1** [arkayenro/arkinventory#1285]
The tooltip in this situation: https://i.imgur.com/B2yNlSE.png

Does not show the extra info about items already held, like when mousing over an item in your inventory: https://i.imgur.com/zeOOeh0.png

**Comment by arkayenro** [comment]
will be fixed in the next release.  its in the latest alpha

**Comment by arkayenro** [comment]
fixed in 3.09.14
