### ISSUE TITLE
3.09.14 Release Not Working. Only Addon Running

### ISSUE THREAD

**Issue by insaneaux** [arkayenro/arkinventory#1286]
Just updated to and even reinstalled 3.09.14 and the consolidated window pops up but nothing inside. I receive the following:

ERROR>Interface\AddOns\ArkInventory\ArkInventory.lua:3206: attempt to index field '?' (a nil value)

This persists whether or not I have any other addons loaded. I have it disabled at the moment, but pia managing inventory and I refuse to load bagnon :)

Thanks for supporting this addon it is awesome.

**Comment by arkayenro** [comment]
i think its something to do with one of your sort methods that i wasnt expecting but i can code around it i think.

see if the r911-alpha version fixes it for you

**Comment by insaneaux** [comment]
Yep, that did it. Everything works now. Thank arkayenro!
 
Question, I see you have released 912, should I stay put or update to it? And what are the nolib versions if you don’t mind me asking?

**Comment by arkayenro** [comment]
you can stay on that alpha, 912 has some config layout changes only but ill be releasing 3.9.15 today anyway to push that sort method fix to everyone

nolib is no library, its for people that want to manage the ace libraries themselves so the download will not have them in it

**Comment by arkayenro** [comment]
fixed in 3.09.15
