### ISSUE TITLE
Issues Updating from 3.09.13

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1288]
I updated yesterday to 3.09.14 when I saw the update in the Twitch client, but I noticed an issue in game -- specifically, I was able to mount using my shortcut and the Mounts LDB showed 'journal not ready' -- and when I looked at a few more things it was clear there was an issue.   I didn't have the time to post an issue ticket and/or gather more troubleshooting data, so I simply reverted back to a backup of my addons / WTF folder and everything was fine. 

I saw the 3.09.15 update today and thought 'Wow! Ark has already fixed the issues' so I went ahead and installed it.  Same issues I saw yesterday, but I have some time tonight so I thought I'd share them to help troubleshoot.

One LUA error that showed was something akin to:

Upgrades.lua:1716 attempt to index field 'active'

I'm not sure if the other issues are related but:

* Mounts LDB - Journal Not Ready
* Money LDB - No currency displayed.  Tooltip shows up when you hover over where it's supposed to show.
* Currency LDB - No Known Currencies
* Open up the backpack - sort order is all messed up.  Items are in order of ilevel but not alphabetically after that like I have it setup.

I've reverted back to 3.09.13 for now.  Hoping the issue is a 'quick' fix!

Thanks for staying on top of things Ark!

**Comment by arkayenro** [comment]
i cant tell there are issues if i dont run into them and no one tells me about them

i've fixed the upgrade code, which i believe was stopping the rest of the code from working

please try the latest r916-alpha version and let me know if it works or not

**Comment by Calesta** [comment]
It works!  Thanks so much for the quick turnaround.  Sorry I didn't report it right away.  I was busy and figured that there was surely someone else who would run into the issue(s).

**Comment by arkayenro** [comment]
fixed in 3.09.16
