### ISSUE TITLE
Bug: Stuck when collecting new Items after 3.09.14

### ISSUE THREAD

**Issue by MonkeyGoneWIld** [arkayenro/arkinventory#1290]
Whenever I collect new Item my game gets stuck for about 2 secs, It only seems to have started from version 3.09.14 and onwards.
I have tested all the versions and only reverting back to 3.09.13 or earlier seems to solve the problem.
I don't receive any errors on bugsack when it occurs but it is quiet annoying to deal with.

**Comment by MonkeyGoneWIld** [comment]
So I have tried 
- Disabling all my addons 
- Disabling arkinventory more rules
- Deleting all my rules 
- Reinstalling the Addon
- Changing to a different profile (and the Default profile)
But none of them worked.

The only thing that seems to work is deleting my saved variables file and going back to the default one but I would really prefer to use my own profile since I have spent years customizing it and it would take too long to recreate it.

You can find my lua files here: https://drive.google.com/drive/folders/1enB5ZkKh8FB09fGOKVOoyePtnP0_bPv9?usp=sharing

Steps to recreate the issue:
- Make sure profile is set to AB
- Pick up a new Item (any Item that is currently not in any bags on any characters)

The screen should stutter for a bit and occasionally get stuck for a couple of seconds. I am not sure

 what is causing the issue but I have tried everything I could think of.

I would highly prefer to not be forced to use version 3.09.13 and would highly appreciate any feedback.

**Comment by arkayenro** [comment]
try [r940-alpha](https://www.curseforge.com/wow/addons/ark-inventory/files/2888366)

**Comment by MonkeyGoneWIld** [comment]
It did solve the problem but I am unable to use the search bar anymore, it just gives me this error: 
```
1x ArkInventory\ArkInventory-30922.lua:12157: ArkInventory\ArkInventoryPT.lua:554: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@ArkInventory\ArkInventory-30922.lua"]:12157: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = "ArkInventory\ArkInventoryPT.lua:554: attempt to index field '?' (a nil `value)"
```

**Comment by arkayenro** [comment]
r941-alpha should be available in about an hour, issue should be fixed in there

**Comment by MonkeyGoneWIld** [comment]
Yep that fixed.

Thanks a lot for time and help, youe awesome!!
