### ISSUE TITLE
iLevel Display

### ISSUE THREAD

**Issue by goldenpaww** [arkayenro/arkinventory#1291]
I'm sure there's a setting that I'm missing somewhere but looked everywhere and checked Wiki and don't see it.  When I open my bag, the iLevel for Timewalking or Holiday items is displaying incorrectly, and causing the sort to be incorrect. As an example:
I have "The Horeseman's Ring". In my bag, it displays as level 136. However, when I mouseover, the tooltip reads correctly (?) as Item Level 395. I've tried disabling addons and my UI, but doesn't seem to make any difference. Thanks for any help/guidance (even "read this")

**Comment by goldenpaww** [comment]
![ArkInv-iLevel](https://user-images.githubusercontent.com/60800426/74074446-0f818280-49dc-11ea-9bfc-148d381b2d33.jpg)

**Comment by arkayenro** [comment]
i dont have any timewarped gear to test it on so im not sure

136 is the base level.  the only reason for it to stay at 136 i think would be the linklevel in the hyperlink to be 0 and not 120 (or whatever you characters level is), but while i remove it for other purposes its still in the hyperlink when i get the ilvl value so it doesnt make any sense

**Comment by goldenpaww** [comment]
Yay, a bug :)  It's not just me; my sister and a guildie confirmed they have the same issue. Let me know if there's anything I can do to help track it down.

**Comment by arkayenro** [comment]
if you have notepad++ or any text file editor open ArkInventoryStorage.lua and go down to line 4634
`osd[10] = 0`

and change it to 
`--osd[10] = 0`

see if that does anything or not

**Comment by arkayenro** [comment]
could you also enable edit mode and click on the item, go to debug, and copy out the itemstring value

**Comment by goldenpaww** [comment]
No change by commenting out the line. I've given you two dif items, one holiday (levels 136/395) and one TW (116/395)
item:143903::::::::120:66:512::1:6315:120:::
item:144096::::::::120:66:512:22:1:6314:120:::

**Comment by arkayenro** [comment]
ok, look like the API changed at some point and i need to call a different function to get the actual level

i'll update the code and post an alpha for you to test in a couple of hours

**Comment by arkayenro** [comment]
try r920-alpha

**Comment by goldenpaww** [comment]
Appears to have fixed it. Thanks very much for your responsiveness, keep up the awesome work!

**Comment by arkayenro** [comment]
fixed in 3.09.17
