### ISSUE TITLE
NoLib Version

### ISSUE THREAD

**Issue by wallyguitar** [arkayenro/arkinventory#1292]
Is there a reason why the NoLib version is available on Curse(Twitch) for download? The reason I ask, Twitch automatically installs the NoLib version by default every time I check for an updated addons. This is SUPER annoying. 
Thanks!

**Comment by arkayenro** [comment]
curse builds it by default.

twitch shouldnt do it by default (it didnt on mine)

you have to change it in the options though
press control comma
got to addons
game specific
pick wow
turn off library preference

if it wasnt on then its set at the addon level
go back to the list of addons
right click on the addon in the list
install settings
untick  install libraries seperately

if both of those are off then open a ticket with twitch to ask them why its install the nolib version when you have that disabled

**Comment by wallyguitar** [comment]
Thanks for the quick response. I have Library preferences off and also install libraries unticked. I’ll open a ticket.

Thanks again.

Sent from Mail for Windows 10
