### ISSUE TITLE
v3.09.20 (2/14/20) Non-Functional

### ISSUE THREAD

**Issue by OrnoCav** [arkayenro/arkinventory#1293]
No inventory display, stuck on "Loading..."

Date: 2020-02-15 02:38:53
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ArkInventory\ArkInventory.lua line 12157:
   ..\AddOns\ArkInventory\ArkInventory.lua line 8131:
   attempt to call global 'IsCorruptedItem' (a nil value)
Debug:
   [C]: ?
   [C]: ?
   ArkInventory\ArkInventory.lua:12157: ThreadResume()
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1

Reverting to 3.09.19 has restored functionality with no errors

**Comment by arkayenro** [comment]
is this in classic or retail?

**Comment by OrnoCav** [comment]
Classic

**Comment by arkayenro** [comment]
will be fixed in about 15 minutes

**Comment by OrnoCav** [comment]
looking forward to it, thanks for the quick attention

**Comment by arkayenro** [comment]
3.09.21-classic should be available now

**Comment by OrnoCav** [comment]
looks good at load, will keep an eye on it

**Comment by arkayenro** [comment]
thanks
