### ISSUE TITLE
outfit() rule not working in classic?

### ISSUE THREAD

**Issue by cbdejavu** [arkayenro/arkinventory#1296]
So I was trying to get a rule to work and it doesn't seem like I can get any rules to work.  I haven't played wow since WotLK but I was so happy to see that this addon was still around (it was always my first must have addon no matter what).

I'm using Arkinventory v3.09.22

the rule I was trying to get work was a basic one to determine if the gear was part of an outfit in classic.  I'm using outfitter (classic) v1.2.1, however I also tried ItemRack classic (v3.25) both versions were the latest and both versions show the item set in the tooltip.  I only ran one or the other while testing.

The rule I'm trying to get to work is a basic:

outfit()

I also tried
outfit("")

I tried another rule I found online and it doesn't seem to work either.
equip() and soulbound() and not outfit()

Am I missing something obviously like having rules disabled or something somewhere?  This is a new install of WoW and the addon was installed clean so this is the only version of arkinventory that has ever run on this system (so there shouldn't be anything i the configuration file that would be from an older version).

**Comment by arkayenro** [comment]
by default rules start out as disabled, so go into edit mode and where the rules are assigned to the bar, open that up and make sure each rule is set to enabled

it will remember its status even if you move it to another bar later but they always start out disabled

**Comment by cbdejavu** [comment]
That was it.  Thanks.  I feel like an idiot for not noticing that the assigned rules where RED lol.  Thanks for the super fast reply and thanks for making the best bag manager out there hands down.
