### ISSUE TITLE
Error on applying rules

### ISSUE THREAD

**Issue by Unrak** [arkayenro/arkinventory#1301]
Hi
Using version 3.08.22 (r818alpha)

I am trying to create a rule so that all of my relic fragments go in a group )Mantid relic, tolvir relic etc)
I create the rule:
name( "Relic" )
but when I try and apply it to a bag i get an error:

Date: 2020-04-18 22:55:02
ID: 11
Error occured in: Global
Count: 1
Message: ...e\AddOns\ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua line 796:
   Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: ArkDewdrop30104Button29:SetPoint.
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: SetPoint()
   [string "@ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua"]:796:
      ...e\AddOns\ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua:576
   [string "@ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua"]:3053: AddLine()
   [string "@ArkInventory\ArkInventoryMenu.lua"]:940:
      ArkInventory\ArkInventoryMenu.lua:207
   [string "@ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua"]:1888:
      ...e\AddOns\ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua:1837
   [string "@ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua"]:2765:
      ...e\AddOns\ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua:2731
   [string "@ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua"]:625:
      ...e\AddOns\ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua:609
Locals:

unloading all addons except arkinvemtory and swatter (part of auctioneer) i get:

Date: 2020-04-18 23:00:07
ID: 3
Error occured in: Global
Count: 1
Message: ...rkInventory\Externals\Ace3\AceEvent\AceEvent-3.0.lua line 33:
   Attempt to register unknown event "AUCTION_OWNED_LIST_UPDATE"
Debug:
   [string "=[C]"]: RegisterEvent()
   [string "@ArkInventory\Externals\Ace3\AceEvent\AceEvent-3.0.lua"]:33: OnUsed()
   [string "@ArkInventory\Libs\CallBackHandler\CallbackHandler-1.0.lua"]:168: RegisterEvent()
   [string "@ArkInventory\ArkInventory.lua"]:2619:
      ArkInventory\ArkInventory.lua:2511
   [string "=[C]"]: ?
   [string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:70:
      ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65
   [string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:527: EnableAddon()
   [string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:620:
      ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:605
   [string "=[C]"]: LoadAddOn()
   [string "@..\FrameXML\UIParent.lua"]:457: UIParentLoadAddOn()
   [string "@..\FrameXML\UIParent.lua"]:504: CombatLog_LoadUI()
   [string "@..\FrameXML\UIParent.lua"]:1268:
      ..\FrameXML\UIParent.lua:1164
Locals:
None

Thanks for all your hard work, used the addon since 2007 and love it!

**Comment by arkayenro** [comment]
youre using 3.08.22 which is over a year old, you probably should upgrade all your mods

**Comment by Unrak** [comment]
You are correct. This is because the most recent version (r946-alpha) does not work at all for me,
Using Swatter to record errors, i get 175 errors on load. I'm not going to list them all, but here are some - for variety:

Date: 2020-04-19 10:29:10
ID: 153
Error occured in: Global
Count: 1
Message: [string "ARKINV_SearchFrameViewTableRow1:OnLoad"] line 2:
   attempt to index global 'ArkInventorySearch' (a nil value)
Debug:
   [string "*:OnLoad"]:2:
      [string "*:OnLoad"]:1
Locals:
self = ARKINV_SearchFrameViewTableRow1 {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = ARKINV_SearchFrameViewTableRow1 {
 0 = <userdata>
}
(*temporary) = "LeftButtonUp"
(*temporary) = "attempt to index global 'ArkInventorySearch' (a nil value)"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  ArkInventory, v30923
  ArkInventoryRules, v20000
  ArkInventoryRulesExample, v20000
  ArkInventorySearch, v20000
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=c6)

Date: 2020-04-19 10:29:21
ID: 175
Error occured in: Global
Count: 41
Message: ...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua line 370:
   attempt to index global 'ArkInventory' (a nil value)
Debug:
   [string "@ArkInventory\ArkInventoryTranslate.lua"]:370:
      ...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:362
Locals:
self = <unnamed> {
 loopmax = 5
 loop = 0
 0 = <userdata>
 timermax = 5
}
elapsed = 0.010000
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'ArkInventory' (a nil value)"
updateTable = <table> {
 WOW_SKILL_ENCHANTING = <function> defined @Interface\AddOns\ArkInventory\ArkInventoryTranslate.lua:28
 WOW_SKILL_BLACKSMITHING = <function> defined @Interface\AddOns\ArkInventory\ArkInventoryTranslate.lua:24
 WOW_SKILL_SKINNING = <function> defined @Interface\AddOns\ArkInventory\ArkInventoryTranslate.lua:70
 WOW_SKILL_TAILORING = <function> defined @Interface\AddOns\ArkInventory\ArkInventoryTranslate.lua:74
 WOW_SKILL_LEATHERWORKING = <function> defined @Interface\AddOns\ArkInventory\ArkInventoryTranslate.lua:58
 WOW_SKILL_JEWELCRAFTING = <function> defined @Interface\AddOns\ArkInventory\ArkInventoryTranslate.lua:52
}
lang = "English (US)"
GetTranslations = <function> defined @Interface\AddOns\ArkInventory\ArkInventoryTranslate.lua:350
table = <table> {
 setn = <function> defined =[C]:-1
 insert = <function> defined =[C]:-1
 getn = <function> defined =[C]:-1
 foreachi = <function> defined =[C]:-1
 maxn = <function> defined =[C]:-1
 foreach = <function> defined =[C]:-1
 concat = <function> defined =[C]:-1
 removemulti = <function> defined =[C]:-1
 sort = <function> defined =[C]:-1
 wipe = <function> defined =[C]:-1
 remove = <function> defined =[C]:-1
}
spellTable = <table> {
 1 = <table> {
 }
}
itemTable = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
}
tooltipTable = <table> {
}
pairs = <function> defined =[C]:-1

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  ArkInventory, v30923
  ArkInventoryRules, v20000
  ArkInventoryRulesExample, v20000
  ArkInventorySearch, v20000
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=c6)

Date: 2020-04-19 10:29:10
ID: 128
Error occured in: Global
Count: 1
Message: [string "ARKINV_RulesFrameViewTableRow4:OnLoad"] line 2:
   attempt to index global 'ArkInventoryRules' (a nil value)
Debug:
   [string "*:OnLoad"]:2:
      [string "*:OnLoad"]:1
Locals:
self = ARKINV_RulesFrameViewTableRow4 {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = ARKINV_RulesFrameViewTableRow4 {
 0 = <userdata>
}
(*temporary) = "LeftButtonUp"
(*temporary) = "attempt to index global 'ArkInventoryRules' (a nil value)"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  ArkInventory, v30923
  ArkInventoryRules, v20000
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=86)

Date: 2020-04-19 10:34:03
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ArkInventory\ArkInventoryConst.lua line 10:
   Cannot find a library instance of "AceAddon-3.0".
Debug:
   [string "=[C]"]: error()
   [string "@!Swatter\Support\LibStub.lua"]:23: LibStub()
   [string "@ArkInventory\ArkInventoryConst.lua"]:10: in main chunk
Locals:
(*temporary) = "Cannot find a library instance of "AceAddon-3.0"."

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  ArkInventory, v30923
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=6a)

and this one was beyond me.....

Date: 2020-04-19 10:34:03
ID: 24
Error occured in: Global
Count: 1
Message: ..\AddOns\ArkInventory\ArkInventoryRules.lua line 10:
   attempt to index global 'ArkInventory' (a nil value)
Debug:
   [string "@ArkInventory\ArkInventoryRules.lua"]:10: in main chunk
Locals:
_G = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @Interface\FrameXML\ActionButton.lua:74
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 740
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 399
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture {
 }
 VideoOptionsFrameDefaults = VideoOptionsFrameDefaults {
 }
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 CHAT_HEADER_SUFFIX = ": "
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @Interface\FrameXML\UnitFrame.lua:778
 PaperDollTitlesPaneButton10BgTop = PaperDollTitlesPaneButton10BgTop {
 }
 DUNGEON_FLOOR_UPPERBLACKROCKSPIRE3 = "Hall of Blackhand"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 FCFDockOverflowButton_OnClick = <function> defined @Interface\FrameXML\FloatingChatFrame.lua:2379
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 ChatFrame6EditBoxFocusMid = ChatFrame6EditBoxFocusMid {
 }
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 AutoCompleteEditBox_OnKeyDown = <function> defined @Interface\FrameXML\AutoComplete.lua:369
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 32
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 ToggleEncounterJournal = <function> defined @Interface\FrameXML\UIParent.lua:957
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_QualityText {
 }
 TalentMicroButtonAlertShadowTopLeft = TalentMicroButtonAlertShadowTopLeft {
 }
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 ROGUE_COMBAT_CORE_ABILITY_4 = "Melee attack that spends Combo Points."
 JoinSkirmish = <function> defined =[C]:-1
 FriendsFriendsScrollFrameButton14 = FriendsFriendsScrollFrameButton14 {
 }
 Advanced_GraphicsAPIDropDownButtonHighlightTexture = Advanced_GraphicsAPIDropDownButtonHighlightTexture {
 }
 MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
 }
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 LFGListSearchPanelScrollFrameButton10BottomRight = LFGListSearchPanelScrollFrameButton10BottomRight {
 }
 DMG_LCD = "DMG"
 RaidGraphics_EnvironmentalDetailSlider = RaidGraphics_EnvironmentalDetailSlider {
 }
 Is64BitClient = <function> defined =[C]:-1
 SecureCmdItemParse = <function> defined @Interface\FrameXML\ChatFrame.lua:1145
 SLASH_STOPATTACK1 = "/stopattack"
 MultiCastActionButton4HotKey = MultiCastActionButton4HotKey {
 }
 CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle = CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle {
 }
 TutorialFrame_OnMouseDown = <function> defined @Interface\FrameXML\Tutoria
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  ArkInventory, v30923
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=6a)

**Comment by Unrak** [comment]
I have rolled back to 3.09.22 which works for me, but i still cannot get the rule to work. That's probably user error, but still you should know the errors i get with latest release.

Thanks for your work and your time

**Comment by arkayenro** [comment]
its erroring on missing libraries and missing sections of arkinventory, as if the file you downloaded was corrupt.  i'd suggest you redownload the file and try again.  that version has been up for a while now so if it was that bad a lot of people would be complaining

whats the rule youre trying to get to work?

**Comment by Unrak** [comment]
Thanks for the reply. Looks like it was a corrupted file.
I was trying to set up a section just for relic fragments, but i have since discovered that they are already set up under System->Key

Thanks again for your work
