### ISSUE TITLE
issues with soulbounds items

### ISSUE THREAD

**Issue by ChipsKetchup** [arkayenro/arkinventory#1302]
Hello, my soulbind items wouln't go to soulbound categories. It seems the problems come from the debug mode... 

https://gyazo.com/c45f190d781d918a481592dffcbfa151

It's a Legion legendary so it's soulbound but arkinventory considers it as a BoE.

Any advice ?

**Comment by arkayenro** [comment]
debug wont give you the actual item in your slot.  it uses the base hyperlink so its always the base item (no enchants, gems, anything)

**Comment by ChipsKetchup** [comment]
So where the bug can come ? I saw on previous issues that this bug was solved 2 years ago.

**Comment by arkayenro** [comment]
try moving it to another slot, see if it picks up the data correctly.

the only other thing i can think of would be to erase the bag data and let it rescan to see if it picks up the correct state

**Comment by arkayenro** [comment]
looks like some tooltips were coming back null instead of "TOOLTIP NOT READY"

**Comment by jcai1** [comment]
I'm getting the same issue after updating to the latest release 3.0.9.23. Soulbound items detected as non-soulbound, seems to only happen in my bank. After moving item to another slot, seems like all the items in the bag get fixed, but only until I close the bank window. If I reopen my bank then all the items are detected as non-soulbound again.

**Comment by arkayenro** [comment]
try the latest 3.09.24 alpha, see if that fixes it for you

**Comment by jcai1** [comment]
seems to be fixed, thanks!

**Comment by arkayenro** [comment]
fixed in 3.09.24
