### ISSUE TITLE
arkinventory 3.09.23 alpha 4: rules pane broken

### ISSUE THREAD

**Issue by speedwaystar** [arkayenro/arkinventory#1305]
opening rules throws the following:

> 3x [string "ARKINV_RulesFrameViewTableRow8:OnLoad"]:2: attempt to index global 'ArkInventoryRules' (a nil value)
> [string "*:OnLoad"]:2: in function <[string "*:OnLoad"]:1>
> 
> Locals:
> self = ARKINV_RulesFrameViewTableRow8 {
>  0 = <userdata>
> }
> (*temporary) = nil
> (*temporary) = ARKINV_RulesFrameViewTableRow8 {
>  0 = <userdata>
> }
> (*temporary) = "LeftButtonUp"
> (*temporary) = "attempt to index global 'ArkInventoryRules' (a nil value)"
> 

screenshot:
[https://i.imgur.com/Gt8RWCE.png](https://i.imgur.com/Gt8RWCE.png)

**Comment by arkayenro** [comment]
removed the dead alpha, uploading fixed one

**Comment by arkayenro** [comment]
fixed in alpha 5
