### ISSUE TITLE
Missing TSM tooltip on pet cages

### ISSUE THREAD

**Issue by Nelfym** [arkayenro/arkinventory#1306]
Hello,

Pet cage has no TSM tooltip (price), not sure if intended.
Works fine with other inventory addons (include built-in bags).

Let me known if I can provide more info.

**Comment by arkayenro** [comment]
you may have to disable the custom pet tooltip in arkinventory

**Comment by Nelfym** [comment]
Thanks, I can confirm this works if i disable the custom pet tooltip.

Could be nice to see TSM data inside your custom tooltip.

**Comment by arkayenro** [comment]
they can always secure hook into ArkInventory.API.CustomBattlePetTooltipReady( ... )
