### ISSUE TITLE
(solved) Translate.lua

### ISSUE THREAD

**Issue by Alandrias** [arkayenro/arkinventory#1308]
After update to 3.09.25 i have the following errors.
`10x (null)`
and 
 `7x ArkInventory\ArkInventoryTranslate.lua:382: attempt to index field 'db' (a nil value)
[string "@ArkInventory\ArkInventoryTranslate.lua"]:382: in function <ArkInventory\ArkInventoryTranslate.lua:362>

Locals:
self = <unnamed> {
 loopmax = 5
 loop = 1
 0 = <userdata>
 timermax = 5
}
elapsed = 0.012000
(*temporary) = nil
(*temporary) = <table> {
 ScanAuctionExpire = <function> defined @ArkInventory\ArkInventoryStorage.lua:4047
 ConfigInternalCategoryCustomRename = <function> defined @ArkInventory\ArkInventoryConfig.lua:554
 ScanCollectionReputation = <function> defined @ArkInventory\ArkInventoryStorage.lua:3559
 EVENT_ARKINV_VAULT_LOCK = <function> defined @ArkInventory\ArkInventoryStorage.lua:837
 modules = <table> {
 }
 MenuSwitchLocationOpen = <function> defined @ArkInventory\ArkInventoryMenu.lua:2536
 ConfigInternalCategorysetRename = <function> defined @ArkInventory\ArkInventoryConfig.lua:1052
 MenuItemMountJournal = <function> defined @ArkInventory\ArkInventoryMenu.lua:4251
 ObjectInfoItemString = <function> defined @ArkInventory\ArkInventoryStorage.lua:4555
 ConfigInternalSortMethodCheck = <function> defined @ArkInventory\ArkInventoryConfig.lua:845
 ClientGetProfessions = <function> defined @ArkInventory\ArkInventoryClient.lua:27
 EVENT_ARKINV_CHANGER_UPDATE_BUCKET = <function> defined @ArkInventory\ArkInventoryStorage.lua:536
 EVENT_ARKINV_VAULT_LOG = <function> defined @ArkInventory\ArkInventoryStorage.lua:874
 MediaObjectFontSet = <function> defined @ArkInventory\ArkInventoryMedia.lua:109
 BlizzardBagIdToInternalId = <function> defined @ArkInventory\ArkInventoryStorage.lua:1397
 EVENT_ARKINV_STORAGE = <function> defined @ArkInventory\ArkInventoryStorage.lua:216
 ScanVaultHeader = <function> defined @ArkInventory\ArkInventoryStorage.lua:2333
 MenuBarOpen = <function> defined @ArkInventory\ArkInventoryMenu.lua:164
 ConfigInternalCategoryRuleGet = <function> defined @ArkInventory\ArkInventoryConfig.lua:624
 ObjectIDCount = <function> defined @ArkInventory\ArkInventoryStorage.lua:4923
 MediaFrameFontSet = <function> defined @ArkInventory\ArkInventoryMedia.lua:159
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:274
 ScanKeyring = <function> defined @ArkInventory\ArkInventoryStorage.lua:2031
 Localise = <table> {
 }
 JunkSell = <function> defined @ArkInventory\ArkInventoryJunk.lua:205
 ConfigInternalCategoryCustomRestore = <function> defined @ArkInventory\ArkInventoryConfig.lua:543
 ConfigInternalCategorysetCopy = <function> defined @ArkInventory\ArkInventoryConfig.lua:1059
 EVENT_ARKINV_QUEST_UPDATE_BUCKET = <function> defined @ArkInventory\ArkInventoryStorage.lua:1318
 ObjectInfoQuality = <function> defined @ArkInventory\ArkInventoryStorage.lua:4327
 UnregisterAllEvents = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 ScanWearing = <function> defined @ArkInventory\ArkInventoryStorage.lua:2420
 ScanVault = <function> defined @ArkInventory\ArkInventoryStorage.lua:2161
 EmptyBag = <function> defined @ArkInventory\ArkInventoryRestack.lua:1477
 JunkIterate = <function> defined @ArkInventory\ArkInventoryJunk.lua:62
 ConfigInternalDesignGet = <function> defined @ArkInventory\ArkInventoryConfig.lua:325
 GetName = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 Frame_Config_Toggle = <function> defined @ArkInventory\ArkInventoryConfig.lua:25
 ScanMailbox_Threaded = <function> defined @ArkInventory\ArkInventoryStorage.lua:2552
 name = "ArkInventory"
 MediaMenuFontSet = <function> defined @ArkInventory\ArkInventoryMedia.lua:141
 Disable = <function> defined @Add`

**Comment by arkayenro** [comment]
try re-installing arkinventory

**Comment by Alandrias** [comment]
nothing change. Arkinventory dosnt work

**Comment by Alandrias** [comment]
Have it. Wors now. Delete config and aadon. freh installation works now fine for me.
Profile on charakter still working.
