### ISSUE TITLE
[Enhancement] Auto-close/ Auto-open behavior.

### ISSUE THREAD

**Issue by strickland** [arkayenro/arkinventory#1309]
The only thing that I am missing from other bag add-ons or also the default blizzard bag behaviour, when you go to a vendor, it automatically opens the bag, then if you left the vendor it then automatically close the bag if the option is checked which is good.

However, if you try the default blizzard bag, if you open the bags yourself prior to visiting vender or AH or anything actually, then if you move away from that vendor/AH, the bag shall still be opened, because I opened it myself.

However, if I went into the vendor while the bags are closed, and if I move away/close the vendor, the bags shall be closed, because the vendor is the person who opened the bag and not me.

To me, I think this makes sense, all bag addons have it, also the default blizz bag has it, and it is surprising to me that arkinventory doesn't have this feature, although I feel it is necessary, and I like arkinventory very much but I am only missing this feature.

Unless it exists and I can't find it, please let me know thanks.

**Comment by arkayenro** [comment]
i've added it to the latest alpha (its been uploaded, just not sure how long it will take to get approved and be visible) - take a backup of your savedvariable file before you try it, just in case.

**Comment by strickland** [comment]
Great, I've tried it and it works now! fantastic, but I want to report something that happened with that update, I don't remember it happening before.

When you open the bag, WoW freezes for a sliver of second, thats like a fraction very quickly, maybe 0.2 freeze then continue playing, you can notice when you open the bag while moving.

I don't know if thats related to the update, or an option that I changed, just felt to report this.

**Comment by arkayenro** [comment]
that will either be because i left threads disabled in one of the previous alphas, or you have sorting set to on open. try the last alpha, threads should be enabled again in that one.

**Comment by strickland** [comment]
Yes, fixed in latest update that I did, thank you! running smooth now.

**Comment by arkayenro** [comment]
fixed in 3.09.26
