### ISSUE TITLE
itemstring not working in rules any more

### ISSUE THREAD

**Issue by anteos59** [arkayenro/arkinventory#1310]
Since a few days the rule itemstring("battlepet") isn't working any more. A while ago that worked fine.

**Comment by arkayenro** [comment]
can you try the latest alpha, there were issues with battlepet tooltips being empty and as rules cache the results it left them cached as empty.   theres a fix for that in the latest alpha.

**Comment by arkayenro** [comment]
actually nevermind, its a bug in the itemstring function

**Comment by arkayenro** [comment]
should be fixed in the [r965-alpha](https://www.curseforge.com/wow/addons/ark-inventory/files/2951162)

**Comment by anteos59** [comment]
I have tried r965-alpha but it's still not working, sorry.

**Comment by anteos59** [comment]
I get the following error:
6x FrameXML\BattlePetTooltip.lua:44: Usage: BattlePetTooltip:SetPoint("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY])
[string "=[C]"]: in function `SetPoint'
[string "@FrameXML\BattlePetTooltip.lua"]:44: in function <FrameXML\BattlePetTooltip.lua:14>
[string "=[C]"]: ?
[string "=[C]"]: in function `BattlePetToolTip_Show'
[string "@ArkInventory\ArkInventoryTooltip.lua"]:1113: in function `TooltipBuildBattlepet'
[string "@ArkInventory\ArkInventoryTooltip.lua"]:165: in function <ArkInventory\ArkInventoryTooltip.lua:156>
[string "=(tail call)"]: ?
[string "@ArkInventory\ArkInventoryStorage.lua"]:2105: in function `ScanBag_Threaded'
[string "@ArkInventory\ArkInventoryStorage.lua"]:1883: in function `ScanBag'
[string "@ArkInventory\ArkInventoryStorage.lua"]:1727: in function `Scan'
[string "@ArkInventory\ArkInventoryStorage.lua"]:1677: in function `ScanLocation'
[string "@ArkInventory\ArkInventoryStorage.lua"]:253: in function `?'
[string "@AddOnSkins\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AddOnSkins\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@AddOnSkins\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@AddOnSkins\Libs\Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...s\AddOnSkins\Libs\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by anteos59** [comment]
r966-alpha has fixed it :)
Thanks a lot (for the fix and for this great addon 🥇 )
