### ISSUE TITLE
Arkinv-Accounts functionality

### ISSUE THREAD

**Issue by Tdybing** [arkayenro/arkinventory#1311]
Hello, 

I couldn't find a wiki page on Accounts so hopefully this is not a stupid question: 

I am the GM of a guild in Classic, and classic doesn't give us an actual Gbank. Hence, i've created two characters acting as storage for guild items, but I also have some of my own characters on this wow-account. 

Arkinventory is storing the gold and items and displaying them on all my chars as a sum, and specifically the gold is a bit tricky. I don't know how much gbank has in total since it calculates all chars:
I would like it to only display my two gbank chars' gold and items, when i'm on those two characters, specifically. 

So I was trying to separate my characters into guild-chars and player chars in the config->Accounts, and I could remove the data from unwanted characters. I tried making a Guildbank" Account in arkinv, but it seems this menu doesn't let me move a char to another ark-inv account? Or I might be missing the point of this feature/Menu? 

I did read about profiles and blueprints, but to me it looks more like it's covering sorting methods, window behaviour, colors and such, not actually separating the characters into segments. But I did make a profile for Gbank chars, and enabled it on those characters, but once i log back in, the new char data appears back as it does for all characters. 

The question then becomes; is there a way to do this? I was thinking I should be able to move a character to a different "Arkinv account", as there is a category called Unassigned, but they all appear in the "My account" container.

**Comment by arkayenro** [comment]
those options are for when i get around to coding for multi-account syncing

there is no way to break up characters on the same account
