### ISSUE TITLE
Not Working At All

### ISSUE THREAD

**Issue by ShepherdGaming** [arkayenro/arkinventory#1319]
I have used AI for years and now it is just gone! 

I have renamed my addon folder and reinstalled AI. It is the only mod I have installed.
I run the game and ESC and go to addons. Here is what it shows:

- Ark Inventory
- Ark Inventory [Configuration]
- Ark Inventory [Rules]
- Ark Inventory [Rules] Example
- Ark Inventory [Search]

All are checked. 

When I open my bags, it defaults to the normal bags.
I even went in and renamed my WTF folder to see if it was some setting in there. Still nothing. Help! I love this mod!

**Comment by arkayenro** [comment]
uncheck Ark Inventory [Rules] Example, its meant for other developers (and why its disabled by defaults when installed)

**Comment by arkayenro** [comment]
you might want to install buggrabber and bugsack to see if they collect any errors

**Comment by ShepherdGaming** [comment]
Thanks for the fast response! It came back with 12 errors.

1
1x ArkInventory\ArkInventoryConst.lua:10: Cannot find a library instance of "AceAddon-3.0".
[string "=[C]"]: in function `error'
[string "@Accomplishment\Lib\LibStub\LibStub.lua"]:23: in function `LibStub'
[string "@ArkInventory\ArkInventoryConst.lua"]:10: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceAddon-3.0"."

**Comment by ShepherdGaming** [comment]
1x ArkInventory\ArkInventoryPT.lua:2: attempt to index global 'ArkInventory' (a nil value)
[string "@ArkInventory\ArkInventoryPT.lua"]:2: in main chunk

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'ArkInventory' (a nil value)"

**Comment by ShepherdGaming** [comment]
1x ArkInventory\ArkInventoryClient.lua:3: attempt to index global 'ArkInventory' (a nil value)
[string "@ArkInventory\ArkInventoryClient.lua"]:3: in main chunk

Locals:
(*temporary) = nil
(*temporary) = <function> defined @ArkInventory\ArkInventoryClient.lua:3
(*temporary) = "attempt to index global 'ArkInventory' (a nil value)"

**Comment by ShepherdGaming** [comment]
1x ArkInventory\ArkInventoryCPU.lua:24: attempt to index global 'ArkInventory' (a nil value)
[string "@ArkInventory\ArkInventoryCPU.lua"]:24: in main chunk

Locals:
(*temporary) = nil
(*temporary) = <function> defined @ArkInventory\ArkInventoryCPU.lua:24
(*temporary) = "attempt to index global 'ArkInventory' (a nil value)"

**Comment by ShepherdGaming** [comment]
1x ArkInventory\ArkInventoryCodex.lua:31: attempt to index global 'ArkInventory' (a nil value)
[string "@ArkInventory\ArkInventoryCodex.lua"]:31: in main chunk

Locals:
_G = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @FrameXML\ActionButton.lua:74
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 740
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 399
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 InterfaceOptionsNamesPanelUnitNameplatesShowAll = InterfaceOptionsNamesPanelUnitNameplatesShowAll {
 }
 VideoOptionsFrameDefaults = VideoOptionsFrameDefaults {
 }
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 CHAT_HEADER_SUFFIX = ": "
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML\UnitFrame.lua:778
 PaperDollTitlesPaneButton10BgTop = PaperDollTitlesPaneButton10BgTop {
 }
 DUNGEON_FLOOR_UPPERBLACKROCKSPIRE3 = "Hall of Blackhand"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 FCFDockOverflowButton_OnClick = <function> defined @FrameXML\FloatingChatFrame.lua:2379
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 MoneyFrame_OnEvent = <function> defined @FrameXML\MoneyFrame.lua:202
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 LE_GAME_ERR_RECRUIT_A_FRIEND_FAILED = 950
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 32
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 ToggleEncounterJournal = <function> defined @FrameXML\UIParent.lua:957
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_QualityText {
 }
 TalentMicroButtonAlertShadowTopLeft = TalentMicroButtonAlertShadowTopLeft {
 }
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 ROGUE_COMBAT_CORE_ABILITY_4 = "Melee attack that spends Combo Points."
 JoinSkirmish = <function> defined =[C]:-1
 FriendsFriendsScrollFrameButton14 = FriendsFriendsScrollFrameButton14 {
 }
 Advanced_GraphicsAPIDropDownButtonHighlightTexture = Advanced_GraphicsAPIDropDownButtonHighlightTexture {
 }
 MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
 }
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 LFGListSearchPanelScrollFrameButton10BottomRight = LFGListSearchPanelScrollFrameButton10BottomRight {
 }
 DMG_LCD = "DMG"
 RaidGraphics_EnvironmentalDetailSlider = RaidGraphics_EnvironmentalDetailSlider {
 }
 Is64BitClient = <function> defined =[C]:-1
 SecureCmdItemParse = <function> defined @FrameXML\ChatFrame.lua:1145
 SLASH_STOPATTACK1 = "/stopattack"
 MultiCastActionButton4HotKey = MultiCastActionButton4HotKey {
 }
 CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle = CompactRaidFrameManagerDisplayFrameFilterOptionsF

**Comment by ShepherdGaming** [comment]
1x ArkInventory\Locale\game-Game.lua:1: Cannot find a library instance of "AceLocale-3.0".
[string "=[C]"]: in function `error'
[string "@Accomplishment\Lib\LibStub\LibStub.lua"]:23: in function `LibStub'
[string "@ArkInventory\Locale\game-Game.lua"]:1: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceLocale-3.0"."

**Comment by ShepherdGaming** [comment]
1x ArkInventory\Locale\enUS-English (US).lua:1: Cannot find a library instance of "AceLocale-3.0".
[string "=[C]"]: in function `error'
[string "@Accomplishment\Lib\LibStub\LibStub.lua"]:23: in function `LibStub'
[string "@ArkInventory\Locale\enUS-English (US).lua"]:1: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceLocale-3.0"."

**Comment by ShepherdGaming** [comment]
1x ArkInventory\Locale\deDE-German.lua:1: Cannot find a library instance of "AceLocale-3.0".
[string "=[C]"]: in function `error'
[string "@Accomplishment\Lib\LibStub\LibStub.lua"]:23: in function `LibStub'
[string "@ArkInventory\Locale\deDE-German.lua"]:1: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceLocale-3.0"."

**Comment by ShepherdGaming** [comment]
1x ArkInventory\Locale\esES-Spanish (EU).lua:1: Cannot find a library instance of "AceLocale-3.0".
[string "=[C]"]: in function `error'
[string "@Accomplishment\Lib\LibStub\LibStub.lua"]:23: in function `LibStub'
[string "@ArkInventory\Locale\esES-Spanish (EU).lua"]:1: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceLocale-3.0"."

**Comment by ShepherdGaming** [comment]
1x ArkInventory\Locale\esMX-Spanish (Latin American).lua:1: Cannot find a library instance of "AceLocale-3.0".
[string "=[C]"]: in function `error'
[string "@Accomplishment\Lib\LibStub\LibStub.lua"]:23: in function `LibStub'
[string "@ArkInventory\Locale\esMX-Spanish (Latin American).lua"]:1: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceLocale-3.0"."

**Comment by ShepherdGaming** [comment]
10x (null)

**Comment by ShepherdGaming** [comment]
36x ArkInventory\ArkInventoryTranslate.lua:370: attempt to index global 'ArkInventory' (a nil value)
[string "@ArkInventory\ArkInventoryTranslate.lua"]:370: in function <ArkInventory\ArkInventoryTranslate.lua:362>

Locals:
self = <unnamed> {
 loopmax = 5
 loop = 0
 0 = <userdata>
 timermax = 5
}
elapsed = 0.010000
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'ArkInventory' (a nil value)"
updateTable = <table> {
 WOW_SKILL_ENCHANTING = <function> defined @ArkInventory\ArkInventoryTranslate.lua:28
 WOW_SKILL_BLACKSMITHING = <function> defined @ArkInventory\ArkInventoryTranslate.lua:24
 WOW_SKILL_SKINNING = <function> defined @ArkInventory\ArkInventoryTranslate.lua:70
 WOW_SKILL_TAILORING = <function> defined @ArkInventory\ArkInventoryTranslate.lua:74
 WOW_SKILL_LEATHERWORKING = <function> defined @ArkInventory\ArkInventoryTranslate.lua:58
 WOW_SKILL_JEWELCRAFTING = <function> defined @ArkInventory\ArkInventoryTranslate.lua:52
}
lang = "English (US)"
GetTranslations = <function> defined @ArkInventory\ArkInventoryTranslate.lua:350
table = <table> {
 pack = <function> defined @FastGuildInvite\functions.lua:869
 setn = <function> defined =[C]:-1
 insert = <function> defined =[C]:-1
 getn = <function> defined =[C]:-1
 foreachi = <function> defined =[C]:-1
 maxn = <function> defined =[C]:-1
 foreach = <function> defined =[C]:-1
 concat = <function> defined =[C]:-1
 copy = <function> defined @ElvUI\Developer\Table.lua:5
 removemulti = <function> defined =[C]:-1
 sort = <function> defined =[C]:-1
 wipe = <function> defined =[C]:-1
 remove = <function> defined =[C]:-1
}
spellTable = <table> {
 1 = <table> {
 }
}
itemTable = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
}
tooltipTable = <table> {
}
pairs = <function> defined =[C]:-1

**Comment by ShepherdGaming** [comment]
There are all 12 that BugSack picked up.

**Comment by arkayenro** [comment]
delete all the arkinventory folders and re-download.  it looks like its completely corrupted

make sure you have not downloaded the no-lib version.  there should be files in the arkinventory/externals and arkinventory/libs folders

**Comment by ShepherdGaming** [comment]
I am using the Twitch app to install. I had reinstalled after deleting the folders and that did not solve. I went in and completely told Twitch to remove it and then reinstall. That did work. Thank you so much for your help! Wonderful Mod!
