### ISSUE TITLE
Adding a Bag to a Bar on "SOME" characters

### ISSUE THREAD

**Issue by ColDinfinite** [arkayenro/arkinventory#1321]
Hi,

I love Arkinventory and have used it for years. I'm currently playing Classic and can't work out how to do a particular function.

Specifically I want to set up, say, Bar 55 to contain my entire Bag 5 (this is a Shard Bag on my Warlock or my Quiver on my Hunter. It could even be my Herb bag or Enchant bag). However, If I'm not on a character which uses such bags, then I don't want to configure Bar 55 as my Bag 5.

I've been scratching my head, and absolutely cant work out how to do this.

In other addons this has been simply a case of setting up profiles, but even though I have read your comments on Blueprints I still haven't been able to work it out.

Please understand that this is not a horrendous issue to be fair. My current workaround is manually selecting Bar 55 to be Bag 5 whenever I log into a particular character, and remove it on another. The situation is just irksome, but would love to know if there is a solution, and if there is how do I fix it?

Here is my warlock showing Bar 55 configured as my Bag 5 (Box of Souls (soulshard bag))

![image](https://user-images.githubusercontent.com/66354607/83613125-3eb79300-a57b-11ea-9210-f917993d60da.png)

**Comment by arkayenro** [comment]
its probably simpler to not try and put a specific  bag there but to put the warlock class categories there instead, eg; class > warlock, empty > soul, that way it will be empty on other classes, and if you ever change bag 5 from soul to normal it wont matter

you should be able to set it up with two profiles where the blueprints are set almost the same, i think its just the layout that would need to be different

**Comment by ColDinfinite** [comment]
Thanks for the reply.

TBH, if I understand what you mean, then I **_had_** been doing similar to that, but the reason I wanted to use my "assign bag 5" idea, was that the "space" remaining in bag 5, if it wasn't full of, say, shards, manifested itself as empty space in my bags. However that space is not available for anything, so it was 'misleading' me into thinking I had spare capacity, when I did not (see new image - down on bar 1 you can see 3 purple outlined slots which are empty slots from the shard bag.

Using my method, bag 5, full or empty slots, would all be gathered together. up out of the way of my true empty bag space.

I did look at interpreting your "class > warlock, empty > soul", but TBH I didn't understand what you meant by "empty > soul", would you mind clarifying?
 
![image](https://user-images.githubusercontent.com/66354607/83722536-0f655c80-a635-11ea-8e21-53381d350b71.png)

**Comment by arkayenro** [comment]
soul shards are covered under the class > warlock category
empty > soul bag is the category for empty soul bag slots
you want to assign both of those categories to bar 55
you shouldnt need a rule for this

empty > soul
in edit mode click on bar 55
go down to assignable categories
mouse over empty
click on soul bag

**Comment by ColDinfinite** [comment]
PERFECT - that is EXACTLY what I wanted

Thank you very much
