### ISSUE TITLE
Unable to add more bars. Stuck at 45

### ISSUE THREAD

**Issue by Adelabruja** [arkayenro/arkinventory#1323]
I am having an issue where i can't insert any additional bars. I turned off all addons. I rebooted and I even tried different alts and I am unable to go beyond 45 bars. I'm not sure if I am doing something wrong or have a limit that I can't find because I have read there is no limit to the number of bars you can create. Let me know if you have any advice to fix the issue.

Thank you,

Adel

**Comment by arkayenro** [comment]
if you assign a category/rule anywhere in the top row that will then add a new top row.

if you did that and it didnt expand then thats weird as i didnt think it was possible for the code to do that
