### ISSUE TITLE
Missing vendor-icon (mouse-over)

### ISSUE THREAD

**Issue by Aur0r4** [arkayenro/arkinventory#1328]
Hello!

I've noticed that there is no "vendor-icon" visible when you are talking to a vendor and mouse-over an item that you want to sell.
Instead the cursor is flickering.
I'm talking about this icon:
![image](https://user-images.githubusercontent.com/28149249/86836620-089b9080-c09e-11ea-9c47-6a9ecc683f8d.png)

I've deleted my WTF folder and disabled all other addons so that only a clear version of AI is running but still get this problem.
I've seen someone reporting this issue a few month ago here: https://github.com/arkayenro/arkinventory/issues/1317

I can do a video if it helps.

_
Aur0r4

**Comment by arkayenro** [comment]
the other issue was for a custom icon being added, not that vendor cursor icon you show

you might need a bigger screen capture as that cursor icon should only display when you mouse into an item and i cant tell what that is over.

the cursor that changes when im talking to a vendor and i cant see anything obviously wrong wit the code

have you disabled all other addons to see if it still happens?

**Comment by Aur0r4** [comment]
Hi arkayenro, thank you for that really quick response, I really appreciate it.

You're right, I'm sorry for opening a ticket for this. It seems like it is a problem on my site, but I'm still wondering why the mouse-cursor does not change to a bag, when hover over an item that I want to sell to vendor.
I've reset my whole UI (renamed WTF and Interface folder) and loaded different versions of ArkInventory, all with the same issue.
Then, I told my girlfriend to test it for me too. The doesn't have this problem. So it must be something on my computer :-/...

Just reinstalled the gpu-driver, but it didnt change a thing.
Weird thing is, that everything is OK with the default blizzard-bags.

Btw: The screenshot above was only there to show you which cursor-icon I refer too.

You can close this ticket or maybe you have another hint for me.

**Comment by arkayenro** [comment]
disable all mods, including AI, see if you have the issue in the base client (not sure if you tried that or not).

its possible that image has become corrupt and you may need to repair the game

**Comment by Aur0r4** [comment]
Unfortunately, I've already tried that. When I deactivate AI, everything works fine in the Blizzard bags.

I deleted the WTF and Interface folder and then installed ONLY AI. Also here the error occurs.

I think I will download WoW again or try the repair option, although it is still strange that the error occurs only in AI.

Thanks for your help!
