### ISSUE TITLE
[Question] How to seperate the normal bag and bank?

### ISSUE THREAD

**Issue by crazy4ever** [arkayenro/arkinventory#1329]
First of all, just wanna say that his addon is amazing! Love the way you can setup these rules. :)

Second, I have (hoping to be) a very small question, how do I seperate my normal Bag and Bank so the bank won't use the bag configuration?

I can see under "General -> Profiles -> Default -> Controls -> Bank" some settings regarding the "Layout", however when I "add" a new profile it does not appear under the "Layout" option, only "1000, 9997, 9998, 9999" show up under the selection list.

Ps. Sorry for opening an issue here on Github, sadly twitch had currently some problems regarding posting a comment.

**Comment by Kirbdawg** [comment]
Settings > Designs(Styles/Layouts)    -  This is where you tweak the "1000, 9997, 9998, 9999"   For instance, make two new style/layouts called Bank1 and Bag1.

General -> Profiles -> Default -> Controls -> Bank"   - This is where you assign the new layout:  Bank1 
General -> Profiles -> Default -> Controls -> Backpack"   - This is where you assign the new layout:  Bag1 

Hope that helps.

**Comment by crazy4ever** [comment]
@Kirbdawg Thanks for the help, that worked. Cheers!
