### ISSUE TITLE
Can't get outfit() rule to work

### ISSUE THREAD

**Issue by Laekoth** [arkayenro/arkinventory#1330]
On classic and using itemrack. I can't get the outfit command to work, even 'outfit( )' by itself. Is it not supported for the classic version of itemrack?

**Comment by toffbiffle** [comment]
Im using the same and it's working for me so it is supported for sure.

If you have already added a custom category for some items in AI it may have higher priority then the Outfit() rule.

**Comment by fenrisbear** [comment]
Just downloaded the addon today. Just create a rule, set the formula to be like ```outfit("nameOfSet")```, in edit mode both _enable_ and assign your new rule to a place in your bag window.

**Comment by Laekoth** [comment]
On a whim I checked this again, and the fact they default to disabled is what got me. Not very obvious if you aren't looking for it.
