### ISSUE TITLE
Guild Bank Tabs

### ISSUE THREAD

**Issue by banshiff** [arkayenro/arkinventory#1333]
When I open a guild bank, the tabs show on the bottom for a moment while the guild bank is loading, but then disappear once the guild bank is fully loaded. I tried erasing the guild bank data, but the problem persists.

**Comment by arkayenro** [comment]
you have to enable the bag changer to see them, unless you mean something else

**Comment by banshiff** [comment]
![WoWScrnShot_072120_095238](https://user-images.githubusercontent.com/68565721/88063514-1b02d900-cb38-11ea-8f56-f219f11c9954.jpg)
![WoWScrnShot_060120_123903](https://user-images.githubusercontent.com/68565721/88063523-1d653300-cb38-11ea-9829-5ddae4fed589.jpg)

**Comment by banshiff** [comment]
Sorry, attached the wrong screenshot for the second one.
![WoWScrnShot_072120_095323](https://user-images.githubusercontent.com/68565721/88063653-438ad300-cb38-11ea-994d-4978b0c1735c.jpg)

**Comment by arkayenro** [comment]
the bag changer frame isnt open on either of those, so while you may have a design/style for the guild bank you must not be using it (ie, its not assigned to the bank) - check the profile youre using for what option are set for the guild bank

just open the guild bank and click on the green chest icon (the one next to the blue swirly / refresh icon) to toggle the frame
