### ISSUE TITLE
[Request] Sorting item by equip slot, in the same order as character pane (Head > Shoulder > Neck > ...)

### ISSUE THREAD

**Issue by RamyRafik** [arkayenro/arkinventory#1335]
The existing sorting priority "Item equip location" sorts items by slot name alphabetically ("Feet" > "Finger" > ..)
Can we have another sorting priority to apply the order slots appear in character sheet ("Head" > "Neck" > ... > "Trinket" > "Main hand" > "Off hand")?

**Comment by arkayenro** [comment]
yes, i forgot about that.  was meant to change it ages ago but never got around to it.

will be in the next alpha/release

**Comment by arkayenro** [comment]
fixed in 3.09.33
