### ISSUE TITLE
itemstat() not working

### ISSUE THREAD

**Issue by nsomneeak** [arkayenro/arkinventory#1336]
The itemstat() function correctly errors out if you leave out the arguments, but does not appear to work with any argument supplied.

I found that the variable below in ArkInventoryRules.lua returns an empty string:
```lua
local stats = ArkInventory.TooltipGetBaseStats( ArkInventoryRules.Tooltip )
```

When looking at the above function in ArkInventoryTooltip.lua, it doesn't appear that the for loop ever executes because the ArkInventory.TooltipGetNumLines( tooltip )  piece returns 0.

```lua
function ArkInventory.TooltipGetBaseStats( tooltip, activeonly )
	
	local obj, txt, ctxt
	
	local started = false
	local rv = ""
	
	for i = 2, ArkInventory.TooltipGetNumLines( tooltip ) do
```

**Comment by arkayenro** [comment]
this may be fixed in 3.09.30, could you try it and let me know

**Comment by nsomneeak** [comment]
This does not appear to be fixed in 3.09.30. It correctly returns an error if no arguments are supplied, and correctly groups all gear using itemstat(""), but doesn't do anything if the argument is anything other than an empty string.

**Comment by arkayenro** [comment]
should be fixed in the next alpha (about 30 minutes)

**Comment by nsomneeak** [comment]
This does appear to be fixed in the r990-alpha.

Thank you!
