### ISSUE TITLE
Altered name of a caged pet getting lost with "custom tooltip"

### ISSUE THREAD

**Issue by Proteyer** [arkayenro/arkinventory#1338]
Hi there,

I found an issue in coexistens of Battle Pet BreedID and the AI Pet Journal "costum tooltip". Battle Pet BreedID adds the breed of a caged pet to the name (see screenshot), if the custom tooltip is activated these information getting lost byside of colored name for rarity but this is lee important for me. I'm pretty sure it worked together dome time back, I'm using AI for years now and Battle Pet BreedID cames way later to my addons. Please have a look into it, I really hope it's easy to get this information back.

Option off
![grafik](https://user-images.githubusercontent.com/26662998/89827060-6fa5dc80-db57-11ea-9895-ef26332a63a1.png)

Tooltip looks like:
![grafik](https://user-images.githubusercontent.com/26662998/89827123-906e3200-db57-11ea-98fd-df26c6136d67.png)

Option on
![grafik](https://user-images.githubusercontent.com/26662998/89827240-bd224980-db57-11ea-8ed7-ed4b519dced6.png)

Tooltip looks like:
![grafik](https://user-images.githubusercontent.com/26662998/89827410-d88d5480-db57-11ea-884f-1f1abfb1f0e0.png)

**Comment by arkayenro** [comment]
created an issue for them to fix their side of the code

https://www.curseforge.com/wow/addons/battle_pet_breedid/issues/14

**Comment by arkayenro** [comment]
i also changed the battlepet tooltips around a bit so i think it will work better with custom names now
