### ISSUE TITLE
Is there anyway to clear "New!" tab

### ISSUE THREAD

**Issue by strickland** [arkayenro/arkinventory#1339]
Helo, I got a tab called "New!" which puts newly received items for 3mins, which is very nice and I love it.

But is there any button that I click to force sort out the newly items, i.e. just put each item in its category rather than wait for 3mins, this helps sometimes to sort out items right away if needed incase I want my !New window empty for other stuff that I am about to collect.

**Comment by strickland** [comment]
I tried the Restack button but it didn't remove the new items, also tried the refresh, didnt help either.

**Comment by arkayenro** [comment]
right click on the refresh icon > new items: reset
