### ISSUE TITLE
Ver 3.09.31 Error when opening/reloading/refreshing bags

### ISSUE THREAD

**Issue by Lorine3** [arkayenro/arkinventory#1342]
I'm getting an error every time Ark loads up my bag view. "Error > Interface\Addons\ArkInventory\ArkInventory.lua:9992: attempt to index local 'obj' (a nil value)"

It also seems to be cutting off the display of my bag contents when you first open them after logging in. Almost like it could be nested inside the window and you can scroll down to see more, if that makes sense. Closing and reopening causes it to fully display my bag contents.

Any thoughts on what might be causing this?

**Comment by arkayenro** [comment]
line 9992 shows one of the backpack currency tokens but obj is used before that so it should have errored before that if obj was nil

what version are you running, and what client?

**Comment by Lorine3** [comment]
I'm running Ver 3.09.31 for BFA. It happens on multiple toons. I do have a space designated for currency, not sure if that matters.

**Comment by arkayenro** [comment]
install [r1000-alpha](https://www.curseforge.com/wow/addons/ark-inventory/files/3040457), it has some output if the token frame is missing which should let me know if thats what the problem really is

**Comment by Lorine3** [comment]
![image](https://user-images.githubusercontent.com/70114978/90991328-ee464500-e56d-11ea-98ae-8fbf472f608f.png)
I only opened my bags once

**Comment by arkayenro** [comment]
ok, somehow you have extra token frames that dont exist in the normal game

int he chat window enter this in `/dump MAX_WATCHED_TOKENS`

does it output 3 or 10?

**Comment by Lorine3** [comment]
10

**Comment by arkayenro** [comment]
youve got another mod thats changed it.

do you have any mod that increases the currency tokens that can be displayed on the backpack?

**Comment by Lorine3** [comment]
Okay yeah I found it. bdUI was causing it. The author consolidated all the separate UI mods he had into one and I guess one of them was interfering with Ark.

Thanks for your help!

**Comment by arkayenro** [comment]
np, i'll update it again so that its capped at 3, that way it wont spit out errors unless its less than 3
