### ISSUE TITLE
Sell Junk

### ISSUE THREAD

**Issue by YoungGooby** [arkayenro/arkinventory#1343]
Hey, I can't get sell junk to work at all. I have some items set to junk, junk is set to auto sell, yet it doesn't do anything. Below are SS's of everything. 

https://i.imgur.com/DetHmGo.png

https://i.imgur.com/iEwkFeJ.png

https://i.imgur.com/5jKcIOR.jpeg

Any one know what I can do to fix this?

**Comment by arkayenro** [comment]
do you see output along the lines of selljunk is loaded, aborting ArkInventory junk sell?

its probably because im setting the junk icon for those items but they arent in selljunk, i'll need to tweak the code a bit to make sure i dont add those if youre using another junk selling mod

**Comment by arkayenro** [comment]
actually, if you use another mod for selling junk youll probably want to disable the option in arkinventory

**Comment by arkayenro** [comment]
also, if you dont actually have sell junk installed, then you have the test option enabled - that wont allow anything to actually be sold

**Comment by YoungGooby** [comment]
I wanted to use Arkinventory to sell junk and stuff as I can see what will be sold by just looking at my inventory. 

Are you saying I need this addon: https://www.curseforge.com/wow/addons/sell-junk  
For the selljunk function to work? 

The only addon I have where selljunk isn't directly disabled is TSM and I don't know how to disable it.

**Comment by MrUzagi** [comment]
You don't need any other add-on installed apart from AI itself for the built in function to work. If it still doesn't work it's most likely another add-on interfering. Try to have only AI active and see if it works then.

**Comment by MrUzagi** [comment]
I'm not in-game so can't check, but you might also have to activate auto-sell on the bar you keep the junk in. Similar to how new rules are disabled and need to be enabled.

**Comment by YoungGooby** [comment]
Okay, I figured it out. It was the addon: extended vendor UI that was causing the issue. Had to get rid of it, but that's fine. Thanks for the help.
