### ISSUE TITLE
Opening configuration in classic

### ISSUE THREAD

**Issue by Tylak111** [arkayenro/arkinventory#1345]
Every time I try to open the configuration in 3.09.34-Classic I get:

Message: ...ace\AddOns\ArkInventoryConfig\ArkInventoryConfig.lua line 9462:
   attempt to call a nil value
Debug:
   (tail call): ?
   ...ace\AddOns\ArkInventoryConfig\ArkInventoryConfig.lua:9462: ConfigInternalLDBMountsUpdate()
   ...ace\AddOns\ArkInventoryConfig\ArkInventoryConfig.lua:9449: ?()
   ...ace\AddOns\ArkInventoryConfig\ArkInventoryConfig.lua:3407: ConfigInternal()
   ...ace\AddOns\ArkInventoryConfig\ArkInventoryConfig.lua:86: ConfigRefresh()
   ...ace\AddOns\ArkInventoryConfig\ArkInventoryConfig.lua:92: ?()
   ...ventory\Libs\CallBackHandler\CallbackHandler-1.0.lua:145:
      ...ventory\Libs\CallBackHandler\CallbackHandler-1.0.lua:145
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4
   [C]: ?
   [string "safecall Dispatcher[1]"]:13: ?()
   ...ventory\Libs\CallBackHandler\CallbackHandler-1.0.lua:90: SendMessage()
   ...ace\AddOns\ArkInventoryConfig\ArkInventoryConfig.lua:9524: in main chunk
   [C]: LoadAddOn()
   ArkInventory\ArkInventory.lua:11219: LoadAddOn()
   ArkInventory\ArkInventoryConfig.lua:19: Frame_Config_Show()
   ArkInventory\ArkInventoryMenu.lua:64: func()
   ...e\AddOns\ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua:731:
      ...e\AddOns\ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua:670

**Comment by arkayenro** [comment]
will be fixed in 3.09.35.  just waiting for curse to process it

**Comment by arkayenro** [comment]
should be available now

**Comment by arkayenro** [comment]
fixed in 3.09.25
