### ISSUE TITLE
Reputation reversed

### ISSUE THREAD

**Issue by Flowy** [arkayenro/arkinventory#1346]
I really like the new reputation tab, to see status on other characters. Would love to see same for skills and maybe even profesion abilities.

For some reason tho, reputation tab is showing me 'reversed' reputation.
I.e.:
I have Revered 5390 reputation with cenarion circle, but token in reputation tab shows revered with 15610 - thats exactly the amount needed to reach exalted.
It is useful even this way, but it may be confusing.

**Comment by arkayenro** [comment]
there are formatting options in the config under tooltip > reputation so you can set them up any way you want (within reason)

the rep window should show both values current rep / max rep (for that level)
