### ISSUE TITLE
Shadowlands - Stuck at "Loading"

### ISSUE THREAD

**Issue by roweboy1974** [arkayenro/arkinventory#1347]
With the last few versions in Shadowlands beta the bag window is stuck saying "Loading...". 

![image](https://user-images.githubusercontent.com/22044497/91739307-be0b3180-eb7f-11ea-8a84-2626a6e67abe.png)

I get this error when closing the bag:
[11:50:52] ArkInventory: ERROR> Interface\AddOns\Scrap\addons\main\main.lua:189: attempt to compare nil with number
[11:50:52] [Error 000002A71D31CBD0] captured, click the link for more information.

**Comment by arkayenro** [comment]
that looks like an error with scrap, could you post the whole error so i can double check?

**Comment by arkayenro** [comment]
definitely a scrap issue, theyre still using the LE_ITEM_QUALITY_UNCOMMON and LE_ITEM_QUALITY_EPIC globals on line 189 but they longer exist in shadowlands.

you probably have a rule thats using scrap?

**Comment by roweboy1974** [comment]
This is straight out of the box. I did not make any config or rules changes. I'm not even sure where I would find that. I disabled the Scrap app but it still happens

    On Monday, August 31, 2020, 07:31:44 PM EDT, arkayenro <notifications@github.com> wrote:  
 
 


definitely a scrap issue, theyre still using the LE_ITEM_QUALITY_UNCOMMON and LE_ITEM_QUALITY_EPIC globals on line 189 but they longer exist in shadowlands.

you probably have a rule thats using scrap?

**Comment by Kirbdawg** [comment]
Scrap is visually appealing and well thought out.... BUT, it is full of bugs.  Try Aardvark instead.   It's a little different but does all the things Scrap does, does it a little better, and it works without bugs and without issues with other addons.
