### ISSUE TITLE
Mailbox Keybinding Bug

### ISSUE THREAD

**Issue by dylanboor** [arkayenro/arkinventory#1348]
The keybinding set in game to open the Mail UI throws an error.
Fixed by correcting line 21 in Bindings.xml from Mail -> Mailbox

	<Binding name="ARKINV_TOGGLE_MAILBOX" category="ADDONS">
		ArkInventory.Frame_Main_Toggle( ArkInventory.Const.Location.Mailbox )
	</Binding>

**Comment by arkayenro** [comment]
thanks, will be fixed in the next release

**Comment by arkayenro** [comment]
fixed in 3.09.36
