### ISSUE TITLE
Skill bar separation

### ISSUE THREAD

**Issue by guilherme-rs** [arkayenro/arkinventory#1350]
After the last update, im having an issue where ark is not organizing los items de profissao.
Already disabled all other addons, and the issue persist.

![image](https://user-images.githubusercontent.com/7820211/91877784-d8fba580-ec54-11ea-85f3-04a82dd804dd.png)

**Comment by arkayenro** [comment]
click on the items that should be in there, are they showing another skill?

do you have both skills?  if so you can prioritise which skill is more important to you.  its in the config under general > professions

if you do not have mining as a skill then it will most likely be under one of the trade goods categories

**Comment by guilherme-rs** [comment]
I have two gathering profession, mining and herbalism, and to organize only if i put as trade goods as you said.
is this happening because i have both skills?

**Comment by arkayenro** [comment]
yes.  when you have two skills the tradegoods are moved to whichever one is first.

you can override that in the config and make the second skill have priority over the first so that they go to that skill instead

**Comment by guilherme-rs** [comment]
Okay, thank you for the explanation and the great addon.
