### ISSUE TITLE
Classic trying to load retail resource?

### ISSUE THREAD

**Issue by toffbiffle** [arkayenro/arkinventory#1351]
Kind of an odd ball, Im trying to run 2 instances of the Wow classic Client at the same time but sharing the
Interface
Utils
and Data folders between both instances. 

Most of the stuff is working as intended but when im loading the Second instance of the wow client i get the following:
ArkInventory: ERROR> Failed to load Blizzard_Collections: Missing
ArkInventory: ERROR> Failed to load Blizzard_GuildBankUI: Missing
ArkInventory: ERROR> Failed to load Blizzard_VoidStorageUI: Missing

With my limited amount of lua experience I think it has with detecting retail from classic but im not sure.

When i check the ToC between the two instances when they are running they do report the same version ( as they should ) tho.

The first instance of ArkInventory is running without issue, thanks for an awesome addon btw.

**Comment by toffbiffle** [comment]
Trying to troubleshoot.
If i use the addon wowlua to run script ingame in a neeter manner i get different results between the two client instances when running:
print( ArkInventory.ClientCheck(ArkInventory.Const.Blizzard.Client.RETAIL ) )
print( ArkInventory.ClientCheck(ArkInventory.Const.Blizzard.Client.CLASSIC ) )

Original installation gives:
false
true

But the copied folders instance gives the opposite results:
true
false

I know this is an issue that is more or less bleeding edge and probably not many other then me have an issue with it so i understand if its to cumbersome to even take a look at it. But i still have my hopes up. :-P

**Comment by arkayenro** [comment]
for some reason it thinks youre running retail, not classic, so its trying to load those blizzard mods

in the failing version type these into the chat window, one at a time
/dump GetCVar( "agentuid" )
/dump WOW_PROJECT_ID

thats what im using to tell the difference between retail/classic and live/ptr/beta.  if your cvar is something else then it will default to retail live

if youre running classic live then you should have a value of "wow_classic"

i may have to add some extra checks for weird cases like this depending on what values youre getting

**Comment by arkayenro** [comment]
if you want to try manually fixing it, open ArkInventoryConst.lua and go to line 1054 and replace that section with this

```
local c = string.lower( GetCVar( "agentuid" ) )
if WOW_PROJECT_ID == 2 then
	if c == "classic_ptr" then
		ArkInventory.Const.Blizzard.Client.id = ArkInventory.Const.Blizzard.Client.CLASSIC_PTR
		ArkInventory.Const.Blizzard.Client.name = EXPANSION_NAME0 .. ": PTR"
	else -- c == "wow_classic"
		ArkInventory.Const.Blizzard.Client.id = ArkInventory.Const.Blizzard.Client.CLASSIC
		ArkInventory.Const.Blizzard.Client.name = EXPANSION_NAME0
	end
else
	if c == "wow_beta" then
		ArkInventory.Const.Blizzard.Client.id = ArkInventory.Const.Blizzard.Client.RETAIL_BETA
		ArkInventory.Const.Blizzard.Client.name = EXPANSION_NAME8 .. ": Beta"
	elseif c == "wow_ptr" then
		ArkInventory.Const.Blizzard.Client.id = ArkInventory.Const.Blizzard.Client.RETAIL_PTR
		ArkInventory.Const.Blizzard.Client.name = EXPANSION_NAME7 .. ": PTR"
	else
		ArkInventory.Const.Blizzard.Client.id = ArkInventory.Const.Blizzard.Client.RETAIL
		ArkInventory.Const.Blizzard.Client.name = EXPANSION_NAME7
	end
end
```

**Comment by toffbiffle** [comment]
Im sad to inform you that the test turned up empty...

Dump: value=GetCVar("agentuid")
[1]=""
Dump: WOW_PROJECT_ID
WOW_PROJECT_ID=2

For some reason it just turn up blank. The weird thing is that I'm pretty sure that ArkInventory did work a short while just when i was copying the files over. But i cant for the love of god figure out why it now suddenly miss-identify.

The good part is that your suggested code change worked for me so now its all good again.
I was pondering on writing something of my own about the lines of GetBuildInfo() but now i dont have to. (probably for the best)

Thanks so much for the help on this absurdly niche bug/feature/issue!

**Comment by toffbiffle** [comment]
i took a look at my second WTF/Config.wtf file and apparantly i have some missing parts in there
`SET agentUID "wow_classic" `
was one of them.

after i manually added that to the Config.wtf file the un-edited version of ArkInventoryConst.lua worked as expected.

I'm not sure why the agentUID have disappeared (if it existed from the start) from the config file but it could be that the second instance of the game had some issues with updating it maybe...

Anyhow, now it works as intended. without the code tweak.
thanks again for the awesome addon, trying to manage 2 accounts worth of characters inventory without it would be... more annoying. :-P
