### ISSUE TITLE
Huge Lag when using with skinner

### ISSUE THREAD

**Issue by BruceLiChong** [arkayenro/arkinventory#1354]
**Issue happening on WoW Classic, not retail**

Not sure if anybody had that before, but I didn't find anything about that, but here what is the issue:

I had issues with my bags always makign my game freeze for about 2 seconds when i opened them. The weird part is that it happened on 2 of my accounts, but not on my main one (that part i still haven't figured out why). There is also an additional 5 to 10 seconds lag whenever the game loads, but that part i didn't really care about as it didn't affect my gameplay at all.

After deleting cache and WTF folder it didn't fix it at all, so I deactivated all my addons and re-enabled them one by one until I found the culprit: The "skinner" addon! I know that it might be their part of the codign who is at fault, but I figured that some other people might have had the same issue, so I found how to fix it withotu completly deactivating skinner. Here's how:

1. Go to the skinner addon menu (type /skinner in chat)
2. Expand the Skinenr category in the left menu with the little plus(+) sign
3. Go to disabled skin
4. Check everything Arkinventory related
5. Close the menu and reload your game (type /reload in chat)
6. Profit!

Hope it helps somebody as I struggled over a week with this problem and I almost dropped that magnificent bag addon that Arkinventory is, and I REALLY DIDN'T WANT TO!

**Comment by arkayenro** [comment]
i've updated my mod for shadowlands, as such there is no longer a border frame named "ArkBorder", there is a frame object instead, frame.ArkBorder

they will need to update their code to  work with that

i would have expected you to be getting a lot of errors from that, not lag, not unless youre not displaying the errors

**Comment by arkayenro** [comment]
ive added some code into the latest alpha that should allow for backwards compatibility until they update their side, although if it works then they probably wont bother unless i remove it

**Comment by arkayenro** [comment]
should be fixed in 3.09.36
