### ISSUE TITLE
[Bonus IDs ] What does this option mean

### ISSUE THREAD

**Issue by liule024** [arkayenro/arkinventory#1355]
![asr](https://user-images.githubusercontent.com/70201394/92410563-20af8f00-f177-11ea-8dd1-63f255aa5fec.jpg)
[Item Count]
[Item Suffix]
[Corruption]
What are they referring to?
I do not understand.
in wow classic!

**Comment by liule024** [comment]
> 
> 
> [Item Count]
> [Item Suffix]
> [Corruption]
> What are they referring to?
> I do not understand


![asr](https://user-images.githubusercontent.com/70201394/92410523-f231b400-f176-11ea-9699-ba6c77883ba0.jpg)

**Comment by arkayenro** [comment]
item count - do you want sword of the monkey and sword of the eagle treated as the same item or as different items when i build the item counts

item search - similar to the above but for when the search entries are built.
and if you want to split out corrupted items from their cleansed version (which you can ignore in classic)

**Comment by liule024** [comment]
> 
> 
> item count - do you want sword of the monkey and sword of the eagle treated as the same item or as different items when i build the item counts
> 
> item search - similar to the above but for when the search entries are built.
> and if you want to split out corrupted items from their cleansed version (which you can ignore in classic)

Thank you very much
 i get it
