### ISSUE TITLE
ItemRack and ArkInventory

### ISSUE THREAD

**Issue by fenrisbear** [arkayenro/arkinventory#1357]
Currently, when I swap entire gear with ItemRack, ArkInventory doesn't recognize the change, and not for a long while either. I've tried "Refresh", closing and opening the bag.

I've tried /reload at that seems to work sometimes. It seems very time based that it won't update before x amount of time.

I've also tried the following:
1) Advanced > Update Timers > Backpack > "check" Custom and having seconds at 0.5s.
2) Settings > Window > Style > Sorting > When set to On Window Open.

I've tried disable every addon except ItemRack and ArkInventory as well. Any clues?

**Comment by arkayenro** [comment]
right click on the refresh item and click on the clear item cache entry, that should force a recategorisation.  you could also go into edit mode and back out, that does a recalculation as well.

its probably been updated and i have to update my code to match.  i'll take a look at it

**Comment by arkayenro** [comment]
could you try the [r1020-alpha](https://www.curseforge.com/wow/addons/ark-inventory/files/3054138) and let me know if its working?

**Comment by fenrisbear** [comment]
I did have a look. Both your alphas, the one from yesterday and the new one.

I can't say did what I wanted it to do. However, you mentioning right click, did actually lead me to see that "Refresh: New items" or similiar named menu option did refresh the view as expected. That's a start for me at least.

**Comment by arkayenro** [comment]
i add some outfits in itemrack and its finding the items without any issues?

open the config and go to settings > designs > pick the one your bag is using > window > sorting > when = instant

then open the bag and change sets, does the window refresh?

**Comment by arkayenro** [comment]
do you have a rule that uses outfit( )
is that rule enabled? enable edit mode, click on the bar, assigned categories > rules > find the rule > status should be enabled

in edit mode click on one of the items that should be in the outfit.  are there two categories with the top one in green?  is it your outfit rule or another rule?

if its another rule then you need to change the order number of your outfit rule to be lower than the other rule so that it gets processed before it

**Comment by arkayenro** [comment]
saving/deleting sets doesnt currently trigger a recalculation, that will be fixed in the next alpha

**Comment by arkayenro** [comment]
fixed in 3.09.36
