### ISSUE TITLE
Sell function of the Scrap addon is being triggered on login

### ISSUE THREAD

**Issue by the-chuppa** [arkayenro/arkinventory#1359]
Hello, please remove **OptionalDeps: Scrap_Merchant** in **ArkInvetory\ArkInvetory.toc**. This part of the Scrap addon is supposed to be loaded only when interacting with a vendor. However by being a depdendency, it is being loaded on login or ui reload, triggering the sell function which - without a vendor to sell to - equips any gray items in the inventory.

**Comment by arkayenro** [comment]
not sure why i made that a opt-dep but i couldn't find any code that actually required it so it will be removed in the next release

**Comment by arkayenro** [comment]
fixed in 3.09.36
