### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by pcangelnc** [arkayenro/arkinventory#1360]
Just got this 
![image](https://user-images.githubusercontent.com/39198694/93157283-e9d9fb80-f6d7-11ea-8b16-e8190f0bec58.png)

vers. 3.09.36

**Comment by arkayenro** [comment]
odd, that tooltip type should work as it should always be an item.

do you remember what you were looting at the time?

**Comment by pcangelnc** [comment]
Yes the item above, the archaeology fragments

**Comment by arkayenro** [comment]
i cant reproduce it but i've added in some code that will stop it if it happens to others

**Comment by pcangelnc** [comment]
Well hopefully it was a fluke then, thanks for taking a look!

**Comment by pcangelnc** [comment]
Just got it again.  Had just looted Magmadar in Molten Core.
![image](https://user-images.githubusercontent.com/39198694/93262230-e1ce9a00-f771-11ea-9eab-10d799981e42.png)

**Comment by arkayenro** [comment]
should be fixed in 3.09.37

**Comment by pcangelnc** [comment]
![image](https://user-images.githubusercontent.com/39198694/93692008-73644180-fabb-11ea-9475-8bab8baf6f05.png)
Got when using Auto Hammer  3.09.37

**Comment by arkayenro** [comment]
thanks, will be fixed in the next alpha/release

**Comment by arkayenro** [comment]
fixed in 3.09.39
