### ISSUE TITLE
Issues with the ItemRack / outfit("xyz") rule

### ISSUE THREAD

**Issue by ollema** [arkayenro/arkinventory#1361]
Hey!

Thanks for a great addon.

In classic, the outfit("xyz") rule is working great for me - except for one item in a particular set.

The other items in that ItemRack set is working fine - but Onyxia Scale Cloak for some reason is not working.

Here are some screenshots to clarify:

**ItemRack set "FR" with 4 items - Onyxia Scale Cloak (not working), Molten Helm, Volcanic Leggins and Onyxia Tooth Pendant**
![WoWScrnShot_091520_022512](https://user-images.githubusercontent.com/31876997/93198461-5b07c600-f74d-11ea-91cf-e58b440dcb73.jpg)

**outfit("FR") rule**
![WoWScrnShot_091520_022454](https://user-images.githubusercontent.com/31876997/93198563-7bd01b80-f74d-11ea-917f-1985e9e122b9.jpg)

**Some items like Molten Helm are picked up and assigned according to the outfit("FR") rule**
![WoWScrnShot_091520_022438](https://user-images.githubusercontent.com/31876997/93198639-999d8080-f74d-11ea-8af0-6929adc10e07.jpg)

**But as you can see, only 3 out of 4 items in the set are assigned to the correct bar - the cloak is not working**
![WoWScrnShot_091520_0224382](https://user-images.githubusercontent.com/31876997/93198725-b5a12200-f74d-11ea-8e44-b38e05de4af9.jpg)

Let me know if I can provide additional information

**Comment by arkayenro** [comment]
it was working in retail but i know there a difference between classic and retail for the itemlinks that i thought was catered for.

servers are down at the moment, can you open your ItemRack.lua saved variables and see if you can find the set in there?  then paste it in here.  mostly i want to double check the itemlinks being saved vs what im checking for in rules

**Comment by arkayenro** [comment]
also, just to make sure, go into edit mode and click on the onyxia cloak, make sure its not being picked up by another rule

**Comment by ollema** [comment]
sorry for the delay @arkayenro 

here is the relevant saved variable:
```lua
ItemRackUser = {
...
	["Sets"] = {
		["FR"] = {
			["ShowHelm"] = 1,
			["equip"] = {
				"16983:1505:::::::60:::::::", -- [1]
				"18404::::::::60:::11::::", -- [2]
				[7] = "15054:1505:::::::60:::::::",
				[15] = "15138:2463:::::::60:::::::",
			},
			["ShowCloak"] = 1,
			["icon"] = 135805,
			["old"] = {
			},
		},
...
```
guessing `[15] = "15138:2463:::::::60:::::::"` is the cloak?
 
if so - it does look like the itemlinks are not matching!
![WoWScrnShot_092020_003928](https://user-images.githubusercontent.com/31876997/93690557-ec729180-fad9-11ea-86bf-f2c5936f288d.jpg)

**Comment by ollema** [comment]
hmm, did some more research.

it looks like the difference is the enchant on the cloak.

Enchant Item: +15 Fire Resistance (2619)
vs
Enchant Item: +7 Fire Resistance (2463)

2619 is the enchant I am using but so ArkInventory is correct.

for some reason, ItemRack was working fine _despite_ having the old enchant saved (2463)

so it's probably safe to close this - the problem was ItemRack all along

**Comment by arkayenro** [comment]
itemrack may not care about the enchant to load the set onto the player but it might care for matching purposes.

if you update the set then AI should pick it up again once it matches
