### ISSUE TITLE
vers. 3.09.37 cannot load.

### ISSUE THREAD

**Issue by Nitti2909** [arkayenro/arkinventory#1364]
After updating from 3.09.36 to 3.09.37 this morning, i got a Lua error that i cant reproduce and Arkinventory didnt load, now i get the following error in chat:
"failsafe kicked in - aborting arkinventory translations due to an error of some sort"

After a rollback to 3.09.36 everything works fine again.

**Comment by arkayenro** [comment]
classic?  there was a problem with code that doesnt work in classic that does in retail (and it was so basic i didnt double check)

**Comment by Nitti2909** [comment]
Sorry, yeah in Classic...

**Comment by arkayenro** [comment]
should be fixed in 3.09.38

**Comment by Nitti2909** [comment]
Thx m8, ill try it out... 
And from a user who has been using this addon since 2006, i just wanted to tell that i think your doing a damn fine job m8:-)
