### ISSUE TITLE
Can't Toggle Currency Window With Hotkey

### ISSUE THREAD

**Issue by Eincrou** [arkayenro/arkinventory#1365]
ArkInventory 3.09.37 - WoW Retail

A few days ago (I don't remember which version I was using, sorry!), my hotkey for displaying the Currencies window stopped working.  Instead of bring up my currencies, it throws the error below.  I'm able to access the currencies window by opening the regular bag window and using the "Toggle Location" menu.

The other windows I have bound to hotkeys, Bag, Bank, Guild Bank and Void Storage all still work properly.

```
3x ArkInventory\ArkInventory-30937.lua:4840: bad argument #3 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@ArkInventory\ArkInventory-30937.lua"]:4840: in function `Frame_Main_Get'
[string "@ArkInventory\ArkInventory-30937.lua"]:5582: in function `Frame_Main_Toggle'
[string "ARKINV_TOGGLE_TOKEN"]:1: in function <[string "ARKINV_TOGGLE_TOKEN"]:1>

Locals:
(*temporary) = "%s%s"
(*temporary) = "ARKINV_Frame"
(*temporary) = nil
(*temporary) = "string expected, got nil"
```

![image](https://user-images.githubusercontent.com/8196586/93521576-43237400-f8fe-11ea-97b4-d6b3eb5641bc.png)

**Comment by arkayenro** [comment]
fixed in 3.09.39
