### ISSUE TITLE
Tint Unusable Not Tinting

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1366]
I'm on a level 1 bank toon on Classic, and everything shows up as not tinted.

![image](https://user-images.githubusercontent.com/55365231/93537385-f5fccd80-f910-11ea-9016-6c204b72de01.png)

**Comment by arkayenro** [comment]
somethings gone weird with it, i've got a recipe thats tinted but items that need level 90 are not.

i'll see if i can work out whats going on

**Comment by arkayenro** [comment]
yep, thats me screwing up a variable name. will be fixed in the next release

**Comment by teelolws** [comment]
Someone made a ticket on my addon about this, for some reason: https://github.com/teelolws/Altoholic-Classic/issues/67

**Comment by arkayenro** [comment]
fixed in 3.09.39
