### ISSUE TITLE
A function named TooltipGetHyperlinkFromSetAuctionSellItem needs to be created

### ISSUE THREAD

**Issue by the-chuppa** [arkayenro/arkinventory#1367]
Hey,

while posting auctions (5 auctions of 2 out of a stack of 11 if it's any help) through Auctionator I got this message in chat:

ArkInventory: WARNING> Code Error: A function named TooltipGetHyperlinkFromSetAuctionSellItem needs to be created to allow item counts to update for this object type.  Please let the author know.   The warning for this function will occur once per session.

WoW Classic 1.13.5
Auctionator (I'm guessing a quickfix version from 03-11-20 09:12 AM, I now updated it just in case)
ArkInventory 3.09.36-Classic

**Comment by arkayenro** [comment]
thanks, will be fixed in the next alpha/release

**Comment by arkayenro** [comment]
fixed in 3.09.39
