### ISSUE TITLE
Code Error: TooltipGetHyperlinkFromSetBuybackItem

### ISSUE THREAD

**Issue by Justicova** [arkayenro/arkinventory#1368]
![image](https://user-images.githubusercontent.com/3710301/93924538-dedc2800-fce2-11ea-9f4b-a9474912d86c.png)

I got this when opening the Auction House today

**Comment by arkayenro** [comment]
fixed in the last alpha, so will be in the next release

**Comment by arkayenro** [comment]
fixed in 3.09.39
