### ISSUE TITLE
Soulbound Items classified as junk

### ISSUE THREAD

**Issue by pcangelnc** [arkayenro/arkinventory#1370]
Happened multiple times today after upgrading to 3.09.39.  Soulbound loot drop items going into my Junk folder.    It may be a wow issue but if so would have to be very recent as I farm these particular instances every week on multiple toons so unlikely I've never gotten the items before.
![image](https://user-images.githubusercontent.com/39198694/94181355-5e95fe00-fe6d-11ea-91d5-8cc353d04306.png)

**Comment by arkayenro** [comment]
unusable soulbound items are categorised as junk, unless you can use it for transmog, but the unusable code had a bug where it would incorrectly return "usable" that i only fixed in the last release

what would you normally do with those items?

**Comment by pcangelnc** [comment]
Well that explains the change.  I'm just not used to seeing gear show up with grey items, even if unusable.  These were going into my Soulbound folder, but this may be a better option once I get used to the change.  Have to think about it. Thanks for the quick response!

**Comment by arkayenro** [comment]
well leather is technically usable by a warrior but i checked that sky strider belt and its plate so it shouldnt have been set as junk so something is weird

open the config and go to settings > designs > the one youre using > items > general > tint unusable = ticked

is the item tinted red?  is there any red text in the item tooltip?

its possible the is-usable code is broken somehow but it seemed to be working ok

**Comment by arkayenro** [comment]
if the item is equipment, is soulbound, and has red text in the tooltip (with some exceptions), then its considered junk

**Comment by pcangelnc** [comment]
Sorry the screenshot I posted was from a different toon, not the warrior. I've sold and switched toons now from the warrior.  Next time I run an instance I'll do as you suggest and let you know.

**Comment by acemodder** [comment]
Is there anyway to change this back?   I hate this classification now for soulbound items.

**Comment by pcangelnc** [comment]
> Is there anyway to change this back? I hate this classification now for soulbound items.

I have to agree. 

After some more instances, it is as you suggested: the warrior "can" equip cloth/leather/mail so they go in soulbound but say wands go in junk, it very confusing as loot goes multiple places.

**Comment by arkayenro** [comment]
next alpha/release will have options to turn them off

**Comment by Incandio** [comment]
Quite got used to this setting, especially as it makes auto-selling easier (I don't know how many Rings of the Kirin Tor I've accidentally sold after running an instance). Artifacts for another spec are categorised as Junk though, which is a bit... sad face.

**Comment by arkayenro** [comment]
i know, but you can always hardcode the special (to you) items to equipment > soulbound, or more preferably a custom category

i have a couple of custom categories i assign items to so that they dont ever get auto sold

**Comment by Incandio** [comment]
Actually, I meant it was ME selling the Ring, not the addon. Having the addon do it is more reliable!

**Comment by acemodder** [comment]
> next alpha/release will have options to turn them off

Thank you very much, appreciated.
