### ISSUE TITLE
Currency values show as 'nil' when inventory opened, but shown correctly in tool tip when moused over

### ISSUE THREAD

**Issue by Tetsemi** [arkayenro/arkinventory#1371]
Retail WoW - 8.3.7.35662
ArkInventory Version - 3.09.39 (Release)

When you open the currency tab on your character and click on a currency to track it so you can see it when you open your inventory, prior to this ArkInventory version, it would show the values of the currency as well as show it when you moused over the value.  Now it is showing a value of 'nil' but still showing correct information in the tool tip when moused over.

**Comment by arkayenro** [comment]
try the latest alpha, i think its fixed in that

**Comment by Tetsemi** [comment]
Can confirm, r1044-alpha does fix the issue.
