### ISSUE TITLE
Profession scanning

### ISSUE THREAD

**Issue by Incandio** [arkayenro/arkinventory#1373]
Hi again, in the latest Alpha 3.09.40 (Alpha 1) the Profession tab in General Settings has gone. I always disabled this feature - now I'm getting the behavior I used to get when it was enabled to one of my professions, ie Runecloth and Rugged Leather are thrown into my Engineering bar instead of my Trade Goods Cloth / Leather bars, things like that.

EDIT: sorry, I see the toggle has been moved to the General > Profiles > Control section under Professions.

**Comment by arkayenro** [comment]
just to confirm, i thought i only moved its location in the config, did the value reset for you?

(it shouldnt have so if it did i need to fix that)

**Comment by Incandio** [comment]
Ha, ever vigilant! No, I hadn't logged into the toon in a while, so I think it just hadn't been toggled off, as it's on by default if I recall. The setting hasn't changed on other toons.

**Comment by arkayenro** [comment]
great, thanks.
