### ISSUE TITLE
problem with ingame dropdowns

### ISSUE THREAD

**Issue by IchAGTed** [arkayenro/arkinventory#1374]
Hi, I have the following problem. By using the current version 3.09.39, I can no longer use the drop-down menus of the game without any problems. These close by themselves within a time window of approx. 2 seconds. The problem disappears when the add-on is deactivated.

**Comment by arkayenro** [comment]
i think i found a possible cause, will be fixed (if this was the cause) in the next alpha/release

**Comment by IchAGTed** [comment]
Fixed. Thanks a lot.
