### ISSUE TITLE
ArkInventoryTradeskill.lua:340 error each time on a start

### ISSUE THREAD

**Issue by epigramx** [arkayenro/arkinventory#1376]
It can't be corrupted files because I have redownloaded them 10 times. IIRC it did go way when I had tried an alpha version (which was slightly older than the main one).

Error 1:

`Message: ...rface\AddOns\ArkInventory\ArkInventoryTradeskill.lua:340: attempt to index field 'data' (a nil value)
Time: Mon Sep 28 07:49:22 2020
Count: 1
Stack: ...rface\AddOns\ArkInventory\ArkInventoryTradeskill.lua:340: attempt to index field 'data' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ArkInventory\ArkInventoryTradeskill.lua"]:340: in function `ScanHeaders'
[string "@Interface\AddOns\ArkInventory\ArkInventory.lua"]:3186: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:3078>
[string "=[C]"]: ?
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:70: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:630: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\PetTracker\addons\main\main.lua"]:46: in function `?'
[string "@Interface\AddOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua"]:20: in function <...dOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
[string "@Interface\AddOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua"]:56: in function <...dOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface\AddOns\AngryAssignments\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\AngryAssignments\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\AngryAssignments\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\AngryAssignments\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:457: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:580: in function `TimeManager_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1267: in function <Interface\FrameXML\UIParent.lua:1164>

Locals: <none>
`

Error 2: 

`Message: ...rface\AddOns\ArkInventory\ArkInventoryTradeskill.lua:340: attempt to index field 'data' (a nil value)
Time: Thu Oct  1 15:13:39 2020
Count: 1
Stack: ...rface\AddOns\ArkInventory\ArkInventoryTradeskill.lua:340: attempt to index field 'data' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\ArkInventory\ArkInventoryTradeskill.lua"]:340: in function `ScanHeaders'
[string "@Interface\AddOns\ArkInventory\ArkInventoryTranslate.lua"]:427: in function <...erface\AddOns\ArkInventory\ArkInventoryTranslate.lua:362>

Locals: `

**Comment by arkayenro** [comment]
i think thats fixed in one of the latest alphas

**Comment by epigramx** [comment]
@arkayenro Which one? The ones later than the stable release are for 9.x and those don't even work.

**Comment by SpiritWolfie** [comment]
Having same issue too and was wondering about it.

**Comment by arkayenro** [comment]
@SpiritWolfie download one of the latest alpha, its fixed in there (they work in all versions)

**Comment by arkayenro** [comment]
fixed in 30940.1
