### ISSUE TITLE
Junk category when looking at alts

### ISSUE THREAD

**Issue by the-chuppa** [arkayenro/arkinventory#1378]
When browsing the bank of other characters, their equipment is categorized as junk based on the character I am on instead of the character I am looking at. This makes sense since you can't possibly track learned armor or weapon specializations of all the characters. However, shouldn't this junk categorization of common+ gear be disabled when looking at alts since it's not accurate?

**Comment by arkayenro** [comment]
thanks, i'll disable that in offline mode
