### ISSUE TITLE
One character is categorizing items incorrectly

### ISSUE THREAD

**Issue by groosalug** [arkayenro/arkinventory#1380]
I have a lot of alts and all use the same profile. However just 1 seems to have items listed in the wrong category by default. 

For example Primordial Saronite is set as crafting reagent by default for all other characters. For this one it is set as skill > tailoring as the default. Any idea why this would be? Is there any additional information I can offer to help figure this out.

**Comment by arkayenro** [comment]
that character will have the tailoring skill
under general > profiles (any profile) > controls > profession - set the priority to none

its a per character option if you want crafting mats assigned to one of your skills or just left as crafting mats

**Comment by groosalug** [comment]
Thank you! I didn't even think of this since another character had tailoring and it wasn't happening. It turns out I had it set to alchemy (which this character also has) and it was the cause. All good now.
