### ISSUE TITLE
ArkInventoryStorage.lua:373 error every time it enters combat on latest retail/alpha

### ISSUE THREAD

**Issue by epigramx** [arkayenro/arkinventory#1382]
Message: ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:373: attempt to call method 'EVENT_ARKINV_TOOLTIP_REBUILD_QUEUE_UPDATE' (a nil value)
Time: Sun Oct 11 22:21:47 2020
Count: 5
Stack: ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:373: attempt to call method 'EVENT_ARKINV_TOOLTIP_REBUILD_QUEUE_UPDATE' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ArkInventory\ArkInventoryStorage.lua"]:373: in function `?'
[string "@Interface\AddOns\TradeSkillMaster\External\EmbeddedLibs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ddedLibs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\TradeSkillMaster\External\EmbeddedLibs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ddedLibs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\TradeSkillMaster\External\EmbeddedLibs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceEvent\AceEvent-3.0.lua"]:120: in function <...rkInventory\Externals\Ace3\AceEvent\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by arkayenro** [comment]
what version are you running?

**Comment by epigramx** [comment]
Twitch is horrible, it went away, after I reinstalled latest version which should be supposedly autoupdated.
