### ISSUE TITLE
items incorrectly have the wrong expansion

### ISSUE THREAD

**Issue by ncplus0** [arkayenro/arkinventory#1384]
![Untitled](https://user-images.githubusercontent.com/72767232/95791107-8e9c2880-0cd8-11eb-987f-7075b1a6852b.jpg)
as you can see in the print screen i have created a rule for ore of the classic expansion but items from other one got into the tab, when i debug it it as classic selected when it's a different one

**Comment by arkayenro** [comment]
expansion is a blizzard value, i dont change it.  i dont think they bothered setting it on anything that existed before they made it available.
