### ISSUE TITLE
Reversed Item Name Sorting Doesn't Appear To Work

### ISSUE THREAD

**Issue by DigitlWorld** [arkayenro/arkinventory#1385]
I've tried setting up a sorting method that has `item name` checked, at the top and also with `Use reversed names` checked. The rest of the sorting method works as intended, and the `Descending` option works as expected, but the `Use reversed names` option appears to do nothing.

I know this is actually implemented in the code, as commenting out the `if v.reversed then/end` around `t = ArkInventory.ReverseName( t )` where the reversing is applied (ArkInventory.lua, 3.09.27 Line 3257) causes the sorting to work as expected, but now all sorting is with reverse names. This is still broken in 3.09.41.

I suspect something gets lost between the configuration screen and whatever table `v` is in that context, but I'm not familiar enough with this code base or the libraries to figure it out and provide an exact suggestion.

Let me know if you need any more information.

**Comment by arkayenro** [comment]
sorry, i think i completely missed that when i rebuilt the sort order methods.

it should be checking `v.order[p].reversed`

**Comment by DigitlWorld** [comment]
Can confirm that does fix it. No sorrys needed! Thanks!

**Comment by arkayenro** [comment]
fixed in 3.09.42
