### ISSUE TITLE
Empty search field

### ISSUE THREAD

**Issue by Tedifa** [arkayenro/arkinventory#1389]
Hi !

I have a problem with the search which helped me a lot before.
I have many alts and it earned me a lot of time to search in this field without logging all these alts.

Does anybidy else has this trouble and knows how to fix it ?

Thx

**Comment by arkayenro** [comment]
give it time.  the search was made threaded so that it wouldnt lock up the game for people that had lots of alts.  it means that it may take a while to load the search contents but at least the game is still playable while its doing it

**Comment by Tedifa** [comment]
![WoWScrnShot_101520_165457](https://user-images.githubusercontent.com/72877319/96147100-46af1880-0f07-11eb-858e-54f61b2c1b6a.jpg)
Waited for an hour and nothing happened.
Still love your add-on and waiting for this search field <3

**Comment by arkayenro** [comment]
are you running 3.09.41?

**Comment by Tedifa** [comment]
Now i have 3.09.42 and same problem

**Comment by arkayenro** [comment]
the only other reason would be an error in the code, most likely caused by bad data, is killing it but as its threaded it may not show

can you go into config > advanced > threads > debug and enable that

then open your bag, then open the search.

is the search thread still running after 30 seconds or has it stopped?

**Comment by Tedifa** [comment]
![WoWScrnShot_101820_134532](https://user-images.githubusercontent.com/72877319/96366510-43ef3600-1148-11eb-80a8-ef71fa9a1242.jpg)

Still trying to work after 30+ seconds with this message p06-search suspended after 12.50ms

**Comment by arkayenro** [comment]
there must be something bad in the saved data for one of your characters, are you able to send me your arkinventory.lua saved variables file?

**Comment by Tedifa** [comment]
I sent mail

**Comment by arkayenro** [comment]
Kael'thas - Alliance - Mage - Elfe du Vide

i think it has gold in its mailbox and the search is barfing on that.  i've updated the code so it wont barf on sent gold and in the mean time if you pickup the gold out of the mailbox the search should work again

**Comment by Tedifa** [comment]
It worked !
Although there was nothing left in my box, I opened it and miraculously the search field full filled.

Thx a lot, I can go peacefully to the shadowlands
