### ISSUE TITLE
Currencies missing in the inventory

### ISSUE THREAD

**Issue by michel-bosseaux** [arkayenro/arkinventory#1390]
Since 9.0.1, the currencies are not displayed in the inventory.

**Comment by arkayenro** [comment]
in what way?

**Comment by arkayenro** [comment]
nvm, figured out you mean the backpack tokens.

looks like blizzard changed one of the returns.  will be fixed in the next alpha/release

**Comment by arkayenro** [comment]
fixed in 3.09.42
