### ISSUE TITLE
Currency LDB display not showing

### ISSUE THREAD

**Issue by Kirbdawg** [arkayenro/arkinventory#1393]
I see the default AI icon in the LDB display, but the currencies I have selected don't actually show until I add or remove one from the display.

This is low priority but wanted to make you aware of it.   You've fixed this for me before.   Not everyone uses this feature so you can stick it on the bottom of you're fix-it list.

I'm using a hacked version of Bazooka for the LDB right now due to prepatch but it was broken long before the prepatch was released... more than a month.

**Comment by arkayenro** [comment]
make sure youve updated.  there was an issue previously where that would happen, and it will also happen if you are not monitoring the currency location (although i think the tooltip says that if you arent)

**Comment by Kirbdawg** [comment]
I have 3.09.42.  I just logged in for the first time today and the issue persist.  Below is a screenshot.  Right next to is is AI Tracking and it IS working.   

https://1drv.ms/u/s!An-FrMdeI_10gZEJ291gkoHk_sncYw?e=PuqtVb

**Comment by arkayenro** [comment]
right click on the object and make sure that the include in text option is enabled for each currency you want on the bar.  i presume they all have include in tooltip enabled as they are showing there

**Comment by Kirbdawg** [comment]
Yup.  Everyone of them has the text option checked.

However...
I didn't understand what the "Unused" option was for.  After a couple items disappeared, I realized it had to do with the Unused section on Blizzard's currency pane.   I made the mistake of clicking "LDB_CURRENCY_REACTIVATE_ALL" thinking it would move them out of Blizzard's Unused section but instead it moved a lot of currencies INTO the Blizzard's Unused currency pane.   Not sure if that's the expected behavior or not.   Anyway, I moved them all out of Unused using Bliz's currency pane.  Then, I noticed that there were still several items in AI's properties that show "Unused" still checked.  I'm not sure if this is expected behavior or not either.   See screenshot below.

https://1drv.ms/u/s!An-FrMdeI_10gZEKA3lTnGBv3qnXpg?e=7my4Sg

**Comment by arkayenro** [comment]
there also seems to be an isuse with one of the returns, the one that is supposed to let you know if the currency is unused or not.  seems its not set properly for the headers so its screwing it up.

should be fixed next alpha/release and i'll probably hide that reactivate option, cant seem to get it to work properly anyway

**Comment by Kirbdawg** [comment]
OK, all good.  Ty vm.
