### ISSUE TITLE
Request for "Tradable" as a System Category of Items

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1394]
Like Soulbound, possible to group the items that are still Tradable?

I run GDKP groups, and I get a full raid worth of junk in my bags at once. I have it set to sort by age... sort of works, but fills up with a bunch of clutter too. Love it if I could just see the items that I can still trade all in one spot, without the clutter.

**Comment by arkayenro** [comment]
added in 3.09.45

**Comment by Gogo1951** [comment]
Thank you!
