### ISSUE TITLE
Error with Pre-patch

### ISSUE THREAD

**Issue by Mythris29** [arkayenro/arkinventory#1398]
I'm not 100% sure what triggered this but I ran into this error today

2x [ADDON_ACTION_BLOCKED] AddOn 'ArkInventory' tried to call the protected function 'MultiBarBottomRightButton1:Hide()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Hide'
[string "@FrameXML\ActionButton.lua"]:501: in function `ActionButton_HideGrid'
[string "@FrameXML\MultiActionBars.lua"]:139: in function `MultiActionBar_UpdateGrid'
[string "@FrameXML\MultiActionBars.lua"]:121: in function `MultiActionBar_ShowAllGrids'
[string "@FrameXML\SpellBookFrame.lua"]:196: in function <FrameXML\SpellBookFrame.lua:187>
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2739: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2584: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2452: in function <FrameXML\UIParent.lua:2448>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3306: in function <FrameXML\UIParent.lua:3289>
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\SpellBookFrame.lua"]:72: in function `ToggleSpellBook'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

**Comment by arkayenro** [comment]
youd have to look for the cause of the taint - see https://github.com/arkayenro/arkinventory/wiki/Taint-and-ADDON_ACTION_BLOCKED
