### ISSUE TITLE
An old config file will not load

### ISSUE THREAD

**Issue by MonkeyGoneWIld** [arkayenro/arkinventory#1399]
I stopped playing WoW for a couple months but I did backed up my ArkInventory.lua file.
It was backed up on version 3.09.22 but it refuses on the current version anymore.

Is there any way to make my old config file work on the current version of wow?
I spent so much time configuring it, it would be a shame if it all went to waste.

**Comment by arkayenro** [comment]
do you get any errors?

**Comment by MonkeyGoneWIld** [comment]
I was initially trying it on a different account and it would refuse to load, but it seems to work perfectly on my original account. 
The new ArkInventory.lua file seems to work on other account too.
