### ISSUE TITLE
Exile's Reach Tutorial stuck

### ISSUE THREAD

**Issue by the-chuppa** [arkayenro/arkinventory#1402]
When starting a new character in Exile's Reach, there is a tutorial that needs you to open the inventory. Opening the ArkInventory does not trigger the tutorial completion however. I had to disable the addon and open the blizzard default bag to proceed.

**Comment by arkayenro** [comment]
it probably wants the actual default bag window opened, which AI is designed to replace, so youd have to temporarily disable AI like you did, or disable override for the backpack location.

manually disabling all of AI is probably the simplest option

**Comment by the-chuppa** [comment]
Yeah those tutorials are pretty wonky. For each and every item you get there, the same tutorial pops up to equip it.

Well once you do it a few times or disable tutorials in the interface options, you never see it again so it's probably not worth "fixing", if it's even possible.
