### ISSUE TITLE
ArkDewdrop  - frame name incorrect

### ISSUE THREAD

**Issue by jncl** [arkayenro/arkinventory#1403]
Hi,

  I've noticed that the frame name generated in the AcquireLevel function is incorrect.

  On line 847 in ArkDewdrop.lua the string format for the frame name is given four parameters instead of three, the third is numButtons but it should be numLevels, which is the fourth parameter.

  I'm happy to fork the repo and push a change if you accept them.

Cheers
  Jon

**Comment by arkayenro** [comment]
thats some mucked up code. im not actually sure yet if if should use `numLevels` or just `i` for the frame name.

realistically if the name isnt used anywhere it would be better to not give it one in the first place (then theres zero chance of it duplicating the name)

**Comment by arkayenro** [comment]
doesnt look like the frame name is ever used (for either button or level) so removing it seems like the better option

**Comment by arkayenro** [comment]
was it causing an issue of some sort?
