### ISSUE TITLE
Configuration wiped

### ISSUE THREAD

**Issue by thenoid** [arkayenro/arkinventory#1404]
I logged in for the first time in a week or so, after updating my addons, and all configuration has been wiped, prefences, rules, arrangments, everything!

Help?  I don't see any other closed issues for this, couldn't find it in the wiki or FAQ

**Comment by arkayenro** [comment]
check if the games own backup of the saved variables file is ok
`...\World of Warcraft\_client_\WTF\Account\yourwowaccountname\SavedVariables\ArkInventory.lua.bak`

restore from your own backup

those are really the only two options if something happens to your saved variables file

**Comment by thenoid** [comment]
the .bak wasn't, and the hourly backups, even dailies weren't.  I went WAY back to september 15th (random date) and apparently that one was viable.

Sorry for the fire drill, I did try backups first before posting.
