### ISSUE TITLE
Bar Names - don't show

### ISSUE THREAD

**Issue by Tappinator9** [arkayenro/arkinventory#1407]
Hi, I've edited the bar names, but they only show in edit mode, not when the bag is displayed normally. Is there an option I am missing somewhere please?
Thanks!

**Comment by arkayenro** [comment]
settings > design > your active design > bars > style > name

**Comment by Jorhall** [comment]
I have had this problem for years and years (since some upgrade in... Dreanor?). I have given up - but do miss the bar names, they where very handy.

**Comment by arkayenro** [comment]
bar names were disabled by default back in 2010 (if you didnt use them they took ups space for no reason) but the option to enable/disable them has always been there, you just have to turn it on

**Comment by Jorhall** [comment]
I love this addon, can't remember how long I have used it - but bra labels doesn't work (we talked a lot about this some years ago). If I ever find out why it doesn't work for me - I will tell you. :-)

Settings > Design > Bars > Style > Name >> "Enabled" are ticked. Position = Top. Alignment = Default. Font Size = 10
