### ISSUE TITLE
Restacking with bank open

### ISSUE THREAD

**Issue by krijos** [arkayenro/arkinventory#1410]
When using the restack function with the bank open arkinventory moves items from my inventory to max out stack sizes in the bank, leaving me with incomplete consumable stacks in my inventory. Is this the intended behavior? If so, what could be potential common user errors on my part?

**Comment by arkayenro** [comment]
its the default behaviour.

right click on the restack icon and youll see the options you can change under there

by the sounds of it youll most likely want to disable the topup option, but there are others in there that you might want to change as well

**Comment by krijos** [comment]
Thank you so much! The addon is so well written I felt like that could not have been an oversight. Thank you for your work and support! :)
