### ISSUE TITLE
Bound rules are broken

### ISSUE THREAD

**Issue by Tireniel** [arkayenro/arkinventory#1411]
I have used your addon since you first made it and love this addon. But when I updated to the latest version all my armor rules broke. I have them separated by expansion and by how it is bound my code is:
type("armor") and subtype("cloth") and bound("0") and expansion("Classic")
it is returning the error:
...erface\addons\ArkinventoryRules\ArkinventoryRules.lua:238: Bound(...).argument 1 is not a number
so I was wondering if they changed something in the Blizz code or if you disabled this function or if you have a possible workaround as I love separating my gear like this to make it easy to find stuff.

**Comment by arkayenro** [comment]
bound take a number and "0" is a string, just use 0 and it should work

**Comment by Tireniel** [comment]
Thank you that seems to have fixed my issue.
