### ISSUE TITLE
Learned toys as "links" in the inventory?

### ISSUE THREAD

**Issue by Cren-Verdis** [arkayenro/arkinventory#1416]
Copy pasted my comment, because Curseforge throws 500ers the last couple of days.

> Hey Arkayenro!
> 
> Long long long long time user and huge fan! Thanks for all the work over the years! (Seriously I'd probably stop playing if ArkInventory would be abandoned)
> 
> 
> Now I've looked up the wiki and couldn't find it but I thought I had read about this feature previously a time back. **Is it possible to set owned and learned toys into a category?** Reason behind this is I want to add the hearthstone like toys to my bags so I have all my teleports in one category. Also I'd like to add the engi teleporters but with a rule to only display them when the character is able to use them. Any chances?

**Comment by arkayenro** [comment]
i presume you mean toys that are items, and not actual toys that end up in the toys location?

toys (even items ones) have category you could use, or you can create a custom category (i use one for hearths/teleports) and assign specific toys/items to them

you could also potentially use a rule to collect them `pt("ArkInventory.System.Toy") and usable()` - i havent tried it so it might not work

**Comment by Cren-Verdis** [comment]
Here is what I want to do: I want to link the toy in my toy location (left side) to my regular inventory. In the screenshot you can see in the default location the new category I did for teleport. I can assign it to the toy hearthstone but it will just sort it in the toy window and not link it to the inventory. Is that one possible?
It would be like adding a placeholder instead of an actual inventory slot, which uses the toy in the toy box location.

![WoWScrnShot_122720_133710](https://user-images.githubusercontent.com/11927169/103170988-cf6ffc00-4848-11eb-997a-d6dd28d143d2.jpg)

**Comment by arkayenro** [comment]
sorry, no, that wont work

you can assign the hearth / teleport toys you want their own custom category so they can be assigned to their own bar in the toy window, but they cant exist in the bag window

**Comment by Cren-Verdis** [comment]
Ah thanks. The default toy box is a mess (especially searching something other than by name) and I thought I could circumvent it with AI. Didn't know/realise they were protected type. Thank you for your quick response as always and I hope you have a Happy New Year! :)
