### ISSUE TITLE
Exclusion List

### ISSUE THREAD

**Issue by NudeSocks** [arkayenro/arkinventory#1417]
**Exclusion List** 
A list the prevents Auto sell or manual selling of items w/o warning. 

Example. Fishing gear. manual add items to a list. Auto sell will exclude any item from the "exclusion list", If you try to manual sell this item a popup asking if you are sure you want to sell this item.

**Comment by pcangelnc** [comment]
With Blizzard starting to fine "uses" for more and more grey items, like currency for a few battle pets in 9.1, this would be a very handy feature.   Auto selling greys is so handy but a way to blacklist some would be so very nice.  I understand Adibags has this already, but I love my Arkinventory too much to change.

**Comment by arkayenro** [comment]
stopping auto sell is simple enough, manually assign the grey items you want to keep to their own custom category so they are no longer part of the auto sell trash category

interrupting manual sales is a bit more problematical

if a grey becomes an actual currency i'll probably assign it to that system category

**Comment by pcangelnc** [comment]
On the ptr, several grey items are used to purchase some of the new battle pets.  Here's the list:
Trash List and Wowhead Links 
Rabbit's Foot https://www.wowhead.com/item=3300/​
Large Slimy Bones https://www.wowhead.com/item=3670/​
A Frayed Knot https://www.wowhead.com/item=6150/​
Rotting Bear Carcass https://www.wowhead.com/item=11406/​
Dark Iron Baby Booties https://www.wowhead.com/item=11944/​
The Stoppable Force https://www.wowhead.com/item=25402/​
Ground Gear https://www.wowhead.com/item=36812/​
Robble's Wobbly Staff https://www.wowhead.com/item=62072/​
Very Unlucky Rock https://www.wowhead.com/item=67410/

Additionally, 4 grey items are used to obtain the Secret item, Waist of Time.  While not currency per se, still was a pain while going thru the steps to get the item as I kept selling them.  Being able to prevent their sale is handy.

**Comment by MrUzagi** [comment]
I frequently use custom categories to exclude things, not just greys, from other categories. For Waist of Time and other similar situations I use the Custom Category "Useful Trash".  Works a treat, and I can put them on their own bar so I get reminded that they are there. 

After I'm done I just removed them from that category and needn't bother with them again.

**Comment by pcangelnc** [comment]
Is there a way to do this with an item id, rather than having to have the item in the bags?  For Waist of Time items, it would be easy to mark as purchased.  But for drop items, it would be nice to have them set side in advance and not have to scrutinize all greys before selling.

**Comment by MrUzagi** [comment]
With a rule you could. But not in a way like right clicking an item and assigning it a category, I don't think.

**Comment by arkayenro** [comment]
next version will allow you to manage the items in the custom categories, so you could add them into the list (If you know the id) before you run into them

**Comment by pcangelnc** [comment]
That would be awesome, thank you!

**Comment by ikvega** [comment]
Custom categories might not be enough for this. For me, autosell triggers on items that are/were assigned to system->trash by default, regardless of actual category rule applied. Disabling autosell for trash category does not help either.
![Bug](https://user-images.githubusercontent.com/40540632/118409582-bc44b800-b693-11eb-98b7-d519fd222f30.jpg)

**Comment by arkayenro** [comment]
ah, i'll fix that in the next alpha.

if you want to fix it yourself in the mean time you can edit arkinventoryjunk.lua, and comment out, or remove, lines 52, 53, and 54
```
--			if info.q == 0 then
--				isJunk = true
--			end
```

**Comment by MrUzagi** [comment]
When I've used custom categories in the past to avoid selling greys I have also put the categories on their own bar, which does not have auto-sell on. So they aren't grouped with the other greys and junk. Not sure if that makes a difference here.

**Comment by arkayenro** [comment]
> Not sure if that makes a difference here.

it wont in this case.  the code used to do a simple "if its grey then its junk i can sell" check which it shouldnt have kept doing after i added the auto sell option to the system junk category.  even if you added they grey item to another custom category that wasnt tagged for auto sell it would still sell it because its grey.

its fixed in the latest alpha though, and will obviously be in the next release
