### ISSUE TITLE
Bug: Normal gear suddenly marked as "Junk" and auto sold

### ISSUE THREAD

**Issue by karl-run** [arkayenro/arkinventory#1420]
It seems ArkInventory started marking my normal gear as "Junk" by default.

For example here is a Shadowlands item marked as junk:

![image](https://user-images.githubusercontent.com/1507032/103359369-17e12100-4ab8-11eb-885f-d4969290fea1.png)

Here's an ilvl 207 epic item marked as junk:

![image](https://user-images.githubusercontent.com/1507032/103359425-334c2c00-4ab8-11eb-9b62-78c2c8b0b245.png)

I didn't noticed that it happened until my entire gear category (except for two daggers) was sold to the vendor. :) I've increased the quality cut-off because I have a custom rule that auto sells old epic items.

![image](https://user-images.githubusercontent.com/1507032/103359318-f849f880-4ab7-11eb-9bdb-a3379006c67f.png)

From what I can tell this has occurred without the addon being updated. WowUp reports my ArkInevntory being updated 25 days ago.

**Comment by arkayenro** [comment]
theres a config option for assigning the junk category to equipment you cannot use.  its possible that has gone weird for some reason so check if thats enabled and turn it off.  if should be with the other junk options

**Comment by karl-run** [comment]
Hmm, under "General - Junk" settings? I'm not able to find it.

![image](https://user-images.githubusercontent.com/1507032/103363101-9b9c0d00-4aba-11eb-87ca-6c339440a20c.png)

**Comment by karl-run** [comment]
When I wipe the `ArkInventory.lua` file, it sets the default category correctly.

![image](https://user-images.githubusercontent.com/1507032/103363456-693edf80-4abb-11eb-9ea6-a6a5b14e2a9b.png)

It's definitely something I've toggled at some point. 🤔

**Comment by karl-run** [comment]
I tried diffing a fresh settings file and mine, but couldn't find anything obvious, it was too noisy anyway, 2k LOC vs 5k LOC. :) I've started a fresh config for now. Closing this.

**Comment by arkayenro** [comment]
theres a soulbound section on that junk tab that youre missing so you seem to be running an older version.

options to disable soulbound items as junk were added in 3.09.41
