### ISSUE TITLE
error: you can't do that while mounted

### ISSUE THREAD

**Issue by eentje** [arkayenro/arkinventory#1423]
i get the above error while depositing anima in my resevoir

**Comment by arkayenro** [comment]
kyrian i presume, as its the only outdoor sanctum

it always barfed or failed if you were mounted so i added the warning text that you cant actually deposit while mounted - or at least you couldnt previously, blizzard may have fixed it but i didnt think they had.

the error is just output it doesnt stop anything, so does the deposit actually work while mounted now?

**Comment by eentje** [comment]
it dismounts me and then deposits now it seems.

**Comment by arkayenro** [comment]
thanks, i'll remove the error warning

**Comment by arkayenro** [comment]
fixed in 3.09.48
