### ISSUE TITLE
ArkInventory: WARNING> code issue - function for [HookOpenAllBags:MailCommanderFrame] was not found - please notify the author so it can be fixed

### ISSUE THREAD

**Issue by alar77** [arkayenro/arkinventory#1424]
Hi, I am MailCommander author. My addon allows people to create list of items to be more or less automatically sent via mail.
In order to let people configure their lists, it sometimes directly calls OpenAllBags, so your code find an"opener" he is not aware of and complains.
Basically a
`elseif whoname =="MailCommanderFrame then
-- third party aoon, uignore
`
in the ArkInventory.HookOpenAllBafs() function will sole the issue.
Feel free to contact me if you want and thanks for this great addon

**Comment by arkayenro** [comment]
should be fixed in 3.09.48
