### ISSUE TITLE
Profiles for characters not being created. 

### ISSUE THREAD

**Issue by IntrovertGenius42** [arkayenro/arkinventory#1429]
Is ArkInventory suppose to create separate profiles for each characters, or do I have to do this manually? I did have two profiles created, and when I made changes to the one profile, it would also make changes to the other profile, so I deleted one of the profiles, and logged out and logged back in to see if it would create a new profile and resolve this issue, but it did not create a new profile, and is using my profile for my main character. Do I have a setting wrong that is doing this. Also, when I go into the Accounts Tab, under Character it says "Account". I am not sure what I am doing wrong with this, and I can't see to find anything online about this. 

Thank you.

**Comment by arkayenro** [comment]
yes and no

read this https://github.com/arkayenro/arkinventory/wiki/UserGuide_Profiles
also read the blueprint link thats in there

the accounts stuff isnt finished/viable yet so you can ignore it.  its meant for people that want to share data across multiple wow accounts but needs a tonne of work that i dont have time for at the moment.
