### ISSUE TITLE
Error mousing over quest rewards on TBC Beta.

### ISSUE THREAD

**Issue by kkatee** [arkayenro/arkinventory#1432]
Greetings from TBC Classic Beta!

Everything seems to be working fine, except for this error when mousing over quest rewards on the quest completion window.

![image](https://user-images.githubusercontent.com/34851555/113372257-f728b000-93b3-11eb-829f-db8cd754fcd6.png)

**Comment by arkayenro** [comment]
theres somethign funky with the itemlink, its barfing on the bonus id for some reason.

next time it happens can you scroll down more? need to see what pos, osd[14], and [15], are set to.

**Comment by kkatee** [comment]
Message: ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:4958: table index is nil
Time: Fri Apr  2 21:07:38 2021
Count: 2
Stack: ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:4958: table index is nil
[string "@Interface\AddOns\ArkInventory\ArkInventoryStorage.lua"]:4958: in function `ObjectStringDecode'
[string "@Interface\AddOns\ArkInventory\ArkInventoryTooltip.lua"]:1950: in function `TooltipAddItemCount'
[string "@Interface\AddOns\ArkInventory\ArkInventoryTooltip.lua"]:1270: in function `HookTooltipSetGeneric'
[string "@Interface\AddOns\ArkInventory\ArkInventoryTooltip.lua"]:1376: in function <...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:1375>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetQuestLogItem'
[string "*:OnEnter"]:3: in function <[string "*:OnEnter"]:1>

Locals: h = "[Bracers of the People's Militia]"
i = nil
hr = "[Bracers of the People's Militia]"
hc = "item:710::::::::22::11:1:3524::::"
osd = <table> {
 1 = "item"
 2 = 710
 3 = 0
 4 = 0
 5 = 0
 6 = 0
 7 = 0
 8 = 0
 9 = 0
 10 = 0
 11 = 0
 12 = 11
 13 = 0
 14 = 3524
 15 = 0
 16 = 0
 17 = 0
 18 = 0
 hb = "item:710"
 enchantid = 0
 linklevel = 22
 id = 710
 class = "item"
 upgradeid = 11
 suffixfactor = 0
 sourceid = 1
 h = "item:710::::::::22::11:1:3524::::"
 suffixid = 0
 specid = 0
 bonusids = <table> {
 }
 gemid = <table> {
 }
 name = "Bracers of the People's Militia"
 uniqueid = 0
}
c = 18
pos = 14
(for index) = 19
(for limit) = 3538
(for step) = 1
x = 19
(*temporary) = <table> {
 0 = true
}
(*temporary) = nil
(*temporary) = ""
(*temporary) = "22"
(*temporary) = "table index is nil"
string = <table> {
 split = <function> defined =[C]:-1
 match = <function> defined =[C]:-1
 gmatch = <function> defined =[C]:-1
 upper = <function> defined =[C]:-1
 gsub = <function> defined =[C]:-1
 format = <function> defined =[C]:-1
 lower = <function> defined =[C]:-1
 sub = <function> defined =[C]:-1
 gfind = <function> defined =[C]:-1
 rep = <function> defined =[C]:-1
 char = <function> defined =[C]:-1
 rtgsub = <function> defined @Interface\FrameXML\RestrictedInfrastructure.lua:610
 join = <function> defined =[C]:-1
 reverse = <function> defined =[C]:-1
 byte = <function> defined =[C]:-1
 trim = <function> defined =[C]:-1
 len = <function> defined =[C]:-1
 find = <function> defined =[C]:-1
}
cacheObjectStringDecode = <table> {
 item:141342 = <table> {
 }
 reputation:1341 = <table> {
 }
 reputation:1828 = <table> {
 }
 item:29425 = <table> {
 }
 item:184381 = <table> {
 }
 item:23984::::::::21::::::: = <table> {
 }
 item:184315 = <table> {
 }
 item:146944 = <table> {
 }
 item:5177::::::::22::::::: = <table> {
 }
 item:140243 = <table> {
 }
 item:32897 = <table> {
 }
 reputation:2165 = <table> {
 }
 item:141990 = <table> {
 }
 item:181550 = <table> {
 }
 item:147410 = <table> {
 }
 [Tabard of the Hand] = <table> {
 }
 reputation:1375 = <table> {
 }
 reputation:1278 = <table> {
 }
 item:181547 = <table> {
 }
 item:184777 = <table> {
 }
 item:184769 = <table> {
 }
 [Sand Pear Pie] = <table> {
 }
 reputation:934 = <table> {
 }
 item:140240 = <table> {
 }
 item:140401 = <table> {
 }
 item:7005::::::::21::::::: = <table> {
 }
 reputation:1337 = <table> {
 }
 [Hearthstone] = <table> {
 }
 item:31263::::::-60:266207237:22::::::: = <table> {
 }
 item:22645::::::::22::::::: = <table> {
 }
 item:26021::::::::22::::::: = <table> {
 }
 [Smoked Bear Meat] = <table> {
 }
 [Jessera's Fungus Lined Bands] = <table> {
 }
 [Seer's Cape] = <table> {
 }
 item:23984::::::::22::::::: = <table> {
 }
 item:118660 = <table> {
 }
 item:184150 = <table> {
 }
 item:79264 = <table> {
 }
 item:184767 = <table> {
 }
 item:147416 = <table> {
 }
 item:140248 = <table> {
 }
 item:140403 = <table> {
 }
 item:184124 = <table> {
 }
 item:184119 = <table> {
 }
 item:3172::::::::22::::::: = <table> {
 }
 item:24344::::::::22::::::: = <table> {
 }
 [Earth Totem] = <table> {
 }
 item:3171::::::::22::::::: = <table> {
 }
 item:146949 = <table> {
 }
 item:183727 = <table> {
 }
 i

**Comment by arkayenro** [comment]
yep, looks like the itemstring format has changed.  it currently thinks there are 3524 bonus ids because of the shift.

i havent been able to find any documentation on which value has been removed from the itemstring though.

evrything up to 10 seems to be ok, so they may have either removed the sourceid, or perhaps moved the upgradevalue to after the bonus ids.

**Comment by kkatee** [comment]
interesting that it only happens in the quest window, and not over regular items.

**Comment by arkayenro** [comment]
it will depend if the item has any bonus ids, not necessarily where the item comes from

**Comment by arkayenro** [comment]
unless you can find an item in your bags that has a bonus id and is working ok.  then it might just be that particular item that is broken

**Comment by kkatee** [comment]
it happens on any item in a quest window. either quest rewards or quest items you hand in. the same item in bags doesnt trigger the error

**Comment by kkatee** [comment]
https://youtu.be/UkAFF07ZdhY

**Comment by arkayenro** [comment]
possibly a bug with the quest api functions.  can you open your bags and go into edit mode, click on the item and select debug, copy the itemstring out and paste it here, want to double check its completely normal when in the bag

**Comment by kkatee** [comment]
item:3511::::::::22:::::::

**Comment by kkatee** [comment]
![image](https://user-images.githubusercontent.com/34851555/113463737-54d00180-9473-11eb-80ec-27793896d8e0.png)

**Comment by arkayenro** [comment]
it looks like every quest reward has a bonus id of 3524 set but once its in your bag it loses the bonus id and is normal.  definitely looks like a bug with the itemstring being passed to / coming out of the quest api functions

**Comment by arkayenro** [comment]
plus the itemstring is missing a value somewhere between 10 and 14.  even if it ended up with that wonky bonus id it wouldnt have mattered if the itemstring had the correct number of values in it.

**Comment by arkayenro** [comment]
do you have any other mods loaded?  could you try it with just arkinventory, just to be sure its not some weird conflict

**Comment by kkatee** [comment]
yeah still happens with just arkinventory loaded.

**Comment by arkayenro** [comment]
k. i dont have access to be beta forums (dont have an invite) but i've posted it in the classic bugs forum, maybe someone will notice or another author/player will comment

**Comment by kkatee** [comment]
I posted a link to your post on to the in-client bug reporter.

**Comment by arkayenro** [comment]
thanks

**Comment by arkayenro** [comment]
was the quest from a heroic scenario?

do you have any items that have bonus ids on them?

**Comment by kkatee** [comment]
scenarios not even a thing in TBC.

not sure what you mean by bonus ID

**Comment by arkayenro** [comment]
rules out it being the difficulyid

when youre in the game next can you type /dump GetSpecialization() in the chat window and see if it outputs 0 or 11

**Comment by kkatee** [comment]
Message: [string "return GetSpecialization()"]:1: attempt to call global 'GetSpecialization' (a nil value)
Time: Sun Apr 11 09:11:13 2021
Count: 1
Stack: [string "return GetSpecialization()"]:1: attempt to call global 'GetSpecialization' (a nil value)
[string "return GetSpecialization()"]:1: in function `func'
[string "@Interface\AddOns\Blizzard_DebugTools\Dump.lua"]:393: in function `DevTools_DumpCommand'
[string "@Interface\FrameXML\ChatFrame.lua"]:2274: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:4697: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4360: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4396: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: (*temporary) = nil
(*temporary) = "attempt to call global 'GetSpecialization' (a nil value)"

**Comment by kkatee** [comment]
This issue seems to be resolved on the current beta build.
