### ISSUE TITLE
Backup/import default profile

### ISSUE THREAD

**Issue by nwardoh** [arkayenro/arkinventory#1433]
I have a couple account and would also like to share my profile with my wife and kids for their accounts so they don't have to set up the sorting individually. Is there any way to do this?

**Comment by arkayenro** [comment]
at the moment youd have to copy/paste the arkinventory.lua saved variables file from your machine to theirs, then they log into each of their characters

if you know what youre doing you can edit the saved variable files and just copy/paste the non character specific sections but if you miss youll potentially screw it up (not really a big deal) and they will lose their character data and will need to do login on them all again

(do not share it via a mapped drive, that will just cause you lots of headaches)

**Comment by arkayenro** [comment]
profile import/export is now available in 30952
