### ISSUE TITLE
TBC Beta error on quest dialog

### ISSUE THREAD

**Issue by nwardoh** [arkayenro/arkinventory#1435]
Any time you open a quest dialog for the first time with an NPC you get an error. After clearing it once it doesn't come back for that particular quest. 

Message: ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:4958: table index is nil
Time: Sat Apr 10 10:40:46 2021
Count: 7
Stack: ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:4958: table index is nil
[string "@Interface\AddOns\ArkInventory\ArkInventoryStorage.lua"]:4958: in function `ObjectStringDecode'
[string "@Interface\AddOns\ArkInventory\ArkInventoryTooltip.lua"]:1950: in function `TooltipAddItemCount'
[string "@Interface\AddOns\ArkInventory\ArkInventoryTooltip.lua"]:1270: in function `HookTooltipSetGeneric'
[string "@Interface\AddOns\ArkInventory\ArkInventoryTooltip.lua"]:1368: in function <...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:1367>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetQuestItem'
[string "@Interface\FrameXML\QuestInfo.lua"]:997: in function <Interface\FrameXML\QuestInfo.lua:986>

Locals: h = "[Wild Shoulderpads]"
i = nil
hr = "[Wild Shoulderpads]"
hc = "item:27724::::::::61::11:1:3524::::"
osd = <table> {
 1 = "item"
 2 = 27724
 3 = 0
 4 = 0
 5 = 0
 6 = 0
 7 = 0
 8 = 0
 9 = 0
 10 = 0
 11 = 0
 12 = 11
 13 = 0
 14 = 3524
 15 = 0
 16 = 0
 17 = 0
 18 = 0
 hb = "item:27724"
 enchantid = 0
 linklevel = 61
 id = 27724
 class = "item"
 upgradeid = 11
 suffixfactor = 0
 sourceid = 1
 h = "item:27724::::::::61::11:1:3524::::"
 suffixid = 0
 specid = 0
 bonusids = <table> {
 }
 gemid = <table> {
 }
 name = "Wild Shoulderpads"
 uniqueid = 0
}
c = 18
pos = 14
(for index) = 19
(for limit) = 3538
(for step) = 1
x = 19
(*temporary) = <table> {
 0 = true
}
(*temporary) = nil
(*temporary) = ""
(*temporary) = "61"
(*temporary) = "table index is nil"
string = <table> {
 split = <function> defined =[C]:-1
 match = <function> defined =[C]:-1
 gmatch = <function> defined =[C]:-1
 upper = <function> defined =[C]:-1
 gsub = <function> defined =[C]:-1
 format = <function> defined =[C]:-1
 lower = <function> defined =[C]:-1
 sub = <function> defined =[C]:-1
 gfind = <function> defined =[C]:-1
 rep = <function> defined =[C]:-1
 char = <function> defined =[C]:-1
 rtgsub = <function> defined @Interface\FrameXML\RestrictedInfrastructure.lua:610
 join = <function> defined =[C]:-1
 reverse = <function> defined =[C]:-1
 byte = <function> defined =[C]:-1
 trim = <function> defined =[C]:-1
 len = <function> defined =[C]:-1
 find = <function> defined =[C]:-1
}
cacheObjectStringDecode = <table> {
 [Ranger Bow] = <table> {
 }
 item:14046::::::::1::::::: = <table> {
 }
 item:1369::::::::4::::::: = <table> {
 }
 [Sungrass] = <table> {
 }
 item:6527::::::::20:::1:::: = <table> {
 }
 [Elegant Cloak of Healing] = <table> {
 }
 item:140243 = <table> {
 }
 [Mystic Crystal] = <table> {
 }
 [Bracers of Might] = <table> {
 }
 item:141990 = <table> {
 }
 item:19387:911:::::::60::::::: = <table> {
 }
 [Bard's Bracers of the Owl] = <table> {
 }
 [Razzashi Coin] = <table> {
 }
 item:10498::::::::60::::::: = <table> {
 }
 item:19610::::::::60:::11:::: = <table> {
 }
 item:7146::::::::51:::1:::: = <table> {
 }
 reputation:21:Friendly:3320:6000:0:0:0 = <table> {
 }
 item:15065::::::::1::::::: = <table> {
 }
 [Goblin Fishing Pole] = <table> {
 }
 [Journeyman's Backpack] = <table> {
 }
 item:20859::::::::1::::::: = <table> {
 }
 [Sentinel Girdle of the Bear] = <table> {
 }
 [Worn Mace] = <table> {
 }
 [Scroll of Strength III] = <table> {
 }
 [Runecloth Bag] = <table> {
 }
 item:11923::::::::60:::1:::: = <table> {
 }
 reputation:470:Friendly:4655:6000:0:0:0 = <table> {
 }
 item:5780::::::::1::::::: = <table> {
 }
 [Ironwood Seed] = <table> {
 }
 item:2453::::::::10::::::: = <table> {
 }
 [Symbol of Divinity] = <table> {
 }
 [Pauldrons of Might] = <table> {
 }
 item:15280::::::849:818583040:60:::1:::: = <table> {
 }
 [Zulian Headdress] = <table> {
 }
 item:79264 = <table> {
 }
 item:983::::::::9:::11:::: = <table> {
 }
 [Rune of Teleportation] = <table> {
 }
 [Shadowcraft Belt] = <table> {
 }
 item:184767 = <table> {
 }
 item:24280::::::::61::::::: = <table> {
 }
 |Hitem:4500:

**Comment by arkayenro** [comment]
the itemstring doesnt match the correct format, it appears to be a bug in blizzards quest api as its missing a value

is that reward from a heroic scenario?  if it is then the 11 would line up with that value and its the spec or upgradetype that is missing

**Comment by arkayenro** [comment]
see #1432

**Comment by nwardoh** [comment]
That’s definitely the same issue. Thanks.

**Comment by arkayenro** [comment]
another user reported that the latest beta appears to have resolved the issue, can you confirm its working ok now for you as well
