### ISSUE TITLE
TBC Beta - Import Doesn't Give Errors, but Doesn't Work

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1436]
Here's the import string I'm using:

> ^1^T^Sdesign^T^Sslot^T^Spad^N8^Sempty^T^Sclump^B^t^Ssize^N36^Sunusable^T^Stint^B^t^t^Scategory^T^S1!201^N3^S1!111^N2^S1!411^N4^S1!209^N3^S1!107^N2^S1!108^N2^S1!203^N3^S1!403^N5^S1!404^N3^S1!452^N2^S1!512^N2^S1!415^N6^S1!102^N2^S1!420^N3^S1!453^N6^S1!412^N2^S1!426^N3^S1!424^N3^S1!104^N2^S1!409^N2^S1!501^N2^S1!435^N3^S1!419^N3^S1!432^N3^S1!101^N2^S1!418^N3^S1!202^N3^S1!110^N2^S1!112^N2^S1!437^N3^S1!206^N3^S1!416^N5^S1!503^N2^S1!902^N3^S1!513^N2^S1!423^N6^S1!430^N3^S1!421^N9^S1!113^N2^S1!438^N4^S1!103^N2^S1!502^N2^S1!106^N2^S1!506^N2^S1!310^N9^S1!205^N3^S1!504^N2^S1!505^N2^S1!208^N9^S1!427^N2^S1!402^N8^S1!443^N6^S1!428^N3^S1!436^N3^S1!105^N2^S1!304^N9^S1!207^N3^S1!431^N3^S1!433^N3^S1!204^N3^S1!417^N3^t^Sused^SY^Sname^SDefault^Sbar^T^Sper^N6^Scompact^B^Sdata^T^N1^T^Ssort^T^Smethod^N9999^t^t^N2^T^Ssort^T^Smethod^N9999^t^t^N3^T^Ssort^T^Smethod^N9999^t^t^N4^T^Ssort^T^Smethod^N9999^t^t^N5^T^Ssort^T^Smethod^N9999^t^t^N6^T^Ssort^T^Smethod^N9999^t^t^N8^T^Ssort^T^Smethod^N9999^t^t^N9^T^Ssort^T^Smethod^N9999^t^t^N10^T^Ssort^T^Smethod^N9999^t^t^t^t^t^Scat^T^t^Ssort^T^t^t^^

**Comment by arkayenro** [comment]
import/export works properly in 30952 but its now for the whole profile
