### ISSUE TITLE
Error every time opening my bags - Classic WOW

### ISSUE THREAD

**Issue by volostyle** [arkayenro/arkinventory#1438]
I'm getting this error every time I open my bags now in WoW Classic:

Message: Interface\SharedXML\Util.lua:248: bad argument #1 to 'pairs' (table expected, got nil)
Time: Thu Apr 22 13:13:30 2021
Count: 2
Stack: Interface\SharedXML\Util.lua:248: bad argument #1 to 'pairs' (table expected, got nil)
...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:758: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[C]: ?
[C]: in function `pairs'
Interface\SharedXML\Util.lua:248: in function `Mixin'
...face\AddOns\AddOnSkins\Skins\AddOns\ArkInventory.lua:34: in function <...face\AddOns\AddOnSkins\Skins\AddOns\ArkInventory.lua:22>
[C]: in function `Frame_Main_Anchor_Set'
Interface\AddOns\ArkInventory\ArkInventory.lua:3610: in function `Frame_Main_Reposition'
Interface\AddOns\ArkInventory\ArkInventory.lua:4335: in function `Frame_Main_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[C]: in function `Show'
Interface\AddOns\ArkInventory\ArkInventory.lua:4306: in function `Frame_Main_Show'
Interface\AddOns\ArkInventory\ArkInventory.lua:4271: in function `Frame_Main_Toggle'
Interface\AddOns\ArkInventory\ArkInventory.lua:10121: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:10117>
(tail call): ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: errMsg = "Interface\SharedXML\Util.lua:248: bad argument #1 to 'pairs' (table expected, got nil)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:295
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by arkayenro** [comment]
thats either AddOnSkins or TSM

disable them one at a time and see if the problem still happens
