### ISSUE TITLE
Invalid inventory slot in GetInventorySlotInfo

### ISSUE THREAD

**Issue by Proteyer** [arkayenro/arkinventory#1439]
Version: v30948.3 Alpha Shadowlands

Hi,
since last alpha update whenever I get an item to my bag i got following lua error:

Message 1/2
Message: ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:2673: Invalid inventory slot in GetInventorySlotInfo
Time: Thu Apr 29 16:17:07 2021
Count: 1
Stack: ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:2673: Invalid inventory slot in GetInventorySlotInfo
[string "@Interface\AddOns\ArkInventory\ArkInventoryStorage.lua"]:1694: in function `ScanLocation'
[string "@Interface\AddOns\ArkInventory\ArkInventoryStorage.lua"]:253: in function `?'
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

Message 2/2
Message: ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:2673: Invalid inventory slot in GetInventorySlotInfo
Time: Thu Apr 29 16:17:12 2021
Count: 2
Stack: ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:2673: Invalid inventory slot in GetInventorySlotInfo

Locals: <none>

**Comment by speedwaystar** [comment]
this error also appears to make the guild bank pane revert to the vanilla WoW interface.

**Comment by arkayenro** [comment]
should be fixed in the latest allpha - https://www.curseforge.com/wow/addons/ark-inventory/files/3293354
