### ISSUE TITLE
Search is slowww

### ISSUE THREAD

**Issue by migzlv** [arkayenro/arkinventory#1442]
When I open search for "heart" (it should show hearthstone )
my pc is relatively fast, have 16 gb ram.
i login to an alt, only arkinventory addon  active, 8 secs to find "hearthstone".
Then one should think the search data is in memory for this wow session.
I relog to another alt, have several addons active, seacrh for hearthstone takes 2m20 seconds to show a search result.
The next search result in the same "screen" is almost instant
arkinventory mem is 100mb 
so in this alt i "relogged" and tried again, this time it took 3 minutes before a search result showed up.
(also it  show only alts from alliance, but all realms) i would like them to show all alts (including horde)  in the search window)
How to make it faster ?

**Comment by arkayenro** [comment]
search data is built off tooltip and other item data that needs to be retrieved so its batched and cached in memory (not saved as its too much data).

if you wait for the search window to populate that typically means its built the search data cache and any search after that should be pretty quick. 

if you try to search before the data is ready then you still have to wait for the search cache to be built, then your search to run.

how much data it needs to build is determined by how much stuff you have on each character, how many characters you have, if youre serchning across realms, across factions, that sort of thing.  the smaller the search window the faster it is to build the cache.

you cant adjust the search thread timer , its currently hardcoded to half of the normal thread timer

**Comment by arkayenro** [comment]
actually it looks like it searches across all characters regardless of faction or realm, but it relies on the item count options to show the numbers so you would change those options to see it across realms/factions.
