### ISSUE TITLE
WoW Classic Window Hidden Behind Other Windows

### ISSUE THREAD

**Issue by Kutcha313** [arkayenro/arkinventory#1443]
Hey guys. Searched for this issue I'm having and didn't find any. COULD BE just user error. :)

In retail Arkinventory can be clicked, and then the window is above other windows opened. 

In Classic WoW ArkInventory is hidden behind other windows and clicking the Ark window doesn't make it unhidden.

The versions I have tried is the latest 1.13.7 and 1.13.6nolib 2/14/2021

Now this could be a setting issue, which I can not find.  I would assume the setting would be under Settings/Designs(Styles/Layouts) or in General.

Thanks for the help.

**Comment by arkayenro** [comment]
there are two options that might cause that
1. config > general > profiles > lcoation > special - should be ticked
2. settings > designs > window > general > frame strata - should be medium, you can try high

**Comment by Kutcha313** [comment]
Thanks for your reply!

1. Yup special is ticked
2. And yes, this was set on low and reset to medium, and it worked!

Thank you!
