### ISSUE TITLE
TBC Classic Extra bank slot not showing 

### ISSUE THREAD

**Issue by kkatee** [arkayenro/arkinventory#1445]
The new extra bag slot in bank is not available.

**Comment by arkayenro** [comment]
in 9.1 retail?  i hadnt heard we were getting another bank slot

**Comment by arkayenro** [comment]
i just checked retail ptr bank and it has the normal seven bag slots, no new bag slot in the bank.

which release are you using?

**Comment by kkatee** [comment]
This is in Burning Crusade Classic

**Comment by arkayenro** [comment]
theres 6 bag slots in the blizzard interface and 6 in arkinventory when using the burning crusade beta.

the 7th bank bag slot isnt in burning crusade, only retail.

disable arkinventory and check the blizzard bank interface to confirm

**Comment by arkayenro** [comment]
nvm, figured it out

**Comment by kkatee** [comment]
![image](https://user-images.githubusercontent.com/34851555/118937235-a7686d00-b990-11eb-8888-28ec5dd0e40a.png)
![image](https://user-images.githubusercontent.com/34851555/118937285-b818e300-b990-11eb-8a8b-1ffbc5b4011e.png)

**Comment by arkayenro** [comment]
try the latest alpha

**Comment by kkatee** [comment]
works fine in the alpha

**Comment by simonsolberg** [comment]
I have the same issue. The last bagslot doesnt show up in ark inventory. I have v.3.09.49 [The Burning Crusade] installed. 

If I disable the addon, put a bag in the new bagslot and re-enable the addon, the bagslots do show up, but the last bag in the bank does not. 

Screenshots: 
![image](https://user-images.githubusercontent.com/31542525/120378362-9cadc080-c31e-11eb-8465-3c86b5f7262d.png)
![image](https://user-images.githubusercontent.com/31542525/120378587-ea2a2d80-c31e-11eb-8fe4-e9fa140300e8.png)

**Comment by arkayenro** [comment]
did you download the alpha version?

**Comment by arkayenro** [comment]
fixed in 3.09.50
