### ISSUE TITLE
BCC error

### ISSUE THREAD

**Issue by Talimar** [arkayenro/arkinventory#1446]
2x ...rkInventory\Externals\Ace3\AceEvent\AceEvent-3.0-4.lua:33: Attempt to register unknown event "PARTY_MEMBERS_CHANGED"
[string "=[C]"]: in function `RegisterEvent'
[string "@ArkInventory\Externals\Ace3\AceEvent\AceEvent-3.0-4.lua"]:33: in function `OnUsed'
[string "@Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:142: in function `RegisterEvent'
[string "@Prat-3.0-3.9.1\modules\PlayerNames.lua"]:1132: in function `OnModuleEnable'
[string "@Prat-3.0-3.9.1\addon\modules.lua"]:189: in function <Prat-3.0\addon\modules.lua:178>
[string "=[C]"]: ?
[string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:540: in function `EnableAddon'
[string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Using version 3.09.49-BurningCrusade

**Comment by arkayenro** [comment]
that looks like a prat issue.

ai doesnt care about party members, but prat, and masque, are using one of the shared libraries that ai loads first (so gets ownership, and thus blame)

**Comment by Talimar** [comment]
I see, thanks :)
