### ISSUE TITLE
TBCC Inventory is not refresehed v.3.09.49 TBC

### ISSUE THREAD

**Issue by Padparadscha** [arkayenro/arkinventory#1447]
The Inventory is not refreshed. 
Already Mailed Items where shown in Bagspace. 
New looted Items are not shown. 
Also after a /reload it is not refreshed. All other Addons are disabled.

**Comment by arkayenro** [comment]
mines working ok.  looted items show up, mailed items go away, sold items go away

you absolutely sure arkinventrory is the only mod running?  no other bag mods installed?

**Comment by Padparadscha** [comment]
it seems, that it's a problem with my WTF arkinventory data. I deleted WTF, made a fresh Arkinventory install and it works.
After copying back WTF it's the same problem and also I have seen wrong symbols for items. Maybe the easy way would be making new Rules
