### ISSUE TITLE
TBC Classic Attempt to register unknown event "PARTY_MEMBERS_CHANGED"

### ISSUE THREAD

**Issue by crichton32** [arkayenro/arkinventory#1448]
I get the below error when I load into game from ark inventory  - but  it otherwise works fine as far as I can tell. 

1x ...rkInventory\Externals\Ace3\AceEvent\AceEvent-3.0-4.lua:33: Attempt to register unknown event "PARTY_MEMBERS_CHANGED"
[string "=[C]"]: in function `RegisterEvent'
[string "@ArkInventory\Externals\Ace3\AceEvent\AceEvent-3.0-4.lua"]:33: in function `OnUsed'
[string "@ArkInventory\Libs\CallBackHandler\CallbackHandler-1.0-7.lua"]:142: in function `RegisterEvent'
[string "@Prat-3.0-3.9.1\modules\PlayerNames.lua"]:1132: in function `OnModuleEnable'
[string "@Prat-3.0-3.9.1\addon\modules.lua"]:189: in function <Prat-3.0\addon\modules.lua:178>
[string "=[C]"]: ?
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:70: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65>
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:540: in function `EnableAddon'
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:630: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:615>

**Comment by arkayenro** [comment]
same as #1446 its an issue with prat, or at least it looks like it.

**Comment by kkatee** [comment]
There is a fixed version of Prat in the comments on curse
