### ISSUE TITLE
How to reset settings of one character?

### ISSUE THREAD

**Issue by pquerner** [arkayenro/arkinventory#1450]
I have a "issue" which bugs me. For one of my characters (and only one) all inventory windows (bank, bags, ..) open in the topright and I want them to open either a) on the last known location (like all other characters) or b) always in the middle.

How can I reset the settings for that one character without breaking others?

(I dont want anything else reset, like added rules, and whatnot)

//Edit
Also this is BCC I am talking about, but it existed in Classic aswell.
Current used version: 3.09.49-BurningCrusade

I cant remember when I first encountered that issue and how I got it.

**Comment by arkayenro** [comment]
if you move the window, then just open/close it does it stay in place or get reset?

what about after a /uireload

double check the profile that character is using.  is it the same as the other characters?

**Comment by pquerner** [comment]
1) Log into said character
2) Open Bags with 'B'
3) Bags open in the topright
4) Move bag window to new place
5) Open/Close a few time -> Bag stay in the moved place
6) Open Bags -> Toggle location to example "Bank" -> open in topright again (only bank window)
7) Move bankwindow 
8) Close all windows, open bag, toggle bank -> bank window (and bag window) are in the moved place

-- RELOAD UI
All of the above again. The window(s) open in the topright again.

As for profiles, I only have 1 profile, thats the "Default" profile and every character on this account is using it.

**Comment by arkayenro** [comment]
weird.  in the profile, make sure the three blueprint dropdowns are using the 1000 default, not the 9999 default (the 9999 one wont allow any changes to be saved

also, could you try it with only arkinventory loaded on that character?  just in case theres a weird conflict

**Comment by pquerner** [comment]
I've fixed it because apparantly I was using no profile at all.
It selected "Default [1000]" but it wasnt using any. (I dont see the 9999 one)

Fix it by selecting the default profile in the "Generals > Profiles Tab".
Because now I see the little checkmark next to the profile. ;D
