### ISSUE TITLE
Can't click on keys in key ring

### ISSUE THREAD

**Issue by Zolath** [arkayenro/arkinventory#1451]
Ordinarily not a problem, but "Blood Red Key" ends up on the key ring, but needs to be clicked to start a quest.

**Comment by arkayenro** [comment]
try the latest alpha https://www.curseforge.com/wow/addons/ark-inventory/files/3321747

it should have worked as is so im not sure why it isnt but theres a possible fix in there that might work, if wow will let it run and not abort

**Comment by arkayenro** [comment]
worse case, change the keyring setting to not override it and use the default ui to start the quest then put it back

**Comment by arkayenro** [comment]
fixed in 3.09.50 (probably)
