### ISSUE TITLE
"outfit" rules broken when items with randoms suffixes are present

### ISSUE THREAD

**Issue by MrTreng** [arkayenro/arkinventory#1453]
Some items with random suffixes (e.g., "of the Eagle") are mistakenly caught by the first "outfit" rule that is evaluated, even though they are not part of any outfit set of ItemRack. This is because the regular expressions used by ArkInventory to check for valid item IDs are broken; they do not allow for negative suffixIDs (for more info, see [here](https://wowpedia.fandom.com/wiki/ItemLink)).

The fix is simple. Instead of this in ArkInventoryRules.lua:902:

```
if ArkInventory.ClientCheck( ArkInventory.Const.Blizzard.Client.CLASSIC ) then
  -- only use the first 7 values in classic
  pattern1 = "^item:(%d-:%d-:%d-:%d-:%d-:%d-:%d-:)"
  pattern2 = "^(%d-:%d-:%d-:%d-:%d-:%d-:%d-:)"
end
```
use, for example, this:

```
if ArkInventory.ClientCheck( ArkInventory.Const.Blizzard.Client.CLASSIC ) then
  -- only use the first 7 values in classic
  pattern1 = "^item:(%d-:%d-:%d-:%d-:%d-:%d-:%-?%d-:)"
  pattern2 = "^(%d-:%d-:%d-:%d-:%d-:%d-:%-?%d-:)"
end
```

This allows for zero or one minus in front of the suffixID number.

Edit: refer to "outfit" rules instead of "equip" rules.

**Comment by arkayenro** [comment]
`equip( )` will capture any equipable item, use `outfit( )` if you only want items that are in an outfit

also, the patterns already handled negative suffixes, thus the `%-?%d-` in the 7th position

**Comment by MrTreng** [comment]
Apologies, I indeed meant "outfit" rules and have updated the issue accordingly.

Let me add a bit more info: The issue only appears if there is at least one item in any set with a negative suffixID. Then, every other item with a negative suffixID in your inventory gets mistakenly attributed to the same set. This is because both following statements evaluate to 0 in this case:

`local id = string.match( ArkInventoryRules.Object.info.osd.h or "", pattern1 ) or 0`

and

`local setitem = string.match( setitem, pattern2 ) or 0`

. As they both match, the current item will be attributed to the current itemset, even though the itemid is actually different.

**Comment by arkayenro** [comment]
try the latest alpha, i rebuilt that code to align with the lastest version of itemrack

**Comment by MrTreng** [comment]
I just tried r1103-alpha and can confirm that the issue is fixed there. Many thanks for this great addon!
