### ISSUE TITLE
Gem are not recognized as such [BCC]

### ISSUE THREAD

**Issue by the-chuppa** [arkayenro/arkinventory#1458]
The simple gems (Aquamarine, Shadowgem, Arcane Crystal, ...) are being assigned the default category of _System > Default_ instead of _Trade Goods > Gems_ or something else more appropriate. Not tested on TBC gems.

![image](https://user-images.githubusercontent.com/71234359/120888381-52676080-c5f8-11eb-9bf0-894e87b9c3e2.png)

**Comment by arkayenro** [comment]
was locked to retail.

should be fixed in the next alpha/release

**Comment by arkayenro** [comment]
fixed in 30951
