### ISSUE TITLE
itemstat() not working

### ISSUE THREAD

**Issue by Alice-Storey** [arkayenro/arkinventory#1459]
Example: A weapon (item 181222) with only strength as a primary stat

passes the rule
( type(2) and subtype(6) )

but fails this rule
( type(2) and subtype(6) and itemstat("strength") )

![image](https://user-images.githubusercontent.com/36473318/121083295-deb68680-c7a4-11eb-8de1-e7f83bb3d48f.png)

**Comment by arkayenro** [comment]
ah, it looks like weapons cause issues because of their damage text.

will be fixed in the next alpha/release

**Comment by arkayenro** [comment]
fixed in 30951
