### ISSUE TITLE
Is this more a Scrap or Arkinventory Issue?

### ISSUE THREAD

**Issue by ByucknahTheRed** [arkayenro/arkinventory#1461]
So whenever I loot a totem or relic I get an error that breaks my Arkinventory that seems to be related to the addon Scrap but I am not sure which end it needs to be fixed on. Is this something Arkinventory needs to fix or something Scrap needs to fix? I have attached an image of the error code. Basically it breaks the inventory until the item is removed. Oddly enough, only the main bags. Putting the object in the bank does not break the bank.

https://i.imgur.com/OklnIsB.png

**Comment by arkayenro** [comment]
im not sure how its getting to that scrap code from arkinventory.  if possible could you install buggrabber and bugsack to capture the entire stack trace and post that?

**Comment by arkayenro** [comment]
ive also added some code that may or may not help from my side which will be in the next alpha/release

**Comment by ByucknahTheRed** [comment]
Yeah, let me install those addons and I will get back to you. Sorry for the delay.

**Comment by ByucknahTheRed** [comment]
Alright, here are the error reports using those two addons. I hope this helps.

https://i.imgur.com/gFaxhK0.png - Bugsack
https://i.imgur.com/eMUQPTr.png - Buggrabber

**Comment by arkayenro** [comment]
i think its an issue with scrap.  you can try the latest alpha 30950.4 to see if that helps or not though (i just pass through the bag and slot so scrap doesnt have to find it).

i presume something is going weird when scrap is trying to work out what the item is like in comparison to what youre wearing

**Comment by ByucknahTheRed** [comment]
Alright, whenever the Alpha populates on Curse I will give it a try and if not I will submit an issue with Scrap. Thanks so much for the assistance.
