### ISSUE TITLE
ARKInventory not remembering previous location on load

### ISSUE THREAD

**Issue by allcoast** [arkayenro/arkinventory#1462]
I have been seeing an issue since shadowlands. Whenever i login to the game or reload my UI, the ark inventory windows does not remember the previous location. It always loads at the top right hand corner of the screen.

Is this a bug or is it intentional?

**Comment by arkayenro** [comment]
it typically means you either have not selected a profile, or the profile you have selected is using a blueprint option (style, design, categoryset) that is system locked, eg, *9999 [Default], and not 1000 [Default] or one you created

**Comment by allcoast** [comment]
How would i be able to check this? It seems that the profiles are valid. I went to settings-> category sets -> and it is using Default[1000] as it always had.

**Comment by allcoast** [comment]
![2021-06-14_00h43_20](https://user-images.githubusercontent.com/20448848/121840101-86eab480-cca9-11eb-8ed0-bdf56556332c.png)

**Comment by allcoast** [comment]
![2021-06-14_00h44_03](https://user-images.githubusercontent.com/20448848/121840135-a08bfc00-cca9-11eb-9270-a4809dda5266.png)

**Comment by arkayenro** [comment]
in the first screenshot the current profile appears to be empty, can you select one of the profiles and restart

**Comment by allcoast** [comment]
Ok, that worked. does each character have to have the profile set or will it cary over?

**Comment by arkayenro** [comment]
i think so.  better to double check anyway.

**Comment by allcoast** [comment]
perfect. thanks. will do. thanks for the quick help
