### ISSUE TITLE
All slots are locked

### ISSUE THREAD

**Issue by Kutcha313** [arkayenro/arkinventory#1465]
Hi there, my friend has an issue of all his slots show locked. We uninstalled Arkinventory then double-checked the interface/add-ons folder and made sure it was empty. He is using BCC. Version 3.09.50-BurningCrusade.zip.

We reinstall this version and other and the bar are still locked. (Bar 2 locked, sorting method locked, assignable categories locked.) 

I uninstalled and cleared out my folder and did a reinstall, and it works fine. 

Maybe his Curseforge is corrupting his file? Not sure. Strange.

https://1drv.ms/u/s!Ah7_Vhm6Z1k3grFNClUTHyAuRjmK9A?e=Bd0CWH

**Comment by arkayenro** [comment]
youre using the system default [9999] elements (which are locked so you cant make changes to them)

edit the profile and change the blurprint options to either the [1000] default ones, or create a new design and categoryset and use those, for each of the locations you want to change the settings for

**Comment by arkayenro** [comment]
btw, if you already use the retail version of arkinventory you may want to copy the savedvariable file across so it has your current setup to start with

**Comment by Kutcha313** [comment]
Ok thank you I'll head over to my friends house and do the changes. Thanks for your help!
