### ISSUE TITLE
Items not shown in AI

### ISSUE THREAD

**Issue by alexandrospanagiotidis** [arkayenro/arkinventory#1466]
Hi!

I just noticed that at least one of my characters has items in its inventory that do not appear in AI.
As an example, see the attached screenshot I just took:

![ark-inventory-item-missing](https://user-images.githubusercontent.com/25583823/123136914-bf318600-d453-11eb-94e4-1a8dc2c38d2b.jpg)

I once had a bar where I showed trinkets, but I removed that recently.
The item above is from Firelands, and I ran that instance (and sold everything from there) before I removed the trinket bar.

I also had a rule active (`equip("trinket")`) that was enabled; disabling it did not change anything, even after relogging the trinkets do not show up.
I also seem to have some shoes that do not appear in AI.

Is there any way to find out why an item is not shown?

EDIT: I disabled AI for the backpack and it seems that AI ignores one bag completely.

**Comment by alexandrospanagiotidis** [comment]
Alright, I'm an idiot. It seems for that bag I disabled "Display" its right-click menu. Checking that again shows the items.

I'll close this one, feel free to delete it if it confuses people too much :)

**Comment by alexandrospanagiotidis** [comment]
Actually, I just noticed that the bag was not marked red, so I didn't notice it was hidden.
So I think at least that could be a bug.

**Comment by arkayenro** [comment]
the bag icon goes red when hidden.  just toggle the display option to check

nothing changes when theyre full

**Comment by alexandrospanagiotidis** [comment]
Yeah you are right, you can actually see the bag being red in my screenshot :D
