### ISSUE TITLE
Location history for keyring and used gems

### ISSUE THREAD

**Issue by Flowy** [arkayenro/arkinventory#1467]
Keys in keyring are not multiplied by stack, always counting only one
Gems that are in gear sockets are not counted at all

**Comment by arkayenro** [comment]
odd, keys never used to stack.  are there stackable keys in the keyring now?

gems socketed onto gear have never been counted

**Comment by arkayenro** [comment]
keyring item count should be fixed in 30951.1

**Comment by Flowy** [comment]
Coilskare Chest Key, Camp Anger Key, Ethereum Prison Key and many other

**Comment by arkayenro** [comment]
fixed in 30952
