### ISSUE TITLE
question about gold display

### ISSUE THREAD

**Issue by eentje** [arkayenro/arkinventory#1468]
i left a guild an i have data from it. i found the option to delete inventory info but that wont delete the gold amount  in the bank. that will show when i hover over my total gold. and i cant find the option to delete the gold from that guild only for all guilds what i dont want. is there an option for it  to delete just a certain guilds gold ?

thx for the great addon. 

Greetz

**Comment by eentje** [comment]
after deleting the info closing the game and deleting it again the info was of the tooltip aswell i guess it was a bug sorry for the unnessary ticket.  ill close it

**Comment by arkayenro** [comment]
the guild gold amount always seems to stick around for some reason.

typically its when youre still in the guild so it scans it immediately after deleting and picks it up again.

did you delete it from the guild window or the account section in the config?

**Comment by eentje** [comment]
i am still in the guild on one toon but i havent visit the guildbank on that in a while. 
i deleted it from the accounts section. that was the first option i found to delete the data. but it is gone now. so im good. thx again.
