### ISSUE TITLE
Custom categories are not showing up

### ISSUE THREAD

**Issue by YakeG** [arkayenro/arkinventory#1469]
Hello,
screenshot of the issue below the text.
Version of the addon is 3.09.51-BurningCrusade
I reinstalled arkinventory after some addon troubleshooting but when I reinstalled it & tried to re-make my custom categories, they refused to show up in the list when assigning it to items. Disabled all my other addons to see if something was conflicting, but the issue persists with only arkinventory active.
Tried going back to earlier versions, but this same issue stays.
![WoWScrnShot_070421_115058](https://user-images.githubusercontent.com/86911524/124381086-e2b0c800-dcc0-11eb-8270-45650b28ca29.jpg)

**Comment by arkayenro** [comment]
custom categories arent global so its opening the category sets, which is where the custom categories live.  its the same as going to config > settings > category sets

ie, youve created a category set called shaman things, not a custom category.

go back to the default category set (i presume thats what youre using), then type in the name of the custom category you want to add, but in the add field under the custom category tab

**Comment by arkayenro** [comment]
you can check the tooltip for the field beforehand to make sure its the right one, it should say add a new custom category

**Comment by YakeG** [comment]
That worked :) Turns out I did do it completely wrong, hehe
Thank you for the help <3
