### ISSUE TITLE
Help with importing a profile

### ISSUE THREAD

**Issue by Dreadscore** [arkayenro/arkinventory#1470]
i cant seem to understand how to import's a streamer's profile he gave me, ive tried looking it up, cant find the answer. is it not possible to just copy an entire profile from some1 else if he shared his exported text with me? help me please

**Comment by arkayenro** [comment]
under config > settings > design there is an import button, does that not work?

what text string were you given?

**Comment by arkayenro** [comment]
if they shared an entire saved variables file then you can just swap it with yours but youll lose everything that was in yours.  so take a backup of yours first.

**Comment by arkayenro** [comment]
import/export has been redone and is working in 30952

old exports will not work, they will need to be exported again

**Comment by Gogo1951** [comment]
Hey @Dreadscore , a lot of times when someone shares a profile over Discord, the Discord markdown formatting fucks it up.

Make sure they "code" it to send it. 

Add ``` to the start and end of the profile hash.

https://www.markdownguide.org/basic-syntax
