### ISSUE TITLE
Bags don't show new items looted / acquired

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1473]
With ArkInventory:

![image](https://user-images.githubusercontent.com/55365231/124962651-801f3b00-dfe4-11eb-88c1-84d2186578ec.png)

Without:

![image](https://user-images.githubusercontent.com/55365231/124962943-d68c7980-dfe4-11eb-9787-6c80d8661a98.png)

Note the bullets are showing a different item. I did a few dungeons and picked up a ton of stuff and none of it showed in my bags at all.

**Comment by arkayenro** [comment]
do you have another bag mod running or is that just a skin?  multiple bag mods can be problematic.

as far as i can see the bullets are the only difference? but that doesnt really help either way.  in AI can you pick them up and move them?  do they update if you do?

can you check the AI config and make sure that monitor is ticked for the backpack location?

**Comment by Gogo1951** [comment]
I have ElvUI, but the bag portion is disabled. Also running TSM, with mailing operations, and GogoLoot for looting, but it doesn't really do much with the inentory in bags, just the loot window. 

I can't interact with anything "invisible" in my bag. Like if I click on it, nothing happens. All that I've added were the new bullets, and sold the old ones. When I shift click to split the stack, nothing happens. I can still interact with "old" items and split those stacks. But when I kill mobs nothing shows up in the bag, and it's not refreshing properly since it still shows the old bullets that I vendored as being present.

Only thing that I can tell has changed since I started having the issue is the latest update for ArkInventory.

![image](https://user-images.githubusercontent.com/55365231/125003128-276b9480-e01c-11eb-884b-ac2791e17063.png)

Game is literally unplayable without ArkInventory man! Ha. It's torture to use the interface without it. Oh god, how does anyone find anything?

**Comment by arkayenro** [comment]
is it classic or burning crusade?

can you disable everything except AI so and see if its updating when you buy something from a vendor then sell it back?

**Comment by Gogo1951** [comment]
Happens on Druid too.

![image](https://user-images.githubusercontent.com/55365231/125004185-98ac4700-e01e-11eb-90a5-7b52d8c7dba6.png)

Disabled all other addons. Only ArkInventory is running. Doesn't show the quest item I picked up.



![image](https://user-images.githubusercontent.com/55365231/125004225-b37ebb80-e01e-11eb-8fcc-1161ee4efaee.png)

**Comment by arkayenro** [comment]
oh, its a burning crusade issue.

**Comment by arkayenro** [comment]
looks like bcc and classic cant handle large integers so i had to recode it a bit.

the fix will be in the next update.  you should be able to go back an alpha version to get in working in the mean time.

**Comment by Gogo1951** [comment]
Thanks!

**Comment by arkayenro** [comment]
alpha 30951.4 should now be available to download
