### ISSUE TITLE
Error when I mouse over quest reward anima icon 

### ISSUE THREAD

**Issue by digitalmuze** [arkayenro/arkinventory#1474]
Only occurs at the quest giver, when quest is offered; error does not occur when I mouse over anima icon quest reward in my quest log.

233x ArkInventory\ArkInventory-30951.lua:6693:  invalid frame
[string "=[C]"]: in function `assert'
[string "@ArkInventory\ArkInventory-30951.lua"]:6693: in function <ArkInventory\ArkInventory.lua:6691>
[string "=(tail call)"]: ?
[string "@AnimaShortage\Patches.lua"]:46: in function `DrawToolTipAnima'
[string "@AnimaShortage\Hooks.lua"]:43: in function `DrawToolTipAnimaForCompatibleAddons'
[string "@AnimaShortage\Hooks.lua"]:22: in function <AnimaShortage\Hooks.lua:18>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
...
[string "=[C]"]: ?
[string "@Vendor\sys\hook.lua"]:54: in function <Vendor\sys\hook.lua:50>
[string "@TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua"]:499: in function <...TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:493>
[string "=[C]"]: ?
[string "@TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua"]:98: in function <...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua"]:425: in function `SetQuestItem'
[string "@FrameXML\QuestInfo.lua"]:1070: in function <FrameXML\QuestInfo.lua:1055>

Locals:
(*temporary) = nil
(*temporary) = " invalid frame"

**Comment by arkayenro** [comment]
there was a blizzard issue in beta that was sort of like that,  quest reward links were broken but im not seeing it on my end so maybe its an issue with either animashortage, tsm or theunderminejournal mods as they all interacted with it.

can you disable both of those and see if AI still has an issue with anima rewards?

**Comment by digitalmuze** [comment]
Confirmed; this mouse over error stops when I deactivate Anima Shortage addon. Thanks for the tip!
