### ISSUE TITLE
Gearquipper outfits not being recognized.

### ISSUE THREAD

**Issue by falcon1209** [arkayenro/arkinventory#1479]
Using the outfit() method within ArkInventory does not successfully recognize GearQuipper outfits.
![image](https://user-images.githubusercontent.com/8881729/125498065-a45cc142-dafe-4a44-8ef8-1540267bffb9.png)

**Comment by arkayenro** [comment]
classic or tbc?  quesrquipper has two different versions.

it was working before but its possible that something has changed.

**Comment by falcon1209** [comment]
This is within TBC classic.

**Comment by arkayenro** [comment]
13 in tbc appears to be working ok for me.

if you mouseover the item in the bag is there a line on the tooltip for the gearquipper sets, and is "cat" listed?

**Comment by falcon1209** [comment]
Yeah, even the outfit( ) method doesnt return any of the items registered  to addons. I'll do some addon isolation and see if I can still replicate the issue on minimal addon usage. (AI + GQ + Libs)

**Comment by falcon1209** [comment]
I found the problem. Itemrack was also installed but I never removed it prior to my switch to Gearquipper. Thought I did. Not sure if this is an edge case you'd like to fix or not but there it is. Thanks for your support.
