### ISSUE TITLE
I hope someone here can help me

### ISSUE THREAD

**Issue by RealOkami** [arkayenro/arkinventory#1481]
getting lots of luaerrors while looting

`Message: Interface\AddOns\ArkInventory\ArkInventory.lua:6713:  invalid frame
Time: Thu Jul 22 11:13:12 2021
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventory.lua:6713:  invalid frame
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "@Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149: in function <...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147>
[string "=[C]"]: ?
[string "=[C]"]: in function `assert'
[string "@Interface\AddOns\ArkInventory\ArkInventory.lua"]:6713: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:6711>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\AnimaShortage\Patches.lua"]:46: in function `DrawToolTipAnima'
[string "@Interface\AddOns\AnimaShortage\Hooks.lua"]:43: in function `DrawToolTipAnimaForCompatibleAddons'
[string "@Interface\AddOns\AnimaShortage\Hooks.lua"]:22: in function <Interface\AddOns\AnimaShortage\Hooks.lua:18>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua"]:107: in function <...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetLootItem'
[string "@Interface\AddOns\ElvUI\Modules\Misc\Loot.lua"]:50: in function <Interface\AddOns\ElvUI\Modules\Misc\Loot.lua:46>

Locals: errMsg = "Interface\AddOns\ArkInventory\ArkInventory.lua:6713:  invalid frame"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}
`

**Comment by arkayenro** [comment]
disable AI and youll still get the error.  its probably not tsm, so you could try disabling animashortage.

it might be calling the AI frame directly, which might work most of the time but its not something i ever intended to happen

**Comment by RealOkami** [comment]
animashortage was the culprit i think thanks
