### ISSUE TITLE
FPS drop when looting

### ISSUE THREAD

**Issue by awedy01** [arkayenro/arkinventory#1482]
Hello! I am not sure if its a bug or its my PC, but i want to report it here:
I have FPS drops (5-10 fps) (from 60 to 50, etc) when i loot a mob. The more mob i loot, the more fps loss happens for about a second or two.
I tested with turning off all addons, only having ArkInventory ON and yep, its the cause for sure.
I like that addon and if its my pc's problem, still i wonder if you have a suggestion how to fix that, what to set in ArkInventory to stop this.

**Comment by arkayenro** [comment]
check if sorting is still set to the default of instantly and change it to on open or manual

config > settings > design > the one you use for the bag > window > sorting > when = something that isnt instant

when its set to instant it recalculates the window on every change, even if its not open

**Comment by awedy01** [comment]
I wanted to respond here to let you know i will have further investigations to this case.
Right now i checked config & it was set to Instantly, but i dont find "design" option anywhere.
What i checked is:
/arkinventory config > Advanced > Update Timers
/arkinventory config > Settings > Window > Sorting (Was instant, i set to "on open")

I will see if those cause anything cuz on fresh start up i dont yet see the fps spikes, later in the afternoon i will make sure to investigate it.

**Comment by awedy01** [comment]
Yeah so now my settings are:
Sorting = On Open
Update Timer = 2.05 seconds
Still i have the 5-10fps loss on looting.

**Comment by arkayenro** [comment]
do you have the same fps loss just moving things around in your bag?

**Comment by arkayenro** [comment]
if youve changed the update timer to 2 seconds then does the fps loss happen two seconds after you start looting or immediately?

**Comment by arkayenro** [comment]
you can also set the sorting to manual and see if the fps drop still happens - it might still happen on the first bag open but it shouldnt happen after that if its due to the container calculations

**Comment by awedy01** [comment]
I can confirm that there is no FPS drop in the morning (9 AM right now).
Sounds weird when we talk about looting, during test i loot alone, noone around me, etc.. but yesterday & today when i tested i could not have any FPS drop.. however when i went online about 5 PM, when i assume a lot of player are online, there will be FPS drop if i loot. 
I will respond to your questions later when i can replicate it once again.

**Comment by arkayenro** [comment]
you sure its not just basic loot lag?  thats starting to happen a lot more often now in korthia and the maw, and i've had it happen when no one else was around.  i dont check if the fps drops at the same time though.

**Comment by awedy01** [comment]
I dont talk about the loot lag which started happening every afternoon in Korthia (when there are many ppl on), its server lag, i just reported it to Blizzard support cuz they might ignore forum reports from people, haha.
I am sure the thing i reported to YOU is caused by ArkInventory in some way as its FPS drop, not lag + it does not happen without the addon. I will record it today & upload here so you can see very clearly whats happening.

**Comment by awedy01** [comment]
I couldnt do the record yesterday as there were latency issues on my realm the whole day.
Today its fixed so i took the chance
First the record with normal use of my addons
Second/Third loots are ONLY with ArkInventory, (in second try there was barely anything to loot so i had to grab more mobs for guaranteed loot in the third try)
In the third try you can see exactly losing 12 FPS with only ArkInventory, same as how much i lost with all addons ON in first try.
Then for last i turn off all addons and you can see 0 FPS drops at all with a lot of mobs, which supposed to mean that its not wow or my pc's trouble.
https://youtu.be/3FtkIE4obvw

**Comment by arkayenro** [comment]
mine drops down from 100 to 95, the more items the more it drops, buts its not for long, unless theres loot lag as well.  it does have to process the new/updated items.

you could always bump up your foreground fps to 70 and set the required fps to 60, see if that helps?

i guess the question is what are you expecting to happen?  no fps loss its not possible, there will always be some.  and is it affecting your gameplay?  ie if you loot while still playing does it impact what you are doing?

**Comment by awedy01** [comment]
What do i expect to happen:
No fps drop on looting. Thats what happens without ArkInventory, thats what happens without addons, and i just dont understand why fps drop happens with ArkInventory when its set to "sorting on next open" etc..
The thing we talk about is different, its not rly breaking gameplay but very annoying.
If you carefully check my video, you dont just see fps loss, you actually see freeze-like problem. When screen freeze for a little moment if i start moving right after loot.

Of course i have drop to 40 FPS if i am at some positions of Korthia but thats nonstop fps loss and not a stutter? not sure if thats the word. What i mean that even with 40 FPS on those places i can normally play just as you say cuz screen wont freeze for a single second. But with looting it actually freezes and it might not cause me to die to horde but still a very annoying and most importantly it does not happen without ArkInventory, so what do i expect is that screen freeze to not happen

I can of course live with it as i like this addon very much but i just report it as its a bug caused by the addon.
Remember: It is expected to NOT happen if update timer set to 2s & sorting to "on open / manual" > still happens > problem.

**Comment by awedy01** [comment]
If screen freeze would only happen on inventory opening case, i dont mind, but it happens on each single looting case, thats the problem, not simple FPS loss, but actual screen freeze.
I dont mind fps loss if its not stopping my screen.
Note: It happens to my partner aswell, who has stronger PC & different card(amd)
(I have nvidia)

**Comment by arkayenro** [comment]
the screen might go laggy but it should never freeze.  if arkinventory is causing the freezing then i would expect the thread timer values are too high and its spending too much time processing instead of yielding so that the game can update the display.

especially if this is happening just on bag updates, not window calculations/draws.  bag updates are minimal processing, they should only ever cause a minor dip.

go to config > advanced > threads and make sure the three values are set to 75/100/25 - those should be low enough for any machine to cope, but feel free to lower them all down to 25 (the minimum), especially the combat one if thats where its impacting more.

the update timer is also a cycle, its not explicitly triggered x seconds after the update happens, its where in that x second cycle the timer is at before it will trigger next.  its not an overly helpful setting for screen freezes.

i will add some more yielding into the scan code, so it yields every slot, not every bag, which may, or may not, help.

my machine is a 4+4 core i7 with a gtx960 running in 3440x1440 at 100fps.  yes it struggles, im pushing it too hard, but its only getting 2-15fps drops when looting and the screen and playability is always fine.

**Comment by arkayenro** [comment]
could you try [30952.7](https://www.curseforge.com/wow/addons/ark-inventory/files/3408272) and see if it helps or not

**Comment by awedy01** [comment]
![image](https://user-images.githubusercontent.com/57992981/127764711-a141343a-71b8-4266-a277-574b30e4e3b9.png)
https://www.curseforge.com/wow/addons/ark-inventory/download/3408272
If you meant this version (r1131-alpha)
I had 12 FPS dropped with screen stuttering by looting the amount of loot on the picture
Config is set to sort "on open"

**Comment by arkayenro** [comment]
delete the `_retail_\Cache` folder

in the `_retail_\WTF\Account\youraccountname\SavedVariables folder`
* rename the `ArkInventory.lua` file to `ArkInventory.lua.old`
* rename (if it exists) the `ArkInventory.lua.bak` file to `ArkInventory.lua.bak.old`

see if it still has issues with everything on defaults.

the cache will rebuild, and you can delete the new ArkInventory files and then rename the `.old` ones back to put things back the way they were

**Comment by awedy01** [comment]
We tested it all as you asked.
The FPS loss is even more serious for my partner who has 100+ FPS & he get down to 70 when loots with DEFAULT configs both alpha & the "official" versions. Right now with the alpha version's default settings, he got 111 FPS to 60
I get 60 (vsync on) to 49
Both screen lag & fps drop as you can see on my video.

The problem is occuring no matter if combat or no combat
It is occuring on LOOT with BAG CLOSED.



Settings 75 / 100 / 25
Debug on for me, partner not (still both happens the fps drop & screen stuff)

[15:21] ArkInventory: THREAD> p08-tooltip starting 
[15:21] ArkInventory: THREAD> p08-tooltip dead after 0.07ms (0.07ms) 
[15:21] ArkInventory: THREAD> p08-tooltip: clearing (state is dead) 
[15:22] You receive loot: [Flowing Ridge Spikes] 
[15:22] You receive loot: [Marred Skin]x2 
[15:22] You receive loot: [Tenebrous Ribs] 
[15:22] ArkInventory: THREAD> p04-scan-1-2 starting 
[15:22] ArkInventory: THREAD> p04-scan-1-3 starting 
[15:22] ArkInventory: THREAD> p04-scan-1-2 dead after 28.26ms (28.26ms) 
[15:22] ArkInventory: THREAD> p04-scan-1-2: clearing (state is dead) 
[15:22] ArkInventory: THREAD> p04-scan-1-3 suspended after 137.86ms (137.86ms) 
[15:22] ArkInventory: THREAD> p04-scan-1-3 dead after 5.97ms (143.84ms) 
[15:22] ArkInventory: THREAD> p04-scan-1-3: clearing (state is dead) 
[15:22] ArkInventory: THREAD> p05-draw-1 aborting, not visible 
[15:22] ArkInventory: THREAD> p05-draw-6 aborting, not visible

--------------------------------------------------------

Threading off > same drop + screen stutter

-------------------------------

With 25/25/25
The problems are a bit worse, or just more loot, not sure

----------------------------
Actually it seems THREADING has NO affect on this case at ALL, not sure if i just dont notice it, or it does not work as intended, but surely no affect.
----------------------------

SIDE NOTE
![image](https://user-images.githubusercontent.com/57992981/127772664-014b7b9f-63c1-4903-8958-aa4416db947e.png)
It does not allow Building Tooltips higher than 250 but says to set between 25-5000 (not a problem but wanted to note it in case its not intended)

Overall i can tell you, the alpha version seem to work better, but there is a big second screen freeze on bag EACH bag open nonstop.
If changes happen & you open bag, its understand if there is a drop/screen freeze for a second
But the screen freeze happen without any changes, just closing then opening the bag again. Default settings, except threads: 5000/250/250

Anyway, on paper, people do not fight when they have time to loot, so this problem should NOT cause any serious thing.
>>>>We can close the issue, Alpha version works better on this case for sure.<<<<
I am happy to see there are addon creators like you, who respond, try to help, etc..
Keep up the good job, love the addon!

**Comment by chodyo** [comment]
I'm experiencing the same problem so I filed a new ticket in #1830
