### ISSUE TITLE
Classic WoW - Doing a restack when you are dead crashes client

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1483]
I did a restack when I was dead, and it tried and put the restack in a loop and eventually crashed the client.

**Comment by arkayenro** [comment]
just while dead though, works ok once youre a ghost.

i'll add a check to make sure it aborts if youre dead.

**Comment by arkayenro** [comment]
will be fixed in the next alpha/release

**Comment by arkayenro** [comment]
fixed in 3.09.55
