### ISSUE TITLE
Error seit heutigen update 12.08

### ISSUE THREAD

**Issue by 13Balu02** [arkayenro/arkinventory#1487]
![grafik](https://user-images.githubusercontent.com/87585558/129220083-0fdb6813-95b8-4277-bb30-33693751b857.png)
und 
![grafik](https://user-images.githubusercontent.com/87585558/129220148-c8df81d0-db2b-46f5-b4ce-d1ac9776469f.png)

**Comment by H8Core** [comment]
Hi @13Balu02 
same problem here

Selbes Problem habe ich auch -.-

**Comment by Morwo01** [comment]
same here

**Comment by KaynXXX** [comment]
same problem here

**Comment by ReglohPri** [comment]
Same here

**Comment by H4waiian** [comment]
gleiches Problem hier .. habe das Addon deinstalliert und wieder installiert .. nun lädt es gar nicht mehr und ich habe die normalen Rucksackfenster wieder ...

**Comment by Proteyer** [comment]
`Message: Interface\AddOns\ArkInventory\ArkInventory.lua:4590: attempt to index field '?' (a nil value)
Time: Thu Aug 12 20:36:22 2021
Count: 15
Stack: Interface\AddOns\ArkInventory\ArkInventory.lua:4590: attempt to index field '?' (a nil value)
[string "@Interface\AddOns\ArkInventory\ArkInventory.lua"]:4590: in function `Frame_Main_OnLoad'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>

Locals: frame = ARKINV_Frame16 {
 0 = <userdata>
 ARK_Data = <table> {
 }
 ArkBorder = ARKINV_Frame16ArkBorder {
 }
}
framename = "ARKINV_Frame16"
loc_id = nil
tex = <unnamed> {
 0 = <userdata>
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 0 = <table> {
 }
 7 = <table> {
 }
 1 = <table> {
 }
 2 = <table> {
 }
 4 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 5 = <table> {
 }
 3 = <table> {
 }
 6 = <table> {
 }
}
(for control) = 0
k = 0
v = <table> {
 Name = "Menü"
 Scripts = <table> {
 }
}
obj = ARKINV_Frame16TitleActionButton0 {
 0 = <userdata>
}
(*temporary) = <function> defined @Interface\AddOns\ArkInventory\ArkInventory.lua:6663
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = "0"
(*temporary) = "ARKINV_Frame16TitleActionButton0"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
string = <table> {
 split = <function> defined =[C]:-1
 match = <function> defined =[C]:-1
 gmatch = <function> defined =[C]:-1
 upper = <function> defined =[C]:-1
 gsub = <function> defined =[C]:-1
 format = <function> defined =[C]:-1
 lower = <function> defined =[C]:-1
 sub = <function> defined =[C]:-1
 gfind = <function> defined =[C]:-1
 rep = <function> defined =[C]:-1
 char = <function> defined =[C]:-1
 rtgsub = <function> defined @Interface\FrameXML\RestrictedInfrastructure.lua:612
 join = <function> defined =[C]:-1
 reverse = <function> defined =[C]:-1
 byte = <function> defined =[C]:-1
 trim = <function> defined =[C]:-1
 len = <function> defined =[C]:-1
 find = <function> defined =[C]:-1
}
pairs = <function> defined =[C]:-1
_G = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @Interface\FrameXML\ActionButton.lua:78
 ERR_OUT_OF_CHI = "Nicht genügend Chi"
 DH_HAVOC_CORE_ABILITY_2 = "Starker Nahkampfangriff. Verbraucht Jähzorn. Kritische Treffer erstatten einen Teil des Jähzorns zurück."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Namen von Einheiten einfärben."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 746
 AllTheThings-SettingsScrollUpButton = AllTheThings-SettingsScrollUpButton {
 }
 SPELL_FAILED_CUSTOM_ERROR_71 = "Dieser Partygast möchte mit Euch tanzen."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 402
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Für diese Community können keine weiteren Einladungslinks generiert werden."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "Mit von Euch angelegten Taschen könnt Ihr nicht handeln."
 PVP_RANK_6_1 = "Fußknecht"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture {
 }
 VideoOptionsFrameDefaults = VideoOptionsFrameDefaults {
 }
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Vordefinierte Tastaturbelegungen für Aktionen reagieren bei gedrückter statt bei losgelassener Taste."
 BINDING_NAME_N`
`Message: ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:1553: code failure: loc_id is nil
Time: Thu Aug 12 20:36:20 2021
Count: 14
Stack: ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:1553: code failure: loc_id is nil
[string "=[C]"]: in function `assert'
[string "@Interface\AddOns\ArkInventory\ArkInventoryStorage.lua"]:1553: in function `InternalIdToBlizzardBagId'
[string "@Interface\AddOns\ArkInventory\ArkInventory.lua"]:9490: in function `Frame_Changer_Slot_OnLoad'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface\AddOns\ArkInventory\ArkInventory.lua"]:9197: in function `Frame_Changer_OnLoad'
[string "*:OnLoad"]:3: in function <[string "*:OnLoad"]:1>

Locals: (*temporary) = false
(*temporary) = "code failure: loc_id is nil"
`
`Message: ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:1553: code failure: loc_id is nil
Time: Thu Aug 12 20:36:20 2021
Count: 8
Stack: ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:1553: code failure: loc_id is nil
[string "=[C]"]: in function `assert'
[string "@Interface\AddOns\ArkInventory\ArkInventoryStorage.lua"]:1553: in function `InternalIdToBlizzardBagId'
[string "@Interface\AddOns\ArkInventory\ArkInventory.lua"]:9490: in function `Frame_Changer_Slot_OnLoad'
[string "@Interface\AddOns\ArkInventory\ArkInventory.lua"]:9312: in function `Frame_Changer_Vault_Tab_OnLoad'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface\AddOns\ArkInventory\ArkInventory.lua"]:9197: in function `Frame_Changer_OnLoad'
[string "*:OnLoad"]:3: in function <[string "*:OnLoad"]:1>

Locals: (*temporary) = false
(*temporary) = "code failure: loc_id is nil"
`
`Message: ...ace\AddOns\ArkInventorySearch\ArkInventorySearch.lua:155: attempt to compare two nil values
Time: Thu Aug 12 20:36:23 2021
Count: 1
Stack: ...ace\AddOns\ArkInventorySearch\ArkInventorySearch.lua:155: attempt to compare two nil values
[string "@Interface\AddOns\ArkInventorySearch\ArkInventorySearch.lua"]:155: in function `Frame_Table_Build'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>
[string "=[C]"]: ?

Locals: frame = ARKINV_SearchFrameViewTable {
 0 = <userdata>
 ArkBorder = ARKINV_SearchFrameViewTableArkBorder {
 }
}
f = "ARKINV_SearchFrameViewTable"
maxrows = nil
rows = nil
height = 24
(*temporary) = ""
(*temporary) = nil
(*temporary) = "."
(*temporary) = ""
(*temporary) = ""
(*temporary) = 2
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare two nil values"
`
`Message: Interface\AddOns\ArkInventory\ArkInventory-30953.lua:3958: bad argument #2 to 'format' (string expected, got nil)
Time: Thu Aug 12 20:36:37 2021
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventory-30953.lua:3958: bad argument #2 to 'format' (string expected, got nil)
[string "@Interface\AddOns\ArkInventory\ArkInventory.lua"]:3401: in function `Frame_Main_Generate'
[string "@Interface\AddOns\ArkInventoryRules\ArkInventoryRules.lua"]:119: in function <...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:98>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\ArkInventory\ArkInventory.lua"]:10397: in function `LoadAddOn'
[string "@Interface\AddOns\ArkInventory\ArkInventory.lua"]:10412: in function `BlizzardAPIHook'
[string "@Interface\AddOns\ArkInventory\ArkInventory.lua"]:2712: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:2682>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>`

**Comment by arkayenro** [comment]
its because the thousands separator in your language is a period (.) and in regex that matches every character so when it replaced it it turned everything into an empty string.

will be fixed in the next release, which i will upload in a minute

**Comment by arkayenro** [comment]
3.09.54 has been uploaded.  please confirm it is fixed in that

**Comment by Morwo01** [comment]
works

**Comment by H8Core** [comment]
yihhaaa, works perfectly @arkayenro

**Comment by ReglohPri** [comment]
It works for me again.
