### ISSUE TITLE
ArkInventoryConst.lua:1224: malformed patten

### ISSUE THREAD

**Issue by IKnewOne** [arkayenro/arkinventory#1488]
Version 3.09.54, russian client
![image](https://user-images.githubusercontent.com/41551327/129284002-91de4642-b4d0-4a5a-aa16-184162a6d2f3.png)

**Comment by arkayenro** [comment]
sorry, go back to .53 for the moment, i need to fix the code again so it can handle having no thousands separators without breaking the other languages
