### ISSUE TITLE
How to merge items from Vendor addon to ArkInventory auto sell

### ISSUE THREAD

**Issue by awedy01** [arkayenro/arkinventory#1495]
**What version number you are using?**
3.09.55

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail / Live

**What language is the game client set to?**
English

**Ask your question**
How can i merge the items to be sold from VENDOR addon into ArkInventory Auto sell?
I would stop using Vendor Addon since ArkInventory is just good enough but i collected a ton of item into Vendor to be sold.

**Comment by arkayenro** [comment]
is the addon actually called vendor?  i've linked to some other selling addons so it can tell what is junk from those, i can always add another one.

if you want to export/import the data then that might be possible but you'd need to know your way around the saved variables file and update that manually

**Comment by awedy01** [comment]
This is the addon: https://www.curseforge.com/wow/addons/vendor
Yes, it is exactly called: Vendor
It has support to ArkInventory which is never understood what it is for, but i dont want to use that addon(vendor) anymore because ArkInventory can do the auto sell aswell.
My problem is that i have a ton of items in this addon which i worked on to always sell. I want to copy-paste them into ArkInventory, but it uses a different coding style for this. I know my way in Vendor's lua but to make sure you understand my situation, i will publish my list here:
[vendor_sell_destroy_list.txt](https://github.com/arkayenro/arkinventory/files/6987029/vendor_sell_destroy_list.txt)
The content of this txt is copied from Vendor.lua. Thats all it needs to auto sell/destroy the items.
The reason of my question is the difference in ArkInventory's lua file.
So once again: How can i put this list into ArkInventory?
I am fine with adding any extra numbers or whatever with notepad++ or something, just dont know what i should modify in the list to have it working in ArkInventory.

**Comment by arkayenro** [comment]
open the config
settings > categorysets > open the one you are using
add a new custom category
enable it and turn on auto sell
close the config
open the bag and enable edit mode
assign the new category to a bar
assign your hearthstone to that category
exit wow

edit the saved variables file and search for `"catset"`
there should be an entry under this section for `"item:6948:1"`
this is where you need to add your data - once youve put it in the correct format

`["item:<itemid>:<soulbound>"] = "<categoryid>"`

you already have the item id, and categoryid can be got from the hearthstone entry that should be there (should be something like `"3!xxx"`) - delete that line before youre done

soulbound is either 0 (no) or 1 (yes) - that youll need to figure out

then save it and start wow

go into the config and check that all your items are listed under that category

alternatively you can do then one at a time from the config when you edit the custom category you can edit what items are in it there

**Comment by arkayenro** [comment]
note - backup your current saved variables file before you do anything

**Comment by awedy01** [comment]
Well, it is partially working with the latest OFFICIAL release.

[09:11] ArkInventory: Selling: 2 x [Fortified Antennae] for 2 41 10 
[09:11] ArkInventory: Selling: 5 x [Pitted Diaphanous Wing] for 1 90 60 
[09:11] ArkInventory: Selling: 4 x [Marred Skin] for 1 41 
[09:11] ArkInventory: Selling: 1 x [Irridescent Eye] for 15 77 36 
[09:11] ArkInventory: Selling: 3 x [Shredded Documents] for 5 69 91 
[09:11] ArkInventory: Selling: 4 x [Squished Mawshroom] for 5 11 16 
[09:11] ArkInventory: Selling: 1 x [Brittle Bark] for 38 84 
[09:11] ArkInventory: Selling: 6 x [Small Gromit Bones] for 7 23 72 
[09:11] ArkInventory: Selling: 1 x [Spindly Flesh] for 37 80 
[09:11] ArkInventory: Selling: 1 x [Augmented Femur] for 17 27 29 
[09:11] ArkInventory: Sold your junk items for 17 65 09.

It sells my Junk but it sells NOTHING from the CustomJunk i created.
I say partially working cuz i added items which i have in inventory to test & they are added to the category but not being sold.

![image](https://user-images.githubusercontent.com/57992981/129470309-89491e80-61b6-4467-b3f6-4b51eb51bcf6.png)

**Comment by arkayenro** [comment]
are the items its not selling above the base junk sell values?

**Comment by awedy01** [comment]
Yeah, you are right! 
![image](https://user-images.githubusercontent.com/57992981/129482462-aef11213-c41e-4cf9-ad72-8ca1dd67cda3.png)
I thought i cannot change it because Poor has exact same color which is used to "blocked" things what u cannot change.
It works perfectly, but i encountered a bug
USING THE LAST VERSION alpha 7 ? I believe, you just shared on my bug report 1 hour ago
When i buy back the sold item, it wont be shown in the bag even after re-opening it.

**Comment by awedy01** [comment]
reported the bug in my opened BUG topic.
