### ISSUE TITLE
4[BUG] Latest update TBC broke soulbound() rule command (Update: Client was missing the item data/cache.)

### ISSUE THREAD

**Issue by Bananaman** [arkayenro/arkinventory#1497]
**What version number you are using?**
v3.09.54 [The burning crusade]

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
TBC

**What language is the game client set to?**
English

**Describe the bug**
After the update, my rule functions broke. They no longer properly ignore items when I say `not soulbound()` in the rule. Soulbound items get sorted into it. I love the new update in all other ways, the new itemlevel text on top of items is awesome!

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Use my rule functions:

Rule 1:
- Name: Equipment: Soulbound
- Order: 10
- Rule: `equip() and soulbound()`

Rule 2:
- Name: Equipment: Not Soulbound, Not Tools, Not Trash
- Order: 11
- Rule: `equip() and not soulbound() and not quality(0) and not itemstring(6256, 6365, 7005, 2901)`

**Screenshots**
This screenshot shows soulbound items sorted into my `and not soulbound()` group now. :(
![image](https://user-images.githubusercontent.com/38923130/129459884-50a9f893-bbde-4997-b64e-89d751afa12f.png)

**Additional context**
My groups are set to only have 1 rule each. The rules are activated. Soulbound items are not being sorted into the "equip and soulbound" group. And soulbound items are being sorted into the "equip and not soulbound etc..." group.

**Comment by Bananaman** [comment]
These functions worked before. They broke after the latest update which added the nice item level strings to item icons.

**Comment by Bananaman** [comment]
I am not sure if the soulbound check is the actual reason for the bug, by the way, but it is my strongest suspicion because it is the major difference between these groups, and the fact that "and not soulbound" rule now contains soulbound items.

**Comment by arkayenro** [comment]
enable edit mode and click on the item, select debug and check what the data ready value is set to.

if its false then the rules will not process it until its data gets loaded and this is set to true

**Comment by Bananaman** [comment]
@arkayenro Hi! 😄 

I went in to do that now, and noticed that the items are all in their correct spots. I haven't updated/changed the addon at all.

So your theory is right, the item data must have been non-ready/old cache.

Yesterday, this problem was "sticky". It didn't matter how many times I logged out and in to that character, the items were still in the wrong groups.

Today it's fixed by itself.

We can close this ticket.

**Just wondering: Is there any command for erasing/forcing a refresh of all item data, if this happens in the future?**

**Comment by arkayenro** [comment]
right click on the refresh icon, there should be a clear item cache option i think

**Comment by arkayenro** [comment]
should be fixed in [alpha 8](https://www.curseforge.com/wow/addons/ark-inventory/files/3428782)

**Comment by arkayenro** [comment]
try [alpha 10](https://www.curseforge.com/wow/addons/ark-inventory/files/3430371), that should fix the last of the issues, and stop the debug output as well

**Comment by Bananaman** [comment]
> right click on the refresh icon, there should be a clear item cache option i think

Sorry about late reply. Your refresh icon command worked. So yep it was simply an outdated cache. :)
