### ISSUE TITLE
Glitch with Skillet at char login (AI “loading…” window)

### ISSUE THREAD

**Issue by tflo** [arkayenro/arkinventory#1502]
AI version 3.09.55 on WoW Retail, English.

***

After 2 years or so I re-tried AI and I’m pleasantly surprised. Probably it will replace my trusty AdiBags… (and maybe Armory too)

However, I noticed a serious glitch with Skillet:

When my toon enters the world, AI does something that looks like opening the Crafting frame for a fraction of a second. 

This works fine as long as Skillet is not loaded. If Skillet is loaded, AI is completely unusable: Opening the bag results in a never-ending “loading…” window, and if I open the Professions frame, I see the first Profession button flickering (as if someone or somewhat is clicking it at high frequency).

This probably happens because Skillet is hijacking the Crafting frame. (To open the Blizz Crafting frame while Skillet is loaded you would have to Shift-click the Profession button.)

I don’t know if it is normal that AI is opening the Crafting frame at char login, but I guess so, because it happens also when only Skillet and AI are loaded. So, very likely not a conflict with other mods.

Well, I managed to help myself efficiently by loading a mini-mod (after Skillet has loaded) that does exactly this: `Skillet:Disable()`. Everything and also AI works fine then; I have to manually enable Skillet via macro afterwards, if I need it, but that’s OK.

First: Can you reproduce the glitch with Skillet?

Second: If Yes, would it be possible that you implement a couple of lines that do something similar as my mini-mod does? I.e. disabling Skillet before AI tries to open the frame, and optionally re-enable it again afterwards.

Thanks for reading and many thanks for the great add-on that AI is!

– Tom

**Comment by arkayenro** [comment]
open the config and go to the current profile
controls > professions
disable scan on load
possibly monitor as well if it has issues scanning the window when you open it manually

i'll have to install skillet to see if it does anything i have to work around

**Comment by arkayenro** [comment]
this part is really there just to track what items each character can create and show that in the tooltip. so if youre not overly fussed about that you can leave it disabled

**Comment by tflo** [comment]
Thanks for the pointer to the disable-scan setting, haven’t seen that.

However, since it is a good thing to keep the related tooltip info up to date, I’ll probably leave it enabled and stick to my `Skillet:Disable()` add-on. Maybe I’ll mod that into AI itself, so I don’t have to load a separate thing.

Ideally, I would like to see a less frequent scan. For example only at login, not at every UI reload, or – better – with a timer that prevents a scan if the last one was less than n hours ago. Just a thought.

Thank you.

**Comment by tflo** [comment]
Oh, I forgot the 

> possibly monitor as well if it has issues scanning the window when you open it manually

part.

What I can say is that there is no glitch when opening the Skillet window manually, but I don’t know if AI successfully scans. 
I have enabled AI’s Debug Mode, but it doesn’t put anything out to the console when I open the Skillet window manually. (Had expected to see something like “Profession scan finished.” or so.)

**Comment by arkayenro** [comment]
try [alpha 1](https://www.curseforge.com/wow/addons/ark-inventory/files/3442481)

**Comment by tflo** [comment]
> conflict with skillet. scan on load is now ignored if skillet is loaded and enabled

Thanks for the fix. I’ve tested it with Skillet enabled/disabled on reload, and it seems to work perfectly.

Independently of any potential conflict with AI, I’m still using my Skillet-disable mod, because it turned out that starting up with Skillet loaded but disabled is the ideal thing for me. (For quick & simple crafting I do not need Skillet and I have a toggle-Skillet macro in my Professions OPie ring, so it is quickly enabled whenever I need its features, without having to reload.)

Besides that, currently/experimentally I have disabled AI’s scan-on-load, because it happens too frequently for my taste.

But I think this fix is really important for all users who start up with Skillet and scan-on-load enabled, and would inevitably run into the old conflict otherwise.

> you have to open the blizzard tradeskill window to trigger a scan, it will not scan the skillet window

Thanks for that info. Since I’m currently relying on the manual scan, this is important to know.

***

Also thanks for posting the Alpha link here. For some reason CurseBreaker is not detecting the Alpha, albeit set to ‘alpha channel’. (Probably a curseforge issue.)
