### ISSUE TITLE
Error Message with Mining Pick?

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1503]
I see a bug message, but I don't see what caused it.

Mining Pick?

![image](https://user-images.githubusercontent.com/55365231/130306415-cba8c601-b557-436c-a650-58656a00680c.png)

![image](https://user-images.githubusercontent.com/55365231/130306427-28c16bd1-7471-40b3-99e4-72b976fb27c3.png)

![image](https://user-images.githubusercontent.com/55365231/130306435-5cad059a-b4b9-4ded-add0-3484e660787c.png)

**Comment by arkayenro** [comment]
it was a bank restack so it would have been something in the bank

**Comment by arkayenro** [comment]
i did find one place that error could trigger from, and thats when the bagtype returned is nil, not 0, so i've added some extra code to make sure it always returns 0 in that case.  that should stop it from treating it as a profession bag (non zero) when it isnt.

**Comment by arkayenro** [comment]
[alpha 11](https://www.curseforge.com/wow/addons/ark-inventory/files/3433093) should fix it

**Comment by Gogo1951** [comment]
No bug when I go to re-stack my bank. Thanks!
