### ISSUE TITLE
Equipment with a profession set bonus marked unusable [BUG] 

### ISSUE THREAD

**Issue by the-chuppa** [arkayenro/arkinventory#1507]
version: v30955.11 (Alpha) (this is not a new issue)
client: BCC

Equipment, which has a set bonus requiring a profession such as [Heavy Clefthoof Leggings](https://tbc.wowhead.com/item=25690/heavy-clefthoof-leggings), is tinted unsuable when the player does not have the required profession, even though the item itself is perfectly usable.

![image](https://user-images.githubusercontent.com/71234359/130346196-3297e909-d004-49ca-874d-9a6d7e6c92a7.png)

**Comment by arkayenro** [comment]
not an easy fix as its a perfect match for not actually being able to use it

**Comment by the-chuppa** [comment]
I'm no addon developer but from looking at your code it seem you're parsing the tooltip line by line and looking for a red line. How about you stop parsing the tooltip when you hit a set bonus line?

But now I thought about a similar issue - the profession-only enchants/gems. If I were to drop enchanting, my enchanted rings would say "Requires Enchanting...", but the ring would still be usable, only the enchant would not work.

**Comment by arkayenro** [comment]
i dont just scan straight down though.  i cater for recipes/patterns where the object created is also in the tooltip, and also potentially has level, class, skill, requirements you dont meet - but can create - so i scan down also looking for an empty line, if i hit one i go to the bottom and scan up - thats meant to get around the item in a recipe or pattern.

that has worked for everything so far - except set bonuses you dont meet

**Comment by arkayenro** [comment]
this should be fixed in 3.10.00 alpha 11
