### ISSUE TITLE
[BUG] Multiple ‘Unknown Object’ in search result

### ISSUE THREAD

**Issue by tflo** [arkayenro/arkinventory#1509]
AI 3.09.55 on WoW Retail, English

When doing a search, multiple ‘Unknown Object’ appear in the result list. These are only icons, without text. Happens also without any other add-ons loaded, and on different toons; search term doesn’t seem to matter. 

All ‘objects’ are reputation objects, see screenshot.

_IIRC_, this was not the case in the first time after I installed and configured AI, so I guess something in my setup is triggering this.

Example:

![WoWScrnShot_082321_124308](https://user-images.githubusercontent.com/1410282/130437115-1efcd3cd-02c3-4bdb-9dd7-73d75b5cfba9.jpg)

**Comment by tflo** [comment]
Since both issues are reputation related, can it be that this is also a sort of “extra mapping” like in https://github.com/arkayenro/arkinventory/issues/1511#issuecomment-904653362?

**Comment by arkayenro** [comment]
no, its probably left over data from an old reputation scan.  i just have to find a way to clean it up without losing the bits i need

**Comment by arkayenro** [comment]
should be fixed in [alpha 17](https://www.curseforge.com/wow/addons/ark-inventory/files/3438700)

**Comment by tflo** [comment]
Unfortunately the ‘objects’ are back. (3.09.56)

**Comment by arkayenro** [comment]
if you have a toon on the other faction can you login to that and then go back to this one
it might just need the data updated

**Comment by arkayenro** [comment]
also let me know what the object numbers are if it doesnt work

eg 1352 from your previous screenshot is Huojin Pandaren, so if its still showing that as unknown then logging into a horde character should resolve it

**Comment by tflo** [comment]
OK, logged into a couple of Hordies, and the unknown objects are gone again (for both faction’s toons).

Thank you!
