### ISSUE TITLE
[BUG] Some new cosmetics are categorized as soulbound

### ISSUE THREAD

**Issue by ghost** [arkayenro/arkinventory#1510]
**What version number you are using?**
*3.09.55 (xx-xxx-2021)*
* alpha 13

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail / Live

**What language is the game client set to?**
English

**Describe the bug**
Some new cosmetics arent showing as cosmetics. (Few names in "Additional context")

**To Reproduce**
Steps to reproduce the behaviour, if possible:
(Simply have one of those cosmetics)

**Screenshots**
![image](https://user-images.githubusercontent.com/57992981/130586246-43ff0a0f-4065-4143-8c09-7dd073deef55.png)

**Additional context**
The items i know about: Gilded Eye Crescent(187083), Gilded Skull Crescent(187082)
The reason i report it is: yes i can fix it on my own, but why not have it fixed for everyone.

**Comment by awedy01** [comment]
Also, i see you talk about Anima in changelog which is now not as "Covenant - Anima" but "Currency" :(
Loved that you automatically had all anima categorized as Anima
Now its all merged to "Currency". Is that what you wanted or its a bug?

**Comment by arkayenro** [comment]
cosmetic items should have an item class of cosmetic in the debug section as thats straight from blizzard.  i dont tooltip scan those.

anima should not be a currency.   it should be where it was

**Comment by arkayenro** [comment]
anima will be fixed next alpha/release

**Comment by arkayenro** [comment]
let me know what the type and subtype are for those two cosmetic items please

**Comment by awedy01** [comment]
![image](https://user-images.githubusercontent.com/57992981/130603436-0f8ee7da-0d74-4fb6-93d2-c80af61522b4.png)
Yes Cosmetic items have a category here but for some reason those are categorized as Soulbound in ArkInventory but has tooltip containing "Cosmetic".
I dont rly understand your answer if its ArkInventory or WoW bug

![image](https://user-images.githubusercontent.com/57992981/130603779-44d21b01-0ec1-452f-8fe8-1f6f798e4409.png)
Both have same Type & SubType: 4 (Armor) / 1 (Cloth)

**Comment by arkayenro** [comment]
there is an armor subtype of cosmetic - every cosmetic item ive seen has had it - this is just another blizzard bug but i have workaround code for that

**Comment by arkayenro** [comment]
because theres a subtype for cosmetic i dont scan the tooltip - thats why its ending up as soulbound
