### ISSUE TITLE
[BUG] Different reputation tooltips for same faction tokens

### ISSUE THREAD

**Issue by tflo** [arkayenro/arkinventory#1511]
AI v30955.13(alpha) on WoW Retail, English

***

It is very nice that AI shows the reputation of all toons also in the tooltip of reputation _tokens_.

Today I noticed the following:

I have two rep tokens in my bag, both for _Argussian Reach_, one with 250 rep points, the other one with 750. Both are account-bound.

Now have a look at the tooltip screenshots: The list of toons with rep is different for each token, albeit both tokens are of the same faction.

I have verified that the shorter list (the one of the 250-token) is the correct one. (It is also consistent with the _Argussian Reach_ tooltip in the rep window.) The additional toons that are listed in the other tooltip do not have any rep with this faction, but the displayed rep of these toons corresponds to the tooltip of the _Armies of Legionfall_ in the rep window.

![WoWScrnShot_082421_134512](https://user-images.githubusercontent.com/1410282/130611818-466ccdde-afcf-4bf3-be91-22806204480c.jpg) 
![WoWScrnShot_082421_134517](https://user-images.githubusercontent.com/1410282/130611894-04b08cb7-b012-420e-aeef-043bb509c18e.jpg)

I also checked it with all other add-ons unloaded, it’s the same.

**Comment by arkayenro** [comment]
it looks like i had an extra mapping for 152954 in the legionfall rep tokens.  will be fixed next alpha/release

**Comment by tflo** [comment]
Great, thanks!
