### ISSUE TITLE
[BUG] Classic TBC - Icons/items not loading just showing as a grey area

### ISSUE THREAD

**Issue by stigge80** [arkayenro/arkinventory#1513]
**What version number you are using?**
ArkInventory-3.09.52-BurningCrusade.zip

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Burning Crusade classic

**What language is the game client set to?**
English

**Describe the bug**
Some items doesnt choose an icon that are beeing picked up. when looting all i see is gray icons in my bad. a relog solves it but its annoying
![image](https://user-images.githubusercontent.com/7827274/130756242-45a068d4-7ed0-431e-ae25-ad6cf1fa61c8.png)

**To Reproduce**
Steps to reproduce the behaviour, if possible:
kill a mob, loot the item and alot of times it ends up like above picture

**Screenshots**
![image](https://user-images.githubusercontent.com/7827274/130756349-9808a3a6-f513-4e26-acdd-97d57e4e86b3.png)
 not possible to hover it, it shows nothing. but press and hole to move it shows the correct icon.. 

**Additional context**
sometimes a relog works. but most times it doesnt.. sometimes when hovering the item it shows what it is.. but thats rarely. 

I did have the wrong "nolib" build for a while from Curseforge. but after readin your posts i fully deleted all my local files on Arkinventory and downloaded it manually from site and put a "ignore" on curseforge so it doesnt change. but the problem continues.

**Comment by arkayenro** [comment]
thats not meant to happen in .52, that started in .53

can you download the latest alpha instead

**Comment by arkayenro** [comment]
please use 3.09.56
