### ISSUE TITLE
[BUG] Warning on Startup

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1514]
**What version number you are using?**
3.09.56

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
On startup, the following warning message appears on all characters.

WARNING> could not retrieve data from server for item:6265 / item:6265:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Simply login to any character.

**Screenshots**

**Additional context**
I looked up the item number on Wowhead and it appears to be a soul shard - https://www.wowhead.com/item=6265/soul-shard.  I think maybe these are remnants from when these were bag items but I'm guessing as it's been some time since that's been the case.

**Comment by arkayenro** [comment]
check your item tracking list in whatever LDB mod you use - that will most likely be where its from, then remove it from that list.

**Comment by Calesta** [comment]
Thanks Arkayenro!  I don't ever remember even tracking an item before so it's odd that there was something in this list, but removing the one temporary (errored) item seemed to fix it.  Cheers!
