### ISSUE TITLE
[BUG] Guild Bank Quantities not showing up on inventory tooltip.

### ISSUE THREAD

**Issue by bxyoung** [arkayenro/arkinventory#1515]
**What version number you are using?**
v30956.1 (Alpha)

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
BCC

**What language is the game client set to?**
English

**Describe the bug**
The tooltip does not show quantities of an item that are stored in guild banks.

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Put any item in guild bank. Mouse over item in inventory. Does not show guild bank amount.

**Screenshots**

**Additional context**

**Comment by arkayenro** [comment]
please check the item count options to make sure that guild bank is enabled

**Comment by bxyoung** [comment]
The option is not able to be checked in the BCC version.

**Comment by arkayenro** [comment]
sorry, i missed that you were in bcc, the vault (guild bank) only works in retail.

or has bcc caught up to where the vault is now active?

**Comment by aLanaMaunz** [comment]
> sorry, i missed that you were in bcc, the vault (guild bank) only works in retail.
> 
> or has bcc caught up to where the vault is now active?

Yes, guild-banks are live in wow bcc now!

**Comment by arkayenro** [comment]
try [alpha 3](https://www.curseforge.com/wow/addons/ark-inventory/files/3446912)

**Comment by bxyoung** [comment]
The option is now enabled but I'm unable to open the guild bank now. No LUA error just won't open. Disabled addon and can open.

**Comment by crichton32** [comment]
Same as bxyoung - disabled control for the gbank and was able to open the default ui for it, but ark inventory still isn't tracking the contents and if I try to manually pull up the AI gbank tab it's showing ERR 
![image](https://user-images.githubusercontent.com/55325495/131871892-58d53b62-5827-45a9-95e4-f444e9d5da01.png)

**Comment by arkayenro** [comment]
forgot to enable the events as well

try [alpha 4](https://www.curseforge.com/wow/addons/ark-inventory/files/3448890)

**Comment by jmphelps92** [comment]
![grafik](https://user-images.githubusercontent.com/90087744/132087740-d5119c30-6d46-4ac3-9deb-b0f652dca040.png)

no improvement :(

**Comment by arkayenro** [comment]
can you open the vault window, then click on the switch character icon, select the current guild, then select erase all data.

close the window then open the guild bank

**Comment by jmphelps92** [comment]
That's what I get:
![grafik](https://user-images.githubusercontent.com/90087744/132121002-16a4ac4e-0210-491b-b494-c81eaab5f298.png)
There's no such option for guilds. Only for characters. I also tried to erase character data from the bag window. Didn't help either.

**Comment by bxyoung** [comment]
I have a BCC guild you could use to test. I sent you an email.

**Comment by arkayenro** [comment]
thanks.  mujch easier when you can test things.

try [alpha 5](https://www.curseforge.com/wow/addons/ark-inventory/files/3451783)

**Comment by jmphelps92** [comment]
thank you, now its running, 👍

**Comment by aLanaMaunz** [comment]
tested https://www.curseforge.com/wow/addons/ark-inventory/files/3451783
looks good so far!

**Comment by aLanaMaunz** [comment]
showing the item/money log causes an error:
ArkInventory\ArkInventory-30956.5.lua:10928: bad argument #3 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@ArkInventory\ArkInventory-30956.5.lua"]:10928: in function `Frame_Vault_Log_Update'
[string "@ArkInventory\ArkInventoryStorage.lua"]:896: in function `?'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by arkayenro** [comment]
should be fixed in [alpha 6](https://www.curseforge.com/wow/addons/ark-inventory/files/3455288)

let me know if you run into any other issues
