### ISSUE TITLE
Pet tooltip: AI tooltip conflicting with Oribos Exchange tooltip

### ISSUE THREAD

**Issue by tflo** [arkayenro/arkinventory#1516]
AI’s inventory tooltips are the best of all comparable add-ons, and as a pet collector and trader I love especially the pet tooltip, because it shows  me _all_ pets (bags, banks, pet journal, auctions) in one spot. Also the additional pet stats, source  and the flavor text are nice :)

However, I noticed that the AI tooltip for pets is killing the [Oribos Exchange](https://www.curseforge.com/wow/addons/oribos-exchange) tooltip with the median price, which is also very useful.

First screenshot shows a pet tooltip without AI tooltip (I highlighted the Oribos tooltip), second one with AI tooltip enabled, obviously:

![WoWScrnShot_090121_210617](https://user-images.githubusercontent.com/1410282/131732337-c91ab9ff-6eb3-4a06-8b0f-fd074d69ae05.jpg)

***

![WoWScrnShot_090121_210402](https://user-images.githubusercontent.com/1410282/131732372-2273159f-6855-4fb0-9661-295f7fbab11d.jpg)

***

The screenshots show also that the TSM tooltip and the [Battle Pet BreedID](https://www.curseforge.com/wow/addons/battle_pet_breedid) tooltip are both unaffected by the AI tooltip.

I know that the pet tooltip is sort of a special one, but the fact that both the other tooltips are living in friendly co-existence with the AI tooltip gives me some hope that this can be solved some way…

**Comment by arkayenro** [comment]
both of those mods added support for my custom tooltip, thats why they work.

you would have to ask the oribos exchange author to add support for it as well.

**Comment by tflo** [comment]
Yeah, I suspected it would be like that.

The add-on has no curseforge comments, nor a github or other issues page; support in general seems to be [behind a paywall](https://www.patreon.com/erorus). Maybe I can catch him on Twitter. Or I simply let it be, since he obviously prefers to not receive any suggestions.
