### ISSUE TITLE
Scanning Headers causing erros?

### ISSUE THREAD

**Issue by jediahcorn** [arkayenro/arkinventory#1517]
Ark conflicts with a lot of things, but normally I can figure it out. I can't figure this one out tho... please help anyone?

256x ...rfaceArkInventory\ArkInventoryTradeskill.lua:340: attempt to index field 'data' (a nil value)
[string "@ArkInventory\ArkInventoryTradeskill.lua"]:340: in function `ScanHeaders'
[string "@ArkInventory\ArkInventory-30939.lua"]:3186: in function <ArkInventory\ArkInventory.lua:3078>
[string "=[C]"]: ?
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:70: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65>
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:630: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:615>

Errors every load, no matter what. Any help is MUCH appreciated cuz I can't deal without Ark. Totally dependent, sadly. >_<

**Comment by arkayenro** [comment]
if youre running 30939 you might want to consider upgrading for starters, as its up to 30956
plus i need to know what client your running
and have you tried at least disabling any mod that is related to tradeskills?

**Comment by jediahcorn** [comment]
Damn! I'm using Ajour to manage my addons, I THOUGHT it was keeping Ark up to date! Lemme go try that first. I'll just slowly enable addon by addon and I'll have to come up with something. I'll try this now!

**Comment by arkayenro** [comment]
if you have skillet installed then just install one of the latest alphas as that conflict is fixed in one of those
