### ISSUE TITLE
[BUG] not local variable good

### ISSUE THREAD

**Issue by Laumesis** [arkayenro/arkinventory#1518]
**What version number you are using?**
r1171-alpha

**Describe the bug**
`ArkInventory\ArkInventoryClient.lua` -> `function ArkInventory.CrossClient.GetProfessions( ... )` -> variable `good` is not defined as local

**Comment by arkayenro** [comment]
will be fixed in the next alpha/release

**Comment by Laumesis** [comment]
Confirmed fixed at least in 3.09.57 release. Thank you.
