### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by DiscordGregory** [arkayenro/arkinventory#1519]
**What version number you are using?**
Alpha 30956.3

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
In Cape of Stranglethorn, caught a battle pet 'Crimson Moth' and the error posted below popped up.

**Additional context**
1x ArkInventory\ArkInventory-30956.3.lua:11367: ...ceArkInventory\ArkInventoryCollectionPet.lua:1685: bad argument #1 to 'sub' (string expected, got nil)
[string "=[C]"]: ?
[string "@ArkInventory\ArkInventory-30956.3.lua"]:11367: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = "...ceArkInventory\ArkInventoryCollectionPet.lua:1685: bad argument #1 to 'sub' (string expected, got nil)"

**Comment by arkayenro** [comment]
some leftover test code.  will be fixed next alpha/release
