### ISSUE TITLE
Sorting Doesn't Work Right in TBC

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1520]
![image](https://user-images.githubusercontent.com/55365231/133603337-4f196272-b1f9-4a09-be09-611fd983c30d.png)

![image](https://user-images.githubusercontent.com/55365231/133603071-1dbcbaba-2d16-4e3a-94b9-bbeaf2fdac21.png)

Some items are showing "Item Level" as "-1" and it's putting those at the top of the list.

![image](https://user-images.githubusercontent.com/55365231/133603308-79c541f4-67fc-4910-ae3d-65291a433db1.png)

**Comment by Gogo1951** [comment]
Actually all the cloth now has i-level set to -1.

It used to sort perfectly and put the higher "quality" cloth common items on top, but now it just sorts by name inside of the "common" quality items.

**Comment by arkayenro** [comment]
will be fixed next alpha/release
