### ISSUE TITLE
[BUG] Classic Era v1.14 client - unknown blizzard bag id

### ISSUE THREAD

**Issue by Laumesis** [arkayenro/arkinventory#1523]
**What version number you are using?**
v3.09.57 [Classic]

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Classic Era Live

**What language is the game client set to?**
enGB or enUS, what ever is english EU default

**Describe the bug**
ArkInventory is not supporting all changes of patch 1.14. I think most of issues come from change of bank bag ids to different ones than 1.13.7 client  had.
`[14:10:54] ArkInventory: ERROR> unknown blizzard bag id - 11`
I have seen bag id errors for 11,13,14
After error items shown on GUI are wrong. Reload fixes until next error.

**To Reproduce**
Examples:
Move items to bags in bought bank bag slots.
Change bag in bank bag slot. 
Run Restack for bank.

**Comment by arkayenro** [comment]
thats typically a temporary error as the game hasnt returned any data for the bag in that slot

**Comment by Laumesis** [comment]
Somewhere is a bug. It might be on Blizzard side.
Bag ids 11-14 shouldn't exists in classic Era.
v1.13.7 -> v.1.14.0 client changed InventorySlotIds for bank bags 72-77 -> 76-81. Note offset of 4. Same offset as bugging in bagIds.

**Comment by Laumesis** [comment]
`ArkInventory:EVENT_ARKINV_BAG_UPDATE( event, arg1 - count + NUM_BAG_SLOTS )` doesn't work anymore for Classic Era after the change.  On BCC it works as bank base slots are 28 instead of classic era's 24.

**Comment by Laumesis** [comment]
Apparently this bugs also on default client because they are using same calculations. So I guess there will be some sort of fix.

**Comment by arkayenro** [comment]
> Somewhere is a bug. It might be on Blizzard side.

the bank bag slot ids are meant to be right after the bank bag slot ids, ie sequential

retail and bcc have 28 slots, so the bank bag slot ids are 29-34, subtract the number of bank slots (28) and add the number of bag slots (4) and you get 5-11 which are the blizzard bag ids for the matching bank bag slots

its the standard formula all bag mods have been using since classic - it shouldnt break unless blizzard fuck it up

classic has 24 slots so the bank bag ids are meant to be 25-30 but its returning 29-35 for some stupid reason which screws it up completely.

i guess i can hardcode it for a while until blizzard fix their shit

**Comment by arkayenro** [comment]
try [alpha 3](https://www.curseforge.com/wow/addons/ark-inventory/files/3481156)

**Comment by Laumesis** [comment]
Works ok on classic era live. You left (intentionally?) some debug messages on.

**Comment by Laumesis** [comment]
And yes, blizzard f* up. As they broke also their own UI code related to bank...

**Comment by arkayenro** [comment]
debug output is gone from [alpha 4](https://www.curseforge.com/wow/addons/ark-inventory/files/3482002)

**Comment by Laumesis** [comment]
Developing story. Blizzard never manages to not disapoint.
`interface_vanilla/framexml/bankframe.lua`:
```lua
BankFrameItemButton_UpdateLocked(BankSlotsFrame["Bag"..(slot-NUM_BANKGENERIC_SLOTS)]);
```
changed to
```lua
BankFrameItemButton_UpdateLocked(BankSlotsFrame["Bag"..(slot-GetFirstBagBankSlotIndex())]);
```
The new function is only available on classic era (at least so far).

**Comment by Laumesis** [comment]
<https://wowpedia.fandom.com/wiki/API_GetFirstBagBankSlotIndex>

From wowuibugs issues:
"The new function will be ported to clients other than Classic Era, however no ETA is given on when this will be. Consistency shall be achieved."

**Comment by arkayenro** [comment]
i added cross client code for this already to make the workaround.

if they ever backport it into classic or tbc the cross client code i added will still work as is

**Comment by arkayenro** [comment]
workaround added in 3.09.60
