### ISSUE TITLE
ArkInventory-3.09.57-BurningCrusade.zip flagged as corrupt

### ISSUE THREAD

**Issue by Snelzzy** [arkayenro/arkinventory#1524]
Curseforge client is throwing an error that says, "This addon might be corrupt (Belongs to 'Retail')"

**Comment by arkayenro** [comment]
ignore it.  the TOC version is irrelevant.  there is only one version of arkinventory and it works with all game clients

**Comment by Snelzzy** [comment]
Okay, thanks! That was a really fast response.
