### ISSUE TITLE
ArkInventory rules etc are not longer working

### ISSUE THREAD

**Issue by hEy1968** [arkayenro/arkinventory#1526]
**What version number you are using?**
3.9.58

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
german

**Ask your question**

After updating via Curse, Ark... doesnt sort my inventory. There are no more rules to apply/change.
Restore backup from a week and 2 weeks before doesnt help.
A day before everything works fine. There were over 50 ledges (Leistten).

**Comment by arkayenro** [comment]
double check the rules addon is ticked when you load the game (it is possible to turn the rules off that way)
