### ISSUE TITLE
Sell items under my item level?

### ISSUE THREAD

**Issue by awedy01** [arkayenro/arkinventory#1527]
**What version number you are using?**
3.09.58

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail/Live

**What language is the game client set to?**
English

**Ask your question**
Hello there! I would like to know if there is any way to make a rule to SELL all gear under my item level.
I know you can make rule to sell items under X item level, but my characters have different item levels so i would like to have it based on my equipped item level or something like that
Thanks for any answer in advance.

**Comment by arkayenro** [comment]
youll need to define what you mean by "my item level"

**Comment by awedy01** [comment]
The goal here is to not define it as each character have different item level.
So is that not possible? "Sell item if its item level is under the character's item level by 10" for example.

**Comment by arkayenro** [comment]
i understand the concept, a rule function already exists for character level plus/minus

define as in where is it found? how do i calculate it? what exactly do you mean when you say "a characters item level"?

i know theres an API to get the average item level value for a player but thats an average, and im not sure thats what you mean

**Comment by awedy01** [comment]
When i open my character pane, i see my item level on the right
Ye i think this is whats called average itemlevel.
This is what i mean, for example: 
IT shows 240 ilvl for me
I get an item which is 220 ilvl, it should be junk as its 20 ilvl below my average. 

The calculation should be something like
Character's average item level - X then sell
and so i should be able to set X to something like 20
So then my example will be true.

**Comment by arkayenro** [comment]
does [this](https://github.com/arkayenro/arkinventory/wiki/RuleFunction_ItemLevelBelowAverage) sound right?

**Comment by awedy01** [comment]
Yes it sounds right i just dont get this second value.
Is that mean if i set this:
belowaverage( 10, 98 )
It will be able to sell everything 10 ilvl below my average ilvl BUT only items above ilvl 98?
If so then i understand it.

I guess you just didnt add the function yet but ill report:
[09:44] ArkInventory: ERROR> Error validating rule <NEW>, invalid formula: [string "return( belowaverage( 10, 98 ) )"]:1: attempt to call global 'belowaverage' (a nil value) 
I get this message when trying the example from your link.

**Comment by arkayenro** [comment]
it needs a minimum, youll probably will use something like 10 to make sure that shirts and low level rewards dont end up getting sold just because theyre item level 1

although i am going to bump the default minimum up to 2 to handle all the level 1 stuff that most people have but wont want sold anyway.  if they do they can put a 1 in the rule to include them.

yeah, the function is in alpha 4 which isnt released yet

**Comment by arkayenro** [comment]
try [alpha 4](https://www.curseforge.com/wow/addons/ark-inventory/files/3517127) and let me know if theres any issues with it

**Comment by awedy01** [comment]
Ok so the first thing here, may you change or add an option in advanced menu to define YOUR categories'weight?
Order Weight i mean. 
Right now Equipment (Party Loot) is more important than my rule even if its set to 0 in order
But i can play through it by equipping the loot, just wondering if you can add something about it.

However, to give a response about the main thing here, i can say it works fine so far. I tried several ways and it was acting perfectly. (The rule for average gear)

**Comment by arkayenro** [comment]
party loot is an override that you can disable - its under settings > items > override > party loot

it will always override everything when its turned on, its just how it works.
