### ISSUE TITLE
[BUG] Destroying is not working

### ISSUE THREAD

**Issue by awedy01** [arkayenro/arkinventory#1530]
**What version number you are using?**
v3.09.58 [Shadowlands]

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail / Live

**What language is the game client set to?**
English

**Describe the bug**
ArkInventory says it "Destroying" items but it doesnt do it actually (at least not doing it for Halloween items)

**To Reproduce**
Get a non-sellable item & try to destroy it via keybind of Arkinventory sell/destroy

**Screenshots**
![image](https://user-images.githubusercontent.com/57992981/140054780-3ddedf9d-98de-4ca8-be92-5c785be3cd0c.png)
![image](https://user-images.githubusercontent.com/57992981/140054860-c46f272b-9541-484a-8130-5f54adc6f6b7.png)
![image](https://user-images.githubusercontent.com/57992981/140054879-6b9b5126-07b1-47ff-8c26-6373f6a3e688.png)
2 pictures after pressing the sell/destroy button

**Additional context**
It seem to destroy ONE item at each try (not always)
I tried reload.
Happening since 9.1.5(today in EU)

**Comment by arkayenro** [comment]
yeah i noticed.  i think (not sure) but it looks like it requires one keypress per delete, it wont chain them

**Comment by awedy01** [comment]
The problem here it doesnt delete an item at each keypress.
It deletes one item at each try only for the first 2 try.
Then on next press it just reorganize them but wont sell them for another few tries

**Comment by arkayenro** [comment]
i only had two items to test with.  ill try and grab something easy/cheap to test with

**Comment by awedy01** [comment]
I tried and i can confirm you can test it with heirloom items.
Simply generate them from the collections into your inventory. You can generate unlimited amount for free so its a good choice for test.
However, they dont wanna be destroyed via Arkinventory at all. But that might be another problem.

Ok so before sending this message, i already found another unsellable item: Mild Spices
You can buy those at Oribos, Cooking Vendor (where the Cooking Trainer is)
I tested on my own as they stack to a big number, so i seperated them into small ones:
![image](https://user-images.githubusercontent.com/57992981/140503800-07513d0c-7386-46e9-9aab-b635010cb71d.png)

First try on destroy:
![image](https://user-images.githubusercontent.com/57992981/140503822-9b24ac50-fcc7-4db0-8b1f-c16a8b992394.png)

One destroyed, and another one stacked into the 3rd one
So i re-seperate the stacked one and try destroy again
![image](https://user-images.githubusercontent.com/57992981/140503953-f96f721e-f17a-454f-be3f-8c3809893acd.png)


One destroyed and the other stacked into the last one
![image](https://user-images.githubusercontent.com/57992981/140504040-1cd892ce-361e-49e2-b6eb-dfbd47aca6d7.png)
Re-seperated and tried to destroy again, in this case i realized something. A stack will always be dragged by my mouse (without actually trying to drag it)


As its cheap, i went crazy mode and bought 4 full stack of this item to test
![image](https://user-images.githubusercontent.com/57992981/140504295-af140c93-2eb6-40ad-b9eb-1b48f869e3fc.png)

First try, one stack is gone and another stack got dragged by my mouse
Second try, another one is gone but nothing is dragged by my mouse



>>>
Ok so, i realized the reason of why its not being destroyed after some tries: Because it gets dragged by my mouse.
Not sure what kind of code you use, but the item will be stuck on my mouse.
So to summary:
9.1.5 latest changes caused ArkInventory to not be able to chain destroy items
It keeps destroying one by one and sometimes it gets stuck on my mouse, so it will stop destroying. After i right click (to drop the item from drag) it will continue to destroy one by one.

**Comment by arkayenro** [comment]
when it aborts its going to be stuck to your mouse because thats how you destroy an item, you put it on the cursor, then delete it, so when it fails the item is still on your cursor.

i'll have a play around with those items and see how i go

**Comment by arkayenro** [comment]
try [alpha 2](https://www.curseforge.com/wow/addons/ark-inventory/files/3516275)

**Comment by awedy01** [comment]
Yeah i can confirm it works as you seem to want it.
It keeps deleting one by one as the message says. No stuck on mouse anymore! Good job.
You may take a look at my question (linked right above your last message)

**Comment by awedy01** [comment]
hey so using alpha 2 i encountered this:
![image](https://user-images.githubusercontent.com/57992981/140566772-2bb0ce7b-a42b-413c-830c-6e11674ae07e.png)
![image](https://user-images.githubusercontent.com/57992981/140566803-c939664b-45f9-431f-8662-89faed70f774.png)

So i have keybind for sell but it say this and wont sell any item

**Comment by awedy01** [comment]
More to note, sorry for double post, but i dunno if u read already or not, so i wont edit:
This last reported problem occur only IN COMBAT (yes i could open vendor to actually sell via right click during combat)

**Comment by arkayenro** [comment]
ive added a config option to allow junk sell to sell while in combat

**Comment by arkayenro** [comment]
try [alpha 3](https://www.curseforge.com/wow/addons/ark-inventory/files/3516745)

just make sure you enable combat in the junk config first

**Comment by awedy01** [comment]
I've tried it & seem to work fine! Good job. Any eta when it gets published to curseforge?

**Comment by arkayenro** [comment]
just tweaking the code to allow for clearing the rule cache when the average equipped item level changes but either later on tonight or tomorrow it should be up.
