### ISSUE TITLE
[BUG] Guild Bank Tab Change Icon / Rename Window Appears Upon Login / Reload UI

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1531]
**What version number you are using?**

3.09.58

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**

Retail

**What language is the game client set to?**

English

**Describe the bug**

Every time I login to a character or reload the UI, a window for changing the icon and/or renaming the a Guild Bank Tab appears.  It happens on ALL characters, whether or not they are in a guild.

https://imgur.com/4pE5QrD

If I disable ArkInventory, then the window doesn't appear.

I can close it, of course, and continue with my session but it's certainly something I'd rather not have to do every time I start playing or swap characters.

**To Reproduce**
Steps to reproduce the behaviour, if possible:

Login to a new character or reload UI.

**Screenshots**

https://imgur.com/4pE5QrD

**Additional context**

I did some testing on different characters to see if it mattered if they were in a guild or not in a guild.  It doesn't seem to matter.  All characters are affected.

On my 'bank' character which is in a guild of one and I have named my bank tabs, the window shows just like the screen shot despite already having an icon and a name.

**Comment by arkayenro** [comment]
type /fstack into the chat window
mouse over that frame
note down its name (or screenshot it)
type /fstack into the chat window (to turn it off)

i need to know what frame that is so i can check the code to see why it might be popping up.

i do forcibly load the guild bank ui at login though, which can screw up some other mods that might be expecting it to only load at the bank.

**Comment by ivardensphere** [comment]
I can confirm this as well. Following Arkayenro's testing, this bug appears only when ELVUI and Arkinventory are enabled together. Using /fstack, the frame that pops up is GuildBankPopupFrame.BG.

**Comment by rockschtar** [comment]
Can confirm it too. ElvUI 12.46 + ArkInventory.

![image](https://user-images.githubusercontent.com/87191/140480886-a9d65b3a-c0ba-4e05-bd3e-15ba436271fc.png)

**Comment by arkayenro** [comment]
i do play with GuildBankPopupFrame when AI is loaded to make sure it doesnt react when its overridden by AI.

youre going to need to ask the elvui people to take a look

let them know that the guild bank addon/frames are being loaded at player login - not afterwards at the bank - and they need to be able to handle that.  seems odd that its only broken now though?  did they make any changes to the guild bank skinning?

**Comment by Fenjahin** [comment]
Hello everyone, 
I had the same problem.
Try disabling the guild bank skin in the ElvUI options. There is indeed a conflict in these options; this temporarily resolves the display of the window. normally this is an option reserved for guild masters.
Hope this helps you.
Br
Fenj 
![image](https://user-images.githubusercontent.com/93865198/140644657-014830fe-bd58-4a63-919a-883a41b00a1f.png)

**Comment by sir-wilhelm** [comment]
Disabling Guild Bank in the ElvUI skins section resolved this issue for me:
![image](https://user-images.githubusercontent.com/3122458/140658704-62c89c2e-6ba9-4f46-bbe6-d94045dbb7b5.png)

**Comment by Calesta** [comment]
I already had skinning the Guild Bank disabled so I still have the issue.

Interestingly enough, I tried toggling it on and got the following error message when I reloaded the UI.

AddOnSkins 4.57: There was an error in the following skin(s): Blizzard_GuildBankUI
AddonSkins Please report this to Azilroka immediately @ [http://git.tukui.org/Azilroka/AddOnSkins/issues]

It looks like there's an issue there which is causing the issue.  I'm going to cross-post for visibility.

**Comment by notDavid** [comment]
Fyi this is fixed in the latest ElvUI version: 

Issue: https://github.com/tukui-org/ElvUI/issues/28
Release: https://github.com/tukui-org/ElvUI/releases/tag/v12.58

**Comment by Calesta** [comment]
Yes!  Thanks for the note.  I'm going to go ahead and close this issue as I was the author and can confirm it's now A-OK.
