### ISSUE TITLE
[BUG] r1188-alpha 100% Broken on TBCC

### ISSUE THREAD

**Issue by stratoru** [arkayenro/arkinventory#1533]
Doesn't seem it was tested or attempted on TBC before release since it's obviously completely broken as soon as you login. The variable "GetAverageItemLevel" doesn't exist in TBC, but was added to the TBC version of the addon today, perhaps by mistake? Bag's don't open, can't open config menu via "/ai config," etc. Rolling back to previous version was only solution.

![image](https://user-images.githubusercontent.com/43893231/140613851-17ff58a4-f063-408c-a288-b0cd4521e1fe.png)
![image](https://user-images.githubusercontent.com/43893231/140613857-0dedd9e5-dc65-463f-a88f-8678a4e3081c.png)
![image](https://user-images.githubusercontent.com/43893231/140613861-caff1b1a-4da3-493a-88b4-83acf442b1b8.png)

**Comment by wirerydr** [comment]
Also happens for me.  Rolling back to previous version cleared the problem.  GetAverageItemLevel() appears to have first appeared in-game in v4.0.1.

**Comment by arkayenro** [comment]
try [alpha 5](https://www.curseforge.com/wow/addons/ark-inventory/files/3517831)

**Comment by wirerydr** [comment]
> 
> 
> try [alpha 5](https://www.curseforge.com/wow/addons/ark-inventory/files/3517831) should be fixed there

Confirmed that [alpha 5](https://www.curseforge.com/wow/addons/ark-inventory/files/3517831) works correctly, and no longer throws any errors.  Thanks very much!
