### ISSUE TITLE
sending and recieving profiles+rules ingame

### ISSUE THREAD

**Issue by Morwo01** [arkayenro/arkinventory#1534]
**Is your feature request related to a problem? Please describe.**
setting up ArkInventory with all the features (many there are) takes a lot of time. setting up rules also requires additional coding knowledge. an import/export feature to send and recieve made profiles and rules would ease the time needed to spent setting up ArkInventory. import/export could also be done on wago.io community too.

**Describe the solution you'd like**
import and export feature with text strings, sending and recieving profiles and rules ingame.

**Describe alternatives you've considered**
none

**Additional context**
setting up ArkInventory and rules can take up to many houres and require learning code knowledge suitable for rules. sharing made profiles and rules helping ArkInventory community

**Comment by arkayenro** [comment]
import/export of profiles already exists.

was there something missing from it?
