### ISSUE TITLE
[BUG] Junk unequipable not selling

### ISSUE THREAD

**Issue by awedy01** [arkayenro/arkinventory#1535]
**What version number you are using?**
v30958.4 (Alpha)

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Unusable equipable item is not considered as junk even if its checked in.

**To Reproduce**
Steps to reproduce the behaviour, if possible:
1. Be a Cloth wearing one
2. Get a Plate item
3. Try to sell it when config is enabled "General > Junk > "Equipment"(be checked)

**Screenshots**
![image](https://user-images.githubusercontent.com/57992981/140652082-14a9da0c-b6a1-4416-932b-b2decdd9ef52.png)

**Additional context**
-

**Comment by arkayenro** [comment]
found the typo thats causing it to not check, will be fixed int he next alpha/release

**Comment by arkayenro** [comment]
fixed in [alpha 6](https://www.curseforge.com/wow/addons/ark-inventory/files/3519463)

**Comment by awedy01** [comment]
I can confirm it is fixed.
So far there are no bugs i found, so i would say its ready for release :P
