### ISSUE TITLE
[BUG] Eroor message when obenig the Guild Tab from Friends list

### ISSUE THREAD

**Issue by Padparadscha** [arkayenro/arkinventory#1536]
**What version number you are using?**
3.09.58

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Burning Crusade

**What language is the game client set to?**
German

**Describe the bug**
every time I open the Guild tab in the Friends List. I get a error message:
Arkinventory wurde geblockt. Die angeforderte Funktion ist der Blizzard-UI vorbehalten. Sie können dieses Addon deaktivieren und die UI neu laden.
I try to translate.
Arkinventory was blocked. The function is only for the Blizzard-UI. You can disable this addon and reload the UI.

**To Reproduce**
every time I open the Guild tab in the Friends List after a UI-Reload/Login

![Screenshot 2021-11-09 162732](https://user-images.githubusercontent.com/10797642/140953687-6d7728e6-892e-4ffd-b6ee-cbfb3dbc714a.png)

**Comment by arkayenro** [comment]
see https://github.com/arkayenro/arkinventory/wiki/Taint-and-ADDON_ACTION_BLOCKED for detailed info/instructions
