### ISSUE TITLE
[BUG] Item stays greyed after right click (if i have it on me aswell)

### ISSUE THREAD

**Issue by awedy01** [arkayenro/arkinventory#1537]
**What version number you are using?**
3.09.60

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail / Live

**What language is the game client set to?**
English

**Describe the bug**
If i try to equip the same item(with right click), it will stuck & become grey until i do something to it OR until i close & re-open my bags.

**To Reproduce**
I did it with item "Vault Guardian's Vambraces" from "Korthian Armaments", simply right clicked the item in my inventory when i had it also equipped on my character.

**Screenshots**
![image](https://user-images.githubusercontent.com/57992981/141377015-e77acc01-e560-4dce-a2bd-f27d17c5a436.png)
![image](https://user-images.githubusercontent.com/57992981/141377027-284eb373-41ec-4251-87fa-dedde3414bb4.png)

**Additional context**
The bug doesnt happen IF i drag and drop it on the equipped item slot.(wrist in this case)

**Comment by arkayenro** [comment]
greyed out means locked/in use which is a server side state.

does going into edit mode and back to normal reset it?

can you pick up the grey item and move it to another slot?  does it revert to normal?

**Comment by awedy01** [comment]
In this case Greyed out means nothing but a color change.
I tested without ArkInventory and there was no problem.
I can even drag the item which will debug the "greyed state"
It does revert to normal without moving it to another slot.

**Comment by arkayenro** [comment]
because it is literally the exact same item (full item hyperlink is identical) it looks like nothing has changed so it doesnt update the slot

**Comment by arkayenro** [comment]
the lock event only triggers once, when the item is swapped out, it doesnt trigger again once the swap is complete - checking at that time shows the item as locked as they havent actually swapped yet

when the items are different in any way the entire bag is updated but when they arent i just update the locked state

ill need to find a way to add in another update that is delayed enough to pickup the new lock state

you can just refresh the window in the mean time

**Comment by arkayenro** [comment]
i've tried a couple of way to get this to update but its never perfect - if you continually right click on the same item swapping it out over and over it will get out of sync.

nothing i've tried will work consistently but considering this is probably a rare edge case then it will have to do.  if it gets out of sync just refresh the window.
