### ISSUE TITLE
[BUG] General > Junk > Equipment sells high level & need reload

### ISSUE THREAD

**Issue by awedy01** [arkayenro/arkinventory#1539]
**What version number you are using?**
v3.09.60

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail/Live

**What language is the game client set to?**
English

**Describe the bug**
1. If General > Junk > Soulbound(Equipment) is checked, it sell item above your level, which is trully unequippable but only a matters of level required, which case shall not sell as many many people will want to keep high level items when they reach that level.
2. It needs reload to be turned on/off but it doesnt say anywhere (either offer a reload or say it needs a reload to work)

**To Reproduce**
Bug 1: Get lv60 item, be lv55 > It will want to sell the item
Bug 2: Simply reproduce Bug 1 & try to turn off this feature, it will still sell until reload

**Screenshots**
![image](https://user-images.githubusercontent.com/57992981/141680990-f4883fea-1255-4191-a511-4e0eebf6d6a9.png)
![image](https://user-images.githubusercontent.com/57992981/141681002-b781fa14-b20a-4ee7-8d9b-d9045b81d788.png)

**Additional context**
Pic 1 shows this item is want to be sold but shouldnt
Pic 2 shows that it still want to be sold when Equipment is unchecked (I can guarantee it wont sell after /reload)

**Comment by arkayenro** [comment]
1. the option is basic.  it does not care why you cannot equip an item, just that you cannot.
2. will be fixed next alpha/release

**Comment by awedy01** [comment]
1. I think its basic that people may get higher level items that they wanna keep till they reach the level, so i think instead of forcing ppl to bank / turn off the feature, it should have either an option to keep higher level OR simply just make the feature care about it.
Dont let those people turn off this feature just for a few level ^^

**Comment by arkayenro** [comment]
ive added extra code into the usable check to specifically check for item level and added a config option to turn it on and off.

**Comment by ImUnicke** [comment]
Yea this is an **extremely** dangerous 'feature' and I see no reason for it to even exist. However the bug occurred today, it vendored my wife's entire inventory of equipment upon interaction with a vendor. She's never had this setting enabled as it's clearly a new setting, and somehow updating to the latest version it became enabled without her knowledge.

Highly recommend removal of this 'feature'

**Comment by arkayenro** [comment]
the "bug" only applies to characters that arent 60, and the items require a higher level than the character currently is to use

junk sell is old, not new, it has quality (of poor) and buypack page limits (so it can only sell 12) as defaults since day one

if you see no reason for it to exist then why did you enable it and set the quality to epic?

**Comment by ImUnicke** [comment]
> if you see no reason for it to exist then why did you enable it and set the quality to epic?

She's never touched the settings... how could it be released as enabled?

**Comment by ImUnicke** [comment]
On **my** ArkInventory, these two settings have never become enabled.
![image](https://user-images.githubusercontent.com/4297742/141923359-72812ca1-051f-49a4-a3e4-adb8df41e4ff.png)

On **her** ArkInventory, the settings were enabled automatically without being toggled.

**Comment by ImUnicke** [comment]
> the "bug" only applies to characters that arent 60, and the items require a higher level than the character currently is to use

This is also false. We are raiding Mythic Sylvanas, and she went to repair her gear, and ALL equipment was vendored. So please make sure that your bug fix accounts for this situation. Something partway through the raid night caused this bug where EVERY soulbound item was considered unequippable, and was vendored.

**Comment by ImUnicke** [comment]
Here's another example: the legendary cloak from BFA is perfectly equippable by a level 60 character, but ArkInventory wants to delete it using the above setting as **enabled**.
![image](https://user-images.githubusercontent.com/4297742/141923953-0d1f7138-a963-4bf5-bd26-b2bfce006bae.png)

Here's a screenshot of a _portion_ of my wife's item restoration page of a few of the items which were vendored by ArkInventory on a level 60 character obviously.
![image](https://user-images.githubusercontent.com/4297742/141924051-fd1e297d-833c-46fd-ac6a-0b919ea46ed4.png)

**Comment by ImUnicke** [comment]
As it turns out, she was streaming and caught the action as it happened... maybe it will help narrow down what was going wrong with the setting.
[Gear Deleted](https://clips.twitch.tv/FairPeacefulSardinePRChase-Uw2rTyptYZsKrZG8)

My best guess is that she opened ArkInventory **during combat** to use items in the bags, and AI decided that none of the gear was 'usable' because in-combat nothing can be equipped. Then later when opening a vendor to repair, AI went and sold everything that had been flagged previously as 'non-equippable' soulbound equipment.

**Comment by arkayenro** [comment]
>  the legendary cloak from BFA is perfectly equippable by a level 60 character, but ArkInventory wants to delete it using the above setting as enabled.

if you mouse over the item there will be red text on it somewhere - that is why it is seen as unusable.  it will have a requirement for the heart, and another for being below 50 in red - but its only specific to that one ability, not the entire item.

there is no API that will tell me if an item can be equipped by your character, just if it is an equipable item (which is pointless as there are item properties for that already)

basically if theres red text that doesnt have an exception coded then its seen as unequipable

if there is unique text (like the heart being disabled on some items that i recently found) then i can code for those exceptions - the shroud doesnt have anything unique

> As it turns out, she was streaming and caught the action as it happened... maybe it will help narrow down what was going wrong with the setting.

i'd need to see the tooltips to work out what the red text on them was/might have been to see if it could be added to the exclusion list

i dont think theres red text added to items tooltips when in combat but i can check that

**Comment by arkayenro** [comment]
went into combat and it appears there is red text added to the tooltip, for combat, arena, torghast, and mythic plus.

i will add exceptions for those

**Comment by arkayenro** [comment]
and yes, it was most likely due to entering the game while in combat (reloading) and opening the bag while in that same combat

**Comment by arkayenro** [comment]
[alpha 2](https://www.curseforge.com/wow/addons/ark-inventory/files/3528191) should fix the combat red text issue
