### ISSUE TITLE
ArkInventoryTradeskill error... ?!

### ISSUE THREAD

**Issue by jediahcorn** [arkayenro/arkinventory#1540]
Below is a copy/paste of what Bugsack reports... does anyone have any idea on how to make this stop? I don't think I even setup Ark to pay attn to my Tradeskills. LOL... like what?

26x ...rfaceArkInventory\ArkInventoryTradeskill.lua:340: attempt to index field 'data' (a nil value)
[string "@ArkInventory\ArkInventoryTradeskill.lua"]:340: in function `ScanHeaders'
[string "@ArkInventory\ArkInventory-30939.lua"]:3186: in function <ArkInventory\ArkInventory.lua:3078>
[string "=[C]"]: ?
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:70: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65>
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:630: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:615
![ArkError](https://user-images.githubusercontent.com/31173768/141683992-b47b29a7-c3c7-4eda-9d38-357cdec7ad12.jpg)
>
I've attached a screenshot also. Any help would be amazing!

**Comment by arkayenro** [comment]
3.09.39 is over a year old, and 20 versions behind, so you may want to consider upgrading.

**Comment by jediahcorn** [comment]
Damn! How come, literally, ALL of the "addon managers" for WoW are literal trash that could not fetch an ACTUAL current version to save their lives. Ugh! >_< I'll just start double-checking my addons individually now... over a hundred of them or so... should only take my addon-update-timeframe from 2 minutes to 2 hours... no big. /facepalm

Overwolf is such trash. What they're doing to the API. Byebye third party addon managers!
