### ISSUE TITLE
Arkinventory - ElvUI Guild Bank Skinning

### ISSUE THREAD

**Issue by Muckwimp** [arkayenro/arkinventory#1541]
Hallo Arkayenro,

nach Installation von Arkinvenory, Spielversion 9.1.5 erscheint immer beim starten von World Of Warcraft ein Fenster.

In diesem Fenster steht folgendes:

Name für Gildenbankfach:

Fach1

Ein Symbol wählen:

Dieses Fenster erscheint immer beim Start auch wenn ich einen Namen und ein Symbol eintrage.

Kann ich das irgendwo einstellen oder abstellen? Wäre echt froh darüber, denn das Fenster nervt.

Mit freundlichem Gruss

 Tuc

**Comment by arkayenro** [comment]
see issue #1531
