### ISSUE TITLE
Note: Warning in CurseForge client for 3.09.61 (Retail)

### ISSUE THREAD

**Issue by tflo** [arkayenro/arkinventory#1542]
I’m still using CurseBreaker to update my add-ons, but in anticipation of the bright future I have already installed the super crappy CurseForge client too.

I’ve noticed that since the latest AI update (3.09.61 for Retail) this CurseForge client classifies the add-on as BurningCrusade version and shows a corruption warning:

<img width="1049" alt="Screen Shot 2021-11-20 at 10 28 25" src="https://user-images.githubusercontent.com/1410282/142721762-5770e738-cb30-4184-bf70-bb69bb3078c9.png">

This persists after a manual download of the latest Retail version and a CurseForge client refresh.

I couldn’t find any anomalies in the toc file, and CurseBreaker shows it as non-BurningCrusade version:

<img width="407" alt="Screen Shot 2021-11-20 at 10 29 57" src="https://user-images.githubusercontent.com/1410282/142721873-347f2a93-ec52-4b98-ad3d-7ce9e79ecb69.png">

So, I tend to think this is a false warning by the CurseForge client. But maybe you can do something on your side to reduce the likeliness that such warnings appear?

This is just an observation, not a bug report.

– Tom

**Comment by arkayenro** [comment]
i have to upload the same files three times to curseforge and then i tag them for which version belongs to which client, its possible you grabbed it just after i uploaded them but before i tagged them

**Comment by arkayenro** [comment]
if you downloaded it manually afterwards as well then im not sure, but theres only one version of arkinventory and it works on all clients so its not a big deal

**Comment by tflo** [comment]
Even weirder: A bit later I clicked the Update button in the CurseForge client (something I normally don’t do). The warning went away, but came back later, presumably after an auto refresh, without me having changed anything in my add-on directory (neither manually nor via CurseBreaker).

Interestingly, among my 350+ add-ons, AI is the only one with that warning. The only similar thing I see is this one:

<img width="724" alt="Screen Shot 2021-11-21 at 09 29 40" src="https://user-images.githubusercontent.com/1410282/142755690-21e5238a-ee5d-4bfc-aebf-e8b5ff2359b7.png">

This makes even less sense, because the CurseForge client _is set_ to Retail. (r49 of this add-on is a one-toc version for Retail, r50 is a three-toc version for all game versions, and the warning is there no matter which one I install.)
