### ISSUE TITLE
Item tracker (LDB): Hiding zero-quantity items?

### ISSUE THREAD

**Issue by tflo** [arkayenro/arkinventory#1543]
Is there any way/setting that allows me to prevent tracked items from being displayed in the LDB if the quantity is zero?  

If not, then here a suggestion:

In Advanced > LDB, add a section for ‘Tracking: Items’ with an option to hide zero-quantity items.

***

Why?

In many use-cases, displaying an item even if there isn’t any in the bags/bank is just a waste of LDB space. 

For example, I’m using the tracker mainly for two things: 

* For a quick overview of items that can/should be consumed in some way, in order to free up bag space. Examples:
  * Construct Supply Key, Battlefront Ration Key, Atonement Crypt Key, etc.: When I’m in the appropriate zone, a look at the tracker tells me to use these items.
  * Account-bound Mission XP tokens: The tracker reminds me to send these to my alts, when I have accumulated some.
* As a counter when farming something specific.

In both cases, I’m not really interested in seeing the item in the LDB, if the quantity is zero. (The item is always visible in the tooltip list either way.) It just consumes space and therefore limits the amount of items I can have activated at a time (activated = green in the tooltip).

I can see that in other use-cases, for example if you are tracking health potions or augment runes, seeing an explicit  “0” value may be beneficial. Hence the suggestion to make this optional.

***

Thanks for considering – or for a hint, if the option is already there and I’m just blind ;)

**Comment by arkayenro** [comment]
config option will be in the next alpha/released

**Comment by tflo** [comment]
Oh, great. Really appreciated, thank you!

**Comment by arkayenro** [comment]
you can test it in [30961.1](https://www.curseforge.com/wow/addons/ark-inventory/files/3535718)

**Comment by tflo** [comment]
Well, I tested it, and the result was impressing ;)

Really, this increases the usability of the tracker by 200% :) Now I’m able to bring 30 tracked items into a space-limited LDB bar (without having to activate/deactivate them according to need/situation).

Another advantage of this is, that you are no longer distracted from spotting the important values by an army of zero-entries, as it was before. I mean, the main point of this feature is to give _focus_ to certain items, no? Now, it does exactly that :)
