### ISSUE TITLE
[BUG] Error upon opening guild bank

### ISSUE THREAD

**Issue by SillyGreenMonkey** [arkayenro/arkinventory#1544]
**What version number you are using?**
3.09.55 downloaded onto IMac Late 2012 running Mojave using wowmatrix, same error also noticed on MacBook

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail, fresh downloads

**What language is the game client set to?**
English-North American

**Describe the bug**
Clicking on the guild bank causes backpack to come up as normal, guild window comes up with all tabs showing as thumbnails and the word ERROR in the bottom left of the window.  The first copied LUA error comes up then, disabled all other addons and reloaded UI, clicking on the guild bank a second time brings up the second LUA error.

Interface\AddOns\ArkInventory\ArkInventory.lua:11338: ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:4565: attempt to compare nil with number

Interface\AddOns\ArkInventory\ArkInventory.lua:11338: Interface\AddOns\ArkInventory\ArkInventory.lua:4793: 'for' limit must be a number

**To Reproduce**
Steps to reproduce the behaviour, if possible:

**Screenshots**

**Additional context**
My mac has been affected by the Agent of the Bnet launcher issue of a few weeks ago, this is an attempt for a new install on a SSD to be used only for WoW.  The macbook also has the addon Zygor, but while that was downloaded to the SSD it isn't showing up in game yet.  The macbook runs Catalina, both systems have the newest Arkinventory available on wowmatrix.

**Comment by arkayenro** [comment]
3.09.55 was pulled because it had serious issues (its no longer available so i hope that wasnt recently downloaded from somewhere else)

upgrade to [3.09.61](https://www.curseforge.com/wow/addons/ark-inventory/files/3530427) and see if the issue is still there.

**Comment by SillyGreenMonkey** [comment]
Wowmatrix insists the problematic version is the newest, I'll have to find a source to download that new version and figure out how to apply it (I don't use Curseforge, which has the newer version).
