### ISSUE TITLE
reagents from bank bags are moved to reagent bag

### ISSUE THREAD

**Issue by seppelinchen** [arkayenro/arkinventory#1546]
hello,
i'm running version 3.09.63 on retail shadowlands and the client language is set to german.
my question is: when i have reagents in bank bags and i use the 'move to reagent bag' (is it called like that in the english version?), the reagents from my bag are moved, which is ok, but then all remaining slots from the reagent bag are filled up with reagents from other bank bag slots, which is not wanted.
can this be switched off/on somewhere?
thank you
btw, it's a really good addon ;)

**Comment by arkayenro** [comment]
right click on the restack icon and untick the top up option - i think thats what you want.

**Comment by arkayenro** [comment]
actually i think its the other option, the one about filling up from the bag?  sorry, im not in game but it should be one of those so play around until you get it set how you want

**Comment by seppelinchen** [comment]
these options i've tried already with no success :(

**Comment by MrUzagi** [comment]
Have you tried changing the Type between the Blizzard: Cleanup and ArkInventory: ReStack?
https://github.com/arkayenro/arkinventory/wiki/UserGuide_Restacking

**Comment by seppelinchen** [comment]
yes, i did

**Comment by arkayenro** [comment]
sorry, i think i may have read it wrong.  so you just dont want reagents from the bank going into the reagent bank?

any reason why not?  i mean you get more space.

if its because its pulling out of profession bags, not just normal bank bags, then tick the option for profession bags having priority and it should leave them there

**Comment by seppelinchen** [comment]
you got it ;)
the reason is, i'm actually doing some gold farming via tailoring. buying lots of cloth and want to have the in the bank to have my bags empty to craft the stuff. it's just much more convenient by clicking once to get every cloth to the bank instead of clicking every cloth stack.
but i've found a workaround: i set the reagent priority to bank and all slots are filled with the cloth. when finished with tailoring, set it back to reagent
