### ISSUE TITLE
How to adjust the opacity of the scrolling bar?

### ISSUE THREAD

**Issue by liumeihui1111** [arkayenro/arkinventory#1547]
**What version number you are using?**
V3.09.63

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Classic

**What language is the game client set to?**
Chinese

**Ask your question**
Is ther any possible to adjust the opacity of the scrolling bar?
![QQ截图20211231092224](https://user-images.githubusercontent.com/96895481/147797646-4467483d-e701-4a1c-9361-835ca6556c99.png)

**Comment by arkayenro** [comment]
added in 3.10.00 alpha 10
