### ISSUE TITLE
[BUG] Can't specify the number of bars in a row

### ISSUE THREAD

**Issue by PsyberWolf** [arkayenro/arkinventory#1548]
**What version number you are using?**
Latest

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
When sliding the slider to set the number of bars, it just does nothing.  Even if you reload the ui.  It's like it's ignoring the setting.

**To Reproduce**
Just try to have more slots in a row.

**Comment by arkayenro** [comment]
its working for me.

if you change anything else in that setting does it update the window?  ie is the setting youre changing the one that is set in the profile you are using?

**Comment by PsyberWolf** [comment]
Nope.  I've even done as you suggested and removed all mods.  Still wouldn't work for me.  I love this mod.  It's awesome...with or without this feature.
