### ISSUE TITLE
How do you change font type within the addon?

### ISSUE THREAD

**Issue by volostyle** [arkayenro/arkinventory#1549]
Trying to change the font type within the addon. I found where to change font size, but not type. Is that possible?

**Comment by arkayenro** [comment]
the font selection is on the first page of the config, right at the top

**Comment by volostyle** [comment]
Wow that's embarrassing, I was literally staring at it forever and didn't see that. Thanks!

**Comment by arkayenro** [comment]
dont feel too bad, i knew it was there but still couldnt find it at first, that top row blends in too well
