### ISSUE TITLE
Guild Bank - Logs not showing up

### ISSUE THREAD

**Issue by Jorvanus** [arkayenro/arkinventory#1550]
Hey

Since go live, the logs for money or any tab do now show anything.  

<img width="383" alt="image" src="https://user-images.githubusercontent.com/89010934/150224900-94fb79f8-3e11-4f54-b78f-8ab215974b5f.png">

(On a related not, they always started weirdly scrolled off screen at the bottom, is there a way to change that so the log takes up the whole screen and then you scroll up to see the oldest history?)

**Comment by arkayenro** [comment]
its working perfectly fine for me in retail using 3.09.63

**Comment by Jorvanus** [comment]
On TBC using same version, on any character, with no other addons enabled, I see nothing in any log window. 

How can I erase the cache? (preferably not including the rules?)

**Comment by Jorvanus** [comment]
This is a blizzard error, apologies
