### ISSUE TITLE
Publish on Wago?

### ISSUE THREAD

**Issue by MrUzagi** [arkayenro/arkinventory#1555]
Currently there is only one actual bag addon (AdiBags) on Wago.
Is there any chance that AI could be published on Wago Addons as well in the future?

**Comment by beren12** [comment]
Yes please! They will support you as well with a % of 70% of the ad revenue.

**Comment by beren12** [comment]
or at least update the wow interface build or publish on github

**Comment by arkayenro** [comment]
didnt know this existed.  have created an account and am trying to figure out how it all works, especially when it comes to the libraries that im using

**Comment by beren12** [comment]
from the wowup discord:

```For the WowUpHub, reach out to any of the mods or Zakrn and provide the Github or Gitlab link to your addon. We will check to make sure it is setup so WowUpHub can detect it. Here’s a guide on setup so you can check for yourself: https://wowup.io/guide/wowup/hub

If it is setup with a zipped folder of the addon itself, Zakrn will connect it to the WowUpHub. Once that is done, nothing else is needed on your part for that connection to remain other than you need to make sure when you update your addon on GitHub to do same setup. From 1 hour of you updating your addon it will hit the WowUpHub’s servers for people to download/update.

To add your addon to Wago, go to this website - https://addons.wago.io/auth/login - you will need to sign in to your BattleNet account or GitHub account.  If you sign in with your Github account, you will be able to choose from the available GitHub repositories to upload from. If you sign in with your BattleNet account follow the prompts to upload your addon in its zipped format. If you aren’t sure if everything is setup correctly for Wago, they have provided a how-to documentation webpage that you can use - https://docs.wago.io/#introduction . If you have questions that are not answered you can reach out to Jayow, QartmisT or via Wago's contact form - https://addons.wago.io/contact 
﻿```

**Comment by arkayenro** [comment]
> and there's also the bigwigs packager to make life easy

im sure it was meant to but not quite so easy for me due to having multiple client specific toc files which they dont support

the fun part is i forked and rewrote their packager code to handle multiple tocs and its working with wago and github, just have to test it with curseforge and i should be good to go

**Comment by beren12** [comment]
I think the idea is to have a master toc and they get split out to version specific?

**Comment by arkayenro** [comment]
that might be the old way but as the game now natively supports having multiple client specific tocs itself (and is what i use) i thought it would be better to handle that way.

uploads to wago, and wowi appear to be working ok, curseforge doesnt like not having an actual "default" toc file in there (the game doesnt care so long as you have a client specific one in there)

have to work out alphas at some point

**Comment by arkayenro** [comment]
wowinterface deleted my test mod so i guess im not uploading there

**Comment by arkayenro** [comment]
wago is barfing when i upload the actual mod
`curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)`

the test mod worked fine so im wondering if they have an upload size limit i might be hitting.  its only 1.4mb though

i've lodged a "contact us", we'll see how that goes.

**Comment by arkayenro** [comment]
manually uploaded to wago in the mean time
