### ISSUE TITLE
Cathegory *verschlossen*

### ISSUE THREAD

**Issue by Lekysha85** [arkayenro/arkinventory#1561]
3.09.64

Retail

German

Hi there, my english is not very good. Try to explain my Problem ;) 

My ArkInventory doesnt work till some weeks. There is nothing sorted when I logg in. I can only sort while im logging in via move an item to a numbered window. After relogg this sort is gone again. If i want to sort it as i usually do via Options, any Cathegory is *verschlossen* (locked i think in english).

I try to reinstall Addon.

The Issue is still there if Ark is the only Addon i use. 

Other Versions doesnt work too.

I love this Addon so much. I couldnt life without. Pls help ;)

MFG Tanja

**Comment by arkayenro** [comment]
it sounds like you havent setup any of the blueprint options, or your saved variables file has corrupted and lost it.

the locked profile is the system default, nothing in that can be changed.  you have to setup a new profile, along with new blueprint options.

see https://github.com/arkayenro/arkinventory/wiki/UserGuide_Profiles and https://github.com/arkayenro/arkinventory/wiki/UserGuide_Blueprints
