### ISSUE TITLE
[BUG] Mythic Keystones no longer recognised

### ISSUE THREAD

**Issue by Mobijuan** [arkayenro/arkinventory#1564]
**What version number you are using?**
3.09.65

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Mythic Keystones have their own built in category but these are no longer recognised and each key is set to system>UNKNOWN and no longer displays the key level on the icon.

**To Reproduce**
No steps required, happens on fresh install.

**Comment by arkayenro** [comment]
please try [30965 alpha 1](https://www.curseforge.com/wow/addons/ark-inventory/files/3697009)

**Comment by arkayenro** [comment]
please try [30965 alpha 2](https://www.curseforge.com/wow/addons/ark-inventory/files/3697332)

**Comment by arkayenro** [comment]
fixed in 3.09.66
