### ISSUE TITLE
Protoform Synthesis Items Classed As Junk

### ISSUE THREAD

**Issue by imazombie** [arkayenro/arkinventory#1566]
Just updated to 9.2.0 and all my protoform synthesis materials have been changed to class 'junk' items.

**Comment by arkayenro** [comment]
go into edit mode and check the categories for them, do you have a rule thats picking them up?

theyre normal reagents i think and should end up in that category

**Comment by imazombie** [comment]
The items were all new to 9.2 and I had to manually change the category
from 'junk' to 'reagents'.

**Comment by arkayenro** [comment]
pretty sure blizzard have them categorised as misc/junk but theyre also tagged with crafting reagent so thats where they end up.

its possible blizzard added that part way through
