### ISSUE TITLE
No logs on disposed/withdrawn from guildlog

### ISSUE THREAD

**Issue by SgtMorrigahnGaming** [arkayenro/arkinventory#1569]
**What version number you are using?**
3.09.66

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Ask your question**

Is there a way to see/read the logs of items removed/added into the guildbank? If so, how to do this?
If not, can that be added?

**Comment by arkayenro** [comment]
open the guild bank and in the bag changer area theres a red icon, click on that to toggle between items, item log, and money log

**Comment by SgtMorrigahnGaming** [comment]
Oh my days .. I didn't think about the arrow button for that.. I thought it was to change between the different bags! So sorry!
Thank you for an amazing addon btw :D
