### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ShelaghG** [arkayenro/arkinventory#1573]
**What version number you are using?** 309.66

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta** Retail

**What language is the game client set to?** English

**Describe the bug**
Getting the following errors:
Message: ...face\AddOns\ArkInventory\Core\ArkInventoryConfig.lua:1060: code error: id is nil
Time: Mon May  2 12:11:11 2022
Count: 1
Stack: ...face\AddOns\ArkInventory\Core\ArkInventoryConfig.lua:1060: code error: id is nil
[string "@Interface\AddOns\ArkInventory\Core\ArkInventoryStorage.lua"]:4763: in function `ObjectCacheCountClear'
[string "@Interface\AddOns\ArkInventory\Core\ArkInventoryStorage.lua"]:4773: in function `ObjectCacheCountClear'
[string "@Interface\AddOns\ArkInventory\Core\ArkInventoryStorage.lua"]:414: in function <...ace\AddOns\ArkInventory\Core\ArkInventoryStorage.lua:402>
[string "=[C]"]: ?
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceBucket\AceBucket-3.0.lua"]:73: in function <...Inventory\Externals\Ace3\AceBucket\AceBucket-3.0.lua:71>
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceBucket\AceBucket-3.0.lua"]:87: in function `func'
[string "@Interface\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua"]:57: in function <...\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals: <none>

Message: ...face\AddOns\ArkInventory\Core\ArkInventoryConfig.lua:1060: code error: id is nil
Time: Mon May  2 12:47:01 2022
Count: 31
Stack: ...face\AddOns\ArkInventory\Core\ArkInventoryConfig.lua:1060: code error: id is nil

Locals: <none>

**To Reproduce**
Steps to reproduce the behaviour, if possible: Add to inventory (eg, looting), remove items from inventory (eg, selling to vendors)

**Screenshots**

**Additional context**

**Comment by arkayenro** [comment]
fairly sure your saved variables file has corrupted, it would be the only way to get a null account id in there.

can you rename your arkinventory saved variable file to something else and start the game to see if it still does it?  if you have a backup you could also try that.

**Comment by ShelaghG** [comment]
It must have overwritten it at some point as everything is working as expected today. Thank you for getting back to me :)
