### ISSUE TITLE
Rules for Outfits non-functional

### ISSUE THREAD

**Issue by RCIRacing** [arkayenro/arkinventory#1576]
I use rules to sort outfits into different sections. I carried all my settings over from last expansion, rule worked fine then. Came back playing about 2 months ago and it has not worked since. I decided to try to remove and recreate the rules to no fix. Screenshot attached with everything open.

![WoWScrnShot_061022_133054](https://user-images.githubusercontent.com/69708288/173146397-27713084-6191-4aca-b978-eca31deeabcc.jpg)

Considering if I need to wipe all variables and try because of a big issue between 8.x to 9.x? Issue persists with all mods except AI and addon control panel enabled.

**Comment by RCIRacing** [comment]
Realized this didn't create a "bug" when I clicked new issue on this one.

Version 3.09.67 / English / Retail. I edited the title to include [BUG].

**Comment by arkayenro** [comment]
same deal as the other issue, and as per that tooltip text, you need to create your own categoryset first and then assign that the the location in your profile, then you can enable rules and categories for that location

**Comment by RCIRacing** [comment]
Per other ticket, thanks Arkayenro! :)
