### ISSUE TITLE
[BUG] "not outfit()" rule ignored in bank, but works in backpack

### ISSUE THREAD

**Issue by digitalmuze** [arkayenro/arkinventory#1578]
**What version number you are using?**
v3.09.67 [Shadowlands]

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
"Current" rule for outfit items in backpack interpreted differently when those same items are moved into bank; appears related to "outfit()" function

**To Reproduce**
I have a custom rule named: SB_Items_Exp8_SL
not outfit() and 
expansion( 8 ) and 
soulbound() and 
not subtype( "junk" )

outfit items when moved to my bank are incorrectly claimed by this rule; yet, those same outfit items when in my backpack are excluded, as expected -- appears when these items are in my bank, the portion of the rule "not outfit()" is ignored

**Context**
to confirm, in my profile the controls for both "Backpack" and "Bank" are using the same blueprint options (i.e. style, layout, category set)

**Comment by arkayenro** [comment]
i presume youre using the blizzard equipment manager?
thats been a pain since for a while now when it comes to the bank, and i need to try and work it out at some point,
it wont be soon though as i dont have a lot of time available.

**Comment by digitalmuze** [comment]
> 

In fact, I was also using Outfitter addon; so your response prompted me to test it. When I deactivate Outfitter, then the "not outfit()" function works properly in the bank container -- so now I think the problem with the bank is w/ Outfitter addon

**Comment by digitalmuze** [comment]
< additional test results >

test setup:
Outfitter (continued from shadowlands - fan fixes) v9.1.5.1
ItemRack v3.17
... created several arkinventory rules where each rule captures a separate equipment set by name
... each of these arkinventory rules assigned to separate bars with backpack/bank
... both backpack & bank share the same blueprint settings -- i.e. where same values set for profiles > controls > blueprint > style | layout | category set; so here in both backpack & bank, same sorting results are expected

scenario 1: outfitter off | itemrack off
... no problems detected; but blizzard limits to 10 equipment sets

scenario 2: outfitter off | itemrack on
... fyi / itemrack - limitation: does not automatically register blizzard equipment sets, so each blizzard set must also be manually registered in itemrack
... in both backpack & bank, arkinventory "outfit()" function recognizes itemrack sets, but ignores blizzard equipment sets

scenario 3: outfitter on | itemrack off
... fyi / outfitter: automatically registers blizzard equipment sets, so any change to a blizzard equipment set also changes the corresponding set in outfitter
... in backpack, arkinventory "outfit()" function recognizes gear associated with a blizzard equipment set, but does not recognize an Outfitter outfit
... in bank, arkinventory does not recognize any blizzard equipment set nor Outfitter outfit

**Comment by arkayenro** [comment]
while outfitter may use the equipment manager to store its outfits (im not sure it actually does as i cant see any), arkinventory doesnt (currently) check both.  if outfitter is enabled then it will ask outfitter if the item is in a set and then exit.

im calling the same outfitter functions regardless of where the items are located so if it works for the bag but not the bank then i expect the issue is in the functions being called.

you can also see that the tooltip no longer includes the outfitter set name once its moved to the bank, so it would appear theres a bug in outfitter somewhere.

**Comment by garylisk** [comment]
I have attempted to disable all the addons I have that do anything with equipment management (ItemRack and Ask Mr. Robot Classic) and the outfit rule is still broken. Does not matter if I make an equipment set manually using the Blizzard UI or keep the ones that AMR Classic generates for me. The tooltips show what sets each piece is in, but they won't sort into bars with the rules enabled. 

Also wanted to say the bug someone mentioned earlier about the set tooltip disappearing once in the bank is not happening for me.

I am using ArkInventory Wrath 30968

**Comment by arkayenro** [comment]
@garylisk  try the latest 3.10.00 alpha

**Comment by garylisk** [comment]
> @garylisk try the latest 3.10.00 alpha

Gorgeous, working like a charm.

**Comment by digitalmuze** [comment]
fix confirmed in alpha 3.10.0 - rules which use equipment set names are now properly recognized in bank, thanks! :)
