### ISSUE TITLE
[BUG]  speciesID is nil

### ISSUE THREAD

**Issue by bmtphoenix** [arkayenro/arkinventory#1584]
**What version number you are using?**
3.09.67

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Lua Error:

Message: Interface\AddOns\ArkInventory\Core\ArkInventory.lua:11464: ...dOns\ArkInventory\Core\ArkInventoryCollectionPet.lua:1616: speciesID is nil
Time: Tue Jul 19 17:55:16 2022
Count: 1
Stack: Interface\AddOns\ArkInventory\Core\ArkInventory.lua:11464: ...dOns\ArkInventory\Core\ArkInventoryCollectionPet.lua:1616: speciesID is nil
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\ArkInventory\Core\ArkInventory.lua"]:11464: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: 

**To Reproduce**
Completed a pet battle without capturing anything and this lua error popped up.
I'm not sure how reliably it can be reproduced, this is the first time I've seen this bug.

**Screenshots**
![arkinventory error](https://user-images.githubusercontent.com/6809957/179862833-1c6d62b9-16cb-4484-9e6e-71f0adaed043.jpg)

**Additional context**
It didn't seem to actually break anything.

**Comment by arkayenro** [comment]
i'll recode it to get rid of the error as i dont think its actually an error (theres no impact), more me being too cautious about the functions inputs

**Comment by arkayenro** [comment]
a fix is in 3.09.67 alpha 2
