### ISSUE TITLE
Issue: Feature request: Direct ARGB Value Input?

### ISSUE THREAD

**Issue by boddoleblitzer** [arkayenro/arkinventory#1585]
**Is your feature request related to a problem? Please describe.**
-Forgive me if this already exists but I just haven't seen it. Currently, when changing colors of Bar names, background, edges, and so on, there is only a color picker that uses the mouse. So if I want to re-use a color I can only get 'so close' and end up with a number of sort of the same colors.  I can go into the lua saved variables file and change things manually but it is quite a work around.

**Describe the solution you'd like**
Perhaps on the same UI 'frame' add a direct input for ARGB values (0-255 might be 'ideal' since I know there are lots of pre-defined color pallets online for 0-255 colors, though I guess 0-1 color lists also exist if I look for them).

**Describe alternatives you've considered**
Direct editing of the saved variable lua file.

**Additional context**
N/A.

**Comment by arkayenro** [comment]
theres a mod named ColorPickerPlus that i suggest you get as if thats installed then AI will use that instead, and it allows for a whole lot more color picking functionality.

i use it myself, and its supported by lots of other mods as well, so why reinvent the wheel when you dont have to.

**Comment by boddoleblitzer** [comment]
I'll definitely take a look at it.
