### ISSUE TITLE
How do I disable sorting completely?

### ISSUE THREAD

**Issue by MarshallBuhl** [arkayenro/arkinventory#1586]
**What version number you are using?**
3.09.67

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail WoW

**What language is the game client set to?**
English

**Ask your question**
I just spent an hour sorting my bags in a way that is meaningful to me and then accidentally hit the dreaded Clean Up Bags button that it **_RIGHT UNDERNEATH THE CLOSE BUTTON_**.  Argh! A minor pointing error cost me over an hour.

I have spent a lot of time searching through the confusing menus, searching the web for disabling that feature and came up empty handed.  I have zero desire for someone to tell me how I want my stuff sorted.  I have my own methods.  All I want ArkInventory for is the wonderful feature of seeing what my other toons have on them.  That's all I want.

So, how can I disable the distressful Clean Up Bags button?

**Comment by arkayenro** [comment]
you cant.  you will just have to be careful not to click on it.

if you dont care about the one big bag thing, then dont let AI override the bags and use the default bags.  the tooltips will still let you know what your alts have.

**Comment by MarshallBuhl** [comment]
Well, that's unfortunate.  I've always used the default bags, so unless an option is added to disable that button or at least kick off a dialog asking if I really want to have my bags resorted, I'll just live in fear of that button.  :-D

**Comment by arkayenro** [comment]
added to 3.10.00 alpha 2
