### ISSUE TITLE
[BUG] CURSOR_UPDATE

### ISSUE THREAD

**Issue by rbpaiett** [arkayenro/arkinventory#1589]
**What version number you are using?**
300967

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Classic WotLK

**What language is the game client set to?**
English

**Describe the bug**
When I have enabled only ArkInventory and Gathermate2 (1.46.1-Classic) The following errors appear:

22x ...rkInventory\Externals\Ace3\AceEvent\AceEvent-3.0-4.lua:33: Attempt to register unknown event "CURSOR_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@ArkInventory\Externals\Ace3\AceEvent\AceEvent-3.0-4.lua"]:33: in function `OnUsed'
[string "@ArkInventory\Libs\CallBackHandler\CallbackHandler-1.0-7.lua"]:142: in function `RegisterEvent'
[string "@GatherMate2\Collector.lua"]:77: in function `RegisterGatherEvents'
[string "@GatherMate2\Collector.lua"]:66: in function <GatherMate2\Collector.lua:65>
[string "=[C]"]: ?
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:70: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65>
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:540: in function `EnableAddon'
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:630: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@ArkInventory\Core\ArkInventory-30967.lua"]:10511: in function `LoadAddOn'
[string "@ArkInventory\Core\ArkInventory-30967.lua"]:10533: in function `BlizzardAPIHook'
[string "@ArkInventory\Core\ArkInventory-30967.lua"]:2779: in function <ArkInventory\Core\ArkInventory.lua:2749>
[string "=[C]"]: ?
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:70: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65>
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:630: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:615>

**To Reproduce**
Just perform /reload

**Screenshots**
Self-explanatory unless you feel I need one.

**Additional context**
No other context

**Comment by arkayenro** [comment]
as far as im aware i dont use CURSOR_UPDATE, but the error indicated that GatherMate2 does so feel free to disable AI and see if the error still happens.

**Comment by rbpaiett** [comment]
Ok, I'll give it a go.
