### ISSUE TITLE
[BUG] Bags won't open (Wrath)

### ISSUE THREAD

**Issue by wharrig** [arkayenro/arkinventory#1590]
**What version number you are using?**
3.09.67

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Wrath of the Lich King Classic

**What language is the game client set to?**
English

**Describe the bug**
When opening bags the Arkinventory bag screen is blank and there is a Loading... in the lower left corner.

**To Reproduce**
Hit 'B' to open bags.

**Screenshots**

![WoWScrnShot_090222_160015](https://user-images.githubusercontent.com/112728439/188227918-8d140382-c9c2-416b-b8ca-81f1112cd397.jpg)

**Additional context**
Deleted the addon and reinstalled with no change to the behavior.

Also disabled all other addons and again no change in behavior.

**Comment by iymeko** [comment]
I'm having the same problem.

**Comment by laurentL** [comment]
Same issue  here.
Delete all savedVaribale file without success
All character are impected

**Comment by DannyJo** [comment]
Looks like this is due to a hotfix in the client changing the `WOW_PROJECT_ID` to now be `WOW_PROJECT_WRATH_CLASSIC`. 

Other addons are having similar issues. I managed to temporarily solve this by editing `Core/ArkInventoryClient.lua:358` and replacing `WOW_PROJECT_BURNING_CRUSADE_CLASSIC` with `WOW_PROJECT_WRATH_CLASSIC`.

**Comment by HoffCoder** [comment]
> Other addons are having similar issues. I managed to temporarily solve this by editing `Core/ArkInventoryClient.lua:358` and replacing `WOW_PROJECT_BURNING_CRUSADE_CLASSIC` with `WOW_PROJECT_WRATH_CLASSIC`.

Applied this fix and It worked for me!

**Comment by arkayenro** [comment]
linking other reports to this one #1591 #1592

**Comment by DanSheps** [comment]
@arkayenro you can do "Duplicate of #1591" to link it as a duplicate

**Comment by arkayenro** [comment]
3.09.67 alpha 2 on curseforge - https://www.curseforge.com/wow/addons/ark-inventory/files/3964928

its on wago as well if you use that

**Comment by wharrig** [comment]
The 3.09.67 alpha 2 update appears to have fixed the issue.

Thank you for the quick response.
