### ISSUE TITLE
[BUG] Lua Error in Classic

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1596]
6x ArkInventory\Core\ArkInventory-31000.1.lua:8210: attempt to call global 'BattlePetToolTip_Show' (a nil value)
[string "@ArkInventory\Core\ArkInventory-31000.1.lua"]:8210: in function `Frame_Item_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
frame = ARKINV_Frame3ScrollContainerBag1Item7 {
 0 = <userdata>
 BattlepayItemTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 ArkLevel = ARKINV_Frame3ScrollContainerBag1Item7Level {
 }
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 icon = ARKINV_Frame3ScrollContainerBag1Item7IconTexture {
 }
 UpdateTooltip = <function> defined @ArkInventory\Core\ArkInventory.lua:8061
 ArkHighlight = ARKINV_Frame3ScrollContainerBag1Item7ArkHighlight {
 }
 ARK_Data = <table> {
 }
 UpgradeIcon = <unnamed> {
 }
 ArkTint = ARKINV_Frame3ScrollContainerBag1Item7ArkTint {
 }
 NewItemTexture = <unnamed> {
 }
 SplitStack = <function> defined @Interface_TBC\FrameXML\BankFrame.lua:18
 BagStaticBottom = <unnamed> {
 }
 ArkBorder = ARKINV_Frame3ScrollContainerBag1Item7ArkBorder {
 }
 GetInventorySlot = <function> defined @Interface_TBC\FrameXML\BankFrame.lua:5
 ArkListEntry = ARKINV_Frame3ScrollContainerBag1Item7ArkListEntry {
 }
 ArkIconTransmog = ARKINV_Frame3ScrollContainerBag1Item7ArkIconTransmog {
 }
 ExtendedSlot = <unnamed> {
 }
 ArkIconOverlay = ARKINV_Frame3ScrollContainerBag1Item7ArkIconOverlay {
 }
 hasItem = 1
 JunkIcon = <unnamed> {
 }
 count = 1
 ArkIconQuest = ARKINV_Frame3ScrollContainerBag1Item7ArkIconQuest {
 }
 locked = false
 flash = <unnamed> {
 }
 Count = ARKINV_Frame3ScrollContainerBag1Item7Count {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 ArkItemAge = ARKINV_Frame3ScrollContainerBag1Item7ArkItemAge {
 }
 searchOverlay = ARKINV_Frame3ScrollContainerBag1Item7SearchOverlay {
 }
 ExtendedOverlay = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
}
loc_id = 3
bag_id = 1
slot_id = 7
i = <table> {
 q = 3
 h = "|cff0070dd|Hitem:9240::::::::70:::::::::|h[Mallet of Zul'Farrak]|h|r"
 slot_id = 7
 sb = 3
 loc_id = 3
 bag_id = 1
 count = 1
}
blizzard_id = -1
reset = true
tbl = <table> {
 1 = true
 2 = false
 3 = 4388
}
hasCooldown = true
repairCost = false
speciesID = 4388
level = nil
breedQuality = nil
maxHealth = nil
power = nil
speed = nil
name = nil
showSell = nil
(*temporary) = nil
(*temporary) = 4388
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to call global 'BattlePetToolTip_Show' (a nil value)"
string = <table> {
 split = <function> defined =[C]:-1
 match = <function> defined =[C]:-1
 gmatch = <function> defined =[C]:-1
 upper = <function> defined =[C]:-1
 gsub = <function> defined =[C]:-1
 format = <function> defined =[C]:-1
 utf8sub = <function> defined @Outfitter\Libraries/UTF8/utf8.lua:183
 lower = <function> defined =[C]:-1
 sub = <function> defined =[C]:-1
 len = <function> defined =[C]:-1
 utf8lower = <function> defined @Outfitter\Libraries/UTF8/utf8.lua:276
 gfind = <function> defined =[C]:-1
 join = <function> defined =[C]:-1
 rep = <function> defined =[C]:-1
 utf8len = <function> defined @Outfitter\Libraries/UTF8/utf8.lua:158
 char = <function> defined =[C]:-1
 rtgsub = <function> defined @FrameXML\RestrictedInfrastructure.lua:612
 utf8upper = <function> defined @Outfitter\Libraries/UTF8/utf8.lua:266
 reverse = <function> defined =[C]:-1
 byte = <function> defined =[C]:-1
 trim = <function> defined =[C]:-1
 utf8reverse = <function> defined @Outfitter\Libraries/UTF8/utf8.lua:286
 find = <function> defined =[C]:-1
}
helper_DragState = <function> defined @ArkInventory\Core\ArkInventory.lua:6512

**Comment by arkayenro** [comment]
will be fixed next alpha release

**Comment by arkayenro** [comment]
fixed in alpha 2
