### ISSUE TITLE
[BUG] Bug on Loot of Heroic Badges in Classic

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1597]
Bug on Loot of Heroic Badges in Classic

8x ...aceArkInventory\Core\ArkInventoryTooltip.lua:1580: attempt to call field 'GetFactionGrantedByCurrency' (a nil value)
[string "@ArkInventory\Core\ArkInventoryTooltip.lua"]:1580: in function <...aceArkInventory\Core\ArkInventoryTooltip.lua:1577>
[string "=(tail call)"]: ?
[string "@ArkInventory\Core\ArkInventoryTooltip.lua"]:1375: in function `HookTooltipSetGeneric'
[string "@ArkInventory\Core\ArkInventoryTooltip.lua"]:1488: in function <...aceArkInventory\Core\ArkInventoryTooltip.lua:1487>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetLootCurrency'
[string "@FrameXML\LootFrame.lua"]:363: in function `LootItem_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
currencyID = 42
(*temporary) = nil
(*temporary) = 42
(*temporary) = "attempt to call field 'GetFactionGrantedByCurrency' (a nil value)"

**Comment by arkayenro** [comment]
will be fixed in alpha 3

**Comment by arkayenro** [comment]
fixed in alpha 4
