### ISSUE TITLE
[BUG] Memory Leak opening/closing bags

### ISSUE THREAD

**Issue by DragonKarsh** [arkayenro/arkinventory#1598]
**What version number you are using?**
3.09.68

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Wotlk Classic

**What language is the game client set to?**
en-US

**Describe the bug**
Memory leak

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Open and close bags and observe memory constantly goes up. It does not matter how many times you open and close your bags, the memory will constantly increase.

**Screenshots**

**Additional context**
 I understand there are a lot of calculations that should be occuring when bags are opened. But should that data not be cached, and if a recalculation is needed, then the resources which were used for the previous calculation surely should be released to be garbage collected.

**Comment by arkayenro** [comment]
* its not a memory leak (i dont think those are even possible with mods)
* a massive amount of the data is cached (its why it uses so much memory)
* there is also a lot of data that is temporary when calculating the window layout
  * if you have sorting set to always, or on window open, then youre typically always forcing a recalculation making it worse.  set sorting to manual and see how it goes
* garbage collection is done by lua itself
   * you are not meant to force one (and im not sure if blizzard added the function)
   * if you wait long enough for that to kick in it will drop back down to whats actually being used

unless you are running out of memory (which im pretty sure youre not) its never going to be an actual issue
