### ISSUE TITLE
[BUG] Debug Text on Screen

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1602]
Getting some debug text on screen. I think it happened when I changed zones. Latest version in Classic.

![image](https://user-images.githubusercontent.com/55365231/192711721-714b646d-1c47-47a5-9744-f2072286720d.png)

**Comment by arkayenro** [comment]
yep, i left some debug output in after fixing some of the tradeskill stuff.  will be gone next alpha

**Comment by arkayenro** [comment]
fixed in alpha 6
