### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by isanusi123** [arkayenro/arkinventory#1603]
v 3.09.68 wrath of the lich king

Wrath classic

English

**Describe the bug**
The outfit() function appears to not work using the blizzard equipment manager.
I have a rule for outfit() that has no affect, and a rule for outfit("heals") that also has no affect.  
before the prepatch i used an addon and it worked fine.

**To Reproduce**
make an outfit, make a rule.  seems to be consistantly not working for me.

**Comment by arkayenro** [comment]
how do you get at the equipment manager in wrath?  its not available on the character pane for me

**Comment by stratoru** [comment]
![image](https://user-images.githubusercontent.com/43893231/192923336-dc2f18fa-c8a1-4cb9-a412-8d2aac9dc5ba.png)

**Comment by arkayenro** [comment]
ah, wrath doesnt have void storage so EquipmentManager_UnpackLocation doesnt have those in the return values

will be fixed in the next alpha

**Comment by arkayenro** [comment]
fixed in alpha 6

**Comment by arkayenro** [comment]
duplicate of #1593

**Comment by isanusi123** [comment]
thank you very much!
