### ISSUE TITLE
[BUG] Classic Quivers & Soul Shard Bags

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1604]
Latest build (probably 2-3 builds ago actually) did away with Quivers / Ammo Pouches and Soul Shard Bags on Classic. Can we get those back again? (=

![image](https://user-images.githubusercontent.com/55365231/193085496-b8dfb754-888a-4ed8-bb5e-c46d198ac731.png)

**Comment by arkayenro** [comment]
issue with the client detection code, will be fixed next alpha

**Comment by Gogo1951** [comment]
Running the alpha but I don't see the fix. Sorry to nag, just wanted to make sure it was fixed if it's supposed to be.

**Comment by arkayenro** [comment]
its in alpha 7, my current working copy.  probably out later today

**Comment by arkayenro** [comment]
fixed in 3.10.00 alpha 7
