### ISSUE TITLE
[BUG] 'Summon Mount' Keybinding in Dragonflight Beta

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1615]
**What version number you are using?**
v31000.9 Alpha

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Beta

**What language is the game client set to?**
English

**Describe the bug**
I usually have one of my extra mouse buttons bound to the 'summon mount' keybinding that ArkInventory provides.  It works really well.  This keybinding appears broken in the beta.

The functionality seems to work just fine as I can click on the LDB button presented on a broker bar like Titan Panel as it toggles between a mounted / unmounted state. 

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Gameplay -> Keybindings.  Set a keybinding to 'Summon Mount' in the 'Addons' section.  Try to use that keybinding.

As an aside, are you planning on creating a named section for ArkInventory in the Keybindings like some of the other addons are doing or will they always simply reside under the general 'Addons' section?  It would be a nice-to-have if all the keybindings for ArkInventory were all gathered into their own section.  (Please see screenshot.)

**Screenshots**

![Keybindings View for Beta Addons](https://user-images.githubusercontent.com/13042214/194433676-2481e452-1a12-448b-b74e-9169a950cff7.PNG)

**Additional context**
Thanks for continuing to support this amazing addon!

**Comment by arkayenro** [comment]
mounts pets and toys probably wont work in wrath until i recode them as pandaria changed it to collections so the code is only in the old wrath versions (when it was retail) and i'd have to pull it out and add into the existing code.  it can be done it will just take time.

funnily enough the addons section doesnt actually exist, its just something a lot of addon authors decided to go with so that everything ended up underneath a common area.  i dont mind where it ends up though.

**Comment by Calesta** [comment]
Arkayenro, 

I probably wasn't clear from the title but this is in the Dragonflight Beta.  Or perhaps you know that and all the talk about Wrath / Pandaria is related to the code used back in those expansions?

In any case, thanks for entertaining the idea of fixing it if you're able and have the bandwidth.

**Comment by arkayenro** [comment]
ah, too many wrath issues as well.
found the problem with the keybinding, should be fixed next alpha (11)

**Comment by arkayenro** [comment]
fixed (i think) in 3.10.00 alpha 11

**Comment by Calesta** [comment]
Arkayenro, this seems to be broken again in Alpha 16.  I don't think I can 'reopen' this ticket so it's likely you'd have to do it.  If I don't see any movement here, I'll just create another issue.

**Comment by arkayenro** [comment]
its at teh point where blizzard have completely broken it.  the workaround i had before no longer works.

theres nothing i can do now until blizzard fixes it.

**Comment by Calesta** [comment]
Just FYI.  This is working in the current retail pre-patch build.  I'm not sure if anything will change once they flip the switch for Dragonflight, but I hoping that it stays this way. :)
