### ISSUE TITLE
[BUG] LUA error thrown, might be AddonSkins related

### ISSUE THREAD

**Issue by BeeJayJayn** [arkayenro/arkinventory#1623]
**What version number you are using?**
3.10.01

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Live 10.0

**What language is the game client set to?**
eng

**Describe the bug**
```lua
11x Usage: self:SetNormalTexture(asset)
[string "=[C]"]: in function `SetNormalTexture'
[string "@Interface/AddOns/AddOnSkins/Skins/AddOns/ArkInventory.lua"]:83: in function <...face/AddOns/AddOnSkins/Skins/AddOns/ArkInventory.lua:73>
[string "=[C]"]: in function `Frame_Item_Update_Border'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:9291: in function `Frame_Item_Update'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:6411: in function `Frame_Bar_DrawItems'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:5662: in function `Frame_Container_Draw'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:4255: in function `Frame_Main_Draw_Threaded'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:4182: in function <Interface/AddOns/ArkInventory/Core/ArkInventory.lua:4181>

Locals:
(*temporary) = "Usage: self:SetNormalTexture(asset)"
```

**Comment by BeeJayJayn** [comment]
Might be AddonSkins related, but as far as I know they tell the addon devs to fix their stuff?

**Comment by BeeJayJayn** [comment]
![image](https://user-images.githubusercontent.com/35027294/198240829-0af0cfff-a424-4da3-9020-2d669edbe67e.png)
Could it be related to the new "profession bag" slot?

**Comment by arkayenro** [comment]
i dont think so, the error trace appears to show the normal items being drawn and failing on one of their borders.

ArkBorder has always been a pretty simple frame so i can set the border edges on it,

It shouldnt have a NormalTexture, its not (and never has been) a button, which do have a NormalTexture

**Comment by BeeJayJayn** [comment]
Okay, was just guessing tbh. Should I open an issue with Addonskins (if I can) or is this something that you have already done / will do?

**Comment by arkayenro** [comment]
you will need to open a ticket with them.  i dont use it.

if they need anything have them ask on this thread.

**Comment by Azilroka** [comment]
This is definitely not @arkayenro issue. There is a toggle for the skin for a reason. It Auto disables itself unless you have skin debug turn on which you shouldn't have on unless you are actively debugging the code.

**Comment by BeeJayJayn** [comment]
> It Auto disables itself unless you have skin debug turn on

So its a @BeeJayJayn problem or is this something that your code does? Am uncertain if I did fuck something up x)
