### ISSUE TITLE
[BUG] Retail issues after prepatch

### ISSUE THREAD

**Issue by elderswordsman** [arkayenro/arkinventory#1625]
**What version number you are using?**
ArkInventory-3.09.68
ArkinventoryCharacterRules-1.0.9
Df-ArkinventoryRules-0.14.0

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Hi There, love the addon, seeing some issues after the prepatch yesterday that I wanted to report. 
 
Running on MacOS 12.6
 
The problem is the the inventory window opens but it says "Loading…" In the lower left corner. No money count, no bag info (ERR on each one). No items. Clicking the cogwheel did nothing
And I get this error: 
ERROR>Interface?AddOns/ArkInventory/Core/Arkinventory.lua:7089:attempt to call global ‘ContainerFrameItemButton_UpdateItemUpgradeIcon’ (a nil value)
 
If I remove my ArkInventory.lua file (to try get things to default), it's a little different. If I click on the cogwheel I can see the placeholders for the different storage zones (but still no items, bag info, money info). But I get this error:
 
Error>Interface/FrameXML/MoneyFrame.lua:542: attempt to index local ‘goldButton’ (a nil value)
 
If I disable all my other plugins, I get one additional error that ArkInventory is throwing
ERROR>Failed to load Blizzard_TradeSkillUI: Missing

**Comment by arkayenro** [comment]
upgrade to 3.10.00
