### ISSUE TITLE
[BUG] ArkInventory is calling a function exclusive to Blizzard UI

### ISSUE THREAD

**Issue by Xaymar** [arkayenro/arkinventory#1626]
**What version number you are using?**
3.10.01

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail 10.0.2

**What language is the game client set to?**
English

**Describe the bug**
A small window appears about ArkInventory using a protected function only available to Blizzard UI.

**To Reproduce**
One way to trigger it:

1. Open Options
2. Go to Keybindings
3. Close Options

Seems to also occur at random during gameplay.

**Screenshots**
![image](https://user-images.githubusercontent.com/437395/198045452-f4d6f02f-dd68-47e3-b559-4ac8856d666c.png)

**Additional context**
Kind of expected one of the bigger lua error popups, not a tiny one with absolutely no info. Is there an addon or command that restores that?

**Comment by mjuopperi** [comment]
`/console scriptErrors 1` enables LUA errors, but this small error seems to be a new thing.

**Comment by arkayenro** [comment]
thats taint, which isnt exactly an error.

see https://github.com/arkayenro/arkinventory/wiki/Taint-and-ADDON_ACTION_BLOCKED

**Comment by Xaymar** [comment]
Oddly enough, I can no longer trigger this. Instead I now get an `Interface action blocked by Addon`, and occasionally a full Blizzard UI crash. Perhaps the new UI is itself causing these issues.

**Comment by Xaymar** [comment]
Got it to happen again, and figured out the exact steps:

```
10/27 18:51:17.917  Global variable BINDING_NAME_ARKINV_JUNK_SELL tainted by ArkInventory - Interface/AddOns/ArkInventory/Core/ArkInventory.lua:1001
10/27 18:51:17.917  Execution tainted by ArkInventory while reading BINDING_NAME_ARKINV_JUNK_SELL - Interface/SharedXML/BindingUtil.lua:141 GetBindingName()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_Keybindings.lua:311 Frame:Init()
10/27 18:51:17.917      Interface/FrameXML/SettingDefinitions/Keybindings.lua:45 Frame:Init()
10/27 18:51:17.917      Interface/SharedXML/Scroll/ScrollUtil.lua:439
10/27 18:51:17.917      securecallfunction()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_SettingsList.lua:52 initializer()
10/27 18:51:17.917      Interface/SharedXML/Scroll/ScrollBoxListView.lua:283 InvokeInitializers()
10/27 18:51:17.917      Interface/SharedXML/Scroll/ScrollBox.lua:657 Frame:Update()
10/27 18:51:17.917      Interface/SharedXML/Scroll/ScrollBox.lua:233 Frame:SetScrollPercentageInternal()
10/27 18:51:17.917      Interface/SharedXML/Scroll/ScrollBox.lua:151 FullUpdateInternal()
10/27 18:51:17.917      Interface/SharedXML/Scroll/ScrollBox.lua:631 Frame:FullUpdateInternal()
10/27 18:51:17.917      Interface/SharedXML/Scroll/ScrollBox.lua:113 Frame:FullUpdate()
10/27 18:51:17.917      Interface/SharedXML/Scroll/ScrollBox.lua:605
10/27 18:51:17.917      securecallfunction()
10/27 18:51:17.917      Interface/SharedXML/CallbackRegistry.lua:143
10/27 18:51:17.917      secureexecuterange()
10/27 18:51:17.917      Interface/SharedXML/CallbackRegistry.lua:146 TriggerEvent()
10/27 18:51:17.917      Interface/SharedXML/Scroll/ScrollBoxListView.lua:225 SignalDataChangeEvent()
10/27 18:51:17.917      Interface/SharedXML/Scroll/ScrollBoxListView.lua:205 SetDataProvider()
10/27 18:51:17.917      Interface/SharedXML/Scroll/ScrollBox.lua:589
10/27 18:51:17.917      securecallfunction()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_SettingsList.lua:101 Frame:Display()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:782 SettingsPanel:DisplayLayout()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:758 SettingsPanel:DisplayCategory()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:725
10/27 18:51:17.917      securecallfunction()
10/27 18:51:17.917      Interface/SharedXML/CallbackRegistry.lua:143
10/27 18:51:17.917      secureexecuterange()
10/27 18:51:17.917      Interface/SharedXML/CallbackRegistry.lua:146 Frame:TriggerEvent()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_CategoryList.lua:136
10/27 18:51:17.917  Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:524
10/27 18:51:17.917  An action was blocked because of taint from ArkInventory - SpellStopCasting()
10/27 18:51:17.917      Interface/FrameXML/UIParent.lua:4006 ToggleGameMenu()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:292 SettingsPanel:TransitionBackOpeningPanel()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:281 SettingsPanel:ExitWithCommit()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:257 SettingsPanel:Close()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:44
10/27 18:51:17.917  Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:524
10/27 18:51:17.917  An action was blocked because of taint from ArkInventory - SpellStopTargeting()
10/27 18:51:17.917      Interface/FrameXML/UIParent.lua:4007 ToggleGameMenu()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:292 SettingsPanel:TransitionBackOpeningPanel()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:281 SettingsPanel:ExitWithCommit()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:257 SettingsPanel:Close()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:44
10/27 18:51:17.917  Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:524
10/27 18:51:17.917  An action was blocked because of taint from ArkInventory - ClearTarget()
10/27 18:51:17.917      Interface/FrameXML/UIParent.lua:4019 ToggleGameMenu()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:292 SettingsPanel:TransitionBackOpeningPanel()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:281 SettingsPanel:ExitWithCommit()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:257 SettingsPanel:Close()
10/27 18:51:17.917      Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:44
```

**Comment by arkayenro** [comment]
what were the steps?

potentially all i can see is you might have pressed the keybinding for the junk sell, then opened the game menu?

**Comment by Xaymar** [comment]
I updated the OP with the new steps with the last post.

**Comment by Cloggie77** [comment]
Attempting to upgrade the item level of an item will also cause this error.

**Comment by zcourge** [comment]
I get this error as well. I have no keybindings set for ArkInventory, and it still appears, so there's something wonky about how the keybindings are coded I assume

**Comment by perrinaz** [comment]
Here are two more (from BugSack). I included them here because I get the same dialog about opening something only available to Blizzard.  If they should be separate issues, let me know and I'll create.

For this one, I went into the keybinding options screen.  I did not change ANY bindings (I was looking one up for movement) and got the error when I closed the config screen:

2x [ADDON_ACTION_FORBIDDEN] AddOn 'ArkInventory' tried to call the protected function 'SpellStopCasting()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SpellStopCasting'
[string "@Interface/FrameXML/UIParent.lua"]:4006: in function `ToggleGameMenu'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:292: in function `TransitionBackOpeningPanel'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:281: in function `ExitWithCommit'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:257: in function `Close'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:44: in function <...erface/SharedXML/Settings/Blizzard_SettingsPanel.lua:43>

This one occured while trying to upgrade PvP gear in Oribos and the upgrade fails:

1x [ADDON_ACTION_FORBIDDEN] AddOn 'ArkInventory' tried to call the protected function 'UpgradeItem()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UpgradeItem'
[string "@Interface/AddOns/Blizzard_ItemUpgradeUI/Blizzard_ItemUpgradeUI.lua"]:104: in function `OnConfirm'
[string "@Interface/FrameXML/StaticPopup.lua"]:355: in function `OnAccept'
[string "@Interface/FrameXML/StaticPopup.lua"]:5269: in function `StaticPopup_OnClick'
[string "*StaticPopup.xml:24_OnClick"]:1: in function <[string "*StaticPopup.xml:24_OnClick"]:1>

**Comment by arkayenro** [comment]
its possible its my code - there is no way around it at the moment - but if you have other mods installed it could be from them.

disable AI and see if it still happens.

**Comment by arkayenro** [comment]
config > advanced > workaround > playerinteractionframemanager

untick enabled

youll get the default bank and guild bank frames but it should not be able to taint any more. if if keeps doing it then it should at least blame the mod thats causing it (if it wasnt me)

**Comment by Xaymar** [comment]
Well, my original report goes away when disabling ArkInventory. Not sure about the other cases that people have reported.

**Comment by Xaymar** [comment]
The currently available version of ArkInventory, 3.10.04, still has the issue as described when used by itself. The steps to reproduce the issue are identical to the ones listed in the OP after updating it.

![image](https://user-images.githubusercontent.com/437395/200165464-f70c2ac0-f0ab-426e-97ff-1335b466b8ff.png)
![image](https://user-images.githubusercontent.com/437395/200165493-eb50bbbf-eb0f-439e-a2d5-cd93af538b95.png)

Is there going to be a release with this bug fixed, given that this was closed as completed?

**Comment by arkayenro** [comment]
did you follow the instructions to disable the playerinteractionframemanager?

**Comment by Xaymar** [comment]
Yes, the issue still occurs. This is happening with the Keybindings menu, like described in the OP, not anywhere else like the bank or guild bank.
