### ISSUE TITLE
[BUG] Unable to open guildbank

### ISSUE THREAD

**Issue by MarvinFlint** [arkayenro/arkinventory#1627]
**What version number you are using?**
3.10.01

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail - 10.0.0.46313

**What language is the game client set to?**
English

**Describe the bug**
When attempting to open the guildbank, nothing happens. No error message, no popup, nothing.
Not even Bugsack / Buggrabber report anything. (See screenshot)

**To Reproduce**
- Walk to a guildbank of your choosing
- Try to interact with it
- Observe nothing happening

**Screenshots**

![image](https://user-images.githubusercontent.com/27552004/198088107-bbf5bce5-c60b-4b90-8b24-ac30231b656b.png)

**Comment by imazombie** [comment]
I can confirm same issue, unable to access guildbank after updating to 10.0.2

**Comment by arkayenro** [comment]
its fixed in 3.10.01 alpha 1
