### ISSUE TITLE
Addon is listed as out of date 

### ISSUE THREAD

**Issue by jsaue003** [arkayenro/arkinventory#1628]
What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta
Retail 10.0.0

What language is the game client set to?
English

Describe the bug
Says addon is out of date even though I have latest version that matches the version of the game
![image](https://user-images.githubusercontent.com/32148757/198119474-9471bfb8-e877-4326-84ee-67ad3e76dccc.png)

**Comment by arkayenro** [comment]
the version is set to 10.0.2 for dragonflight so it will go away in a couple of weeks

just tick the box to load out of date addons.
