### ISSUE TITLE
[BUG] Pawn arrow not shown

### ISSUE THREAD

**Issue by malfurion** [arkayenro/arkinventory#1629]
**What version number you are using?**
3.10.01

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail (10.0.0)

**What language is the game client set to?**
English

**Describe the bug**
In combination with pawn is arkinventory not showing the item upgrade arrow without arkinventory it works fine

**To Reproduce**
Steps to reproduce the behaviour, if possible:
- install arkinventory and pawn
- check item with update in bag

**Screenshots**
![image](https://user-images.githubusercontent.com/634939/198145283-1e1a1b87-b90d-4fca-aafd-fd26bfab4c66.png)
![image](https://user-images.githubusercontent.com/634939/198145348-14304312-1c90-40b3-8194-a077a97e6a9a.png)

**Additional context**

**Comment by arkayenro** [comment]
will be fixed in 3.10.01 alpha 3

**Comment by malfurion** [comment]
fixed in .02 version
