### ISSUE TITLE
[BUG] multiple errors on load with Dragonflight pre-patch

### ISSUE THREAD

**Issue by fraerie** [arkayenro/arkinventory#1633]
**What version number you are using?**
ArkInventory 3.10.01 alpha 2

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Load in game

**Screenshots**

**Additional context**

4x CreateFrame(): Couldn't find inherited node "OptionsCheckButtonTemplate"
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Postal/Modules/Select.lua"]:108: in function <Interface/AddOns/Postal/Modules/Select.lua:75>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:66: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:626: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:11011: in function `LoadAddOn'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:11027: in function `BlizzardAPIHook'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:2881: in function <Interface/AddOns/ArkInventory/Core/ArkInventory.lua:2850>
[string "=[C]"]: ?
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:66: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:626: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:611>

4x AceEvent30Frame:RegisterEvent(): AceEvent30Frame:RegisterEvent(): Attempt to register unknown event "CURSOR_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceEvent/AceEvent-3.0-4.lua"]:33: in function `OnUsed'
[string "@Interface/AddOns/ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-7.lua"]:142: in function `RegisterEvent'
[string "@Interface/AddOns/Rarity/Core/EventHandlers.lua"]:68: in function `Register'
[string "@Interface/AddOns/Rarity/Core.lua"]:189: in function `DoEnable'
[string "@Interface/AddOns/Rarity/Core.lua"]:151: in function <Interface/AddOns/Rarity/Core.lua:150>
[string "=[C]"]: ?
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:66: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:626: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:11011: in function `LoadAddOn'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:11027: in function `BlizzardAPIHook'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:2881: in function <Interface/AddOns/ArkInventory/Core/ArkInventory.lua:2850>
[string "=[C]"]: ?
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:66: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:626: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:611>

4x ...ddOns/PetJournalEnhanced/modules/HookedFunctions.lua:124: attempt to index global 'PetJournalListScrollFrame' (a nil value)
[string "@Interface/AddOns/PetJournalEnhanced/modules/HookedFunctions.lua"]:124: in function <...ddOns/PetJournalEnhanced/modules/HookedFunctions.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:66: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:619: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:11011: in function `LoadAddOn'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:11027: in function `BlizzardAPIHook'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:2881: in function <Interface/AddOns/ArkInventory/Core/ArkInventory.lua:2850>
[string "=[C]"]: ?
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:66: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:626: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:611>

**Comment by arkayenro** [comment]
thats an error with postal, you need to update it or wait for it to be updated

disable arkinventory and it will still happen.  disable postal and it will go away.
