### ISSUE TITLE
Rule returning false positive after 10.0

### ISSUE THREAD

**Issue by chadmccune** [arkayenro/arkinventory#1634]
**What version number you are using?**
3.10.01

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Live

**What language is the game client set to?**
English

**Describe the bug**
I'm playing my mage and have had the following rule set up for quite a long time.  It no longer works correctly in 10.0

Seems to be returning false positive

**To Reproduce**
Disabled all addons except ArkInventory
Create following rule:
usable() and transmog()

Right now a "mail" waist and a cosmetic "mace"  passes the rule

**Screenshots**
https://i.postimg.cc/zbk1YWtQ/Wo-WScrn-Shot-102722-010401.jpg
https://i.postimg.cc/phvtSkZ8/Wo-WScrn-Shot-102722-010419.jpg
https://i.postimg.cc/VrPY8zYJ/Wo-WScrn-Shot-102722-010431.jpg

**Additional context**

**Comment by arkayenro** [comment]
`transmog( )` doesnt look broken, they have appearances you havent learnt (because you cant learn them)
`usable( )` must be whats broken

can you mouse over the actual items?

**Comment by arkayenro** [comment]
yep, blizzard changed the colour of the red they use so it no longer matches what i was checking for.

will be fixed in the next release
