### ISSUE TITLE
[BUG] Can't deposit anima at covenant sanctum

### ISSUE THREAD

**Issue by OwenNicholson** [arkayenro/arkinventory#1635]
**What version number you are using?**
v31002 [Shadowlands]

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Live

**What language is the game client set to?**
English

**Describe the bug**
When I try to deposit anima in the sanctum reservoir I get a popup that says "ArkInventory has been blocked from an action only available to he Blizzard UI. You can disable this addon and reload the UI."

I've disabled all other addons and also removed the WTF folder in case it was something in my profile.
If I disable ArkInventory and leave all the other addons loaded, I can deposit anima.

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Attempt to deposit anima in the covenant sanctum.

**Screenshots**

**Additional context**
Found [this page](https://github.com/arkayenro/arkinventory/wiki/Taint-and-ADDON_ACTION_BLOCKED) that sounded relevant, this is the taint.log contents.

10/27 12:44:42.144  Execution tainted by ArkInventory while reading ARKINV_Frame14 - Interface/FrameXML/UIParent.lua:3307
10/27 12:44:42.144      securecall()
10/27 12:44:42.144      Interface/FrameXML/UIParent.lua:3347
10/27 12:44:42.144      securecall()
10/27 12:44:42.144      Interface/FrameXML/UIParent.lua:2643 Frame:ShowUIPanel()
10/27 12:44:42.144      Interface/FrameXML/UIParent.lua:2552
10/27 12:44:42.144      Frame:SetAttribute()
10/27 12:44:42.144      Interface/FrameXML/UIParent.lua:3150 ShowUIPanel()
10/27 12:44:42.144      Interface/AddOns/Blizzard_CovenantSanctum/Blizzard_CovenantSanctum.lua:25 CovenantSanctumFrame:InteractionStarted()
10/27 12:44:42.144      Interface/FrameXML/PlayerInteractionFrameManager.lua:133 showFunc()
10/27 12:44:42.144      Interface/FrameXML/PlayerInteractionFrameManager.lua:183
10/27 12:44:42.144      Interface/FrameXML/PlayerInteractionFrameManager.lua:215
10/27 12:44:42.144  Interface/SharedXML/HelpTip.lua:602 Matches()
10/27 12:44:42.144  An action was blocked because of taint from ArkInventory - DepositAnima()
10/27 12:44:42.144      Interface/AddOns/Blizzard_CovenantSanctum/Blizzard_CovenantSanctumUpgrades.lua:327 Frame:DepositAnima()
10/27 12:44:42.144      Button:lizzard_CovenantSanctumUpgrades.xml:594_OnClick()

**Comment by arkayenro** [comment]
try alpha 5, config > advanced > woraround > playerinteractionframemanager

untick enabled

youll get the default bank and guild bank frames but it should not be able to taint any more.  if if keeps doing it then it should at least blame the mod thats causing it (if it wasnt me)

**Comment by OwenNicholson** [comment]
Thanks, that seems to have fixed it.
