### ISSUE TITLE
Ark inventory blocks open en closing UI options

### ISSUE THREAD

**Issue by Jonnn3** [arkayenro/arkinventory#1636]
What version number you are using?
3.10.02

What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta
Retail Live

What language is the game client set to?
English

Describe the bug
When i have Ark inventory active, (no other addons Active) i can not open the vendor and transmog. 
Also when i have a UI open like the Map,, Toys enz. i cant close it down with Escape. 
It displays message": ''Interface action nfailed because of an AddOn''

I cant find an option in Config to turn this off so i hope this can be resolved. I get a message, this option is blocked by an Addon.

Screenshots
Cant add pictures of thhis problem

EDIT:
I have removed the saved vairables from Ark Inventory, removed the entire addon, ran it without any othher addons. the problem still maintains active

Please help, i really like ArkInventory

**Comment by arkayenro** [comment]
config > advanced > workaround > playerinteractionframemanager

untick enabled

youll get the default bank and guild bank frames but it should not be able to taint any more. if if keeps doing it then it should at least blame the mod thats causing it (if it wasnt me)
