### ISSUE TITLE
[BUG] Unable to deposit Anima

### ISSUE THREAD

**Issue by allcoast** [arkayenro/arkinventory#1638]
**What version number you are using?**
Latest

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
en

**Describe the bug**
When opening the sanctum window and attempting to deposit anima, an error is generated "ArkInventory has been clocked from an action only available to the Blizzard UI

**To Reproduce**
Attempt to deposit anima into the sanctum

**Screenshots**

**Additional context**

**Comment by arkayenro** [comment]
i think its a side effect of the new method of overriding the bag, bank, and guild bank frames.

not much i can do about it at the moment though.

if you do a /reload and then immediately deposit it should work.

**Comment by rherzfeld** [comment]
It does not for me. I have to disable ArkInventory to deposit.

**Comment by ByucknahTheRed** [comment]
Yeah, gotta agree with Rherzfeld here, that does not work. I have to entirely turn off Arkinventory, reload, deposit, then turn it back on and reload again.

It's not the worst bug in the world but it certainly is annoying XD Thankfully I am not turning in Anima multiple times a day or something and thankfully we wont have to worry about Anima for too much longer.

**Comment by Mythris29** [comment]
Same issue here.

3x [ADDON_ACTION_FORBIDDEN] AddOn 'ArkInventory' tried to call the protected function 'DepositAnima()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `DepositAnima'
[string "@Blizzard_CovenantSanctum\Blizzard_CovenantSanctumUpgrades.lua"]:327: in function `DepositAnima'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

**Comment by arkayenro** [comment]
config > advanced > workaround > playerinteractionframemanager

untick enabled

youll get the default bank and guild bank frames but it should not be able to taint any more. if if keeps doing it then it should at least blame the mod thats causing it (if it wasnt me)

**Comment by arkayenro** [comment]
should be fixed in alpha 9
