### ISSUE TITLE
Turn off item and currency indexing?

### ISSUE THREAD

**Issue by elderswordsman** [arkayenro/arkinventory#1639]
**What version number you are using?**
3.10.02
Character rules: 1.0.9
df Arkinventory rules 0.14.0

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Ask your question**

Hi there - TL;DR: can I turn off Arkinventory's feature that catalogs every new item and piece of currency in my inventory? 
 in a nutshell since the DF pre-patch my WoW performance has been pretty bad. I'm trying to isolate addons, etc., and one symptom is when I go to loot stuff, the game freezes. My theory is since I have 2 addons that track which toons and guild banks have which items, the idea that both addons are seeking and updating based on the same inventory changes might be a problem.

The other addon that catalogues everything for me is TradeskillMaster. I do run Elvui but I disabled its bag functionality, and I don't think it deals with counting and cataloging inventory.

Even if it's not the addons colliding and causing these freezes, I think a reasonable theory is I don't need 2 addons doing the same thing, since it can only hurt overall performance.  the item indexing seems a bit more crucial to how TradeSkillmaster works than Arkinventory, at least for my needs.

Is it possible to turn off the cataloging/indexing and just use Arkinventory to organize my bag and bank views?

Thanks!

**Comment by elderswordsman** [comment]
I disabled Arkinventory but kept these other addons running:
bigwigs, Caerdon Wardrobe, Details!, Mount Journal Enhanced, O Item Level, SilverDragon, Venture Plan, WIM, World Quest Tracker, TradeskillMaster, Elvui. Doing this boosted my FPS 2-3X.

**Comment by Flowy** [comment]
after last update, I'm getting extreme lags after anything moves in my bags, like if cache was rebuild every time
wrath classic

**Comment by Mandrakekardnam** [comment]
Duplicate? 
https://github.com/arkayenro/arkinventory/issues/1624

**Comment by arkayenro** [comment]
yes, you can disable the item counts in the config if you have another mod that does them (it wont hurt but theres no point having two mods do the same thing)

3.10.03 should also remove the lag issues.

**Comment by elderswordsman** [comment]
Thanks! I couldn’t find the option when I looked, could you let me know how to find it?

**Comment by arkayenro** [comment]
config > general > tooltips > item counts > enabled
