### ISSUE TITLE
[BUG] `pawnupgrade()` conflicts with tradeable soulbound items

### ISSUE THREAD

**Issue by TylerR909** [arkayenro/arkinventory#1640]
**What version number you are using?**
v31002

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
WotLK Classic

**What language is the game client set to?**
enUS

**Describe the bug**
When you get soulbound loot in a dungeon/raid that you're allowed to trade for 2 hours, `pawnupgrade()` detects that it's an upgrade but refuses to move it to the appropriate bar. 

**To Reproduce**
Get a soulbound upgrade while in a group, such that you can trade it with them for 2 hrs. 

If I try to equip this, accept the "This will be bound to you!" prompt, then swap it back out with the downgrade, now it appears in the correct bar.

**Screenshots**
Before equipping:
![image](https://user-images.githubusercontent.com/20718430/198504409-1c003b61-acc9-4dea-88c7-cae57fa0a43e.png)

After equipping:
![image](https://user-images.githubusercontent.com/20718430/198504570-e52981ab-7774-4aca-910c-6257cc019ec8.png)

**Comment by arkayenro** [comment]
theres an internal automatic category for those type of tradeable items.  if you have that enabled it will override all your rules for that type of item.

config > settings > items > override > party loot

**Comment by TylerR909** [comment]
yep that solved it

**Comment by TylerR909** [comment]
Might be cool to pull `partyloot()` into its own rule so I can make a `partyloot() and not pawnupgrade()` lower order than `pawnupgrade()`

**Comment by TylerR909** [comment]
Eh, this works too: `tt("You may trade this item with players") and not pawnupgrade()`
