### ISSUE TITLE
Custom category import/export

### ISSUE THREAD

**Issue by ghost** [arkayenro/arkinventory#1641]
**What version number you are using?**
v31002

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
German

**Ask your question**

Hey,
is there a way to export/import custom categories? It would be awesome after adding all those items to a category and share them with friends.... and also safe them for the next UI wipe

Thanks

**Comment by arkayenro** [comment]
there is an import/export profile option but i cant remember if it includes the custom categories but i would presume it would.

if its only for yourself then you should probably just backup your WTF folder as that contains the configs for all your installed mods.
