### ISSUE TITLE
[BUG] Script ran too long

### ISSUE THREAD

**Issue by jsaue003** [arkayenro/arkinventory#1642]
**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail 10.0

**What language is the game client set to?**
English

**Describe the bug**

LUA error on login. 

Message: Interface/AddOns/ArkInventory/Core/ArkInventory.lua:12074: script ran too long
Time: Fri Oct 28 15:19:16 2022
Count: 1
Stack: Interface/AddOns/ArkInventory/Core/ArkInventory.lua:12074: script ran too long
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:12074: in function `ThreadResume'
[string "*ArkInventory.xml:2346_OnUpdate"]:4: in function <[string "*ArkInventory.xml:2346_OnUpdate"]:1>

Locals: threads = <table> {
 p04-scan-1-6 = <table> {
 }
 p04-scan-1-4 = <table> {
 }
 p03-scan-toybox = <table> {
 }
 p04-scan-1-1 = <table> {
 }
 p04-scan-6-1 = <table> {
 }
 p04-scan-1-5 = <table> {
 }
 p03-scan-pet = <table> {
 }
 p04-scan-1-2 = <table> {
 }
 p04-scan-1-3 = <table> {
 }
}
tz = 890027547.652000
(for generator) = <function> defined @Interface/AddOns/ArkInventory/Core/ArkInventoryConst.lua:227
(for state) = <table> {
 1 = "p03-scan-pet"
 2 = "p03-scan-toybox"
 3 = "p04-scan-1-1"
 4 = "p04-scan-1-2"
 5 = "p04-scan-1-3"
 6 = "p04-scan-1-4"
 7 = "p04-scan-1-5"
 8 = "p04-scan-1-6"
 9 = "p04-scan-6-1"
 idx = 1
 tbl = <table> {
 }
}
(for control) = "p03-scan-pet"
thread_id = "p03-scan-pet"
data = <table> {
 duration = 93.586400
 resumed = 890027547.652000
 thread = <no value>
}
ok = false
errmsg = "...face/AddOns/ArkInventory/Core/ArkInventoryObject.lua:776: script ran too long"
(*temporary) = false
(*temporary) = "...face/AddOns/ArkInventory/Core/ArkInventoryObject.lua:776: script ran too long"
(*temporary) = false
(*temporary) = false
(*temporary) = "p04-scan-1-5"
(*temporary) = "p04-scan-1-4"
(*temporary) = false
(*temporary) = "script ran too long"
type = <function> defined =[C]:-1
error = <function> defined =[C]:-1
string = <table> {
 split = <function> defined =[C]:-1
 match = <function> defined =[C]:-1
 gmatch = <function> defined =[C]:-1
 upper = <function> defined =[C]:-1
 gsub = <function> defined =[C]:-1
 format = <function> defined =[C]:-1
 lower = <function> defined =[C]:-1
 sub = <function> defined =[C]:-1
 gfind = <function> defined =[C]:-1
 rep = <function> defined =[C]:-1
 char = <function> defined =[C]:-1
 rtgsub = <function> defined @Interface/FrameXML/RestrictedInfrastructure.lua:618
 join = <function> defined =[C]:-1
 reverse = <function> defined =[C]:-1
 byte = <function> defined =[C]:-1
 trim = <function> defined =[C]:-1
 len = <function> defined =[C]:-1
 find = <function> defined =[C]:-1
}

**To Reproduce**
Steps to reproduce the behaviour, if possible:

**Screenshots**

WoW is randomly crashing every time I login. Also get this LUA error for ARK

![image](https://user-images.githubusercontent.com/32148757/198715856-91914b0a-efc1-4d25-8aa9-80e0cf049e1d.png)

**Comment by arkayenro** [comment]
try 3.10.03
