### ISSUE TITLE
Blue border in bank

### ISSUE THREAD

**Issue by fgsfdss** [arkayenro/arkinventory#1644]
**What version number you are using?**
31002 WotLK

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
WotLK Classic

**What language is the game client set to?**
English

**Ask your question**
In a new update, the first bag in my bank has started to appear as blue with the 'Rgt' tag. What does this mean?
Might be a bug, but I'm not sure if it's an intended feature that I simply don't understand.

![image](https://user-images.githubusercontent.com/5033279/198776760-9a9b3891-bee0-49cc-85e0-340f57464fa1.png)

Pardon me if I did not follow the proper report template. Please ask me for additional information if required.

**Comment by arkayenro** [comment]
its a bug, the reagent bag code from dragonflight caused the wrath/classic banks to thinks the first bag is a reagent bag.

its fixed in 3.10.02 alpha 2

**Comment by arkayenro** [comment]
fixed in release 3.10.03
