### ISSUE TITLE
[BUG] Looting kills FPS on latest in Classic

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1645]
In Classic, on latest.

Having a bug where when I loot anything or grab anything thing from the bank, my FPS just drops to under 10 for 2-3 seconds.

I downgraded to a previous version and it's fine, but the latest is not working for me.

**Comment by Gogo1951** [comment]
May be a conflict with Gargul? Doesn't seem to happen as much when I turn off "auto-greed" -- but the bank line-by-line refresh still happens even with Gargul disabled.

**Comment by Gogo1951** [comment]
So you loot, or win a roll, then 2-3 seconds later it just freezes up for 2-3 seconds. Every time I loot anything. Really clunky. Oof. Logging turned on with this release? Maybe there's some excessive recording. Kinda what it feels like. Or re-caching all the items to make search work?

**Comment by severd8** [comment]
I'm having the same issue. I'm not using Gargul.

If I loot only silver/gold, I get no FPS drops. If it is an item that goes into inventory, my FPS drops to like 8 for 4-5 seconds. I've disabled ALL addons except ArkInventory and I have the same issue. Logs available if you need. Let me know.

**Comment by severd8** [comment]
Same issue here. Only happens when I loot items; doesn't happen when I look only money.

**Comment by arkayenro** [comment]
try 3.10.02 alpha 2

**Comment by Shinae17** [comment]
It's seem good with the 3.10.02 alpha 2

**Comment by Gogo1951** [comment]
Agreed, seems fixed. Thanks!
