### ISSUE TITLE
[BUG] WOTLK - Latest Alpha won't load on Wrath at all. 

### ISSUE THREAD

**Issue by Jorvanus** [arkayenro/arkinventory#1648]
Installed latest alpha 3.10.03 1, which produces the following errors and it completely doens't load. 

![image](https://user-images.githubusercontent.com/89010934/198872409-4b7b7abf-2e5b-4ba2-a7fa-519a7ac528ce.png)

I know it's the alpha, but don't know of any other way to make contact without an issue post.

**Comment by arkayenro** [comment]
fixed in alpha 2
