### ISSUE TITLE
[BUG] ArkInventory blocks TSM BankUI

### ISSUE THREAD

**Issue by KoronGIT** [arkayenro/arkinventory#1649]
**What version number you are using?**
1.00.95

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
German

**Describe the bug**
When ArkInventory is activated, the TSM BankUI no longer opens.

**To Reproduce**
1. Have ArkInventory and TSM Addon active
2. Open bank

**Additional context**
The TSM Bankui cannot be opened with the console command /tsm bankui either. The BankUI is completely blocked by ArkInventory.

**Comment by KoronGIT** [comment]
Fixed in last ArkInventory Update

**Comment by arkayenro** [comment]
im not sure how i fixed it (unless you mean to new workaround for taint) but you do realise that having two mods try to replace the same frame is not a good idea.
