### ISSUE TITLE
Junk Icon on Greys and Items marked with Scrap is not showing.

### ISSUE THREAD

**Issue by Perkele441** [arkayenro/arkinventory#1650]
Arkinventory-1.00.95 on Retail, Client is set to English

Since Pre Patch, the Junk Coin from Scrap on Items i marked as Junk isn't showing anymore, it's also not showing on grey items either.

**Comment by arkayenro** [comment]
should be fixed in 3.10.04 alpha 1

**Comment by Perkele441** [comment]
Yes, it is fixed now, thank you!
