### ISSUE TITLE
[BUG] WARNING> The Category Set [1000] being used by the Keyring location no longer exists

### ISSUE THREAD

**Issue by 0xjc** [arkayenro/arkinventory#1651]
**What version number you are using?**
3.10.4 Alpha 9

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
On logging in I get these messages:
```
ArkInventory: WARNING> The Category Set [1000] being used by the Keyring location no longer exists.  Please check Config > General > Profiles > Controls > Blueprint
ArkInventory: WARNING> The Category Set [1000] being used by the Mount location no longer exists.  Please check Config > General > Profiles > Controls > Blueprint
ArkInventory: WARNING> The Category Set [1000] being used by the Professions location no longer exists.  Please check Config > General > Profiles > Controls > Blueprint
```

When I go to the specified config section, the Keyring location does not exist, the Mount location is already set to Category Set [1001] Default, and the Professions location does not have a Category Set option.

I don't think I actually use these locations so there is nothing actually broken. Just these warning messages I get on every login.

**Comment by arkayenro** [comment]
the warning should stop next release and i've updated the dropdowns so that if the option has been deleted it will be in red, which will also allow you to change it to one that isnt deleted more easily.

**Comment by Cudyhouse** [comment]
I have the same issue with "Métiers" (french location of the addon)

ArkInventory: WARNING> The Style and Layout [1001] being used by the Métiers location no longer exists.  Please check Config > Général > Profiles > Commandes > Blueprint 
btw there is NO "Blueprint" section on this tab to fix manualy this issue.

**Comment by arkayenro** [comment]
there is a blueprint tab, its next to the general tab, but keyring wont be in the controls list though

install 3.10.04 alpha 10 to stop it complaining about the keyring
