### ISSUE TITLE
How can I assign specific custom category set on different profiles

### ISSUE THREAD

**Issue by JohnnySebre** [arkayenro/arkinventory#1652]
**What version number you are using?**
3.10.04
**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail
**What language is the game client set to?**
English

**Ask your question**
I have different profiles and for some of them I want to have different category sets to be enabled/disabled. I've created one profile per character and some category sets that are to be used on individual characters, but I cannot find where to assign those category sets within specific profiles. I did it not long ago and there was a drop-down list I could link a category set to a profile, but I cannot find it currently.

**Comment by arkayenro** [comment]
open the config and on that page in the profiles section theres a controls tab, its in there

**Comment by JohnnySebre** [comment]
Awesome this is what I was looking for, thank you!
