### ISSUE TITLE
Assigning an action

### ISSUE THREAD

**Issue by tflo** [arkayenro/arkinventory#1653]
From the release notes of 31004 alpha 11 Retail:

> added - one action can be assigned to each category/rule in a categoryset. actions can be set to disabled, automatic, or manual

Probably I'm just horribly blind, but how (where in the UI) exactly can I assign an action?

**Comment by arkayenro** [comment]
in edit mode, click on a bar, go down to the assignable/assigned categories section and mouser over a category and there should be an "action type" and "action when" entries, click on those to cycle through the options.

**Comment by tflo** [comment]
Indeed, I was blind. Thank you very much!
