### ISSUE TITLE
[Feature Request] Flying (Dragonriding) Selection in Mount LDB

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1654]
**Is your feature request related to a problem? Please describe.**
Once you've learned how to ride a dragon in the Dragon Isles, you're able to use the Dragonriding mounts for flight.  I can set my flying mount for one of these mounts using the Mount LDB and everything is fine while I'm in the Dragon Isles.  If I go to Stormwind and try to activate this selected mount it fails because I'm in the wrong zone. 

**Describe the solution you'd like**
Ideally, there would be a separate selection for Dragonriding that would be used for flying in the Dragon Isles and everywhere else it would be the Flying selection.  Maybe have an option to 'just use flying selection' in the Dragon Isles so if/when flying becomes enabled there, the user could just use the Flying selection rather than the Dragonriding selection.

**Describe alternatives you've considered**
I can select two (2) different flying mounts for it to randomly select, but it's random so depending on the zone I have a 50%/50% chance of getting the correct mount.

**Additional context**
Thanks for the consideration!

**Comment by arkayenro** [comment]
yeah, im going to have to add in some code to check which zones a mount can be used in and skip those if youre not in one of those zones.

**Comment by arkayenro** [comment]
next alpha will have zone restrictions for the four dragonriding mounts, and some other old ones (seahorse and aq)

when on the island it will prioritise the dragoriding ones, when off the island it wont ever call them

**Comment by Calesta** [comment]
I tried 3.10.04 Alpha 13.  I selected a regular flying mount and a Dragonriding mount in the 'Flying' list.  In Valdrakken, I tried mounting over and over using the keybind shortcut and it only ever selected the regular flying mount.  I tried the same experiment outside the city, "out in the field", so to speak, just in case the city isn't recognized in your zone code and had the same results.

Looking forward to seeing this feature request in action!  Thanks for spending some time on it!

**Comment by arkayenro** [comment]
if youre on the dragonisles and it wont call a dragonriding mount can you run this

`/dump C_Map.GetBestMapForUnit( "player" )`

and let me know what the number it outputs is and i can add it to the restrictions for those mounts

**Comment by Calesta** [comment]
In Valdrakken,

[1]=2112

Just outside Valdrakken,

[1]=2025

If you need more values, then please let me know.

**Comment by arkayenro** [comment]
added to 3.10.06

**Comment by Calesta** [comment]
Couldn't use my dragonriding mount in Ohn'ahran Plains.

/dump C_Map.GetBestMapForUnit( "player" )
[1]=2023

**Comment by arkayenro** [comment]
will be in the next release

**Comment by Calesta** [comment]
Thanks Arkayenro!

**Comment by arkayenro** [comment]
if you dont have the use all option enabled then make sure that the dragonriding mounts you want to use are selected in the flying menu.

theyre zone restricted so wont get called outside of the dragon isles

**Comment by Calesta** [comment]
I'm still seeing selection errors in the Azure Span (Zone) and in The Nokhud Offensive (Dungeon) with the latest release version (3.10.10).  Just FYI for continued troubleshooting.

**Comment by Arkios64** [comment]
Still not getting a Dragonflying mount inside The Nokhud Offensive, map id 2093.

**Comment by arkayenro** [comment]
map id will be added into the next release
