### ISSUE TITLE
Can not remove item from Custom Category[BUG] 

### ISSUE THREAD

**Issue by fisken1991** [arkayenro/arkinventory#1655]
**What version number you are using?**
ArkInventory-3.10.04.zip

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Live

**What language is the game client set to?**
English

**Describe the bug**
Adding an item to a Custom Category. Then I'm unable to remove it

**To Reproduce**
Create new Custom Category, add an item. Then try to remove the item from that category

**Screenshots**
https://i.gyazo.com/4ecd7535cae12fa4a8b8e559b2329c0c.png

**Additional context**

**Comment by arkayenro** [comment]
click on the default line underneath to reset (clear) it back to its default
