### ISSUE TITLE
[BUG] WOTLK No longer showing CD text on Items

### ISSUE THREAD

**Issue by Jorvanus** [arkayenro/arkinventory#1656]
3.10.04 Alpha 13 (Although it happened on whatever version I was on before updating to this one.)

WOTLK - English

There used to be cooldown text on items in bags, this isn't working despite the setting being enabled. 
![image](https://user-images.githubusercontent.com/89010934/201444894-d69a3319-29fe-4be4-a11d-ef72a5e6704c.png)

![image](https://user-images.githubusercontent.com/89010934/201444916-90c6d558-8cd1-4894-880b-ecb794adc0db.png)

I don't have any other addons enabled. Am I just doing something wrong?

**Comment by arkayenro** [comment]
its not just wrath.  i've broken something somewhere, just have to find it.

**Comment by arkayenro** [comment]
blizzard appears to have changed the `BAG_UPDATE_COOLDOWN` event and it no longer provides the bag id that the item that triggered it was in.

will be fixed in the next release

**Comment by Jorvanus** [comment]
> 

Hey, just grabbed latest alpha, and this still isn't working in WOTLK. 

![image](https://user-images.githubusercontent.com/89010934/201494195-ef54fe6a-9672-4832-aacc-243921f3af70.png)

**Comment by arkayenro** [comment]
weird, it wasnt displaying the number on on mine, and i changed the code and it displayed. so it appeared to be fixed.

its still displaying, so im not sure why yours isnt.  can you move the item to a different slot/bag?  disable all your other mods to test.

**Comment by Jorvanus** [comment]
Nah, made no difference.  No addons and sappers in two different bags. 

![image](https://user-images.githubusercontent.com/89010934/201501109-e7b4fa1b-8a44-419f-ba29-f6c31db72d6d.png)

**Comment by arkayenro** [comment]
you do have show numbers for cooldowns enabled in the blizzard interface (under ActionBars)?  i dont control the numbers, only showing/hiding the cooldown itself - which i can see is there.

it does look like there is an issue with the first couple of item slots anyway due to creating them on load (before entering the world - so never in combat).

for me the first 6 slots dont have cooldown numbers, but all the others are ok.  if i dont create them on load the numbers all work fine.

**Comment by Jorvanus** [comment]
> you do have show numbers for cooldowns enabled in the blizzard interface (under ActionBars)? i dont control the numbers, only showing/hiding the cooldown itself - which i can see is there.
> 
> it does look like there is an issue with the first couple of item slots anyway due to creating them on load (before entering the world - so never in combat).
> 
> for me the first 6 slots dont have cooldown numbers, but all the others are ok. if i dont create them on load the numbers all work fine.

Probably should have started with "have you got blizzard setting enabled" haha cause I didn't.  

It was working historically without.  Thanks though

**Comment by arkayenro** [comment]
np, there is still a weird bug in there that ill have to sort out at some point as some slots are not showing the number even when its enabled.

**Comment by arkayenro** [comment]
theres a workaround in alpha 16 that should fix it as im not seeing it any more.
