### ISSUE TITLE
[BUG] LDBs ArkInvetory addons overlap isssue with bazooka

### ISSUE THREAD

**Issue by Thaldan** [arkayenro/arkinventory#1657]
**What version number you are using?**
3.10.04 "Realease" and 3.10.04 alpha15

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
French

**Describe the bug**

Hello, since the pre-patch, I migrated to bazooka (chocolate bar before) and the LDB arkinventory addons, overlaps between them and with the other LDB addons. (The highlights size doesn't fit the text size too, as you can see in the screen below)

**To Reproduce**
Just log in with LDB arkiventory in bazooka

**Screenshots**
![ArkLDB in bazooka](https://user-images.githubusercontent.com/32823726/201488983-3bae8d20-4aa4-40a6-86d6-e8b03f56ad93.jpg)

**Additional context**

**Comment by arkayenro** [comment]
that would be a bazooka issue.

i have no control over the position or size of the text on those bars, i just set the underlying information and the LDB mod is supposed to display it.

**Comment by Thaldan** [comment]
I supose that was from you because all other LDB addon (BrokerEverything, AraBrokerRéputation, and all ldb mod from other addon like prat,kgpanels,....) not have this issue. So I'll post this issue on there side too

Thx for the quick answer.
