### ISSUE TITLE
[BUG] Selling Junk Fails with LUA Error and Continues to Run

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1661]
**What version number you are using?**
ArkInventory v31104 (3.10.04)

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Before the recent update, when I visit a vendor and interact with it, my junk items up to the buyback limit are typically sold because of my settings.  [ General | Junk : 'Auto Sell' Checked,  'Limit to Buyback' Checked ]

Now when I visit a vendor, one junk item gets sold and then there's a LUA error in chat. 

![SellJunkError](https://user-images.githubusercontent.com/13042214/202049948-eb5ac745-10d5-49bd-b8a1-9117ccd546c8.PNG)

If I try to open the vendor again, then there's a warning stating that Sell Junk Items is already running, please wait.
 
![StillRunning](https://user-images.githubusercontent.com/13042214/202050109-5e396298-bfa1-4abc-a386-8aa417fe3f00.PNG)

**To Reproduce**
Ensure that 'Auto Sell' in checked in General | Junk.

Have junk to sell.

Open a vendor. 

**Screenshots**
See embedded above.

**Additional context**

**Comment by arkayenro** [comment]
try 3.10.05

**Comment by Calesta** [comment]
I installed 3.10.05 Alpha 1.  Issue seems to have been resolved.  Thanks!
