### ISSUE TITLE
[bug]Unable to open up guild bank.

### ISSUE THREAD

**Issue by strunberg** [arkayenro/arkinventory#1662]
I get this error.  The guild bank is blank but everything else is fine.

![nbvnbbn](https://user-images.githubusercontent.com/6355904/202063943-4fb7aad6-1294-4a9a-8083-72c93237134b.png)

**Comment by arkayenro** [comment]
yeah, battlepets have shifted again, but notin the vault so its messy

**Comment by arkayenro** [comment]
try 3.10.05

**Comment by arkayenro** [comment]
try 3.10.05 alpha 1

**Comment by strunberg** [comment]
3.10.05 seem to have fixed the issue.
