### ISSUE TITLE
[BUG] Battle Pet Tooltip On Startup / Refreshes Every Few Seconds

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1663]
**What version number you are using?**
ArkInventory v31104 (3.10.04)

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
I use a common profile for all my characters.  I have 3 characters out of 17 on a single realm where having ArkInventory active causes a tooltip to show up even when I'm not hovering over anything that displays battle pet information.  This tooltip then refreshes every few seconds.  Upon login, it's just chilling out on my action bars refreshing over and over.

![Rnadom Tooltip O O 2](https://user-images.githubusercontent.com/13042214/202065212-03d49195-2ed2-45b9-8b8a-41742042c879.jpg)

I'm using ElvUI with the tooltip anchored to my cursor so when I move the mouse, the tooltip follows along.  If I hover over something that I expect to see a tooltip (e.g., a player), I see the real tooltip for a second and then this crazy battle pet tooltip comes back.

![Random Tooltip Over and Over](https://user-images.githubusercontent.com/13042214/202064523-b4551dbb-56d0-4b7e-aca8-830fbd01990f.jpg)

**To Reproduce**
It's not consistent across my characters so I don't know how to reproduce it.  I did isolate the issue to ArkInventory (or its interaction with ElvUI perhaps) by disabling all my addons and adding things one at a time.  

Another oddity is that the battle pet data tooltip that's displayed seems to stay the same per character on each login but it's not the same battle pet data for different characters.  For example, the Putrid Geist tooltip in the screenshots above were on my Horde warrior, but on another character it was for a different battle pet.

I can't see anything character-specific in the settings that would cause a few characters sharing a common profile have this issue while  the majority don't.

**Screenshots**
See embedded above.

**Additional context**

**Comment by arkayenro** [comment]
try 3.10.05

**Comment by arkayenro** [comment]
actually, try 3.10.05 alpha 1

**Comment by Calesta** [comment]
I installed 3.10.05 Alpha 1.  Issue seems to have been resolved.  Thanks!
