### ISSUE TITLE
[BUG] High UI lag / memory use / glitching on 10.0.2

### ISSUE THREAD

**Issue by Silarn** [arkayenro/arkinventory#1664]
**What version number you are using?**
3.10.05

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
10.0.2

**What language is the game client set to?**
en_US

**Describe the bug**
Significant lag and memory use while ArkInventory frame (bag) is open. Dragging frame sometimes moves erratically. Occasionally causes entire GUI to disappear when moving mouse around and updating the tooltip frequently.

**To Reproduce**
Open up Ark. I tried to remove as many extra AddOns as I could to rule out issues. I still have Pawn and Outfitter active which might be contributing. I also still have a number of rules and filters set up.

**Comment by Silarn** [comment]
I'm fairly sure tooltips in general are contributing to this issue.

**Comment by arkayenro** [comment]
try alpha 1 - and also try turning off cooldowns in the config.

**Comment by Silarn** [comment]
I'll give it a try as soon as I can.

**Comment by Silarn** [comment]
On a different machine with minimal filters / rules configured, it seems to be working well. I can try it on the other machine later tonight.
