### ISSUE TITLE
How can I add more bars to the left of each other?

### ISSUE THREAD

**Issue by strunberg** [arkayenro/arkinventory#1665]
I was wondering how one could increase the number of bars beyond 5 to the left of each other.
![kldfkldsfk](https://user-images.githubusercontent.com/6355904/202260598-94bfd7b1-d361-4b09-92c6-2bfd1b06e249.png)

**Comment by arkayenro** [comment]
in the config change the bars per row, and you may want to increase the window width as well.

**Comment by strunberg** [comment]
For some reason when I try to change the height of the window it doesn't adjust it.
