### ISSUE TITLE
Sort by CustomUserCategory

### ISSUE THREAD

**Issue by kovjogin** [arkayenro/arkinventory#1668]
Hello. Thanks a lot for the addon.

My request is this: add each custom category a sorting priority.

I assign several categories to one block. I want the items to follow each other. But the group united them.

Here are my categories:
1) Garrison Return Stone and Dalaran Return Stone
2) Items to move: Ring of Kirin Tor Mages, Jaina's Medallion, etc.
3) Speed ​​toys

I want these items to be sorted, but the categories go one by one within the same block.

I created these categories and assigned them all to one block. And no matter what category the items belong to, they are sorted together. And I would like each group to be sorted separately. And you could prioritize it. And how they will be sorted within the category - it does not matter to me.

**Comment by arkayenro** [comment]
category is already an option in the sort method.

did you assign that sort method to the window (as the default) or specifically to that bar?

**Comment by kovjogin** [comment]
Either we don't understand each other, or I need help. I already read the WIKI and the FAQ.

**I want:** 
State without click "sort button": https://ibb.co/h2GH7TJ

**I have:**
Click on "sort button" https://ibb.co/BNthkkH

I have 3 custom categories (small, for example):
- Teleport.Stone (item:110560:1, item:140192:1)
- Teleport.Item (item:103678:1, item:63206:1)
-  Teleport.Other (item:109076:0)

I set all 3 categories for the first bar. (https://ibb.co/VYdWL71)
Sorting Method for this bar: Default (https://ibb.co/tKMpvvm)

**Comment by arkayenro** [comment]
the name (ascending) sort method does not include the category, only the item name, you need to make a custom sort method

config > settings > sort methods
add a new sort method
click on the new sort method
tick item category
tick item name

enable edit mode
click on the bar and set the sort method to the one you just created

that bar will now use that sort method

you can enable any other options you want in there, and move them around, to get it to sort the way you want

**Comment by kovjogin** [comment]
Yes, I think I'm starting to understand.

Category ID looks like: 2!1009

It turns out that to change the order, I need to re-create the category? Can I somehow change 1009 to another number? Or prioritize?

**Comment by arkayenro** [comment]
yes, the category id is essentially the order the category was created in.  youd have to recreate them in the correct order if you want them in a different order.

**Comment by kovjogin** [comment]
This is not convenient if I will have 10 or more categories. This will turn into hell.

The rules have a "sort priority" can you please add the same item to the "user categories" as well? Well, or add the ability to sort not by category ID, but by name?

Then I can create a category: "102.My category". And flexibly manage sorting

**Comment by arkayenro** [comment]
including the category name will be in the next release

**Comment by kovjogin** [comment]
thanks a lot

**Comment by arkayenro** [comment]
added to 3.10.06
