### ISSUE TITLE
Taint question (not related to ArkInventory)

### ISSUE THREAD

**Issue by tflo** [arkayenro/arkinventory#1670]
11 days ago you said on the [WoW US forum](https://us.forums.blizzard.com/en/wow/t/bindingsxml-taint-and-other-issues/1394681)

> using any category other than ADDONS for your keybinding will cause taint

Do you have any idea if this is still true for the current 10.0.2 release build?

I'm asking because I see more and more addons moving to their own category in keybindings, and I'm wondering if I should do the same for my addon, or better wait for them to fix the broken header display (if ever?).

Sorry for posting this here, but I do not have access to the US forums.

– Tom

**Comment by arkayenro** [comment]
yes, its still there but i just posted an update.

so long as you use plain text that will not resolve to anything then it will work without tainting.

**Comment by tflo** [comment]
Thank you for the info!

**Comment by tflo** [comment]
Your method worked perfectly for me, thanks again.

Upon further testing, I was shocked to find that literally all of my loaded addons that have their own category produce taint.

**Comment by arkayenro** [comment]
the standard was to use `BINDING_HEADER_XXXX` where `XXXX` was the category value.

it used to work fine, but now because thats inside a mod, even if its set to plain text, it causes taint.
