### ISSUE TITLE
[BUG] GetContainerItemID (a nil value) at line 1189 of ArkInventoryRules.lua

### ISSUE THREAD

**Issue by nathan43082** [arkayenro/arkinventory#1672]
**What version number you are using?**
31003.05

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Live Retail

**What language is the game client set to?**
US English

**Describe the bug**
I was receiving the error "attempt to call global 'GetContainerItemID' (a nil value)" at line 1189 of ArkInventoryRules.lua. This error was being thrown in response to Rules I had defined that used the outfit() keyword with any text inside the parens. It was working fine last week.

**To Reproduce**
Persistent issue. Happens every time I enable any of the Rules containing outfit().

**Screenshots**
![ark](https://user-images.githubusercontent.com/49687789/202613638-9fc3dffb-e4de-4299-80cb-cb705093284f.jpg)

**Additional context**
I was actually able to fix the problem by prepending GetContainerItemID with C_Container, as in C_Container.GetContainerItemID(). Perhaps Blizz moved some things around in their API without telling anyone?

I applied this same fix to line 237 of ArkInventoryJunk.lua and the automatic selling of grey items worked just fine instead of being hung up as some have pointed out.

**Comment by arkayenro** [comment]
you'll probably want to upgrade to the latest version.
