### ISSUE TITLE
ArkInventory: ERROR> code failure: TOC Interface value appears to be a point release but X-ReleaseType is not set  ArkInventory: Loading Connected Realm (EU) Data [BUG] 

### ISSUE THREAD

**Issue by eentje** [arkayenro/arkinventory#1676]
**What version number you are using?**
v310007.1

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
retail

**What language is the game client set to?**
english

**Describe the bug**
i get this message when i login
ArkInventory: ERROR> code failure: TOC Interface value appears to be a point release but X-ReleaseType is not set 
ArkInventory: Loading Connected Realm (EU) Data

**Comment by arkayenro** [comment]
that error is meant to be for me to make sure i setup the toc version properly, you can ignore it as it doesnt actually hurt anything.

itll get fixed when the next version comes out

**Comment by arkayenro** [comment]
fixed in 3.10.09
