### ISSUE TITLE
[BUG] Lua Error on Login (Wrath)

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1679]
1x ArkInventory\Core\ArkInventory-31007.02.lua:3147: attempt to index global 'ContainerFrameCombinedBags' (a nil value)
[string "@ArkInventory\Core\ArkInventory-31007.02.lua"]:3147: in function <ArkInventory\Core\ArkInventory.lua:3017>
[string "=[C]"]: ?
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:66: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:61>
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:626: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:611>

**Comment by arkayenro** [comment]
try 3.10.07 alpha 3
