### ISSUE TITLE
[BUG] Changing equipment cause stuttering when AI enabled.

### ISSUE THREAD

**Issue by zzipsa22** [arkayenro/arkinventory#1682]
**What version number you are using?**
3.10.07-ALPHA-4

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
koKr

**Describe the bug**

First of all, Thank you for this great addon. I can't play wow w/o arkinventory. 

but recently it has serious performance issues.
It seems some stuttering occurs when I equip items or loot something. 

As these actions(equip or loot something) accumulate, the symptoms get worse until I reload UI or reconnect.

**To Reproduce**
Steps to reproduce the behaviour, if possible:
I've tested it by continuously wearing the two cloaks alternately. (you can easily reproduce this too)

**Screenshots**

**Additional context**

**Comment by arkayenro** [comment]
please try 3.10.07 alpha 6

**Comment by zzipsa22** [comment]
It seems got Fixed! :D Thank you AKY!
