### ISSUE TITLE
[BUG] Ui disappearing while crafting

### ISSUE THREAD

**Issue by dapal-003** [arkayenro/arkinventory#1683]
**What version number you are using?**
3.10.07 Alpha 3

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Entire UI disappears, unable to bring it back with. Key inputs still work.

**To Reproduce**
Steps to reproduce the behavior, if possible:
When crafting a large amount of items, the UI will disappear during crafting

**Screenshots**

**Additional context**
Add any other context about the issue here.
Due to the entire UI disappearing, I've not seen any error messages. Bugsack doesn't record any errors after doing a /reload.
This happens as well with all other add-ons disabled, having just ark inventory loaded

**Comment by garandacas** [comment]
Confirm the same behavoir

**Comment by chadmccune** [comment]
It's not just crafting, anything that changes a lot of items in your inventory.

The following are ways I've personally experienced it:
- Long periods of farming
- Running multiple old raids and looting/selling everything
- Opening 100 or so lock boxes
- Mailing (sending or receiving) a bunch of BoEs between characters
- Auctioning a large quantity of different items
- Extended periods of play (this is less frequent, but, the more items I loot, the slower the game gets every time I loot something, I end up restarting client to get rid of the 1s hiccup every time I loot something)

**Comment by arkayenro** [comment]
try alpha 4

**Comment by dapal-003** [comment]
Alpha 5 is already out which my mod manager defaulted to. The new version did not fix the issue

**Comment by arkayenro** [comment]
please try 3.10.07 alpha 6

**Comment by dapal-003** [comment]
Crafted well over 3000 items and it didn't crash, thansk for the fix!
