### ISSUE TITLE
[BUG] Disabling "Secondary Sources" for Transmog Status Icons

### ISSUE THREAD

**Issue by Arkios64** [arkayenro/arkinventory#1686]
"Secondary Sources" doesn't actually disable those, but Transmog for other characters; Secondary Sources for the CURRENT character is always active and can't be individually disabled.
I can't actually remember a time this wasn't an issue, going as far back as WoD.

**Comment by arkayenro** [comment]
the clue is in the config.  when you disable secondary sources it doesnt hide them it hides the ones for learning on other characters.

it should be fixed next release

if you dont report it then i wont know about it.  i dont use all the functions

**Comment by arkayenro** [comment]
fixed in 3.10.07 alpha 6
