### ISSUE TITLE
[BUG] Toys

### ISSUE THREAD

**Issue by gz2k2** [arkayenro/arkinventory#1688]
**What version number you are using?**
3.10.7

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
German

**Describe the bug**
1x [ADDON_ACTION_FORBIDDEN] AddOn 'ArkInventory' hat versucht die geschützte Funktion 'UseToy()' aufzurufen.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseToy'
[string "@Blizzard_Collections/Blizzard_ToyBox.lua"]:181: in function `ToySpellButton_OnClick'
[string "*Blizzard_ToyBox.xml:10_OnClick"]:4: in function <[string "*Blizzard_ToyBox.xml:10_OnClick"]:1>

**To Reproduce**
Use Toys, Change Zone, use more Toys. At some point, you can't use any Toys from Toybox. Toys on ActionBars are working.
after ReloadUI it works again

**Screenshots**

**Additional context**

**Comment by arkayenro** [comment]
try 3.10.09 alpha 2
