### ISSUE TITLE
[BUG] Rule wearable() problem with Cloaks

### ISSUE THREAD

**Issue by Horogg** [arkayenro/arkinventory#1689]
**What version number you are using?**
31007.06

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
EN

**Describe the bug**
On items with Equip type "Back" (Cloak) not work rule wearable().
Inside file ArkInventoryRules.lua on row 1503 is wrong name of variable "wearble", correct name is "wearable".

**Comment by arkayenro** [comment]
thanks, will be fixed next release

**Comment by arkayenro** [comment]
fixed in 3.10.09
