### ISSUE TITLE
[BUG] WOTLK Tooltip.lua error on login

### ISSUE THREAD

**Issue by Jorvanus** [arkayenro/arkinventory#1691]
Version 3.10.09

WOTLK

This error comes up in chat on login each time. 

![image](https://user-images.githubusercontent.com/89010934/203717676-34237a61-d86b-4279-a43b-bde801394779.png)

**Comment by arkayenro** [comment]
will be fixed next release

**Comment by joelgriffiths** [comment]
This also causes the junk to stay in my bag, even though it's not there.

**Comment by Jorvanus** [comment]
> will be fixed next release

It's also not updating the size/amount in bag.  When I'm using say a sapper, the amount stays the same.  Refresh doesn't fix it nor does closing or opening.

**Comment by joelgriffiths** [comment]
Restarting the game doesn't fix it either. It's perma-broken.

**Comment by arkayenro** [comment]
you can use 3.10.09 alpha 1 in the mean time

**Comment by joelgriffiths** [comment]
Thank a ton for this. This has been the most important addon for me ever since it was released, and I don't have any idea how I would have lived without it.
