### ISSUE TITLE
[BUG] Menu for auto-sell junk was missing: Failed to load ArkInventoryActions

### ISSUE THREAD

**Issue by ala75** [arkayenro/arkinventory#1692]
**What version number you are using?**
3.10.09 (24-NOV-2022) and alpha 6

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**

Retail

**What language is the game client set to?**

EN

**Describe the bug**

Thanks for the addon using it sinds you made it in 2006. Can't  live without Ark......been using it so long. I can confirm the issues others are describing. I was testing alpha 6 yesterday. While doing that i noticed something broke in the addon . Just noticed the new release 3.10.09 this morning and is has the same bug as alpha 6: The menu for auto-sell junk was missing in the config settings. so when i went the other route of going there by clicking the bag icon, choose "actions" from the menu, it gives this error:

 ArkInventory: ERROR> Failed to load ArkInventoryActions: Missing

 Since it was late is stopped testing there. Tonight we are doing some achievement runs in the raids, will test how the new versions holds in there.

**To Reproduce**

clicking the bag icon, choose "actions" from the menu

result:  ArkInventory: ERROR> Failed to load ArkInventoryActions: Missing

**Screenshots**

**Additional context**

**Comment by arkayenro** [comment]
sorry, though i had hidden all the access points for that.   its not ready, just ignore it

3.10.09 should have the action tabs back in the config

**Comment by Arkios64** [comment]
Didn't even notice that option in that menu before, so thanks.

Yeah, auto-trash and mail are broken, that's why they are disabled from even showing up currently.
