### ISSUE TITLE
ARKINV_ButtonOverrideBag not working

### ISSUE THREAD

**Issue by tflo** [arkayenro/arkinventory#1694]
When AI is disabled it provides a button to the Blizz bag frame (ARKINV_ButtonOverrideBag1, or ARKINV_ButtonOverrideBag2 for non-split bags) that should allow to reenable AI. This button does not work for me. I get the tooltip and highlight when hovering over, but clicks do nothing.

AI 31009.Alpha.1, WoW 10.0.2 (46741)

**Comment by arkayenro** [comment]
no errors?  mines working.  it should close the arkinventory window at a minimum, does it do that?

**Comment by tflo** [comment]
No errors, it just does nothing.

> it should close the arkinventory window at a minimum, does it do that?

Maybe we are speaking of different buttons, I mean this one:

<img width="469" alt="WoWScrnShot_112722_135811" src="https://user-images.githubusercontent.com/1410282/204136734-327a86e3-fe49-4579-af0b-c46d5800923b.png">

**Comment by arkayenro** [comment]
yep thats the one.  do you have errors enabled, or a bug catcher mod installed?

**Comment by tflo** [comment]
Sure, I have always BugSack and BugGrabber loaded. No errors.

Just double-checked it again with really every addon unloaded, except AI and BugGrabber/Sack. Button gets highlighted and shows the tooltip, but does nothing, and no errors.

In a second test I even moved the ContainerFrameCombinedBags away from the MinimapCluster, to rule out any interference with that, but it changes nothing.

In your previous answer, I do not understand what you mean with "it should close the arkinventory window" (that's why I thought we are not speaking of the same button): When this button is on screen, there is no AI window that could be closed, as AI is disabled.

What I expect this button to do is activating[^1] AI again, i.e. running `ArkInventory:Enable()` or a similar function, which also corresponds to what the tooltip is saying.

[^1]: Not that I'm activating/deactivating AI all day long, I just stumbled on this while trying to narrow down the mail retrieval lag issues.

**Comment by arkayenro** [comment]
wait, have you disabled arkinventory, not just the bank/bank override?

**Comment by tflo** [comment]
Yes, with this checkbox:

<img width="305" alt="WoWScrnShot_112922_005210" src="https://user-images.githubusercontent.com/1410282/204405155-df9a115d-e6cb-49a9-b5f7-2f0f543daf09.png">

I was assuming the button that appears then on the Blizz bag frame is for re-enabling it.

What is "bank/bank override"?

**Comment by arkayenro** [comment]
the override leaves ai running, but it doesnt override the default blizzard frames. so yo get teh default bag or bank or vault (whatever you dont set for override)

its also in the config ? general page, under controls for each location

eg, open the ai bag window, click on the location icon, go down to bag, then click on disable in the override menu
that will close the ai window and give you back the blizzard bags
clicking the ai bag icon on that will revert it.

i guess i hadnt expected anyone to disable ai and go back in but its not hard to add some more code to cater for that.

**Comment by tflo** [comment]
> overrride […] its also in the config ? general page, under controls for each location

Thanks, found it now. Indeed, for that, your button on the Blizz bag does work.

> i hadnt expected anyone to disable ai and go back in but its not hard to add some more code to cater for that.

Yeah I already made a button that runs `ArkInventory:Enable()`, but if the above-mentioned AI button on the Blizz bag could do that, it would be more elegant of course.

**Comment by arkayenro** [comment]
will be fixed next release

**Comment by tflo** [comment]
Works fine in 31010 now. Thank you very much!
