### ISSUE TITLE
Pet Cages not displaying properly in guild bank

### ISSUE THREAD

**Issue by seaglass** [arkayenro/arkinventory#1700]
**What version number you are using?**

v31009
**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**

Retail
**What language is the game client set to?**

English
**Describe the bug**
Caged Pets in my guild bank are just showing as "Pet Cage" with the name of the pet. This works properly in my Bags and Bank

**To Reproduce**
Steps to reproduce the behaviour, if possible:

I believe you just need to cage a pet and try to put it into your Guild Bank.

**Screenshots**

**Additional context**

My suspicion is that your comment here is relevant to the issue...

https://us.forums.blizzard.com/en/wow/t/lua-to-identify-pets-in-guild-bank/346625

**Comment by arkayenro** [comment]
theres an underlying issue with pet cages in the bank where blizzard do not treat them same as when they are in the bag or bank.

upgrade to alpha 2, theres a workaround in there.
