### ISSUE TITLE
[BUG] "Tint Unusable" Not Working on Latest

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1701]
![image](https://user-images.githubusercontent.com/55365231/204159392-fa33b577-1715-48b4-b63c-9326cb20a494.png)

A bunch of stuff, but easiest to spot is the group of BoE items should all be tinted red when on a Level 1 Bank Toon.

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/204159419-cdfb6b30-f2ca-46e6-a4cb-fc8da5a7c652.png)

**Comment by arkayenro** [comment]
it should be working.

check the style assigned to the bank and make sure its enabled in there

**Comment by Gogo1951** [comment]
I just have the one setting for all my bags and banks.

Tint-unusable isn't working on any of my toons since downloading the latest.

![image](https://user-images.githubusercontent.com/55365231/204179781-d6f9165a-eba6-42a0-b430-02c64f3cc623.png)

Anything I can do?

**Comment by arkayenro** [comment]
is the bank actually set to use that?  it should as its the default, but cant hurt to check

**Comment by Gogo1951** [comment]
The bank is set to use that, and the issue is happening in my bags and bank.

**Comment by arkayenro** [comment]
weird, mines working.  even if i create a new style with the only thing changed being the tint and assign it to the bank it works ok.

**Comment by wendybird** [comment]
Confirmed this is also an issue in v31010 wotlk

![in bag unusable, not tinted](https://user-images.githubusercontent.com/12815384/204636791-ace73be8-3c18-426a-be5f-8b4c382ea89f.PNG)
Class can not use bows. Item is not tinted.

![profile pane](https://user-images.githubusercontent.com/12815384/204637009-c0fca949-ea9a-476f-be39-7b93afeb8e11.PNG)
Config screen showing active profile and style.

![wobby item settings](https://user-images.githubusercontent.com/12815384/204637186-13ddcd45-3f97-4c46-9789-3911784dc5e5.PNG)
Settings screen showing that tint unusable is checked for the selected style.

**Comment by arkayenro** [comment]
disable off all other mods and confirm it with just arkinventory running please

**Comment by wendybird** [comment]
No change. 
![image](https://user-images.githubusercontent.com/12815384/204659609-262e1030-3c8d-4858-80a9-e06051b02c12.png)
Unusable item in bag, not tinted.

I don't know if this will be useful to you at all for troubleshooting, but I did test the following two rules, and they worked as expected.

First: subtype("Guns"). Expected and actual behavior = included the Ornate Blunderbuss
Second: subtype("Guns") and usable. Expected and actual behavior = excluded the Ornate Blunderbuss

So, the addon *is* recognizing it as unusable. It just isn't tinting it.

**Comment by arkayenro** [comment]
ah, wrath.  found the problem and will be fixed next release

theres an issue template for a reason.  if you dont mention a version im going to presume retail.

**Comment by bpreynolds** [comment]
Anyone eager to fix this for themselves before the next release can do so by changing one letter in one file.
Open ArkInventory\Core\ArkInventoryConst.lua and go to line 692, which should read
`["fefe1f1f"] = true, -- shadowlands`
Change the first "e" to "f" so that it now reads
`["fffe1f1f"] = true, -- shadowlands`
You can change "shadowlands" to say "wrath" or "wotlk" if you want to, but it has no effect on anything, so no reason to.

**Comment by arkayenro** [comment]
wait, is there a third colour?

the issue was is some bad code that wasnt passing the left text colour through to the get line function.

should be fixed in 3.10.10 alpha 1

**Comment by bpreynolds** [comment]
> wait, is there a third colour?
> 
> the issue was is some bad code that wasnt passing the left text colour through to the get line function.
> 
> should be fixed in 3.10.10 alpha 1

Admittedly my testing wasn't rigorous, but as a cloth-wearer who uses the unusability tint to see at-a-glance what leather/mail/plate items I can safely dump on a vendor without checking if it might be an upgrade, this was the change for me that re-enabled that tint.

**Comment by arkayenro** [comment]
updated the constants with that red text code, should be fixed next release

**Comment by arkayenro** [comment]
fixed in 3.10.12
