### ISSUE TITLE
[BUG] Lua Error in Wrath Classic on Login

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1703]
5x ...face\AddOns\ArkInventory\Core\ArkInventoryAction.lua:600: attempt to index field 'send' (a nil value)
[string "@Interface\AddOns\ArkInventory\Core\ArkInventoryAction.lua"]:600: in function `Send'
[string "@Interface\AddOns\ArkInventory\Core\ArkInventoryStorage.lua"]:1157: in function `?'
[string "@Interface\AddOns\TradeSkillMaster\External\EmbeddedLibs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ddedLibs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\TradeSkillMaster\External\EmbeddedLibs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ddedLibs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\TradeSkillMaster\External\EmbeddedLibs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceEvent\AceEvent-3.0-4.lua"]:120: in function <...rkInventory\Externals\Ace3\AceEvent\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

**Comment by arkayenro** [comment]
go back to alpha 3 for the moment, will be fixed next release

**Comment by arkayenro** [comment]
fixed in 3.10.10
