### ISSUE TITLE
[BUG] Opening mailbox not working with 3.10.09-alpha-4.

### ISSUE THREAD

**Issue by cassiopeia-x** [arkayenro/arkinventory#1704]
**What version number you are using?**
ArkInventory-3.10.09-alpha-4

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Trying to open the mailbox produces the following output and the mailbox doesn't open.

1x ...faceArkInventory/Core/ArkInventoryAction.lua:600: attempt to index field 'send' (a nil value)
[string "@ArkInventory/Core/ArkInventoryAction.lua"]:600: in function `Send'
[string "@ArkInventory/Core/ArkInventoryStorage.lua"]:1157: in function `EVENT_ARKINV_MAIL_ENTER'
[string "@ArkInventory/Core/ArkInventory.lua"]:11277: in function `HookPlayerInteractionProcess'
[string "@ArkInventory/Core/ArkInventory.lua"]:11252: in function <ArkInventory/Core/ArkInventory.lua:11249>
[string "=(tail call)"]: ?
[string "@FrameXML/PlayerInteractionFrameManager.lua"]:215: in function <FrameXML/PlayerInteractionFrameManager.lua:212>
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals:
manual = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil

**Additional context**
Version 3.10.09-alpha-2 is still working fine. I haven't checked whether 3.10.09-alpha-3 introduced the bug.

**Comment by tflo** [comment]
>  haven't checked whether 3.10.09-alpha-3 introduced the bug.

With Alpha 3 I can still open mailboxes.

**Comment by arkayenro** [comment]
bug is in alpha 4, go back to alpha 3 for the moment

**Comment by fraerie** [comment]
also getting this - rolled back to alpha 3 and have mailbox access again

**Comment by arkayenro** [comment]
fixed in 3.10.10
