### ISSUE TITLE
[BUG]  Retail - Item_lock_changed

### ISSUE THREAD

**Issue by Jorvanus** [arkayenro/arkinventory#1705]
When I click cleanup, latest alpha

![image](https://user-images.githubusercontent.com/89010934/204419864-dbac3763-e02f-43d4-a611-72b897c59e80.png)

**Comment by arkayenro** [comment]
will be gone next release

**Comment by Jorvanus** [comment]
![image](https://user-images.githubusercontent.com/89010934/204516988-e45415dd-ba8d-40ee-a058-e93220b7ba18.png)

![image](https://user-images.githubusercontent.com/89010934/204517027-9c10cfae-0d46-4d46-86d3-0c342efbfc7d.png)

Couple of additional errors i'm getting also. (Everything appers to work nonetheless)

**Comment by fraerie** [comment]
3.10.09 Seeing the same issue everytime an item is added, removed or moved in my bags.

**Comment by Jorvanus** [comment]
fixed ty
