### ISSUE TITLE
[BUG] Quality Sorting Rule selecting wrong items.

### ISSUE THREAD

**Issue by GumarxLeychar** [arkayenro/arkinventory#1710]
**What version number you are using?**
3.10.10

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Items which are not Poor Quality are being identified by the following rule. quality(0).  
I've also tried quality("poor") and q("poor")
Right clicking on the items in edit mode shows they are being sorted into the rule despite the debug menu showing them as quality 1.

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Create a rule for poor quality.  
Assign it within the bag.  
Check to see if items which are not poor quality are assigned to the slot in the bag.

**Screenshots**
![image](https://user-images.githubusercontent.com/119534888/204892108-416f16bb-d43b-4dc9-8fb5-bc2e452fbb7a.png)
![image](https://user-images.githubusercontent.com/119534888/204892165-b9c68271-f415-47d5-8851-c29b24c4f0b4.png)

**Additional context**
This issue seems to appear sporadically.  Resetting the UI doesn't force it to resolve.  I've not identified why sometimes it sorts fine and sometimes it does not.

**Comment by TylerR909** [comment]
It would also appear that Soulbound is not coming back correctly. _Everything_ is coming back Soulbound 0. Gear, Crafting Reagents, Hearthstones, etc.

[the](https://github.com/arkayenro/arkinventory/wiki/RuleFunction_Unwearable) `sb() and unwearable()` rule isn't picking up Soulbound Mail pants on my Priest, for example. 

![image](https://user-images.githubusercontent.com/20718430/204912874-645cbf43-bba8-4a5a-bc9c-3e4e223c6581.png)

**Comment by oesi94** [comment]
Have the same issue, using soulbound(), sometimes some gear have soulbound0 on debug instead of soulbound4.

**Comment by oesi94** [comment]
All of 19 showing soulbound 0 https://prnt.sc/VlvKF2q4GJOE

Tooltip says Soulbound https://prnt.sc/k0CtjUXxjjUi

**Comment by arkayenro** [comment]
could you try disabling the pre-load for the bag and bank and see if thats causing it

**Comment by GumarxLeychar** [comment]
> could you try disabling the pre-load for the bag and bank and see if thats causing it

Changing sorting rules to manual resulted in the issue not occurring after a cleanup/refresh.  

Steps taken include:
Change sorting rule to manual
Open bag and enable rule
A bunch of stuff got sorted into the tab with the rule
Refresh/Cleanup and the sorting was correct after.

**Comment by arkayenro** [comment]
config > profiles > the one youre using > controls > backpack > general > pre-load

turn that off, and the one for the bank

**Comment by ImUnicke** [comment]
> config > profiles > the one youre using > controls > backpack > general > pre-load

Came here to see if this was reported already as well. Turning off this setting seems (at a glance) to have fixed the loading of the Items in my Backpack after a reload (using v31010.Alpha.1)

*Possibly unrelated, dragging the AI window after first opening it now jumps away from my mouse cursor little by little*

**Comment by GumarxLeychar** [comment]
In my case it changed what was sorted improperly, but still is catching a number of items that are not poor quality.  

May or may not be relevant but upon first opening the bag it seems to sort most items in the bag into that rule, but not all of them.  Sometimes running clean up cuts the number down drastically, sometimes I have to reload and it changes down to a smaller number of improperly sorted items.

**Comment by arkayenro** [comment]
try 3.10.10 alpha 2

some of the changes in there may help, i still need to look into the quality rule though

**Comment by GumarxLeychar** [comment]
Will do.  If I can do anything else to help test I'm happy to help further.

**Comment by GumarxLeychar** [comment]
As it relates to the quality rule, I checked a few of the items in debug and the one commonality I found is that they have soulbound: 0 (never).  Even items that are soulbound.   Granted, other items (but not all items) which are not getting sorted into "Poor Quality" show the same.

**Comment by arkayenro** [comment]
i cant get it to pick up anything but poor quality items.

is arkinventory the only mod running and is it 310.10 alpha 2 or higher?

**Comment by arkayenro** [comment]
i changed some stuff around and i think i found the issue.  everything in each bag is getting the bag quality, and the first bag doesnt have one so gets 0.

should be fixed in alpha 4 (when released)

**Comment by GumarxLeychar** [comment]
Good find.  I can confirm it's working as expected in Alpha 4
