### ISSUE TITLE
[BUG] Error: unknown event "WEAR_EQUIPMENT_SET" on load

### ISSUE THREAD

**Issue by luitzifa** [arkayenro/arkinventory#1713]
**What version number you are using?**
3.10.10

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
wotlk classic

**What language is the game client set to?**
en

**Describe the bug**
Directly after loading scrren i get the error:
```Message: ...rkInventory\Externals\Ace3\AceEvent\AceEvent-3.0.lua:33: Attempt to register unknown event "WEAR_EQUIPMENT_SET"
Time: Thu Dec  1 22:49:31 2022
Count: 1
Stack: ...rkInventory\Externals\Ace3\AceEvent\AceEvent-3.0.lua:33: Attempt to register unknown event "WEAR_EQUIPMENT_SET"
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceEvent\AceEvent-3.0.lua"]:33: in function `OnUsed'
[string "@Interface\AddOns\ArkInventory\Libs\CallBackHandler\CallbackHandler-1.0.lua"]:142: in function `RegisterEvent'
[string "@Interface\AddOns\ArkInventory\Core\ArkInventory.lua"]:3120: in function <Interface\AddOns\ArkInventory\Core\ArkInventory.lua:3050>
[string "=[C]"]: ?
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:66: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:61>
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:626: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:611>

Locals: <none>```

**To Reproduce**
Steps to reproduce the behaviour, if possible:
1. Start Game
2. Select Character
3. Waiting for game to load
4. Error appears

**Screenshots**
If applicable, add screenshots to help explain your problem.


**Additional context**
Add any other context about the problem here.

**Comment by stratoru** [comment]
Same here. Seems like every single alpha build over the last couple months has broken the WotLK version of the addon in some way after retail-WoW fixes are implemented. Most of these would be discovered after logging in to check functionality just once before releasing. Not a huge deal to just revert to the prior versions I guess but still D:

**Comment by stratoru** [comment]
Wait, this is a problem with a release version, not even an alpha version. Which makes this more baffling.

**Comment by wendybird** [comment]
The hotfix from Blizzard today broke Ark on Wrath. This workaround will get you back in business until there is a release with a proper fix.

1. Open the file Interface\AddOns\ArkInventory\Core\ArkInventory.lua in a text editor. If you're on Windows, you can shift+right click the file, click Open With, and then select Notepad.

2. Edit -> Find or CTRL+F and then search for WEAR_EQUIPMENT_SET

3. Put a -- at the front of that line. So, it now reads: 

**--         { "WEAR_EQUIPMENT_SET", "EVENT_ARKINV_PLAYER_EQUIPMENT_CHANGED" },**

4. Save your file (File -> Save or just CTRL+S)

5. Reload the game.

**Comment by arkayenro** [comment]
weird, its still in classic.  i wonder why they removed it only from wrath

**Comment by wendybird** [comment]
@arkayenro Idk. Accidental change, perhaps? I looked for notes on the hotfix that was pushed today, but the most recent hotfix notes are from the 18th

**Comment by arkayenro** [comment]
try 3.10.10 alpha 2

**Comment by luitzifa** [comment]
3.10.10 alpha 2 works for me. Getting a warning about the missing event now. I guess thats on purpose?

**Comment by arkayenro** [comment]
yes, its that or an error
