### ISSUE TITLE
[BUG] Can't vendor anything

### ISSUE THREAD

**Issue by nwardoh** [arkayenro/arkinventory#1717]
**What version number you are using?**
31010 wrath of the lich king

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
wotlk classic

**What language is the game client set to?**
english

**Describe the bug**
When opening a vendor grays do not auto sell. When trying to manually sell you can not sell anything

**To Reproduce**
Steps to reproduce the behaviour, if possible:

**Screenshots**

**Additional context**

**Comment by nwardoh** [comment]
Also can not move anything in my bags. If I right click on an item it will equip it but the icons do not update

**Comment by wendybird** [comment]
This workaround will get you back in business until there is a release with a proper fix.

Open the file Interface\AddOns\ArkInventory\Core\ArkInventory.lua in a text editor. If you're on Windows, you can shift+right click the file, click Open With, and then select Notepad.

Edit -> Find or CTRL+F and then search for WEAR_EQUIPMENT_SET

Put a -- at the front of that line. So, it now reads:

-- { "WEAR_EQUIPMENT_SET", "EVENT_ARKINV_PLAYER_EQUIPMENT_CHANGED" },

Save your file (File -> Save or just CTRL+S)

Reload the game.

**Comment by arkayenro** [comment]
try 3.10.10 alpha 2

**Comment by LandonStewart** [comment]
<img width="288" alt="Screen Shot 2022-12-01 at 11 16 08 PM" src="https://user-images.githubusercontent.com/2685312/205236880-77f0d516-a8a4-466b-bb12-05cb195945a2.png">
3.10.10 alpha 2 works
