### ISSUE TITLE
Inventory data not updating

### ISSUE THREAD

**Issue by MrVIrTuS22** [arkayenro/arkinventory#1720]
**What version number you are using?**
11/29/2022
ArkInventory-3.10.10.zip
Release
3.4.0

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Wrath

**What language is the game client set to?**
Russian, but doesn't matter

**Describe the bug**
Any change to items in the inventory will result in incorrect display of information. Only complete deletion of character data helps.

**To Reproduce**
[Steps to reproduce the behaviour, if possible:]

**Screenshots**
(https://media.discordapp.net/attachments/392726821009096714/1048156318898323568/image.png) this is not soul stone.
(https://media.discordapp.net/attachments/392726821009096714/1048156637988397066/image.png) this is not a little health stone

**Additional context**
12/2/2022
ArkInventory-3.10.10-alpha-2.zip
Alpha
3.4.0
There is no bug in this version.
Used alpha version (latest)

**Comment by matcpn** [comment]
Same issue here on all my characters in Wrath, English language. I'll add that disabling the addon and re-loading it will update what I see in my bag but the bug still persists - updates to inventory are not reflected

**Comment by Decard6** [comment]
The issue persists on lower version such as:
- `3.10.5`
- `3.9.68`

So it probably exists on any version.
