### ISSUE TITLE
[BUG] Bank does not open in wrath

### ISSUE THREAD

**Issue by DavidBabel** [arkayenro/arkinventory#1721]
**What version number you are using?**
last

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Wrath

**What language is the game client set to?**
Fr

**Describe the bug**
Bank does not open in wrath, you click the pnj, he talks like it's open but nothing displays.
When you move, the npc talks "goodbye"

**To Reproduce**
Steps to reproduce the behaviour, if possible:
- talk to a banker

**Screenshots**
n/a

**Additional context**

**Comment by DavidBabel** [comment]
Juste noticed that the content of the bag does not update either. Bags can be opened by clicking on it, but content is fixed

**Comment by arkayenro** [comment]
try 3.10.10 alpha 2

**Comment by fabbew** [comment]
> try 3.10.10 alpha 2

3.10.10 alpha 2 is working

**Comment by DavidBabel** [comment]
Good to know, since it's a fix that address an "unusable addon issue", maybe considering the alpha => beta => release  may help to prevent some churn

**Comment by Werwolfsoul** [comment]
> try 3.10.10 alpha 2

same here, this version fixed it for me as well
