### ISSUE TITLE
[BUG] Item quality borders do not register until you move an item

### ISSUE THREAD

**Issue by Mobijuan** [arkayenro/arkinventory#1724]
**What version number you are using?**
3.10.10

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail Live

**What language is the game client set to?**
English

**Describe the bug**
All of the item quality borders are drawn white, even after pressing cleanup then refresh. Only after moving an item of that type to an empty slot does it then start to show the item quality borders for that type of item. 
This is after deleting my Arkinventory WTF files and setting it up afresh.
I have attached a video to display the behaviour. 

**To Reproduce**
Steps to reproduce the behaviour, if possible:
As above

**Screenshots**
https://gfycat.com/lawfulidenticalboto

**Additional context**

**Comment by arkayenro** [comment]
try 3.10.10 alpha 4

**Comment by arkayenro** [comment]
fixed in 3.10.12
