### ISSUE TITLE
Bar names won't show

### ISSUE THREAD

**Issue by GSPierce** [arkayenro/arkinventory#1726]
Please check into bar names not showing. They show in edit mode. Proper settings check box checked.

**Comment by arkayenro** [comment]
they are working ok for me.

if you have both names options enabled and they arent showing then you may be changing the wrong layout.

turn off the one for edit mode and go into edit mode - if they are still on then youre updating the wrong layout.

**Comment by GSPierce** [comment]
Perfect, one of the four layouts I apparently had. Makes me wonder what the other three are, but good enough for me. Thanks!
