### ISSUE TITLE
[BUG] Addon starts, but does nothing (events not starting?) (WRATH)

### ISSUE THREAD

**Issue by MyaSSSko** [arkayenro/arkinventory#1727]
Tried all last versions, including alphas, playing on wrath, ru locale

That's all i see in addon:
![image](https://user-images.githubusercontent.com/13821595/205478623-382fd418-1ab7-4f53-a30b-73ef05c591d7.png)
tried with and without different verisons of ACE3

Error text:
Date: 2022-12-04 13:58:05
ID: 1
Error occured in: Global
Count: 1
Message: ...ce\AddOns\ArkInventory\Core\ArkInventoryUpgrades.lua line 1361:
   bad argument #1 to 'pairs' (table expected, got nil)
Debug:
   [string "=[C]"]: ?
   [string "@ArkInventory\Core\ArkInventoryUpgrades.lua"]:1361: DatabaseUpgradePostLoad()
   [string "@ArkInventory\Core\ArkInventory.lua"]:3087:
      ArkInventory\Core\ArkInventory.lua:3054
   [string "=[C]"]: ?
   [string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:66:
      ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:61
   [string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:523: EnableAddon()
   [string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua"]:626:
      ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:611
Locals:
None
AddOns:
  Swatter, v3.4.6837 (SwimmingSeadragon)
  ACP, vr259 
  ArkInventory, v31011
  ArkInventoryRules, v31011
  ArkInventorySearch, v31011
  GatherMate2, v1.46.3-classic
  SlideBar, v3.4.6851 (SwimmingSeadragon)
  Stubby, v3.4.6816 (SwimmingSeadragon)
  BlizRuntimeLib_ruRU v3.4.0.30400 <none>
  (ck=122)

**Comment by arkayenro** [comment]
try 3.10.11 alpha 1

**Comment by MyaSSSko** [comment]
Seems like it's started to work.. Thanks a lot for a turbo-fix
![image](https://user-images.githubusercontent.com/13821595/205494979-0354c577-4e39-46df-8655-1da4f9d0f165.png)
