### ISSUE TITLE
[BUG] Rules doen't work anymore

### ISSUE THREAD

**Issue by Aurjn** [arkayenro/arkinventory#1728]
Hi, 

since the upgrad to Version 3.10.10 in Retail my rules doesn't work anymore.  My Rules are all like this: 
equip( "Finger" ) and soulbound( ) and q( 2, 3, 4, 5, 6, 7 )

With 3.10.09  it works just fine.

any tips?

**Comment by Aurjn** [comment]
i removed the q part, now it works again :)

**Comment by arkayenro** [comment]
try 3.10.11 alpha 1
