### ISSUE TITLE
[BUG] Q() filters in rules didn't work since 10.0.2

### ISSUE THREAD

**Issue by thomasbruchet** [arkayenro/arkinventory#1729]
**What version number you are using?**
10.0.2

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
French

**Describe the bug**
All my rules using q() for quality filter didn't work since last update.

**To Reproduce**
outfit( ) and q (3,4,5) or q (5) and type ("armure") -> not work
outfit( ) and q (3,4,5) -> not work
outfit( ) and q (5) -> not work
outfit( ) and type ("armure") -> WORK

**Screenshots**
Not work: https://i.imgur.com/rnkj8ay.png
Work: https://i.imgur.com/9IaPkwi.png

On other formula to confirme this bug on q(): 
Not work: https://i.imgur.com/qaQgRNR.png
Work: https://i.imgur.com/1An27Xv.png

**Comment by dkolb** [comment]
Just confirmed this is fixed for me in 3.10.11-alpha-1.

**Comment by thomasbruchet** [comment]
Hello, I confirm, 3.10.11-alpha-1 has solved the issue. 
Thank you.
