### ISSUE TITLE
3.00.11 Some rules are not working after latest update.

### ISSUE THREAD

**Issue by mbarbone1369** [arkayenro/arkinventory#1731]
**What version number you are using?**
3.00.11

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Some rules are working, while others are not for the bags. 
Like in the screenshots, the top shows the Garrison Bar created, so that Hearthstones, and whistle are assigned to it.
In the second screen shot is just "normal bag opening", these bars are missing, even though many of them should have items in them, based on rules, etc.

**To Reproduce**
Open the bags.

**Screenshots**
![Ark_Edit](https://user-images.githubusercontent.com/47456996/205516585-aff49f6c-5689-492c-ae30-44ff3ab45f80.jpg)
![Ark_Normal](https://user-images.githubusercontent.com/47456996/205516587-cfe640c5-16bc-4363-b1ff-44ea85c78e31.jpg)

**Comment by arkayenro** [comment]
try 3.10.11 alpha 1
