### ISSUE TITLE
[BUG] Rules with Quality function don't work

### ISSUE THREAD

**Issue by dioxina** [arkayenro/arkinventory#1732]
**What version number you are using?**
3.10.11

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
10.0.2

**What language is the game client set to?**
en

**Describe the bug**
Rules with Quality function don't work

**To Reproduce**
Remove Quality function > Item sort to correct field

**Comment by arkayenro** [comment]
try 3.10.12
