### ISSUE TITLE
[BUG] Conflict with Bankstack

### ISSUE THREAD

**Issue by dapal-003** [arkayenro/arkinventory#1734]
**What version number you are using?**
3.10.12-Alpha-1

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
When using Arkiventory to manage the guild bank, Bankstack doesn't detect that it's currently viewing a guild bank and refuses to work

**To Reproduce**
Use `/sort guild` while viewing a guild bank, a warning is displayed about not being at the (guild)bank
Disabling Arkinventory results in it working again

**Additional context**
[Bank stack can be found here](https://github.com/kemayo/wow-bankstack)

**Comment by arkayenro** [comment]
it wont work if you replace the bank or vault interface - which i do.  so either turn off arkinventory for those locations or get them to update their mod to work with 10.0

they need to listen for the new events, PLAYER_INTERACTION_MANAGER_FRAME_SHOW / HIDE, and pull arg1 from there to work out what the player is, or was, talking to.
