### ISSUE TITLE
How to use Track: Items

### ISSUE THREAD

**Issue by azuraji** [arkayenro/arkinventory#1739]
I just started out using this addon and so far I think it's fantastic.

One feature I don't seem to understand though is how to track items?

I have the **Track: Items** icon in my LDB but there's not much I can do with it in terms of interaction.

![image](https://user-images.githubusercontent.com/72912613/206229402-5b3ad22c-da34-4c89-816d-871ff1327ff8.png)

**Comment by arkayenro** [comment]
you can remove things from there once they have been added, but you can only add via the chat
