### ISSUE TITLE
How can I lock the bags frame to not accidentally drag it?

### ISSUE THREAD

**Issue by MoosGames** [arkayenro/arkinventory#1745]
I'm sure there must be a lock button somewhere and I think I've seen it before, but I just can't find it anymore even though I looked through the config multiple times. Can someone please help me to find out how to lock my bags (I've set it to bottom right anchor and want it to be locked to that position). I sometimes accidentally grab and drag the bags around.

**Comment by arkayenro** [comment]
config > general > profiles > select a profile > controls > select a location > controls > lock

or

open the location > click on main menu > blueprint > general > lock
