### ISSUE TITLE
[BUG] bad argument #1 to '?' (Usage: local itemAppearanceID, itemModifiedAppearanceID = C_TransmogCollection.GetItemInfo(itemInfo))

### ISSUE THREAD

**Issue by Ahfau77** [arkayenro/arkinventory#1757]
**What version number you are using?**
3.10.13

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail 10.0.2 (47213)

**What language is the game client set to?**
german

**Describe the bug**
after completing the quest https://www.wowhead.com/quest=70893/community-feast, i receive the error:

 bad argument #1 to '?' (Usage: local itemAppearanceID, itemModifiedAppearanceID = C_TransmogCollection.GetItemInfo(itemInfo))

when i try to open my bags.

**Comment by Ahfau77** [comment]
I've checked the "new" items in my bag.
After disabling Arkinventory and deleting one by one, the error is gone after removing:

 https://www.wowhead.com/item=201934/nokuhd-whittling-knife

from my bags.

The played char is am arms warrior at level 62.

**Comment by Dalarrus** [comment]
Had this issue with the client set to English with ArkInventory 3.10.13

Seems to be caused by grey equippable items. Mine was caused by grey plate bracers that I fished up, and did not error until hearthing and loading the ui again.

**Comment by arkayenro** [comment]
does it say what line in the code it was?

**Comment by Ahfau77** [comment]
not for me, i posted the whole message.

the error was printed in my chat-window, BugGrabber/BugSack didn't show it.

**Comment by arkayenro** [comment]
ok, try 3.10.13 alpha 1 and let me know if it happens again

**Comment by Ahfau77** [comment]
I had the identical error with my balance-druid and the same item with the "old" version.
After upgrading to the alpha, the error is gone and my bags open again.

Thank you!

**Comment by Scarah22** [comment]
Just happened to me. It was indeed Nokuhd Whittling Knife - grey item i probably fished up or looted from lunker. Bags stopped working until i auto sold greys. Then i bought back several items and filtered the bad one.

14x bad argument #1 to '?' (Usage: local itemAppearanceID, itemModifiedAppearanceID = C_TransmogCollection.GetItemInfo(itemInfo))
[string "=[C]"]: in function `GetItemInfo'
[string "@ArkInventory/Core/ArkInventory.lua"]:8014: in function `ItemTransmogState'
[string "@ArkInventory/Core/ArkInventoryCategory.lua"]:858: in function `ItemCategoryGetDefaultActual'
[string "@ArkInventory/Core/ArkInventoryCategory.lua"]:1464: in function `ItemCategoryGetDefault'
[string "@ArkInventory/Core/ArkInventoryCategory.lua"]:1528: in function `ItemCategoryGet'
[string "@ArkInventory/Core/ArkInventoryAction.lua"]:66: in function `Check'
[string "@ArkInventory/Core/ArkInventory.lua"]:7766: in function `Frame_Item_Update_StatusIconJunk'
[string "@ArkInventory/Core/ArkInventory.lua"]:9748: in function `Frame_Item_Update_Instant'
[string "@ArkInventory/Core/ArkInventoryStorage.lua"]:522: in function <...aceArkInventory/Core/ArkInventoryStorage.lua:512>
[string "=[C]"]: ?
[string "@Ace3/AceBucket-3.0-4/AceBucket-3.0.lua"]:69: in function <Ace3/AceBucket-3.0/AceBucket-3.0.lua:67>
[string "@Ace3/AceBucket-3.0-4/AceBucket-3.0.lua"]:83: in function `func'
[string "@Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

**Comment by arkayenro** [comment]
@Scarah22 did you have alpha 1 installed?
