### ISSUE TITLE
[BUG] the sorting applied instantly no matter which "When" parameter set for the "Sorting Method" option

### ISSUE THREAD

**Issue by Werwolfsoul** [arkayenro/arkinventory#1760]
**What version number you are using?**
v31013 (and v31013 alpha1), but the issues started to reproduce earlier (not sure from which build) 

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
wotlk (not repro on retail)

**What language is the game client set to?**
English

**Describe the bug**
inventory is being refreshed and sorted after each item change (moving items from one spot to another, adding items or removing items etc.) despite the "Sorting Method" option set to "On Window Open" or "Manually"

**To Reproduce**
1. navigate Settings>Designs>Sorting
2. change the "when" parameter for the "Sorting Method" option to "On Window Open"
3. reload UI
4. open inventory
5. drag and drop any item to a different cell
6. observe results
AR: the inventory is refreshed and sorting is applied right away
ER: sorting is not applied until the next window open event or manually clicking the refresh button

**Screenshots**
![image](https://user-images.githubusercontent.com/19953370/212322695-8477e620-d4a5-4848-b9ed-5f8d7b28d175.png)

**Additional context**
- the same repro for the "Manual" setting for the "Sorting Method" option, seems like it behaves as "Instantly" setting is always on
- the issue was spotted without changing any options: 
-- I had the "Sorting Method" option set to "On Window Open" and it worked ok
-- at some point, it just started working as "Instantly" setting is set
-- I checked the option and it was still set to "On Window Open" 
-- I tried changing this option to a different settings without any differences in actual behaviour

**Comment by Werwolfsoul** [comment]
I took a look at the blueprint as described in the comment section of  #1758 and there was a red record in the "Category Set" drop-down with the name that matches a custom categories name that I created a while ago and then tried to unassign items and remove the category. 
it is still can be found in the list altho it is in red color
![image](https://user-images.githubusercontent.com/19953370/214320285-7806bace-dfa1-4c88-8595-0181878e778a.png)

after selecting default for mentioned drop the issue was resolved. 

if you need any more info to investigate how to reproduce it and if it is a bug or miss configuration on my side let me know, otherwise this item can be closed since the issue itself is resolved on my side.

**Comment by Werwolfsoul** [comment]
![image](https://user-images.githubusercontent.com/19953370/214489370-fd6eab7a-694c-415f-bb6d-0fd71c77cbe6.png)

**Comment by arkayenro** [comment]
its not a bug, its working as intended.

if you delete a blueprint thats being used it reverts to using the system default (the ** locked **)

you need to either restore that blueprint option, or use a different one.  it shows in red so that you can tell which one it actually is and restore it.  if you pick a different one it will no longer show in the list.

there is also a one off error in your chat about it every time you login.
