### ISSUE TITLE
[BUG] bad argument #1 to '?'

### ISSUE THREAD

**Issue by wrufeger** [arkayenro/arkinventory#1761]
**What version number you are using?**
3.10.13

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
german

**Describe the bug**
bags wont open:
bad argument #1 to '?' (Usage: local itemAppearanceID, itemModifiedAppearanceID = C_TransmogCollection.GetItemInfo(itemInfo))

works again on 3.10.13-alpha-1

**Comment by arkayenro** [comment]
duplicate of #1757 

install alpha 1
