### ISSUE TITLE
[BUG] itemstat rule not working

### ISSUE THREAD

**Issue by rockschtar** [arkayenro/arkinventory#1762]
**What version number you are using?**
v31031 Dragonflight

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Live

**What language is the game client set to?**
English

**Describe the bug**
The "itemstat" rule seems not be working any more since Dragonflight. All my rules that are including the itemstat function stopped working. Until now i tried everything, disabled all other addons including resetting arkinventory profile. 

**To Reproduce**
Example rule:
```type("armor") and itemstat("Haste")``` or just ```itemstat("Haste")```

**Screenshots**
![image](https://user-images.githubusercontent.com/87191/212533739-5a6eec0e-86c2-4d9a-9f02-d84abd1803be.png)

**Comment by arkayenro** [comment]
try 3.10.13 alpha 2
