### ISSUE TITLE
[BUG] 2 Lua Errors on Load

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1764]
In Wrath, latest from GitHub.

Says conflict with Elv / TSM... but unsure the origin.

**Comment by Gogo1951** [comment]
11x ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
[string "@ElvUI/Core/General/Core.lua"]:379: in function `ValueFuncCall'
[string "@ElvUI/Core/General/Core.lua"]:331: in function `UpdateMedia'
[string "@ElvUI/Core/General/API.lua"]:456: in function `?'
[string "@ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-8.lua"]:114: in function <...ventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-8.lua"]:24: in function <...ventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:20>
[string "@ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-8.lua"]:59: in function `Fire'
[string "@ArkInventory/Externals/Ace3/AceEvent/AceEvent-3.0-4.lua"]:120: in function <...rkInventory/Externals/Ace3/AceEvent/AceEvent-3.0.lua:119>

**Comment by Gogo1951** [comment]
11x ...ceElvUI/Wrath/Modules/Skins/AuctionHouse.lua:134: attempt to index field 'BrowseBidText' (a nil value)
[string "@ElvUI/Wrath/Modules/Skins/AuctionHouse.lua"]:134: in function <...ceElvUI/Wrath/Modules/Skins/AuctionHouse.lua:12>
[string "=[C]"]: ?
[string "@ElvUI/Core/Modules/Skins/Skins.lua"]:1852: in function `CallLoadedAddon'
[string "@ElvUI/Core/Modules/Skins/Skins.lua"]:1793: in function `?'
[string "@ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-8.lua"]:114: in function <...ventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-8.lua"]:24: in function <...ventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:20>
[string "@ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-8.lua"]:59: in function `Fire'
[string "@ArkInventory/Externals/Ace3/AceEvent/AceEvent-3.0-4.lua"]:120: in function <...rkInventory/Externals/Ace3/AceEvent/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@TradeSkillMaster/Core/UI/AuctionUI/Core.lua"]:48: in function `_callback'
[string "@TradeSkillMaster/LibTSM/Util/Delay.lua"]:100: in function <TradeSkillMaster/LibTSM/Util/Delay.lua:93>
[string "@TradeSkillMaster/External/LibTSMClass-2/LibTSMClass.lua"]:332: in function `_CheckIfDone'
[string "@TradeSkillMaster/LibTSM/Util/Delay.lua"]:123: in function <TradeSkillMaster/LibTSM/Util/Delay.lua:116>

**Comment by arkayenro** [comment]
elvui and/or tsm.

callbackhandler is an acelibrary
