### ISSUE TITLE
[BUG] Arkinventory Bank UI and Blizzard Bank UI are both open when bank is opened up.

### ISSUE THREAD

**Issue by rbpaiett** [arkayenro/arkinventory#1765]
**What version number you are using?**
31013

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Wrath

**What language is the game client set to?**
English

**Describe the bug**
I access the bank and both the Arkinventory Bank UI and the Blizzard Bank UI open.

**To Reproduce**
Just open the bank

**Screenshots**
No screenshots needed.

**Additional context**
No other context necessary.

**Comment by luitzifa** [comment]
have the same problem.

**Comment by jazminite** [comment]
same problem

**Comment by arkayenro** [comment]
try 3.10.13 alpha 2

**Comment by rbpaiett** [comment]
Alrighty, will do, tx.

**Comment by rbpaiett** [comment]
Oh, how do I navigate to it?  I just suffered a brainfart.

**Comment by rbpaiett** [comment]
Oh nm, I see it, thanks.

**Comment by rbpaiett** [comment]
Works just fine now, thanks!
