### ISSUE TITLE
[BUG] No gbank interface

### ISSUE THREAD

**Issue by jazminite** [arkayenro/arkinventory#1766]
**What version number you are using?**
Latest released version - 3.10.13

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Wrath Classic

**What language is the game client set to?**
English

**Describe the bug**
Doesn't open frame at guild bank after P2 patch (worked before). Only opens regular game interface.

**To Reproduce**
Open a gbank

**Screenshots**
![image](https://user-images.githubusercontent.com/65823478/213306892-3e617684-f518-4e55-8adb-40b7db8738d6.png)

**Additional context**
N/A

**Comment by arkayenro** [comment]
try 3.10.13 alpha 2

**Comment by jazminite** [comment]
> try 3.10.13 alpha 2

Works, thanks!

**Comment by wendybird** [comment]
Apologies, but where would I find this? I don't see anything on the releases page, and Wago/Curse have the last release build.
![image](https://user-images.githubusercontent.com/12815384/213384025-f61150ce-c7c2-46c6-a0ab-19597a871065.png)

**Comment by arkayenro** [comment]
in curse you need to open the files tab to see alphas
in wago you need to open the alpha tab to see alphas

**Comment by kingyoshi9** [comment]
I don't see any alphas listed on curse?
![image](https://user-images.githubusercontent.com/122946032/213526329-909441f2-eec0-4082-8ae7-8ba3152bee7b.png)

**Comment by arkayenro** [comment]
click on view all
i see them by default so there must be an option to show them somewhere

**Comment by wendybird** [comment]
Blizzard just pushed a hotfix, and w/e they changed seems to have fixed this issue. I just opened my bank and guild bank, and they worked as expected.
