### ISSUE TITLE
[BUG] Black loading window in Classic

### ISSUE THREAD

**Issue by Ageous27** [arkayenro/arkinventory#1768]
With the Phase 2 launch in Classic there are a lot of errors and I get a black window that just says loading when I try to open my inventory.

**Comment by arkayenro** [comment]
cant duplicate the issue, mine loads fine in classic.

is arkinventory the only mod loaded?
what error messages are you getting?

**Comment by Ageous27** [comment]
Sorry, I realized that Curseforge was loading an old version.  Closing.
