### ISSUE TITLE
[BUG] micro menu

### ISSUE THREAD

**Issue by blecaplol** [arkayenro/arkinventory#1769]
**What version number you are using?**
latest

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
retail

**What language is the game client set to?**
en

13x Bartender4/MicroMenu.lua:89: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@ArkInventory/Externals/Ace3/AceHook/AceHook-3.0-9.lua"]:210: in function <.../ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua:118>
[string "@ArkInventory/Externals/Ace3/AceHook/AceHook-3.0-9.lua"]:340: in function `SecureHook'
[string "@Bartender4/MicroMenu.lua"]:89: in function <Bartender4/MicroMenu.lua:58>
[string "=[C]"]: ?
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:66: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:61>
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:536: in function `EnableAddon'
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:626: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:11532: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:11548: in function `BlizzardAPIHook'
...
[string "@FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

**Comment by arkayenro** [comment]
thats a bartender issue, its just using the ace3 shared libraries that i loaded first.
