### ISSUE TITLE
[BUG] AltTracking

### ISSUE THREAD

**Issue by JohnnyOtkatilo** [arkayenro/arkinventory#1776]
V4.12.32
Message: TSM/LibTSM/Service/AltTracking.lua:208: assertion failed!
Time: 02/01/23 19:04:31 (1198383224)
Client: 10.0.5 (47884)
Locale: ruRU
Combat: false
Error Count: 1
Stack Trace:
  TSM/LibTSM/Service/AltTracking.lua:208 <UpdateDB>
    totalQuantity = {
      i:140333 = 10
      i:109118 = 1157
      i:95491 = 34
      i:133571 = 13
      i:169223::+2 = 1
      i:171418::+116 = 1
      i:112826::+3 = 1
      i:152747::+0 = 1
      i:198159 = 3
      i:102286 = 3
      i:137049::+9 = 1
      i:201921 = 1
      i:170554 = 6
      i:188152 = 1
      i:129928 = 1
      i:128610 = 1
      i:184504 = 3
      i:167048 = 3
      i:187837 = 3
      i:128507 = 6
      i:188007::+3 = 1
      i:153705 = 145
      i:195543 = 1
      i:197746 = 13
      i:136975::+365 = 1
      i:86425 = 1
      i:201255 = 10
      i:187552 = 1
      i:142117 = 6
      i:174315::+98 = 1
      i:85592 = 1
      i:137046::+9 = 1
      i:142097 = 1
      i:193001::i392 = 1
      i:186718 = 56
      i:177962 = 3
      i:87208 = 15
      i:133324::i6 = 1
      i:14512 = 1
      i:71083 = 204
      i:53643 = 9
      i:71617 = 3
      i:167786 = 2
      i:38320 = 1
      p:2473 = 1
      i:172052 = 555
      i:193230 = 2
      i:160491::+5 = 1
      i:1776::i56 = 1
      i:14099 = 1
      i:89685 = 1
      i:124441 = 2
      i:19019 = 1
      i:40772 = 3
      i:127115 = 16
      i:4236 = 2
      i:172419 = 4
      i:115280 = 135
      i:76095 = 1
      i:183298 = 1
      i:201406 = 11
      i:169499 = 1
      i:8153 = 2
      i:151564 = 88
      i:172957 = 33
      i:21100 = 75
      i:191237::i346 = 3
      i:142522 = 1
      i:13505::i87 = 1
      i:124113 = 95
      i:167555::+8 = 1
      p:2797 = 8
      i:94226 = 199
      i:188658 = 8
      i:111658 = 1
      i:128941::+50 = 1
      i:182964::+81 = 1
      i:115350 = 1
      i:2589 = 98
      i:134268::+352 = 1
      i:154174 = 1
      p:2840 = 2
      i:153510 = 1
      i:8343 = 4
      i:191238::i332 = 1
      i:200407::+0 = 1
      i:198192 = 3
      i:144279::+9 = 1
      i:128823 = 1
      i:8846 = 8
      i:21844 = 32
      i:164766 = 1
      i:154167 = 5
      i:71715 = 15
      i:193920 = 3
      i:194337 = 4
      i:158075::+79 = 1
      i:200880::i256 = 1
      i:155831 = 1
      i:34664 = 60
      i:184506 = 1
      i:200563::i256 = 1
      i:193442::i343 = 1
      i:139590 = 1
      i:200082 = 4
      i:200506 = 4
      i:169860 = 2
      i:118278 = 1
      i:171176 = 218
      i:190456 = 5169
      i:52194 = 9
      i:87399 = 325
      i:31901 = 1
      i:21301 = 1
      i:45067 = 1
      i:193020 = 3
      i:144364::+9 = 1
      i:81055 = 161
      i:193470 = 1
      i:86566::i90 = 1
      i:152513 = 571
      i:77949 = 1
      i:193922 = 483
      i:201323 = 2
      i:187326 = 7
      i:72162 = 5
      i:151784::+9 = 1
      p:2832 = 1
      i:2449 = 7
      i:200641::i337 = 1
      i:192872 = 79
      i:202039 = 25
      i:9327 = 1
      i:87595::i90 = 1
      i:52192 = 3
      i:87764 = 8
      i:116913::i103 = 1
      i:190932 = 1
      i:8838 = 9
      i:124119 = 190
      i:2459 = 7
      i:6310 = 2
      i:25343::i56 = 1
      i:138007 = 1
      i:20406 = 1
      i:132752 = 9
      i:20407 = 1
      i:115008 = 1
      i:121356::i104 = 1
      i:188725::i180 = 1
      i:173204 = 69
      i:86468 = 1
      i:87216 = 11
      i:5213 = 1
      i:184480 = 1
      i:194124 = 44
      i:160324 = 1
      i:128225 = 1
      i:21002::i6 = 1
      i:7286 = 1
      i:168215 = 1
      i:193360 = 5
      i:192055 = 96
      i:188524::+49 = 6
      i:24588::i66 = 1
      i:104264 = 2
      i:172321::+60 = 1
      i:129158 = 31
      p:2901 = 1
      i:1770::i56 = 1
      i:2840 = 92
      i:172045 = 212
      i:138272 = 1
      i:25403::i56 = 1
      i:102264 = 9
      i:193708::+126 = 1
      i:24589::i30 = 1
      i:3169 = 1
      i:154786::i87 = 1
      i:49050 = 2
      i:1427::i47 = 1
      i:52177 = 1
      i:31952 = 2
      i:200071 = 1
      i:62094::i62 = 1
      i:163483 = 1
      i:49040 = 1
      i:190313 = 4
      i:168620 = 1
      i:183827 = 2
      i:198185 = 8
      i:197754 = 3
      i:31248::i75 = 1
      i:116913::i100 = 1
      i:94223 = 176
      i:858 = 1
      i:128647 = 5
      i:153164 = 13
      i:192097 = 14
      i:140846::+9 = 1
      i:186985 = 1
      i:176948::i148 = 1
      i:9742 = 1
      i:123918 = 383
      i:6513 = 1
      i:3575 = 30
      i:77950 = 1
      i:11325 = 2
      i:36925 = 1
      i:138393 = 1
      i:152734 = 1
      i:114943 = 5
      i:153555 = 5
      i:193609::i343 = 1
      i:193444::i343 = 1
      i:132753 = 6
      i:86574 = 1
      i:25372::i56 = 1
      i:10083::i66 = 1
      i:198330::i316 = 17
      i:24811::i66 = 1
      i:25075::i66 = 1
      i:45798 = 1
      i:144249::i220 = 1
      i:189163 = 7
      i:198328::i316 = 10
      i:8623 = 1
      i:198331::i316 = 11
      i:167555::+2 = 3
      i:167181 = 4
      i:153701 = 275
      i:3810::i56 = 1
      i:199039::i302 = 7
      i:192615 = 2
      i:17203 = 1
      i:199043::i302 = 1
      i:198985::i292 = 2
      i:23447 = 2
      i:190451 = 19
      i:113191 = 1
      i:199002::i292 = 1
      i:21877 = 2611
      i:193050 = 260
      i:2320 = 258
      i:184152 = 18
      i:71636 = 10
      i:128870::+51 = 1
      i:45991 = 2
      i:199197 = 1
      i:126948::i14 = 2
      i:31243::i75 = 1
      i:102250 = 1
      i:199211 = 30
      i:198283 = 4
      i:19299 = 5
      i:128910 = 1
      i:116786 = 1
      i:184386 = 24
      i:118099 = 51
      i:146668::+9 = 1
      i:187106 = 1
      i:3358 = 15
      i:179314 = 391
      i:86527 = 1
      i:193506::i343 = 1
      i:201422 = 8
      i:71153 = 183
      i:16789
    }
  TSM/LibTSM/Service/AltTracking.lua:54 <settingsLoadFunc>
  TSM/LibTSM/Core.lua:160 <ProcessSettingsLoad>
    path = "Service.AltTracking"
    context = {
      module = {}
      path = "Service.AltTracking"
      moduleLoadTime = 0
      settingsLoadFunc@TSM/LibTSM/Service/AltTracking.lua:32
      settingsLoadTime = 0
    }
    st = 1198382556.481600
    private = {
      gotAddonLoaded = true
      gotPlayerLogout = false
      gotPlayerLogin = false
      frame = Frame {
      }
    }
  TSM/LibTSM/Core.lua:212 <Core.lua:202>
    _ = Frame {}
    event = "ADDON_LOADED"
    arg = "TradeSkillMaster"
    (for generator) = <function> defined =[C]:-1
    (for state) = {
      1 = "Environment"
      2 = "Locale"
      3 = "LibTSMClass"
      4 = "Util.Debug"
      5 = "Util.TempTable"
      6 = "Util.Math"
      7 = "Util.HSLuv"
      8 = "Util.String"
      9 = "Util.ObjectPool"
      10 = "Util.ReactiveClasses.Publisher"
      11 = "Util.Table"
      12 = "Util.ReactiveClasses.State"
      13 = "Util.ReactiveClasses.StateSchema"
      14 = "Util.ReactiveClasses.Stream"
      15 = "Util.DatabaseClasses.Constants"
      16 = "Util.DatabaseClasses.Util"
      17 = "Util.Vararg"
      18 = "Util.DatabaseClasses.QueryResultRow"
      19 = "Util.DatabaseClasses.QueryClause"
      20 = "Util.Reactive"
      21 = "Util.DatabaseClasses.Query"
      22 = "Util.DatabaseClasses.DBTable"
      23 = "Util.SlotId"
      24 = "Util.DatabaseClasses.Schema"
      25 = "Data.BonusIds"
      26 = "Util.SmartMap"
      27 = "Data.FontPaths"
      28 = "Util.Color"
      29 = "Util.FontObject"
      30 = "Util.Theme"
      31 = "Util.Log"
      32 = "Util.FSMClasses.State"
      33 = "Util.FSMClasses.Machine"
      34 = "Util.Event"
      35 = "Util.JSON"
      36 = "Util.ItemString"
      37 = "Util.Container"
      38 = "Service.ErrorHandler"
      39 = "Util.Sound"
      40 = "Util.CSV"
      41 = "Util.Wow"
      42 = "Service.Settings"
      43 = "Data.ItemClass"
      44 = "Data.VendorSell"
      45 = "Util.Analytics"
      46 = "Util.Database"
      47 = "Util.Delay"
      48 = "Service.DefaultUI"
      49 = "Service.ItemInfo"
      50 = "Util.Money"
      51 = "Data.DisenchantInfo"
      52 = "Data.Mill"
      53 = "Data.Prospect"
      54 = "Data.Transform"
      55 = "Data.VendorTrade"
      56 = "Service.Conversions"
      57 = "Util.Future"
      58 = "Service.AuctionScanClasses.Util"
      59 = "Service.AuctionHouseWrapper"
      60 = "Service.AuctionScanClasses.ResultSubRow"
      61 = "Util.FSM"
      62 = "Service.AuctionScanClasses.ResultRow"
      63 = "Service.AuctionScanClasses.Scanner"
      64 = "Service.Threading"
      65 = "Service.AuctionScanClasses.Query"
      66 = "Service.AuctionScanClasses.QueryUtil"
      67 = "Service.AuctionScanClasses.ScanManager"
      68 = "Service.ItemTooltipClasses.ExtraTip"
      69 = "Service.ItemTooltipClasses.Builder"
      70 = "Service.ItemTooltipClasses.Wrapper"
      71 = "Service.TooltipScanning"
      72 = "Service.SyncClasses.Constants"
      73 = "Service.SyncClasses.Comm"
      74 = "Service.SyncClasses.Connection"
      75 = "Service.SyncClasses.RPC"
      76 = "Service.SyncClasses.Mirror"
      77 = "Service.InventoryInfo"
      78 = "Service.AuctionTracking"
      79 = "Service.Sync"
      80 = "Service.PlayerInfo"
      81 = "Service.CustomPrice"
      82 = "Service.AltTracking"
      83 = "Service.BagTracking"
      84 = "Service.MailTracking"
      85 = "Util.MatString"
      86 = "Data.ProfessionInfo"
      87 = "Service.ProfessionHelpers.State"
      88 = "Service.ProfessionHelpers.Quality"
      89 = "Util.CraftString"
      90 = "Service.ProfessionHelpers.Scanner"
      91 = "Util.TextureAtlas"
      92 = "Util.ScriptWrapper"
      93 = "Util.RecipeString"
      94 = "Service.Profession"
      95 = "UI.WidgetExtensions"
      96 = "Data.ClassicRealms"
      97 = "Service.SlashCommands"
      98 = "Service.BlackMarket"
      99 = "Service.Inventory"
      100 = "UI.UIUtils"
      101 = "UI.UIElements"
      102 = "UI.Tooltip"
      103 = "UI.Rectangle"
      104 = "Service.ItemLinked"
      105 = "UI.SyntaxHelpers"
      106 = "UI.DragContext"
      107 = "Util.NineSlice"
      108 = "Service.AuctionScan"
      109 = "UI.UIManager"
      110 = "Service.ItemFilter"
      111 = "Service.GuildTracking"
      112 = "Service.ItemTooltip"
    }
    (for control) = 82
    _ = 82
    path = "Service.AltTracking"
    ADDON_NAME = "TradeSkillMaster"
    private = {
      gotAddonLoaded = true
      gotPlayerLogout = false
      gotPlayerLogin = false
      frame = Frame {
      }
      conte
    }
Temp Tables:
  [3] ?
Object Pools:
  AUCTION_SCAN_RESULT_ROW (0 created, 0 in use)
    <none>
  DATABASE_SCHEMAS (1 created, 0 in use)
    <none>
  PUBLISHER (0 created, 0 in use)
    <none>
  EXPIRING_MAIL_TASK (0 created, 0 in use)
    <none>
  TOOLTIP_ENTRY (0 created, 0 in use)
    <none>
  GATHERING_ALT_TASK (0 created, 0 in use)
    <none>
  SCROLLING_TABLE_COL_INFO (0 created, 0 in use)
    <none>
  AUCTION_SCAN_MANAGER (0 created, 0 in use)
    <none>
  LIST_ROWS (0 created, 0 in use)
    <none>
  QUERY_SCROLLING_TABLE_COL_INFO (0 created, 0 in use)
    <none>
  DATABASE_QUERY_CLAUSES (5 created, 5 in use)
    [5] ???
  COOLDOWN_TASK (0 created, 0 in use)
    <none>
  AUCTION_SCAN_RESULT_SUB_ROW (0 created, 0 in use)
    <none>
  TABLE_ROWS (0 created, 0 in use)
    <none>
  DATABASE_QUERIES (3 created, 3 in use)
    [3] ???
  EXPIRED_AUCTION_TASK (0 created, 0 in use)
    <none>
  DATABASE_QUERY_RESULT_ROWS (11 created, 11 in use)
    [11] ???
  AUCTION_SCAN_QUERY (0 created, 0 in use)
    <none>
Running Threads:
Debug Log:
  19:04:26.180 [ERR] {ErrorHandler.lua:169} TSM/LibTSM/Service/AltTracking.lua:208: assertion failed!
  19:04:26.180 [ERR] {Connection.lua:250} Missing friends info - will try again
  19:04:26.180 [INFO] {ItemInfo.lua:220} Imported 27706 items worth of data
Addons:
  Accountant_Classic (v2.12.24)
  AddonFactory (10.0.010)
  AllTheThings (DF-3.2.0)
  Altoholic (10.0.010)
  Auctionator (10.0.36)
  AutoLootPlus (2.0.0-80200)
  BetterWardrobe (4.7)
  BlizzMove (v3.5.9)
  BtWQuests (2.27.0)
  !BugGrabber (v10.0.3)
  BugSack (v10.0.3)
  BuyEmAll (3.5.15)
  CanIMogIt (10.0.5v1.46)
  Capping (v10.0.13)
  Collectionator (0.104)
  CopyPasta (1.1.2)
  CovenantMacro (1.0.7)
  CraftSim (6.1)
  DataStore (2023.01.06)
  DeModal (0.7.3)
  Details (#Details.DF.Wrath.10410.148)
  Details_Compare2 ()
  Details_RaidCheck ()
  Details_Streamer ()
  Details_TinyThreat ()
  Details_Vanguard ()
  FriendGroups (10.0.1)
  GlobalIgnoreList (10.0.5)
  HandyNotes (v1.6.13)
  HandyNotes_Dragonflight (30)
  HandyNotes_DragonflightTreasures (v41)
  HandyNotes_LegionTreasures (v32)
  HandyNotes_Shadowlands (52)
  HandyNotes_ShadowlandsTreasures (v73)
  HandyNotes_TreasureHunter (v33)
  hide-increase-backpack-button (2.0.1)
  HidingBar (v10.0.8)
  InfiniteRaidTools (10.07)
  InstanceAchievementTracker (4.14.0)
  InteractiveWormholes (100002.33-Release)
  Krowi_AchievementFilter (51.4)
  Ace3 (Release-r1294)
  MasterPlanA (A)
  MRT (4720)
  MikScrollingBattleText (5.7.153.df3)
  MinimalArchaeology (10.0.3)
  MogIt (v3.9.12)
  Molinari (100002.95-Release)
  MythicDungeonTools (4.0.2.4)
  MythicPlusTimer (5.0.3)
  OmniBar (v14.8)
  OmniCD (10.0.5.2742)
  OPie (Yuzu 5b)
  tdBattlePetScript (v1.5)
  PortGear (4)
  Postal (v3.9.5)
  PremadeGroupsFilter (3.6.1)
  RaiderIO (10.0.0 (v202301290715))
  RaiderIO_DB_EU_M ()
  RaiderIO_DB_EU_R ()
  RaidAchievement ()
  RandomHearthToy (2.1a)
  RareShareKorthia (v0.6.0)
  RareShare (v1.1.0)
  RareShare_Zereth_Mortis (0.2.0)
  RareScanner (10.0.5.1)
  Rarity (1.0 (r718-release-4))
  Rarity_Options ()
  RCLootCouncil (3.7.0)
  Rematch (4.14.13)
  Rematch_TSMPetValues (1.1.30)
  RematchElvUISkin (1.3.0)
  SavedInstances (10.0.9)
  SilverDragon (v2023.1)
  SilverDragon_Overlay (v2023.1)
  SilverDragon_RangeExtender (v2023.1)
  SimpleAddonManager (v1.20)
  SoulshapeJournal (1.2.1)
  Spy (3.10.2)
  TLDRMissions (10.0-013)
  TomTom (v3.3.5-release)
  TurnIn (2.2) [Not Loaded]
  UnlimitedMapPinDistance (1.2.2) [Not Loaded]
  VenturePlan (4.37) [Not Loaded]
  WarPlan (3.22) [Not Loaded]
  WeakAuras (5.3.7) [Not Loaded]
  WeakAurasCompanion (4.1.0) [Not Loaded]
  WorldQuestTracker (v10.0.2.460-Retail) [Not Loaded]
  WorldBossTimers (v1.10) [Not Loaded]
  +Wowhead_Looter (100005)
  WoWthing_Collector (10.0.5.3) [Not Loaded]
  WQAchievements (v10.0.2-7) [Not Loaded]
  VenturePlanMoreFollowers (10) [Not Loaded]
  ParagonReputation (1.44)
  TSM (v4.12.32)
  TSM_AppHelper (v4.0.23) [Not Loaded]
  ElvUI (13.23)
  ElvUI_Libraries (1.00)
  Narcissus (1.3.9)
  Narcissus_BagFilter (1.0.0)
  BetterFishing (1.1.10)
  NPCTime (1.0.10)
  DBM-Core (6065739)
  Scrap (10.0.10)
  DejaCharacterStats (R100002r2)

**Comment by arkayenro** [comment]
thats a tsm/altoholic issue.

that error trace says you dont even have arkinventory installed.
