### ISSUE TITLE
In Wrath Classic, It Tints Leather & Mail as "Unwearable" for Warriors

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1785]
![image](https://user-images.githubusercontent.com/55365231/230957100-e06edc7a-8380-4b3f-9642-58fe85585db8.png)

Warriors can wear everything! (=

This is super minor, turning that option off again. Was just playing around and saw this.

**Comment by arkayenro** [comment]
working as intended. while you can wear everything that doesnt mean that you should (or that its good for you)

**Comment by Gogo1951** [comment]
A lot of Warriors and Paladins use Mail and Leather in Wrath.

A lot of Healers use Cloth. It's not "Unusable" in Wrath, it's the BiS item for your class.
