### ISSUE TITLE
[BUG] WARNING>function for [HookOpenAllBags:GearManagerDialogPopup] was not found

### ISSUE THREAD

**Issue by d3xavier** [arkayenro/arkinventory#1801]
**What version number you are using?**
v31016

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Wrath

**What language is the game client set to?**
English

**Describe the bug**
Just see a notification in the chat window.  I don't see a LUA error.  I am having a hard time replicating it.  I have enabled Debug in the ArkInventory settings, but not getting any additional output.

**To Reproduce**
Steps to reproduce the behaviour, if possible:

**Screenshots**
![image](https://github.com/arkayenro/arkinventory/assets/4826700/cd5722bb-8b81-4651-a439-f24456927472)

**Additional context**

**Comment by arkayenro** [comment]
fixed in 31016-alpha-1
