### ISSUE TITLE
when open bags, error in datastore currencies

### ISSUE THREAD

**Issue by migzlv** [arkayenro/arkinventory#1806]
**What version number you are using?**
31016

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
retail

**What language is the game client set to?**
english

**Describe the bug**
17x AceEvent30Frame:RegisterEvent(): AceEvent30Frame:RegisterEvent(): Attempt to register unknown event "RESEARCH_ARTIFACT_HISTORY_READY"
[string "=[C]"]: in function `RegisterEvent'
[string "@ArkInventory/Externals/Ace3/AceEvent/AceEvent-3.0-4.lua"]:33: in function `OnUsed'
[string "@ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-8.lua"]:137: in function `RegisterEvent'
[string "@DataStore_Crafts/DataStore_Crafts.lua"]:825: in function <DataStore_Crafts/DataStore_Crafts.lua:814>
[string "=[C]"]: ?
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:66: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:61>
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:626: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:11532: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:11548: in function `BlizzardAPIHook'
[string "@ArkInventory/Core/ArkInventory.lua"]:3169: in function <ArkInventory/Core/ArkInventory.lua:3135>
...
[string "@FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:175: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:168: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:163: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:154: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:150>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:118: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
(*temporary) = AceEvent30Frame {
 0 = <userdata>
}
(*temporary) = "RESEARCH_ARTIFACT_HISTORY_READY"
______________________________________________________

AND

17x DataStore_Currencies/DataStore_Currencies.lua:601: attempt to call global 'RequestArtifactCompletionHistory' (a nil value)
[string "@DataStore_Currencies/DataStore_Currencies.lua"]:601: in function <DataStore_Currencies/DataStore_Currencies.lua:586>
[string "=[C]"]: ?
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:66: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:61>
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:626: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:11532: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:11548: in function `BlizzardAPIHook'
[string "@ArkInventory/Core/ArkInventory.lua"]:3169: in function <ArkInventory/Core/ArkInventory.lua:3135>
[string "=[C]"]: ?
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:66: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:61>
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
...
[string "@FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:175: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:168: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:163: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:154: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:150>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:118: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:363
 Enable = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:290
 RegisterChatCommand = <function> defined @ArkInventory/Externals/Ace3/AceConsole/AceConsole-3.0.lua:81
 EnableModule = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:438
 defaultModuleLibraries = <table> {
 }
 UnregisterChatCommand = <function> defined @ArkInventory/Externals/Ace3/AceConsole/AceConsole-3.0.lua:107
 Printf = <function> defined @ArkInventory/Externals/Ace3/AceConsole/AceConsole-3.0.lua:65
 SetDefaultModulePrototype = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:405
 name = "DataStore_Currencies"
 IsEnabled = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 DisableModule = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:346
 RegisterMessage = <function> defined @ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:85
 GetArgs = <function> defined @ArkInventory/Externals/Ace3/AceConsole/AceConsole-3.0.lua:140
 Print = <function> defined @ArkInventory/Externals/Ace3/AceConsole/AceConsole-3.0.lua:50
 Characters = <table> {
 }
 IsModule = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:464
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:383
 ThisCharacter = <table> {
 }
 baseName = "DataStore_Currencies"
 SetEnabledState = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:420
 OnDisable = <function> defined @DataStore_Currencies/DataStore_Currencies.lua:605
 enabledState = true
 OnEnable = <function> defined @DataStore_Currencies/DataStore_Currencies.lua:586
 RegisterEvent = <function> defined @ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:85
 UnregisterAllMessages = <function> defined @ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:169
 OnInitialize = <function> defined @DataStore_Currencies/DataStore_Currencies.lua:550
 UnregisterAllEvents = <function> defined @ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:169
 SendMessage = <function> defined @ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:54
 IterateModules = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:433
 UnregisterMessage = <function> defined @ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:148
 NewModule = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:231
 GetName = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:275
 defaultModuleState = true
 UnregisterEvent = <function> defined @ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:148
 Disable = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:310
}
_ = 7
_ = 9
arch = 11
(*temporary) = nil
(*temporary) = "attempt to call global 'RequestArtifactCompletionHistory' (a nil value)"
addon = <table> {
 SetDefaultModuleLibraries = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:363
 Enable = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:290
 RegisterChatCommand = <function> de

**To Reproduce**
Steps to reproduce the behaviour, if possible:

**Screenshots**

**Additional context**

**Comment by arkayenro** [comment]
its DataStore_Crafts having the issue.

itsusing the ace3 libraries loaded by arkinventory but the problem is in its own code.
