### ISSUE TITLE
[BUG] [ADDON_ACTION_BLOCKED] protected function 'Frame:SetPassThroughButtons()

### ISSUE THREAD

**Issue by cgsub** [arkayenro/arkinventory#1807]
**What version number you are using?**
ArkInventory-3.10.16.zip Curseforge release install.

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enUS

**Describe the bug**
Calling of protected function **'Frame:SetPassThroughButtons()',** changed in patch 10.1.5 as protected while in combat:

 32x [ADDON_ACTION_BLOCKED] AddOn 'ArkInventory' tried to call the protected function 'Frame:SetPassThroughButtons()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetPassThroughButtons'

**To Reproduce**
Loot something when in combat

**Screenshots**

**Additional context**
Handynotes seemed to have the exact same issue:
https://github.com/Nevcairiel/HandyNotes/issues/4

**Comment by arkayenro** [comment]
SetPassThroughButtons is not in my code anywhere.  its more likely that its another mod that is using one of the ace3 libraries

disable arkinventory and repeat whatever causes the issue, another mod should get blamed.

suggest following standard addon blocked process to determine which mod is actually causing the issue
