### ISSUE TITLE
Short description of your question

### ISSUE THREAD

**Issue by wambuwulance** [arkayenro/arkinventory#1808]
**What version number you are using?**
Outfitter-1.3.2

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Clasic Era

**What language is the game client set to?**
English 

**Ask your question**
Hi, for some reason. I'm unable to create new outfits. I have "Normal" and Birthday Suit and those function well. But I'm unable to create other outfits. Ive tried some fixes I saw online, and have not been able to get it working. 

Below is the LUA error and an image. 
Date: 2023-07-31 20:43:39
ID: 3
Error occured in: Global
Count: 1
Message: ...tter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua line 165:
   attempt to call method 'SetBackdrop' (a nil value)
Debug:
   [string "=[tsm error check]"]:1: in main chunk
   [string "=(tail call)"]: ?
   [string "=[C]"]: SetBackdrop()
   [string "@Outfitter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua"]:165: SetDialogBackdrop()
   [string "@Outfitter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua"]:188: Construct()
   [string "@Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua"]:145: inheritOver()
   [string "@Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua"]:41: initObject()
   [string "@Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua"]:15:
      ...dOns\Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua:6
   [string "=(tail call)"]: ?
   [string "@Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua"]:10: New()
   [string "@Outfitter\Outfitter.lua"]:3826: OpenNameOutfitDialog()
   [string "@Outfitter\Outfitter.lua"]:3839: CreateNewOutfit()
   [string "*:OnClick"]:2:
      [string "*:OnClick"]:1

<img width="1512" alt="Screenshot 2023-07-31 at 8 43 58 PM" src="https://github.com/arkayenro/arkinventory/assets/141098739/06a51a27-807d-4992-9796-ebcf23fab39b">

**Comment by arkayenro** [comment]
outfitter is not my mod.  setbackdrop was deprecated a while back.

theres a couple of other variants of outfitter on curse that you might need to swap to.
