### ISSUE TITLE
[BUG] An item is ignoring a rule to move it to a bar.

### ISSUE THREAD

**Issue by JoeyJFranklin** [arkayenro/arkinventory#1810]
**What version number you are using?**
V31016

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
I have a rule assigned to a bar: q(0), an item that this rule should apply to isn't being moved to the bar https://www.wowhead.com/item=25402/the-stoppable-force

**To Reproduce**
Make a custom rule with q(0) as the formula, assign it to a bar, have The Stoppable Force in your bags.

**Screenshots**
![image](https://github.com/arkayenro/arkinventory/assets/134342419/958967cc-7826-43f2-a976-a80b5ed55e71)
![image](https://github.com/arkayenro/arkinventory/assets/134342419/ce189d69-5721-4cbc-9f2b-935236430477)
![image](https://github.com/arkayenro/arkinventory/assets/134342419/09557f9a-102a-4cca-9d17-85cd5bcf5bd0)

**Additional context**

**Comment by arkayenro** [comment]
its probably assigned to a system category which means a rule cannot pick it up.

in edit mode click on the item and then click on its default category, that should reset it and allow the rule to pick it up

**Comment by JoeyJFranklin** [comment]
Ah yes that default category would be problematic :D

![image](https://github.com/arkayenro/arkinventory/assets/134342419/813f9946-5598-4c17-8063-f773d6f014fe)

Thanks Ark!

**Comment by arkayenro** [comment]
it is actually a currency for a pet, one of the many junk items that are.
