### ISSUE TITLE
[BUG] Default Blizzard Bag Bar Not Hidden While Addon Enabled

### ISSUE THREAD

**Issue by Greybaine** [arkayenro/arkinventory#1820]
**What version number you are using?**

Ark version: 3.10.17 // Game Version: 10.1.15

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**

* Retail

**What language is the game client set to?**

English

**Describe the bug**

* For some reason the default blizzard bag bar still shows while addon is enabled. I've disabled all addons except for Ark inventory and it seems the default blizzard bag bar persists. Perhaps, this is not a bug and more of a feature request? I am not 100% certain but I was hoping that Ark Inventory would hide it. 

**To Reproduce**

1. Install the addon
2. Disable all other addons
3. You should see that the default blizzard bag bar appears on your screen.

**Screenshots**

![image](https://github.com/arkayenro/arkinventory/assets/53406911/4a45d9bd-c819-4c2f-98b6-fc8e718de3b9)

**Additional context**

**Comment by arkayenro** [comment]
arkinventory doesnt hide the bag bar.  its part of the ui, not the bags, so i left it alone.

most of the ui mods will have an option to hide that
