### ISSUE TITLE
[BUG] Freeze/Stutter/FPS Spike when receiving currency/items

### ISSUE THREAD

**Issue by CrayonIRL** [arkayenro/arkinventory#1821]
**What version number you are using?**
3.10.17 (02-SEP-2023)

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Large FPS drops/stutters when receiving currency or items during.
Example: in any BG (easily tested in this weeks brawl) when I get the chat message "you receive currency: [Honor]x##" I get a drop of ~40FPS and the game stutters for about half a second. 
Example: Clicking a mage table, same drops happen every instance of receiving Conjured Mana Bun x20

**To Reproduce**
Easiest way to reproduce is during this weeks brawl since you eventually get a stream of "you receive currency: [Honor]x##" which causes constant lag/stutter. Tested with with all addons disabled except for Ark Inventory, lag/stutter still occurs. With no addons or just no Ark Inventory installed there is no more lag/stutter.

Another way to reproduce is just clicking a mage table.

**Screenshots**
(example of currency received in chat)
![image](https://github.com/arkayenro/arkinventory/assets/80538241/73f07178-c362-4c19-9798-49d6e328cfae)

(video example of stutter during received currency, all addons disabled except Ark Inventory)
https://youtu.be/ImGuws3iKak

**Additional context**
I only just started using Ark Inventory yesterday (previously Adi Bags)
![image](https://github.com/arkayenro/arkinventory/assets/80538241/cc4e015e-44fb-4b96-bcdd-26eb274b5ad8)

**Comment by arkayenro** [comment]
3.10.18 alpha 2 onwards should have a fix for it.

**Comment by CrayonIRL** [comment]
> 3.10.18 alpha 2 onwards should have a fix for it.

Testing 3.10.18 alpha 3 tomorrow. Thanks!
![image](https://github.com/arkayenro/arkinventory/assets/80538241/e082fb0a-4a95-49a7-9515-519698db8280)

**Comment by arkayenro** [comment]
fixed in 3.10.19
