### ISSUE TITLE
[BUG] securehook error

### ISSUE THREAD

**Issue by kkatee** [arkayenro/arkinventory#1822]
**What version number you are using?**

3.10.17

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**

wotlk icc ptr

**What language is the game client set to?**

english

**Describe the bug**
LUA error on startup, bags dont display correctly.

Message: Interface/AddOns/ArkInventory/Core/ArkInventory.lua:11641: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
Time: Thu Sep 21 06:37:11 2023
Count: 1
Stack: Interface/AddOns/ArkInventory/Core/ArkInventory.lua:11641: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua"]:210: in function <.../ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua:118>
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:11641: in function `BlizzardAPIHook'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:3163: in function <Interface/AddOns/ArkInventory/Core/ArkInventory.lua:3129>
[string "=[C]"]: ?
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua"]:66: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua"]:626: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:611>

Locals: (*temporary) = "Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target"

**To Reproduce**
Steps to reproduce the behaviour, if possible: log into ptr with the addon.

**Screenshots**
![image](https://github.com/arkayenro/arkinventory/assets/34851555/bb2cf09d-88c4-42be-ab2e-4835c6309a26)
only the backpack is displayed

**Additional context**

**Comment by kkatee** [comment]
![image](https://github.com/arkayenro/arkinventory/assets/34851555/4541d3c6-3152-4cc5-bd0e-3270ec95e2ef)

**Comment by arkayenro** [comment]
try [3.10.17-alpha-1](https://legacy.curseforge.com/wow/addons/ark-inventory/files/4761101)

**Comment by kkatee** [comment]
Thanks that seems to be working fine :D
