### ISSUE TITLE
[BUG] ArkInventory is blocked in Valdrakken

### ISSUE THREAD

**Issue by Voydra** [arkayenro/arkinventory#1823]
**What version number you are using?**
3.10.17

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
I dont know what it causes, but warning appears on middle of screen saying: "ArkInventory has been blocked from an action..." (It is not blocked trully)

**To Reproduce**
When I log into any character thats in Valdrakken OR i go to Valdrakken with those characters the warning will appear

**Screenshots**
![image](https://github.com/arkayenro/arkinventory/assets/95168228/66fe2713-c173-4152-825a-cb798b724186)

**Additional context**
- This happens since this week's (weekly reset) patch OR MAX a few days earlier when a bigger sized patch arrived (Cant remember exactly)

**Comment by hollo6** [comment]
Happens to me too, started after Sep 20th patch.

**Comment by Turaide** [comment]
I have the same problem as OP. Not only in Valdrakken. It's happening anywhere in the Dragon Flight Expansion.

**Comment by arkayenro** [comment]
appears to be a wow client issue, something they "fixed" for a ClearTarget issue has broken a bunch of other stuff

**Comment by arkayenro** [comment]
see Stanzilla/WoWUIBugs#483

**Comment by arkayenro** [comment]
pretty sure blizzard has fixed this in 10.1.7
