### ISSUE TITLE
[BUG] White Bell Pigment shares same count as Dragon Isles Supplies

### ISSUE THREAD

**Issue by Betternyou** [arkayenro/arkinventory#1826]
**What version number you are using?**
3.10.17

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
When mousing over White bell pigment or Dragon Isles supplies. The count is shared between the two. 

**To Reproduce**
Steps to reproduce the behaviour, if possible: Mouse over the items.

**Screenshots**
![image](https://github.com/arkayenro/arkinventory/assets/146389567/5478fa68-3c65-4030-afdd-58e23fd80223)

**Additional context**
I can see in the tooltip that it says "Dragon Isle Supplies" but its not the same item.

**Comment by arkayenro** [comment]
the item is glitchy, its not meant to end up in your bags, its meant to convert to that currency upon looting
