### ISSUE TITLE
[BUG] Dragging item to custom category breaks it

### ISSUE THREAD

**Issue by Endor96** [arkayenro/arkinventory#1829]
**What version number you are using?**
3.10.18

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Creating a custom category and then dragging an item to the "add textbox" breaks the custom category so it no longer can be opened.
It seems like it perma breaks the category in that menu, can still add things in edit mode. Also breaks the entire category menu until reload.

**To Reproduce**
Steps to reproduce the behaviour, if possible:
>(see screenshots)
>-Create a custom category
>-Drag an item to the "add textbox"

**Screenshots**
https://i.imgur.com/zEzfiP0.png
https://i.imgur.com/1Z8eeSI.png

**Additional context**
BugSack error I think is related:
https://pastebin.com/JxaeykNT

Might help, dunno:
![NVIDIA_Share_j1fHKibivV](https://github.com/arkayenro/arkinventory/assets/7146223/1c592eec-18ee-4208-a078-649b30fc82a2)
After removing all of those entries from the saved variables it seems to be working properly again.

**Comment by arkayenro** [comment]
found the problem, will be fixed in the next alpha

did not expect people to drag items to there, but it will be able to handle that now

**Comment by arkayenro** [comment]
fixed in [3.10.24 alpha 4](https://www.curseforge.com/wow/addons/ark-inventory/files/5152761)
