### ISSUE TITLE
[BUG] ArkMount not selecting newer Dragonriding mounts

### ISSUE THREAD

**Issue by mrkag** [arkayenro/arkinventory#1835]
**What version number you are using?**
3.10.18

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
US English

**Describe the bug**
When using the ArkMount macro, newer Dragonriding mounts are never selected.  These include Algarian Stormrider, Winding Slitherdrake, Grotto Netherwing Drake, and Flourishing Whimsydrake.

Anu'relos may have the issue as well, but I don't own the mount.

**To Reproduce**
Own the above listed mounts
Be in the Dragon Isles zone
Click the ArkMount button several times
Observe that the above listed mounts are never selected

**Additional context**
The mounts also do not show up on the Flying tab of the Mounts configuration screen.

**Comment by arkayenro** [comment]
try the latest alpha version, should be fixed in there

**Comment by mrkag** [comment]
The alpha works like a charm.  Thank you!
