### ISSUE TITLE
[BUG] Arrangement/dead space

### ISSUE THREAD

**Issue by Fred-IV** [arkayenro/arkinventory#1836]
**What version number you are using?**
v31018 Alpha 7

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail, Dragonflight, Live.

**What language is the game client set to?**
English

**Describe the bug**
Item arrangement. Dead space.
See screen capture.
There's a ton of dead space, and I can't figure out a way to fix it.
Is this a bug? Or am I missing something.
I would think it should be automatic.

Also, if I right-click a section, and use "sent to bank", it never works.

**To Reproduce**
Steps to reproduce the behavior, if possible:
See above.

**Screenshots**
![WoWScrnShot_112423_030742](https://github.com/arkayenro/arkinventory/assets/66499758/13ae2e2a-e578-4704-b649-0e778cafb4be)

**Additional context**

**Comment by MrUzagi** [comment]
There is an option for a compact view. However I'm currently at work though so I can't check exactly where the setting is.

**Comment by arkayenro** [comment]
its not a bug, its the default so that things tend to stay in the same location.  you can enable compact mode and it will move things around to fill up the space as much as possible.

you could also decrease the window width to obtain a similar result, albeit a taller one.

**Comment by MrUzagi** [comment]
The option for compact view is in Config: Settings -> Design (Styles / Layouts) -> Bars -> General
![image](https://github.com/arkayenro/arkinventory/assets/21023158/08e6453b-21fd-4554-ab9f-2ed1a544bd3b)

**Comment by Fred-IV** [comment]
THANK YOU!
That was driving me nuts.
I looked for that setting so many times, I didn't think it existed.
