### ISSUE TITLE
[BUG] Loading Error - CollectionMount

### ISSUE THREAD

**Issue by Aronus1973** [arkayenro/arkinventory#1838]
**What version number you are using?**
3.10.19

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Wrath

**What language is the game client set to?**
German

**Describe the bug**
13x ...ns/ArkInventory/Core/ArkInventoryCollectionMount.lua:1804: attempt to index global 'MountJournal' (a nil value)
[string "@ArkInventory/Core/ArkInventoryCollectionMount.lua"]:1804: in function <...ns/ArkInventory/Core/ArkInventoryCollectionMount.lua:1787>
[string "=[C]"]: ?
[string "@ArkInventory/Externals/Ace3/AceBucket/AceBucket-3.0-4.lua"]:69: in function <...Inventory/Externals/Ace3/AceBucket/AceBucket-3.0.lua:67>
[string "@ArkInventory/Externals/Ace3/AceBucket/AceBucket-3.0-4.lua"]:83: in function `func'
[string "@DataStore/libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
self = <table> {
 StartupChecks = <function> defined @ArkInventory/Core/ArkInventory.lua:12309
 Action = <table> {
 }
 Frame_Item_PreClick = <function> defined @ArkInventory/Core/ArkInventory.lua:8904
 EVENT_ARKINV_BANK_TAB = <function> defined @ArkInventory/Core/ArkInventoryStorage.lua:777
 HookOpenAllBags = <function> defined @ArkInventory/Core/ArkInventory.lua:10964
 modules = <table> {
 }
 MenuSwitchLocationOpen = <function> defined @ArkInventory/Core/ArkInventoryMenu.lua:3043
 TooltipCustomBattlepetAddDetail = <function> defined @ArkInventory/Core/ArkInventoryTooltip.lua:650
 Frame_Bar_Edit_OnReceiveDrag = <function> defined @ArkInventory/Core/ArkInventory.lua:7004
 ObjectInfoItemString = <function> defined @ArkInventory/Core/ArkInventoryObject.lua:887
 EVENT_ARKINV_BACKPACK_TOKEN_UPDATE = <function> defined @ArkInventory/Core/ArkInventoryStorage.lua:648
 TooltipValidateDataFromSetQuestLogRewardSpell = <function> defined @ArkInventory/Core/ArkInventoryTooltip.lua:1803
 LocationMonitorChanged = <function> defined @ArkInventory/Core/ArkInventory.lua:12131
 GetItemTinted = <function> defined @ArkInventory/Core/ArkInventoryStorage.lua:2156
 ItemAgeGet = <function> defined @ArkInventory/Core/ArkInventory.lua:12263
 Frame_Changer_Slot_Update = <function> defined @ArkInventory/Core/ArkInventory.lua:10679
 LocationOverrideSet = <function> defined @ArkInventory/Core/ArkInventory.lua:12681
 ConfigInternalCategoryGet = <function> defined @ArkInventory/Core/ArkInventoryConfig.lua:448
 Frame_Bag_OnLoad = <function> defined @ArkInventory/Core/ArkInventory.lua:7141
 BlizzardBagIdToInternalId = <function> defined @ArkInventory/Core/ArkInventoryStorage.lua:1730
 EVENT_ARKINV_OBLITERUM_LEAVE = <function> defined @ArkInventory/Core/ArkInventoryStorage.lua:1527
 EVENT_ARKINV_LOCATION_DRAW_BUCKET = <function> defined @ArkInventory/Core/ArkInventoryStorage.lua:447
 db = <table> {
 }
 MenuLDBTrackingReputationListOptions = <function> defined @ArkInventory/Core/ArkInventoryMenu.lua:4146
 isLocationSaved = <function> defined @ArkInventory/Core/ArkInventory.lua:12152
 MediaFrameFontSet = <function> defined @ArkInventory/Core/ArkInventoryMedia.lua:159
 Frame_Item_GetDB = <function> defined @ArkInventory/Core/ArkInventory.lua:7271
 Frame_Main_Paint = <function> defined @ArkInventory/Core/ArkInventory.lua:4280
 ConfigInternalCategoryActionPurge = <function> defined @ArkInventory/Core/ArkInventoryConfig.lua:800
 HookToggleBackpack = <function> defined @ArkInventory/Core/ArkInventory.lua:10888
 ScanWearing_Threaded = <function> defined @ArkInventory/Core/ArkInventoryStorage.lua:3033
 HookCloseAllBags = <function> defined @ArkInventory/Core/ArkInventory.lua:11161
 MoneyFrame_Tooltip = <function> defined @ArkInventory/Core/ArkInventoryMoney.lua:495
 EVENT_ARKINV_COLLECTION_HEIRLOOM_UPDATE = <function> defined @ArkInventory/Core/ArkInventoryCollectionHeirloom.lua:194
 ConfigInternalCategoryCustomRestore = <function> defined @ArkInventory/Core/ArkInventoryConfig.lua:521
 EVENT_ARKINV_QUEST_UPDATE_BUCKET = <function> defined @ArkInventory/Core/ArkInventoryStorage.lua:1607
 ObjectInfoQuality = <function> defined @ArkInventory/Core/ArkInventoryObject.lua:902
 UnregisterAllEvents = <function> defined @DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 ScanWearing = <function> defined @ArkInventory/Core/ArkInventoryStorage.lua:3001
 ScanVault = <function> defined @ArkInventory/Core/ArkInventoryStorage.lua:2734
 Frame_Changer

**Comment by Cabro** [comment]
Same error for english client wotlk

**Comment by arkayenro** [comment]
please try 3.10.19 alpha 1

**Comment by Aronus1973** [comment]
With the new Alpha version, the bug is fixed
