### ISSUE TITLE
[BUG] Long loading times when used in conjunction with WeakAuras

### ISSUE THREAD

**Issue by cdmichaelb** [arkayenro/arkinventory#1839]
**What version number you are using?**
3.10.19

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Classic

**What language is the game client set to?**
English

**Describe the bug**
When loading wow benchmarking addon load time ArkInventory has a pretty impressive 0.102s, 0.005s, and 0.003s load time. But it causes Weakauras to have a 1.555second load time. Disabling ArkInventory returns WeakAuras to a 0.071s load time.

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Use Warmup addon (curseforge) to benchmark addon load times. Enable ArkInventory alongside WeakAuras.

**Additional context**
Link to [Warmup](https://www.curseforge.com/wow/addons/warmup)

ArkInventory is my favorite bag addon and no other's compare, but the fact that it interacts poorly with WeakAuras forces me to not use it, because as nice as ArkInventory is, WeakAuras is essential in modern (classic) wow.

**Comment by arkayenro** [comment]
i dont use weak auras so i'd have to go through it to see what its doing.

its most likely because im force loading a lot of blizzard addons up front that normally only load when you open them (bank, void, tradeskills/professions, collections, auctions).  it might cause wa to need to do more stuff during load time.

**Comment by arkayenro** [comment]
eg check your warmup results when arkinventory is NOT loaded and see if any of these are in there
Blizzard_Collections
Blizzard_Professions
Blizzard_TradeSkillUI
Blizzard_GuildBankUI
Blizzard_VoidStorageUI

then load arkinventory as well and see which ones are in there now.

if weak auras hooks into any of those then it will need to initialise whatever it needs to, to support those addins which will take more time.

**Comment by arkayenro** [comment]
tested and its not those, but i can force weakauras to load before arkinventory and it seems to fix the issue

with the game shut down
edit your `ArkInventory_Vanilla.toc` file
find the line that starts with `## OptionalDeps:`
add `, WeakAuras` to the end of it

load the game

**Comment by arkayenro** [comment]
fixed in 3.10.20
