### ISSUE TITLE
Error when opening Character sheet

### ISSUE THREAD

**Issue by Goofy1807** [arkayenro/arkinventory#1843]
**What version number you are using?**
v31019 [Classic]

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Classic SoD

**What language is the game client set to?**
German

**Describe the bug**
When pressing C or opening the Character Menu via the Taskbar, the following Error occurs:

"WARNING> code issue - function for [HookOpenAllBags:EngravingFrame] was not found - please notify the author so it can be fixed"

**To Reproduce**
Open the Character Menu on a german client with the following Addons active:

"ArkInventory v31019 [Classic]"
"Leatrix Maps Classic 1.15.04"
"Questie v.9.0.4"
"RareScanner 1.15.0.4"

**Screenshots**
https://snipboard.io/Inplsz.jpg

**Additional context**
The Bags do open, even with the error

**Comment by arkayenro** [comment]
see #1841 and download the latest alpha
