### ISSUE TITLE
[BUG] ScrollBoxListView • un-trackable w/ bugsack

### ISSUE THREAD

**Issue by Latinx** [arkayenro/arkinventory#1844]
**What version number you are using?**
3.10.19

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

Here is my bugsack log. It mentions no addons at all.

---------------------------------------------------

132x SharedXML/Scroll/ScrollBoxListView.lua:628: attempt to perform arithmetic on a nil value
[string "@SharedXML/Scroll/ScrollBoxListView.lua"]:628: in function <SharedXML/Scroll/ScrollBoxListView.lua:587>
[string "=(tail call)"]: ?
[string "@SharedXML/Scroll/ScrollBoxListView.lua"]:831: in function `ValidateDataRange'
[string "@SharedXML/Scroll/ScrollBox.lua"]:708: in function `Update'
[string "@SharedXML/Scroll/ScrollBox.lua"]:258: in function `SetScrollPercentageInternal'
[string "@SharedXML/Scroll/ScrollBox.lua"]:250: in function `SetScrollPercentage'
[string "@SharedXML/Scroll/ScrollBox.lua"]:242: in function `ScrollToEnd'
[string "@Blizzard_Professions/Blizzard_ProfessionsCraftingOutputLog.lua"]:369: in function `FinalizePendingResultData'
[string "@Blizzard_Professions/Blizzard_ProfessionsCraftingOutputLog.lua"]:317: in function <professions/Blizzard_ProfessionsCraftingOutputLog.lua:313>

---------------------------------------------------

I love ark. the rules and custom categories are an absolute necessity. Not sure how I can move forward w/o them.

**Comment by arkayenro** [comment]
im not getting it so possibly from another mod - did you do this with only arkinventory loaded?

**Comment by arkayenro** [comment]
all good, im just happy i dont have to try and debug that one.

its got profession/crafting code in there so its possibly related to a profession mod of some sort?

**Comment by Latinx** [comment]
Good evening! I have an update.

I decided to follow [Resetting the WoW Interface](https://us.battle.net/support/en/article/7549) albeit temporarily.
On a fresh install with Bugsack, Buggrabber and ArkInventory I can get it to throw this error.

It has to do with the use of temporary weapon enhancements Like [Hissing Rune](https://www.wowhead.com/item=204973/hissing-rune) or [Completely Safe Rockets](https://www.wowhead.com/item=198162/completely-safe-rockets).

I really hope this information comes of some use. Maybe you can try one of these item enhancements out and see if you toss an error on your end.

Thank you for your time

**Comment by arkayenro** [comment]
see #1840
