### ISSUE TITLE
[BUG] Looting currencies gives error in chat

### ISSUE THREAD

**Issue by Cabro** [arkayenro/arkinventory#1850]
**What version number you are using?**
31022 wotlk

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
wotlk

**What language is the game client set to?**
enUS

**Describe the bug**
![image](https://github.com/arkayenro/arkinventory/assets/1155017/55d23d10-2646-4e80-b583-9fd744876c9c)

**To Reproduce**
Steps to reproduce the behaviour, if possible:
kill a boss in dungeon/raid

**Additional context**
Started with latest version, wasn't popping until this

**Comment by arkayenro** [comment]
wrath api is so damned inconsistent.

will be fixed in the next alpha
