### ISSUE TITLE
[BUG] Getting warning about being in combat (spam)

### ISSUE THREAD

**Issue by Cabro** [arkayenro/arkinventory#1851]
**What version number you are using?**
31022 wrath

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
wotlk

**What language is the game client set to?**
enUS

**Describe the bug**
Some quests you have to interact while in combat. The addon gives you a spam warning about this. I usually comment it out in the code, but it's really unnecessary and it might put off people from using the addon due to this spam. Also it's missing the intro `<` for `<WARNING>`
Also i could open the interact window just fine.

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Right click an NPC while in combat.

**Screenshots**
![image](https://github.com/arkayenro/arkinventory/assets/1155017/16856082-d989-4f6a-bdb8-1c2780880356)

**Additional context**
Been present for the last 2-3 revisions.

**Comment by arkayenro** [comment]
will be removed in the next alpha
