### ISSUE TITLE
LUA error in chat on rep gain/change

### ISSUE THREAD

**Issue by DaveB1977** [arkayenro/arkinventory#1854]
**What version number you are using?** 3.10.22

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta** Retail

**What language is the game client set to?** English

**Describe the bug**
An LUA error only in chat, bugsack does not hook it. 

**To Reproduce**
gain rep

**Screenshots**
![image](https://github.com/arkayenro/arkinventory/assets/52803773/79d53143-d6f9-4e39-8556-ebc7fbec5eeb)

**Additional context**
N/A

**Comment by arkayenro** [comment]
see #1852 

should have been fixed in alpha 1
