### ISSUE TITLE
[BUG] TRADE_SKILL_ITEM_CRAFTED_RESULT error on initial login

### ISSUE THREAD

**Issue by Cabro** [arkayenro/arkinventory#1858]
**What version number you are using?**
31023 wrath

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
wrath

**What language is the game client set to?**
enUS

**Describe the bug**
You're getting an error on login.

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Just login.

**Screenshots**
![image](https://github.com/arkayenro/arkinventory/assets/1155017/361dae19-8fc5-47a5-818f-218db16feabc)

**Additional context**
New error with 31023wrath.

**Comment by arkayenro** [comment]
duplicate #1855

**Comment by Cabro** [comment]
Alright!
