### ISSUE TITLE
[BUG] Some keys no longer work. they show a popup 

### ISSUE THREAD

**Issue by thisisu** [arkayenro/arkinventory#1861]
**What version number you are using?**

3.10.24

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**

Retail

**What language is the game client set to?**

English

**Describe the bug**
1x ...aceArkInventory/Core/ArkInventoryTooltip.lua:1901: attempt to index field 'tooltip' (a nil value)
[string "@ArkInventory/Core/ArkInventoryTooltip.lua"]:1901: in function `HookOnTooltipSetUnit'
[string "@ArkInventory/Core/ArkInventoryTooltip.lua"]:3085: in function <...aceArkInventory/Core/ArkInventoryTooltip.lua:3084>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:162: in function <SharedXML/Tooltip/TooltipDataHandler.lua:157>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:182: in function <SharedXML/Tooltip/TooltipDataHandler.lua:178>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:218: in function <SharedXML/Tooltip/TooltipDataHandler.lua:208>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:243: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:389: in function <SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function <SharedXML/Tooltip/TooltipDataHandler.lua:335>
[string "=(tail call)"]: ?
[string "@Details/classes/container_actors.lua"]:185: in function `GetPetOwner'
[string "@Details/classes/container_actors.lua"]:755: in function `GetOrCreateActor'
[string "@Details/classes/class_damage.lua"]:6910: in function `AddToCombat'
[string "@Details/classes/class_combat.lua"]:936: in function <Details/classes/class_combat.lua:918>
[string "@Details/classes/container_segments.lua"]:204: in function `AddToOverallData'
[string "@Details/classes/container_segments.lua"]:493: in function <Details/classes/container_segments.lua:339>
[string "=(tail call)"]: ?
[string "@Details/core/control.lua"]:748: in function <Details/core/control.lua:475>
[string "=[C]"]: in function `xpcall'
[string "@Details/core/parser.lua"]:6430: in function <Details/core/parser.lua:6343>

Locals:
tooltip = DetailsPetOwnerFinder {
 0 = <userdata>
 SetQuestPartyProgress = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 processingInfo = <table> {
 }
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:410
 infoList = <table> {
 }
 waitingForData = false
 SetAzeriteEssenceSlot = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRuneforgeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 HasDataInstanceID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:514
 SetUnit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetTotem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetVoidWithdrawalItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 updateTooltipTimer = 0.200000
 StatusBar = DetailsPetOwnerFinderStatusBar {
 }
 SetInfoBackdropStyle = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:492
 SetBuybackItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetPrimaryTooltipData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:499
 SetSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 TextRight1 = DetailsPetOwnerFinderTextRight1 {
 }
 SetEnhancedConduit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 RefreshData = <function> defined @FrameXML/GameTooltip.lua:1055
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetSlottedKeystone = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:1074
 SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetPetAction = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:1112
 SetOwnedItemByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetItemKey = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 supportsDataRefresh = true
 SetEquipmentSet = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRecipeReagentItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetQuestCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetTransmogrifyItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWeeklyReward = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetPvpBrawl = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetUnit = <function> defined @FrameXML/GameTooltip.lua:1116
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 OnLoad = <function> defined @FrameXML/GameTooltip.lua:1049
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:335
 ProcessLines = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:400
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetCompanionPet = <function> defined @SharedXML/Tooltip/TooltipDataHandle

**To Reproduce**
Steps to reproduce the behaviour, if possible:

**Screenshots**

**Additional context**

**Comment by arkayenro** [comment]
the error message appears to indicate that the saved variables havent been loaded yet but somehow the arkinventory tooltip code got called.

the subject makes no sense in context with that though as you should have been mousing over a pet or battlepet for that function to run, so more information would be helpful.

**Comment by thisisu** [comment]
I think I had the wrong add on here. Feel free to close. Thanks for reading
