### ISSUE TITLE
[BUG] Error when trying to use toys while a profession window is open.

### ISSUE THREAD

**Issue by thisisu** [arkayenro/arkinventory#1866]
**What version number you are using?**
3.10.24

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**

``
1x [ADDON_ACTION_FORBIDDEN] AddOn 'ArkInventory' tried to call the protected function 'UseToy()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseToy'
[string "@Blizzard_Collections/Blizzard_ToyBox.lua"]:181: in function `ToySpellButton_OnClick'
[string "*Blizzard_ToyBox.xml:10_OnClick"]:4: in function <[string "*Blizzard_ToyBox.xml:10_OnClick"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}
``

**To Reproduce**
Go to an Alchemist's Lab Bench. Use bench. With the bench still open, open Hierlooms, visit Toy Box tab. Try to launch use toy. Pretty much all of them work. Ai-Li's Skymirror, Aqua Jewel, Katy's Stampwhistle, etc...

**Screenshots**

![WoWScrnShot_022024_175240](https://github.com/arkayenro/arkinventory/assets/35790653/59380c80-dcfa-4a68-898f-d30946c09818)

**Additional context**

**Comment by arkayenro** [comment]
could you disable arkinventory and test it again?

i dont call UseToy() in my code as its protected, its probably another mod using the same shared ace3 libraries (which will blame me because i typically load them first)

**Comment by thisisu** [comment]
Yep will try it and let you know

**Comment by thisisu** [comment]
Can no longer reproduce. There were some updates to other addons. It was probably one of those as the culprit. Thanks
