### ISSUE TITLE
Can't change the background color of any item bar

### ISSUE THREAD

**Issue by anteos59** [arkayenro/arkinventory#1867]
**What version number you are using?**
v31024 [Dragonflight]

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
German

**Describe the bug**
I cannot change the background color of any bar. The colorpicker isn't even showing. Bugsack is showing a lua error in ArkDevdrop.lua 706: attempt to call method 'SetColorRGB' (a nil value)

**To Reproduce**
go into edit mode, right click any bar, select color / background / color (but it also happens with border or name instead of background)

**Screenshots**

**Additional context**
Here is the whole Bugsack-Message:
23x ...eArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:706: attempt to call method 'SetColorRGB' (a nil value)
[string "@ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua"]:706: in function <...eArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:670>

Locals:
self = Button {
 0 = <userdata>
 textHeight = 16
 checked = false
 b = 0.400000
 opacity = 0.400000
 radioHighlight = Texture {
 }
 colorSwatch = Texture {
 }
 level = Button {
 }
 hasArrow = false
 r = 0
 highlight = Texture {
 }
 text = FontString {
 }
 tooltipText = "set the colour to use for the background of bar 38"
 disabled = false
 hasOpacity = true
 hasColorSwatch = true
 arrow = Texture {
 }
 check = Texture {
 }
 colorFunc = <function> defined @ArkInventory/Core/ArkInventoryMenu.lua:820
 g = 0
 tooltipTitle = "Farbe"
}
func = <function> defined @ArkInventory/Core/ArkInventoryMenu.lua:820
hasOpacity = true
self = Button {
 0 = <userdata>
 textHeight = 16
 checked = false
 b = 0.400000
 opacity = 0.400000
 radioHighlight = Texture {
 }
 colorSwatch = Texture {
 }
 level = Button {
 }
 hasArrow = false
 r = 0
 highlight = Texture {
 }
 text = FontString {
 }
 tooltipText = "set the colour to use for the background of bar 38"
 disabled = false
 hasOpacity = true
 hasColorSwatch = true
 arrow = Texture {
 }
 check = Texture {
 }
 colorFunc = <function> defined @ArkInventory/Core/ArkInventoryMenu.lua:820
 g = 0
 tooltipTitle = "Farbe"
}
(*temporary) = nil
(*temporary) = ColorPickerFrame {
 0 = <userdata>
 GetColorRGB = <function> defined @FrameXML/ColorPickerFrame.lua:79
 DragBar = Frame {
 }
 OnKeyDown = <function> defined @FrameXML/ColorPickerFrame.lua:53
 SetupColorPickerAndShow = <function> defined @FrameXML/ColorPickerFrame.lua:62
 OnLoad = <function> defined @FrameXML/ColorPickerFrame.lua:3
 opacity = 0.600000
 GetExtraInfo = <function> defined @FrameXML/ColorPickerFrame.lua:87
 GetPreviousValues = <function> defined @FrameXML/ColorPickerFrame.lua:91
 OnShow = <function> defined @FrameXML/ColorPickerFrame.lua:34
 hasOpacity = true
 GetColorAlpha = <function> defined @FrameXML/ColorPickerFrame.lua:83
 Header = Frame {
 }
 Footer = Frame {
 }
 func = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:687
 Border = Frame {
 }
 Content = Frame {
 }
 opacityFunc = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:687
}
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0.400000
(*temporary) = "attempt to call method 'SetColorRGB' (a nil value)"
button = Button {
 0 = <userdata>
 textHeight = 16
 checked = false
 b = 0.400000
 opacity = 0.400000
 radioHighlight = Texture {
 }
 colorSwatch = Texture {
 }
 level = Button {
 }
 hasArrow = false
 r = 0
 highlight = Texture {
 }
 text = FontString {
 }
 tooltipText = "set the colour to use for the background of bar 38"
 disabled = false
 hasOpacity = true
 hasColorSwatch = true
 arrow = Texture {
 }
 check = Texture {
 }
 colorFunc = <function> defined @ArkInventory/Core/ArkInventoryMenu.lua:820
 g = 0
 tooltipTitle = "Farbe"
}
tmpt = <table> {
}
lib = <table> {
 Close = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:3004
 AddSeparator = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:3040
 OnTooltipHide = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:3369
 AddLine = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:3053
 argCheck = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:3491
 error = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:3518
 SetStandardFont = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:34
 IsOpen = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:2727
 GetOpenedParent = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:2732
 hookedTooltip = true
 IsRegistered = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:2894
 Refresh = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:1900
 Open = <fu

**Comment by verpixelt** [comment]
I'm getting the exact same error.

**Comment by arkayenro** [comment]
should be fixed in [3.10.24-alpha-3](https://www.curseforge.com/wow/addons/ark-inventory/files/5150232)

**Comment by anteos59** [comment]
Yes it's fixed, thanks alot
