### ISSUE TITLE
EquipLocation [INVTYPE_NON_EQUIP_IGNORE] not coded.

### ISSUE THREAD

**Issue by Crelam** [arkayenro/arkinventory#1871]
**What version number you are using?**
3.1025 (Dragonflight)

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Live

**What language is the game client set to?**
English

**Describe the bug**
Lots of my bars are empty, like everything been filtered out.

Also receiving message:
ArkInventory: WARNING> EquipLocation [INVTYPE_NON_EQUIP_IGNORE] not coded, please let the author know.

**To Reproduce**
Steps to reproduce the behaviour, if possible:
I just loaded into the game and saw that warning spamming my chatbox. 😅 

**Screenshots**

**Additional context**

**Comment by LilliCat** [comment]
![Untitled](https://github.com/arkayenro/arkinventory/assets/13368475/bab90fb3-55f1-4240-8fad-b816ab178047)

Same issue on live retail. In addition, many "non-equipment" items (consumables, herbs, meat, ores, etc) and in this example, Swiftthistle is incorrectly being assigned

**Comment by ImUnicke** [comment]
This was not an issue in `v31024` (or at least prior to 10.2.6 Retail patch).
But reverting to this version retains the same issue.

**Comment by ImUnicke** [comment]
Oh no, I think Blizz broke their `GetItemInfo` API 😩
It's now returning the `INVTYPE_NON_EQUIP_IGNORE` instead of one of these values https://warcraft.wiki.gg/wiki/Enum.InventoryType

**Comment by ImUnicke** [comment]
`v31026` fixes the chat error spam due to the missing item equip type, but the default Item category choices are mostly wrong still. Tons of Items are now default-categorized as Equipment [(Soulbound)] whereas they were previously Recipes/Potions/Consumables/etc.

**Comment by arkayenro** [comment]
yeah, it looked ok but there were some oddities that i missed.  just trying to work out the best way to fix it forever

**Comment by arkayenro** [comment]
should be properly fixed in [3.10.27](https://www.curseforge.com/wow/addons/ark-inventory/files/5196891)

**Comment by ImUnicke** [comment]
Item default categories seem back to normal in `v31027`.

Think this issue can be closed.

**Comment by Sandrock431** [comment]
This issue seems to be back with patch 10.2.7, running addon version `3.10.29`

![image](https://github.com/arkayenro/arkinventory/assets/42790049/044be11a-9153-4abd-af6e-24ac364439d7)
