### ISSUE TITLE
[BUG] Inventory content is displayed twice

### ISSUE THREAD

**Issue by AlexL1118** [arkayenro/arkinventory#1875]
**What version number you are using?**
v3.10.27-alpha-6.

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail live.

**What language is the game client set to?**
English.

**Describe the bug**
Attempt to open inventory leads to showing its content correctly, but then the whole window is filled by background, and then its content is shown second time (also correctly).
In other words, showing inventory bags is happening using 3 steps:
- Correct showing the inventory (all items).
- Wiping the graphical content and filling the whole window by background.
- Showing the corrent inventory content again.

Such kind of blinking is annoying.
Same problem happens also with other inventories, e.g. with bank window.
I tried to go back by versions, and I found that the problem happens in all versions starting from v3.10.27-alpha-2.
So I had to return to v3.10.27-alpha-1 where this bug does not happen.

**To Reproduce**
Open bags.

**Additional context**
It seems that the situation slightly depends on number of bags. Or, maybe, on number of items in the inventory.
E.g., when I try to reproduce the problem with an alt who has only backpack and does not have additional bags, I see a bit different situation: the first step is omitted, and I see only filling the bag window with background, and then filling the bag window by the items. This is also a kind of blinking, but only with 2 filling steps instead of 3.

The problem happens even if only ArkInventory is enabled among all addons.

**Comment by arkayenro** [comment]
should be fixed in the next alpha

**Comment by AlexL1118** [comment]
Indeed, fixed.
