### ISSUE TITLE
[BUG] Category, Display or Sorting Issue??

### ISSUE THREAD

**Issue by Dekkysaurus** [arkayenro/arkinventory#1877]
**What version number you are using?**
10.2.6

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Ark is causing inventory to stack as a long vertical list. I've tried to fix this using the sorting options (size, padding, etc) and adding categories  but it doesn't fix the issue. I have uninstalled and reinstalled multiple times. This is how it looks after every reinstall.

![ark1](https://github.com/arkayenro/arkinventory/assets/168304608/cc30b935-e1ee-4522-93ee-7db1da186345)

**Comment by arkayenro** [comment]
not a bug, you have it set to list view (which isnt the default).

open the config, click on settings, under general untick the "display as list" option

you will need to do that for the design that applies to that location - or all of them if you dont remember which one that is and you dont want list view anyway.
