### ISSUE TITLE
[BUG] Error displayed lua212

### ISSUE THREAD

**Issue by thisisu** [arkayenro/arkinventory#1879]
**What version number you are using?**

3.10.27 (20-MAR-2024)

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**

Retail

**What language is the game client set to?**
English

**Describe the bug**
Error shown in chat. See screenshot below

**To Reproduce**
What I did was visit tab 2 of my guild bank, and dragged 40 rank 3 dreamwalker's healing potions out of it and into my bags.

**Screenshots**
![image](https://github.com/arkayenro/arkinventory/assets/35790653/b1275057-daa0-4156-abba-19734d9f2c60)
**Additional context**

**Comment by arkayenro** [comment]
i've added some extra logic around it to stop the error.  will be in the next alpha.

it shouldnt cause any actual issue though, just mucks up the tooltip until it sorts itself out.
