### ISSUE TITLE
[BUG]  Missing entry for 'WOW_TOOLTIP_ITEM_CONTAINER_SLOTS' error after Loading the character . 

### ISSUE THREAD

**Issue by landre-cerp** [arkayenro/arkinventory#1880]
**What version number you are using?**

3.10.28

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**

Retail

**What language is the game client set to?**
FR 

**Describe the bug**
Just after login. 

Message: AceLocale-3.0: ArkInventory: Missing entry for 'WOW_TOOLTIP_ITEM_CONTAINER_SLOTS'
Time: Tue Apr 30 12:53:37 2024
Count: 1
Stack: AceLocale-3.0: ArkInventory: Missing entry for 'WOW_TOOLTIP_ITEM_CONTAINER_SLOTS'
[string "=(tail call)"]: ?
[string "@Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua"]:152: in function <...dOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:150>
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceLocale/AceLocale-3.0.lua"]:27: in function <...Inventory/Externals/Ace3/AceLocale/AceLocale-3.0.lua:25>
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryObject.lua"]:247: in function <...face/AddOns/ArkInventory/Core/ArkInventoryObject.lua:94>
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryObject.lua"]:894: in function `GetObjectInfo'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryStorage.lua"]:2328: in function `ScanBag_Threaded'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryStorage.lua"]:2254: in function <...ace/AddOns/ArkInventory/Core/ArkInventoryStorage.lua:2252>

Locals: 

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Disabled all addons except Arkinventory and logged a character. 

**Screenshots**

**Additional context**
Happens with all addons deactivated except Arkinventory.

**Comment by arkayenro** [comment]
can you put these in the chat and let me know what the output is

`/dump CONTAINER_SLOTS`
`/dump ArkInventory.Localise["WOW_TOOLTIP_ITEM_CONTAINER_SLOTS"]`

**Comment by landre-cerp** [comment]
![image](https://github.com/arkayenro/arkinventory/assets/49897630/b3324b34-6ba9-43e6-abb0-cd2932029d67)

**Comment by arkayenro** [comment]
ah, the french value is using a conditional format to handle plurals.  the english version doesnt, its just "%d slot %s" (1 slot bag) so doesnt need a conditional format.

will be fixed in the next release.

**Comment by landre-cerp** [comment]
Affirm 
![image](https://github.com/arkayenro/arkinventory/assets/49897630/d16e23ac-1b0d-45d8-8888-c6171a6f3cf3)

**Comment by arkayenro** [comment]
try [3.10.28-alpha-1](https://www.curseforge.com/wow/addons/ark-inventory/files/5306004)
