### ISSUE TITLE
Cata Classic - Alpha

### ISSUE THREAD

**Issue by volostyle** [arkayenro/arkinventory#1881]
Hi, I'm currently using the latest alpha build, and I get this LUA upon entering the game. The addon still works though:

43x ArkInventory/ArkInventory.toc:40 Duplicate File Load Detected. [ArkInventory/Libs/LibDataBroker/lib.xml] first loaded at [ArkInventory/ArkInventoryExternals.xml:6]

**Comment by arkayenro** [comment]
i presume it means there are multiple other mods using the data broker library

for the moment just ignore it unless youre having any actual issues as it appears to only be in the cata beta so its possibly something blizzard have changed and not told anyone about yet

**Comment by tholo** [comment]
FWIW I see it in Cata pre-patch.

**Comment by arkayenro** [comment]
as far as im aware the only way i could think of to stop if from happening would be to use the non-embedded lib versions of each mod and install all those libraries separately.  i cant see users being overly happy to do that.

**Comment by volostyle** [comment]
What's actually causing it though? Other addons just not being updated yet?

**Comment by arkayenro** [comment]
normally we embed all the libraries we need in case the user hasnt installed them, theres a no-lib version of the mod that doesnt have any of the libraries and its up to the user to install them.

so basically every mod that has an ldb object they want displayed, embeds the data broker library so the same library files get loaded over and over.

it appears that blizzard is now calling that out and treating it as an error for some reason.

**Comment by volostyle** [comment]
Looks like your latest release fixed this issue? I'm not getting that LUA anymore when entering the game.
