### ISSUE TITLE
optionally hide certain bag types in the ldb bag object and status frame

### ISSUE THREAD

**Issue by Galeia** [arkayenro/arkinventory#1882]
Version number : 3.10.28
Game client : Retail
Language set to : french
LDB : Bazooka v3.0.10

Hello
Is there a way to hide the regents number in the LDB ? I don't mind hiding it totally even in my bags window

![2024-05-01 18_42_19-World of Warcraft](https://github.com/arkayenro/arkinventory/assets/168665561/ffe1a98d-c427-4598-a9ba-a6b71067e2e3)

**Comment by arkayenro** [comment]
for the bag text: config > settings > window > style > status

for the ldb: right click on the text in the ldb bar > ldb

neither will currently let you hide the individual bag types but i can add that in

**Comment by Galeia** [comment]
It would be great. But if it is too much of a hassle, don't bother if I am
the only request of the kind you had.
Thank you again.

**Comment by arkayenro** [comment]
the code change was simple, setting up the config and menu options took longer.

try [3.10.28-alpha-2](https://www.curseforge.com/wow/addons/ark-inventory/files/5309736)
