### ISSUE TITLE
TOC Bump for Cata Pls

### ISSUE THREAD

**Issue by Jorvanus** [arkayenro/arkinventory#1884]
Not urgent, but just flagging it.

**Comment by arkayenro** [comment]
new cata toc files are in [3.10.28-alpha-3](https://www.curseforge.com/wow/addons/ark-inventory/files/5312534)

**Comment by Jorvanus** [comment]
I can't get curse/wowup to see the alpha as for Cata, and it still shows as out of date in game too.

**Comment by arkayenro** [comment]
the toc files have 4.4.0 which is cataclysm classic.

the beta is 4.4.0

if the alpha is running something higher i cant cater for it, just allow out of date addons

**Comment by arkayenro** [comment]
nvm, worked out what you meant.  the packager isnt handling cataclysm. will sort it out shortly

**Comment by Jorvanus** [comment]
> nvm, worked out what you meant. the packager isnt handling cataclysm. will sort it out shortly

This is fixed, cheers

**Comment by arkayenro** [comment]
should be fixed in [3.10.28-alpha-4](https://www.curseforge.com/wow/addons/ark-inventory/files/5314266)
