### ISSUE TITLE
Restack feature no longer sorts items into profession bags

### ISSUE THREAD

**Issue by Kathos7** [arkayenro/arkinventory#1885]
Version 3.1.29

Cata Prepatch

English

Restack feature no longer properly condenses/moves items that can be put in specific profession bags from general bags

Maybe I am recalling incorrectly but it used to automatically sort the items into the profession bags if eligible. 

Additionally it used to condense as many items as possible into a single bag before filling the next. 

The restack feature now appears to only condense stacks

**Comment by arkayenro** [comment]
right click on the restack icon and make sure the priority is set to profession bags not reagent bank

**Comment by arkayenro** [comment]
also make sure its set to restack type arkinventory.  if its set to blizzard then thats just a blizzard cleanup that i have no control over

**Comment by Kathos7** [comment]
I double checked this setting and it was correct. 
![Screenshot_151](https://github.com/arkayenro/arkinventory/assets/169167625/bf00732f-722d-4ad3-8589-be7a7380f981)

However there is no priority setting there. 

after a restack:

![Screenshot_152](https://github.com/arkayenro/arkinventory/assets/169167625/7de9bf55-b34a-4ce4-970a-7848b931f143)

**Comment by arkayenro** [comment]
of, cata.  you dont get a reagent bank until warlords.

and its defaulted to the reagent bank, which wont help in cata.

i'll need to fix that somehow

**Comment by arkayenro** [comment]
fixed in 3.10.30

**Comment by seppelinchen** [comment]
sorry, but not fixed in 3.10.33 :(
the items do not go to my inscription bag and there is no option for that

![image](https://github.com/arkayenro/arkinventory/assets/96299043/5dba5941-542a-49d2-9e60-e9c5cf246992)
