### ISSUE TITLE
[BUG] bad argument #1 to 'SetJustifyH'

### ISSUE THREAD

**Issue by djmillerjr** [arkayenro/arkinventory#1887]
**What version number you are using?**
v31029 Dragonflight

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
As soon as I attempt to open my bags, I get the ArkInventory window, with "Loading..." in the upper left corner. In the chat window I get the following message:

ArkInventory: ERROR> Interface/AddOns/ArkInventory/Core/ArkInventory.lua:6601: bad argument #1 to 'SetJustifyH' (Usage: self:SetJustifyH(justifyH)) 

**To Reproduce**
Steps to reproduce the behaviour, if possible:

**Screenshots**

**Additional context**

**Comment by 11-Lambda** [comment]
I'm also seeing this bug when opening my bags after the recent retail WoW patch.

**Comment by ShicKla** [comment]
If you do not want to wait for the addon author to do an update, and are comfortable editing the code, here is what you can do to fix it.

Using a text editor, preferably one that shows line numbers, open the file
`\World of Warcraft\_retail_\Interface\AddOns\ArkInventory\Core\ArkInventory.lua`

In the text editor scroll down to line `6601` and change `obj:SetJustifyH( "MIDDLE" )` to `obj:SetJustifyH( "CENTER" )`

Save and close the the file, then use the `/reload` command in WoW, or just restart the game.

**Comment by arkayenro** [comment]
should be fixed in [3.10.29-alpha-2](https://www.curseforge.com/wow/addons/ark-inventory/files/5328734)

**Comment by djmillerjr** [comment]
> should be fixed in [3.10.29-alpha-2](https://www.curseforge.com/wow/addons/ark-inventory/files/5328734)

Awesome, back to normal. Thank you!!
