### ISSUE TITLE
Error Message in Chat window

### ISSUE THREAD

**Issue by the-quality** [arkayenro/arkinventory#1889]
Hi,

with latest verion v31029 (Dragonflight) and WoW Patch 10.2.7 ive got multiple messages in chat:

ArkIventory: FEHLER> ARKINV_Debug does not exist.

Any idea how to fix this?

**Comment by arkayenro** [comment]
that shouldnt be possible.

close the game, delete the addons\arkinventory folder, and reinstall arkinventory.  see if that fixes it.

**Comment by the-quality** [comment]
did it, same eror

**Comment by arkayenro** [comment]
disable all other mods except arkinventory and see if it still happens.

**Comment by the-quality** [comment]
i think i got it.

if i witch to english game client, everything is fine, switching back to german game client, error is back.
so i think it has something to do with language files in "Locale" folder ?

**Comment by arkayenro** [comment]
ok, let me switch mine to german and see if i can work out whats happening

**Comment by arkayenro** [comment]
sorry, im not getting any issues when i switch to german.

**Comment by the-quality** [comment]
hm, no idea then...just fyi, i switched text and audio to german, just to be sure

**Comment by arkayenro** [comment]
yeah i changed both.

could you install these mods and see if they catch the actual error?

- https://www.curseforge.com/wow/addons/bugsack
- https://www.curseforge.com/wow/addons/bug-grabber

**Comment by the-quality** [comment]
no need, its somehow fixed with version 31030.

thanks
