### ISSUE TITLE
[BUG] LUA error with LibDialog

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1890]
**What version number you are using?**
3.10.29-alpha2

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
When trying to save an addon set with Better Addon List, the LUA error below pops up and completely breaks the game, meaning the chat stops working so reload is not possible, menu can't be opened either, so cannot logout, the game can only be exited by killing the WoW process.
This seems to be a bug with LibDialog and the fix [here](https://legacy.curseforge.com/wow/addons/betteraddonlist/issues/18) applied to LibDialog-1.0.lua within the ArkInventory libs fixes it here as well.

4x ArkInventory/Libs/LibDialog/LibDialog-1.0-9.lua:833: attempt to get length of field 'StaticPopup_DisplayedFrames' (a nil value)
[string "@ArkInventory/Libs/LibDialog/LibDialog-1.0-9.lua"]:833: in function `Spawn'
[string "@BetterAddonList/BetterAddonList.lua"]:472: in function `func'
[string "@Blizzard_SharedXML/Mainline/UIDropDownMenu.lua"]:1019: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:133_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:133_OnClick"]:1>

error = <function> defined =[C]:-1
_BuildDialog = <function> defined @ArkInventory/Libs/LibDialog/LibDialog-1.0.lua:553
_Dialog_OnShow = <function> defined @ArkInventory/Libs/LibDialog/LibDialog-1.0.lua:229

**To Reproduce**
1. Install [Better Addon List](https://legacy.curseforge.com/wow/addons/betteraddonlist/files/all)
2. Open the Addons menu
3. Try to save an addon set
4. Observe the LUA error above and game broken

**Additional context**
I'm sure this could be reproduced with some other method, but this is how I encountered it and don't know where else this funcion is used.
Changing the above function in Better Addon List only did not fix the issue, it got resolved only after doing it in ArkInventory's lib as well.

**Comment by arkayenro** [comment]
LibDialog is a shared library, i tend to load it first (a being first alphabetically) so any time another mod using it has an issue i will get blamed.

i've read the other post and replied.  they need to bump the version number as well or it will keep happening.

i've included the fix in my version of the library and bumped it to 10 so it should be fixed in the next alpha

note that the source does not have the fix yet

**Comment by arkayenro** [comment]
should be fixed in [3.10.29-alpha-3](https://www.curseforge.com/wow/addons/ark-inventory/files/5331811)

**Comment by hollo6** [comment]
Looks good, thank you!
