### ISSUE TITLE
Rules problem with the Tooltip focntion when the tooltip have space or hyphen (-)

### ISSUE THREAD

**Issue by AshLeBlanc** [arkayenro/arkinventory#1892]
Hello i'm doing a simple rule like:

tt("Gemme prismatique")
![image](https://github.com/arkayenro/arkinventory/assets/170059152/247331a4-a384-4501-80e7-52a1abf339fa)

and it works perfectly but when i try with this:

tt("méta - gemme") 
![imageww](https://github.com/arkayenro/arkinventory/assets/170059152/e8563920-4d84-4302-8bee-21b18052e8b4)

it doesn't work.. someone know how to do it?

Thanks in advance

**Comment by PyroPope** [comment]
I don't think its the hyphen, I have not been able to get it to work with Tinker Gems either. i think the Meta, Cog, and Tinker gems are all not working?

**Comment by AshLeBlanc** [comment]
I don’t know it’s strange normally when you use the Tooltip rule is suppose to copie the word you choose from it, there is maybe something blocking it with the meta gemme and I think there is a way to force it…. at least I hope!? (Sorry for my English)

**Comment by AshLeBlanc** [comment]
> I don't think its the hyphen, I have not been able to get it to work with Tinker Gems either. i think the Meta, Cog, and Tinker gems are all not working?

I don’t know it’s strange normally when you use the Tooltip rule is suppose to copie the word you choose from it, there is maybe something blocking it with the meta gemme and I think there is a way to force it…. at least I hope!? (Sorry for my English)

**Comment by arkayenro** [comment]
the minus character is a regex magic character so it needs to be escaped

use `tt("méta%-gemme")`

**Comment by AshLeBlanc** [comment]
> the minus character is a regex magic character so it needs to be escaped
> 
> use `tt("méta%-gemme")`

OMG it worked thank you so much !! nad thanks for keeping this amazing addon alive.
