### ISSUE TITLE
[BUG] Deleting junk takes precedence even when the item is refundable

### ISSUE THREAD

**Issue by ZeShmoutt** [arkayenro/arkinventory#1894]
**What version number you are using?**
v31030 [Dragonflight]

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
French

**Describe the bug**
If an item is refundable but not sellable (e.g. an armor ensemble), and the option to delete unsellable junk is activated, right clicking the item at a vendor will show the refund pop up but also immediately delete the item.

**To Reproduce**
Easiest done on MoP Remix currently :
1. Enable deleting junk
2. Buy an ensemble that you already know (it will be automatically flagged as junk)
3. Try to refund the ensemble

**Comment by arkayenro** [comment]
should be fixed in the next release.  anything refundable wont be touched
