### ISSUE TITLE
[BUG] Cata - LUA Error, Keyring

### ISSUE THREAD

**Issue by Jorvanus** [arkayenro/arkinventory#1895]
On Alpha 3.  

![image](https://github.com/arkayenro/arkinventory/assets/89010934/e2842189-ff3d-4493-8aeb-3ba10a815b9e)

I believe they removed some keyring functionality in last nights patch.

**Comment by arkayenro** [comment]
so the keyring no longer exists?

**Comment by Jorvanus** [comment]
I'm sure there is a more technical response, but yes, I believe that is the issue.

**Comment by arkayenro** [comment]
yeah, i went back through my old code and it was removed in 40200 and cata is now 40400

will be fixed in the next alpha

**Comment by Jorvanus** [comment]
> yeah, i went back through my old code and it was removed in 40200 and cata is now 40400
> 
> will be fixed in the next alpha

On latest alpha

![image](https://github.com/arkayenro/arkinventory/assets/89010934/cb79fc9c-7855-4653-abd4-397815d6a9dd)

**Comment by arkayenro** [comment]
so they half arsed it.  i'll need to find a way to let it know about the keyring "bag" but not enable the location.

i dont have any keys on my cata toon so no errors showed up when i tested it.

**Comment by arkayenro** [comment]
hopefully alpha 5 will fix it

**Comment by luitzifa** [comment]
alpha5 and alpha6 works
