### ISSUE TITLE
[BUG] LUA error & printout CONFIG_ACTION_MAIL_CONFLICT_DESC

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1896]
**What version number you are using?**
v31030.Alpha.6

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
A few versions ago, I started getting the following printout on every login/reload:
`[11:50:24] ArkInventory: WARNING> CONFIG_ACTION_MAIL_CONFLICT_DESC`

And the below LUA error:
`152x AceLocale-3.0-6: ArkInventory: Missing entry for 'CONFIG_ACTION_MAIL_CONFLICT_DESC'
[string "@ArkInventory/Core/ArkInventoryAction.lua"]:73: in function `ConflictCheck'
[string "@ArkInventory/Core/ArkInventory.lua"]:3140: in function <ArkInventory/Core/ArkInventory.lua:3117>
[string "=[C]"]: ?
[string "@!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:402: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:607: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 delete = <table> {
 }
 mail = <table> {
 }
 scrap = <table> {
 }
 vendor = <table> {
 }
 use = <table> {
 }
}
(for control) = "vendor"
_ = "vendor"
action = <table> {
 addon = "SellJunk"
 running = false
 name = "Vendor"
 addons = <table> {
 }
 conflict = true
 money = 0
 bypass = false
 sold = 0
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "Scrap"
 2 = "SellJunk"
 3 = "ReagentRestocker"
 4 = "Peddler"
}
(for control) = 2
_ = 2
a = "SellJunk"
(*temporary) = <function> defined @ArkInventory/Core/ArkInventoryConst.lua:373
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
 DISPLAY = "Display"
 MENU_BAR_CATEGORY_REMOVE_DESC = "click to remove %1$s from bar %2$s

the category will revert to the default bar"
 ANCHOR_TEXT1 = "set the anchor point for the %1$s window"
 CONFIG_GENERAL_TOOLTIP_BATTLEPET_MOUSEOVER_ENABLE_DESC = "include extra text in mouseover tooltips for player, npc and wild battlepets"
 RULE_FAILED = "Error validating rule %s"
 CONFIG_CONTROL_BLUEPRINT_DESC = "select which %2$s to use when generating the %1$s window"
 CONFIG_DESIGN_BAR_COMPACT = "Compact"
 CONFIG_DEBUG = "Debug Mode"
 CONFIG_SORTING_WHEN_DESC = "When to re-sort the windows"
 WOW_ITEM_CLASS_ITEM_ENHANCEMENT = "Item Enhancement"
 FRAME_ONENTER_DRAG_BAR_ALT = "

hold ALT and release the mouse button, to move all categories assigned to bar %1$s to this bar (%2$s)"
 WOW_SKILL_ENCHANTING = "Enchanting"
 WOW_ITEM_TOOLTIP_10P6S = "M"
 CONFIG_DESIGN_BAR_COMPACT_DESC = "display all non empty bars in sequential order"
 ASSIGNABLE = "Assignable"
 IMPORT = "Import"
 CONFIG_PROFILE = "Profile"
 CONFIG_CONTROL_ANCHOR_LOCK_DESC = "lock the %1$s window so it can't be moved"
 MENU_BAG_SHOWALL_DESC = "display the contents of all bags for this location"
 CONFIG_DESIGN_BAR_SHOW_EMPTY_DESC = "display empty bars"
 MENU_ITEM_DEBUG_ID = "Blizzard ID"
 WOW_ITEM_CLASS_MISC_HOLIDAY = "Holiday"
 CONFIG_DESIGN_BAR_NAME_EDITMODE_DESC = "display bar names in %1$s"
 CONFIG_GENERAL_TRADESKILL_QUIET_DESC = "When the %1$s option is enabled the %2$s window is opened, that makes noise which may, or may not, be annoying for you.

Enabled: will mute your sound when the on load scanning starts and unmute it when they are done.

Disabled: Wont touch your sound settings and you will hear the windows open."
 CONFIG_GENERAL_BONUSID_SUFFIX_COUNT_DESC = "Enabled: Generates a count for each item suffix found

Disabled: Ignores any item suffix and generates a count for the base item instead"
 SLOT = "Slot"
 CONFIG_GENERAL_TOOLTIP_CROSSREALM_DESC = "display data from realms connected to the current characters realm"
 NEW_ITEM_GLOW = "New Item Glow"
 CONFIG_GENERAL_TRADESKILL_PRIORITY_DESC = "Select which %1$s you want items categorised for first.

This will save the slot the %1$s is in, not the actual %1$s."
 ENABLED = "Enabled"
 CONFIG_ACTION_TYPE_DESC = "Set the action type for %s to %s"
 ASSIGN = "Assign"
 CONFIG_DESIGN_ITEM_STACK_COMPRESS_INCLUDE_EMPTY_DESC = "compress empty slots"
 CONFIG_SORTING_INCLUDE_ITEMUSELEVEL = "item (use) level"
 BLIZZARD = "Blizzard"
 SLASH_UI = "ui"
 RELOAD = "Reload"
 RULE_LIST_ENABLED = "Use"
 CONFIG_GENERAL_CONFLICT_TSM_MERCHANT_DESC = "enable this if you have set TSM to be the merchant window"
 BUGFIX_TAINTED_ALERT_OPEN_DESC = "some of the item frames for this window were created while you were in combat which has caused them to be tainted and cannot be used until you leave combat"
 HORIZONTAL = "Horizontal"
 CONFIG_DESIGN_BAR_PADDING_EXTERNAL_DESC = "the amount of space to add between bars"
 MENU_BAR_CATEGORY_DISABLE_DESC = "Disables this rule so it is no longer used by this layout"
 CRAFTING_REAGENT = "Crafting Reagent"
 SCRAP = "Scrap"
 CONFIG_DESIGN_ITEM_OVERRIDE_NEW_CUTOFF_DESC = "only reassign items to the new items category if they are within this duration."
 MENU_ITEM_DEBUG_ITEMSTRING = "Item String"
 PET_CANNOT_BATTLE = "This creature cannot battle."
 NONE = "None"
 LDB_CURRENCY_NONE = "You dont know any currencies"`

**To Reproduce**
Not sure what's needed to get this error, I haven't changed anything in AI settings, it started popping up with one of the addon updates.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by arkayenro** [comment]
will be fixed in the next alpha

**Comment by hollo6** [comment]
No longer getting this error in alpha7. Thanks!
