### ISSUE TITLE
[BUG] Scrap overlays missing in latest version

### ISSUE THREAD

**Issue by BradCOnGitHub** [arkayenro/arkinventory#1899]
Scrap overlays missing in latest version

**Comment by arkayenro** [comment]
whats a scrap overlay?

**Comment by BradCOnGitHub** [comment]
Overlays from the Scrap addon https://www.curseforge.com/wow/addons/scrap

You can see some here: 
![image](https://github.com/arkayenro/arkinventory/assets/15109073/aabb6f56-de00-497d-9cab-dfef4a2004c1)

**Comment by arkayenro** [comment]
ah, the junk icon.  should be fixed in the next alpha release
