### ISSUE TITLE
[BUG] [TWW Beta] 'Summon Mount' Keybinding Doesn't Work

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1905]
**What version number you are using?**
v31033.Alpha.5

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
TWW Beta

**What language is the game client set to?**
English

**Describe the bug**
After having properly selected my mounts in the options, I setup an ArkInventory keybinding for 'Summon Mount' but it doesn't seem to work.

**To Reproduce**
Steps to reproduce the behaviour, if possible:

**Screenshots**
![KeyBinding](https://github.com/arkayenro/arkinventory/assets/13042214/09c59d4d-96ae-45ce-938d-41a921801a45)

**Additional context**
I realize this is an Alpha build and there's probably a lot still being reviewed.  I'm simply raising this issue for awareness to help with troubleshooting.  Hopeful that it can be resolved for launch!

**Comment by arkayenro** [comment]
it was working last week but it appears one of the later beta updates has screwed up the click bindings

same thing happened in the dragonflight beta and it eventually got fixed so hopefully this will too.

i might add another keybinding for non-secure mount summons.  it wont work in combat but at least it will be there until this is fixed

**Comment by Calesta** [comment]
FYI.  This started working in the latest beta build.  You can close this issue if you're confident that it's 'fixed' and no longer needs tracking.  Thanks!

**Comment by arkayenro** [comment]
seems to have been fixed by blizzard in the latest beta
