### ISSUE TITLE
[BUG] Recipe stock/location not shown on tooltip

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1911]
**What version number you are using?**
3.10.33-alpha-5, 3.10.33-alpha-7

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
Item quantities are not being shown on item tooltips for recipes.
I think they are actually stored because search finds them but even there it's imporssible to tell where they are because the information is missing from the tooltip.
Seems to only affect recipes, but all of them.

**To Reproduce**
Mouseover any recipe.
Observe the stock info line missing from the tooltip.

**Screenshots**
Stock info missing:
![image](https://github.com/arkayenro/arkinventory/assets/365584/27e749fe-84ec-4497-801e-b5dca3375fc4)

Example of it being shown for other items:
![image](https://github.com/arkayenro/arkinventory/assets/365584/6c3e9025-8ac8-4c18-876c-d5dc434dc1a3)

**Additional context**
I think this was working before, but not sure when.

**Comment by arkayenro** [comment]
thats an known issue, recipes show the item counts for the things they make, not the actual recipe.  havent been able to work out why yet

**Comment by arkayenro** [comment]
its shows the transmog status for the item the recipe makes as well, which it shouldnt

**Comment by hollo6** [comment]
Showing the transmog status of the actual item is not annoying, not being able to tell the counts and location for the recipes are. :)

**Comment by hollo6** [comment]
All good in alpha-12! Thanks!
