### ISSUE TITLE
[BUG] [TWW Beta] Opening Bags: Stuck at 'Loading' with Error Message

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1914]
**What version number you are using?**
v31033.Alpha.9

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
TWW Beta

**What language is the game client set to?**
English

**Describe the bug**
Logged in this morning to check on the latest update and when I open my bags, the ArkInventory frame shows up but it's stuck at 'Loading'.  I captured the error message in the screenshot shared below.

**To Reproduce**
See above.

**Screenshots**
![image](https://github.com/arkayenro/arkinventory/assets/13042214/c205ee9a-f90a-4f0a-8193-c0635ddf0e60)

**Additional context**
N/A

**Comment by arkayenro** [comment]
yep, looks like blizzard removed a function in the latest beta

**Comment by fraerie** [comment]
error message below, I tried updating to the most recent Ace3 build, it did not resolve the issue

15x ...faceArkInventory/Core/ArkInventoryClient.lua:1085: attempt to call global 'GetItemQualityColor' (a nil value)
[string "@ArkInventory/Core/ArkInventoryClient.lua"]:1085: in function `GetItemQualityColor'
[string "@ArkInventory/Core/ArkInventoryStorage.lua"]:5264: in function `GetItemQualityColor'
[string "@ArkInventory/Core/ArkInventory.lua"]:8485: in function `Frame_Item_Update_Border'
[string "@ArkInventory/Core/ArkInventory.lua"]:10029: in function `Frame_Item_Update_Instant'
[string "@ArkInventory/Core/ArkInventoryStorage.lua"]:546: in function <...aceArkInventory/Core/ArkInventoryStorage.lua:536>
[string "=[C]"]: ?
[string "@Ace3/AceBucket-3.0-4/AceBucket-3.0.lua"]:69: in function <Ace3/AceBucket-3.0/AceBucket-3.0.lua:67>
[string "@Ace3/AceBucket-3.0-4/AceBucket-3.0.lua"]:83: in function `func'
[string "@Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call global 'GetItemQualityColor' (a nil value)"

**Comment by arkayenro** [comment]
its not an ace issue.  it will be fixed in the next alpha

**Comment by fraerie** [comment]
cheers!

**Comment by arkayenro** [comment]
should be fixed in alpha 10

**Comment by fraerie** [comment]
confirming that it's working for me
