### ISSUE TITLE
[BUG] LUA error for character/location changer

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1917]
**What version number you are using?**
alpha-12

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
When trying to view another character's inventory, it spams the below LUA error continuously while the switcher menu is open and the selected character's inventory will show the current one's instead.

35x ArkInventory/Core/ArkInventoryMenu.lua:3217: attempt to call field 'GetPlayerInfo' (a nil value)
[string "@ArkInventory/Core/ArkInventoryMenu.lua"]:3217: in function `MenuSwitchCharacter'
[string "@ArkInventory/Core/ArkInventoryMenu.lua"]:3270: in function <ArkInventory/Core/ArkInventoryMenu.lua:3269>
[string "@ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua"]:1872: in function <...eArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:1821>
[string "@ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua"]:2749: in function <...eArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:2715>
[string "@ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua"]:626: in function <...eArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:610>

Locals:
offset = 0
level = 2
value = "SWITCH_CHARACTER_ERASE_Name - Ragnaros"
frame = ARKINV_Frame13TitleActionButton5 {
 0 = <userdata>
}
loc_id = 13
codex = <table> {
 toon = <table> {
 }
 workpad = <table> {
 }
 profile_id = 1000
 layout = <table> {
 }
 profile = <table> {
 }
 loc_id = 13
 style = <table> {
 }
 catset_id = 1000
 catset = <table> {
 }
 layout_id = 1000
 player = <table> {
 }
 style_id = 1000
}
account = nil
realm = nil
player_id = "Name - Ragnaros"
(*temporary) = nil
(*temporary) = "Name - Ragnaros"
(*temporary) = "attempt to call field 'GetPlayerInfo' (a nil value)"
string = <table> {
 split = <function> defined =[C]:-1
 match = <function> defined =[C]:-1
 gmatch = <function> defined =[C]:-1
 upper = <function> defined =[C]:-1
 gsub = <function> defined =[C]:-1
 format = <function> defined =[C]:-1
 utf8sub = <function> defined @ElkBuffBars/libs/UTF8/utf8.lua:183
 lower = <function> defined =[C]:-1
 sub = <function> defined =[C]:-1
 find = <function> defined =[C]:-1
 gfind = <function> defined =[C]:-1
 len = <function> defined =[C]:-1
 rep = <function> defined =[C]:-1
 utf8len = <function> defined @ElkBuffBars/libs/UTF8/utf8.lua:158
 char = <function> defined =[C]:-1
 rtgsub = <function> defined @Blizzard_FrameXML/RestrictedInfrastructure.lua:535
 join = <function> defined =[C]:-1
 reverse = <function> defined =[C]:-1
 byte = <function> defined =[C]:-1
 trim = <function> defined =[C]:-1
 utf8reverse = <function> defined @ElkBuffBars/libs/UTF8/utf8.lua:286
 startswith = <function> defined @MoveAny/libs/db.lua:645
}
pairs = <function> defined =[C]:-1

**To Reproduce**
Click "Switch Character" button in the top row.

**Screenshots**
N/A

**Additional context**
This was working until a few versions ago (probably alpha-10), was definitely not a problem in alpha-5.

**Comment by arkayenro** [comment]
will be fixed in the next alpha

**Comment by hollo6** [comment]
In alpha-14, it looks the same (won't change bag, showing the current one's inventory instead) but getting a different LUA error now:

17x ArkInventory/Core/ArkInventoryMenu.lua:3220: attempt to index field 'data' (a nil value)
[string "@ArkInventory/Core/ArkInventoryMenu.lua"]:3220: in function `MenuSwitchCharacter'
[string "@ArkInventory/Core/ArkInventoryMenu.lua"]:3270: in function <ArkInventory/Core/ArkInventoryMenu.lua:3269>
[string "@ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua"]:1872: in function <...eArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:1821>
[string "@ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua"]:2749: in function <...eArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:2715>
[string "@ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua"]:626: in function <...eArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:610>

Locals:
offset = 0
level = 2
value = "SWITCH_CHARACTER_ERASE_Name - Ragnaros"
frame = ARKINV_Frame1TitleActionButton5 {
 0 = <userdata>
}
loc_id = 1
codex = <table> {
 toon = <table> {
 }
 style_id = 1000
 profile_id = 1007
 catset_id = 1000
 layout_id = 1007
 player = <table> {
 }
 style = <table> {
 }
 workpad = <table> {
 }
 layout = <table> {
 }
 profile = <table> {
 }
 loc_id = 1
 catset = <table> {
 }
}
account = nil
realm = nil
player_id = "Name - Ragnaros"
tp = <table> {
 istimerunner = 0
 guid = "Player-3682-05D04B98"
 class = "HUNTER"
 class_local = "Hunter"
 race = "Troll"
 level = 70
 realm = "Ragnaros"
 tradeskill = <table> {
 }
 isplayer = true
 money = 24266320726
 gender = 3
 itemlevel = 491
 guild_id = "+Pure Shame - Ragnaros"
 name = "Name"
 faction = "Horde"
 race_local = "Troll"
 account_id = 100
 player_id = "Name - Ragnaros"
 faction_local = "Horde"
}
(*temporary) = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:3032
(*temporary) = <table> {
 Close = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:2983
 AddSeparator = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:3019
 OnTooltipHide = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:3348
 AddLine = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:3032
 argCheck = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:3470
 error = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:3497
 SetStandardFont = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:31
 IsOpen = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:2706
 GetOpenedParent = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:2711
 hookedTooltip = true
 IsRegistered = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:2873
 Refresh = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:1879
 Open = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:2935
 InjectAceOptionsTable = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:3284
 FeedTable = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:1762
 onceRegistered = <table> {
 }
 registry = <table> {
 }
 FeedAceOptionsTable = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:1261
 KEY_BUTTON2 = "Right Mouse"
 frame = Frame {
 }
 EncodeKeybinding = <function> defined @ArkInventory/Libs/ArkDewdrop/ArkDewdrop.lua:2646
 KEY_BUTTON1 = "Left Mouse"
}
(*temporary) = "text"
(*temporary) = <function> defined @ArkInventory/Core/ArkInventory.lua:13893
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'data' (a nil value)"
string = <table> {
 split = <function> defined =[C]:-1
 match = <function> defined =[C]:-1
 gmatch = <function> defined =[C]:-1
 upper = <function> defined =[C]:-1
 gsub = <function> defined =[C]:-1
 format = <function> defined =[C]:-1
 utf8sub = <function> defined @ElkBuffBars/libs/UTF8/utf8.lua:183
 lower = <function> defined =[C]:-1
 sub = <function> defined =[C]:-1
 find = <function> defined =[C]:-1
 gfind = <function> defined =[C]:-1
 len = <function> defined =[C]:-1
 rep = <function> defined =[C]:-1
 utf8len = <function> defined @ElkBuffBars/libs/UTF8/utf8.lua:158
 char = <function> defined =[C]:-1
 rtgsub = <function> defined @Blizzard_FrameXML/RestrictedInfrastructure.lua:535
 join = <function> defined =[C]:-1
 rever

**Comment by arkayenro** [comment]
sorry, i thought it was just a function that had been renamed and i missed that one but it appears theres a bigger underlying issue this just made obvious.

ill try and get it fixed for the next alpha

**Comment by hollo6** [comment]
Looks good in alpha-15, thanks!

**Comment by arkayenro** [comment]
its still a bit wonky if you have stack compression enabled, it wont actually compress them across the new sublocation boundaries (bag/reagent bag or bank/reagent bank/account bank) when offline and i havent worked that one out yet, but i dont think anyone will overly care too much about that as its more of a cosmetic issue than a real one.

if you notice anything else weird with the offline views let me know

**Comment by hollo6** [comment]
Thanks, will do! I'm not using that feature so all good for me.
I did get a new error in the new version after using HS, but wanted to test on other characters to try and narrow down the cause and didn't note it (was AI printout and no LUA error). Will open a new ticket when I see it again. Only thing I remember it said was ArkInventoryCodex.lua:111 try to index some nil variable.
