### ISSUE TITLE
[BUG] Tooltip-Error

### ISSUE THREAD

**Issue by Coltseavers75** [arkayenro/arkinventory#1919]
I'm using Arkinventory-3.10.33-alpha-13

Cata_classic

German client

While hovering over bagitems, Message in chat shows up and says as long as i hover over bagitem:
G0: GameTooltip:SetBagItem ( 3, 4, nil, nil )

While hovering over bags, Message in chat shows up and says as long as i hover over bag:
G0: GameTooltip:SetHyperlink ( |cff1eff00|Hitem:41599::::::::83::::::::::|h[Frosttasche]|h|r, nil, nil, nil )

**To Reproduce**
Just hover over items or bag

**Screenshots**
![grafik](https://github.com/user-attachments/assets/060d33fe-a06f-4261-9e05-6965e733f255)

**Comment by arkayenro** [comment]
sorry, leftover debug output will get rid of it next alpha
