### ISSUE TITLE
Pre-Patch error with 10.2.7 version, CloseBankFrame

### ISSUE THREAD

**Issue by 40P3** [arkayenro/arkinventory#1921]
5x ArkInventory/Core/ArkInventory.lua:12437: attempt to call global 'CloseBankFrame' (a nil value)
[string "@ArkInventory/Core/ArkInventory.lua"]:12437: in function `BlizzardAPIHook'
[string "@ArkInventory/Core/ArkInventory.lua"]:3169: in function <ArkInventory/Core/ArkInventory.lua:3125>
[string "=[C]"]: ?
[string "@Accountant/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Accountant/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Accountant/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
disable = nil
reload = nil
(*temporary) = nil
(*temporary) = "attempt to call global 'CloseBankFrame' (a nil value)"
_G = <table> {
 StanceButton9OverlayOverlay = StanceButton9OverlayOverlay {
 }
 ARKINV_SearchFrameViewTableRow12T1 = ARKINV_SearchFrameViewTableRow12T1 {
 }
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 TrinketMenu_Menu8HotKey = TrinketMenu_Menu8HotKey {
 }
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "Hide Bar Art"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 783
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 421
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 MultiBarBottomLeftButton11OverlayHighlight = MultiBarBottomLeftButton11OverlayHighlight {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Attached to the left side of Right Action Bar 1 by default"
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 375
 MerchantItem3AltCurrencyFrameItem1Text = MerchantItem3AltCurrencyFrameItem1Text {
 }
 PROFESSIONS_COLUMN_REAGENTS_NONE = "None"
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Nameplates"
 CHAT_HEADER_SUFFIX = ": "
 COVENANT_MISSIONS_HEALTH = "Health"
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 MultiBar6Button4Flash = MultiBar6Button4Flash {
 }
 ERR_NOAMMO_S = "%s"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 ARKINV_PopupBarFrameBackground = ARKINV_PopupBarFrameBackground {
 }
 ClassNameplateBarPaladinFrameRune5 = ClassNameplateBarPaladinFrameRune5 {
 }
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 BOOST2_WARRIOR_COLOSSUSSMASH = "Use |cFFFFFFFFColossus Smash|r.

|cFFFFFFFFColossus Smash|r increases your damage."
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 CinematicFrameRaidBossEmoteFrame = CinematicFrameRaidBossEmoteFrame {
 }
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 SLASH_LibQTip1 = "/qtip"
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 MacroFrame = MacroFrame {
 }
 POWERBAR_PREDICTION_COLOR_MAELSTROM_CODE = "|cff003366"
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 DMG_LCD = "DMG"
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 ARKINV_Frame4TitleActionButton2 = ARKINV_Frame4TitleActionButton2 {
 }
 SLASH_STOPATTACK1 = "/stopattack"
 MAP_LEGEND_RARE_TOOLTIP = "A special creature that provides various rewards"
 MultiCastActionButton4HotKey = MultiCastActionButton4HotKey {
 }
 MINIMAP_TRACKING_TRAINER_CLASS = "Class Trainer"
 SLASH_DISMOUNT2 = "/dismount"
 DUNGEON_FLOOR_DRAGONBLIGHTCHROMIESCENARIO2 = "Andorhal"
 EMOTE69_CMD1 = "/nosepick"
 WowTokenRedemptionFrameBg = WowTokenRedemptionFrameBg {
 }
 SPELL_FAILED_CUSTOM_ERROR_152 = "You must choose a specialization to use Ascendance."
 AutoFollowStatus = AutoFollowStatus {
 }
 ARENA_CASUAL = "Skirmish"
 STABLE_PET_ABILITIES_LIST_HEADER = "Special Abilities"
 SendStationeryBackgroundRight = SendStationeryBackgroundRight {
 }
 MultiBarLeftButton11Name = MultiBarLeftButton11Name {
 }
 KEY_ABBR_PADLSTICK = "|A:Gamepad_Gen_LStickIn_32:14:14|a"
 CONQUEST_BAR = "Conquest %d / %d"
 MultiBarLeftButton9Border = MultiBarLeftButton9Border {
 }
 POSTMASTER_PIPE_KALIMDOR = "Kalimdor"
 UIWidgetCenterDisplayFrameText = UIWidgetCenterDisplayFrameText {
 }
 TopIconTexture = TopIconTexture {
 }
 OPTION_T

**Comment by arkayenro** [comment]
try using the latest alpha version

**Comment by arkayenro** [comment]
is that alpha 20, or just 3.10.33?

you want the alpha version at the moment, its the only one setup for war within

**Comment by arkayenro** [comment]
https://www.curseforge.com/wow/addons/ark-inventory/files/5560486
