### ISSUE TITLE
How does the addon process commands?

### ISSUE THREAD

**Issue by jsauerland** [arkayenro/arkinventory#1923]
I'm learning how to develop in LUA, and took a look under the hood at all the files. I know the absolute basics of LUA programming, XML files, TOC files and how they work together. I was looking to see where your slash commands are, like using /ai or /arkinventory. Couldn't find them. I'm curious where they're located so I can see how to structure my own addons in the future. For example.... How do I create a /addonname list to create a window with the UI. 

I thought it would be in ArkInventory.lua but maybe I'm missing it, not sure.

**Comment by arkayenro** [comment]
arkinventory is ace3 based so the primary slash commands are set here

`ArkInventory.Lib.Config:RegisterOptionsTable( ArkInventory.Const.Frame.Config.Blizzard, ArkInventory.Config.Blizzard, { "arkinventory", "arkinv", "ai" } )`

the rest is part of the config table -see `core\arkinventoryconfig.lua - function ArkInventory.ConfigBlizzard( )` and `arkinventoryconfig\arkinventoryconfig.lua` for the main config

**Comment by jsauerland** [comment]
Thanks for the info! 🥇
