### ISSUE TITLE
[BUG] Stack bad argument error when mousing over certain icons

### ISSUE THREAD

**Issue by tabdelrazaq** [arkayenro/arkinventory#1927]
**What version number you are using?**
31033.Alpha.20

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
When mousing over certain buttons (Summon Random Mount from Warband Collections for example) the following error appears
Message: bad argument #1 to '?' (Usage: local spellLink = C_Spell.GetSpellLink(spellIdentifier [, glyphID]))
Time: Wed Jul 24 18:20:46 2024
Count: 39
Stack: bad argument #1 to '?' (Usage: local spellLink = C_Spell.GetSpellLink(spellIdentifier [, glyphID]))
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryClient.lua"]:1078: in function `GetSpellLink'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryTooltip.lua"]:3238: in function <...ace/AddOns/ArkInventory/Core/ArkInventoryTooltip.lua:3230>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bartender4/libs/LibActionButton-1.0/LibActionButton-1.0.lua"]:1985: in function <...er4/libs/LibActionButton-1.0/LibActionButton-1.0.lua:1978>
[string "@Interface/AddOns/Bartender4/libs/LibActionButton-1.0/LibActionButton-1.0.lua"]:1060: in function <...er4/libs/LibActionButton-1.0/LibActionButton-1.0.lua:1058>

**To Reproduce**
Steps to reproduce the behaviour, if possible: Open Warband Collections window, go to mounts, move cursor over the summon random mount button.

**Comment by arkayenro** [comment]
should be fixed in the next alpha
