### ISSUE TITLE
[BUG] Short description of your issue

### ISSUE THREAD

**Issue by Theundependable** [arkayenro/arkinventory#1928]
**What version number you are using?**

v31033 DF
**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**

Retail
**What language is the game client set to?**

English
**Describe the bug**
<img width="209" alt="image" src="https://github.com/user-attachments/assets/179ab593-666c-4ac8-96f6-ecf8850a4ab4">
**To Reproduce**
Happends on any toon.. i have no clue what went wrong.. tried removing addon and cache and shit..

**Screenshots**

**Additional context**

**Comment by arkayenro** [comment]
download the latest alpha
