### ISSUE TITLE
[BUG] 'Mount: Config' Shows No Mounts / 'Summon Mount' Keybind Failure

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1929]
**What version number you are using?**
v31033 Dragonflight

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
After logging into retail after having been away for vacation, I noticed I couldn't summon my mount using the ArkInventory keybinding.   I selected 'Mount: Config' and all the tabs -- Flying, Ground, Aquatic, Customized/Unknown -- are completely blank.  Please see the screen capture below.

**To Reproduce**

**Screenshots**
![Capture](https://github.com/user-attachments/assets/89138eab-c8e8-4462-ae7f-2aef0cd45227)

**Additional context**

**Comment by arkayenro** [comment]
download the latest alpha

**Comment by Calesta** [comment]
Thanks!  The latest alpha did indeed fix this issue.  Closing.
