### ISSUE TITLE
[BUG] Can't Access Bank

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1930]
**What version number you are using?**
v31033 Dragonflight

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
When I interact with the Banker, my bags auto open as configured but the bank window isn't made visible.  The guild bank works as before.

**To Reproduce**

**Screenshots**
![Capture](https://github.com/user-attachments/assets/a8dd417a-cbca-4925-8b0a-770ccaa96db3)

**Additional context**

**Comment by arkayenro** [comment]
download the latest alpha

**Comment by Calesta** [comment]
Thanks! The latest alpha did indeed fix this issue. Closing.
