### ISSUE TITLE
[BUG] Attempt to Call global 'IsCurrentSpell' (a nil value) - Alpha Version 21

### ISSUE THREAD

**Issue by amethystnw** [arkayenro/arkinventory#1931]
**What version number you are using?**
ArkInventory-3.10.33-alpha-21.zip

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail - Pre-Patch War Within
Pandaria Remix

**What language is the game client set to?**
English

**Describe the bug**
From Bug Stack - 1 occurrence

1x ...aceArkInventory/Core/ArkInventoryStorage.lua:1543: attempt to call global 'IsCurrentSpell' (a nil value)
[string "@ArkInventory/Core/ArkInventoryStorage.lua"]:1543: in function <...aceArkInventory/Core/ArkInventoryStorage.lua:1541>
[string "=[C]"]: ?
[string "@Ace3/AceBucket-3.0-4/AceBucket-3.0.lua"]:69: in function <Ace3/AceBucket-3.0/AceBucket-3.0.lua:67>
[string "@Ace3/AceBucket-3.0-4/AceBucket-3.0.lua"]:83: in function `func'
[string "@Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
self = <table> {
 Action = <table> {
 }
 db = <table> {
 }
 TranslationsLoaded = true
 Codex = <table> {
 }
 Lib = <table> {
 }
 hooks = <table> {
 }
 Table = <table> {
 }
 baseName = "ArkInventory"
 Search = <table> {
 }
 acedb = <table> {
 }
 Tools = <table> {
 }
 LDB = <table> {
 }
 Tradeskill = <table> {
 }
 orderedModules = <table> {
 }
 Const = <table> {
 }
 Localise = <table> {
 }
 Debug = <table> {
 }
 API = <table> {
 }
 defaultModuleState = true
 Util = <table> {
 }
 Collection = <table> {
 }
 modules = <table> {
 }
 name = "ArkInventory"
 CrossClient = <table> {
 }
 ENUM = <table> {
 }
 enabledState = true
 Config = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 MailRecipients = <table> {
 }
 Global = <table> {
 }
}
bucket = <table> {
 PLAYER_INTERACTION_HOOK = 1
}
(*temporary) = nil
(*temporary) = 265742
(*temporary) = "attempt to call global 'IsCurrentSpell' (a nil value)"

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Accessed several buff scrolls in inventory although entirely sure this triggered the error.  There were 0 errors on a reload of the UI.

**Screenshots**
See copy of text from Bug Stack above

**Additional context**
Bug Stack also captured the same error two times in ArkInventoryStorage.lua line 1563 where the same call to global "IsCurrentSpell' (a nil value) occurred

2x ...aceArkInventory/Core/ArkInventoryStorage.lua:1563: attempt to call global 'IsCurrentSpell' (a nil value)
[string "@ArkInventory/Core/ArkInventoryStorage.lua"]:1563: in function <...aceArkInventory/Core/ArkInventoryStorage.lua:1561>
[string "=[C]"]: ?
[string "@Ace3/AceBucket-3.0-4/AceBucket-3.0.lua"]:69: in function <Ace3/AceBucket-3.0/AceBucket-3.0.lua:67>
[string "@Ace3/AceBucket-3.0-4/AceBucket-3.0.lua"]:83: in function `func'
[string "@Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
self = <table> {
 Action = <table> {
 }
 db = <table> {
 }
 TranslationsLoaded = true
 Codex = <table> {
 }
 Lib = <table> {
 }
 hooks = <table> {
 }
 Table = <table> {
 }
 baseName = "ArkInventory"
 Search = <table> {
 }
 acedb = <table> {
 }
 Tools = <table> {
 }
 LDB = <table> {
 }
 Tradeskill = <table> {
 }
 orderedModules = <table> {
 }
 Const = <table> {
 }
 Localise = <table> {
 }
 Debug = <table> {
 }
 API = <table> {
 }
 defaultModuleState = true
 Util = <table> {
 }
 Collection = <table> {
 }
 modules = <table> {
 }
 name = "ArkInventory"
 CrossClient = <table> {
 }
 ENUM = <table> {
 }
 enabledState = true
 Config = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 MailRecipients = <table> {
 }
 Global = <table> {
 }
}
bucket = <table> {
 UNIT_SPELLCAST_SUCCEEDED = 2
}
(*temporary) = nil
(*temporary) = 265742
(*temporary) = "attempt to call global 'IsCurrentSpell' (a nil value)"

**Comment by arkayenro** [comment]
will be fixed in the next alpha
