### ISSUE TITLE
[BUG] Companion Icons Shown as Generic Warcraft 'W'

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1932]
**What version number you are using?**
v31033 Dragonflight

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Some companion icons are being shown as the generic Warcraft 'W' icon.  I've seen this issue in the past but it's quite a few years.

**To Reproduce**

**Screenshots**
![Capture2](https://github.com/user-attachments/assets/5fb1c0a9-a39f-42cb-ad65-37570e5ca391)

**Additional context**

**Comment by arkayenro** [comment]
youll need to use the latest alpha

**Comment by Calesta** [comment]
Thanks! The latest alpha did indeed fix this issue. Closing.
