### ISSUE TITLE
[BUG] Can't Remove Items from Guild Bank

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1933]
**What version number you are using?**
v31033 Dragonflight

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Despite having full access to the guild vault tab and having all of my daily withdrawals remaining, I can't remove items from my guild bank with ArkInventory enabled.  Disabling ArkInventory restores expected functionality.

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by arkayenro** [comment]
you need to use the latest alpha

**Comment by Calesta** [comment]
Thanks! The latest alpha did indeed fix this issue. Closing.
