### ISSUE TITLE
[BUG] Items Received Not Shown in Bags

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1934]
**What version number you are using?**
v31033 Dragonflight

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
I completed a quest and received three companions but they don't show up in my bags with ArkInventory enabled.

Given this and the other two issues I've logged as bugs - [1932](https://github.com/arkayenro/arkinventory/issues/1932), [1933](https://github.com/arkayenro/arkinventory/issues/1933) - I'm guessing that there's some sort of caching issue?

**To Reproduce**

**Screenshots**
![Capture3](https://github.com/user-attachments/assets/84651065-b107-4eaf-bd24-81ae01391c88)

**Additional context**

**Comment by arkayenro** [comment]
youll need to use the latest alpha

**Comment by Calesta** [comment]
Thanks! The latest alpha did indeed fix this issue. Closing.
