### ISSUE TITLE
[BUG] LUA error when opening gbank

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1935]
**What version number you are using?**
alpha-21

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
Getting the following LUA error when opening the guild bank:

1x ArkInventory/Core/ArkInventory.lua:12406: attempt to index local 'obj' (a nil value)
[string "@ArkInventory/Core/ArkInventory.lua"]:12406: in function `Frame_Changer_Slot_Highlight'
[string "@ArkInventory/Core/ArkInventory.lua"]:12368: in function `Frame_Changer_Generic_OnLeave'
[string "*ArkInventory.xml:1137_OnLeave"]:1: in function <[string "*ArkInventory.xml:1137_OnLeave"]:1>

Locals:
frame = ARKINV_Frame4ChangerWindowBag6 {
 IconOverlay = Texture {
 }
 AugmentBorderAnim = AnimationGroup {
 }
 showMatchHighlight = true
 icon = ARKINV_Frame4ChangerWindowBag6IconTexture {
 }
 size = 98
 count = 98
 HighlightTexture = Texture {
 }
 ArkBorder = ARKINV_Frame4ChangerWindowBag6ArkBorder {
 }
 IconQuestTexture = ARKINV_Frame4ChangerWindowBag6IconQuestTexture {
 }
 PushedTexture = Texture {
 }
 emptyBackgroundAtlas = "bags-item-slot64"
 Count = ARKINV_Frame4ChangerWindowBag6Count {
 }
 searchOverlay = ARKINV_Frame4ChangerWindowBag6SearchOverlay {
 }
 locked = false
 IconOverlay2 = Texture {
 }
 itemContextMatchResult = 3
 BattlepayItemTexture = Texture {
 }
 flashAnim = AnimationGroup {
 }
 newitemglowAnim = AnimationGroup {
 }
 JunkIcon = Texture {
 }
 ExtendedSlot = Texture {
 }
 ARK_Data = <table> {
 }
 NewItemTexture = Texture {
 }
 flash = Texture {
 }
 AugmentBorderAnimTexture = Texture {
 }
 UpgradeIcon = Texture {
 }
 NormalTexture = ARKINV_Frame4ChangerWindowBag6NormalTexture {
 }
 IconBorder = Texture {
 }
 Cooldown = ARKINV_Frame4ChangerWindowBag6Cooldown {
 }
 ItemContextOverlay = Texture {
 }
 BagIndicator = Texture {
 }
 Stock = ARKINV_Frame4ChangerWindowBag6Stock {
 }
}
show = false
loc_id_window = 4
bag_id_window = 6
codex = <table> {
 toon = <table> {
 }
 workpad = <table> {
 }
 profile_id = 1005
 layout = <table> {
 }
 profile = <table> {
 }
 loc_id = 4
 style = <table> {
 }
 catset_id = 1000
 catset = <table> {
 }
 layout_id = 1000
 player = <table> {
 }
 style_id = 1000
}
enabled = true
colour = <table> {
 r = 0
 g = 1
 b = 0
}
map = <table> {
 bag_id_window = 6
 loc_id_storage = 4
 tab_id = 6
 bag_id_storage = 6
 loc_id_window = 4
 blizzard_id = 1006
 bag_type = 1
}
loc_id_storage = 4
bag_id_storage = 6
storage = <table> {
 data = <table> {
 }
}
bag = <table> {
 type = 1
 access = "|cff20ff20(Full Access)|r"
 slot = <table> {
 }
 bag_id = 6
 loc_id = 4
 name = "Tab 6"
 status = -3
 empty = 19
 count = 98
 texture = "Interface\Icons\INV_Misc_QuestionMark"
}
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 62 = <table> {
 }
 63 = <table> {
 }
 64 = <table> {
 }
 65 = <table> {
 }
 66 = <table> {
 }
 67 = <table> {
 }
 68 = <table> {
 }
 69 = <table> {
 }
 70 = <table> {
 }
 71 = <table> {
 }
 72 = <table> {
 }
 73 = <table> {
 }
 74 = <table> {
 }
 75 = <table> {
 }
 76 = <table> {
 }
 77 = <table> {
 }
 78 = <table> {
 }
 79 = <table> {
 }
 80 = <table> {
 }
 81 = <table> {
 }
 82 = <table> {
 }
 83 = <table> {
 }
 84 = <table> {
 }
 85 = <table> {
 }
 86 = <table> {
 }
 87 = <table> {
 }
 88 = <table> {
 }
 89 = <table> {
 }
 90 = <table> {
 }
 91 = <table> {
 }
 92 = <table> {
 }
 93 = <table> {
 }
 94 = <table> {
 }
 95 = <table> {
 }
 96 = <table> {
 }
 97 = <table> {
 }
 98 = <table> {
 }
}
(for control) = 1
slot_id = 1
objname = "ARKINV_Frame4ScrollContainerBag6Item1"
obj = nil
(*temporary) = 6
(*temporary) = 1
(*temporary) = nil
(*temporary) = "ARKINV_Frame4ScrollContainerBag6It

**To Reproduce**
Open guild bank.

**Screenshots**
N/A

**Additional context**
Not sure what triggers it, doesn't happen every time.

**Comment by arkayenro** [comment]
i cant duplicate it but i can see where there might be an error if somehow the item object doesnt exist.

should be fixed in the next alpha

**Comment by arkayenro** [comment]
that one makes no sense as it had to check tooltipInfo exists before getting to that line

do you recall what you were doing at the time?

**Comment by hollo6** [comment]
I just opened guild bank.

**Comment by hollo6** [comment]
Not getting this for a while now.
