### ISSUE TITLE
[BUG] Map.Window[21] is not mapped Error

### ISSUE THREAD

**Issue by thisisu** [arkayenro/arkinventory#1937]
**What version number you are using?**
3.10.33

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
I am getting these errors in the chatbox:
![image](https://github.com/user-attachments/assets/9cc38be3-3870-4993-bbbb-d3ebc03077a1)

**To Reproduce**
I was in Valdrakken and took the Stormwind portal. I imagine using the Orgrimmar portal would trigger it as well.

**Screenshots**

**Additional context**
Just updated and received this error. Previous version wasn't throwing it out. I see it was updated just today.

**Comment by arkayenro** [comment]
try alpha 22

**Comment by thisisu** [comment]
```
1x ArkInventory/Core/ArkInventoryUtil.lua:235: ERROR> Map.Window[21] is not mapped
[string "=[C]"]: in function `error'
[string "@ArkInventory/Core/ArkInventoryUtil.lua"]:13: in function <ArkInventory/Core/ArkInventoryUtil.lua:11>
[string "@ArkInventory/Core/ArkInventoryUtil.lua"]:22: in function `Assert'
[string "@ArkInventory/Core/ArkInventoryUtil.lua"]:235: in function `MapGetWindow'
[string "@ArkInventory/Core/ArkInventoryUtil.lua"]:255: in function `getBlizzardBagIdFromWindowId'
[string "@ArkInventory/Core/ArkInventory.lua"]:7406: in function `Frame_Item_Update_Texture'
[string "@ArkInventory/Core/ArkInventory.lua"]:10056: in function `Frame_Item_Update_Instant'
[string "@ArkInventory/Core/ArkInventoryStorage.lua"]:555: in function <...aceArkInventory/Core/ArkInventoryStorage.lua:545>
[string "=[C]"]: ?
[string "@ArkInventory/Externals/Ace3/AceBucket/AceBucket-3.0-4.lua"]:69: in function <...Inventory/Externals/Ace3/AceBucket/AceBucket-3.0.lua:67>
[string "@ArkInventory/Externals/Ace3/AceBucket/AceBucket-3.0-4.lua"]:83: in function `func'
[string "@WeakAuras/Libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <WeakAuras/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
(*temporary) = "|cffff2020ERROR> Map.Window[21] is not mapped"
```
here is a bug report of it as well. ok will try alpha 22

**Comment by thisisu** [comment]
![image](https://github.com/user-attachments/assets/c9d8e49c-2604-47ac-b956-1724159e26ad)
More errors for me. Bag contents won't load.

**Comment by arkayenro** [comment]
will be fixed in a minute

**Comment by thisisu** [comment]
alpha 24 doing well. Thanks for your good work :)

**Comment by 40P3** [comment]
Hi,
It's the warband bag though, so I guess once Blizz fix the issue this will go away in Arkinventory but I added this just in case... Alpha 24 version installed.
Cheers,
H0PE
---------------
4x ArkInventory/Core/ArkInventoryUtil.lua:235: ERROR> Map.Window[20] is not mapped
[string "=[C]"]: in function `error'
[string "@ArkInventory/Core/ArkInventoryUtil.lua"]:13: in function <ArkInventory/Core/ArkInventoryUtil.lua:11>
[string "@ArkInventory/Core/ArkInventoryUtil.lua"]:22: in function `Assert'
[string "@ArkInventory/Core/ArkInventoryUtil.lua"]:235: in function `MapGetWindow'
[string "@ArkInventory/Core/ArkInventoryUtil.lua"]:255: in function `getBlizzardBagIdFromWindowId'
[string "@ArkInventory/Core/ArkInventoryObject.lua"]:575: in function `ObjectStringDecode'
[string "@ArkInventory/Core/ArkInventoryObject.lua"]:929: in function `GetObjectInfo'
[string "@ArkInventory/Core/ArkInventoryMenu.lua"]:2277: in function `MenuBagOpen'
[string "@ArkInventory/Core/ArkInventory.lua"]:12176: in function `Frame_Changer_Slot_OnClick'
[string "*ArkInventory.xml:1141_OnClick"]:1: in function <[string "*ArkInventory.xml:1141_OnClick"]:1>

Locals:
(*temporary) = "|cffff2020ERROR> Map.Window[20] is not mapped"

**Comment by arkayenro** [comment]
if that was a right click on either the reagent bank or account bank slot in the changer then it should be fixed next alpha

**Comment by the-quality** [comment]
same error with alpha 25, this time when you open auction house, error accoured in LUA line 2
![Screenshot 2024-07-27 090820](https://github.com/user-attachments/assets/d0b81a6e-3603-40bd-bb4e-33300f329b16)
36

**Comment by the-quality** [comment]
edit, also when i am loot

```
Message: ...erface/AddOns/ArkInventory/Core/ArkInventoryUtil.lua:236: ERROR> Map.Window[21] is not mapped
Time: Sat Jul 27 09:13:15 2024
Count: 1
Stack: ...erface/AddOns/ArkInventory/Core/ArkInventoryUtil.lua:236: ERROR> Map.Window[21] is not mapped
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceBucket/AceBucket-3.0.lua"]:83: in function `func'
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceTimer/AceTimer-3.0.lua"]:57: in function <...rkInventory/Externals/Ace3/AceTimer/AceTimer-3.0.lua:50>

Locals: bucket = <table> {
 received = <table> {
 }
 object = <table> {
 }
 timer = <table> {
 }
 interval = 0.200000
 callback = "EVENT_ARKINV_ITEM_UPDATE_BUCKET"
}
received = <table> {
 106001 = 1
 101018 = 1
}
callback = "EVENT_ARKINV_ITEM_UPDATE_BUCKET"
AceTimer = <table> {
 embeds = <table> {
 }
 activeTimers = <table> {
 }
}

```

**Comment by arkayenro** [comment]
open the bag window
click on the switch character icon
find the logged in character
click on erase bags data

if that fixes it then run this from the chat window to clear the bags data for all characters
```
/run ArkInventory.EraseSavedData( nil, ArkInventory.Const.Location.Bag )
```

**Comment by the-quality** [comment]
thx

**Comment by 40P3** [comment]
Just to confirm saved data means what? Configuration also or something like what items the character's bag holds?

**Comment by arkayenro** [comment]
yep, what items are in each location
