### ISSUE TITLE
Attempt to call global 'CloseBankFrame'

### ISSUE THREAD

**Issue by Keahilani** [arkayenro/arkinventory#1938]
**What version number you are using?**
3.10.33

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Doesn't allow an item to be added to a bar #1. I can edit name, color, size (min/max) of bar #1. I can add items to bars >1. When opening a bag, the contents of my bags do not appear. Clicking on a bag provides the following error.
Message: ...ace/AddOns/ArkInventory/Core/ArkInventoryStorage.lua:1768: code failure: loc_id is nil
Time: Sat Jul 27 01:08:19 2024
Count: 1
Stack: ...ace/AddOns/ArkInventory/Core/ArkInventoryStorage.lua:1768: code failure: loc_id is nil
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryStorage.lua"]:1768: in function `InternalIdToBlizzardBagId'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryObject.lua"]:491: in function `ObjectStringDecode'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryObject.lua"]:845: in function `GetObjectInfo'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryMenu.lua"]:2275: in function `MenuBagOpen'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:11214: in function `Frame_Changer_Slot_OnClick'
[string "*ArkInventory.xml:1142_OnClick"]:1: in function <[string "*ArkInventory.xml:1142_OnClick"]:1>

Locals: loc_id = nil
bag_id = nil
string = <table> {
}

**To Reproduce**
Steps to reproduce the behavior, if possible:
I have no addons enabled except for ArkInventory. All I do is select the character I want to use and start the game. It occurs first thing.

**Screenshots**
![image](https://github.com/user-attachments/assets/1459dee2-01f1-46d4-9dce-58c32e0dd0b7)

**Additional context**
Message: Interface/AddOns/ArkInventory/Core/ArkInventory.lua:12437: attempt to call global 'CloseBankFrame' (a nil value)
Time: Sat Jul 27 01:05:31 2024
Count: 1
Stack: Interface/AddOns/ArkInventory/Core/ArkInventory.lua:12437: attempt to call global 'CloseBankFrame' (a nil value)
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua"]:626: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:611>

Locals: self = <table> {
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 embeds = <table> {
 }
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}
addon = <table> {
 Action = <table> {
 }
 db = <table> {
 }
 Lib = <table> {
 }
 ENUM = <table> {
 }
 MailRecipients = <table> {
 }
 Table = <table> {
 }
 baseName = "ArkInventory"
 Search = <table> {
 }
 Tradeskill = <table> {
 }
 acedb = <table> {
 }
 Tools = <table> {
 }
 orderedModules = <table> {
 }
 LDB = <table> {
 }
 Const = <table> {
 }
 Global = <table> {
 }
 Localise = <table> {
 }
 name = "ArkInventory"
 Debug = <table> {
 }
 API = <table> {
 }
 defaultModuleState = true
 Collection = <table> {
 }
 modules = <table> {
 }
 CrossClient = <table> {
 }
 enabledState = true
 Config = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 hooks = <table> {
 }
}
AceAddon = <table> {
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 embeds = <table> {
 }
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}

**Comment by arkayenro** [comment]
please download the latest alpha if running war within
