### ISSUE TITLE
[BUG] Rule function "junk" and its alias "trash" cause an error

### ISSUE THREAD

**Issue by fubaWoW** [arkayenro/arkinventory#1939]
**What version number you are using?**
3.10.33-alpha-26

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Adding the condition ``and (not junk())`` or ``and (not trash())`` in any rule it will cause the complete rule system to break.

**To Reproduce**
this is my Rule:
``(not outfit()) and equip() and sb() and (not q(5, 6))``
this works as intended but...
add  ``and (not junk())`` or ``and (not trash())`` will cause the "collapse"

**Additional context**
error report https://github.com/arkayenro/arkinventory/issues/1924 was a fail as of i thought ``outfit()`` was the trigger of the error...  
but actually ``junk()`` and it's alias is it!

**Comment by arkayenro** [comment]
will be fixed in the next alpha
