### ISSUE TITLE
[BUG] Trader's Tender not treated as global currency

### ISSUE THREAD

**Issue by Talimar** [arkayenro/arkinventory#1940]
**What version number you are using?**
Alpha 27

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Tender is counted per character rather than per account.

**To Reproduce**
Steps to reproduce the behaviour, if possible:

**Screenshots**
https://i.imgur.com/lP9dkG5.jpeg

**Comment by arkayenro** [comment]
account wide currencies arent supported yet
