### ISSUE TITLE
Trying to do a clean install of ArkInventory, but encountering issues

### ISSUE THREAD

**Issue by jtwms1** [arkayenro/arkinventory#1942]
Version 31033, Retail, English, MacOS

I think I have cleaned out all my old settings, but when I reinstall via CurseForge, the bag window only shows "No Data", no items and no bag icons.

Clearly it's screwed up, but what can I do to really do a "clean install" so that I can use it again?

I have tried removing the saved variables, and then the addon via curseforge, then made manually that the following folders were removed in /World of Warcraft/_retail_/Interface/AddOns/

ArkInventoryConfig, ArkInventoryRules, ArkInventoryRules_Example, ArkInventorySearch, ArkInventory

I've also checked there were no ArkInventory related files in World of Warcraft/_retail_/WTF/Account/<ACCOUNT>/<REALM>/<CHARACTER>/SavedVariables/

I wonder if anyone has any advice, is there something else I need to do that I am missing?

**Comment by jtwms1** [comment]
screenshot:
![ArkInventoryissue](https://github.com/user-attachments/assets/1606c621-f1eb-4808-87c3-34f66d057289)

**Comment by arkayenro** [comment]
the only versions that support war within are the alpha versions, you will need to download the latest alpha

**Comment by jtwms1** [comment]
Thanks! Got it working with the alpha!
