### ISSUE TITLE
[BUG] Arkinventory showing entirely different items than what's in my bags.

### ISSUE THREAD

**Issue by Rycia** [arkayenro/arkinventory#1944]
**What version number you are using?**
![image](https://github.com/user-attachments/assets/a283775a-6f58-451d-b503-d35d770ded6b)
v31033

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Arkinventory is showing entirely different items than what's actually in my bags across all characters; exact same item set. I assume this is some sort of debug set of items.

**To Reproduce**
I hadn't played for the last 2 patches until prepatch systems got implemented, and I simply logged in and had issues with my bags while using Ark since (a few weeks.)

**Screenshots**
Here's what shows on Arkinventory:
![image](https://github.com/user-attachments/assets/7bea8506-1b06-4297-8fa6-b687b71469fc)
Keep in mind this EXACT set of items shows up no matter what character I play on regardless what's in my bags, even when they're empty.
![image](https://github.com/user-attachments/assets/3898e8ba-b7f9-4142-9570-24ef61c8c82d)
Here with ElvUI only I only have 3 items actually  in my bags.

**Additional context**
I have also tried deleting savedvariables for the addon, and nothing changed, multiple reinstalls, deleted ark's .lua files manually in savedvariables, ect.

**Comment by arkayenro** [comment]
use the alpha versions, those are the only ones that work properly at the moment

**Comment by damianjyates** [comment]
i installed the alpha version but the issue persists. any other suggestions?

**Comment by damianjyates** [comment]
just saw there was another version for alpha.  Giving it a try now

**Comment by Rycia** [comment]
Fixed with alpha version.
