### ISSUE TITLE
Warbank Gold Deposit/Withdraw

### ISSUE THREAD

**Issue by Biomedic32** [arkayenro/arkinventory#1945]
**Is your feature request related to a problem? Please describe.**
Arkinv does not have the ability (at least that I can find) to deposit and withdraw gold to and from your warbank

**Describe the solution you'd like**
Same as default basically, just a datatext of how much gold is in there and a withdraw/deposit button

**Describe alternatives you've considered**
Only current alternative is to disable bank override and do it on default ,then re-enable

**Additional context**
Probably in the works, just wanted to make sure it was on the radar if it wasnt already

**Comment by arkayenro** [comment]
in the status bar on the bank window, click the red button at the right hand edge, select deposit or withdraw
