### ISSUE TITLE
[BUG] Scroll bar length does not match window length

### ISSUE THREAD

**Issue by Biomedic32** [arkayenro/arkinventory#1946]
**What version number you are using?**
v31033.Alpha.27

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
The scroll bar length is not the same as the window frame. Unsure of what exactly its bound to, doesnt seem to be the bars or another subframe

**To Reproduce**
exceed the size of the window with items such that a scroll bar appears

**Screenshots**
Attached
![image](https://github.com/user-attachments/assets/2d4ca4d8-ae3d-4fe7-9768-0fd740b8d31b)

**Additional context**

**Comment by arkayenro** [comment]
it works fine though?  its just a cosmetic issue correct?

**Comment by arkayenro** [comment]
it is anchored to the container frame but its got a 30 pixel offset for the up/down handlers
looks like they got resized by half at some point and i didnt readjust the offsets
will be fixed in the next alpha

**Comment by Biomedic32** [comment]
Correct, this is just a cosmetic issue

**Comment by arkayenro** [comment]
fixed in alpha 28

**Comment by Biomedic32** [comment]
excellent thank you!
