### ISSUE TITLE
Left clicking bag in Bank - Bag Changer "lifts" the bag instead of changing displayed bank to that "bag"

### ISSUE THREAD

**Issue by Incandio** [arkayenro/arkinventory#1955]
**What version number you are using?**

3.10.33 alpha 29
**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
retail

**What language is the game client set to?**
Eng

**Describe the bug**
Left clicking other icons on Bag Changer works as expected (shifts to that "tab"). But bank bags are lifted as though they are going to be moved.

**To Reproduce**
Steps to reproduce the behaviour, if possible: Follow steps above. Try to select a bank "bag".

**Comment by arkayenro** [comment]
can you clarify - you have the reagent bank or one of the account bank tabs active and clicking on a bank bag picks it up instead of activating the bank?

**Comment by Incandio** [comment]
Actually I can only have the main bank tab active (the OG bank with 28 slots). I can't open any of the 7 "bag" bank tabs at all.

I interact with a banker, the bank window comes up. Only the OG bank tab shown now (this is new), whereas before the entire bank / reagent bag / warbank were in one giant window. So, to view what's in the various banks I have to click on the relevant part of the Bag Changer.

The Bag Changer row has several icons, starts with the OG bank, then the 7 bag slots, then the Reagent Bank, then the warbank slots. All the slots that don't require bags are fine. If I click on any of the bag icons (the ones where you buy a slot from the OG bank and use a bag in it) the bag lifts off like to move it across (I think the technical term is a sticky click?) Right click shows the Arkinventory window as expected.

**Comment by arkayenro** [comment]
are the icons in the bag slots tinted red?  try right clicking on the main bank bag and select display all

**Comment by Incandio** [comment]
![image](https://github.com/user-attachments/assets/eb55e4d8-3baa-49dc-9951-68f60fb5d844)
This is the left click action.

**Comment by Incandio** [comment]
I noticed something else. I can click on one of the bank bags if I select a warbank bag first. But then the problem above occurs and I can't select any other bank bags. I have to click back on a warbank bag to "release" the bank bags.

**Comment by Incandio** [comment]
Ah, I've figured out what's happening. I had "show empty" deselected so the entire bank window looked really small and I thought it was just showing one bag.
