### ISSUE TITLE
[BUG] Error when scrolling over some items in guild bank

### ISSUE THREAD

**Issue by dan-fwr** [arkayenro/arkinventory#1958]
LIVE

When I scroll over items in the guild bank, the following error appears:

Message: ...ace/AddOns/ArkInventory/Core/ArkInventoryStorage.lua:960: attempt to index global 'active_map' (a nil value)
Time: Sun Aug  4 07:59:37 2024
Count: 9
Stack: ...ace/AddOns/ArkInventory/Core/ArkInventoryStorage.lua:960: attempt to index global 'active_map' (a nil value)
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceBucket/AceBucket-3.0.lua"]:69: in function <...Inventory/Externals/Ace3/AceBucket/AceBucket-3.0.lua:67>
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceBucket/AceBucket-3.0.lua"]:83: in function `func'
[string "@Interface/AddOns/WeakAuras/Libs/AceTimer-3.0/AceTimer-3.0.lua"]:57: in function <.../AddOns/WeakAuras/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals: 

It seems to be random as to what item triggers it.  Although quest starting items do it more often.

**Comment by arkayenro** [comment]
bad code, it should error every time you change vault tabs. i dont think it will cause any real issues though.

will be fixed in the next alpha.

**Comment by dan-fwr** [comment]
Thanks.  It does not affect game play.
