### ISSUE TITLE
[BUG] alpha-32/alpha-33 issues

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1959]
**What version number you are using?**
alpha-32

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
- getting the LUA error below when opening warbank
- when trying to deposit items into warbank, they go into the regular bank instead (this was already working fine in alpha-31)
- layout assigned to regular bank is not being applied (working in earlier versions)
- search function in bank window is broken, doesn't find some items (working in earlier versions)

the error:
1x ArkInventory/Core/ArkInventoryUtil.lua:182: ERROR> Map.Blizzard[12] is not mapped
[string "=[C]"]: in function `error'
[string "@ArkInventory/Core/ArkInventoryUtil.lua"]:13: in function <ArkInventory/Core/ArkInventoryUtil.lua:11>
[string "@ArkInventory/Core/ArkInventoryUtil.lua"]:22: in function `Assert'
[string "@ArkInventory/Core/ArkInventoryUtil.lua"]:182: in function `MapGetBlizzard'
[string "@ArkInventory/Core/ArkInventoryUtil.lua"]:196: in function `getStorageIdFromBlizzardBagId'
[string "@ArkInventory/Core/ArkInventoryStorage.lua"]:634: in function `?'
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@TomTom/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...aceTomTom/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = "|cffff2020ERROR> Map.Blizzard[12] is not mapped"

**To Reproduce**
- open warbank
- try to deposit items into warbank with right-click
- open regular bank, see layout not being applied
- try to search in regular bank (e.g. "haw" does not find Hawk Owl)

**Screenshots**
N/A

**Additional context**
All of the above are new issues with this version.
Alpha-31 is mostly working but generates a lot of errors with warbank and guild bank.

**Comment by arkayenro** [comment]
crud, was meant to hide the 7th bank slot before wrath but coded it to after

will be fixed in the next alpha

**Comment by arkayenro** [comment]
how are you trying to deposit items?  just a right click on an item in your bags? or drag and drop?  although im not getting errors with either.

what do you mean by layout not applied?

normal bank searching looks ok, but it looks like searching only applies to the first account bank tab if you combine them

**Comment by hollo6** [comment]
I was trying to deposit items with right-click, didn't try drag&drop because I thought that was already working before, you fixed right-click deposit in alpha-30 and guessed that fix broke later.

By layout not applied I mean I have bars assigned with categories and it looked like i didn't have any, everything was in 1 space all together without any kind of system. I think the correct word should've been blueprint.

You're probably right about searching, I just couldn't find the pattern. I do use combined bank.

**Comment by hollo6** [comment]
Did a quick test with alpha-33 and these seems alright at a first glance.

However, now gbank won't remember which tab it was open at, is this intentional?

**Comment by hollo6** [comment]
Also, search bar disappeared from the bag frame.

**Comment by arkayenro** [comment]
right click on the search icon to toggle the display of the search bar, or via the config options?

if its there then disappears there should be an error

**Comment by hollo6** [comment]
Huh. Never knew right-clicking that icon would invoke a different action, I've no idea how it got toggled but this brought it back, thanks!

**Comment by hollo6** [comment]
So for now the only questions is if not remembering last used guild tab is intended or not.

**Comment by arkayenro** [comment]
its intended. the bank and vault reset on each open in the default ui and theyre both now properly linked to those frames

previously i didnt care but with the account bank it was causing issues with the right click destination so now what you do in ai is sent back to them so they update as if you had done it there, which then sets everything properly.

**Comment by hollo6** [comment]
Thank you for the explanation!
I can live without this feature and it's always good to only override as little as possible.
I have not seen any LUA errors or odd behavior for these things with alpha-33 so I'm deeming all this fixed, thanks!
