### ISSUE TITLE
[BUG] Switch Character menu only shows current realm

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1961]
**What version number you are using?**
alpha-33

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
Trying to look at other toons' bags or bank but the "Switch Character" menu only shows the ones from the server where I'm currently logged in at. I should be able to look at all characters from here. The data is there, it shows up on tooltips but can't look at the actual bags/banks this way.

**To Reproduce**
Have characters on multiple realms.
Open "Switch Character" menu.
See that only current realm is shown and there is no way to select others.

**Comment by arkayenro** [comment]
there should be an option down the bottom "Other" to select different realms.

**Comment by hollo6** [comment]
I don't have such an option.
![image](https://github.com/user-attachments/assets/6e324970-a2a3-4af4-a991-a846a6511f21)

**Comment by arkayenro** [comment]
if you log into one of the other characters does it then update?

theres a value it checks, basically the slot count for that storage location, which determines if the character is displayed in that list or not.

the item count code references that same value so im not sure how theyre getting different results

**Comment by hollo6** [comment]
I've tried to log in to numerous characters across multiple servers and I only ever see the current realm listed in this menu.

**Comment by arkayenro** [comment]
just to make sure, if you log into a character that isnt on ragnaros does the realm name at the top of that list shift to that realm and show that character (along with the other characters on that realm)?

with that character paste this - eeplacing `player_id` with `charactername - servername` (its case sensitive so has to match their names) - into the chat

`/dump ArkInventory.db.player.data["player_id"].info`

then replace it with a character from a different realm and let me know if the `realm` value is correct or not

you can also check the savedvariables file as well if thats easier

**Comment by hollo6** [comment]
Yes, the realm value and all the other info are correct in the dump for all characters on other realms.
And yes, the realm name is always correct at the top of the menu, see my first screenshot from Minahonda.

**Comment by hollo6** [comment]
I just compared some dumps and found that the attributes that are present in them match for characters on the same realm I'm currently on (including the one I'm on), but the `player_id=` field is not present in those on other realms, it is instead replaced by `class_local=` and its value is a non-capitalized equivalent of the `class` field.

**Comment by hollo6** [comment]
Today this menu suddenly appeared without me changing anything.
Dumps still have the same disparity as yesterday but the Other row is there now. Weird.

**Comment by hollo6** [comment]
Today I had the "Other" row suddenly appear and found out that it was because I logged in on a character on a 3rd realm.
After deleting the data of that character, it disappeared again.
Then I tested some use cases with other realms and concluded that the option goes missing if there are data present from less than 3 realms.

**Comment by arkayenro** [comment]
ah, its not including the current realm in the realm array.  will be fixed in the next alpha

**Comment by hollo6** [comment]
Indeed fixed in alpha-37, thanks!
