### ISSUE TITLE
When I add anything new to my bags it doesn't show up as being there

### ISSUE THREAD

**Issue by Immolata** [arkayenro/arkinventory#1963]
**What version number you are using?**

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**

**What language is the game client set to?**

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour, if possible:

**Screenshots**

**Additional context**

**Comment by arkayenro** [comment]
first of all,  I love this addon!  When I add anything new to my bags it doesn't show up as being there..  Can you help with this please?[BUG] Short description of your issue.  I am using version 3.10.33.zip playing retail. version 10.2.7

**Comment by arkayenro** [comment]
please make sure you are installing the alpha versions
