### ISSUE TITLE
[BUG] Search won't find several items

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1964]
**What version number you are using?**
alpha-34

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
When using the Search window, the ZG coin items (e.g. Bloodscalp Coin, Hakkari Coin, Vilebranch Coin) cannot be found by any part of their name. The inventory is being shown correctly on the items' tooltips so the data is there, but the search window won't find any of them.

**To Reproduce**
Have any of the ZG coins in any character's inventory.
Open Search window and enter any string that should match the coins' name.
Other items that match the search string are being shown but none of the coins.

**Comment by hollo6** [comment]
Just realized that the Search field at the top of bag/bank windows won't find them either.

**Comment by hollo6** [comment]
I just found a bunch of other items that neither the search window nor the field won't find for any string:
Dark Iron Ore
Mark of the Illidari
Relic of Ulduar

At first I thought because Dark Iron Ore was for some reason by default had the assigned category Consumables > Reputation, I have manually changed it but no luck.

Also tried to move these items around (bag, bank, reagent bank, guild bank, warbank) but that doesn't make a difference either.

**Comment by arkayenro** [comment]
its probably that the game servers didnt return the item info within 5 retries so it gave up asking for it

**Comment by arkayenro** [comment]
put "data not found" into the search window, if it matches on those items then they timed out, if they dont then its something else

**Comment by hollo6** [comment]
Interesting, this does find these items.
But it's weird because it's always the same items and they are always have the correct stock in the tooltip.

**Comment by arkayenro** [comment]
thye'll all be reputation items, ones that dont have "gain x rep with" text on them

i was setting the underlying object name to "data not found" for items that timed out, but those rep items will never pass because it cant work out how much rep they are worth.

that will still happen but im not replacing the name any more, and using another method to cater for dead data after too many retries.

**Comment by hollo6** [comment]
They are not all reputation items: Runecloth (but not Bolt of Runecloth), Blood of the Mountain, ZG coins, Sinstones, Sinstone Fragments, Core Leather, Dark Iron Ore, Arakkoa Feather, Quivering Firestorm Egg - some examples that are not even related to rep.
There are a lot that are somewhat related, as in they can somehow be turend into rep (turnins and items that can be used as currency), but not items that would actually give rep.

**Comment by arkayenro** [comment]
everything in the rep category is checked, and yes, item turnins would be in the rep category (which most of the ones you listed are)

**Comment by hollo6** [comment]
Indeed looks all good now, thank you!
