### ISSUE TITLE
[BUG] crafting() rule function error

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1966]
**What version number you are using?**
alpha-37

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
Trying to use a rule containing crafting() which is not included on the Wiki page but I found it in the code and looked like should be something useable.
Currently it returns an error printout that says it's an invalid rule, so I looked at the code and found in ArkInventoryRules.lua L320, a possible oversight:
	return ArkInventoryRules.Object.**osd**.info.craft

I changed this to:
	return ArkInventoryRules.Object.info.craft

And it's now working (does not give an error) and doing exactly what I'd expect.

**To Reproduce**
Create a rule including `crafting()` function.

**Comment by arkayenro** [comment]
good catch. will be fixed in the next alpha

not sure why its not documented though, possibly because i wasnt sure if it was needed as you can access all of the info/osd attributes directly without a function, eg `crafting( )` is the same as `i.info.craft` in a rule

**Comment by hollo6** [comment]
Oh, did not know that I can use that kind of condition in rules, but it's been a long time I've read the wiki page, sorry if I missed that. :)
Thanks!

**Comment by arkayenro** [comment]
https://github.com/arkayenro/arkinventory/wiki/RuleVariables

it wasnt in there either, so i updated that page

**Comment by hollo6** [comment]
Awesome, thank you!

**Comment by hollo6** [comment]
Fixed in alpha-38. :)
