### ISSUE TITLE
A button to transfer every item from bank/bag/warbank matching current text filter like in baganator.

### ISSUE THREAD

**Issue by cgsub** [arkayenro/arkinventory#1968]
**Is your feature request related to a problem? Please describe.**
No just annoying to have to manually click every item.

**Describe the solution you'd like**
A simple button to click to automate the trandfer, like you can find in the Baganator addon

**Describe alternatives you've considered**
Baganator.

**Additional context**
Useful when transferring a lot of items at once.

**Comment by arkayenro** [comment]
do you mean the deposit all reagents and deposit all warbank options?  they should be on the reagent bank slot and account bank slot right click menu
