### ISSUE TITLE
[BUG] Warbound / Warbound until equipped items randomly change category between logins

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1970]
**What version number you are using?**
alpha-38

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
Some logins, items that normally have the default category "Warbound" or "Warbound until equipped" (e.g. Dalaran Defender's *), are being changed to System > Equipment. Reload won't fix it but it may be ok again on next login.
Noticed it first in this version.

**To Reproduce**
Not sure how to trigger this, on some logins it happens, on some it does not.

**Comment by arkayenro** [comment]
if you go into edit mode and click on the items is their default category set to [0469] equipment (warbound until equipped)?

**Comment by hollo6** [comment]
No, that's how I found out they changed the category. I didn't change any of these items' category manually, I noticed this because I had the Warbound and Warbound until equipped assigned to bars and they suddenly appeared elsewhere.
So, they have the Default: [0469] assigned normally but they sometimes change to Default: [0414].

**Comment by hollo6** [comment]
As I was trying to find a way to reproduce this, the following just happened:
- I had a [0469] item in my bag and some in my warbank
- the item in my bag got the correct 0469 assigned to it
- every item in the warbank, except the one that was the same as in my bag, got 0414

**Comment by arkayenro** [comment]
did it only start happening in 38, or was it in earlier alphas?

**Comment by hollo6** [comment]
I only noticed it in 38, will try earlier versions now.

**Comment by arkayenro** [comment]
if its what i think it is it should only happen in 38

**Comment by hollo6** [comment]
Yes! I just found a way to reproduce it - login on a character, log out, then login on a different one, subsequent logins on the same character don't trigger it.
And it does not happen in 37.

**Comment by arkayenro** [comment]
yeah, the initial logins dont have the tooltip data quick enough, reloads do

because the toooltip isnt ready it cant work out the soulbound state so it falls back to the default equipment category

i commented out some is item ready checks as it was causing multiple rescans for no real reason

will need to recode it to only rescan on a tooltip not ready, not an item not ready (those get updated later anyway)

**Comment by arkayenro** [comment]
should be fixed in alpha 39 (i think)

**Comment by hollo6** [comment]
will test as soon as it appears

**Comment by hollo6** [comment]
Looks good after a few quick tests. :) I will keep an eye on this for a while,

**Comment by hollo6** [comment]
Not seeing this issue anymore. 👍
