### ISSUE TITLE
Bank turned off?

### ISSUE THREAD

**Issue by HarryyPropper** [arkayenro/arkinventory#1971]
3,10,33-alpha-39

Retail

Germany

Want to turn off the bank complet. If i turn off "overdrive" still a window there.
![Bild_2024-08-11_092736801](https://github.com/user-attachments/assets/1ee42f5a-0eca-4e58-ad7d-4b598f2073dd)

**Comment by arkayenro** [comment]
if you turned off override then that image looks normal - its the default bank ui

if you mean that little green bag icon, thats a shortcut to turn the override back on, its always going to be there.

**Comment by HarryyPropper** [comment]
but i cant turn it off complet
i use elvui and the arkinventory still is up
![image](https://github.com/user-attachments/assets/82639620-76c5-4bf4-9928-5f373c936d96)

if i turn on the bug mode from elvui the bank is gone. So its from arkinventory that the window is there

**Comment by arkayenro** [comment]
its not happening for me, can you disable elvui completely and see if it still happens.
