### ISSUE TITLE
[BUG] Map.Window[9] is not mapped

### ISSUE THREAD

**Issue by rbpaiett** [arkayenro/arkinventory#1974]
**What version number you are using?**
31100

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Classic Era

**What language is the game client set to?**
English

**Describe the bug**
Message: ...erface/AddOns/ArkInventory/Core/ArkInventoryUtil.lua:381: ERROR> Map.Window[9] is not mapped
Time: Sun Aug 11 19:23:26 2024
Count: 1
Stack: ...erface/AddOns/ArkInventory/Core/ArkInventoryUtil.lua:381: ERROR> Map.Window[9] is not mapped
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryUtil.lua"]:381: in function `MapGetChildren'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryStorage.lua"]:29: in function `EraseSavedData'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryUpgrades.lua"]:2241: in function `DatabaseUpgradePostLoad'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:3140: in function <Interface/AddOns/ArkInventory/Core/ArkInventory.lua:3093>
[string "=[C]"]: ?
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: loc_id_window = 9
Map = <table> {
 Blizzard = <table> {
 }
 Window = <table> {
 }
 Storage = <table> {
 }
}

**To Reproduce**
All I have to do is reload/relog, etc.  When I click on my bags, it says No Data.

**Screenshots**

**Additional context**
I just came from an AQ40 raid, arrived at Stormwind and then reloaded and that's when the error appeared.  I tried logging off and no go.  I even tried reinstalling with no success.  I have yet to try deleting saved variables.

**Comment by arkayenro** [comment]
ah, its trying to erase the currency data but classic doesnt have currency so its failing

will be fixed in the next alpha

**Comment by rbpaiett** [comment]
Excellent!

**Comment by rbpaiett** [comment]
How do I gain access to the Alpha you mentioned?

**Comment by arkayenro** [comment]
if you use a download client you typically have to tell them to look for alpha versions, that will depend on the download client.

if your manually downloading from curseforge then click on the option two show alphas in the file list
