### ISSUE TITLE
[BUG] Right-click deposits to personal bank instead of warbank on second open

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1975]
**What version number you are using?**
31100 alpha-1

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
I believe the issue concerns this change:
fixed - when opening the bank it should remember which bag/tab you previously had open (current session only)

This would be real nice but then it caues that upon opening the bank frame for the second time after switching to warbank, it shows the warbank again but the items from the bag will be deposited into the personal bank instead.

**To Reproduce**
1. open warbank
2. close frame
3. open bank, warbank frame is still being shown
4. right-click on an item in inventory
5. the item went to the personal bank instead
 
**Additional context**
Wasn't a problem in earlier versions when the first tab (personal bank or gbank tab1) were always shown on subsequent openings.

**Comment by arkayenro** [comment]
i cant duplicate it?  is the correct bag/tab still highlighted when you open it the second time?

is that bag/tab full?

it should only end up in your personal bank if theres an error, as it falls back on the blizzard code to handle it when that happens.

**Comment by arkayenro** [comment]
could you open the bank, change to an account bank tab, close, open the bank, type this in the chat window

`/dump ArkInventory.Util.getWindowActiveMap( ArkInventory.Const.Location.Bank )`

is the `loc_id_storage` value `20`, `19`, or `3`

**Comment by hollo6** [comment]
I think I found the problem.

With this version, I started getting a "That bag is full." error message every time I tried to deposit something in the warbank, even if it eventually went through. This never happened in earlier versions.

So I tested some scenarios:
(All tests were made with items that are eligible to be deposited into warbank.
Warbank slot stays highlighted on second open as it should. What's shown is correct, the problem is the discrepancy between what's shown and what happens.)
1. warbank tab1 full:
  - on first open, always getting the bag full error but the items eventually get deposited into the warbank as expected (the error is not expected though)
  - on second open, still getting the same error but now the items always go into the personal bank
 2. warbank tab1 not full:
   - not getting error messages and items are being deposited into warbank correctly on first and subsequent opens
 3. warbank tab1 has 1 empty slot:
   - on first open, first item gets deposited into warbank without error, subsequent items go into warbank but with error
   - on second open, first item goes into warbank, then I get the error and they go into personal bank
 
My conclusion is that when the warbank tab1 is full, deposit falls back to personal bank instead of warbank2...n.

**Comment by arkayenro** [comment]
ah, ok, the default bank ui isnt staying in sync on re-opens.  it stays at the bank which explains why things are ending up in there.

the default ui only will move an item into the warbank based on the bag filters that have been set.  it starts on tab 1 and works its way up.  if you have tab 3 open and theres an empty slot on tab 1 then thats where the deafult ui will put it.  it makes a sort of sense but only if all the tabs were shown at once, and they arent, so it doesnt really make any sense to do it that way.

there is no api to deposit an item into a specific account bank tab, so i've been faking that by looking for an empty slot on the active tab and then picking the item up and dropping it there, its why the moves are so slow.

thats also why you get the bag full error. i generate that and then it falls back to blizzard to move it. without a good api its going to be messy.

**Comment by arkayenro** [comment]
should be fixed in the next alpha

**Comment by hollo6** [comment]
Now the window won't remember that warbank was opened last. Is this intended?

**Comment by hollo6** [comment]
Alpha-3 status: 
- warbank remembers being opened and depositing to it works
- guild bank won't remember which tab it was opened at
- categories sometimes disappear (similar to https://github.com/arkayenro/arkinventory/issues/1970) and getting a new error but this is quite sporadic, might be caused by other addons' errors.

**Comment by arkayenro** [comment]
i havent made the guild bank sync up yet, its going to reset to tab 1 each time.
its on my list of things to do

**Comment by hollo6** [comment]
This is what's probably causing the category issue:

32x ArkInventory/Core/ArkInventory.lua:9148: attempt to index local 'tooltipInfo' (a nil value)
[string "@ArkInventory/Core/ArkInventory.lua"]:9148: in function `Frame_Item_UpdateTooltip'
[string "@ArkInventory/Core/ArkInventory.lua"]:9325: in function `Frame_Item_OnEnter'
[string "*ArkInventory.xml:353_OnEnter"]:1: in function <[string "*ArkInventory.xml:353_OnEnter"]:1>

Locals:
frame = ARKINV_Frame3ScrollContainerBag5Item17 {
 IconOverlay = Texture {
 }
 AugmentBorderAnim = AnimationGroup {
 }
 showMatchHighlight = true
 icon = ARKINV_Frame3ScrollContainerBag5Item17IconTexture {
 }
 count = 1
 ArkTint = ARKINV_Frame3ScrollContainerBag5Item17ArkTint {
 }
 HighlightTexture = Texture {
 }
 ArkBorder = ARKINV_Frame3ScrollContainerBag5Item17ArkBorder {
 }
 itemContextMatchResult = 1
 flash = Texture {
 }
 isProfessionItem = false
 IconQuestTexture = ARKINV_Frame3ScrollContainerBag5Item17IconQuestTexture {
 }
 hasItem = 1
 locked = false
 ExtendedSlot = Texture {
 }
 PushedTexture = Texture {
 }
 timeSinceUpgradeCheck = 0
 emptyBackgroundAtlas = "bags-item-slot64"
 BattlepayItemTexture = Texture {
 }
 Count = ARKINV_Frame3ScrollContainerBag5Item17Count {
 }
 searchOverlay = ARKINV_Frame3ScrollContainerBag5Item17SearchOverlay {
 }
 ArkIconTransmog = ARKINV_Frame3ScrollContainerBag5Item17ArkIconTransmog {
 }
 NormalTexture = ARKINV_Frame3ScrollContainerBag5Item17NormalTexture {
 }
 IconOverlay2 = Texture {
 }
 ArkItemAge = ARKINV_Frame3ScrollContainerBag5Item17ArkItemAge {
 }
 ArkLevel = ARKINV_Frame3ScrollContainerBag5Item17Level {
 }
 ArkIconProfessionRankText = ARKINV_Frame3ScrollContainerBag5Item17ArkIconProfessionRankText {
 }
 ArkIconProfessionRank = ARKINV_Frame3ScrollContainerBag5Item17ArkIconProfessionRank {
 }
 flashAnim = AnimationGroup {
 }
 newitemglowAnim = AnimationGroup {
 }
 JunkIcon = Texture {
 }
 ArkHighlight = ARKINV_Frame3ScrollContainerBag5Item17ArkHighlight {
 }
 ArkIconCorrupted = ARKINV_Frame3ScrollContainerBag5Item17ArkIconCorrupted {
 }
 ARK_Data = <table> {
 }
 NewItemTexture = Texture {
 }
 isCraftedItem = false
 AugmentBorderAnimTexture = Texture {
 }
 UpgradeIcon = Texture {
 }
 ArkIconQuestBang = ARKINV_Frame3ScrollContainerBag5Item17ArkIconQuestBang {
 }
 IconBorder = Texture {
 }
 Cooldown = ARKINV_Frame3ScrollContainerBag5Item17Cooldown {
 }
 ItemContextOverlay = Texture {
 }
 ArkListEntry = ARKINV_Frame3ScrollContainerBag5Item17ArkListEntry {
 }
 BagIndicator = Texture {
 }
 Stock = ARKINV_Frame3ScrollContainerBag5Item17Stock {
 }
 readable = false
}
blizzard_id = 9
loc_id_window = 3
bag_id_window = 5
slot_id = 17
i = <table> {
 loc_id = 3
 count = 1
 sb = 0
 h = "|cff0070dd|Hbattlepet:2001:1:3:158:11:10:0000000000000000:74513|h[Dibbler]|h|r"
 bag_id = 5
 slot_id = 17
}
map = <table> {
 bag_id_window = 5
 panel_id = 1
 inv_id = 95
 bag_id_storage = 5
 loc_id_window = 3
 blizzard_id = 9
 loc_id_storage = 3
}
loc_id_storage = 3
bag_id_storage = 5
reset = true
tooltipInfo = nil
showSell = nil
(*temporary) = ARKINV_Frame3ScrollContainerBag5Item17 {
 IconOverlay = Texture {
 }
 AugmentBorderAnim = AnimationGroup {
 }
 showMatchHighlight = true
 icon = ARKINV_Frame3ScrollContainerBag5Item17IconTexture {
 }
 count = 1
 ArkTint = ARKINV_Frame3ScrollContainerBag5Item17ArkTint {
 }
 HighlightTexture = Texture {
 }
 ArkBorder = ARKINV_Frame3ScrollContainerBag5Item17ArkBorder {
 }
 itemContextMatchResult = 1
 flash = Texture {
 }
 isProfessionItem = false
 IconQuestTexture = ARKINV_Frame3ScrollContainerBag5Item17IconQuestTexture {
 }
 hasItem = 1
 locked = false
 ExtendedSlot = Texture {
 }
 PushedTexture = Texture {
 }
 timeSinceUpgradeCheck = 0
 emptyBackgroundAtlas = "bags-item-slot64"
 BattlepayItemTexture = Texture {
 }
 Count = ARKINV_Frame3ScrollContainerBag5Item17Count {
 }
 searchOverlay = ARKINV_Frame3ScrollContainerBag5Item17SearchOverlay {
 }
 ArkIconTransmog = ARKINV_Frame3ScrollContainerBag5Item17ArkIconTransmog {
 }
 NormalTexture = ARKINV_Frame3ScrollContainerBag5Item17NormalTexture {
 }
 IconOverlay2 = Texture {
 }
 ArkItemAge = ARKINV_Frame3ScrollContainerBag5Item17ArkItemAge {
 }
 ArkLevel = ARKINV_Frame3ScrollContainerBag5Item17Level {
 }
 ArkIconProfessionRankText = ARKINV_Frame3ScrollContainerBag5Item17ArkIconProfessionRankText {
 }
 ArkIconProfessionRank = ARKINV_Frame3ScrollContainerBag5Item17ArkIconProfessionRank {
 }
 flashAnim = AnimationGroup {
 }
 newitemglowAnim = AnimationGroup {
 }
 JunkIcon = Texture {
 }
 ArkHighlight = ARKINV_Frame3ScrollCont

**Comment by arkayenro** [comment]
that should be fixed in alpha 4

**Comment by hollo6** [comment]
Indeed it is! 👍
