### ISSUE TITLE
[BUG] Tint Unusable/Unwearable and offline frame takes precedence over search fade

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1976]
**What version number you are using?**
3.11.0-alpha1

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
If Tint Unusable and/or Tint Unwearable is enabled, it takes precedence over (or just way too prominent compared to) search fade.
This, in most situations, makes the search filter virtually useless because if there are a lot of tinted items in the bag, it's impossible to tell whether they are faded or not.

Also, I don't know if this is related or not but right now it is also impossible to use the search filter when looking at other character's bag/bank. "Fade offline" setting does not make any difference to this behavior (if it is enabled, everything is always faded, if disabled, everything is unfaded even after entering search term).

**To Reproduce**
tint:
1. enable Tint Unusable, Tint Unwearable
2. have some of those items in bag
3. enter a filter term in Search bar

offline:
1. open a bag/bank/gbank/wbank frame for another character via "Switch Character"
2. enter a filter term in Search bar
3. nothing changes, cannot see what matches the filter

**Screenshots**
tint:
![image](https://github.com/user-attachments/assets/eabb97f5-6af4-430a-be25-77bcd5d1c0eb)

offline:
![image](https://github.com/user-attachments/assets/f1efb075-f806-4cd8-b94b-90a0ce1e9fa5)

**Additional context**
Not sure when this changed but can't remember having the tint problem until a few weeks ago.
Filtering on "offline" frames was definitely working until recently.

**Comment by arkayenro** [comment]
will revert to hiding the item if it doesnt match the search filter

**Comment by hollo6** [comment]
Perfect, thank you!
