### ISSUE TITLE
[BUG] No content showing, bags marked as "Unknown" 

### ISSUE THREAD

**Issue by jenscodejens** [arkayenro/arkinventory#1977]
**v31034** (latest)

**Classic**

**English**

**Describe the bug**
The pictures will show the issues best, these issues impact _all_ characters.
I checked if it was just some kinda of enable bug on features but it was not.

- Other than that all my rules, the settings for categories etc are still there.
- Keyring shows up as it should including toys as well.
- The addon is now unaware of every other chars inventories & bank inventories as well.

**To Reproduce**
Cant help you there, just updated to latest version from a few hours ago and that is when it occourred.

**Screenshots**

![ark1](https://github.com/user-attachments/assets/03a5b29d-4811-42a4-95b5-061e1d2266dd)
![ark2](https://github.com/user-attachments/assets/289f0420-a7f2-4c77-ae95-1a2ea324e364)

**Additional context**
Just thanks for a kickass addon.

**Comment by arkayenro** [comment]
for classic youll need 3.11.00 alpha 1

**Comment by jenscodejens** [comment]
Yea, I tried it now before I read your comment. I might have misspelled but it speficially mentioned "If you use War Within" use alpha.
Either way it works, once again: kickass addon thank you so much for your work put into it :)
