### ISSUE TITLE
[BUG] Not working in 11.0.2

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1980]
**What version number you are using?**
alpha-3

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
Completely broken in 11.0.2. Opening any frame (bag/bank) shows an empty window and gives the following printout:
[08:03:29] ArkInventory: WARNING> ...face/AddOns/ArkInventory/Core/ArkInventoryAction.lua:145: attempt to call method 'isException' (a nil value)

LUA error:
18x ...faceArkInventory/Core/ArkInventoryAction.lua:145: attempt to call method 'isException' (a nil value)
[string "@ArkInventory/Core/ArkInventoryAction.lua"]:145: in function `Check'
[string "@ArkInventory/Core/ArkInventory.lua"]:7753: in function `Frame_Item_Update_StatusIconJunk'
[string "@ArkInventory/Core/ArkInventory.lua"]:10333: in function `Frame_Item_Update_Instant'
[string "@ArkInventory/Core/ArkInventoryStorage.lua"]:558: in function <...aceArkInventory/Core/ArkInventoryStorage.lua:548>
[string "=[C]"]: ?
[string "@ArkInventory/Externals/Ace3/AceBucket/AceBucket-3.0-4.lua"]:69: in function <...Inventory/Externals/Ace3/AceBucket/AceBucket-3.0.lua:67>
[string "@ArkInventory/Externals/Ace3/AceBucket/AceBucket-3.0-4.lua"]:83: in function `func'
[string "@WeakAuras/Libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <WeakAuras/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
codex = <table> {
 toon = <table> {
 }
 style_id = 1000
 profile_id = 1001
 catset_id = 1000
 layout_id = 1003
 player = <table> {
 }
 style = <table> {
 }
 workpad = <table> {
 }
 layout = <table> {
 }
 profile = <table> {
 }
 loc_id = 1
 catset = <table> {
 }
}
blizzard_id = 1
slot_id = 12
manual = true
delete = nil
isMatch = false
vendorPrice = -1
map = <table> {
 bag_id_window = 2
 panel_id = 1
 inv_id = 31
 bag_id_storage = 2
 loc_id_window = 1
 blizzard_id = 1
 loc_id_storage = 1
}
loc_id_window = 1
bag_id_window = 2
loc_id_storage = 1
bag_id_storage = 2
player_id = "Nahren - Ragnaros"
storage = <table> {
 data = <table> {
 }
}
bag = <table> {
 q = 4
 type = 1
 inv_id = 31
 bag_id = 2
 h = "|cffa335ee|Hitem:212335::::::::70:103:::::::::|h[Collector's Carryall]|h|r"
 count = 36
 slot = <table> {
 }
 status = -3
 empty = 21
 loc_id = 1
 texture = 5524917
}
i = <table> {
 age = 28726889
 h = "|cff0070dd|Hitem:184777::::::::70:103:::::::::|h[Gravedredger's Shovel]|h|r"
 slot_id = 12
 sb = 3
 loc_id = 1
 bag_id = 2
 count = 5
}
info = <table> {
 itemtypeid = 15
 ilvl = 1
 stacksize = 100
 hs = "item:184777:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0"
 itemsubtypeid = 4
 itemsubtype = "Other"
 h = "|cff0070dd|Hitem:184777::::::::70:103:::::::::|h[Gravedredger's Shovel]|h|r"
 retry = 1
 spell_name = "Deposit Anima"
 spell_id = 336327
 texture = 1059121
 q = 3
 expansion = 8
 stock = 35
 binding = 1
 id = 184777
 class = "item"
 ready = true
 craft = false
 vendorprice = 1000
 itemtype = "Miscellaneous"
 name = "Gravedredger's Shovel"
 osd = <table> {
 }
 equiploc = ""
 ilvl_base = 1
 uselevel = 0
}
ignore = false
(*temporary) = nil
(*temporary) = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 optionsFrame = <table> {
 }
 name = "SellJunk"
 orderedModules = <table> {
 }
 sellButton = Button {
 }
 enabledState = true
 baseName = "SellJunk"
 defaultModuleState = true
}
(*temporary) = "|cff0070dd|Hitem:184777::::::::70:103:::::::::|h[Gravedredger's Shovel]|h|r"
(*temporary) = "attempt to call method 'isException' (a nil value)"

**To Reproduce**
Open any bag or bank window.

**Screenshots**
![image](https://github.com/user-attachments/assets/6d25b08e-0e96-4b79-a7bb-4496314ac74a)

**Additional context**
Started happening in 11.0.2.

**Comment by hollo6** [comment]
Sorry nevermind, looked at the code and found out it was SellJunk.

**Comment by arkayenro** [comment]
i'll add some more checks in that should potentially work around that happening

**Comment by hollo6** [comment]
No need, I just updated SellJunk and this went away.
