### ISSUE TITLE
[BUG] LUA Error

### ISSUE THREAD

**Issue by fraerie** [arkayenro/arkinventory#1982]
**What version number you are using?**
ArkInventory-3.11.00-alpha-4

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail 11.0.2.56110

**What language is the game client set to?**
English

**Describe the bug**
LUA error output below

**To Reproduce**
TBH I don't know when it triggered. I was scrolling through other errors to post them and saw it.

**Screenshots**

**Additional context**

1x ArkInventory/Core/ArkInventory.lua:9140: attempt to index local 'tooltipInfo' (a nil value)
[string "@ArkInventory/Core/ArkInventory.lua"]:9140: in function `Frame_Item_UpdateTooltip'
[string "@ArkInventory/Core/ArkInventory.lua"]:9315: in function `Frame_Item_OnEnter'
[string "*ArkInventory.xml:353_OnEnter"]:1: in function <[string "*ArkInventory.xml:353_OnEnter"]:1>

Locals:
frame = ARKINV_Frame1ScrollContainerBag2Item18 {
 IconOverlay = Texture {
 }
 AugmentBorderAnim = AnimationGroup {
 }
 showMatchHighlight = true
 icon = ARKINV_Frame1ScrollContainerBag2Item18IconTexture {
 }
 count = 1
 ArkTint = ARKINV_Frame1ScrollContainerBag2Item18ArkTint {
 }
 HighlightTexture = Texture {
 }
 ArkBorder = ARKINV_Frame1ScrollContainerBag2Item18ArkBorder {
 }
 itemContextMatchResult = 1
 flash = Texture {
 }
 isProfessionItem = false
 IconQuestTexture = ARKINV_Frame1ScrollContainerBag2Item18IconQuestTexture {
 }
 hasItem = 1
 locked = false
 ExtendedSlot = Texture {
 }
 PushedTexture = Texture {
 }
 timeSinceUpgradeCheck = 0
 emptyBackgroundAtlas = "bags-item-slot64"
 BattlepayItemTexture = Texture {
 }
 Count = ARKINV_Frame1ScrollContainerBag2Item18Count {
 }
 searchOverlay = ARKINV_Frame1ScrollContainerBag2Item18SearchOverlay {
 }
 ArkIconTransmog = ARKINV_Frame1ScrollContainerBag2Item18ArkIconTransmog {
 }
 NormalTexture = ARKINV_Frame1ScrollContainerBag2Item18NormalTexture {
 }
 IconOverlay2 = Texture {
 }
 ArkItemAge = ARKINV_Frame1ScrollContainerBag2Item18ArkItemAge {
 }
 ArkLevel = ARKINV_Frame1ScrollContainerBag2Item18Level {
 }
 ArkIconProfessionRankText = ARKINV_Frame1ScrollContainerBag2Item18ArkIconProfessionRankText {
 }
 ArkIconProfessionRank = ARKINV_Frame1ScrollContainerBag2Item18ArkIconProfessionRank {
 }
 flashAnim = AnimationGroup {
 }
 newitemglowAnim = AnimationGroup {
 }
 JunkIcon = Texture {
 }
 ArkHighlight = ARKINV_Frame1ScrollContainerBag2Item18ArkHighlight {
 }
 ArkIconCorrupted = ARKINV_Frame1ScrollContainerBag2Item18ArkIconCorrupted {
 }
 ARK_Data = <table> {
 }
 NewItemTexture = Texture {
 }
 isCraftedItem = false
 AugmentBorderAnimTexture = Texture {
 }
 UpgradeIcon = Texture {
 }
 ArkIconQuestBang = ARKINV_Frame1ScrollContainerBag2Item18ArkIconQuestBang {
 }
 IconBorder = Texture {
 }
 Cooldown = ARKINV_Frame1ScrollContainerBag2Item18Cooldown {
 }
 CanIMogItOverlay = CIMIOverlayFrame_ARKINV_Frame1ScrollContainerBag2Item18 {
 }
 ItemContextOverlay = Texture {
 }
 ArkListEntry = ARKINV_Frame1ScrollContainerBag2Item18ArkListEntry {
 }
 BagIndicator = Texture {
 }
 Stock = ARKINV_Frame1ScrollContainerBag2Item18Stock {
 }
 readable = false
}
blizzard_id = 1
loc_id_window = 1
bag_id_window = 2
slot_id = 18
i = <table> {
 age = 28728257
 h = "|cff0070dd|Hbattlepet:3412:1:3:147:12:12:0000000000000000:109988|h[Gale Spirit]|h|r"
 count = 1
 sb = 0
 loc_id = 1
 bag_id = 2
 slot_id = 18
}
map = <table> {
 bag_id_window = 2
 panel_id = 1
 inv_id = 31
 bag_id_storage = 2
 loc_id_window = 1
 blizzard_id = 1
 loc_id_storage = 1
}
loc_id_storage = 1
bag_id_storage = 2
reset = true
tooltipInfo = nil
showSell = nil
(*temporary) = ARKINV_Frame1ScrollContainerBag2Item18 {
 IconOverlay = Texture {
 }
 AugmentBorderAnim = AnimationGroup {
 }
 showMatchHighlight = true
 icon = ARKINV_Frame1ScrollContainerBag2Item18IconTexture {
 }
 count = 1
 ArkTint = ARKINV_Frame1ScrollContainerBag2Item18ArkTint {
 }
 HighlightTexture = Texture {
 }
 ArkBorder = ARKINV_Frame1ScrollContainerBag2Item18ArkBorder {
 }
 itemContextMatchResult = 1
 flash = Texture {
 }
 isProfessionItem = false
 IconQuestTexture = ARKINV_Frame1ScrollContainerBag2Item18IconQuestTexture {
 }
 hasItem = 1
 locked = false
 ExtendedSlot = Texture {
 }
 PushedTexture = Texture {
 }
 timeSinceUpgradeCheck = 0
 emptyBackgroundAtlas = "bags-item-slot64"
 BattlepayItemTexture = Texture {
 }
 Count = ARKINV_Frame1ScrollContainerBag2Item18Count {
 }
 searchOverlay = ARKINV_Frame1ScrollContainerBag2Item18SearchOverlay {
 }
 ArkIconTransmog = ARKINV_Frame1ScrollContainerBag2Item18ArkIconTransmog {
 }
 NormalTexture = ARKINV_Frame1ScrollContainerBag2Item18NormalTexture {
 }
 IconOverlay2 = Texture {
 }
 ArkItemAge = ARKINV_Frame1ScrollContainerBag2Item18ArkItemAge {
 }
 ArkLevel = ARKINV_Frame1ScrollContainerBag2Item18Level {
 }
 ArkIconProfessionRankText = ARKINV_Frame1ScrollContainerBag2Item18ArkIconProfessionRankText {
 }
 ArkIconProfessionRank = ARKINV_Frame1ScrollContainerBag2Item18ArkIconProfessionRank {
 }
 flashAnim = AnimationGroup {
 }

**Comment by arkayenro** [comment]
try mousing over a battlepet in your bags.  i thought the error was fixed in alpha 1 though

**Comment by fraerie** [comment]
Verifying that mousing over a battle pet in my bags triggered this - I managed to replicate it.

**Comment by arkayenro** [comment]
now make sure you actually have alpha 4

open the bag
click on the main icon in the title bar
does it say 3.11.00 Alpha 4

**Comment by fraerie** [comment]
Grrrr - the Wago app had reverted me to v3.11.00 Release.

If I re-update to v3.11.00-alpha 4 the error is resolved. :(

I need to go poke Artemis - it honestly is not updating installed addon versions so much and keeps telling me I have older version s installed when I have just restarted both the game and the Wago app.
