### ISSUE TITLE
[BUG] Reagents getting deposited into regular bank instead of reagent bank

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1983]
**What version number you are using?**
alpha-4

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
Crafting reagents, when right-clicked, are going into regular bank instead of the reagent bank.
This was working fine in earlier versions, though I'm not sure which one this exactly changed in.
Previously when right-clicking a crafting reagent, it automatically went into the reagent bank.
I have plenty of available space in my reagent bank so the items should go there.

**To Reproduce**
Open bank.
Right-click any crafting reagent in bag.

**Comment by arkayenro** [comment]
yes, the warbank being added as a destination meant you have to select the reagent bank as the destination if thats where you want them to go.

it probably needs some work

**Comment by hollo6** [comment]
I see, thanks for the explanation.
We'd really appreciate this working again as it's such an integral part of everyday gameplay I even thought it was a game feature :D

**Comment by arkayenro** [comment]
ok, next alpha it should revert to the way it was originally working, so if you have the bank or reagent bank open and its a crafting material it will try to send it to the reagent bank first.

if it fails for any reason it will fall back to whatever blizzard does with it, which i cant stop from happening.

**Comment by hollo6** [comment]
Works as expected now, thank you!
