### ISSUE TITLE
[BUG] Auction storage frame stopped working

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1984]
**What version number you are using?**
alpha-4

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
Trying to open the auction storage location via "Locations" menu shows an empty window and the following printout:
[09:34:38] ArkInventory: ERROR> blizzard_id is [nil], should be [number]
[09:34:38] ArkInventory: WARNING> ...ace/AddOns/ArkInventory/Core/ArkInventoryStorage.lua:1875: ERROR> blizzard_id is [nil], should be [number]

**To Reproduce**
Click Locations -> Auctions

**Additional context**
All the other locations are working fine.

**Comment by arkayenro** [comment]
do you have the whole error trace?

**Comment by hollo6** [comment]
I don't get an actual LUA error, only this printout.

**Comment by hollo6** [comment]
Hmm, I just discovered that I only get this on one of the 2 of my toons that has auctions. It's working as expected on the other one.
I have no clue what's different though, I'm using the same set of related addons on both.

**Comment by arkayenro** [comment]
possibly bad data, open the config and go tot eh account tab, find the character and if they have account data you should be able to erase just that and see if it fixes it.

visiting the auction house should also clear it up (i think)

**Comment by hollo6** [comment]
I tried visiting the AH so it would refresh the data but it didn't help.
Erasing the auction data and rescanning it did the trick though, thanks!
