### ISSUE TITLE
[BUG] Mousing over caged Battle Pet gives a tooltip error

### ISSUE THREAD

**Issue by ala75** [arkayenro/arkinventory#1986]
**What version number you are using?**

3.11.0

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**

Retail

**What language is the game client set to?**

ENGLISH

**Describe the bug**

Caged a Battle Pet. The moment I mouse over the caged pet, no tooltip is shown and an error is generated

**To Reproduce**
Steps to reproduce the behaviour, if possible:

Caged a Battle Pet. Mouse over the caged pet. No tooltip is shown and an error is generated

**Screenshots**

**Additional context**

Generated error:

17x ArkInventory/Core/ArkInventory.lua:9140: attempt to index local 'tooltipInfo' (a nil value)
[string "@ArkInventory/Core/ArkInventory.lua"]:9140: in function `Frame_Item_UpdateTooltip'
[string "@ArkInventory/Core/ArkInventory.lua"]:9315: in function `Frame_Item_OnEnter'
[string "*ArkInventory.xml:353_OnEnter"]:1: in function <[string "*ArkInventory.xml:353_OnEnter"]:1>

Locals:
frame = ARKINV_Frame1ScrollContainerBag1Item3 {
 IconOverlay = Texture {
 }
 AugmentBorderAnim = AnimationGroup {
 }
 showMatchHighlight = true
 icon = ARKINV_Frame1ScrollContainerBag1Item3IconTexture {
 }
 count = 1
 ArkTint = ARKINV_Frame1ScrollContainerBag1Item3ArkTint {
 }
 HighlightTexture = Texture {
 }
 ArkBorder = ARKINV_Frame1ScrollContainerBag1Item3ArkBorder {
 }
 itemContextMatchResult = 1
 flash = Texture {
 }
 isProfessionItem = false
 IconQuestTexture = ARKINV_Frame1ScrollContainerBag1Item3IconQuestTexture {
 }
 hasItem = 1
 locked = false
 ExtendedSlot = Texture {
 }
 PushedTexture = Texture {
 }
 timeSinceUpgradeCheck = 0
 emptyBackgroundAtlas = "bags-item-slot64"
 BattlepayItemTexture = Texture {
 }
 Count = ARKINV_Frame1ScrollContainerBag1Item3Count {
 }
 searchOverlay = ARKINV_Frame1ScrollContainerBag1Item3SearchOverlay {
 }
 ArkIconTransmog = ARKINV_Frame1ScrollContainerBag1Item3ArkIconTransmog {
 }
 NormalTexture = ARKINV_Frame1ScrollContainerBag1Item3NormalTexture {
 }
 IconOverlay2 = Texture {
 }
 ArkItemAge = ARKINV_Frame1ScrollContainerBag1Item3ArkItemAge {
 }
 ArkLevel = ARKINV_Frame1ScrollContainerBag1Item3Level {
 }
 ArkIconProfessionRankText = ARKINV_Frame1ScrollContainerBag1Item3ArkIconProfessionRankText {
 }
 ArkIconProfessionRank = ARKINV_Frame1ScrollContainerBag1Item3ArkIconProfessionRank {
 }
 flashAnim = AnimationGroup {
 }
 newitemglowAnim = AnimationGroup {
 }
 JunkIcon = Texture {
 }
 ArkHighlight = ARKINV_Frame1ScrollContainerBag1Item3ArkHighlight {
 }
 ArkIconCorrupted = ARKINV_Frame1ScrollContainerBag1Item3ArkIconCorrupted {
 }
 ARK_Data = <table> {
 }
 NewItemTexture = Texture {
 }
 isCraftedItem = false
 AugmentBorderAnimTexture = Texture {
 }
 UpgradeIcon = Texture {
 }
 ArkIconQuestBang = ARKINV_Frame1ScrollContainerBag1Item3ArkIconQuestBang {
 }
 IconBorder = Texture {
 }
 Cooldown = ARKINV_Frame1ScrollContainerBag1Item3Cooldown {
 }
 ItemContextOverlay = Texture {
 }
 ArkListEntry = ARKINV_Frame1ScrollContainerBag1Item3ArkListEntry {
 }
 BagIndicator = Texture {
 }
 Stock = ARKINV_Frame1ScrollContainerBag1Item3Stock {
 }
 readable = false
}
blizzard_id = 0
loc_id_window = 1
bag_id_window = 1
slot_id = 3
i = <table> {
 h = "|cff0070dd|Hbattlepet:2084:1:3:149:12:12:0000000000000000:79641|h[Zephyrian Prince]|h|r"
 count = 1
 sb = 0
 loc_id = 1
 bag_id = 1
 slot_id = 3
}
map = <table> {
 loc_id_storage = 1
 loc_id_window = 1
 panel_id = 1
 bag_id_window = 1
 bag_id_storage = 1
 fixed = true
 blizzard_id = 0
 texture = "Interface\Icons\INV_Misc_Bag_07_Green"
}
loc_id_storage = 1
bag_id_storage = 1
reset = true
tooltipInfo = nil
showSell = nil
(*temporary) = ARKINV_Frame1ScrollContainerBag1Item3 {
 IconOverlay = Texture {
 }
 AugmentBorderAnim = AnimationGroup {
 }
 showMatchHighlight = true
 icon = ARKINV_Frame1ScrollContainerBag1Item3IconTexture {
 }
 count = 1
 ArkTint = ARKINV_Frame1ScrollContainerBag1Item3ArkTint {
 }
 HighlightTexture = Texture {
 }
 ArkBorder = ARKINV_Frame1ScrollContainerBag1Item3ArkBorder {
 }
 itemContextMatchResult = 1
 flash = Texture {
 }
 isProfessionItem = false
 IconQuestTexture = ARKINV_Frame1ScrollContainerBag1Item3IconQuestTexture {
 }
 hasItem = 1
 locked = false
 ExtendedSlot = Texture {
 }
 PushedTexture = Texture {
 }
 timeSinceUpgradeCheck = 0
 emptyBackgroundAtlas = "bags-item-slot64"
 BattlepayItemTexture = Texture {
 }
 Count = ARKINV_Frame1ScrollContainerBag1Item3Count {
 }
 searchOverlay = ARKINV_Frame1ScrollContainerBag1Item3SearchOverlay {
 }
 ArkIconTransmog = ARKINV_Frame1ScrollContainerBag1Item3ArkIconTransmog {
 }
 NormalTexture = ARKINV_Frame1ScrollContainerBag1Item3NormalTexture {
 }
 IconOverlay2 = Texture {
 }
 ArkItemAge = ARKINV_Frame1ScrollContainerBag1Item3ArkItemAge {
 }
 ArkLevel = ARKINV_Frame1ScrollContainerBag1Item3Level {
 }
 ArkIconProfessionRankText = ARKINV_Frame1ScrollContainerBag1Item3ArkIconProfessionRankText {
 }
 ArkIconProfessionRank = ARKINV_Frame1ScrollContainerBag1Item3ArkIconProfessionRank {
 }
 flashAnim = AnimationGroup {
 }
 newitemglowAnim = AnimationGroup {
 }
 JunkIcon = Texture {
 }
 ArkHighligh

**Comment by arkayenro** [comment]
youll need to install (at least) 3.11.00 alpha 1, its fixed in there

**Comment by ala75** [comment]
Ty!
