### ISSUE TITLE
[BUG] ArkInventoryStorage.lua:5521: attempt to index local 'i' (a nil value)

### ISSUE THREAD

**Issue by rbpaiett** [arkayenro/arkinventory#1988]
**What version number you are using?**
3.11.00-alpha-6

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Classic Era

**What language is the game client set to?**
English

**Describe the bug**
Lua error:
Message: ...ace/AddOns/ArkInventory/Core/ArkInventoryStorage.lua:5521: attempt to index local 'i' (a nil value)
Time: Thu Aug 22 11:14:56 2024
Count: 1
Stack: ...ace/AddOns/ArkInventory/Core/ArkInventoryStorage.lua:5521: attempt to index local 'i' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: (*temporary) = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:57

**To Reproduce**
Just logon.

**Screenshots**
N/A

**Additional context**
No other context.

**Comment by rbpaiett** [comment]
Ok, after deleting saved variables, the error disappeared.  I'll keep watch but I'll close the issue unless something related shows up.

**Comment by rbpaiett** [comment]
Ok, the error appeared again when I had only Arkinventory active.  It appeared after I disabled all addons and logged back on.  

Also, the error WARNING> Interface/Addons/ArkInventory/Core/Arkinventory.lua:14671: ERROR>thread_id is [nil], should be [string] appears when I open the Auction interface and open bag with inventory is enabled.

**Comment by arkayenro** [comment]
the first issue will be fixed in alpha 8 but i would need the full trace from the second to work it out

**Comment by rbpaiett** [comment]
Super, thanks!

**Comment by rbpaiett** [comment]
It's an odd one because bug sac doesn't pick it up. It does show up in chat only.

**Comment by rbpaiett** [comment]
The issue with the auction interface no longer appears after the latest update.

**Comment by rbpaiett** [comment]
Damn, when I logged on to a different char, the error re-appeared, sry about this :(

**Comment by rbpaiett** [comment]
I see someone has reported this so I'll close this and affirm in the other bug report.
