### ISSUE TITLE
[BUG] Arkinventory is disabled by blizzard on character currency Transfer

### ISSUE THREAD

**Issue by rpsalis** [arkayenro/arkinventory#1998]
**What version number you are using?**
v11.0.003

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Transfering Currenency from another character

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Transfer Currency from another character

**Screenshots**

**Additional context**

2x [ADDON_ACTION_FORBIDDEN] AddOn 'Altoholic' tried to call the protected function 'RequestCurrencyFromAccountCharacter()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `RequestCurrencyFromAccountCharacter'
[string "@Blizzard_TokenUI/Blizzard_CurrencyTransfer.lua"]:331: in function <...ddOns/Blizzard_TokenUI/Blizzard_CurrencyTransfer.lua:328>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

**Comment by rpsalis** [comment]
Forgot to mention the first time works but the 2nd cuases the error

**Comment by arkayenro** [comment]
i dont call that function, as per the error message its altoholic
