### ISSUE TITLE
[BUG] Classic Era Ammo / Special Items aren't moving to Ammo / Special Item bags on Restack

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#2008]
**What version number you are using?**

Latest Alpha on Curseforge

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**

Classic Era

**What language is the game client set to?**

Engrish.

**Describe the bug**

<img width="424" alt="image" src="https://github.com/user-attachments/assets/2d681a20-9021-4d5a-822b-5db334dfda95">

Ammo doesn't move to ammo bags on restack.

Mentioned this also https://github.com/arkayenro/arkinventory/issues/2000

**To Reproduce**
Steps to reproduce the behaviour, if possible:

Have a quiver, or other special bags, and hit restack. The items don't move to that bag.

**Screenshots**

**Additional context**

**Comment by Gogo1951** [comment]
Admittedly, I don't really understand this section yet.

<img width="782" alt="image" src="https://github.com/user-attachments/assets/b3a78e81-5441-4600-85bb-e43259d828bb">

**Comment by arkayenro** [comment]
restack has been limited to crafting items until very recently.

reagent items were added in 3.11.01 alpha 2
projectiles (ammo) was added in 3.11.01 alpha 4

when restacking the priority sets what order teh bags are restacked in.  higher bags can pull items out of lower bags but not the other way around.

if you wanted the reagent bank/bag filled up first (and take from profession bags) you make it higher than profession bags.

**Comment by Gogo1951** [comment]
Thanks. I just wanted arrows put in the quiver when I did a re-stack in Classic Era. Is it possible to have that logic back again? At least for Classic Era?

**Comment by arkayenro** [comment]
it was never there.  ammo was added in alpha 4.  download any version after that

**Comment by Gogo1951** [comment]
Maybe we're talking about different things?

I've been away from WoW for a few years, but like back in the day when you hit "restack" it put Arrows in the Quiver Slots. I'm 99% sure anyway (my memory wouldn't lie to me, would it?! Ha!), and the in-game help seems to imply that's how it should work.
