### ISSUE TITLE
[BUG] Wrong ID stored for AccountBank location ...

### ISSUE THREAD

**Issue by rkuenzel** [arkayenro/arkinventory#2014]
**What version number you are using?**
v31101.Alpha.5

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
In Arkinventory.lua:623 the "id" member is initialized with "ArkInventory.Const.Location.ReagentBank". I assume, this should be "ArkInventory.Const.Location.AccountBank" instead.

**Comment by arkayenro** [comment]
thanks, although i dont think its actually used by anything yet.
