### ISSUE TITLE
[BUG] Lua Error in Classic Era

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#2015]
**What version number you are using?**

<img width="170" alt="image" src="https://github.com/user-attachments/assets/db741780-ded4-4fad-bfc0-04d7b96de3ea">

(Should make a "copy version and client" from the menu! Ha)

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**

**What language is the game client set to?**

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour, if possible:

**Screenshots**

**Additional context**

3x [ADDON_ACTION_BLOCKED] AddOn 'ArkInventory' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Details/classes/class_instance.lua"]:3933: in function <Details/classes/class_instance.lua:3932>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Comment by arkayenro** [comment]
that would most likely be a `Details` issue

**Comment by Gogo1951** [comment]
Ah, thank you! I got lost on the headline. (=

**Comment by Gogo1951** [comment]
@arkayenro I took a look at the re-stocker function.

My god... that's beyond me. (=

Thanks again mate!
