### ISSUE TITLE
[BUG] Restack setting "Blizzard Cleanup" not working for warbank

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#2016]
**What version number you are using?**
31101-alpha-6

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
I have set Restack mode to Blizzard: Cleanup because that code does an actual good job at organizing the warbank (tried it with AI disabled), but it's not being called when clicking the Cleanup button. _Something_ happens, I can't figure out what exactly (maybe the AI Restack function?) but it's not the Blizzard cleanup code.

**To Reproduce**
Good - AI disabled:
1. have a messy warbank
2. open warbank
3. click "Cleanup" button
4. get a nice tidy warbank

Bad - AI enabled:
1. have a messy warbank
2. set General > Restack > Blizzard: Cleanup
3. open warbank
4. click AI Restack button
5. ???

**Screenshots**
![image](https://github.com/user-attachments/assets/b471bba3-c504-4186-a023-0f08720ae627)

**Additional context**
It would be nice if this setting could be applied to warbank only but if not it's fine - I just want to use the built in Blizzard cleanup code only for the warbank because Genie sadly can't work with it.

**Comment by hollo6** [comment]
Additionally, when clicking the Restack button, the Deposit All Reagents function is being called despite that it is disabled in the settings:

[09:20:59] ArkInventory: Cleanup: Bank - Start
[09:20:59] ArkInventory: Cleanup: Deposit All Reagents Enabled
[09:20:59] ArkInventory: Cleanup: Bank - Complete

![image](https://github.com/user-attachments/assets/1e9fd9ac-bbd1-4e4a-b7b6-9e40fc193146)

**Comment by arkayenro** [comment]
restack does not make things pretty, it just restacks.

the deposit all reagents thing should be fixed in the next release

**Comment by hollo6** [comment]
I know what restack does, my problem is that if AI is enabled, I cannot run the built in cleanup function.
Isn't that what this setting is supposed to be for?

**Comment by hollo6** [comment]
To clarify:
On the default warbank UI, there is this button:
![image](https://github.com/user-attachments/assets/e147082d-12c7-45c2-a512-87eabd3907df)

And that does the sorting I want.

From what I understood, this setting:
![image](https://github.com/user-attachments/assets/c53ba757-c509-413b-98d3-2bbcc2221d1f)

is supposed to make this button:
![image](https://github.com/user-attachments/assets/a02162f5-e15e-4347-b79f-50704c36d013)

call that first function.

I tried to search for "cleanup" on the wiki/FAQ page but couldn't find anything so I guess I misunderstood something.

Either way, my request is to have some, any, way to run that function when AI is enabled without a macro. I strongly dislike having to have an extra button on my action bars for this.

**Comment by arkayenro** [comment]
there was a typo in the cleanup code that caused the bank and reagent bank cleanup to run when only the account bank cleanup should have run.  that would lock items and probably muck it up.

should be fixed in the next release.

**Comment by hollo6** [comment]
Now the cleanup code fine but it's now trying to deposit warbound items:
[15:23:43] ArkInventory: Cleanup: Bank - Start
[15:23:43] ArkInventory: 20
[15:23:43] ArkInventory: Cleanup: Deposit All Warbound Items Enabled
[15:23:43] ArkInventory: Cleanup: Bank - Complete

Despite having it disabled:
![image](https://github.com/user-attachments/assets/3215afb5-605e-4dee-a6e5-16583022a9fb)

And getting the following error when clicking the cleanup button:
3x ...faceArkInventory/Core/ArkInventoryClient.lua:1347: attempt to index global 'self' (a nil value)
[string "@ArkInventory/Core/ArkInventoryClient.lua"]:1347: in function `DepositAccountBank'
[string "@ArkInventory/Core/ArkInventoryRestack.lua"]:1158: in function <...aceArkInventory/Core/ArkInventoryRestack.lua:1156>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'self' (a nil value)"

**Comment by arkayenro** [comment]
the debug output and error should be fixed next release

im not sure why its doing the deposit.  its based off the cvar so it should work
can you check with `/dump ArkInventory.CrossClient.GetCVarBool( "bankAutoDepositReagents" )`

**Comment by hollo6** [comment]
[16:02:02] Dump: value=ArkInventory.CrossClient.GetCVarBool( "bankAutoDepositReagents" )
[16:02:02] [1]=true

But it actually did not deposit those few warbound items I have tested it with.

**Comment by arkayenro** [comment]
nvm, figured it out, im checking the wrong thing, thats just for the tradable reagents when you have deposit on

**Comment by hollo6** [comment]
Everything works as expected now, thank you!
