### ISSUE TITLE
Is there a function to determine the age of an item (for new loot)

### ISSUE THREAD

**Issue by chadmccune** [arkayenro/arkinventory#2017]
Retail, I'd like to be able to sort newly looted items into a new section, is there an AI function for that?

**Comment by arkayenro** [comment]
theres a new item category that you can assign to a bar, then in the config enable it and set how long "new" is for you.  i think its in the override section.

**Comment by chadmccune** [comment]
I found the "new" category, but can't find anywhere in the options to
change the value for it.  It also appears that my other rules override this.

**Comment by arkayenro** [comment]
config > settings > the style you are using > items > override > new items

it needs to be enabled for it to override the rules/categories

**Comment by chadmccune** [comment]
Thanks, worked perfectly
