### ISSUE TITLE
[BUG] Classic Era - Error when opening bank

### ISSUE THREAD

**Issue by RabbleCode** [arkayenro/arkinventory#2019]
**What version number you are using?**

v3.11.01-alpha-6

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**

Classic Era (SOD)

**What language is the game client set to?**

en-us

**Describe the bug**

When visiting the bank, ArkInventory throws the following error immediately once bags are opened:

`WARNING> ...ace/Addons/ArkInventory/Core/ArkInventoryStorage.lua;2770: bad argument #1 to 'IsInventorySlotEngravable' (outside of expected range 0 to 4294967295 - Usage: local result = C_Engraving.IsInventorySlotEngravable(containerIndex, slotIndex))`

From this point ArkInventory's bank bags stop updating visually (e.g. if I put an item in the bank, ArkInventory's bank bag doesn't show the item in the bank), but I can still interact with the bank. 

This happens regardless of whether the character has no, some, or all extra bank slots unlocked.

**To Reproduce**

Talk to bank vendor, open bank. No other special circumstances required, this is consistently reproducible with no other addons enabled and across any character.

**Screenshots**

N/A

**Additional context**

I've resolved this locally by adding a nil check to variable `blizzard_id` on line 2270 of ...\ArkInventory\Core\ArkInventoryStorage.lua as follows:

Original:

`if C_Engraving.IsEngravingEnabled( ) and C_Engraving.IsInventorySlotEngravable( blizzard_id, slot_id ) then`

Modified:

`if C_Engraving.IsEngravingEnabled( ) and blizzard_id ~= nil and C_Engraving.IsInventorySlotEngravable( blizzard_id, slot_id ) then`

**Comment by arkayenro** [comment]
`blizzard_id` shouldnt ever be `nil` there, theres multiple checks for a valid value before that.

could you open the debug window and check what it says in there when you open the bank?

**Comment by arkayenro** [comment]
nvm, its the base bank blizzard id of -1

does SOD have runes? or just classic?

**Comment by arkayenro** [comment]
although that should mean that the API is broken as any runed item the bank cannot be worked out

**Comment by arkayenro** [comment]
ive included a workaround so it wont crap out on the error but any runed item you put in the bank bag wont show as runed until blizzard fix their bug

**Comment by RabbleCode** [comment]
Sorry for not responding earlier, but glad you found a workaround. If you need any further details I'm happy to help.

**Comment by RabbleCode** [comment]
Installed v3.11.01-alpha-7 and verified the issue workaround is working. No error message when opening the bank, I can add/remove items from the bank, and tooltips for SoD runed items in the bank even display properly too.
