### ISSUE TITLE
[BUG] Breaking ToC issue with Classic Era

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#2020]
**What version number you are using?**

Latest Alpha.

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**

Classic Era 

Ark Inventory won't load.

**What language is the game client set to?**

**Describe the bug**

1x ...rfaceArkInventoryRules/ArkInventoryRules.lua:2409: attempt to call field 'TOCVersionFail' (a nil value)
[string "@ArkInventoryRules/ArkInventoryRules.lua"]:2409: in function `Register'

Locals:
a = <table> {
 SetDefaultModuleLibraries = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:363
 Enable = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:290
 NewModule = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:231
 EnableModule = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:438
 IsModule = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:213
 defaultModuleLibraries = <table> {
 }
 SetEnabledState = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:420
 enabledState = true
 moduleName = "Pawn"
 GetName = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:275
 defaultModuleState = true
 Disable = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:310
 IterateModules = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:433
 name = "ArkInventoryRules_Pawn"
 SetDefaultModulePrototype = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:405
 IsEnabled = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 SetDefaultModuleState = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:383
 DisableModule = <function> defined @ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:346
}
n = "PAWNUPGRADE"
f = <function> defined @Pawn/Pawn.lua:891
o = nil
(*temporary) = nil
(*temporary) = true
(*temporary) = "attempt to call field 'TOCVersionFail' (a nil value)"
string = <table> {
 split = <function> defined =[C]:-1
 match = <function> defined =[C]:-1
 gmatch = <function> defined =[C]:-1
 upper = <function> defined =[C]:-1
 gsub = <function> defined =[C]:-1
 format = <function> defined =[C]:-1
 utf8sub = <function> defined @Outfitter/Libraries/UTF8/utf8.lua:183
 lower = <function> defined =[C]:-1
 sub = <function> defined =[C]:-1
 len = <function> defined =[C]:-1
 utf8lower = <function> defined @Outfitter/Libraries/UTF8/utf8.lua:276
 gfind = <function> defined =[C]:-1
 join = <function> defined =[C]:-1
 rep = <function> defined =[C]:-1
 utf8len = <function> defined @Outfitter/Libraries/UTF8/utf8.lua:158
 char = <function> defined =[C]:-1
 rtgsub = <function> defined @Blizzard_FrameXML/RestrictedInfrastructure.lua:534
 utf8upper = <function> defined @Outfitter/Libraries/UTF8/utf8.lua:266
 reverse = <function> defined =[C]:-1
 byte = <function> defined =[C]:-1
 trim = <function> defined =[C]:-1
 utf8reverse = <function> defined @Outfitter/Libraries/UTF8/utf8.lua:286
 find = <function> defined =[C]:-1
}

**Comment by RabbleCode** [comment]
Confirm this issue is happening with v 3.11.01-alpha-8 in Classic Era.

**Comment by arkayenro** [comment]
blizzard left out one of their enum tables only in classic era.
fixed in next release
