### ISSUE TITLE
[BUG] Restack does not move Reagent Items into Reagent Bags

### ISSUE THREAD

**Issue by ImUnicke** [arkayenro/arkinventory#2021]
**What version number you are using?**
### v31101.Alpha.6/8 [TWW]

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Reagent Items in Bags do not move to empty Reagent Bags when performing Restack on Bag Panel

**To Reproduce**
Steps to reproduce the behaviour, if possible:
1. Move Reagent to a Bag slot from Reagent Bag
2. Restack
3. -- Reagent is not moved to Reagent Bag

**Additional context**

**It seems Reagents in Bags do not follow 'Consolidate' option as expected.**

I have a couple Reagents in my Bags and the following Settings for Restack - Bags
![image](https://github.com/user-attachments/assets/9069602f-6913-4f8b-be63-3274ff71512d)
![image](https://github.com/user-attachments/assets/3c75ce94-06c7-4dcc-91a8-096ae1c30c63)

The Restack is very much instant since this character has basically nothing
![image](https://github.com/user-attachments/assets/9cf36a18-4ad4-44bd-b1b2-ead7112af7ba)

But the Reagents remain in the Bags instead of moving to a higher priority Container Type as indicated in the Bag Priority
![image](https://github.com/user-attachments/assets/1f6d63e9-f2f7-4202-99bd-7125dae432d8)

I would expect that the Consolidate option for a given Panel would attempt to reduce the Priority of Items (i.e. moving them to the highest priority Containers within that Panel if possible) but the wording seems to indicate it may only target Profession Containers?

The 'Stack' functionality does work as expected and will move the single Reagent from a Bag into the same stack of the Item in a Reagent bag
![image](https://github.com/user-attachments/assets/c144a569-e54d-43a0-ad91-bf50962e1310) => ![image](https://github.com/user-attachments/assets/a2c89d0d-46f0-4903-b2ca-901628ae51a5)

Edit: I noticed these two Reagents are assigned as 'Junk' but removing that assignment does not change the outcome of the Restack operation -- they remain in Bags instead of moving to Reagent Bag.

**Comment by arkayenro** [comment]
missed the reagent bag when setting up the config/defaults.

should be fixed in the next release

**Comment by ImUnicke** [comment]
Fixed in v31101.Alpha.10
