### ISSUE TITLE
[BUG] Bag Restack with Conjured Mana Buns in inventory

### ISSUE THREAD

**Issue by ImUnicke** [arkayenro/arkinventory#2022]
**What version number you are using?**
v31101.Alpha.10

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Attempting to Restack Bags while Conjured Mana Buns (113509) are in bags will cause the Restack operation to infinitely attempt to restack the mana buns somehow. The only fix is to reload UI (at least I waited over a minute with no change)

**To Reproduce**
Steps to reproduce the behaviour, if possible:
1. Have Conjured Mana Buns in inventory
2. Use Restack operation

**Additional Info**
Not sure if it's related to Conjured items in general or these specific items. These are 'Unique (80)' so possibly AI is trying to put them into a stack of 80 when they only stack to 20. Not really sure.

**Comment by arkayenro** [comment]
i have correction code to handle an item saying it can stack to say 20 but being unique (3), i should have expected blizzard to screw up on both ends.

should be fixed in the next release (i'll go with the smaller value)

**Comment by arkayenro** [comment]
if the above is correct you should be seeing warnings in the debug output about changing the stacksize from 20 to 80 for mana buns

**Comment by arkayenro** [comment]
fixed in alpha 11
