### ISSUE TITLE
How do I enable searches for "...of the Bear" green items?

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#2028]
Classic Era, I thought this used to work. But it comes up with nothing when I do a search.

<img width="679" alt="image" src="https://github.com/user-attachments/assets/86540a77-5dde-4962-b742-8d072e1126cf">

It would be cool to see the green items in search... I keep them for leveling alts.

<img width="710" alt="image" src="https://github.com/user-attachments/assets/522a2d35-654f-4faf-b621-f3bbf7c5b16e">

**Comment by arkayenro** [comment]
theres a config option to discard suffixes for item counts and searches, youll need to enable it

**Comment by Gogo1951** [comment]
Thanks!

I think this should be enabled by default. (=

<img width="402" alt="image" src="https://github.com/user-attachments/assets/b38607da-0163-4cbd-a1f5-b56dcd57e0ee">
