### ISSUE TITLE
Additional Bag Configuration

### ISSUE THREAD

**Issue by GoogleCodeExporter** [arkayenro/arkinventory#275]
```
Suggestion:
Add a "Mini-Bag" option to display only specified items.

What version of the product are you using? On what operating system?
3.02.23, Windows XP

Please provide any additional information below.
Sometimes I don't want to see everything in my bags, but only a small
subset.  Would it be possible to add a "Mini-Bag" option that could be
configured separately from your main bag, and only display user/system
defined categories/rules?  This way you could launch the "Mini-Bag" with B
and the "Main Bag" with Shift+B.

```

Original issue reported on code.google.com by `jrhi...@gmail.com` on 7 Sep 2009 at 3:02

**Comment by spiralofhope** [comment]
A simple version would be another arkinventory window which only display items from one specific rule.

I could see this implemented with something like:

```
/ai minibag( 'rulename' )
```

**Comment by arkayenro** [comment]
the ability to hide bars/categories was added at some point which should do what was requested

**Comment by spiralofhope** [comment]
I myself don't strongly want the original commenter's proposed feature (feature creep), but I'll describe it better in case you're interested.

The regular functionality of arkinventory combines bags together.  This would stay.

This is a request for the display of an entirely new instance of bag with its own unique rule.

I don't believe this is currently possible.
