### ISSUE TITLE
not display gold/silver/coper icons on ru_RU version

### ISSUE THREAD

**Issue by GoogleCodeExporter** [arkayenro/arkinventory#383]
```
Downloaded from > googlecode | wowinterface | curse | wowui | other (specify)


http://s004.radikal.ru/i208/1009/84/8a388e7c26ed.jpg
```

Original issue reported on code.google.com by `modest.d...@gmail.com` on 23 Sep 2010 at 2:21

Attachments:
* [arkinventory.jpg](https://storage.googleapis.com/google-code-attachments/arkinventory/issue-383/comment-0/arkinventory.jpg)

**Comment by arkayenro** [comment]
closing really old tickets - if its still an issue re-open it
