### ISSUE TITLE
clampedToScreen

### ISSUE THREAD

**Issue by GoogleCodeExporter** [arkayenro/arkinventory#418]
```
Not so much an issue as a feature request.

Would it be possible to have an option added to allow you to choose whether the 
frames are clamped to the screen or not?

If I'm remembering correctly the frames used to be clamped and in one of your 
updates you changed that, was just wondering if there was a reason you removed 
it.
```

Original issue reported on code.google.com by `ian.bri...@gmail.com` on 3 Dec 2010 at 11:33

**Comment by spiralofhope** [comment]
Was this implemented?

I do recall an option to automatically reposition (like ```/ai reposition```) the bags back on-screen on reload, but I don't see that happening on every bag open, which is what I'd want.  Is this a different request than clamping?

**Comment by arkayenro** [comment]
clamptoscreen made sure you couldnt move the bag off the screen, that was added a while back

re-positioning on open was added in 3.06.02
