### ISSUE TITLE
Request: rule function to check for account bound items

### ISSUE THREAD

**Issue by GoogleCodeExporter** [arkayenro/arkinventory#421]
```
Downloaded from > curse

Currently you can use soulbound() or sb() to check to see if an item is 
soulbound. It would also be useful to check for non-heirloom account bound 
items like the ones you can get from Archaeology. This would let users sort out 
these types of objects from other drops. 
```

Original issue reported on code.google.com by `krevi...@hotmail.com` on 21 Dec 2010 at 11:04

**Comment by spiralofhope** [comment]
Problems with matching in tooltips are probably from a bad pattern, because of the period or because of spaces.

https://github.com/arkayenro/arkinventory/wiki/RuleFunction_Tooltip

Still, there is now ```lua type( 'Account Bound' ) ``` and so this issue can be closed/fixed.

**Comment by arkayenro** [comment]
closing old issues - if its still a problem re-open the ticket
