### ISSUE TITLE
Can't delete old guild banks gold, 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [arkayenro/arkinventory#646]
```
I can't delete old data from older gbanks. i deleted all data, but the gold of 
guilds are still there. How can i fix ?

```

Original issue reported on code.google.com by `jpl...@gmail.com` on 11 Apr 2014 at 6:40

Attachments:
* [WoWScrnShot_041114_034000.jpg](https://storage.googleapis.com/google-code-attachments/arkinventory/issue-646/comment-0/WoWScrnShot_041114_034000.jpg)

**Comment by arkayenro** [comment]
closing old tickets - if this issue still occurs please re-open the ticket
