### ISSUE TITLE
Error when using item from quest tracker

### ISSUE THREAD

**Issue by GoogleCodeExporter** [arkayenro/arkinventory#684]
```
Downloaded from > curse


What steps will reproduce the problem?
1. Get quest "Those That Couldn't Let Go" from Chillwind Camp.
2. Use "Holy Thurible" from the quest tracker on a Withdrawn Soul.
3. Notice error "ArkInventory has been blocked from an action only available to 
the Blizzard UI...."

What is the expected output? What do you see instead?
No error


What version of the product are you using? On what operating system?
3.04.18 on Win 8.1

Please provide any additional information below.


```

Original issue reported on code.google.com by `ellswort...@gmail.com` on 28 Dec 2014 at 9:00

**Comment by spiralofhope** [comment]
I don't know that this is the fault of ArkInventory.

This issue does occasionally happen for me, though I don't bother to look at errors any more.  It's only occasional, so I doubt it's not ArkInventory.

If the original poster finds this, I recommend they reproduce this issue both after

```
/console reloadui
```

, as well as after disabling all other addons.

**Comment by arkayenro** [comment]
closing old issues - if its still a problem re-open the ticket
