### ISSUE TITLE
Patch: new rule goodforclass() checks if item is usable/useful for current player class

### ISSUE THREAD

**Issue by GoogleCodeExporter** [arkayenro/arkinventory#705]
```
This rule checks item usability against various criteria but goes beyond 
classic usability. Good to filter items when farming transmog etc.

For example it will report FALSE for the following combinations despite the 
fact that these items are strictly speaking usable.

- Paladin/Cloth Wrist
- Hunter/Polearm
- Warrior/Thrown
...

Other than that, common sense pretty much dictates the outcome of the rule.
It may not be bullet proof but see if you like it. Feedback welcome.

Possible improvements:
- Sub-40 armor proficiencies
- Factor in off-hand/main hand attribute
- Factor in spec/talent based dual wielding
- Legacy stuff like relics/ammo is currently ignored

I have not implemented any of the latter as there is little demand.

Dave Driesen
```

Original issue reported on code.google.com by `pyromas...@gmail.com` on 3 Mar 2015 at 12:16

Attachments:
* [ArkInventoryRules_goodforclass_v1.0.diff](https://storage.googleapis.com/google-code-attachments/arkinventory/issue-705/comment-0/ArkInventoryRules_goodforclass_v1.0.diff)

**Comment by King-Aeon** [comment]
This is the contents of the .diff file (used notepad++)

--- ArkInventoryRules.orig	2015-03-03 12:07:31.439634740 +0100
+++ ArkInventoryRules.lua	2015-03-03 13:03:46.771523818 +0100
@@ -1115,6 +1115,144 @@
 	
 end
 
+function ArkInventoryRules.System.goodforclass( )
+	
+	if not ArkInventoryRules.Object.h or ArkInventoryRules.Object.class ~= "item" then
+		return false
+	end
+
+	local playerClass, englishClass = UnitClass("player");
+	
+	local objecttype = string.lower( select( 8, ArkInventory.ObjectInfo( ArkInventoryRules.Object.h ) ) )	
+	local objectsubtype = string.lower( select( 9, ArkInventory.ObjectInfo( ArkInventoryRules.Object.h ) ) )
+	local objectequip = string.lower ( select( 11, ArkInventory.ObjectInfo( ArkInventoryRules.Object.h ) ) )
+
+	if objecttype == "trinket" then return true end
+	
+	if objecttype == "armor" then
+		if objectsubtype == "miscellaneous" then return true end
+		if objectequip == "invtype_cloak" then return true end
+		if objectequip == "invtype_trinket" then return true end
+		if objectequip == "invtype_neck" then return true end
+		if objectequip == "invtype_finger" then return true end
+		
+		if ( ( englishClass == "WARRIOR" ) 		and ( objectsubtype == "plate") )	then return true end
+		if ( ( englishClass == "WARRIOR" ) 		and ( objectsubtype == "shields") )	then return true end
+		if ( ( englishClass == "DEATHKNIGHT" )		and ( objectsubtype == "plate") )	then return true end
+		if ( ( englishClass == "PALADIN" )		and ( objectsubtype == "plate") )	then return true end
+		if ( ( englishClass == "PALADIN" ) 		and ( objectsubtype == "shields") )	then return true end
+		if ( ( englishClass == "PRIEST" )		and ( objectsubtype == "cloth") )	then return true end
+		if ( ( englishClass == "MAGE" )			and ( objectsubtype == "cloth") )	then return true end
+		if ( ( englishClass == "WARLOCK" )		and ( objectsubtype == "cloth") )	then return true end
+		if ( ( englishClass == "HUNTER" )		and ( objectsubtype == "mail") )	then return true end
+		if ( ( englishClass == "SHAMAN" )		and ( objectsubtype == "mail") )	then return true end
+		if ( ( englishClass == "SHAMAN" ) 		and ( objectsubtype == "shields") )	then return true end
+		if ( ( englishClass == "DRUID" )		and ( objectsubtype == "leather") )	then return true end
+		if ( ( englishClass == "ROGUE" )		and ( objectsubtype == "leather") )	then return true end
+		if ( ( englishClass == "MONK" )			and ( objectsubtype == "leather") )	then return true end
+	end
+	
+	if objecttype == "weapon" then
+	if ( englishClass == "WARRIOR" ) and ( 
+		( objectsubtype == "one-handed swords") or
+		( objectsubtype == "two-handed swords") or
+		( objectsubtype == "one-handed axes") or
+		( objectsubtype == "two-handed axes") or
+		( objectsubtype == "one-handed maces") or
+		( objectsubtype == "two-handed maces") or
+		( objectsubtype == "daggers") or
+		( objectsubtype == "polearms") or
+		( objectsubtype == "fist weapons")
+	) then return true end
+	
+	if ( englishClass == "DEATHKNIGHT" ) and ( 
+		( objectsubtype == "one-handed swords") or
+		( objectsubtype == "two-handed swords") or
+		( objectsubtype == "one-handed axes") or
+		( objectsubtype == "two-handed axes") or
+		( objectsubtype == "one-handed maces") or
+		( objectsubtype == "two-handed maces") or
+		( objectsubtype == "polearms")
+	) then return true end
+	
+	if ( englishClass == "PALADIN" ) and ( 
+		( objectsubtype == "one-handed swords") or
+		( objectsubtype == "two-handed swords") or
+		( objectsubtype == "one-handed axes") or
+		( objectsubtype == "two-handed axes") or
+		( objectsubtype == "one-handed maces") or
+		( objectsubtype == "two-handed maces") or
+		( objectsubtype == "polearms")
+	) then return true end
+	
+	if ( englishClass == "PRIEST" )	and ( 
+		( objectsubtype == "staves") or
+		( objectsubtype == "wands") or
+		( objectsubtype == "daggers") or
+		( objectsubtype == "one-handed maces")
+	) then return true end
+	
+	if ( englishClass == "MAGE" )	and ( 
+		( objectsubtype == "one-handed swords") or
+		( objectsubtype == "staves") or
+		( objectsubtype == "daggers") or
+		( objectsubtype == "wands")
+	) then return true end
+	
+	if ( englishClass == "WARLOCK" ) and (
+		( objectsubtype == "one-handed swords") or
+		( objectsubtype == "staves") or
+		( objectsubtype == "daggers") or
+		( objectsubtype == "wands")
+	) then return true end
+	
+	if ( englishClass == "HUNTER" )	and ( 
+		( objectsubtype == "crossbows") or
+		( objectsubtype == "bows") or
+		( objectsubtype == "guns")
+	) then return true end
+	
+	if ( englishClass == "SHAMAN" )	and (
+		( objectsubtype == "staves") or
+		( objectsubtype == "one-handed maces") or
+		( objectsubtype == "two-handed maces") or
+		( objectsubtype == "one-handed axes") or
+		( objectsubtype == "two-handed axes") or
+		( objectsubtype == "daggers") or
+		( objectsubtype == "fist weapons")
+	) then return true end
+	
+	if ( englishClass == "DRUID" ) and (
+		( objectsubtype == "staves") or
+		( objectsubtype == "one-handed maces") or
+		( objectsubtype == "two-handed maces") or
+		( objectsubtype == "polearms") or
+		( objectsubtype == "daggers") or
+		( objectsubtype == "fist weapons")
+	) then return true end
+	
+	if ( englishClass == "ROGUE" ) and (
+		( objectsubtype == "daggers") or
+		( objectsubtype == "one-handed swords") or
+		( objectsubtype == "one-handed axes") or
+		( objectsubtype == "one-handed maces") or
+		( objectsubtype == "fist weapons")
+	) then return true end
+	
+	if ( englishClass == "MONK" ) and (
+		( objectsubtype == "one-handed axes") or
+		( objectsubtype == "one-handed swords") or
+		( objectsubtype == "one-handed maces") or
+		( objectsubtype == "polearms") or
+		( objectsubtype == "staves") or
+		( objectsubtype == "fist weapons")
+	) then return true end
+	end
+	
+	return false
+	
+end
+
 function ArkInventoryRules.System.usable( )
 	
 	if not ArkInventoryRules.Object.h or ArkInventoryRules.Object.class ~= "item" then
@@ -1359,6 +1497,10 @@
 	
 	location = ArkInventoryRules.System.location,
 	loc = ArkInventoryRules.System.location,
+
+	myspecialisation = ArkInventoryRules.System.goodforclass,
+	myspec = ArkInventoryRules.System.goodforclass,
+	goodforclass = ArkInventoryRules.System.goodforclass,
 	
 	usable = ArkInventoryRules.System.usable,
 	use = ArkInventoryRules.System.usable,

**Comment by spiralofhope** [comment]
Was this code adopted into the new ```lua usable() ``` ?

Because that code is awesome.

----

> Sub-40 armor proficiencies

Personally I wouldn't use this, though I'm careful about gear when levelling (for transmog).  Perhaps this would be useful as a separate rule?

> Factor in off-hand/main hand attribute

I don't understand this.  Is this to prevent something like off-hand int wielding?

> Factor in spec/talent based dual wielding

I don't think I'd use this either, though I don't think I understand the feature.

**Comment by arkayenro** [comment]
was created as a rule mod

**Comment by stonedune** [comment]
I know this is closed but I really like what this is doing. I copied it into my ArkInventoryRules.lua and commented out the old .usable function as from what I see this overwrites it. When i load the game and open the rules it gives me an error and doesn't list any of them. Can someone give me a few suggestions as to how to get this into my setup?

**Comment by arkayenro** [comment]
its a separate mod that someone else is looking after, they should have updated it for legion as they asked a question about it the other day.  just download that

**Comment by stonedune** [comment]
Amazing! Thank you
