### ISSUE TITLE
lua error on purchasing from GR vendor

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#714]
When I purchase something from any GR vendor, first time no problems, and when I buy a second stack, this error pops up:

[12:28:31] [ADDON_ACTION_FORBIDDEN] AddOn 'ArkInventory' tried to call the protected function 'AscendStop()'.
[12:28:31] ...dOns\ComboPointsRedux\Libs\BugGrabber\BugGrabber.lua:589: in function <...dOns\ComboPointsRedux\Libs\BugGrabber\BugGrabber.lua:589>
[C]: in function `AscendStop'
[string "JUMP"]:4: in function <[string "JUMP"]:1>
[C]: in function `RunBinding'
Interface\FrameXML\StackSplitFrame.lua:181: in function <Interface\FrameXML\StackSplitFrame.lua:178>
[C]: in function `Hide'
Interface\FrameXML\StackSplitFrame.lua:167: in function `StackSplitFrameOkay_Click'
Interface\FrameXML\StackSplitFrame.lua:112: in function <Interface\FrameXML\StackSplitFrame.lua:90>
[12:28:31] nil

**Comment by hollo6** [comment]
Appearing in case of other vendors as well.

**Comment by arkayenro** [comment]
closing really old tickets - if its still an issue re-open it
