### ISSUE TITLE
TSM 3.0 / ArkInventoryRules_TSMGroup

### ISSUE THREAD

**Issue by behub** [arkayenro/arkinventory#715]
I know TSM 3.0 is still in beta but it is incompatible with ArkInventoryRules_TSMGroup.

TSM 3.0 has removed Events.lua (TSMAPI:GetEventObject() is gone).

TSM has asked for the beta not to be distributed but I am sure I can pass on the CoreAPI folder.

Couldn't this support just be built into ArkInventory now being TSM is so popular instead of having a separate addon for it?

**Comment by arkayenro** [comment]
merged back into core mod in 3.06.05

**Comment by behub** [comment]
Thanks. I did see the update on curseforge and remembered making this issue :p
