### ISSUE TITLE
Invalid Item Hyperlink in Search

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#716]
The following LUA error is displayed and then nothing shows up in the list of items.

Date: 2015-06-24 21:46:40
ID: 1
Error occured in: Global
Count: 17
Message: ...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua line 34:
   Invalid Item Hyperlink.
Debug:
   [C]: ?
   [C]: SetHyperlink()
   ...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:34: TooltipSetHyperlink()
   ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:3499: ObjectInfo()
   ArkInventory\ArkInventorySearch.lua:226: Frame_Search_Table_Refresh()
   [string "*:OnShow"]:1:
      [string "*:OnShow"]:1
   [C]: Show()
   ArkInventory\ArkInventorySearch.lua:19: Frame_Search_Show()
   ArkInventory\ArkInventorySearch.lua:28: Frame_Search_Toggle()
   ArkInventory\ArkInventory.lua:765:
      ArkInventory\ArkInventory.lua:754
Locals:

AddOns:
{{ clipped }}
  (ck=5fe)

**Comment by spiralofhope** [comment]
Everything is working fine for me, is this still an issue for you, @Calesta?

**Comment by arkayenro** [comment]
closing old tickets - if this issue still occurs please re-open the ticket
