### ISSUE TITLE
3.05.02 Non-functioning (3.05.01 beta 3 has same issues)

### ISSUE THREAD

**Issue by Amadeus-** [arkayenro/arkinventory#717]
BugSack is catching 11 errors loading the latest version (3.05.02).   3.05.01 beta 3 also causes the same errors.

I had to revert back to 3.05.00 to regain functionality  (thankfully my setting files were still OK.)

Here is a screenshot of the list of bug reports from BugSack.
![arkinventory_3 05 02_bugs](https://cloud.githubusercontent.com/assets/2244392/8350279/d7ded1d4-1ad8-11e5-88c7-364a9c3b6628.jpg)

**Comment by Amadeus-** [comment]
I should have been clear in that ArkInventory does not work at all with these errors in play.   I'm getting the regular inventory windows with version 3.05.02.    (Reverting back to 3.05.00 makes everything work perfectly again.)

**Comment by arkayenro** [comment]
are you running the version without libraries?

**Comment by akeeva** [comment]
Having the exact same errors, I even downloaded the library from Curse. Same problem.

**Comment by Amadeus-** [comment]
No, I'm using the regular version.   In fact, the initial update to 3.05.02 was through the curse client application.   Then, I went and downloaded 3.05.01 beta 3 manually and had the same errors.   Eventually, I downloaded 3.05.00 manually (with libs) and everything works again.

**Comment by spiralofhope** [comment]
Everything is working fine for me, is this still an issue for you, @Amadeus-?

**Comment by arkayenro** [comment]
was fixed at some point, cant remember exactly when
