### ISSUE TITLE
ArkInventory cleanup moves some potions, food, and flasks to bank

### ISSUE THREAD

**Issue by joevt** [arkayenro/arkinventory#719]
Using 3.05.02
I have incomplete stacks of potions, food, and flasks in the bank. When I click Cleanup, ArkInventory fills those stacks in the bank with items from my bags. I need those for raiding.

I expect only reagents that can go into the Reagents bank to be moved from my bags to my bank.

An option could be added to fill a specified number of stacks in bags of a specified item from bank for things that I want to have on hand... This could include the above types of items, an anvil, fishing bait, lures, pet bandages.

I'm using Restack (ArkInventory) because Cleanup (Blizzard) is really slow and moves everything around so that I need to also do a refresh afterward.

I also have "Deposit all Reagents" enabled.

**Comment by arkayenro** [comment]
right click on the restack icon and disable the top up option for the bank
