### ISSUE TITLE
Library error

### ISSUE THREAD

**Issue by jasblade** [arkayenro/arkinventory#724]
Just downloaded revision 1348 (Sat, 27 Jun 2015), and picked up an error that LibItemUpgradeInfo-1.0 was missing.  Was easy enough to download it on curse and now I have no problems, but maybe it should be included or error trap the condition when the library is missing to fail soft?

Error pointed to line 27:
	UpgradeInfo = LibStub( "LibItemUpgradeInfo-1.0" ),

**Comment by spiralofhope** [comment]
Everything seems to be working fine for me, is this still an issue for you?

**Comment by jasblade** [comment]
nope, once I snagged the libary life has been good. Only recent bug (think it's video bug not AI) sometimes items go into my bag and no icon shows up. When I mouse over one of the empty spots in the bag it lights up letting me know something is there, but I get no tool tip info.  Items are not sorted when this happens.  My wife said it was happening to her with her nvidia GTX970, for me ati R9 280X, but for her video driver update fixed it. 

I still love ArkInventory. As bag sizes and collecting in game has grown, it's the only bag add-on that can grow dynamically enough by writing rules.  

Thanks!
