### ISSUE TITLE
call global 'exit' (a nil value)

### ISSUE THREAD

**Issue by esvarc** [arkayenro/arkinventory#728]
Version ArkInventory-3.5.11, when re-stack is active and closing re-stacked container. 

Date: 2015-08-19 09:40:48
ID: 1
Error occured in: Global
Count: 1
Message: ...nterface\AddOns\ArkInventory\ArkInventoryRestack.lua line 871:
   ...nterface\AddOns\ArkInventory\ArkInventoryRestack.lua line 22:
   attempt to call global 'exit' (a nil value)
Debug:
   (tail call): ?
   [C]: ?
   ...nterface\AddOns\ArkInventory\ArkInventoryRestack.lua:871: RestackResume()
   ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:756:
      ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:747
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[2]"]:9:
      [string "safecall Dispatcher[2]"]:5
   (tail call): ?
   ...ce\AddOns\Archy\Libs\AceBucket-3.0\AceBucket-3.0.lua:116: func()
   ...face\AddOns\Archy\Libs\AceTimer-3.0\AceTimer-3.0.lua:55:
      ...face\AddOns\Archy\Libs\AceTimer-3.0\AceTimer-3.0.lua:48
Locals:
None
AddOns:
  Swatter, v5.21d.5530 (SanctimoniousSwamprat)
  Archy, v6.2.0.2
  ArkInventory, v30511
  ArkInventoryRules, v10001
  AskMrRobot, v28
  Auctionator, v3.2.4
  BadBoy, v12.809
  BadBoyCCleaner, v
  BadBoyGuilded, v
  BadBoyHistory, v
  BonusRollPreview, v60200.26-Release
  BrokerDualSpec, v1.8.1
  BrokerGarrison, v1.8.0
  BuyEmAll, v3.2.1
  ClassicQuestLog, v1.0.6
  CleanBossButton, v1.19
  Decursive, v2.7.4.3
  DugisGuideViewerZ, v3.208
  EasyMail, v
  ElvUI, v8.25
  ElvUIEnhanced, v3.1.0-beta5
  ElvUILocPlus, v2.09
  EquipSee, v2.3
  GatherMate2, v1.34-2-g1e8eb12
  HandyNotes, vv1.3.3
  HandyNotesDraenorTreasures, v1.14a
  Levelland, v
  LootWonAlertHiderMover, v1.08.00
  MasterPlan, v0.67
  MasterPlanA, v
  MoveAnything, v15.1.7
  NOP, v05.10 14.08.2015
  Pawn, v1.9.19
  SavedInstances, v6.2.2
  Skada, v1.4-32
  TomTom, vv60200-1.0.0
  TradeSkillDW, v1.99
  WoWBox, v06.06
  WoWTokenWatch, v1.0.2
  WSFMover, v1.1
  BlizRuntimeLib_enUS v6.2.0.60200 <none>
  (ck=3c9)

**Comment by spiralofhope** [comment]
I'm not seeing this.  Is this still an issue for you, esvarc?

**Comment by esvarc** [comment]
It happens, when you select ArkInventory as restack method and prematurelly close restacked window. In ArkInventoryRestack.lua at line 22 is referenced exit( ) function. It is not implemented in actual WoW LUA code. I did fix it by comment that line and for every occurence of referenced function RestackAbort I did append proper return statemenet, like on line 37 in same file in function RestackBagCheck my line looks like:

		RestackAbort( loc_id ); return nil, 0

**Comment by spiralofhope** [comment]
I understand now.

I checked, and I'm using the new Blizzard Cleanup function. (```/ai config``` > Display > [x] Restack)

.. so I wasn't seeing your problem.  Maybe this will be a workaround for you.

I'd wager that @arkayenro is going to remove his old restack code soon, to simplify the code.

**Comment by arkayenro** [comment]
fixed in 3.05.12
