### ISSUE TITLE
Request: Item Count in Profession Window

### ISSUE THREAD

**Issue by EclairFaie** [arkayenro/arkinventory#730]
Version 3.5.11

Item count works perfectly in bags, bank and guild bank, but does not show anything in the profession window. If I mouse over any reagent or item (in profession window) doesn't show how much of that item I have in my characters but works fine if I have the same item in bag, bank, etc.

**Comment by arkayenro** [comment]
blizzard keep changing their code around slightly, just enough to break it every now and then, this is working in 3.5.12 and 3.6.4 (legion)
