### ISSUE TITLE
Guild bank items not showing

### ISSUE THREAD

**Issue by Deviousdb1** [arkayenro/arkinventory#731]
Downloaded from > curse

What steps will reproduce the problem?
1. Open guild bank
2. Click on any tab
3. Nothing shows up

What is the expected output? What do you see instead?

I would expect to see the items in my guild's bank, however, I see absolutely nothing. I see the tabs, the frame looks the way that it should, however, not a single item shows up. This happens on the raid guild that I'm in as well as my own guild. I have access so that's not an issue.

What version of the product are you using? On what operating system?
3.5.11 Windows 10 Pro build 10532 however, I've had this issue for the last ten or so builds. I thought it was something that I had done with settings, but I did a fresh install and it still occurs.
![screenshot 2015-08-29 17 45 51](https://cloud.githubusercontent.com/assets/14035571/9565187/b0008d26-4e75-11e5-8703-82f916fd76f9.png)

Please provide any additional information below.

**Comment by spiralofhope** [comment]
The guild bank feature is working for me, both online and offline.

Deviousdb1, could you confirm if this is still an issue?

**Comment by Deviousdb1** [comment]
Still an issue. I had to turn off the override feature and it now works, just not through Ark.

**Comment by spiralofhope** [comment]
@Deviousdb1, that's really odd.  Could you try with all other addons disabled?  I'm wondering if there's an issue with another addon and, if so, if you're able to narrow it down.

**Comment by arkayenro** [comment]
was fixed in 30700 beta 3
