### ISSUE TITLE
Guild bank not sorting items

### ISSUE THREAD

**Issue by Stefenatefun** [arkayenro/arkinventory#732]
**ArkInventory version**: v3.05.11

**World of Warcraft version**: 6.2.2 (20444)

**Issue**: Restacking the guild bank with either Blizzard's cleanup method or ArkInventory's restack method does not function. It does, however, print the following lines in the chat immediately, respectively:

>ArkInventory: Cleanup: Guild Bank Start
>ArkInventory: Cleanup: Guild Bank Complete

and

>ArkInventory: Restack: Guild Bank Start
>ArkInventory: Restack: Guild Bank Complete

Both methods work as intended with the bank and player bags.

**How to reproduce issue**:

1. Obtain a guild bank.

2. Buy a guild bank tab.

3. Place multiple items of different types (weapons, armor, crafting reagents, etc.) in the guild bank.

4. Use either Blizzard's cleanup or ArkInventory's restack method using the restack button.

**Additional info**: I already posted this on the Curse page and made Arkayenro aware of the issue; I am simply posting the issue on Github to make it "official" and to make communication about the issue easier.

**Comment by Stefenatefun** [comment]
So I went and tried another addon, [TradeSkillMaster_GuildSorter](http://www.curse.com/addons/wow/tradeskillmaster_guildsorter) (and the [TradeSkillMaster](http://www.curse.com/addons/wow/tradeskill-master) dependency, of course), to sort my guild bank, just for the hell of it and to see if anything else would work, and what do you know? It didn't work! This leads me to believe that the issue lies within Blizzard's guild bank API and not with ArkInventory or TSM_GS' code. Though, I'm sure there's a workaround that could be implemented as long as the API bug doesn't prevent addons from modifying the guild bank's contents entirely.

**Comment by arkayenro** [comment]
its working on the ptr servers so the code seems fine.
