### ISSUE TITLE
PT sets debug fix

### ISSUE THREAD

**Issue by Korosys** [arkayenro/arkinventory#733]
Hello, not sure if this is the right place to post this or if anyone even cares, but I noticed that the Debug Info> PT Sets menu was not functioning and I managed to fix it fairly quickly.

On line 1183 of ArkInventoryMenu.lua I changed 

`local pt_set = ArkInventory.PTItemSearch( i.h )`
to 
`local pt_set = ArkInventory.Lib.PeriodicTable:ItemSearch( i.h )`

and it seems to have completely fixed it. Thanks!

**Comment by spiralofhope** [comment]
As of this writing, I could not find that code.  I did find new code starting on line 9761 with:

```lua
function ArkInventory.PTItemSearch( item )
```

I don't use the PT Sets functionality.  Is it working for you, Korosys?

**Comment by arkayenro** [comment]
migrated ticket - issue was resolved
