### ISSUE TITLE
Pet scanning hangs for several seconds and can't be turned off.

### ISSUE THREAD

**Issue by durandal42** [arkayenro/arkinventory#736]
You said "its always been like that, the more pets you have the longer it takes to scan all of them when they update.  the pet api isnt the best and you have to scan all of them every single time"

In this case, please allow us to turn off pet scanning entirely. I use ArkInventory for inventory management, not pet management.

**Comment by durandal42** [comment]
AI spends *25 seconds* scanning my pet roster every time I acquire a new pet or cage an existing pet. Please let me turn this off.

**Comment by arkayenro** [comment]
added in 3.06.04
