### ISSUE TITLE
aborting a bank restack

### ISSUE THREAD

**Issue by wownob** [arkayenro/arkinventory#737]
After the latest patch (3.05.12) a bank restack (including storing reagents) always leads to "restacking bank aborted".

**Comment by pervel** [comment]
I can confirm this. It appears to happen when you haven't yet purchased all available bank slots.

**Comment by wownob** [comment]
pervel is right.
I tested the restack with a char which has all bank slots available.
Restack runs ok.
If I withdraw one bag form a bankslot, the error Comes up again.

**Comment by arkayenro** [comment]
yes, issue is due to unpurchased bank slots

fixed in 3.06.00
