### ISSUE TITLE
Request: Macros for summoning random mounts/companions

### ISSUE THREAD

**Issue by mjsmagalhaes** [arkayenro/arkinventory#738]
I would like to suggest a macro(slash command) to summon random mount/companion.

**Comment by mjsmagalhaes** [comment]
My description was terrible ... Improved it to say what i meant. :)

**Comment by nawlbergs** [comment]
this is not the mod for that...

**Comment by arkayenro** [comment]
make sure your mounts/pets are setup

mount macro (or use the keybinding)
/run ArkInventory.LDB.Mounts:OnClick( )

pet macro
/run ArkInventory.LDB.Pets:OnClick( )
