### ISSUE TITLE
[Visual Bug] Guild Bank + Item Tooltip's

### ISSUE THREAD

**Issue by Medivha** [arkayenro/arkinventory#740]
I copy paste the text from the TSM website, they send me to you! 

Hi Tradeskillmaster Team,

I have a visual bug on the tooltip's from items when i hover them if the Guild Bank is open! It shows some Tooltip parts multiple times and disapear so it flickers.
And it is only when i have ArkInventory + TSM or Auctinator + TSM activated and the Guild Bank is open.

When i have one of the following setups i have no problems:
TSM alone,
ARkInv alone,
Auctionator alone 
or ArkInv + Auctionator

I was assuming, TSM have some confliction issues with these addons and it is on TSM's side.

http://imgur.com/4dSHVtt (with ArkInv+TSM)
- on ArkInv it is only in my inventory

http://imgur.com/2yL8yFU (with Auctionator+TSM)
- on Auctionator it is on every tooltip, also when i hover something else and in this case it expands endless

TSM Versions http://imgur.com/eznbBe0
ArkInventory 3.05.12
Auctionator 3.2.6

All other Addons was disabled and i enabled only the combinations mentioned above.
I tested it with BugGrabber and BugSack but i dont got any LUA error!

So because it always appears when TSM is involved i post it here first and when it is not on your side i move to the ArkInventory and Auctionator sides.

So thanks for reading and i wish you all Merry Christmas!

Original TSM post:
http://stormspire.net/tradeskillmaster-addon/17976-%5Bvisual-bug%5D-guild-bank-item-tooltips.html

**Comment by Medivha** [comment]
some response from auctionator and TSM dev maybe you join the discussion
https://github.com/jrob8577/AuctionatorAddon/issues/58

**Comment by arkayenro** [comment]
not an ai issue

TSM is setting GameToolip when it doesnt need to.  they should use a private tooltip instead so as not to interfere with GameTooltip.
