### ISSUE TITLE
question: Crafting materials in crafting bag and by rule?

### ISSUE THREAD

**Issue by Naesstrom** [arkayenro/arkinventory#741]
So, I never found a place to ask a question so I'll do it right here, might end up being a request.

I'm storing all my reagents and crafting materials in Blizzards fancy bag in the bank but I also want them organized by my AI rules so that my cloth doesn't smell like dead fish etc. Have tried multiple ways but they just stay in the reagent bag for some reason.

Any ideas?

**Comment by arkayenro** [comment]
it will depend on how you have the bank setup to display.  go into edit mode an check what category your cloth is assigned and see if that is the correct category, if it is then move that category to the bar you would like it to display on
