### ISSUE TITLE
No tooltip in guild bank for caged pets when custom tooltip disabled.

### ISSUE THREAD

**Issue by JoshDave** [arkayenro/arkinventory#742]
When custom tooltips for battle pets are disabled, tooltips for caged pets are not displayed in the guild bank. Tooltips for caged pets are displayed normally in bags and bank. Tooltips for non-used pets are not affected.

Test setup:
ArkInventory v3.05.12
No other addons enabled.
Display > Tooltips > Battle Pet > Custom > Enabled = unchecked

**Comment by arkayenro** [comment]
thats because the item is a pet cage and when you put them in the vault there are no parameters returned when you set the tooltip, unlike for the bag and bank, to tell you whats inside the cage.

essentially its a blizzard bug they need to fix.  once fixed my code should pick up the data
