### ISSUE TITLE
Too much lag to use even with rules disabled

### ISSUE THREAD

**Issue by monolithsan** [arkayenro/arkinventory#743]
https://videobin.org/+bcc/eur.html  6 seconds to open my bank with no rules used with rules on it takes about 10 seconds

**Comment by arkayenro** [comment]
depends on what rule functions you used.  first opening will always take longer as it has to categorise every item.  how long was the second opening?

**Comment by monolithsan** [comment]
I would like to apologize, it seems the issue was another addon but I do not know what one was causing it.  Currently I am back to using ark without the issues I was experiencing in that video :)
