### ISSUE TITLE
Item age not displaying in guild bank

### ISSUE THREAD

**Issue by Ylaana** [arkayenro/arkinventory#744]
I've noticed that item age display has stopped working for the guild bank. I have deleted and recreated my profile to no avail. It seems to work fine for my bags and personal bank, but ticking the option in Settings for the guild bank has no effect. 

To my knowledge, this used to work, and is incredibly useful when you're clearing out old/unwanted items.

**Comment by arkayenro** [comment]
the code has it set to only show for the bag, not the bank or vault, but i dont see why its limited like that when theres an option to enable/disable it

**Comment by arkayenro** [comment]
fixed in 3.06.04
