### ISSUE TITLE
System > 0402. Junk

### ISSUE THREAD

**Issue by Nomad461** [arkayenro/arkinventory#750]
When opening up my guild bank, several items are classified as System > 0402. Junk.
A /reload clears the issue up.
Looking at other tickets, it seems like it might be a Blizz issue.

**Comment by arkayenro** [comment]
seeing as a reload is "fixing" it then its not a translation delay issue, or a hard coded system category assignment.

im not sure how it could be a blizzard issue either as if they set the items category to junk it would stay like that.

which item is it and what category does it end up on when working correctly?

**Comment by Nomad461** [comment]
Item enchantments seem to be the most frequent culprit.  They end up in the
correct category after a reload.
After further pondering, I don't think it is an AI issue as the items are
put in the proper place for a junk item.

Thanks again for the awesome addon and getting back to me!

**Comment by arkayenro** [comment]
if you figure anything out feel free to re-open this
