### ISSUE TITLE
Host code on github

### ISSUE THREAD

**Issue by spiralofhope** [arkayenro/arkinventory#751]
https://github.com/arkayenro/arkinventory/blob/master/README.md

.. claims that your code will be posted up here, but it is not.

Would you upload your repository to github?  This way, others can do pull requests and help contribute more easily.

**Comment by arkayenro** [comment]
changed the readme

at some point i might upload the code here but it was mostly for the wiki/issue features that it was moved here when googlecode shut down

once i have some time i can look into how to setup git on my end and sync with it

**Comment by spiralofhope** [comment]
Sounds good.

Do you need to keep this ticket open as a reminder?

**Comment by arkayenro** [comment]
no, should be ok, my nas's os comes with a git server in the next update so i'll play with it then

**Comment by spiralofhope** [comment]
*poke*

Are you interested in hosting your source up here?

**Comment by arkayenro** [comment]
short answer has always been no.  github was for the issue tracking and wiki (which they are fine with) - but as i still use 'all rights reserved' it doesnt mesh with the rules (copyright/licensing) of a public git repository.

long answer, maybe, if i ever get around to learning git, setting up a workflow to replace my current svn based workflow, and changing the type of copyright on my code

**Comment by spiralofhope** [comment]
I understand.  Thanks for clarifying.
