### ISSUE TITLE
[legion] can't rename Designs

### ISSUE THREAD

**Issue by b3n9ti** [arkayenro/arkinventory#754]
**you can type over the old, press okay, but nothing happens.**

off-topic question: is there gonna be a built-in category for artifact-power-upgrades?

**Comment by arkayenro** [comment]
will be fixed in 3.06.04

**Comment by arkayenro** [comment]
i dont have the legion beta, only the ptr, so not sure what they look like but if they are easy to work out i can probably add one in for them

**Comment by b3n9ti** [comment]
the category they're in now is consumables (other)...
