### ISSUE TITLE
Rule for a specific stat

### ISSUE THREAD

**Issue by stonedune** [arkayenro/arkinventory#756]
Is there a way to write a rule that would take all rings with "agility" or any other defined stat and sort them out? I only want to see agility items on my rogue not any strength or intellect ones and have those sorted separately.

**Comment by Yanngo** [comment]
https://github.com/arkayenro/arkinventory/wiki/RuleFunction_Tooltip
`tt( "agility" )` should work? No rings with agility anymore though.

**Comment by joevt** [comment]
tt( "agility" ) and equip( "finger" )

Also, you can use regular expressions in some cases if you want to be more specific about the formatting of the stat in the tooltip, like this

    tt( "%+ %d+ Speed" )

%+ means + (if the % wasn't there, then the + would be misinterpreted)
%d means a digit
%d+ means one or more digits

**Comment by stonedune** [comment]
Awesome, thanks. I knew it was something easy I was just missing.

**Comment by ragerdl** [comment]
Just as a followup, the space after the `%+` needs to be removed.  As in
```
tt( "%+%d+ Speed" )
```
