### ISSUE TITLE
Legion Beta: Sorting 'On Window Open'

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#757]
I installed the 3.06.03 LEGION BETA version to test on the Beta and found that the option to sort 'on window open' and 'instant' options seems to be gone.  These options used to be found under Settings -> Window -> Sorting and allowed for full control of the sort behavior per window type.

I did notice that some of the preferences have moved around perhaps in an attempt to streamline them, but I couldn't find these options anywhere else in the new views.

Can you please look into adding that functionality back into the addon?  If it's already there and I simply overlooked where it can now be found, can you please respond to the new location?

This is one of my 'must have' addons.  I simply love it.  Thanks!

**Comment by arkayenro** [comment]
i think i moved it to the global area, where the font is located.

although im moving it back to the style area because i think it makes more sense there (plus that way all the settings are together)

**Comment by arkayenro** [comment]
3.06.04 moved it back to the window options and defaulted it back to "on window open"
