### ISSUE TITLE
PTR errors - attempt to index global 'ArkInventory' (a nil value)

### ISSUE THREAD

**Issue by jrnt28** [arkayenro/arkinventory#760]
Using 3.06.04_LEGION_BETA, I'm getting this error when I login to the PTR  when ArkInventory is the only addon in the AddOns folder and:
1. I copy a fresh SavedVariables\ArkInventory.lua from live and login.
2. I exit, delete SavedVariables\ArkInventory.lua, and login again (let it create default SavedVariables\ArkInventory.lua).
3. I exit and login again (using the default SavedVariables\ArkInventory.lua created from step #2).

After step #2 and #3, SavedVariables\ArkInventory.lua contains only the line:
ARKINVDB = nil

I was curious if the error happened using a default SavedVariables\ArkInventory.lua from live, so I:
1. Deleted/Moved SavedVariables\ArkInventory.lua from live
2. Logged into live and logged out.
3. Copied the newly-created SavedVariables\ArkInventory.lua from live to the PTR folder.
4. Logged into the PTR (again with only ArkInventory loaded).
This also resulted in the same error.

I pasted the error below.

( Btw, I get the missing AceSerializer lib error that others reported when I login with ArkInventory plus several other mods, so I suspect one of the other mods is causing library conflicts.  I'm still trying to figure out which, but the above error happens with only ArkInventory loaded. )

---

Message: ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:86: attempt to index global 'ArkInventory' (a nil value)
Time: 07/18/16 00:52:08
Count: 1
Stack: ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:86: in function <...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:81>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:558: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:651: in function <...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:482: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:993: in function <Interface\FrameXML\UIParent.lua:891>

Locals: (*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'ArkInventory' (a nil value)"
pairs = <function> defined =[C]:-1
string = <table> {
 split = <function> defined =[C]:-1
 match = <function> defined =[C]:-1
 gmatch = <function> defined =[C]:-1
 upper = <function> defined =[C]:-1
 gsub = <function> defined =[C]:-1
 format = <function> defined =[C]:-1
 lower = <function> defined =[C]:-1
 sub = <function> defined =[C]:-1
 gfind = <function> defined =[C]:-1
 rep = <function> defined =[C]:-1
 char = <function> defined =[C]:-1
 rtgsub = <function> defined @Interface\FrameXML\RestrictedInfrastructure.lua:610
 join = <function> defined =[C]:-1
 reverse = <function> defined =[C]:-1
 byte = <function> defined =[C]:-1
 trim = <function> defined =[C]:-1
 len = <function> defined =[C]:-1
 find = <function> defined =[C]:-1
}

**Comment by jrnt28** [comment]
In all cases with this error ArkInventory doesn't load.

**Comment by arkayenro** [comment]
if any library is missing it stops loading at that point.

where did you download the file from?

If it was a zip file can you look in it under `...\Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-Serializer` to see if there are any files in there or not, same for your own wow install, are the files in there?

**Comment by jrnt28** [comment]
Well to clarify, I am not getting the missing Serializer lib error.  I only get the error shown above, "'ArkInventory' (a nil value)".  I only get the missing Serializer lib error only when I load AI with other addons, which is not the case here.  When I load AI alone, I get the "nil value" error instead.

I do see 2 files under ...\ArkInventory\Externals\curse\svn\Ace3-Serializer :+1: 
07/16/2016  03:50 PM             9,336 AceSerializer-3.0.lua
07/16/2016  03:50 PM               219 AceSerializer-3.0.xml

I just tried re-downloading from curse, then wowace and login to the PTR with each (only AI loaded) and still get the error.

My download links are:
http://mods.curse.com/addons/wow/ark-inventory/903742
http://www.wowace.com/addons/ark-inventory/files/1362-3-06-04-legion-beta/

If you'd like to verify the contents, I re-posted both zip files (drive lets you browse them without downloading):
https://drive.google.com/open?id=0B9lWKVF0R2wMeUhaVlJEY2gtY1E   (zip from curse)
https://drive.google.com/open?id=0B9lWKVF0R2wMTDMzQ1FmUUw0VVk   (zip from wowace)

(I diffed the 2 zip files, and they appear to be identical)

It's weird that nobody else is having this problem.  If it's just me, then I'll just wait until the pre-patch goes live and see if it's still happening there.

**Comment by gunner007cd** [comment]
I do get a similar error, the folder under SVN is actually called Ace3-AceSerializer, but the files are there, error output is below.

Message: Interface\AddOns\ArkInventory\ArkInventoryConst.lua:14: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceSerializer-3.0".
Time: 07/18/16 14:55:07
Count: 1
Stack: [C]: ?
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:220: in function `EmbedLibrary'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:202: in function `EmbedLibraries'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:169: in function `NewAddon'
Interface\AddOns\ArkInventory\ArkInventoryConst.lua:14: in main chunk

Locals: (*temporary) = "Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceSerializer-3.0"."

**Comment by arkayenro** [comment]
can you disable every other mod youre loading and test it with just arkinventory? it should work as thats all i have running on the ptr on my machine.

then turn on any other mods one at a time to see where it breaks

**Comment by gunner007cd** [comment]
Happens with ARK alone. Just to be 100% sure, I deleted WTF and Interface and only added back in ARK.
Actually this is running under Legion beta... maybe that's it?

Attached SS:    https://postimg.org/image/hicec8sbb/

**Comment by arkayenro** [comment]
possibly a beta thing but i found one place where i can remove the reference to the serializer library and it still works ok on the ptr, i'll upload that in a couple of minutes

**Comment by arkayenro** [comment]
ok, theres an r530 alpha version on curse, could you try that and see if it fixes it?

**Comment by gunner007cd** [comment]
Error is gone (using PTR client, however ArkInventory doesn't seem to load. (or at least have any hooks - /arkinventory doesn't seem to do anything. Does show up in the list of addons though. Again, only ARKInventory is installed)

**Comment by arkayenro** [comment]
does it at least print out the bits for loading realm data, being enabled, and then loading the translations?

**Comment by jrnt28** [comment]
I tried the r530 link from above, but it gave the same "nil value" error.

I tried 3.06.03_LEGION_BETA (from curse), and it works without error.  Bag categories are gone (using settings copied from live), but those are easy to redo.

**Comment by jrnt28** [comment]
Actually, the error from r530 is slightly different (PTR):

Message: ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:86: attempt to index field 'db' (a nil value)
Time: 07/18/16 16:52:49
Count: 1
Stack: ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:86: in function <...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:81>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:558: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:651: in function <...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:482: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:993: in function <Interface\FrameXML\UIParent.lua:891>

Locals: (*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'db' (a nil value)"
pairs = <function> defined =[C]:-1
string = <table> {
 split = <function> defined =[C]:-1
 match = <function> defined =[C]:-1
 gmatch = <function> defined =[C]:-1
 upper = <function> defined =[C]:-1
 gsub = <function> defined =[C]:-1
 format = <function> defined =[C]:-1
 lower = <function> defined =[C]:-1
 sub = <function> defined =[C]:-1
 gfind = <function> defined =[C]:-1
 rep = <function> defined =[C]:-1
 char = <function> defined =[C]:-1
 rtgsub = <function> defined @Interface\FrameXML\RestrictedInfrastructure.lua:610
 join = <function> defined =[C]:-1
 reverse = <function> defined =[C]:-1
 byte = <function> defined =[C]:-1
 trim = <function> defined =[C]:-1
 len = <function> defined =[C]:-1
 find = <function> defined =[C]:-1
}

**Comment by gunner007cd** [comment]
To answer your question, no it doesn't print out any text to chat like the working versions do.

**Comment by jbresciani** [comment]
I had to load the ace3 module as a stand alone module from the curse client to get rid of those errors

**Comment by arkayenro** [comment]
fixed in 3.06.09
