### ISSUE TITLE
Issue upon logging into Live (7.0.3) with newest version

### ISSUE THREAD

**Issue by TiaMaster** [arkayenro/arkinventory#761]
4x ArkInventory\ArkInventoryRealms.lua:212: bad argument #1 to 'unpack' (table expected, got no value)
[C]: in function `unpack'
ArkInventory\ArkInventoryRealms.lua:212: in main chunk

Locals:
(*temporary) = "table expected, got no value"

**Comment by nithaiah** [comment]
Beat me to it.

**Comment by arkayenro** [comment]
will be fixed in 3.06.07

**Comment by arkayenro** [comment]
fixed in 3.06.07
