### ISSUE TITLE
'On Window Open' sort is not working.

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#762]
I found the new location for the sorting style for the windows, but when I select 'On Window Open' it doesn't appear to work.  I move an item to another location, close the window and then open the window and that item is still where I moved it rather than where it should be given the configuration.

I tried changing the 'Restack' method from 'Blizzard: Cleanup' to 'ArkInventory: Restack' thinking maybe that would do something but it didn't.

**Comment by alexbrault** [comment]
Automatic sorting altogether seems to have this issue. I tried setting it to "Instantly" as a workaround, but that wasn't working either

**Comment by arkayenro** [comment]
will be fixed in 3.06.07

**Comment by arkayenro** [comment]
fixed in 3.06.07
