### ISSUE TITLE
Item Comparison Tooltip Windows Overlap

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#763]
Mouseover an item and the tooltip for the given item is shown and the tooltip for the currently equipped item is shown to the right.

I have the ArkInventory bag window configured to show in the lower right-hand corner of the screen so whenever an item in the window happens to be close to the right-hand side, the currently equipped tooltip 'runs out of room' and it pushed to the left where it overlaps the original item tooltip.

I have a workaround -- hitting 'shift' to trigger Blizzard's comparison tooltip which is shown to the left and doesn't overlap -- but I'd rather not have to use it.

Any way to fix this behavior?

P.S.  This also seems to happen on the cascading dropdowns while in edit mode and assigning a category to an item.  If the menu pushes to the right and it goes off the screen, it's shifted left and overlaps.  It does appear that at times, though, it's 'smart' enough to open the menus to the left rather than the right.

**Comment by arkayenro** [comment]
> Mouseover an item and the tooltip for the given item is shown and the tooltip for the currently equipped item is shown to the right.

ai does not do this at all, another mod must be doing it

**Comment by Zepharon** [comment]
I have now tested with ArkInventory as the only installed addon and the mouseover tooltip issue that Calesta describes still  happens?

**Comment by arkayenro** [comment]
you can only have one mouseover tooltip, multiple tooltips should only appear if you press shift

which of your items generates two tooltips on mouseover?

perhaps a screenshot because this doesnt make sense to me

**Comment by Zepharon** [comment]
Alright, I've now taken screenshots of both situations - one where I don't hold shift and one where I do.

Without Shift held down:
http://i.imgur.com/cPPDh2D.png

With Shift held down:
http://i.imgur.com/yTveLfM.png

This is a level 1 character, freshly made. No other addons installed aside from ArkInventory. The compare tooltip only appears when there is actually items to compare, such as my starter robe with the heirloom robe - or my starter staff with the heirloom staff. When there is no comparison available the tooltip is fine and shows no errors. It is ONLY when you compare things and it compares automatically without holding down shift (thus producing the overlapping error). If you press Shift, you re-align the compare windows so they do not overlap.

If you need any other information, I'll be happy to provide it as I really enjoy this addon!

**Comment by Calesta** [comment]
Exactly the same behavior that I see, Zepharon, even when ArkInventory is installed alone.

**Comment by arkayenro** [comment]
that is really odd, there must be a base interface option to turn that on because i dont get the comparison tooltips unless i hold the shift key down

**Comment by Zepharon** [comment]
Alright! Here we go!
It seems there's an advanced option in WoW baseline, where you can enable always compare. It's not found in the normal options and is enabled/disabled via a macro.

For more info: http://wow.gamepedia.com/CVar_alwaysCompareItems

I have now disabled it and ArkInventory now works as you describe, Arkayenro! Thanks for going along with the troubleshooting and apologies that the error was on my end.

**Comment by arkayenro** [comment]
now that makes more sense, at least now i can turn it on and see if i can code something for it

**Comment by arkayenro** [comment]
will be fixed in .15

**Comment by arkayenro** [comment]
fixed in .15
