### ISSUE TITLE
Error when attempting to change settings in 7.0.3 (Live) with version 3.06.06

### ISSUE THREAD

**Issue by Johnny3D** [arkayenro/arkinventory#764]
When I go to Interface > Addons > ArkInventory I get the following error and no ability to change any of the settings for ArkInventory:

Message: Interface\AddOns\ArkInventory\ArkInventoryConfig.lua:54: attempt to index field 'CONST' (a nil value)
Time: 07/19/16 18:04:01
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventoryConfig.lua:54: in function `member'
...ceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:249: in function <...ceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:197>
...ceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:371: in function <...ceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:344>
...ceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1059: in function <...ceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1055>
...ceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1588: in function `FeedGroup'
...ceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1868: in function `Open'
...ceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1896: in function <...ceConfig\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1894>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...ntory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:314: in function `Fire'
...-AceGUI\widgets\AceGUIContainer-BlizOptionsGroup.lua:20: in function <...-AceGUI\widgets\AceGUIContainer-BlizOptionsGroup.lua:19>
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:2336: in function `SetUIPanel'
Interface\FrameXML\UIParent.lua:2138: in function `ShowUIPanel'
Interface\FrameXML\UIParent.lua:2048: in function <Interface\FrameXML\UIParent.lua:2044>
[C]: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:2830: in function `ShowUIPanel'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals: <none>

____________

I have removed all addons and installed only ArkInventory. I have installed it by way of the download from WowInterface manually. When that did not work I deleted the manual installation and installed it via Curse.

I have tried it with Ace3 not installed. With Ace3 installed. I keep getting this same error and no settings.

**Comment by arkayenro** [comment]
fixed in 3.06.07
