### ISSUE TITLE
3.06.08 AceSerializer wrong in ArkInventoryExternals.xml

### ISSUE THREAD

**Issue by porgig** [arkayenro/arkinventory#767]
Standalone version of addon is looking for AceSerializer, cannot find it because ArkInventoryExternals.xml has it listed wrong on line 19.

It's this:
`<Include file="Externals\curse\svn\Ace3-Serializer\AceSerializer-3.0.xml" />`
`<Include file="Externals\curse\svn\Ace3-AceSerializer\AceSerializer-3.0.xml" />`
Should be this ^

**Comment by arkayenro** [comment]
already fixed in .09

its why i dont like the way curse packages up stuff, its too easy to miss simple typos
