### ISSUE TITLE
Assigned categories not working 3.06.10

### ISSUE THREAD

**Issue by joevt** [arkayenro/arkinventory#769]
I'm using ArkInventory 3.06.10. I have many items (couple thousand) assigned a category in previous versions of ArkInventory, but those assignments are ignored in the current version.

I looked at my saved variables and the assignments appear to still exist. They are located here:
```
ARKINVDB = {
	["global"] = {
		["option"] = {
			["catset"] = {
				["data"] = {
					[1001] = {
						["used"] = "Y",
						["name"] = "Default",
						["category"] = {
							["assign"] = {
```

The old assignments look like this:

```
								["item:18986:0"] = "2!20",
								["item:18986:1"] = "2!20",
								["item:37863:0"] = "2!20",
								["item:37863:1"] = "2!20",
								["item:22742:1"] = "2!13",
```

new assignments look like this:
```
								["9999:item:18986:1"] = "2!20",
								["1001:item:37863:1"] = "2!20",
								["1001:item:22742:1"] = "2!13",
```

Shouldn't there be update code to update the old assignments?

In the new format, I don't know what the first number is (1001 is default category set? but what is 9999?). or why the old assignments have both :0 and :1 items. I think the number before the ! is category type (3 = rule?, 2 = custom category?). The number after ! is the category index or rule index. I think rules used to start at 1 but now start at 1001?

**Comment by Cy4n1d3** [comment]
I'm experiencing this as well.
Furthermore `Style`, `Layout` and `Category Set` under `Controls`-Setting is not being set correctly (all default to 9999 instead of i.e. 1001) after updating the addon from the 6.2 to the current 7.0 release version. I think those should be migrated?

**Comment by arkayenro** [comment]
> Shouldn't there be update code to update the old assignments?
there should if i had changed it, it was supposed to stay the same, but the caching code got updated to handle multiple users and i didnt notice.

the categories will be corrected in 3.06.11

> In the new format, I don't know what the first number is (1001 is default category set? 
just the category set id

> but what is 9999?).
the default category set id.  defaults are from 9000-9999, users are from 1000-8999

> or why the old assignments have both :0 and :1 items.
soulbound state

> I think the number before the ! is category type (3 = rule?, 2 = custom category?). The number after ! is the category index or rule index. I think rules used to start at 1 but now start at 1001?
correct

**Comment by arkayenro** [comment]
> Furthermore Style, Layout and Category Set under Controls-Setting is not being set correctly (all default to 9999 instead of i.e. 1001) after updating the addon from the 6.2 to the current 7.0 release version.  I think those should be migrated?

they should have been unless something stopped it.  its possible your data is still intact on the profile if the upgrade never ran.  it might be possible to re-run the upgrade code if you logout then change the version number on the profile back to 30512 and then login.  each profile has its own version number so make sure to change the correct one(s)

**Comment by Cy4n1d3** [comment]
My `ArkInventory.lua.bak` contains `["version"] = 30512,`. This is the lua I've backed up before updating my client to 7.0.3 this morning.
I can reproduce the problem I've described above by logging out, replacing the (upgraded) lua with my backup and logging back in. This is the output I'm getting, if it's worth anything:
> [13:25:04] ArkInventory: Upgrading profile data for [Default] to v30602
> [13:25:04] ArkInventory: transferring profile data to design Default - Bag
> [13:25:04] ArkInventory: transferring profile data to design Default - Bank
> [13:25:04] ArkInventory: transferring profile data to design Default - Guild Bank
> [13:25:04] ArkInventory: transferring profile data to design Default - Mail
> [13:25:04] ArkInventory: transferring profile data to design Default - Wearing
> [13:25:04] ArkInventory: transferring profile data to design Default - Pet
> [13:25:04] ArkInventory: transferring profile data to design Default - Mount
> [13:25:04] ArkInventory: transferring profile data to design Default - Currency
> [13:25:04] ArkInventory: transferring profile data to design Default - Auctions
> [13:25:04] ArkInventory: transferring profile data to design Default - Void Storage
> [13:25:04] ArkInventory: transferring profile data to design Default - Toy Box
> [13:25:04] ArkInventory: Upgrading global option data to v30603
> [13:25:04] ArkInventory: Upgrading profile data for [Default] to v30604
> [13:25:04] ArkInventory: Upgrading global option data to v30604
> [13:25:04] ArkInventory: Upgrading profile data for [Default] to v30605
> [13:25:04] ArkInventory: v3.06.10 Enabled

As a test I then changed the version in the (now upgraded as well) lua back to `30512` and logged back in, which led to another upgrade round:
> [13:29:00] ArkInventory: Upgrading profile data for [Default] to v30602
> [13:29:00] ArkInventory: Upgrading global option data to v30603
> [13:29:00] ArkInventory: Upgrading profile data for [Default] to v30604
> [13:29:00] ArkInventory: Upgrading global option data to v30604
> [13:29:00] ArkInventory: Upgrading profile data for [Default] to v30605
> [13:29:00] ArkInventory: v3.06.10 Enabled

It's still broken however.

**Comment by arkayenro** [comment]
can you mail me you lua file, i can check to see why its not converting them properly, all of mine worked

**Comment by Cy4n1d3** [comment]
I've send you the files, tried out 3.06.11 in the meantime - didn't help in my case.
Categories are still messed up :'(

**Comment by arkayenro** [comment]
all, good, i worked out what caused it to fail the upgrade, will be fixed in .12 and you can run your backup through it

**Comment by Cy4n1d3** [comment]
Awesome, I really appreciate your efforts :)
Thanks for looking into it!

**Comment by joevt** [comment]
Thanks. Looks like .12 fixed my item assigned categories.

**Comment by Cy4n1d3** [comment]
My upgrade also went smooth, looks good so far! Thanks!

**Comment by knocknoc** [comment]
DL'ed the lastest update but my settings appear to be gone, ok I go to redo it but when I go to click on a bar it says Bar 5 *Locked* (in red) sort method & assignable categories both are locked. Should I just uninstall & reinstall?

**Comment by arkayenro** [comment]
the upgrade code should be working correctly now, or at least most of the bugs appear to be gone.

if you have a backup of your saved variables file then restore it and start the game again
