### ISSUE TITLE
Error when sorting

### ISSUE THREAD

**Issue by TiaMaster** [arkayenro/arkinventory#771]
1x ...aceArkInventoryConfig\ArkInventoryConfig-3.06.12.lua:2249: attempt to call field 'ConfigInternalStyle' (a nil value)
...aceArkInventoryConfig\ArkInventoryConfig-3.06.12.lua:2249: in function <...aceArkInventoryConfig\ArkInventoryConfig.lua:2248>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-61.lua:799: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[4]"]:9: in function <[string "safecall Dispatcher[4]"]:5>
(tail call): ?
Ace3\AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...dOns\Ace3\AceGUI-3.0-34\widgets\AceGUIWidget-Button.lua:22: in function <...dOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>

Locals:
nil

**Comment by arkayenro** [comment]
will be fixed in .13

**Comment by arkayenro** [comment]
fixed in 30613
