### ISSUE TITLE
Items sometimes in wrong categories

### ISSUE THREAD

**Issue by TiaMaster** [arkayenro/arkinventory#773]
I have no error for this, but, sometimes items will appear in my Misc bar which is the first one created by AI.
For instance, right now I have a pair of BOE feet that I just put on, and they went straight to the first bar.
Reloading UI, opening bags again, and closing the game all SOMETIMES make it work again - but not all the time. This is just an example, of which I have several.

**Comment by arkayenro** [comment]
go into edit mode and check the debug info, see which category it has been assigned

**Comment by arkayenro** [comment]
found the problem, will be fixed in .13

**Comment by arkayenro** [comment]
fixed in .13
