### ISSUE TITLE
Items not Showing on Expected Bar

### ISSUE THREAD

**Issue by prizmpaladin** [arkayenro/arkinventory#776]
I'm using ArkInventory 3.06.12. I have items that have either a custom category or rule assigned to them, however they show on the default bar instead of that bar that category or rule is enabled on. For example:

Hexweave Robe fits rule Current Gear (1006) and the item reflects that:
![1](https://cloud.githubusercontent.com/assets/2113858/17007198/9e0d1af4-4eb4-11e6-8bb9-8f97d32d9796.png)

But the item is in Bar 1, which is the default bar:
![2](https://cloud.githubusercontent.com/assets/2113858/17007200/a47b7552-4eb4-11e6-8249-1cb1af91cafb.png)

But I have Bar 4 that has the Current Gear (1006) rule assigned to it and enabled:
![3](https://cloud.githubusercontent.com/assets/2113858/17007201/a7b7afd8-4eb4-11e6-8108-6aa815b25c51.png)

I've tried reloading and restacking, and I've looked through the wiki but can't find an explanation for this behavior.

**Comment by prizmpaladin** [comment]
Tested this more on another character that I hadn't touched yet. Seems to be okay with existing items in my bag after setting the values in Control for the bag. But new items go into the default bar. When I click restack, it causes everything to go to the default bar. Not seeing any lua errors.

**Comment by arkayenro** [comment]
i think ive found the issue and it should be fixed in .13

**Comment by arkayenro** [comment]
fixed in .13
