### ISSUE TITLE
'Refresh' isn't stacking like items.

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#777]
Updated to the latest build, 3.06.11.

Prior to 7.0.3 when I clicked the 'refresh' button, multiple stacks of the same item used to combine until the max stack count was hit.  This doesn't happen now.  I tried both 'Blizzard: Cleanup' and 'ArkInventory: Restack' methods.

To test, split a stack of mats and then refresh.  The two stacks remain separate.

**Comment by arkayenro** [comment]
the blue refresh icon just updates the windows, you want the red restack icon.  see if that one works

**Comment by Calesta** [comment]
I'll test as soon as I'm home and let you know.  I don't remember there being two refresh buttons before. :)

**Comment by Calesta** [comment]
You're right!  It was the red restack button that I used to hit.  Safe to close this ticket.  Sorry for the time wasted.

**Comment by arkayenro** [comment]
no problem
