### ISSUE TITLE
Blueprint settings in same profile do not carry over to different characters

### ISSUE THREAD

**Issue by Yanngo** [arkayenro/arkinventory#779]
Addon version 3.06.11.

I have **one and the same profile for all toons** to minimize memory footprint, addon settings loading time and enjoy the well-tuned ArkInventory experience. On a new toon I always choose my universal profile.

After patch 7.0 hit I loaded the first character, **set up ArkInventory just this way**
https://www.youtube.com/watch?v=f_XFlsAYBho
and logged out to move on to the next character.

For some reason I **had to do the same procedure on every character**
http://imgur.com/ocGYGEs
although all of them had the ANEW profile selected from before 7.0. I also checked after the patch that they still had the right profile selected.

Addon version 3.06.12.
Logged a character today for the first time since the patch hit. Switched to ANEW profile. The blueprint settings did not set properly either.

**Comment by arkayenro** [comment]
should be fixed in .13

you can run your backup through again or just keep on setting the controls for each one

**Comment by arkayenro** [comment]
fixed in .13
