### ISSUE TITLE
New items

### ISSUE THREAD

**Issue by Syrion** [arkayenro/arkinventory#781]
Hello,

When equipping and item from inventory, the piece removed from me and put i in my inventory is always considered as new (timer put to 1min). Is there a way to avoid this ? It's perturbing with outfits items considered new when switching.

Thanks for your time and for this great addon btw !

(Sorry for my english ^^)

**Comment by Acrivec** [comment]
Bump.

**Comment by arkayenro** [comment]
dont bump old issues, open your own.  and the answer is no because the game sees them as new

new does not mean utterly new and never seen before, it just means it wasnt in that slot before (or the item count changed)

**Comment by Acrivec** [comment]
> 
> 
> dont bump old issues, open your own. and the answer is no because the game sees them as new
> 
> new does not mean utterly new and never seen before, it just means it wasnt in that slot before (or the item count changed)

You're like, breaking the basic rule of all forums. Don't open new topics if the issue has been already mentioned and topic is not closed. 'Use search option before posting' is the most common reply ever.
If you don't close issues from 2016 as invalid/won't be fixed/I don't care it's your fault. I see that someone already posted an issue about the exact problem I'm experiencing, so I pin up to that. No need for duplicates.

I wanted to write this on curseforge but it's throwing error 200 constantly:
New Items function is going nuts at least 3 times a day. All items in my bags are suddenly marked as new, and after I reset new status - I'm losing the actually new ones.
Item age - resetting randomly. Sometimes I have an item for days, and then boom - it's 3 minutes old. Useless.

 

Search function - weird. There are rules, but you can't use those rules there. Want to highlight all items below 100 ilvl? Good luck.
Or maybe you can, but you won't find that on wiki...


Seems I just have to wait for Adibags to be updated.
