### ISSUE TITLE
Help with displayed items

### ISSUE THREAD

**Issue by Imre1312** [arkayenro/arkinventory#787]
Hi,

after the last patch when I open the guildbank and normal bank all items have randomly switched position and the whole sorting was messed up. I dont really know how to describe this problem, I'm sorry^^ This is why I attached 2 screenshots: 
How it looks like now:
![How it looks like now](https://cloud.githubusercontent.com/assets/20599874/17061603/9bfc2c06-502f-11e6-98c5-6de372592095.PNG)
How it should look like when the add on is enabled(that's the screen where ArkInventory is disabled)
![How it should look like when the add on is enabled]
(https://cloud.githubusercontent.com/assets/20599874/17061604/9bfd163e-502f-11e6-8a55-e43626797b35.PNG)
I'm really new to ArkInventory and haven't really done any research, so if its an easy solution I'm really sorry. I also couldn't find anything in the FAQ or Issues that reflects my issue.

Hope you understand what I mean
Imre

**Comment by Yanngo** [comment]
Go to Settings >> Controls >> Guild Bank tab and uncheck Override checkbox. Read the description

![gbank_override](https://cloud.githubusercontent.com/assets/17704069/17062159/76469450-503a-11e6-9bca-77b38dc3ce1c.jpg)

**Comment by Imre1312** [comment]
Already thanks for you help, but that's not quite what I wanted. As I said, it's hard to explain xD I want to have the look and feel of Arkinventory still, but the sorting of the guild bank.
I'll try another way to explain it: 
In the first row you can see that all those potions of agilty in a row horizontally. 
I want that all those potions are in a row vertically just like it looks in the guild bank, Before the patch that's how it worked, now everything gets sorted horizontally.

Sorry if it is not clear what I mean, I can't explain that well :D

**Comment by Yanngo** [comment]
Go to Settings >> Sort Methods and try to make something of them.

**Comment by arkayenro** [comment]
for a classic guild bank layout you need to do the following;

- go to Settings > Design
    - add a new design
    - set the width to 14 
    - set the sort method to [9995] Guild Bank / Void Storage
- go to Controls > Guild Bank
    - set the Style to the Design you just created
    - set the Layout  to the Design you just created
    - leave the Category Set using the default
- open the vault

**Comment by Imre1312** [comment]
Thank you very much arkayenro, that's exactly what I needed. I really love this addon, tried some others but this is really the best one. Thanks for helping me out :)
