### ISSUE TITLE
Default Battle Pet UI Filters Turn Off

### ISSUE THREAD

**Issue by moosecat11** [arkayenro/arkinventory#791]
So I've troubleshooted this by turning off ALL other addons. It seems when ArkInventory is loaded, my battle pet collection window filters keep resetting themselves to off.

Just opening/closing the window over and over again, I see the list go blank, then come back sometimes (filters turn back on).

When I check the filters on a blank window, it has turned off "Not Collected" and all Pet Families and Sources.

If I turn off "Monitor" for pets in the config, the issue goes away.

Thank you!

**Comment by Yanngo** [comment]
Oh! Another confirmation then it is ArkInventory that does that.
I've even tried reading all the comments here http://www.wowinterface.com/forums/forumdisplay.php?f=153 and trying to look at LUA code to see whether ArkInventory has implemented the changes and apparently it has.

**Comment by arkayenro** [comment]
i could have sworn id updated the code for legion but it looks like i missed the pets filter somehow

will be fixed in the next version

**Comment by arkayenro** [comment]
fixed in .17
