### ISSUE TITLE
Issues with Rules and Categories

### ISSUE THREAD

**Issue by Recanna** [arkayenro/arkinventory#792]
I've been noticing oddities with items not obeying rules and categories all night. 

First, I deleted my entire wtf folder with the prepatch and set everything back up.  I've been building new rules and configuring bars all night. 

Instance #1:  When I add a new rule or category to bar it seems that it doesn't always move all items that the rule/category applies to into the new bar.  Sometimes restacking, refreshing, or reloading will correct this. Other times it just randomly fixes itself over time. In the screenshots below so far nothing has moved these boots into the correct Outfit bar.

![capture](https://cloud.githubusercontent.com/assets/20620702/17082244/5e482c5a-5144-11e6-8568-1c0f4880cfd1.PNG)
![capture2](https://cloud.githubusercontent.com/assets/20620702/17082245/6682c83a-5144-11e6-908d-153f1559b69f.PNG)

Instance #2:  I pulled a lot of things out of my bank which caused me to need to restack items.  When i clicked restack nearly all of my items ended up in the default #1 bar.  I had to reload the game to fix this. I didn't think to grab screenshots.

Instance #3: This may be related to instance number 1 but I have two Empty Drinking Horns, one is heroic and the other normal.  Both always show in the Outfit bar even though the second horn is not part of an outfit. 

Instance #4: After changing between equipped gear sets all of the newly un-equipped items show in the default bar #1. Reloading and refreshing does not appear to correct this but randomly it'll start working again.
![capture3](https://cloud.githubusercontent.com/assets/20620702/17082257/ee8bebbc-5144-11e6-9179-82c2d5307218.PNG)

**Comment by arkayenro** [comment]
item categorisation is flaky as all hell at the moment, as soon as i figure it out it will get fixed

**Comment by Recanna** [comment]
Fair enough. :) if you need any debug info or anything from me let me know.
Happy to supply.

**Comment by acemodder** [comment]
I have the same issues myself.   I have spent hours truying to fix it locally.    Good to know it's not just me being a noob.

**Comment by arkayenro** [comment]
if possible, try beta 3 and see if it seems better at the categorisation

**Comment by Recanna** [comment]
I'll install and test it out tonight. Thanks!

**Comment by acemodder** [comment]
Installed 3.07.00 BETA 3c now, going to test it now

**Comment by acemodder** [comment]
Still not assigning all items correctly.

See below.   Bar 9 is assigned the "equippable item"

![screenshot 2016-07-28 16 16 36](https://cloud.githubusercontent.com/assets/20584654/17218281/2b3641fa-54df-11e6-9ddc-56628d819bba.png)

However there are "equippable items" still in bar 1.   see here.....
![screenshot 2016-07-28 16 16 48](https://cloud.githubusercontent.com/assets/20584654/17218367/65e0f494-54df-11e6-9acf-6e4fad49c32b.png)

**Comment by acemodder** [comment]
And here showing I'm on the new beta

![screenshot 2016-07-28 16 22 44](https://cloud.githubusercontent.com/assets/20584654/17218422/a2118488-54df-11e6-9457-12f74d9ee563.png)

**Comment by Recanna** [comment]
I don't know how you have the rules set up but since that item is soulbound
wouldn't be in the bar you've assigned Equippable Items \ Soul bound?  I
wonder if the rules are conflicting somehow...

**Comment by acemodder** [comment]
Maybe, but arkinventory gives it the default equipable items, not equipable soulbound.

But randomly after closing and reopening my bags a few times it has corrected itself now.
But it wont stay corrected if it is like the previous versions, they tend to jump around from bar to bar on reopenings.

![screenshot 2016-07-28 16 29 39](https://cloud.githubusercontent.com/assets/20584654/17218728/c33413e6-54e0-11e6-8db5-9b861aa85c92.png)

**Comment by acemodder** [comment]
I just pressed "restack" and it moved some items back to bar 1 from Bar 9.  Not other changes made.

**Comment by arkayenro** [comment]
restack moves the item so rebuilds the data for it, can you try just picking up a problem item and moving it to another slot (preferably one with an item in it) then refresh and see if it goes into the correct category

if it does then it bad sotred item data and you can erase either everything via `/ai cache erase confirm` or just one character at a time (through the switch character menu)

if it is that then i might force an erase on everyone just to clean it up

**Comment by acemodder** [comment]
Hi, I have tried that, and it has not fixed it.   Moving items and then doing a refresh did nothing.   

And actually hitting the refresh button kills all the bar groupings.   and just puts everything in bag 1.    

I have to reboot/relog to get to catergorise again.

**Comment by Recanna** [comment]
Sorry for the delay, was a hectic raid night last night. In any case I did
download the 3beta and it was better than it had been. I noticed that
randomly a few items would show in the wrong bars and then randomly it
would correct itself. No rhyme or reason that I could detect. It almost
seemed like items that I used recently were wrong for a short period.
However I didn't have the random restacking issue that Acemodder is
describing.  I'll play around with it some more tonight.

**Comment by arkayenro** [comment]
can you check if you have the new items option enabled?

also assign the new items category to a bar out of the way to see if they are ending up in there, as that is the only thing that will invisibly override the default category

**Comment by Recanna** [comment]
I apparently did have the New Items feature turned on. I didn't catch that
when I configured my new profiles.  My old profile had it disabled. I just
set them to go into their own bar. It did move quite a few items that were
showing in bar1 that shouldn't have been.  I'll run a few timewalkers and
see how it behaves and let you know.

**Comment by Recanna** [comment]
Ok, I think that's fixed most of the issues though I think there is still
something off a bit.  I noticed that there were times items I had for a few
minutes would show in their normal bars but when I looted something new
they would go back into the new items bar. Here are some screenshots. 

I am running the beta 4. My bags were opened/closed/reopened between the screenshots.  I went through my loot log and it appears I picked up the Skeleton Lord's Cranium at 11:42 which means it MAY have still been a new item in the first screenshot but by the second they should have been moved to SB.

![wowscrnshot_073116_114457](https://cloud.githubusercontent.com/assets/20620702/17277825/01e3ae26-571b-11e6-8db8-6e99af48c700.jpg)
![wowscrnshot_073116_114623](https://cloud.githubusercontent.com/assets/20620702/17277827/04c7bc9a-571b-11e6-96d6-6eae175c8e74.jpg)

**Comment by acemodder** [comment]
disabling it seems to have fixed it for me

**Comment by arkayenro** [comment]
turn on the option to display the item age, that way you can tell if its been reset or not, the timer value is also in there so you'll see how long it takes before they are no longer considered new.

and if you dont need to know which items are new id turn that option off

**Comment by Recanna** [comment]
I disabled the new items feature and it does appear to be working correctly
now. I'm not gonna say that was the issue the whole time but... Definitely
seems to have been a major contributor.

**Comment by acemodder** [comment]
ive been testing this with new items on/off

It certainly does affect it, and that is the bug, for example if you use miners coffee, arkinventory considers the rest of the stack as a "new" item and moves it over.   This is certainly the reason for it, with it disabled, no issues at all.
