### ISSUE TITLE
Can't See Bank

### ISSUE THREAD

**Issue by Anaelle6737** [arkayenro/arkinventory#794]
When I got to open the bank it is giving me this error. The Bank frame opens but I can't see any of the items. I can add stuff to the bank though. Running version 3.06.17.

SharedXML\HybridScrollFrame.lua:65: attempt to perform arithmetic on local 'stepSize' (a nil value)
SharedXML\HybridScrollFrame.lua:65: in function <SharedXML\HybridScrollFrame.lua:57>

Locals:
self = ARKINV_Frame3Scroll {
 0 = <userdata>
 scrollDown = ARKINV_Frame3ScrollVerticalScrollScrollDownButton {
 }
 scrollBar = ARKINV_Frame3ScrollVerticalScroll {
 }
 scrollUp = ARKINV_Frame3ScrollVerticalScrollScrollUpButton {
 }
 scrollChild = ARKINV_Frame3ScrollScrollChild {
 }
}
delta = 1
stepSize = nil
minVal = 0
maxVal = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = ARKINV_Frame3ScrollVerticalScroll {
 0 = <userdata>
 trackBG = ARKINV_Frame3ScrollVerticalScrollTrack {
 }
 thumbTexture = ARKINV_Frame3ScrollVerticalScrollThumbTexture {
 }
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = 0
(*temporary) = 0
(*temporary) = ARKINV_Frame3ScrollVerticalScroll {
 0 = <userdata>
 trackBG = ARKINV_Frame3ScrollVerticalScrollTrack {
 }
 thumbTexture = ARKINV_Frame3ScrollVerticalScrollThumbTexture {
 }
}
(*temporary) = "attempt to perform arithmetic on local 'stepSize' (a nil value)"

**Comment by arkayenro** [comment]
thats very weird as stepSize is hardcoded to 80

**Comment by Anaelle6737** [comment]
Didn't get an error this morning but I did get this. I have attached a screen shot of it.  It is very similar to the DK bag issue.
![wowscrnshot_072616_135007](https://cloud.githubusercontent.com/assets/20633552/17153230/e8448a20-5338-11e6-8bdc-a9ee443fb092.jpg)

My bags are as follows:
Hexweave Bag
Royal Satchel x2
Tattered Hexcloth Sack
Enlarged Onyxia Hide backpack
Frostweave Bag
Dragon Hide Bag

Thanks!

**Comment by abackstrom** [comment]
My bank looks the same as that screenshot.

**Comment by arkayenro** [comment]
i think it will be fixed in 30700 beta 4

**Comment by abackstrom** [comment]
Awesome, I'm happy to test b4 once it's available.

**Comment by arkayenro** [comment]
should be fixed, if it isnt let me know
