### ISSUE TITLE
Latest Beta, in funtion

### ISSUE THREAD

**Issue by gOOvER** [arkayenro/arkinventory#796]
I got this Error with latest BETA 3.07...

`2x ArkInventory\ArkInventory-3.06.17.lua:9582: attempt to call field 'GetPlayerCodex' (a nil value)
ArkInventory\ArkInventory-3.06.17.lua:9582: in function `LocationIsControlled'
ArkInventory\ArkInventory-3.06.17.lua:9012: in function `BlizzardAPIHook'
ArkInventory\ArkInventory-3.06.17.lua:2247: in function <ArkInventory\ArkInventory.lua:2240>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:482: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:993: in function <FrameXML\UIParent.lua:891>

Locals:
nil`

**Comment by gOOvER** [comment]
`4x ArkInventory\ArkInventoryStorage.lua:309: attempt to call field 'LocationStyleGet' (a nil value)
ArkInventory\ArkInventoryStorage.lua:309: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0-3.lua:120: in function <ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
nil`

**Comment by arkayenro** [comment]
2nd error fixed in beta2, not sure how the first error is happening yet

**Comment by gOOvER** [comment]
Not really fixed... Beta2

`256x ArkInventory\ArkInventoryStorage.lua:309: attempt to call field 'LocationStyleGet' (a nil value)
ArkInventory\ArkInventoryStorage.lua:309: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0-3.lua:120: in function <ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
nil`

**Comment by gOOvER** [comment]
with Version 3.06.xx it works without any in function.....

**Comment by arkayenro** [comment]
sorry about that, i added in the new line that would fix it but left the old in there so it still tried to run, will be fixed in the next release

**Comment by ctgarry** [comment]
good news.  I was going to report this one as well.  thank you for your addon.

**Comment by arkayenro** [comment]
i think the first error is fixed in 30700 beta 3, not sure though

**Comment by arkayenro** [comment]
if its not fixed let me know and ill re-open the ticket

**Comment by gOOvER** [comment]
Thanks for the fix.  I'll test it after weekend :)


Am 30. Juli 2016 09:27:05 schrieb arkayenro <notifications@github.com>:
