### ISSUE TITLE
[suggestion] buttons in no title mode

### ISSUE THREAD

**Issue by b3n9ti** [arkayenro/arkinventory#798]
no title mode is great, super clean. but it's so damn clean that one can't easily access edit mode or anything else. it would be great if one could choose which buttons to keep even though the title bar is hidden.

**Comment by arkayenro** [comment]
is there a button in the top right corner of the main window when the title bar is hidden?  i cant remember if i did that already (cant get in game so cant check at the moment)

**Comment by b3n9ti** [comment]
when the title is hidden the only button is visible is "clear" (also no right click option)

**Comment by arkayenro** [comment]
i'll see if i can add a menu like the guild bank has somewhere the title is hidden

**Comment by arkayenro** [comment]
will be in beta 3
