### ISSUE TITLE
Deposit reagents (v3.07.00 BETA 2)

### ISSUE THREAD

**Issue by ctgarry** [arkayenro/arkinventory#801]
Steps:
 - have rules and examples loaded or not (same result either way) 
 - have categories setup
 - /reload
 - wait for any translations to finish loading
 - open bank
 - wait for categories rules to be applied, reopen bank as needed until display is correct
 - right click reagent bank icon
 - on that click, as the drop down is drawn, a LUA error is popped:

_Message: Interface\AddOns\ArkInventory\ArkInventoryMenu.lua:1739: attempt to index field '?' (a nil value)
Time: 07/27/16 16:06:50
Count: 1
Stack: [C]: ?
Interface\AddOns\ArkInventory\ArkInventoryMenu.lua:1739: in function <Interface\AddOns\ArkInventory\ArkInventoryMenu.lua:1534>
...e\AddOns\ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua:1883: in function <...e\AddOns\ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua:1832>
...e\AddOns\ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua:2760: in function <...e\AddOns\ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua:2726>
...e\AddOns\ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua:2979: in function `Open'
Interface\AddOns\ArkInventory\ArkInventoryMenu.lua:1531: in function `MenuBagOpen'
Interface\AddOns\ArkInventory\ArkInventory.lua:8378: in function `Frame_Changer_Slot_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>_

**Comment by arkayenro** [comment]
fixed in 30700 beta 3
