### ISSUE TITLE
Void area on part of specific slots in each bar when bar titles are on

### ISSUE THREAD

**Issue by Azbec** [arkayenro/arkinventory#802]
I know I am going to do a horrible job of explaining this...

The top left slot in each bar except for bar 1 (Default) has a an issue with tool tip/recognizing there is an item there. If you divided the slot into quadrants the top left quadrant doesn't show a tool tip and does not interact. Even when the slot is empty I can put my pointer over slot and it highlights on 3 of the quadrants but it doesn't on the top left quadrant.

I have tried the following:
-Turned off item level
-Turned off stack number
-Toggled Frame Level under Workarounds

As I was typing this I thought to change the layout to the default and the issue went away. When I gave the bar a name the issue returned. When I disabled Name under Style under Bars the issue went away.

Thank you for an excellent addon. It is tied with Bartender as my favorite addon.

**Comment by joevt** [comment]
type /framestack

Move the the mouse over the four quadrants. Does the framestack show different frames?

**Comment by arkayenro** [comment]
its most likely the bar names overlapping the items somehow and blocking the mouse

**Comment by arkayenro** [comment]
"fixed" in 30700 beta 3
