### ISSUE TITLE
Gildbank revert into Default [1000] settings

### ISSUE THREAD

**Issue by esvarc** [arkayenro/arkinventory#806]
In latest beta build (3.07.00 BETA 3c). I have my profile set and I have two defined settings one for bank [1002] and another for guild bank [1003], default [1000] settings I did modify and using for bags.

In latest beta when I open GB it use [1000] style instead [1003] as I did set in "Config". I can open config and set it back to [1003] by selecting any other settings and then selecting back to [1002] in controll under guild bank tab. It reset to my layout and show bag changer (all other settings have bag changer hidden). In moment when I close GB and open it again it goes back to default [1000] and bag changer get hidden as well as rest of settings (number of items per row etc.) 

Bags using default [1000] and Bank using [1002]. [1001] is number for my "Sort Method".
In Profiles > 1st profiles tab I do have selected current profile [1001] Default.

When I did select predefined (may be migrated) [9999] * Default and set it from scratch. Guild Bank obey settings and don't revert to [1000] style and stay at my selected [1002] for GB. May be it is result of wrong edta migration? I did upgrade from latest release to latest beta 3c directly.

**Comment by arkayenro** [comment]
same underlying cause of #805

**Comment by arkayenro** [comment]
fixed in 30700 beta 4
