### ISSUE TITLE
Guild bank redraw (all items refresh)

### ISSUE THREAD

**Issue by esvarc** [arkayenro/arkinventory#807]
Now GB sorting is fixed. I still see that on removal/insert all items in guild bank tab getting redraw (probably refresh). I have rarity colored item border. And when I do insert/remove item in tab all items in tab getting redraw (+LAG spike happens) and all items does blink. When I do operate same way at bank/bags redraw doesn't happens until I press Refresh button.

It seems that GB still doing refresh on every time GB get changed. Probably is OK and it is necessary to redraw all just because you getting event. GB is shared space not only for single character but for bunch of characters (accounts) and need to be updated every time it changes probably.

Anyway it would be nice not to have it refreshed in graphical wise if there is no other change than actaully I did (from pov of current character).

**Comment by arkayenro** [comment]
its not refreshing for me, when i move an item out of the guild bank it leaves an empty slot

double check the control settings for which style you have set on the guild bank, then check the sort when on that style

**Comment by esvarc** [comment]
Ah you misunderstod my issue. It really doesn't do auto-sort. It is already fixed. When I remove item place stay empty. What I do means with redraw is that all items get visible redraw (some sort of refresh slot). I have seen it because I do have colored border by rarity and I see all items in GB get redraw on border (become grey and then get rarity colored border). All is tied with LAG spike until all items in bank tab get theirs redraw. Same visible effect not happens for bank, bags when I do removing or putting in item. Just GB do it all the time.

Problem with GB not obeing settings is really fixed it happens not anymore when I have "sort on open" it really sort only on open. BTW that redraw flash I don't know if it is related to event handling did happens before and it happens in latest beta as well. And it happens only for GB.

Similar flash happens when I press "Refresh" then you can see it on bank, GB and bags as well. I think this flash is produced by code 1st set border to gray then test item rarity and then border is redrawn again in proper color for item rarity.

**Comment by esvarc** [comment]
More than thousand words is one picture. So there is short video showing what I do mean.

https://youtu.be/bIsvBROUfVA

**Comment by arkayenro** [comment]
thats not normal and i think it might be due to the frame overlap, ie im not repainting all the borders, they dont shift back to grey and then get turned into the correct colour, they just get painted the colour.  i think the game is trying to sort out which frame should be on top of the other and flickering them.

can you increase the item padding size until they no longer overlap and see if it still does it?

**Comment by esvarc** [comment]
Interesting is I have same settings for every tab. Padding etc. GB has only one option different than rest. It is bag changer is not hidden. And of coarse every of them has different items per row, but I guess this should not have impact on it. I will set bigger padding and see what happens.

**Comment by esvarc** [comment]
So it is explained. You think you don't call update rarity for every GB item when new item is not put in bank, but you do. I did put this simple print at line 6868 in ArkInventory.lua

print("Frame_Item_Update_Border",loc_id) -- ES

when I remove item from bank and put it into bags, this function prints two lines

Frame_Item_Update_Border 1
Frame_Item_Update_Border 1

and then for every item in GB line with

Frame_Item_Update_Border 4

I repeat for every item in GB so in my case it prints 2 lines with loc_id 1 and around 100 with loc_id 4

So you does redraw rarity item border for each item in GB everytime when GB does change.

**Comment by arkayenro** [comment]
Frame_Item_Update_Border is called once per item - i didnt say i dont paint them (i have to do that), i said i dont paint them twice (first grey then the correct rarity colour) causing the flash

location 1 is the bag, location 4 is the vault, you get approx 100 because there are 98 slots.

if youre only getting approx 100 updates in location 4 then thats one per item, not two (one for grey and then one for the real colour) the code also shows that it only paints a single colour, it does after all work out what colour to paint it, and then paints it at the end via Frame_Border_Paint

**Comment by arkayenro** [comment]
the re-anchoring in Frame_Border_Paint might be a cause but its used in all locations so should happen to all of them., not just the guild bank

**Comment by esvarc** [comment]
I understand but for bank/bag is this function called only for item put in bags. But for GB it is called for every item not just for slot where item was before, and that producing that blink on GB in my video. As I did say that print function shows function is called just twice for bag when I put item from GB to bags, but at least 40 times for GB (every item get redrawn border) even when just removing item from GB.

**Comment by arkayenro** [comment]
ok, ive gone through and removed all the extra code where a refresh is set for the vault and it now only paints all items when you change tabs, you can check if that stops the flickering when beta 6 is released

**Comment by esvarc** [comment]
It is now fixed and GB now behave same way as other locations. Thank you. Did I say I can't live without ArkInventory after patch I did try couple of add-ons for bags and bank and no single of them did suit me. I'm user of ElvUI where is partially implemented bag/bank and GB but I had it enabled only once and I went back in next second into ArkInv.

**Comment by arkayenro** [comment]
must be graphics thing as it wasnt doing it on my machine, oh well, hasnt seemed to hurt anything so its all good
