### ISSUE TITLE
Add "Heirlooms" view

### ISSUE THREAD

**Issue by joevt** [arkayenro/arkinventory#809]
The other collections have their own views (Mounts, Pets, Toys). There should be a view for Heirlooms too. A user can then use rules to organize their heirlooms (upgrade level, equipment slot, appropriate). A rule for class may be problematic since items can be appropriate for multiple classes. You would want a method to disable a rule or category for a specific player while sharing all the other rules.

Bonus points if you can show un-obtained heirlooms and have a rule for that. Un-obtained pets and mounts and toys may be interesting too.

A view for "Appearances" could be implemented like the guild bank, with a tab for each equipment slot.

**Comment by arkayenro** [comment]
added in 30700 beta 7
