### ISSUE TITLE
Request for new feature

### ISSUE THREAD

**Issue by acemodder** [arkayenro/arkinventory#810]
Hi

I would love a button that moves all possible reagents into the reagent slots in the bank, currently it all has to be done manual, when you right click an item in your bag to put it into the bank, it puts it in a slot that is NOT the reagent bag, can we get an option to move them with one click?

**Comment by joevt** [comment]
The restack button of the guild bank is supposed to be able to move all items to the reagent bag. There might be a problem with it currently. I would have to double check.

It might be useful to be able to move only items that are already in the bank to the reagent bag, so it doesn't take anything out of my bags which I may want to mail to another character or use for quests or crafting.

Right-clicking the restack button changes it's options. Perhaps the options can include a setting for the default action (a radio button to select between "Restack moves all items to reagent bag", or "Restack moves only bank items to reagent bag"). Then clicking the restack button of the bank will perform the default action. The other action can be performed by right clicking the restack button and selecting an action, either "Restack and move all items to reagent bag", or "Restack and move only bank items to reagent bag".

**Comment by arkayenro** [comment]
the item action buttons are secure, i cannot tamper with their onclick code, only add onmouseup code

the bank/reagent bank are two separate places in the game, i just merged them for display purposes, when you open the bank you never actually open the reagent bank when using ai so when you click on an item the only place it can see to go is the normal bank

> I would love a button that moves all possible reagents into the reagent slots in the bank

if you right click on the restack button you can change its type from blizzard (their vclenaup function) or to arkinventory (my old restack code) you will then get options to top up stacks and to move crafting items to the bank/reagent bank when a restack is done.

the crafting items will go into bank profession bags first then the reagent bank (those could be swapped, cant remember at the moment), then the normal bank - depends which one has space

> There might be a problem with it currently. I would have to double check.

there isnt, its working fine

**Comment by acemodder** [comment]
oh, thats cool.  I didnt realise restack had a right click menu, this is perfect for what I wanted.   The feature is already there.
