### ISSUE TITLE
Guild Bank refresh

### ISSUE THREAD

**Issue by stonedune** [arkayenro/arkinventory#811]
I can't seem to figure out when I deposit or withdrawal from the guild bank it instantly resorts the remaining items. My bags and bank do not do this only my guild bank. I've checked every setting I can find and still no luck turning it off. I have the update timers set at .5 sec and on my "guild bank" layout the window sort method is set to "On Window Open"

What am I missing?

**Comment by arkayenro** [comment]
was fix in 30700 beta 4, do you have that version?

**Comment by stonedune** [comment]
In on the most recent "live" version. I'll check out the beta.
