### ISSUE TITLE
Functionality of SyLevel to ArkInventory

### ISSUE THREAD

**Issue by Akeruh** [arkayenro/arkinventory#812]
Hello, ArkInventory is by far the best bag addon for wow but I've been looking for this forever and I coulnd't find anyway to do it.

It would be awesome to be able to add over text info on bags like item lvl, BOE and BOP.

There was one project some years ago:
https://github.com/suicidalkatt/SyLevel_ArkInventory

The addon:
http://www.wowinterface.com/downloads/info22452-SyLevel.html#info

Image examples:

![pvw60979](https://cloud.githubusercontent.com/assets/20836163/17397485/f1bf0076-5a40-11e6-9314-24ba774f4f97.jpg)

![pvw24133](https://cloud.githubusercontent.com/assets/20836163/17397516/0c50c906-5a41-11e6-962d-9872c3f1c59d.jpg)

**Thank you very much for your time.**

**Comment by arkayenro** [comment]
item level is already in there under settings > style > items

the rarity coloured text is a neat alternative for not having rarity coloured borders (which i have so never needed to colour the text)

not sure i'd want bop/bop/boa on the items, i have system categories for that purpose so theyd end up on different bars

(i think i may have broken their code in a previous update as well but maybe they stopped after i added in the itemlevel display)
