### ISSUE TITLE
Item links to chat are Duplicating

### ISSUE THREAD

**Issue by bludgeons** [arkayenro/arkinventory#814]
Whenever I shift click an item to link it in a chat window the link is entered twice. Also Bnet friends login and logout messages appear twice in a row. Every addon was disabled and tested only with arkinventory. Problem still occurs. 

Im running 3.07.00 Beta 7 at the moment.

Also upon login the addon spams a bunch of random numbers in multiple lines in the chat box which are actually item numbers referencing to toys in my favorite list.
![wowscrnshot_080716_184817](https://cloud.githubusercontent.com/assets/20894201/17466183/916c3496-5ccf-11e6-9ea1-aad8d978eb52.jpg)

**Comment by arkayenro** [comment]
i'll remove the debug text next beta, will need to check the code for the doubled up itemlinks

ai cant impact bnet stuff though, nothing in the code touches it

**Comment by bludgeons** [comment]
ya not really sure on the notification duplication but the item link doubling only occurs when linking items from my bags. Linking items from atlas loot or off my character panel still works fine.

Thanks for the response been using this addon for years now.

**Comment by arkayenro** [comment]
found the doubled up chatlinks, will be fixed in 30700 beta 8
debug text is gone too

**Comment by arkayenro** [comment]
fixed in 30700 beta 8
