### ISSUE TITLE
LUA error on login, all data "lost" - new

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#815]
Hello,

Now with 30700 beta 7, the error in #813 is not present, but a new one (and config is still lost):

ArkInventory: Loading Connected Realm (EU) Data
ArkInventory: Rules: SellJunk Enabled

ArkInventory: Rules Enabled
[08:47:24] ArkInventory: Upgrading profile data for [Bloodscalp] to v3.023
[08:47:24] ArkInventory: WARNING> The sort order for each location has been reset to bag/slot as it couldnt be automatically transferred. You will need to create an equivalent sort method (via the config menu) to what you had and apply that to each location
[08:47:24] ArkInventory: WARNING> The border styles for each location have been reset to Blizzard Tooltip (default), the colour was able to be kept though
[08:47:24] ArkInventory: Upgrading profile data for [Bloodscalp] to v3.024

[08:47:28] ArkInventory: English (US) translations - attempt 1 of 5.
[08:47:32] ...terface\AddOns\ArkInventory\ArkInventoryUpgrades.lua:486: attempt to index field 'slot' (a nil value)
[08:47:32] ...terface\AddOns\ArkInventory\ArkInventoryUpgrades.lua:486: in function <...terface\AddOns\ArkInventory\ArkInventoryUpgrades.lua:118>
...terface\AddOns\ArkInventory\ArkInventoryUpgrades.lua:1274: in function `DatabaseUpgradePostLoad'
Interface\AddOns\ArkInventory\ArkInventory-3.07.00 BETA 7.lua:2256: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:2247>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: ?
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:414: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:995: in function <Interface\FrameXML\UIParent.lua:891>
[08:47:32] nil
[08:47:33] ArkInventory: English (US) translations - attempt 2 of 5.
[08:47:38] ArkInventory: English (US) translations - attempt 3 of 5.
[08:47:38] ArkInventory: English (US) translations successfully loaded.

**Comment by arkayenro** [comment]
can you email me your saved variable file for ai, i'll run it through the upgrade code until it comes out clean, that should get all the errors fixed in one go

**Comment by hollo6** [comment]
savedvariables files sent.

**Comment by arkayenro** [comment]
looks like that was the last error, all the files upgrade without errors in beta 8

**Comment by hollo6** [comment]
Indeed no errors now during upgrade, some rules (even default ones) were changed though. Seems weird that there are items I have never touched, yet changed default category now but not for all my characters. Would you please look into this? If so, what is the info I should send, printouts/savedvariables/list of items I've found?

**Comment by kballard** [comment]
Now I'm getting a similar error on launch, using version 3.07.01.

Chat frame output:

```
AddonLoader: Loading ArkInventory
ArkInventory: Loading Connected Realm (US) Data
ArkInventory: Upgrading profile data for [Faelyn - Burning Legion] to v3.026
AddonLoader: Loading ArkInventoryRules
ArkInventory: Rules Enabled
AddonLoader: Loading ArkInventoryRules_Example
ArkInventory: Successful rule registration from ArkInventoryRules_Example - rule function [example1] is now active
ArkInventory: Successful rule registration from ArkInventoryRules_Example - rule function [example2] is now active
```

And the bug itself:

```
ArkInventory\ArkInventoryUpgrades.lua:461: attempt to index field 'anchor' (a nil value)
ArkInventory\ArkInventoryUpgrades.lua:461: in function <ArkInventory\ArkInventoryUpgrades.lua:118>
ArkInventory\ArkInventoryUpgrades.lua:1276: in function `DatabaseUpgradePostLoad'
ArkInventory\ArkInventory-3.07.01.lua:2256: in function <ArkInventory\ArkInventory.lua:2247>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
AddonLoader\AddonLoader-r139.lua:160: in function `LoadAddOn'
AddonLoader\Conditions.lua:154: in function <AddonLoader\Conditions.lua:142>
AddonLoader\Conditions.lua:147: in function <AddonLoader\Conditions.lua:142>
AddonLoader\Conditions.lua:174: in function <AddonLoader\Conditions.lua:161>

Locals:
nil
```

**Comment by kballard** [comment]
(note: Faelyn is a character I haven't logged into for an extremely long time, probably on the order of a few years)

**Comment by ChiperSoft** [comment]
I'm getting one that's slightly different.

```
ArkInventory\ArkInventoryUpgrades.lua:461: attempt to index field '?' (a nil value)
Time: 08/09/16 19:54:25
Count: 1
Stack: \ArkInventory\ArkInventoryUpgrades.lua:461: in function <ArkInventory\ArkInventoryUpgrades.lua:118>
ArkInventory\ArkInventoryUpgrades.lua:1276: in function `DatabaseUpgradePostLoad'
ArkInventory\ArkInventory.lua:2256: in function <ArkInventory\ArkInventory.lua:2247>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:558: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:651: in function <...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:414: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:995: in function <Interface\FrameXML\UIParent.lua:891>

Locals: <none>
```

Chat output:
```
ArkInventory: WARNING> The border styles for each location have been reset to Blizzard Tooltip (default), the colour was able to be kept though
ArkInventory: WARNING> The sort order for each location has been reset to bag/slot as it couldnt be automatically transferred. You will need to create an equivalent sort method (via the config menu) to what you had and apply that to each location
ArkInventory: WARNING> The sort order for each location has been reset to bag/slot as it couldnt be automatically transferred. You will need to create an equivalent sort method (via the config menu) to what you had and apply that to each location
ArkInventory: Loading Connected Realm (US) Data
ArkInventory: Loading Connected Realm (US) Data
TVS
ArkInventory: Rules Enabled
ArkInventory: Upgrading profile data for [Default] to v3.023
ArkInventory: WARNING> The sort order for each location has been reset to bag/slot as it couldnt be automatically transferred. You will need to create an equivalent sort method (via the config menu) to what you had and apply that to each location
ArkInventory: WARNING> The border styles for each location have been reset to Blizzard Tooltip (default), the colour was able to be kept though
ArkInventory: Upgrading profile data for [Default] to v3.024
ArkInventory: Upgrading profile data for [Default] to v3.026
```

I was playing just yesterday. Updated from 3.06 to 3.07.1 today.

**Comment by ChiperSoft** [comment]
I've uploaded my SavedVariables file to https://www.dropbox.com/s/lbe0m3t1x377xmo/ArkInventory.lua?dl=0

**Comment by arkayenro** [comment]
thanks for the sv file, helped to figure out the issue

will be fixed in 30702

**Comment by hollo6** [comment]
Anything about my issue with item category changes? God forbid to look like I want to rush you, just wanted to know if it was something you wanted to address and/or needed any more info on.

**Comment by kballard** [comment]
3.07.02 fixed my issue. Thanks!

**Comment by hollo6** [comment]
With 3.07.02, upgrade, profile data recovery and category migration all seem totally fine! Thanks!
