### ISSUE TITLE
Categories not working sometimes

### ISSUE THREAD

**Issue by maven79** [arkayenro/arkinventory#817]
First - thanks for your work on the new version changes. By far the best inventory management in game and a really nice project. Your hard work is appreciated.

V30700, I have roughly a dozen bars with a mix of the default in-game categories, my own, custom rules, equipment sets etc. Most of the time since the new version, it just bunches up all my categorized items into the first bar and will not put things in their appropriate bar group. I try restacking, reloading, relogging on, recreating the categories, changing zones. After some tinkering or sometimes at random times (and often never) it may just start working - but its all or nothing. They all work or none of them do and I am unable to find a trigger that makes it work when it does.

I did reinstall and recreate my structure choosing not to "import" old settings and have been using 
arkinventory for years so am pretty familiar with how it works (for what that's worth).

Thanks again

**Comment by arkayenro** [comment]
check that new items isnt enabled, if it starts working after a period of time then its usually that

**Comment by maven79** [comment]
Fixed it. Thank you.
