### ISSUE TITLE
Unable to Copy "Category Sets" - bug

### ISSUE THREAD

**Issue by HallucinaDream** [arkayenro/arkinventory#818]
Hello,
Firstly thanks for your hard work in keeping this project alive! It's a wonderful tool.

I was attempting to reduce the sheer amount of profiles down to a few useable ones. To do this I wished to make a single Category Set and copy it from a current Category profile I have built up over many years. Unfortunately when I select the "Copy From" pull down list and click the already listed Category Set I wish to use I get the following error and nothing is copied;

Message: Interface\AddOns\ArkInventory\ArkInventoryConfig.lua:1085: attempt to index local 'v' (a nil value)
Time: 08/10/16 12:14:25
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventoryConfig.lua:1085: in function `ConfigInternalCategorysetCopy'
...ace\AddOns\ArkInventoryConfig\ArkInventoryConfig.lua:3364: in function <...ace\AddOns\ArkInventoryConfig\ArkInventoryConfig.lua:3362>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:799: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
....0-SharedMediaWidgets\Libs\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...ts\Libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua:442: in function <...ts\Libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua:433>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
....0-SharedMediaWidgets\Libs\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...s\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:353: in function <...s\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:343>

Locals: src = 1001
id = 1024
v = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'v' (a nil value)"

I have tried numerous things to fix this. One thing I also tried was to revert back to a pre-7.0.3 patch backup of my saved variables of "ArkInventory.lua". However, when I do this I still get the same error as above, but also it does not copy the Category Sets across correctly; there is no "Name" information at all for the bars, although all the bars and category contents are copied correctly.

Any help would be most appreciated, thanks :)

**Comment by arkayenro** [comment]
odd, i thought i fixed that issue before

will be fixed in 30702

**Comment by arkayenro** [comment]
fixed in 30702
