### ISSUE TITLE
attempt to call field 'GetPlayerCodex' (a nil value) - Bug

### ISSUE THREAD

**Issue by neidzwiedz** [arkayenro/arkinventory#819]
Good Morning,
Thank you for for the most useful addon i run!  This morning on log in i received the following error.

Date: 2016-08-10 08:00:02
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ArkInventory\ArkInventory.lua line 2212:
   attempt to call field 'GetPlayerCodex' (a nil value)
Debug:
   ArkInventory\ArkInventory.lua:2212:
      ArkInventory\ArkInventory.lua:2182
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...s\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:529: InitializeAddon()
   ...s\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:644:
      ...s\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:636
Locals:
None
AddOns:
  KalielsTracker, v2.0.2
  MoncaiCompare, v7.0.0
  Swatter, v7.0.5637 (TasmanianThylacine)
  AckisRecipeList, v7.0.3.5
  Altoholic, vr171
  Archy, v7.0.3.11
  ArkInventory, v30701
  BattlePetBreedID, vv1.6.0
  DataStore, vr59
  DataStoreCharacters, vr36
  PetTracker, v7.0.0
  TomTom, vv70000-1.0.0
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=155)

**Comment by arkayenro** [comment]
did you upgrade with the game still running?
