### ISSUE TITLE
attempt to index field 'PetJournal' (a nil value) - Bug

### ISSUE THREAD

**Issue by neidzwiedz** [arkayenro/arkinventory#820]
Also the following

Date: 2016-08-10 08:09:34
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\ArkInventory\ArkInventory.lua line 9032:
   attempt to index field 'PetJournal' (a nil value)
Debug:
   ArkInventory\ArkInventory.lua:9032: BlizzardAPIHook()
   ArkInventory\ArkInventory.lua:2254:
      ArkInventory\ArkInventory.lua:2247
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...s\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: EnableAddon()
   ...s\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:651:
      ...s\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:636
   [C]: ?
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:391: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:414: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:995:
      ..\FrameXML\UIParent.lua:891
Locals:
None
AddOns:
  KalielsTracker, v2.0.2
  MoncaiCompare, v7.0.0
  Swatter, v7.0.5637 (TasmanianThylacine)
  AckisRecipeList, v7.0.3.5
  Archy, v7.0.3.11
  ArkInventory, v30701
  ArkInventoryRules, v10003
  ArkInventoryRulesExample, v10000
  ArkInventoryRulesTSMGroup, v10701
  Bartender4, v4.7.2
  BattlePetBreedID, vv1.6.0
  CaerdonWardrobe, vv0.31.0
  CraftBuster, v1.0.31
  DailyGlobalCheck, v
  DailyGlobalCheckPetTamers, v
  DataStore, vr59
  DataStoreAchievements, vr42
  DataStoreAgenda, vr23
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr36
  DataStoreContainers, vr53
  DataStoreCrafts, vr73
  DataStoreCurrencies, vr31
  DataStoreGarrisons, vr16
  DataStoreInventory, vr46
  DataStoreMails, vr46
  DataStorePets, vr39
  DataStoreQuests, vr36
  DataStoreReputations, vr37
  DataStoreSpells, vr27
  DataStoreStats, vr26
  DataStoreTalents, vr54
  Decliner, v7.0.3.160719.1
  DestroyusPro, v0.1.3.1
  FishingBuddy, v1.7.2
  GoGoMount, v7.0.7
  MetaMap, v7.0.3.0
  MinimapButtonFrame, v3.1.10e
  MinimapButtonFrameSkinPack, v3.0.1b
  MobInfo2, v6.0.1 - beta 1
  Molinari, v70000.36-Release
  MountJournalEnhanced, v1.3.2
  OmniCC, v7.0.1
  Outfitter, v5.14.2
  Pawn, v2.0.7
  PetFarmer, v1.2.0.2
  PetJournalEnhanced, v2.9.18
  PetTracker, v7.0.0
  PetTrackerBreeds, v
  PetTrackerJournal, v
  PetTrackerSwitcher, v
  PetTrackerUpgrades, v
  PokemonTrainer, v7.0.1
  Postal, vv3.5.8
  Quartz, v3.3.0
  Rematch, v4.4.9
  sct, v7.00
  SexyMap, v2.4.29
  TinyDPS, v0.942
  Titan, v5.7.2.70000
  TitanBag, v5.7.2.70000
  TitanClock, v5.7.2.70000
  TitanGarrisonResources, v4.0.001
  TitanGold, v5.7.2.70000
  TitanItemCount, v70000-1.2.3
  TitanItemDed, v5.4.0.1
  TitanLocation, v5.7.2.70000
  TitanLootType, v5.7.2.70000
  TitanPerformance, v5.7.2.70000
  TitanRepair, v5.7.2.70000
  TitanReputations, v1.4
  TitanSpacer, v1.3
  TitanVolume, v5.7.2.70000
  TitanXP, v5.7.2.70000
  TomTom, vv70000-1.0.0
  ToyBoxEnhanced, v1.2.1
  TradeSkillInfo, vv2.3.11
  ZPerl, v5.0.5
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=83e)

**Comment by arkayenro** [comment]
that cant be missing unless youve somehow managed to completely disable the internal blizzard collections mod (the pets, mounts, toys, heirlooms and wardrobe) from loading
