### ISSUE TITLE
Character Level Rule Function

### ISSUE THREAD

**Issue by syserr0r** [arkayenro/arkinventory#824]
My implementation of character level function, `cl(minlevel, maxlevel)` (based on v3.07.02)
https://gist.github.com/syserr0r/578600dd0d452348b14947f63c07434b

I can now do something like:
```
equip() and cl(10,20) and ilvl(1,10)
or equip() and cl(21,30) and ilvl(1,20)
or equip() and cl(31,40) and ilvl(1,30)
or equip() and cl(41,50) and ilvl(1,40)
or equip() and cl(51,59) and ilvl(1,50)
or equip() and cl(60,64) and ilvl(1,80)
or equip() and cl(65,69) and ilvl(1,100)
or equip() and cl(70,74) and ilvl(1,130)
or equip() and cl(75,79) and ilvl(1,150)
or equip() and cl(80,82) and ilvl(1,270)
or equip() and cl(83,84) and ilvl(1,300)
or equip() and cl(85,87) and ilvl(1,360)
or equip() and cl(88,89) and ilvl(1,400)
or equip() and cl(90,95) and ilvl(1,480)
or equip() and cl(95,100) and ilvl(1,520)
```
Which allows me to categorize stuff that isn't apropriate for my item level.

It would be really nice if this could be merged into release so I don't have to keep modding my ArkInventoryRules.lua -- It's really just a copy of the `characterlevelrange` function.

Note: I originally submitted this as a comment for #734 but I realize this was a very old ticket so created this one.

**Comment by arkayenro** [comment]
you know the ArkInventory_RulesExample mod that doesnt do anything?  you can use it as a template for creating your own rule function that gets added in, that way you'll always have the rule function no matter what i do.

ps, if youre going to use a non-static value youll need to reset the item cache every time you level up, that or do a /reload at each one.

**Comment by syserr0r** [comment]
Thanks for the suggestion about breaking it out into a seperate addon, I didn't think it was an option.
Does something like this seem to cover what is needed:
https://gist.github.com/syserr0r/fe9bf01cc42eae2ce56cda86ed4e735a

**Comment by arkayenro** [comment]
try this

[ArkInventoryRules_syserr0r.zip](https://github.com/arkayenro/arkinventory/files/416346/ArkInventoryRules_syserr0r.zip)
