### ISSUE TITLE
ArkInventory_Tracking_Currency ldb icons and text - frame strata too high

### ISSUE THREAD

**Issue by charleslaine** [arkayenro/arkinventory#825]
I am using Bazooka Bar, and I have a floating bar that I turn on and off as needed.  In this floating bar, I have enabled the ArkInventory Tracking Currency plugin, with both the icon and title text enabled.

If I open a window, such as the ArKInventory bags window, or other floating moving windows, the text and icon of the Tracking Currency plugin will appear above the movable window.  Everything else in the bazooka bar draws correctly, behind and below other windows.  It's only this tracking currency ldb plugin that exhibits this glitch.  I didn't check any of the other ArkInventory LDB plugins, so they may have the same strata issue also.

**Comment by arkayenro** [comment]
the ldb plugin doesnt give me any control, i just tell it what text to display and it does the rest

**Comment by charleslaine** [comment]
thx for the reply. 

Do you then think that it would be Bazooka responsible for the z-ordering of these plugin text elements, or maybe it is in some underlying lib?  I'm just trying to figure out who would be the correct addon dev to pass on this info.

**Comment by arkayenro** [comment]
bazooka should be your first point of call, it sounds like its being the ldb display engine so it would be responsible for where things end up
