### ISSUE TITLE
Some items show as empty space

### ISSUE THREAD

**Issue by RevengencerAlf** [arkayenro/arkinventory#826]
No LUA error that I have seen so far but in the latest release, a chunk of items (seems like it was maybe 7 or 8) that I had in my bags showed and were categorized as empty spaces. No tooltip on hover but you could still click them to pick them up, right click to use, etc.   

It also reset all my characters' categories and layouts to 1000default for every bag type, regardless of what they were before. 

Note: Further testing below

**Comment by RevengencerAlf** [comment]
I upgraded back to the most recent version again so I could poke around.  got an error this time, which is extra weird because it all seems to be working ok now.

`Date: 2016-08-14 03:29:45
ID: 1
Error occured in: Global
Count: 1
Message: ...terface\AddOns\ArkInventory\ArkInventoryUpgrades.lua line 291:
   attempt to index field '?' (a nil value)
Debug:
   ...terface\AddOns\ArkInventory\ArkInventoryUpgrades.lua:291:
      ...terface\AddOns\ArkInventory\ArkInventoryUpgrades.lua:118
   ...terface\AddOns\ArkInventory\ArkInventoryUpgrades.lua:1306: DatabaseUpgradePostLoad()
   ArkInventory\ArkInventory.lua:2257:
      ArkInventory\ArkInventory.lua:2248
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   Ace3\AceAddon-3.0\AceAddon-3.0.lua:558: EnableAddon()
   Ace3\AceAddon-3.0\AceAddon-3.0.lua:651:
      Ace3\AceAddon-3.0\AceAddon-3.0.lua:636
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:391: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:414: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:995:
      ..\FrameXML\UIParent.lua:891
Locals:
None
AddOns:
  InspectFix, v4.5.1
  KalielsTracker, v2.0.3
  Swatter, v5.21f.5579 (SanctimoniousSwamprat)
  NPCScan, v7.0.3.7
  NPCScanOverlay, v7.0.3.4
  AccountantClassic, v2.07.06
  Ace3, v
  ActionBarSaver, v
  Altoholic, vr171
  AngryAssignments, vv1.7.1
  ArkInventory, v30703
  ArkInventoryRules, v10003
  AskMrRobot, v39
  Auctionator, v4.0.9
  BattlePetBreedID, vv1.6.0
  BigBrother, v4.2.1
  BodyGuardAway, v2.2
  BodyguardHealth, vv2.3.2
  CameraMaxFactor, v2.0
  CanIMogIt, v7.0.3.20
  Chinchilla, vv2.8
  ChocolateBar, vv2.4.7
  DataStore, vr59
  DataStoreAchievements, vr42
  DataStoreAgenda, vr23
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr36
  DataStoreContainers, vr53
  DataStoreCrafts, vr73
  DataStoreCurrencies, vr31
  DataStoreGarrisons, vr16
  DataStoreInventory, vr46
  DataStoreMails, vr46
  DataStorePets, vr39
  DataStoreQuests, vr36
  DataStoreReputations, vr37
  DataStoreSpells, vr27
  DataStoreStats, vr26
  DataStoreTalents, vr54
  DBMCore, v
  DBMDefaultSkin, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Details, v
  DetailsCalcLeech, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsDungeonInfoWarlords, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoBlackrockFoundry, v
  DetailsRaidInfoHellfireCitadel, v
  DetailsRaidInfoHighmaul, v
  DetailsRaidInfoSiegeOfOrgrimmar, v
  DetailsRaidInfoThroneOfThunder, v
  DetailsRaidPowerBars, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Elephant, v3.4.7
  ElkBuffBars, v2.5.0-188
  epgp, vv5.12.0
  epgplootmaster, v6.69
  epgplootmasterml, v6.69
  ExRT, v3740
  FlaskMinder, v6.2.1.001
  FuBar2Broker, vr88-release
  GTFO, v4.38.5
  GupPet, v7.0.3.05
  HandyNotes, vv1.4.8
  HandyNotesDraenorTreasures, v1.19c
  HandyNotesTimelessIsleChests, v1.14
  HandynotesTimelessTreasures, v1.0.2
  IceHUD, v1.10.4
  IskarAssist, v
  ItemRack, v
  LibDBIcon10, v
  LibDogTag30, v1.0
  LibDogTagUnit30, v1.0
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.146
  MoveAnything, v16.0.7
  NeedToKnow, v4.0.26
  Pawn, v2.0.7
  PitBull4, vv4.0.3
  PitBull4Aggro, vv4.0.3
  PitBull4AltPowerBar, vv4.0.3
  PitBull4Aura, vv4.0.3
  PitBull4Background, vv4.0.3
  PitBull4BattlePet, vv4.0.3
  PitBull4BlankSpace, vv4.0.3
  PitBull4Border, vv4.0.3
  PitBull4CastBar, vv4.0.3
  PitBull4CastBarLatency, vv4.0.3
  PitBull4CombatFader, vv4.0.3
  PitBull4CombatIcon, vv4.0.3
  PitBull4CombatText, vv4.0.3
  PitBull4ComboPoints, vv4.0.3
  PitBull4DogTagTexts, vv4.0.3
  PitBull4ExperienceBar, vv4.0.3
  PitBull4HealthBar, vv4.0.3
  PitBull4HideBlizzard, vv4.0.3
  PitBull4Highlight, vv4.0.3
  PitBull4HostilityFader, vv4.0.3
  PitBull4LeaderIcon, vv4.0.3
  PitBull4MasterLooterIcon, vv4.0.3
  PitBull4PhaseIcon, vv4.0.3
  PitBull4Portrait, vv4.0.3
  PitBull4PowerBar, vv4.0.3
  PitBull4PvPIcon, vv4.0.3
  PitBull4QuestIcon, vv4.0.3
  PitBull4RaidTargetIcon, vv4.0.3
  PitBull4RangeFader, vv4.0.3
  PitBull4ReadyCheckIcon, vv4.0.3
  PitBull4ReputationBar, vv4.0.3
  PitBull4RestIcon, vv4.0.3
  PitBull4RoleIcon, vv4.0.3
  PitBull4Sounds, vv4.0.3
  PitBull4ThreatBar, vv4.0.3
  PitBull4VisualHeal, vv4.0.3
  PitBull4VoiceIcon, vv4.0.3
  Poisoner, v6.1.1
  Postal, vv3.5.8
  PowerAuras, v4.29.2
  Quartz, v3.3.0
  RepairBroker, v7.0.0
  ServerHop, v2.0.1
  SilverDragon, vv3.2.5
  SlideBar, v5.21f.5579 (SanctimoniousSwamprat)
  Stubby, v5.21f.5579 (SanctimoniousSwamprat)
  TidyPlates, v6.18.Beta19
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TipTac, v16.07.23
  TipTacItemRef, v16.07.23
  TipTacTalents, v16.07.21
  TomTom, vv70000-1.1.0
  WeakAuras, v2.2.1.0
  WIM, v3.7.9
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=eb1)

`

**Comment by arkayenro** [comment]
if you click on the refresh icon do the items show up?

the error in the upgrade code will be fixed in 30704

**Comment by RevengencerAlf** [comment]
To answer the first bit, the refresh icon doesn't seem to do anything.   If I delete bag data for the character, it fixes, but only until I move something.  The instant the contents of the bag are changed, any addition, move, etc.  It's off again. 
The more I play with it the more it seems that it's just a frozen in time snapshot of the bag (I swapped 2 or 3 random items within the same category.  Their icons did not swap, but when I clicked on the icon, it "picked up" the new item I'd just placed there). 

Regarding the other bit, thanks.  That's not too bad at least once I figured out how to get the data back.  A few minutes of dropdown changes was better than having to rebuild all my settings. Hopefully the fix to the item placement issue doesn't involve completely wiping my settings.

**Comment by RevengencerAlf** [comment]
It looks like 30704 also fixed the "not updating" problem.   I'll continue testing on characters but they all seem to be working now.   Thanks for all your work on this addon. It's by far one of the most helpful and I can't imagine playing without it.
