### ISSUE TITLE
ArkInventoryUpgrades fails - cannot open bank or mail

### ISSUE THREAD

**Issue by taalas** [arkayenro/arkinventory#832]
Hi,

I haven't been able to open my bank or mail windows for a while now. ArkInventory seems to upgrade my profile everytime I start the game but files with the following:

3x ArkInventory\ArkInventoryUpgrades.lua:291: attempt to index field '?' (a nil value)
ArkInventory\ArkInventoryUpgrades.lua:291: in function <ArkInventory\ArkInventoryUpgrades.lua:118>
ArkInventory\ArkInventoryUpgrades.lua:1306: in function `DatabaseUpgradePostLoad'
ArkInventory\ArkInventory-3.07.03.lua:2257: in function <ArkInventory\ArkInventory.lua:2248>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: ?
[C]: ?
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:414: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:995: in function <FrameXML\UIParent.lua:891>

Locals:
nil

**Comment by arkayenro** [comment]
should be fixed in 30704

**Comment by taalas** [comment]
it is
