### ISSUE TITLE
LUA error on login

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#835]
Hi,

I'm having a LUA error on login with 3.07.04. I know it seems like it's Ember but I didn't do anything with Ember and this was not present with 3.07.03.

[18:00:50] Interface\AddOns\Ember\Ember-1.0.9.lua:543: in function `ThrottleEmberFunction'
Interface\AddOns\Ember\Ember-1.0.9.lua:575: in function `?'
Interface\AddOns\Ember\Ember-1.0.9.lua:616: in function <Interface\AddOns\Ember\Ember.lua:614>
[C]: in function `CloseBankFrame'
Interface\AddOns\ArkInventory\ArkInventory-3.07.04.lua:9206: in function `BlizzardAPIHook'
Interface\AddOns\ArkInventory\ArkInventory-3.07.04.lua:2259: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:2252>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0-12.lua:558: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0-12.lua:651: in function <...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:636>
[C]: ?
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:414: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:995: in function <Interface\FrameXML\UIParent.lua:891>
[18:00:50] self = Ember {
 0 = <userdata>
 FlyoutButtonOnEnter = <function> defined @Interface\AddOns\Ember\Ember.lua:202
 BankButtonOnClick = <function> defined @Interface\AddOns\Ember\Ember.lua:386
 BANKED = 4
 PLAYER_EQUIPMENT_CHANGED = <function> defined @Interface\AddOns\Ember\Ember.lua:606
 UpdateAllSetColors = <function> defined @Interface\AddOns\Ember\Ember.lua:337
 CreateBankButton = <function> defined @Interface\AddOns\Ember\Ember.lua:348
 ShowBorders = <function> defined @Interface\AddOns\Ember\Ember.lua:174
 freeSpace = <table> {
 }
 HowManyUnbankedSetsContainThisLocation = <function> defined @Interface\AddOns\Ember\Ember.lua:418
 PLAYER_REGEN_DISABLED = <function> defined @Interface\AddOns\Ember\Ember.lua:580
 slotName = <table> {
 }
 WORN = 1
 GetSetStatus = <function> defined @Interface\AddOns\Ember\Ember.lua:268
 DisplaySetTooltip = <function> defined @Interface\AddOns\Ember\Ember.lua:261
 ThrottleEmberFunction = <function> defined @Interface\AddOns\Ember\Ember.lua:541
 CreateInterceptor = <function> defined @Interface\AddOns\Ember\Ember.lua:482
 BAGGED = 3
 MISSING = 2
 PLAYER_LOGIN = <function> defined @Interface\AddOns\Ember\Ember.lua:549
 bagOrder = <table> {
 }
 BAG_UPDATE = <function> defined @Interface\AddOns\Ember\Ember.lua:610
 ItemsHaveMoved = <function> defined @Interface\AddOns\Ember\Ember.lua:594
 PaperDollEquipmentManagerPane_OnHide = <function> defined @Interface\AddOns\Ember\Ember.lua:332
 BANKFRAME_OPENED = <function> defined @Interface\AddOns\Ember\Ember.lua:563
 PLAYER_REGEN_ENABLED = <function> defined @Interface\AddOns\Ember\Ember.lua:585
 InitializeThrottle = <function> defined @Interface\AddOns\Ember\Ember.lua:523
 PushFromBagsToBank = <function> defined @Interface\AddOns\Ember\Ember.lua:445
 reusableSetTable = <table> {
 }
 ShowInterceptor = <function> defined @Interface\AddOns\Ember\Ember.lua:501
 SetTooltip = <function> defined @Interface\AddOns\Ember\Ember.lua:228
 FlyoutButtonOnClick = <function> defined @Interface\AddOns\Ember\Ember.lua:113
 PullFromBankToBags = <function> defined @Interface\AddOns\Ember\Ember.lua:397
 CreateFlyoutBorders = <function> defined @Interface\AddOns\Ember\Ember.lua:146
 BANKFRAME_CLOSED = <function> defined @Interface\AddOns\Ember\Ember.lua:571
 ConvertBankToPickup = <function> defined @Interface\AddOns\Ember\Ember.lua:55
 UpdateBankButton = <function> defined @Interface\AddOns\Ember\Ember.lua:365
 PaperDollEquipmentManagerPaneButtonXText_SetTextColor = <function> defined @Interface\AddOns\Ember\Ember.lua:292
 locationsToIgnore = <table> {
 }
 ScanFreeSpace = <function> defined @Interface\AddOns\Ember\Ember.lua:68
 NotEnoughSpace = <function> defined @Interface\AddOns\Ember\Ember.lua:63
 GetFreeSpace = <function> defined @Interface\AddOns\Ember\Ember.lua:91
 SetOverlayOpacity = <function> defined @Interface\AddOns\Ember\Ember.lua:218
 FlyoutButtonOnLeave = <function> defined @Interface\AddOns\Ember\Ember.lua:213
 PaperDollEquipmentManagerPane_OnShow = <function> defined @Interface\AddOns\Ember\Ember.lua:311
 reverseBagOrder = <table> {
 }
}
func = "SetOverlayOpacity"
arg = nil
(*temporary) = nil
(*temporary) = "nil"
(*temporary) = "attempt to index field 'throttleQueue' (a nil value)"
throttle = EmberThrottle {
 0 = <userdata>
 OnUpdate = <function> defined @Interface\AddOns\Ember\Ember.lua:529
 timer = 0
}
ember = Ember {
 0 = <userdata>
 FlyoutButtonOnEnter = <function> defined @Interface\AddOns\Ember\Ember.lua:202
 BankButtonOnClick = <function> defined @Interface\AddOns\Ember\Ember.lua:386
 BANKED = 4
 PLAYER_EQUIPMENT_CHANGED = <function> defined @Interface\AddOns\Ember\Ember.lua:606
 UpdateAllSetColors = <function> defined @Interface\AddOns\Ember\Ember.lua:337
 CreateBankButton = <function> defined @Interface\AddOns\Ember\Ember.lua:348
 ShowBorders = <function> defined @Interface\AddOns\Ember\Ember.lua:174
 freeSpace = <table> {
 }
 HowManyUnbankedSetsContainThisLocation = <function> defined @Interface\AddOns\Ember\Ember.lua:418
 PLAYER_REGEN_DISABLED = <function> defined @Interface\AddOns\Ember\Ember.lua:580
 slotName = <table> {
 }
 WORN = 1
 GetSetSt

**Comment by arkayenro** [comment]
ive changed the code to only close the bank if its open which will probably stop the error

**Comment by hollo6** [comment]
With 3.07.05, I get a different error:

[11:42:39] ArkInventory: English (US) translations - attempt 1 of 5.
[11:42:44] self = Ember {
 0 = <userdata>
 FlyoutButtonOnEnter = <function> defined @Interface\AddOns\Ember\Ember.lua:202
 BankButtonOnClick = <function> defined @Interface\AddOns\Ember\Ember.lua:386
 BANKED = 4
 PLAYER_EQUIPMENT_CHANGED = <function> defined @Interface\AddOns\Ember\Ember.lua:606
 UpdateAllSetColors = <function> defined @Interface\AddOns\Ember\Ember.lua:337
 CreateBankButton = <function> defined @Interface\AddOns\Ember\Ember.lua:348
 ShowBorders = <function> defined @Interface\AddOns\Ember\Ember.lua:174
 freeSpace = <table> {
 }
 HowManyUnbankedSetsContainThisLocation = <function> defined @Interface\AddOns\Ember\Ember.lua:418
 PLAYER_REGEN_DISABLED = <function> defined @Interface\AddOns\Ember\Ember.lua:580
 slotName = <table> {
 }
 WORN = 1
 GetSetStatus = <function> defined @Interface\AddOns\Ember\Ember.lua:268
 DisplaySetTooltip = <function> defined @Interface\AddOns\Ember\Ember.lua:261
 ThrottleEmberFunction = <function> defined @Interface\AddOns\Ember\Ember.lua:541
 CreateInterceptor = <function> defined @Interface\AddOns\Ember\Ember.lua:482
 BAGGED = 3
 MISSING = 2
 PLAYER_LOGIN = <function> defined @Interface\AddOns\Ember\Ember.lua:549
 bagOrder = <table> {
 }
 BAG_UPDATE = <function> defined @Interface\AddOns\Ember\Ember.lua:610
 ItemsHaveMoved = <function> defined @Interface\AddOns\Ember\Ember.lua:594
 PaperDollEquipmentManagerPane_OnHide = <function> defined @Interface\AddOns\Ember\Ember.lua:332
 BANKFRAME_OPENED = <function> defined @Interface\AddOns\Ember\Ember.lua:563
 PLAYER_REGEN_ENABLED = <function> defined @Interface\AddOns\Ember\Ember.lua:585
 InitializeThrottle = <function> defined @Interface\AddOns\Ember\Ember.lua:523
 PushFromBagsToBank = <function> defined @Interface\AddOns\Ember\Ember.lua:445
 reusableSetTable = <table> {
 }
 ShowInterceptor = <function> defined @Interface\AddOns\Ember\Ember.lua:501
 SetTooltip = <function> defined @Interface\AddOns\Ember\Ember.lua:228
 FlyoutButtonOnClick = <function> defined @Interface\AddOns\Ember\Ember.lua:113
 PullFromBankToBags = <function> defined @Interface\AddOns\Ember\Ember.lua:397
 CreateFlyoutBorders = <function> defined @Interface\AddOns\Ember\Ember.lua:146
 BANKFRAME_CLOSED = <function> defined @Interface\AddOns\Ember\Ember.lua:571
 ConvertBankToPickup = <function> defined @Interface\AddOns\Ember\Ember.lua:55
 UpdateBankButton = <function> defined @Interface\AddOns\Ember\Ember.lua:365
 PaperDollEquipmentManagerPaneButtonXText_SetTextColor = <function> defined @Interface\AddOns\Ember\Ember.lua:292
 locationsToIgnore = <table> {
 }
 ScanFreeSpace = <function> defined @Interface\AddOns\Ember\Ember.lua:68
 NotEnoughSpace = <function> defined @Interface\AddOns\Ember\Ember.lua:63
 GetFreeSpace = <function> defined @Interface\AddOns\Ember\Ember.lua:91
 SetOverlayOpacity = <function> defined @Interface\AddOns\Ember\Ember.lua:218
 FlyoutButtonOnLeave = <function> defined @Interface\AddOns\Ember\Ember.lua:213
 PaperDollEquipmentManagerPane_OnShow = <function> defined @Interface\AddOns\Ember\Ember.lua:311
 reverseBagOrder = <table> {
 }
}
func = "SetOverlayOpacity"
arg = nil
(*temporary) = nil
(*temporary) = "nil"
(*temporary) = "attempt to index field 'throttleQueue' (a nil value)"
throttle = EmberThrottle {
 0 = <userdata>
 OnUpdate = <function> defined @Interface\AddOns\Ember\Ember.lua:529
 timer = 0
}
ember = Ember {
 0 = <userdata>
 FlyoutButtonOnEnter = <function> defined @Interface\AddOns\Ember\Ember.lua:202
 BankButtonOnClick = <function> defined @Interface\AddOns\Ember\Ember.lua:386
 BANKED = 4
 PLAYER_EQUIPMENT_CHANGED = <function> defined @Interface\AddOns\Ember\Ember.lua:606
 UpdateAllSetColors = <function> defined @Interface\AddOns\Ember\Ember.lua:337
 CreateBankButton = <function> defined @Interface\AddOns\Ember\Ember.lua:348
 ShowBorders = <function> defined @Interface\AddOns\Ember\Ember.lua:174
 freeSpace = <table> {
 }
 HowManyUnbankedSetsContainThisLocation = <function> defined @Interface\AddOns\Ember\Ember.lua:418
 PLAYER_REGEN_DISABLED = <function> defined @Interface\AddOns\Ember\Ember.lua:580
 slotName = <table> {
 }
 WORN = 1
 GetSetSt
[11:42:44] ArkInventory: English (US) translations - attempt 2 of 5.

**Comment by arkayenro** [comment]
get the author of ember to fix it - they need to have their mod confirm they are actually at the bank before they do anything

**Comment by hollo6** [comment]
Done, Ember is fixed now, no more errors on login.
