### ISSUE TITLE
Enabling a rule for any bar applies it to all bars

### ISSUE THREAD

**Issue by auldis** [arkayenro/arkinventory#836]
Causing any matching items to end up in bar 1

I first noticed this about a week ago (hadn't tried to use rules before that) and am still seeing it in 3.07.05

I have reproduced it after clearing savedvariables with only ArkInventory, ArkInventory[Configuration], and ArkInventory[Rules] loaded.

**Comment by arkayenro** [comment]
is the rule enabled?
which bar did you assign the rule to?
in edit mode do the items show as being assigned to the rule?

**Comment by auldis** [comment]
> is the rule enabled?

Yep.  I am enabling the rule by turning on edit mode, opening the context menu for the bar by right clicking the bar number, navigating to Rule > [rule #] rule name, and clicking 'Enabled'

After I do this, every bar I right click shows that the rule is Enabled, with the option to disable it.  Selecting disable causes it to become disabled for all bars.

> which bar did you assign the rule to?

bar 2 in my original report, but I am seeing this behavior with all bars.

> in edit mode do the items show as being assigned to the rule?

Yep

**Comment by arkayenro** [comment]
rule management while in edit mode can be done from any bar, its meant to do that

ie you can enabled/disable a rule from any bar (because you may not remember where you put it)

the items will only go to the bar where you assigned the rule (which should be displayed on the end of the rule name in square brackets)

**Comment by auldis** [comment]
Thanks for that explanation--the missing piece for me was that clicking the rule itself in the rule menu is how you assign it to a bar.  I did not expect a menu option with a sub-menu to have an 'on click' effect that was anything other than opening the sub-menu.

It might be worthwhile to add an 'assign' menu option in the rule sub-menu to make this functionality more obvious.
