### ISSUE TITLE
Debug info showing soulbound on an item that isn't soulbound.

### ISSUE THREAD

**Issue by Archov** [arkayenro/arkinventory#841]
So, I don't know if this is a bug with Warcraft or with ArkInventory.

I'm using the [MoreRules](https://mods.curse.com/addons/wow/arkinventoryrules_morerules) addon (i know that's not made by you but my bug isn't with that addon).

I have a rule set up to check for Recipes that are Soulbound, but I've seen more than one Recipe get sent to that location but isn't  a soulbound item. When I expand the debug info for those items, it states Soulbound: Yes.

The item definitely isn't soulbound, I was able to mail it to my alts no problem. Here's a screenshot of one of the items I'm having the issue with.

[Item showing that it's not soulbound](https://i.imgur.com/6XWXFh6.png)
[Debug showing Soulbound: Yes](https://i.imgur.com/VFWQJZJ.png)

Again not sure if this is an issue with ArkInventory, MoreRules or Warcraft in general so any guidance would be appreciated.

**Comment by arkayenro** [comment]
it getting it from the item it creates that is soulbound.  i thought i had coded for that and there were plenty of them in wod.  blizzard may have changed something so ill have to go back and take a look at them again

**Comment by Archov** [comment]
I thought that might have been the case, though I did see other Recipes that returned soulbound: no that also created BoP items. Thanks for looking into it!

**Comment by arkayenro** [comment]
i havent been able to fully test it but the tooltip search for souldbound now only goes down to the first empty line which should stop if from picking up recipe items

should be fixed in 30706
