### ISSUE TITLE
Bar names indent downward when truncated

### ISSUE THREAD

**Issue by TheBaron87** [arkayenro/arkinventory#842]
Whenever the labels on my bars are too long to fully display, they indent downward.  The longer the name is, the farther it indents.  Even a single letter that results in "..." will push the label so far down it can't be read.
![arkinventorybug](https://cloud.githubusercontent.com/assets/21356809/18120757/fa8e21d4-6f15-11e6-9405-028804b84b46.jpg)

**Comment by arkayenro** [comment]
will be fixed in 30706
