### ISSUE TITLE
Artifact power usable items

### ISSUE THREAD

**Issue by amivit** [arkayenro/arkinventory#843]
Hey guys. Thanks for a beautifully powerful addon that I've used over the years. Glad to see you on GitHub now.

Is there any chance to implement a sorting rule for artifact power usable items? I managed to catch them in my "Soulbound" group, but this obviously brings in a lot of other clutter as well. If this isn't something I can "configure" my way to achieve, I would love to try coding the feature myself and submitting a pull request. Not too familiar with LUA though :)

**Comment by arkayenro** [comment]
id already noticed that the artifact power and relic items were categorised badly with their defauls and changed the code to move them to the system > artifact relic category to make it easier for people

**Comment by amivit** [comment]
Super cool, very fast response, cheers!

**Comment by amivit** [comment]
Btw I'm using 3.07.05, but don't see artifact power (consumable) and relic items (gem)

**Comment by arkayenro** [comment]
the artifact power items are consumables so get put under that category, the relics are gems, the next version will override that and place them into the artifact relic category

not sure why blizzard created that category and then didnt use it

**Comment by stonedune** [comment]
I setup a quick rule that reads the tooltip for "artifact" and "relic" and dropped them into their own slot.

**Comment by arkayenro** [comment]
"fixed" in 3.07.06

**Comment by phorcys** [comment]
Artifact power (consumables) filter is not woking under zh_CN locale because of translation problem.

fix:   append this line to locale/zhCN.lua

L["WOW_TOOLTIP_ARTIFACT_POWER"] = string.format( "%%d点%s", ARTIFACT_POWER )

tested working under version 3.07.09, zhCN wow 7.0.3.22642
