### ISSUE TITLE
Show item level on icon for Artifact Relics

### ISSUE THREAD

**Issue by jason-e** [arkayenro/arkinventory#850]
Artifact Relics are essentially a new type of gear so I think it should display the item level on the icon if that setting is enabled, however the addon does not do this because they don't have an associated equip location. This is easily fixed by modifying ArkInventory.Frame_Item_Update_Stock to check if the item's type is 3 (Gem) and subtype is 11 (Artifact Relic).

[Example code (edited ArkInventory.lua line 6723)](http://pastebin.com/sdTFqye2)

**Comment by arkayenro** [comment]
i can add that, just have to swap to internal constant values in case blizzard decide to renumber everything

**Comment by arkayenro** [comment]
added to 30707
