### ISSUE TITLE
Guild Bank - Layout

### ISSUE THREAD

**Issue by BaldwinEP** [arkayenro/arkinventory#851]
I know I am missing something here and I also know that in the past I was able to do this.  For the guild bank, I want the same style that I have for my bag and bank, but I want the layout to be the default guild layout (14x7).  That option is not available it seems.  If I switch the style to 9998 * Guild Bank while the style is 9998 * Guild Bank, it allows the proper grid layout, but not the option to style the window.  If I switch the Layout to 9998 * Guild Bank while the style is on 1000 Default, it does nothing.  

Leaving both style and layout at 9998 * Guild Bank does not give me an option to style the window.

**Comment by BaldwinEP** [comment]
I figured out a work around.  I created a new style/layout design and called it Guild Bank.  I copied my settings from default and removed all of the customization for categories, rules, and bars.  I then changed the sort method under style/window to Guild Bank.  This was a pretty long work around.

**Comment by arkayenro** [comment]
its pretty much what youd have to do, although you didnt have to clear out the layout data, you could have just used the system default layout [9999] for the  vault instead as it has nothing in it and you dont need anything for that type of vault layout

**Comment by BaldwinEP** [comment]
Yeah, I realized this mistake about removing everything.  Good thing I was still setting it up and not too far into the rules.  Thanks for answering.
