### ISSUE TITLE
Wrong item category

### ISSUE THREAD

**Issue by laric** [arkayenro/arkinventory#854]
The item here
http://www.wowhead.com/item=140515/gift-of-alakir

doesn't go into the correct catoegory (should have been artifact relic).  It gives this debug info.

![image](https://cloud.githubusercontent.com/assets/2378120/18338476/8b2481b4-7599-11e6-983d-9a8f6ba7bfcd.png)

**Comment by arkayenro** [comment]
blizzard classify it as junk.  feel free to just hard assign it to the "correct" category
