### ISSUE TITLE
Creeping Carpet is not a flying mount but listed in flying mounts

### ISSUE THREAD

**Issue by syserr0r** [arkayenro/arkinventory#858]
Creeping Carpet is not a flying mount but listed in flying mounts (and selected in zones with flying when I use my binding for summon mount)

Also, the chauffer mount should not get used after Journeyman Riding (100% ground speed) has been learnt as it will still only move at 70%.

**Comment by arkayenro** [comment]
carpet will be fixed in 30708

disable the chauffeur if you dont want it used

**Comment by syserr0r** [comment]
I've changed Creeping Carpet to a ground mount in the config, so that is sorted until 30708.

Is there any way to have the chauffer for low-level toons/alts without having it on higher level characters?

**Comment by arkayenro** [comment]
the mount options are per character so you can disable it for the higher level ones (via the menu, not the config)
