### ISSUE TITLE
autosell feature issue with changing category of item

### ISSUE THREAD

**Issue by isanusi123** [arkayenro/arkinventory#860]
Starlight Rosedust is (by default) a grey item, classed as miscellaneous - junk.   i reclassified the item as trade goods - herb but when i allow arkinventory to autosell junk, it still sells it off.  Autosell should recognize the assigned category, and not sell the item.

**Comment by arkayenro** [comment]
autosell was coded to be standalone, it doesnt look at anything except quality and vendor price

i'll see if it can access the category data for an item

**Comment by arkayenro** [comment]
fixed in 30708
