### ISSUE TITLE
Frame not rendering properly for single character

### ISSUE THREAD

**Issue by richardfein** [arkayenro/arkinventory#862]
Been noticing more and more ArkInventory errors while playing lately on this one particular character.  Today, I logged in and the frame renders like the screenshot below, for this character only.  Disabling all other addons did not fix.     Removing my entire WTF folder did not fix.  Not sure what else I can try deleting/cleaning. 
![wowscrnshot_092216_093757](https://cloud.githubusercontent.com/assets/10539411/18750481/430a57da-80a9-11e6-9c52-8183a4e66367.jpg)

**Comment by richardfein** [comment]
Deleting my WTF and Cache folders seemed to fix, but restoring WTF breaks again.  I'd obviously like some way to try and fix without losing all of my layouts and rules for all of my characters... thanks!

**Comment by Rhage1991** [comment]
Just updated, same issue.

**Comment by richardfein** [comment]
It seems like it resolves it self 30s-1m after logging in.  After upgrading to the latest version today I am getting the same errors as the other poster to this issue.

**Comment by Rhage1991** [comment]
unfortunately mine has not resolved itself, I have to disable the addon :/

**Comment by arkayenro** [comment]
disable everything, including elvui and try it with just ai loaded, see if it still does it
then load everything, except elvui, and see if it still happens

**Comment by Rhage1991** [comment]
All addons disabled other than ArkInventory, still the same issue

**Comment by arkayenro** [comment]
can you go into config > workaround and disable the in-combat yielding, then open the bag again, you should get a full error stack

**Comment by Rhage1991** [comment]
Sorry I stepped away for dinner, I did just come back and login, everything appears to be fixed now :) much appreciated! I did see if I could get an error stack still for you and I did not. Thanks for fixing it! I'll check back here for the next day or so to see if you'd like me to do anything else to prevent it from happening in the future for others.
