### ISSUE TITLE
Custom rules destroyed again as usual with each update

### ISSUE THREAD

**Issue by makedir** [arkayenro/arkinventory#864]
Custom rules like: type(0) and tt("ancient mana") not working anymore since last update.

Stop releasing broken after broken after broken after broken release. Beta test the damn sh*t at least. I told you before. You can't publish/add/change random stuff with each release and destroy or add 10 new bugs each time. Just that you release 10 times per release is sign again how careless you program.

I know at least 5 people who are so sick if this and want to switch to another bag addon.

**Comment by arkayenro** [comment]
so switch to another mod, i dont mind, its not like youre paying for a product, you get what you get

**Comment by makedir** [comment]
FIX THE DAMN BUG AND LEARN TO PROGRAM.
