### ISSUE TITLE
uncoded object class [achievement]

### ISSUE THREAD

**Issue by Yanngo** [arkayenro/arkinventory#866]
23:10:17 ArkInventory: ERROR> code failure: uncoded object class [achievement]
23:10:17 ArkInventory: ERROR> code failure: uncoded object class [achievement]
23:10:17 ArkInventory: ERROR> code failure: uncoded object class [achievement]
23:10:17 ArkInventory: ERROR> code failure: uncoded object class [achievement]
23:10:17 ArkInventory: ERROR> code failure: uncoded object class [achievement]
23:10:18 ArkInventory: ERROR> code failure: uncoded object class [achievement]
I was just mousing over some complex achievements like http://www.wowhead.com/achievement=7479/the-shado-master

**Comment by arkayenro** [comment]
it just shows the date i completed them for me when i mouse over those (if ive completed them), no error

can you try it with only ai running?  also do you have any achievement mods that could be creating a custom tooltip for them?

**Comment by Tetsemi** [comment]
Getting an error with the latest update

28x ArkInventory\ArkInventoryStorage.lua:3848: code failure: uncoded object class
[C]: ?
ArkInventory\ArkInventoryStorage.lua:3848: in function `ObjectIDCount'
ArkInventory\ArkInventoryTooltip.lua:775: in function `TooltipAddItemCount'
ArkInventory\ArkInventoryTooltip.lua:644: in function <ArkInventory\ArkInventoryTooltip.lua:584>
(tail call): ?
[C]: ?
[C]: in function `Outfitter_OrigSetHyperlink'
Outfitter\Outfitter-5.15.5.lua:7367: in function `SetHyperlink'
TipTac\core.lua:1133: in function <TipTac\core.lua:1129>

Locals:
(*temporary) = "code failure: uncoded object class"


I disabled both addons, completely exited the game, came back in and the mouse over error was gone, but the error came back if I click on the link for the achievement.

**Comment by arkayenro** [comment]
should be fixed next version

**Comment by Tetsemi** [comment]
Latest version has indeed fixed this issue, thank you!
