### ISSUE TITLE
No currency count information in tooltip

### ISSUE THREAD

**Issue by Yanngo** [arkayenro/arkinventory#867]
In tooltips I cannot see how much currency other characters of mine have. The information is stored indeed because I can open the currency frame of ArkInventory and see it for myself but I'd love to see it in tooltips too.
Version 3.07.09

**Comment by arkayenro** [comment]
that would be because i limited item counts to just item tooltips to stop a bug, i'll add currencies back into 30711

**Comment by arkayenro** [comment]
fixed in 30711
