### ISSUE TITLE
New release (nonbeta) and bug...

### ISSUE THREAD

**Issue by 40P3** [arkayenro/arkinventory#868]
I'm a bit frustrated because I update to all betas but I had no issues, now I update to release version and I receive a bug and data is missing. Please don't do this! I glad to test, glad to loose stuff during a beta but this was not a beta update according to you. :(

123x ArkInventory\ArkInventoryStorage.lua:3701: attempt to index field 'bonusids2' (a nil value)
ArkInventory\ArkInventoryStorage.lua:3701: in function `ObjectStringDecode'
ArkInventory\ArkInventoryStorage.lua:3845: in function `ObjectIDCount'
ArkInventory\ArkInventoryStorage.lua:4048: in function `ObjectCountGetRaw'
ArkInventory\ArkInventoryStorage.lua:4102: in function `ObjectCountGet'
ArkInventory\ArkInventoryTooltip.lua:833: in function `TooltipObjectCountGet'
ArkInventory\ArkInventoryTooltip.lua:786: in function `TooltipAddItemCount'
ArkInventory\ArkInventoryTooltip.lua:654: in function <ArkInventory\ArkInventoryTooltip.lua:584>
(tail call): ?
[C]: ?
[C]: in function `SetBagItem'
FrameXML\ContainerFrame.lua:1107: in function `ContainerFrameItemButton_OnEnter'
ArkInventory\ArkInventory-3.07.10.lua:7082: in function `Frame_Item_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
h = "|cffe6cc80|Hitem:128825:::132816:::::109:258:256:9::118::3:664:1591:1809:|h[T'uure, Beacon of the Naaru]|h|r"
i = nil
h = "|cffe6cc80|Hitem:128825:::132816:::::109:258:256:9::118::3:664:1591:1809:|h[T'uure, Beacon of the Naaru]|h|r"
s = "item:128825:::132816:::::109:258:256:9::118::3:664:1591:1809:"
v = <table> {
 1 = "item"
 2 = 128825
 3 = 0
 4 = 0
 5 = 132816
 6 = 0
 7 = 0
 8 = 0
 9 = 0
 10 = 109
 11 = 258
 12 = 256
 13 = 9
 14 = 0
 15 = 118
 16 = 0
 17 = 3
 18 = 664
 19 = 1591
 20 = 1809
 21 = 0
 bonusids3 = <table> {
 }
 enchantid = 0
 id = 128825
 class = "item"
 upgradeid = 256
 specid = 258
 h = "item:128825:::132816:::::109:258:256:9::118::3:664:1591:1809:"
 suffixid = 0
 sourceid = 9
 upgradelevel = 118
 gemid = <table> {
 }
 linklevel = 109
 uniqueid = 0
}
c = 21
pos = 17
(for index) = 18
(for limit) = 20
(for step) = 1
x = 18
(*temporary) = nil
(*temporary) = 664
(*temporary) = "attempt to index field 'bonusids2' (a nil value)"
string = <table> {
 split = <function> defined =[C]:-1
 match = <function> defined =[C]:-1
 gmatch = <function> defined =[C]:-1
 upper = <function> defined =[C]:-1
 gsub = <function> defined =[C]:-1
 format = <function> defined =[C]:-1
 utf8sub = <function> defined @HitsMode5\Libs\UTF8\utf8.lua:189
 lower = <function> defined =[C]:-1
 sub = <function> defined =[C]:-1
 gfind = <function> defined =[C]:-1
 len = <function> defined =[C]:-1
 rep = <function> defined =[C]:-1
 utf8len = <function> defined @HitsMode5\Libs\UTF8\utf8.lua:157
 char = <function> defined =[C]:-1
 rtgsub = <function> defined @FrameXML\RestrictedInfrastructure.lua:610
 join = <function> defined =[C]:-1
 reverse = <function> defined =[C]:-1
 byte = <function> defined =[C]:-1
 trim = <function> defined =[C]:-1
 utf8reverse = <function> defined @HitsMode5\Libs\UTF8\utf8.lua:296
 find = <function> defined =[C]:-1
}

**Comment by arkayenro** [comment]
if it doesnt break on my machine its a bit hard to find typos

**Comment by 40P3** [comment]
Hi,

Updated to the alpha r597
Prior this alpha the items didn't even show up in my warrior's bags, strangely. Guild bank and other char seemed unaffected. I hope my backup isn't damaged. :S
Logged in with my warrior, seems the same error as above but I copy paste again to be sure...:

780x ArkInventory\ArkInventoryStorage.lua:3701: attempt to index field 'bonusids2' (a nil value)
ArkInventory\ArkInventoryStorage.lua:3701: in function `ObjectStringDecode'
ArkInventory\ArkInventoryStorage.lua:3845: in function `ObjectIDCount'
ArkInventory\ArkInventoryStorage.lua:4048: in function `ObjectCountGetRaw'
ArkInventory\ArkInventoryStorage.lua:4102: in function `ObjectCountGet'
ArkInventory\ArkInventoryTooltip.lua:833: in function `TooltipObjectCountGet'
ArkInventory\ArkInventoryTooltip.lua:786: in function `TooltipAddItemCount'
ArkInventory\ArkInventoryTooltip.lua:654: in function <ArkInventory\ArkInventoryTooltip.lua:584>
(tail call): ?
[C]: ?
[C]: in function `SetBagItem'
FrameXML\ContainerFrame.lua:1107: in function `ContainerFrameItemButton_OnEnter'
ArkInventory\ArkInventory-3.07.10.lua:7082: in function `Frame_Item_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
h = "|cffe6cc80|Hitem:128825:::132816:::::109:258:256:9::118::3:664:1591:1809:|h[T'uure, Beacon of the Naaru]|h|r"
i = nil
h = "|cffe6cc80|Hitem:128825:::132816:::::109:258:256:9::118::3:664:1591:1809:|h[T'uure, Beacon of the Naaru]|h|r"
s = "item:128825:::132816:::::109:258:256:9::118::3:664:1591:1809:"
v = <table> {
 1 = "item"
 2 = 128825
 3 = 0
 4 = 0
 5 = 132816
 6 = 0
 7 = 0
 8 = 0
 9 = 0
 10 = 109
 11 = 258
 12 = 256
 13 = 9
 14 = 0
 15 = 118
 16 = 0
 17 = 3
 18 = 664
 19 = 1591
 20 = 1809
 21 = 0
 bonusids3 = <table> {
 }
 enchantid = 0
 id = 128825
 class = "item"
 upgradeid = 256
 specid = 258
 h = "item:128825:::132816:::::109:258:256:9::118::3:664:1591:1809:"
 suffixid = 0
 sourceid = 9
 upgradelevel = 118
 gemid = <table> {
 }
 linklevel = 109
 uniqueid = 0
}
c = 21
pos = 17
(for index) = 18
(for limit) = 20
(for step) = 1
x = 18
(*temporary) = nil
(*temporary) = 664
(*temporary) = "attempt to index field 'bonusids2' (a nil value)"
string = <table> {
 split = <function> defined =[C]:-1
 match = <function> defined =[C]:-1
 gmatch = <function> defined =[C]:-1
 upper = <function> defined =[C]:-1
 gsub = <function> defined =[C]:-1
 format = <function> defined =[C]:-1
 utf8sub = <function> defined @HitsMode5\Libs\UTF8\utf8.lua:189
 lower = <function> defined =[C]:-1
 sub = <function> defined =[C]:-1
 gfind = <function> defined =[C]:-1
 len = <function> defined =[C]:-1
 rep = <function> defined =[C]:-1
 utf8len = <function> defined @HitsMode5\Libs\UTF8\utf8.lua:157
 char = <function> defined =[C]:-1
 rtgsub = <function> defined @FrameXML\RestrictedInfrastructure.lua:610
 join = <function> defined =[C]:-1
 reverse = <function> defined =[C]:-1
 byte = <function> defined =[C]:-1
 trim = <function> defined =[C]:-1
 utf8reverse = <function> defined @HitsMode5\Libs\UTF8\utf8.lua:296
 find = <function> defined =[C]:-1
}

Hope this helps.

**Comment by 40P3** [comment]
Ouch,

On my priest nothing shows either, the bag placement is erronous too, same error as above.

Guess I revert to an earlier version and prob need to do a new config file.

**Comment by arkayenro** [comment]
config wont change, its just a code error. will be fixed in 30711

**Comment by arkayenro** [comment]
fixed in 30711

**Comment by 40P3** [comment]
Thanks!
