### ISSUE TITLE
Stock and Overstock to bank not working.

### ISSUE THREAD

**Issue by MusicBuddha** [arkayenro/arkinventory#870]
Hi,

As the title suggests Stock and Overstock to the bank are not working. I disabled all other addons and tried ark on it's own and the error is till present. Stock from vendors is working fine.

I have been having this problem for some time now (well before legion) but just assumed that because it was such a huge bug that it would be known about and fixed in time.

I hope you can help me fix this cause I love Arkinventory :).

Best Regards,

Lachlan MacColl

**Comment by arkayenro** [comment]
i found an issue with the restack function, which is what i think youre talking about, although it could be something else.

perhaps you could explain a bit more detail?

**Comment by MusicBuddha** [comment]
Hi,


I am sorry about this but I reported my issue to the wrong addon creator. I have a problem with Reagent Restocker not Arkinventory. Mane apologies for this mixup.


Best Regards,


Lachlan MacColl

On 25/09/2016 9:59 PM, arkayenro wrote:

i found an issue with the restack function, which is what i think youre talking about, although it could be something else.

perhaps you could explain a bit more detail?
