### ISSUE TITLE
Mythic Keystones cause errors (unhandled itemstring)

### ISSUE THREAD

**Issue by jason-e** [arkayenro/arkinventory#871]
Mythic Keystones seem to have a new kind of itemstring that the addon doesn't know how to handle.

The error: "ArkInventoryStorage.lua:3691: table index is nil"

This happens when I have a Mythic Keystone in my bags (specifically, a depleted level 8 one for Black Rook Hold)

Here's three example keystones and their itemstrings:

[Depleted Level 8 BRH](https://gyazo.com/4d0360f1aaba954e14474d47965876e9)
`item:138019::::::::110:260:1966080:::1501:8:7:2:::`

[Level 4 VotW](https://gyazo.com/0d02da75bb4e9c3d7bc1e924cfaa64e2)
`item:138019::::::::110:260:5111808:::1493:4:7:1:::`

[Level 2 CoS](https://gyazo.com/b29ebaf974fab76459f08dd75535a9da)
`item:138019::::::::110:260:4587520:::1571:2:1:::`

It looks like what would normally be the "numbonusids2" field is actually the keystone level, which leads to the above error (but only if the keystone is above level 5). Beyond that I'm not sure what each field specifies.

**Comment by arkayenro** [comment]
yeah, they dont match a normal itemstring at all.  will recode the function to handle them

**Comment by arkayenro** [comment]
working copy can handle all three itemstrings above so hopefully next release should be done with the itemstring stuff

**Comment by jason-e** [comment]
Awesome, thanks for the quick update

**Comment by arkayenro** [comment]
fixed in 30712
