### ISSUE TITLE
Item icons not showing properly

### ISSUE THREAD

**Issue by Wyndgem** [arkayenro/arkinventory#872]
For some reason the icons for some of the items in my inventory are showing up as different items and being sorted into a slot as if I had two of them.  ie. I have two Fu'zans, Two Shei'luns, two Legendary healing rings.  The tool tip when I hover over it tells me what the item really is.  Here's a screenshot with only AI enabled.  I checked the bags with AI disabled and everything looked fine.
![wowscrnshot_092516_154027](https://cloud.githubusercontent.com/assets/22434376/18818156/84755450-8337-11e6-8dfc-75f027733256.jpg)

**Comment by Wyndgem** [comment]
Update that may or may not be related.  I got this LUA when opening AMR on one of my rogues.

Date: 2016-09-25 18:56:15
ID: 1
Error occured in: Global
Count: 1
Message: ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua line 3691:
   table index is nil
Debug:
   ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:3691: ObjectStringDecode()
   ...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:644:
      ...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:584
   (tail call): ?
   [C]: ?
   [C]: Outfitter_OrigSetHyperlink()
   Outfitter\Outfitter.lua:7367: SetHyperlink()
   AskMrRobot\ui\Ui.lua:387:
      AskMrRobot\ui\Ui.lua:384
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[2]"]:9:
      [string "safecall Dispatcher[2]"]:5
   (tail call): ?
   ...face\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:314: Fire()
   AskMrRobot\ui\AmrUiLabel.lua:45:
      AskMrRobot\ui\AmrUiLabel.lua:44
Locals:
h = "[The Kingslayers]"
i = nil
h = "[The Kingslayers]"
s = "item:128870::132832:132850:::::104:259::::3:1545:1793:1809:4:1555:1741:1793:1809:"
v = <table> {
 1 = "item"
 2 = 128870
 3 = 0
 4 = 132832
 5 = 132850
 6 = 0
 7 = 0
 8 = 0
 9 = 0
 10 = 104
 11 = 259
 12 = 0
 13 = 0
 14 = 0
 15 = 3
 16 = 1545
 17 = 1793
 18 = 1809
 19 = 4
 20 = 1555
 21 = 1741
 22 = 1793
 23 = 1809
 24 = 0
 enchantid = 0
 id = 128870
 class = "item"
 upgradeid = 0
 specid = 259
 bonusids2 = <table> {
 }
 h = "item:128870::132832:132850:::::104:259::::3:1545:1793:1809:4:1555:1741:1793:1809:"
 suffixid = 0
 sourceid = 0
 upgradelevel = 3
 gemid = <table> {
 }
 linklevel = 104
 uniqueid = 0
}
c = 24
pos = 16
(for index) = 25
(for limit) = 1561
(for step) = 1
x = 25
(*temporary) = <table> {
 1793 = true
 1741 = true
 1809 = true
 4 = true
 0 = true
 1555 = true
}
(*temporary) = nil
(*temporary) = "table index is nil"
string = <table> {
 split = <function> defined =[C]:-1
 match = <function> defined =[C]:-1
 gmatch = <function> defined =[C]:-1
 upper = <function> defined =[C]:-1
 gsub = <function> defined =[C]:-1
 format = <function> defined =[C]:-1
 utf8sub = <function> defined @Interface\AddOns\Outfitter\utf8.lua:183
 lower = <function> defined =[C]:-1
 sub = <function> defined =[C]:-1
 len = <function> defined =[C]:-1
 utf8lower = <function> defined @Interface\AddOns\Outfitter\utf8.lua:276
 gfind = <function> defined =[C]:-1
 join = <function> defined =[C]:-1
 rep = <function> defined =[C]:-1
 utf8len = <function> defined @Interface\AddOns\Outfitter\utf8.lua:158
 char = <function> defined =[C]:-1
 rtgsub = <function> defined @Interface\FrameXML\RestrictedInfrastructure.lua:610
 utf8upper = <function> defined @Interface\AddOns\Outfitter\utf8.lua:266
 reverse = <function> defined =[C]:-1
 byte = <function> defined =[C]:-1
 trim = <function> defined =[C]:-1
 utf8reverse = <function> defined @Interface\AddOns\Outfitter\utf8.lua:286
 find = <function> defined =[C]:-1
}

AddOns:
  MoncaiCompare, v7.0.1
  Swatter, v7.0.1 (<%codename%>)
  Altoholic, vr171
  ArkInventory, v30711
  ArkInventoryRules, v10003
  ArkInventoryRulesExample, v10000
  AskMrRobot, v44
  AutoBar, v7.0.3.08
  autoturnin, v7.0.9
  BrokerClock, v1.0
  CanIMogIt, v7.0.3.23
  ChocolateBar, vv3.0.2
  Clique, vv70000-1.3.0
  DataStore, vr59
  DataStoreAchievements, vr42
  DataStoreAgenda, vr23
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr36
  DataStoreContainers, vr53
  DataStoreCrafts, vr73
  DataStoreCurrencies, vr31
  DataStoreGarrisons, vr16
  DataStoreInventory, vr46
  DataStoreMails, vr46
  DataStorePets, vr39
  DataStoreQuests, vr36
  DataStoreReputations, vr37
  DataStoreSpells, vr27
  DataStoreStats, vr26
  DataStoreTalents, vr54
  DBMCore, v
  DBMDefaultSkin, v
  DBMLDB, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  DejaCharacterStats, v7.0.3 r12
  ElvUI, v10.19
  ExRT, v3765
  GreenWall, v1.8.0
  HandyNotes, vv1.4.9
  HandyNotesLegionRaresTreasures, v1.01a
  HealBot, v7.0.3.0
  HealBotTips, v6.2.3.1
  LibPeriodicTable31, vv3.3.0.519
  LibSharedMedia30, v3.0-95
  MasterPlanA, vA
  MogIt, v3.6.5
  MogItSetTransmog, v1.5.0
  Outfitter, v5.15.5
  Paste, v1.4.9
  Pawn, v2.0.12
  Postal, vv3.5.8
  Stubby, v7.1.5675 (TasmanianThylacine)
  TomTom, vv70000-1.1.0
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=553)

**Comment by arkayenro** [comment]
the error above is fixed in 30713

**Comment by Wyndgem** [comment]
Just updated and looks like everything is working great!  Thanks!
