### ISSUE TITLE
Sort by equip location not working

### ISSUE THREAD

**Issue by wisnij** [arkayenro/arkinventory#875]
Using ArkInventory v3.07.13, I noticed that sorting by item location does not appear to be working, although other sorting methods seem to work as expected.  Looking at ArkInventory.lua, I believe that line 2668 in `ArkInventory.ItemSortKeyGenerate`:
```lua
if i.h and class == "item" and sorting.active.location then
```
should instead be
```lua
if i.h and info.class == "item" and sorting.active.location then
```

I tried making this change locally and running `ReloadUI()`, and afterwards location sorting worked again.

**Comment by arkayenro** [comment]
good catch, ill fix it in the next release

**Comment by arkayenro** [comment]
fixed in 30715
