### ISSUE TITLE
New Item category showing outfit gear on equipment swap

### ISSUE THREAD

**Issue by Leonolovich** [arkayenro/arkinventory#876]
I have an addon that automatically swaps my Equipment Set when I change Spec. Now, I have one of ArkInventory bars set up for System>New Items, and whenever I change specs, this Bar shows all the Equipment that is automatically un-equipped.

Is there a way to make it so the New Item category ignores my equipment gear sets? 

I was trying to set up a rule like this: `new() and not outfit()`

but new() doesn't seem to be an operator. Is there a way that I can make this work for me?

-Leo

**Comment by arkayenro** [comment]
technically its not a rule, its a logic check during the display part of the code, if you have it enabled and the item is under the time limit then it temporarily puts it into the new location.

it overrides everything, including rules.
