### ISSUE TITLE
Stack & Order not working in bank

### ISSUE THREAD

**Issue by Bachsau** [arkayenro/arkinventory#877]
When you bought that place for reagents and tell ArkInventory to stack and order items ("Stapeln und Umordnen" in german version) it generates several errors that some items can't be put in that bag and then hangs in the operation whenever an item is moved so you need to reload AI to get it back to normal. I've set it to use the build-in function instead of that from blizzard so it does move items to specific bags.

**Comment by arkayenro** [comment]
fixed in 30715
