### ISSUE TITLE
What replaces id() in rules

### ISSUE THREAD

**Issue by Amadeus-** [arkayenro/arkinventory#879]
I see that you removed id() from the rules system.   What do I use now to get the same functionality?   (I had thought that categorizing certain things by id would be more efficient than by name.)

**Comment by behub** [comment]
I assume you use the new 'itemstring' rule but currently in the latest build pushed to curse 'itemstring' is a not a valid function.

Using a test blank test rule:
```
ArkInventory: ERROR> Error validating rule <NEW>, invalid formula: [string "return( itemstring(1) )"]:1: attempt to call global 'itemstring' (a nil value)
```

**Comment by behub** [comment]
https://github.com/arkayenro/arkinventory/wiki/RuleFunction_ItemString

**Comment by arkayenro** [comment]
yes, itemstring() replaces it but i forgot to add it to the environment, thus the error. will be fixed next release

**Comment by jcai1** [comment]
For now it's possible to replicate the functionality of `id` by replacing calls to `id` with calls to an explicitly constructed closure, like so:

`id(1, 2, 3, 4)`

becomes

`(function(...) local function f(id, ...) return id and (i.osd.id == id or f(...)) end return f(...) end)(1, 2, 3, 4)`

I don't understand why `id` was removed, it's more convenient and less error-prone to write `id(1, 2, 3, 4)` than to write `itemstring("item:1:", "item:2:", "item:3:", "item:4:")`.

Another sidenote: as I was writing this, I noticed it would be nice to have at least `pairs` and `select` available inside the rule environment. Other library functions like `tostring`, `tonumber`, `type`, `unpack`, `table.*`, `string.*`, and `math.*` could also be helpful.

**Comment by arkayenro** [comment]
why would you do that for?  itemstring() will convert numbers to an item itemstring, ie i catered for those that really still want to use it.

all you have to do is change id to itemstring, thats it

**Comment by arkayenro** [comment]
fixed in 30715

**Comment by jcai1** [comment]
My bad, I didn't read the `itemstring` doc
