### ISSUE TITLE
Item Age still resetting

### ISSUE THREAD

**Issue by Drall15** [arkayenro/arkinventory#880]
Item Age still resets on all of my items every time I log in.  Can supply screenshots or debug info as needed.

**Comment by ThompsonDJ89** [comment]
Same here.

**Comment by rangerrambo** [comment]
Confirmed. Also resets with Item Swap. 

If it is of any relevance or how to circumvent this, Adi Bags sorted this issue New Items being marked new until user resets their status with a "Reset New items" button.

**Comment by Acrivec** [comment]
Wanted to report it now, but wow. Seems it won't be even fixed.

**Comment by arkayenro** [comment]
> Seems it won't be even fixed.

it relies on the game, plus you can always right click on the refresh icon and reset all new items
