### ISSUE TITLE
Error with Lure Master Tackle Box

### ISSUE THREAD

**Issue by subparpleasure** [arkayenro/arkinventory#881]
WARNING> bag [5] in location 1 [Bag] type is unknown, queuing for rescan

I get this message any time something changes or gets dropped into my inventory. It is referring to the bag "Lure Master Tackle Box". I disabled all other addons, and I still get the error. If I change out the Tackle Box bag for something else, it goes away. Arkinventory seems to have a problem with this fishing bag. Is there anything I can do to fix this, or should I just wait for the next Arkinventory update? Thanks

**Comment by arkayenro** [comment]
fixed in 30718

**Comment by subparpleasure** [comment]
thank you
