### ISSUE TITLE
Sort by ID

### ISSUE THREAD

**Issue by gen4ik** [arkayenro/arkinventory#882]
Sorting by ID use "string" method.
Now it sorting like this:
91
8234
54
10000
etc.

**Comment by gen4ik** [comment]
And one more question.
How make rule to cut all items with ID less then some number?

**Comment by arkayenro** [comment]
should be fixed next release

its always been like that but ive zero padded the id part now so it should sort "numerically" even though its still a string (and so long as ids have 10 or less digits)

**Comment by arkayenro** [comment]
> How make rule to cut all items with ID less then some number?

osd.id < 20304

should work i think

**Comment by arkayenro** [comment]
fixed in 30716

**Comment by gen4ik** [comment]
> osd.id < 20304
not worked
`Error validating rule 104, invalid formula: [string "return(osd<124124 )"]:1: attempt to index global 'osd'(a nil value)`
