### ISSUE TITLE
Rule accountbound() not working with german client

### ISSUE THREAD

**Issue by rkuenzel** [arkayenro/arkinventory#883]
The rule `accountbound()` does not work with a german client.

Reason for this is that the two localized tooltip strings which mark the item as accountbound are: 

* `ITEM_BIND_TO_BNETACCOUNT = 'Wird an den Battle.net-Account gebunden'`
* `ITEM_BNETACCOUNTBOUND = 'Battle.net-Accountgebunden'`

Both strings contain a period `.` as well as a hyphen `-` which lead to `string.find()` returning `nil` in `ArkInventory.TooltipFind()`. The strings should be quoted before using them (would be a good idea for all localized strings which are used as regular expressions :-))

A test run with adapted strings:

* `ITEM_BIND_TO_BNETACCOUNT = 'Wird an den Battle%.net%-Account gebunden'`
* `ITEM_BNETACCOUNTBOUND = 'Battle%.net%-Accountgebunden'`

worked fine with my client.

**Comment by arkayenro** [comment]
should be fixed next release

**Comment by arkayenro** [comment]
fixed in 30716
