### ISSUE TITLE
tooltip("<Right Click to Open>") does not match any item that can create another item

### ISSUE THREAD

**Issue by Fraktyl** [arkayenro/arkinventory#889]
Would love to have just one rule to grab every chest/box/random treasure that has the green text <Right Click to Open>.

Instead we have to add each and every box to either a custom sort or to a rule and add by name. 

The help page for tooltip even lists "right click to open" as a valid rule but the code never matches.

Thanks

**Comment by arkayenro** [comment]
i may have picked a bad example to use on the help page.

go into config mode and mouseover an openable item to check what the tooltip says - as thats the generic tooltip used when scanning, so if it doesnt contain "right click to open" in it then it wont be found by a rule

**Comment by arkayenro** [comment]
fixed in 3.07.23
