### ISSUE TITLE
Artifact item level on icon too high, counts relic bonuses twice

### ISSUE THREAD

**Issue by jason-e** [arkayenro/arkinventory#890]
863 shows as 976 on icon
881 shows as 1012  on icon
885 shows as 1020  on icon

I'm guessing the addon adds the relic bonuses to the reported item level, but now the game automatically reports the true item level since 7.1

**Comment by arkayenro** [comment]
no, my code just double checks the item level value in the tooltip when set using the hyperlink.

ie every other item (that is upgradable or has bonus ids) is reporting the base item level as its ilvl and the tooltip has the actual ilvl in it.

its just seems to be broken for artifacts, and only blizzard can break the tooltip.

**Comment by arkayenro** [comment]
actually it might be down to GetItemInfo() returning a slightly different hyperlink than what was passed in as using the original hyperlink doesnt seem to have the level increase issue

**Comment by arkayenro** [comment]
will change the code to use the original hyperlink for the moment and see if blizzard get around to fixing it later

**Comment by arkayenro** [comment]
fixed in 30717
