### ISSUE TITLE
Guild Bank Log and Money Log fonts are 2 pt and unreadable

### ISSUE THREAD

**Issue by Tetsemi** [arkayenro/arkinventory#891]
When I logged in after updating the game and addons today, I did my weekly check of the guild bank money transactions and the log file font is barely big enough to see that the data is there but it's not readable due to the font size.

I couldn't find a setting in the UI for ArkInventory to change the font or the font size for Guild Bank Log or Guild Bank Money Log.

**Comment by arkayenro** [comment]
theres no setting as its supposed to use the same default font size across everything

if it was working last week then something in the patch must have changed it

**Comment by Tetsemi** [comment]
Here is a screen shot showing the issue 

![image](https://cloud.githubusercontent.com/assets/6722073/19709761/e5de9360-9add-11e6-8d77-b29d49217326.png)

**Comment by arkayenro** [comment]
found the issue, will be fixed next release

**Comment by Tetsemi** [comment]
Okay, and just FYI for completeness, here's how it looked before, finally found a screen shot

![image](https://cloud.githubusercontent.com/assets/6722073/19709890/03a70430-9adf-11e6-9d04-ee425b8f5259.png)

**Comment by arkayenro** [comment]
fixed in 301718
