### ISSUE TITLE
ArkInventory crashing game on specific character

### ISSUE THREAD

**Issue by Gamemaker945** [arkayenro/arkinventory#893]
I can load all of my characters except my Druid. It is crashing on him everytime. I have narrowed it down to Ark as the culprit. Anything I can do to reset him and get him rolling?

**Comment by arkayenro** [comment]
log into a different character, open the bag window, click on the change character icon, mouse over the druid, wait for the slide out menu to open, click on erase all data

then login to the druid and see if that fixes it.

**Comment by Gamemaker945** [comment]
Thank you for reaching out. It appears it was a WoW issue. There was an item in my inventory that, when touched or moused over, crashed the game. I did a scan/fix of the game and that cleared it up.
Thanks again.
