### ISSUE TITLE
SubZone and Zone changes causes lag spike?

### ISSUE THREAD

**Issue by JustJinxed** [arkayenro/arkinventory#894]
So I had to isolate which mod was causing the issue, and it came down to only having ArkInventory loaded. But every time the screen notification that I'm changing zone, comes up on the screen, there's a sizable and noticeable fps drop and cpu spike. 

Thinking it might be the rules module, I disabled it temporarily, same issue. Seems it might be in the core? I'm working in a completely new and clean install, no savedvars to speak of when I started. 

## Version: 30717 
(lib version)

**Comment by arkayenro** [comment]
it looks like the mounts are scanned after each zone change, which was fine when there werent so many mounts, but now there are and its making an impact.

i dont think its needed to scan them every time so i'll probably remove it for the moment and see if there are any issues with it

**Comment by arkayenro** [comment]
fixed in 301718
