### ISSUE TITLE
Cross Realm and Guild Bank

### ISSUE THREAD

**Issue by dangedup** [arkayenro/arkinventory#895]
I'm not sure if I missed something with the set-up, but this is my issue.  I have two toons in the same guild.  The guild master is on realm 1 while the other one is on a connected cross-realm.  Under the GM toon it shows what items are in the guild bank; however, under the non GM toon it does not show items in the guild bank.

Am I doing something wrong.  Thanks!

**Comment by arkayenro** [comment]
does the non gm character have view access to the tabs?

are you actually opening the vault with the non-gm toon, just looking at it offline, or looking at an item count on the tooltip?

**Comment by dangedup** [comment]
The non gm character does have access to view the guild bank and i'm looking at the items from the non gm character's bags.

the thing that is odd is that it shows items that are in another guild that i have.

**Comment by arkayenro** [comment]
shows where?  is the issue that the vault is empty when opened or that the tooltips arent including vault item counts for it?

can you screenshot it?

**Comment by dangedup** [comment]
okay... what i did was a clean install of arkinventory and it seemed to have fixed the problem.  items are showing (when you mouse over them) properly now.

thank you for your assistance.
