### ISSUE TITLE
Issue with tsm group not matching subgroup

### ISSUE THREAD

**Issue by MuffinManKen** [arkayenro/arkinventory#898]
I have a bunch of groups with a hierachy like "Profession->Expansion->bad" where bad has stuff I want to be able to track, but not actively buy. I was hoping to set a Rule to put those all together. I'd hoped tsmgroup( "bad" ) would match them, but it doesn't. I have to put the entire hierarchical name to match, but there are a lot of them so it'd pretty tedious to set up.

Am I doing something wrong, or is this not supported?

**Comment by arkayenro** [comment]
if "Profession->Expansion->bad" isnt matching the sub groups (it should) you can use the wildcard character (*) so "Profession->Expansion->bad->*"

**Comment by MuffinManKen** [comment]
Sorry, I wasn't clear enough. I have a bunch of groups like:
Tailoring->BurningCrusade->bad
Tailoring->Cataclysm->bad
Tailoring->LichKing->bad
and many more.

I'd like to match all of the "bad" groups with a single rule rather than typing out 20 of them. I'd hoped tsmgroup ( "bad" ) would match them, but it appears to not do so.

**Comment by arkayenro** [comment]
i'll add a new rule function to allow for pattern matching the tsm group name

**Comment by MuffinManKen** [comment]
Thank you!

**Comment by MuffinManKen** [comment]
I just tried the latest version, and switching to the tsm() rule is working fine. Thanks!
