### ISSUE TITLE
Queue for BG's blocked

### ISSUE THREAD

**Issue by jeffv2011** [arkayenro/arkinventory#903]
Sometimes I cannot queue for PvP-Random Battleground. I can queue for anything else except for this. Below is the Bug grabber info.

Ps: Kinda curious why my bags are messing with my group finder...totally unrelated.

Date: 2016-11-25 02:01:48
ID: 1
Error occured in: AddOn: ArkInventory
Count: 1
Message: Error: AddOn ArkInventory attempted to call a forbidden function (JoinBattlefield()) from a tainted execution path.
Debug:
   [C]: JoinBattlefield()
   Blizzard_PVPUI\Blizzard_PVPUI.lua:551: HonorFrame_Queue()
   [string "*:OnClick"]:2:
      [string "*:OnClick"]:1
Locals:
None
AddOns:
  Swatter, v7.1.5675 (TasmanianThylacine)
  ACP, v3.4.30 
  AdvancedInterfaceOptions, v1.0.6
  ArkInventory, v30719
  ArkInventoryRules, v10003
  ArkInventoryRulesExample, v10000
  ArkInventoryRulesGFM, v10200
  ArkInventoryRulesMoreRules, v7.0.3.1.8.1
  ArkInventoryRulesTSMGroup, v10701
  ArkInventoryRulesTSMValue, v10200
  ArkInventoryRulesWardrobe, v10000
  AskMrRobot, v48
  Auctionator, v4.0.16
  BattlegroundTargets, v70000-1
  BigDebuffs, vv5.2
  BonusRollPreview, v70100.35-Release
  DailyGlobalCheck, v
  DBMCore, v
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Details, v
  DetailsChartViewer, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTrialOfValor, v
  DetailsTimeAttack, v
  DetailsTimeLine, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  DugisGuideViewerZ, v4.046
  ElvUI, v10.31
  ElvUICustomTweaks, v1.31
  ElvUISLE, v3.16
  GSCore, v152
  GSDraikMacros, vv1.5.1 Legion 7.1
  GSmyMacros, vv1
  GSSequenceEditor, v1.52
  GTFO, v4.41.3
  HealersHaveToDie, v2.4.3
  IceHUD, v1.10.12
  MasterPlanA, vA
  MogIt, v3.6.5
  MogItHighlighter, vv1.3.2
  MogItSetTransmog, v1.5.0
  NOP, v06.22 15.11.2016
  OmniCC, v7.1.0
  Outfitter, v5.17.2
  Pawn, v2.1.8
  PersonalLootHelper, v1.16
  Postal, vv3.5.8
  RotationBuilder, v1.61.0
  SlideBar, v7.1.5675 (TasmanianThylacine)
  Spy, v3.3.8
  StarCursor, vr1
  StealthAlerter, v0.99.25
  Stubby, v7.1.5675 (TasmanianThylacine)
  SuperGuildInvite, v7.6.0
  TradeSkillMaster, vv3.6.20
  TradeSkillMasterAppHelper, vv3.0.2
  TradeSkillMasterCrafting, vv3.1.18
  WeakAuras, v2.2.2.2-3-g957d372
  WeakAurasOptions, v2.2.2.2-3-g957d372
  WeakAurasStopMotion, v1.0.0
  WorldQuestGroupFinder, v0.19.1
  WorldQuestsList, v23
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v7.1.0.70100 <none>
  (ck=774)

**Comment by arkayenro** [comment]
youll need to enable taint logging and check the output as AI does not touch any PVP/Group functions at all.  its most likely one of the libraries i use which is also used by whatever is causing the taint.  the game will lay blame on the first mod (alphabetically) that loads the library
