### ISSUE TITLE
No Bags

### ISSUE THREAD

**Issue by Christina1331** [arkayenro/arkinventory#905]
When I open the guild bank there are no bank tabs, only the one that initially opens. I have turned off every other addon and still nothing. This is only happening on my laptop and not my desktop.  thanks

**Comment by arkayenro** [comment]
login with the same toon
dont access the vault
open your bags
click on the change location icon
select the vault - do you see all the tabs now?
if not try erasing all the vault data for that guild and then access the vault to see if it updates
