### ISSUE TITLE
outfit() fails on respec because itemLink specialisationId changes

### ISSUE THREAD

**Issue by cameronpm** [arkayenro/arkinventory#907]
Issues manifest themselves when respeccing.

I changed ArkInventoryRules.System.outfit_blizzard to do the following and issues went away.

Old code:
> if h == ArkInventoryRules.Object.h then

New code:

> local h1 = gsub(h, "(item:%d+:[^:]\*:[^:]\*:[^:]\*:[^:]\*:[^:]\*:[^:]\*:[^:]\*:[^:]\*:)[^:]\*", "%1")
> local h2 = gsub(ArkInventoryRules.Object.h, "(item:%d+:[^:]\*:[^:]\*:[^:]\*:[^:]\*:[^:]\*:[^:]\*:[^:]\*:[^:]\*:)[^:]\*", "%1")
> 
> if h1 == h2 then

Pic of specialisationId changing for an item, showing the item being compared and the cached item with the old specialisationId.

![arkinventory_outfit_bug](https://cloud.githubusercontent.com/assets/1286356/21522587/f9e1f5c8-cd5a-11e6-93b5-e349b7ed53fa.png)

http://wow.gamepedia.com/API_GetInspectSpecialization - you can see the specId going from Feral (103) to Guardian (104).

[e] corrected mistake, it is specialisationId, not upgradeId

**Comment by arkayenro** [comment]
next version will use the location of the item from the equipment manager api instead of the hyperlink, should be safer than the ever changing hyperlink

**Comment by arkayenro** [comment]
fixed in 30720
