### ISSUE TITLE
Bank rules issue

### ISSUE THREAD

**Issue by Boatshoes24** [arkayenro/arkinventory#908]
So I'm not getting a lua error, but my rules have broken specifically in my bank. I am able to fix the rules for my bags if the bank is closed and I open the rules and click accept again, however they break again as soon as I open my bank. I'll paste an example of the rules and the chat error I'm getting. This is only an issue since the most recent update. Was working fine before. 

Rule examples that are broken on the bank:

1) ilvl(835,950) and sb() and not outfit() and type("armor","weapon") 
2) outfit("Tank") and not q(6)

These are the chat errors I'm receiving:

ArkInventory: WARNING> ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:897: Usage: GetContainerItemID(index, slot)
ArkInventory: WARNING> Rule 1004 is now flagged as damaged and will no longer be used until repaired
ArkInventory: WARNING> ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:897: Usage: GetContainerItemID(index, slot)
ArkInventory: WARNING> Rule 1006 is now flagged as damaged and will no longer be used until repaired
ArkInventory: WARNING> ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:897: Usage: GetContainerItemID(index, slot)
ArkInventory: WARNING> Rule 1005 is now flagged as damaged and will no longer be used until repaired
ArkInventory: WARNING> ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:897: Usage: GetContainerItemID(index, slot)
ArkInventory: WARNING> Rule 1015 is now flagged as damaged and will no longer be used until repaired
ArkInventory: WARNING> ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:897: Usage: GetContainerItemID(index, slot)
ArkInventory: WARNING> Rule 1007 is now flagged as damaged and will no longer be used until repaired
ArkInventory: WARNING> ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:897: Usage: GetContainerItemID(index, slot)
ArkInventory: WARNING> Rule 1003 is now flagged as damaged and will no longer be used until repaired
ArkInventory: WARNING> ...rface\AddOns\ArkInventoryRules\ArkInventoryRules.lua:897: Usage: GetContainerItemID(index, slot)
ArkInventory: WARNING> Rule 1004 is now flagged as damaged and will no longer be used until repaired

**Comment by flatluigi** [comment]
It appears to specifically be the outfit() function that causes this issue.

**Comment by hollo6** [comment]
Yes it is the outfit() function. I have the same problem when I open the bank and there is any item from any equipment set in the bank. The immediate cause is that the first argument of GetContainerItemID becomes nil but I haven't had the time yet to figure out why.
If there are multiple items of an equipment set in the bank, the first couple of them (5-6) can be read correctly, but if I leave only 1 item, it gets the problem no matter which item is it. Maybe it's a problem of the last one in the list.

**Comment by KalleDK** [comment]
Same problem here - also in the bank.

**Comment by AletheianAlex** [comment]
Same issue here, and same error: 

ArkInventoryRules.lua:897 Usage:GetContainerItemID(index, slot)

The rules effected all take this format:

outfit( "<outfit name>" ).  i.e. outfit( "Ranged DPS" ), etc

it breaks when I visit the bank always, and it occasionally breaks when opening my character bags

**Comment by arkayenro** [comment]
fixed in 3.07.21
