### ISSUE TITLE
Rule xx is now flagged as damaged and will no longer be used until repaired

### ISSUE THREAD

**Issue by traceofwind** [arkayenro/arkinventory#909]
Hi,

**Version: 3.07.20**

This warning started appearing today, another user is also reporting on the Curse page in the comments section. The rules effected are all related to Outfits. Examples:

_`outfit("Tank")`
`outfit("TW") or name("Bladeshadow Wristguards")`_

The following warnings are output to my chat window:

**`WARNING>ArkInventoryRules.lua:897: Usage: GetCpntainerItemIS(index,slot)`
`WARNING>Rule 44 is now flagged as damaged and will no longer be used until repaired`**

I hope this can help you find and fix the bug.

Cheers

**Comment by arkayenro** [comment]
duplicate with #908 

fixed in 3.07.21
