### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Talimar** [arkayenro/arkinventory#911]
Not sure if Ark has any or all blame here, there's several addons mentioned in the error message.
The error began when I was on the quest "The Keys to Success" and received the metal in Dalaran. I have now finished the quest but the error keeps popping up on reload.

3x GatherMate2\Display-Display.lua:348: table index is nil
GatherMate2\Display-Display.lua:348: in function `DigsitesChanged'
GatherMate2\Display-Display.lua:251: in function <GatherMate2\Display.lua:220>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0-12.lua:558: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0-12.lua:571: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0-12.lua:651: in function <...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
ArkInventory\ArkInventory-30722.lua:9168: in function `LoadAddOn'
ArkInventory\ArkInventory-30722.lua:9179: in function `BlizzardAPIHook'
ArkInventory\ArkInventory-30722.lua:2272: in function <ArkInventory\ArkInventory.lua:2265>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0-12.lua:558: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0-12.lua:651: in function <...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:407: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:430: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:1012: in function <FrameXML\UIParent.lua:907>

Locals:
nil

http://i.imgur.com/qnqdiuC.jpg

**Comment by arkayenro** [comment]
looks like a possible issue with gathermate.  arkinventory is mentioned because its typically the first mod (alphabetically) to load the ace3 libraries that a lot of mods share so when something breaks it blames whichever mod loaded the ace3 libraries first

**Comment by Talimar** [comment]
Ok that makes sense thanks
