### ISSUE TITLE
Bug with Rules Enforcing

### ISSUE THREAD

**Issue by AdilHindistan** [arkayenro/arkinventory#912]
I see a problem with rule enforcement. Addon seems to work most of the time, but sometimes it just does not pick up the rule correctly, especially if it included 'ilvl'.
Rule #1 Order #10: equip("Head")
Rule #2 Order # 6: type("armor") and ilvl(800, 849)

Each is assigned to a different slot. Problem is that I have 2 Head pieces, one with ilvl 865, other 835, and they are both in head slot, Instead, the Rainfinder version should be fit into Rule #2 as it has higher order number. 

Any ideas why?
![wowscrnshot_012117_141012](https://cloud.githubusercontent.com/assets/1984488/22176976/743a5942-dfe3-11e6-9af1-5b209877e595.jpg)

**Comment by arkayenro** [comment]
probably because they share the same internal rule id

the bonus ids that give the extra ilvls arent included in the internal id so it cant see any difference.  so the first item it finds that matches a rule, lumps all of them into that rule

at some point i have to change that

**Comment by arkayenro** [comment]
should be fixed in 3.07.23
