### ISSUE TITLE
[SUGGESTION] Show Stacks of Items as One

### ISSUE THREAD

**Issue by Imiona** [arkayenro/arkinventory#914]
Hello

I just would like to throw a Suggestion in here, specificly, could you add an Option to Show Stacks of Items as one? What i mean is, if i have say, 10 Stacks of Flasks, it will show them as one (200) and hide the Stacks (Adi Bags has that feature and its really nice).

Thx for considering :)

**Comment by arkayenro** [comment]
gets asked for a lot but i cant do it due to the way i originally coded it.

closest youll get is the 'only show X number of stacks of an item' option (which is close but not quite what want you want)

**Comment by Imiona** [comment]
Ah, i see, thx anyway :)
