### ISSUE TITLE
ArkInventory refuses to work on 1 of my characters

### ISSUE THREAD

**Issue by ishirra** [arkayenro/arkinventory#916]
I use different profiles on all my characters. No problem with any of them, only my bankalt doesn't seem to load ArkInventory.
I have disabled all addons (only Bugsack was loaded so I could grab the errors) and my bankalt is the only one giving these errors (uploaded the file with 11 errors)
I tried erasing data, I tried deleting saved variables, it didn't work.

**Comment by ishirra** [comment]
Not sure if the file was attached, I can't see it anywhere...  I can always mail it.

**Comment by arkayenro** [comment]
youll need to mail it, ill need the errors to work out whats gone wrong

**Comment by ishirra** [comment]
Mailed the errors to you

**Comment by arkayenro** [comment]
it looks like somehow youre missing libstub.  for ai its under libs\arkdewdrop\libstub.lua

check which addons load for that toon compared to your other ones, maybe you have it installed standalone but not enabled for that toon?

**Comment by ishirra** [comment]
Libstub.lua is installed in the Arkdewdrop folder.
I did a search and noticed a lot of my addons are using libstub, and it's all included in their folder.  Guess I have to enable these addons, hoping I will find the one that stops the errors for my bankalt.

**Comment by arkayenro** [comment]
maybe try it with just ai enabled and see if it works, one of the other mods may have a corrupt libstub file

**Comment by ishirra** [comment]
Those errors are happening with only AI enabled.  The only other addon I had enabled was bugsack, so I could grab the errors.
AI isn't showing in the Interface - Addon menu either..

**Comment by arkayenro** [comment]
from what you sent ai isnt loading because libstub isnt loading, basically the errors kill ai completely

can you delete the ai folders from wow (with wow closed) and re-download/install it to see if that helps?

**Comment by ishirra** [comment]
Just did it, and this time I manually installed AI.
The errors are gone so far (will try with more addons enabled in a little while)
Since I reinstalled AI for about 7 times in the past days, I'm guessing updating/installing via the Curse app, corrupted the file in some way.

**Comment by ishirra** [comment]
With all addons enabled (the ones that I use for this character) still error free.
Am guessing the Curse app corrupted the file in some way.  Will manually update/install from now on.

Thanks a lot for the help!

**Comment by arkayenro** [comment]
its possible.  ive had other users report weird stuff after a curse update but typically doing it again fixes it.  shouldnt need 7 goes at it though

the hard part for me is that i have the source code and dont install ai via the curse client to test it so i never see that sort of corruption

**Comment by ishirra** [comment]
Well, so far this problem has been fixed, so I can continue using this wonderful addon.
Thanks for your time!
