### ISSUE TITLE
Rules are backwards?

### ISSUE THREAD

**Issue by Chris1389** [arkayenro/arkinventory#917]
Hey, I was trying to do something simple with the Rules system. I made a Rule:

outfit("Prot") 

For one of my outfit sets. Applying the Rule to the bar, it removes anything to do with the Prot set. When I change the Rule to:

not outfit("Prot")

It keeps only the Prot outfit. I might be misunderstanding the Rules and its working as intended? Im not sure.

**Comment by arkayenro** [comment]
are you sure youve assigned the rule to that bar?  it shows up under assigned > rules for that bar?

just that it sounds like its moving it to the default bar once you enable the rule, which is where rules go when you dont assign them to a bar

**Comment by Chris1389** [comment]
Hm, It seems that It's not going under the Assigned tab. It seems to be applying to the layout, overall.

**Comment by Chris1389** [comment]
I think I may have gotten it, It seems that there is an extra step that I was missing.

**Comment by arkayenro** [comment]
you enabled the rule but didnt actually click on it to assign it to a bar?

**Comment by Chris1389** [comment]
Ding!

**Comment by arkayenro** [comment]
i think need to find a way to make that step more obvious

**Comment by arkayenro** [comment]
i might move the assign code to the enable/disable menu that should make it obvious what you have to do

**Comment by Chris1389** [comment]
I'd have to agree. It makes sense once you know what you have to do. But it's a little confusing when just starting out.

**Comment by arkayenro** [comment]
it made sense with the old way rules used to get enabled (via the rule window where they were created) but the new format needs a bit more help

**Comment by arkayenro** [comment]
should be an easy fix anyway so will be in the next version

**Comment by Chris1389** [comment]
Awesome. Glad to see the active improving of this mod. That is why it's my essential bag mod.

**Comment by arkayenro** [comment]
"fixed" in 3.07.29
