### ISSUE TITLE
Feature Request - Rules saved to profiles

### ISSUE THREAD

**Issue by Jarhead101st** [arkayenro/arkinventory#920]
Firstly love the addon. I've used it for years. 

Would it be possible to allow rules enabled / disabled to be saved in a profile?

I have several rules that I use to separate BOEs into armor type to be sent to the right disenchanter. I only want to use them occasionally. I figured I would save a profile "Disenchanting" which would have all those rules enabled and a second "Default" profile with all those rules disabled. 

But it seems that rules are global rather than being able to be saved to individual profiles. Unless i'm doing things wrong. I wasn't able to get it to work as I wanted.

**Comment by arkayenro** [comment]
rules are global, enabling/disabling them isnt, thats part of the layout "profile"

create two profiles, with different layouts, then swap between them as needed

**Comment by Jarhead101st** [comment]
"edit: updated because even i have a hard time remembering where im storing bits of data"

oh man i thought i was going crazy. I read you initial response and left entirely confused with the intent to work it out some other time but with the knowledge i was doing it wrong. even though from what you said I was doing exactly that.

spent some time playing around with it tonight and got it working. came back to correct your initial response. found the edited response and thought to myself "damn you must have been tired last time you were here because this is totally different from what you remember". then saw the edit :)

yeah once i figured out category sets existed I got it all working. thanks once again for a great addon.
