### ISSUE TITLE
Rule issue with "outfit"

### ISSUE THREAD

**Issue by q3fuba** [arkayenro/arkinventory#921]
Hi there,
i use this Rule
```
outfit() and (not q(5, 6))
```
But all trinkets with the same name already used in an outfit that are **NOT** in any outfit are also asigned to this bar/group.

Why?
The Tooltip show the right?!

I dont use any outfit addon just the ingame Equipment Manager.

here are some screenshots:
https://drive.google.com/open?id=0BwDAoCkQ9Wz2Zl9fd2JkMVdtWm8

**Comment by arkayenro** [comment]
the in-game equipment manager should return bag/slot data, which is then compared to the items bag/slot and if it matches then its added to the equipment set return, it cant match on name.

the internal itemstring format should stop all the variants of the items being seen as the same item

so im not sure why it thinks its in an equipment set

can you go into edit mode and click on the two variants of that trinket and see what the itemstrings are?

**Comment by q3fuba** [comment]
Trinket2:
```
Three-Toed Rabbit Foot
Item Level 845
item:134203::::::::110:105::42:4:3474:605:1507:1674:::
```
Trinket2:
```
Three-Toed Rabbit Foot
Item Level 855
item:134203::::::::110:105::42:4:3474:607:1517:3336:::
```

screens of the debug view - ItemString1.png and ItemString2.png:
https://drive.google.com/open?id=0BwDAoCkQ9Wz2Zl9fd2JkMVdtWm8

**Comment by arkayenro** [comment]
are you sure its not part of another equipment set?

can you update the rule to include the set name to see if it still picks it up

**Comment by arkayenro** [comment]
i had a look a the code for the in-game equipment manager matching and its possible theres a logic error in it that might be causing the issue so im re-arranging it to see if that will help

**Comment by q3fuba** [comment]
> are you sure its not part of another equipment set?

yep im sure and you can see it at the screenshots

> can you update the rule to include the set name to see if it still picks it up

updated the rule to just my "Guardian" Equip Set and both Trinkets are still in the bar.
Seems this happens with all items with the same name.

Overall its not that bad because the error just happens on equip with the same Name.
But it's still an error so i reported it :)

**Comment by arkayenro** [comment]
try 3.07.24 and see if its fixed or not

**Comment by q3fuba** [comment]
`try 3.07.24 and see if its fixed or not`

yep seem fixed now.

Thanks! ;)
