### ISSUE TITLE
Keystones incorrect icon

### ISSUE THREAD

**Issue by ashkashlitwin** [arkayenro/arkinventory#923]
![image](https://cloud.githubusercontent.com/assets/19734305/24437130/44686624-13f4-11e7-8164-b70226b61eaa.png)

Is this something you need to fix, or do we fix locally?

**Comment by arkayenro** [comment]
are you using 3.07.25?

i dont have a keystone to check so im not sure if the changes i made fix the issue or not

**Comment by ashkashlitwin** [comment]
Yes, I am. I don't get the error spam that I used to, so thanks for that fix, but I still have the incorrect icon.

**Comment by arkayenro** [comment]
ok, as soon as i get a keystone ill see if i can fix it

**Comment by arkayenro** [comment]
if anyone has a keystone could they go into edit mode > debug and copy/paste the itemstring value to here

**Comment by joevt** [comment]
Here's one for Eye of Azshara Mythic Level 2
keystone:197:2:1:0:0:0

**Comment by ashkashlitwin** [comment]
Keystone: Darkheart Thicket (+2)
keystone:198:2:1:0:0:0

**Comment by arkayenro** [comment]
was fixed in 3.07.26
