### ISSUE TITLE
Problem logging out of the game

### ISSUE THREAD

**Issue by Thraxer** [arkayenro/arkinventory#933]
Hi,

I've had the same problem for a few weeks now that I haven't been able to pinpoint exactly but which seems to be caused by ArkInventory.
I tried with only this addon active to be sure, fresh WTF/Cache folders, and even though it works for a time the same thing always happens : 
It takes an abnormaly long time to log out (when changing character for example) and after a few days it just won't leave me disconnect/leave the game, wow just hangs and I get the "this program is not responding" window (all I can do is closing via task manager). And the funny thing is, when I restart the game, I'm back with the default ArkInventory configuration (default font and bag settings at least).
As this addon is otherwise great I've become kinda addicted to it so, if you have an idea or if there's a way to provide you with more information, let me know I'll gladly help.
As I said, great work anyway, thanks and good luck :)

PS : I'm using release version 3.07.26

**Comment by arkayenro** [comment]
find the arkinventory.lua file under the savedvariables folder and rename it to something else (dont delete it), then see what happens

saving the savedvariable data is a game thing, theres no api code for it so the game might be having an issue saving to that location (possible corruption?).

obviously the more data you have the longer it will take to save it but ive got 10+ toons with full banks/bags and dont have any issues logging out/in (just my personal data point but its all i have to go on)

**Comment by Gildan71** [comment]
I had the same problem with increasing logout times and wow stopped responding. For me, it was Avast's Gaming Mode that caused the problem. 

In Avast: Go to settings, components and scroll down. Turn of gaming mode, restart of your computer might be required. After this my logout problems was gone.

**Comment by Thraxer** [comment]
Hello and thanks for your advices. I've deleted the arkinventory.lua and disabled Avast game mode and everything's been fine for a few weeks now.
I've had already been deleting my wtf folder, sometimes without noticing any improvement, but since Avast game mode is disabled it seems to be fixed !
