### ISSUE TITLE
Jumping around screen when dragged

### ISSUE THREAD

**Issue by drkdragonarcher** [arkayenro/arkinventory#934]
Not getting a LUA error or anything to help debug this but with only ArkInventory enabled if I drag the bag screen around the screen, it doesn't stay attached to the mouse and jumps around.

**Comment by arkayenro** [comment]
try the latest alpha build and see if it still happens.  its probably related to the constant updates the broken shore tower buffs are causing

**Comment by Gildan71** [comment]
Had this problem, installed r636-alpha and the problem went away
