### ISSUE TITLE
No longer able to assign multiple categories by clicking

### ISSUE THREAD

**Issue by Syrasha** [arkayenro/arkinventory#936]
I've upgraded recently, and I lost all my config data. I'm going through the process of configuring again, and when configuring my virtual bars, I'm running into a frustrating issue that seems new to me. 

Used to be, when setting up my "Consumables" section, say, I could click multiple items in the consumables list, picking and choosing. I never had to hover over one, (we'll say "Guardian Elixirs", and then when the smaller menu pops up to the right, go over and click "Assign". I had only to click the word "Guardian Elixirs" and it would add it, then I could immediately also click "Battle Elixirs", "Bandages", "Food", etc.  But now it seems to want me to navigate over to the "official" 'Assign' menu item, which pops the menu out of existence. Now I have to go up to the red virtual bar config square, right click, and navigate down to "Consumables" then "Battle Elixir", then "Assign" and do that over and over and over, it's laborious and quite slow. 

What happened to the ability to just click on several subcategories in sequence?

**Comment by arkayenro** [comment]
with the ability to assign a category to a bar, but not enable it, too many people were getting confused as to why their items werent ending up on the bar even though they had assigned the category to it.

that change forces them to see the enabled/disabled option at the time they assign the category so theres no reason now for anyone to get confused or miss the enabled option

**Comment by Syrasha** [comment]
But there is no way to say "Assign these 15 items within Consumables to this bar"  or  "Assign All Consumables items to this bar" and then go in and remove 2, or whatnot.  This creates far more work for _all_ users, to have to click through like 4 menus, _carefully_, 15 times. And that's just for one bar!

Please either enable a modifier key to assign items via Shift+clicking the categories/items, or create a way to add a whole category at once. (not as a single item, I need to have Artifact Power in a separate bar, for example). 

I've never been confused by the enable/disable options, they're right there, and you can see them. I'm sorry people being confused created more work for you, though. That's silly.

**Comment by Syrasha** [comment]
Another potential band-aid would be to make it such that clicking "Assign" did NOT pop the menu out of existence. Then we could navigate to the next item, again navigate to "Assign", and on and on.  Still a hassle, but at least less precision mouse work.

**Comment by Syrasha** [comment]
Where is your donate button? I've been using this addon for YEARS, and it's one of my favorites. =)

**Comment by Syrasha** [comment]
ping =)

**Comment by arkayenro** [comment]
was added back in 3.07.29
