### ISSUE TITLE
Auto-hiding items if more than 2 stacks

### ISSUE THREAD

**Issue by fivecatsrc** [arkayenro/arkinventory#940]
I'm almost sure this is not an issue and is in fact addressed somewhere, but I couldn't find a darn thing about how to change it. 

When I have more than 2 stacks worth of an item (e.g. cloth), AI will only show 2 stacks and hide the rest. I can't for the life of me find a setting to change to make it not do this.

**Comment by arkayenro** [comment]
i think thats in the style under items, you need to reset it back to zero

**Comment by fivecatsrc** [comment]
You're the light of my life. Thank you!
