### ISSUE TITLE
ArkInv 3.07.24 on 7.2.5 'Script ran too long' on zone change

### ISSUE THREAD

**Issue by ghubwow** [arkayenro/arkinventory#942]
When changing zones via teleport or method that causes a loading screen (but not logging into game) the following error occurs.  Verified with only Arkinventory and BugSack/-Grabber loaded.

1x ArkInventory\ArkInventory-30724.lua:2941: script ran too long
ArkInventory\ArkInventory-30724.lua:2941: in function `CategoryGenerate'
ArkInventory\ArkInventory-30724.lua:3742: in function `ItemCacheClear'
ArkInventory\ArkInventoryStorage.lua:3446: in function `ScanChanged'
ArkInventory\ArkInventoryStorage.lua:1682: in function `ScanBag'
ArkInventory\ArkInventoryStorage.lua:1373: in function `Scan'
ArkInventory\ArkInventoryStorage.lua:1348: in function `ScanLocation'
ArkInventory\ArkInventoryStorage.lua:1202: in function <ArkInventory\ArkInventoryStorage.lua:1195>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...Externals\curse\svn\Ace3-AceBucket\AceBucket-3.0-3.lua:116: in function `func'
...y\Externals\curse\svn\Ace3-AceTimer\AceTimer-3.0-17.lua:55: in function <...y\Externals\curse\svn\Ace3-AceTimer\AceTimer-3.0.lua:48>

Locals:
nil

**Comment by jcai1** [comment]
I've been having a different "script ran too long" error with the 7.2.5 patch.

	1x ArkInventory\ArkInventory-30727.lua:4428: script ran too long
	ArkInventory\ArkInventory-30727.lua:4428: in function `Frame_Main_Draw'
	ArkInventory\ArkInventory-30727.lua:3781: in function `Frame_Main_DrawLocation'
	ArkInventory\ArkInventory-30727.lua:3774: in function `Frame_Main_Generate'
	ArkInventory\ArkInventory-30727.lua:4821: in function `Frame_Main_Show'
	ArkInventory\ArkInventory-30727.lua:4798: in function `Frame_Main_Toggle'
	ArkInventory\ArkInventory-30727.lua:9146: in function <ArkInventory\ArkInventory.lua:9141>
	(tail call): ?
	[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

	Locals:
	frame = ARKINV_Frame1 {
	 0 = <userdata>
	 ARK_Data = <table> {
	 }
	}
	loc_id = 1
	(*temporary) = false
	(*temporary) = "ArkInventory\ArkInventoryTooltip.lua:48: script ran too long"
	(*temporary) = false
	(*temporary) = "ArkInventory\ArkInventoryTooltip.lua:48: script ran too long"
	(*temporary) = "script ran too long"
	type = <function> defined =[C]:-1

It happens when out of combat, which is strange because I thought the execution time limit was for in-combat only. In any case, when this happens a workaround is to press "Refresh" and it should finish drawing.

**Comment by andrasterawr** [comment]
I'm getting a similar problem with errors after load screens. It works fine when I log in but if I port or anything I get an error that the script ran too long (the line number varies also). I'm not sure why it chopped everything off at the beginning but hopefully this is at least somewhat helpful.

> Message: ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua line 3811:
   script ran too long
Debug:
   ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:3811: ObjectStringDecode()
   ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:3576: ObjectInfoArray()
   ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:4023: ObjectIDCategory()
   ArkInventory\ArkInventory.lua:3638: ItemCategoryGetPrimary()
   ArkInventory\ArkInventory.lua:3691: ItemCategoryGet()
   ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:1698: ScanBag()
   ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:1370: Scan()
   ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:1345: ScanLocation()
   ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:1199:
      ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:1192
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[2]"]:9:
      [string "safecall Dispatcher[2]"]:5
   (tail call): ?
   ...Externals\curse\svn\Ace3-AceBucket\AceBucket-3.0.lua:116: func()
   ...\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:55:
      ...\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:48

**Comment by behub** [comment]
Same issues. Error occurs during the load screen.

`1x ArkInventory\ArkInventoryConst.lua:786: script ran too long
ArkInventory\ArkInventoryConst.lua:786: in function <ArkInventory\ArkInventoryConst.lua:774>
(tail call): ?
ArkInventory\ArkInventoryStorage.lua:2612: in function `ScanCollectionToy'
ArkInventory\ArkInventoryStorage.lua:1393: in function `Scan'
ArkInventory\ArkInventoryStorage.lua:1345: in function `ScanLocation'
ArkInventory\ArkInventoryStorage.lua:73: in function `EraseSavedData'
ArkInventory\ArkInventoryStorage.lua:238: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0-3.lua:120: in function <ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
nil`

**Comment by arkayenro** [comment]
edit arkinventory.lua, and on line 2427 change

`ArkInventory:RegisterBucketMessage( "EVENT_ARKINV_ZONE_CHANGED_BUCKET", 1 )`

to 

`ArkInventory:RegisterBucketMessage( "EVENT_ARKINV_ZONE_CHANGED_BUCKET", 5 )`

see if the extra delay after zoning allows it work or not

**Comment by arkayenro** [comment]
you can also test opening the mount window after logging in, and then zoning somewhere else to see if building all the mount data before a zone makes it work

**Comment by ghubwow** [comment]
Re: ArkInventory:RegisterBucketMessage( "EVENT_ARKINV_ZONE_CHANGED_BUCKET", 1 )

5 didn't do it; 10 seems to have been ok...so far...

**Comment by behub** [comment]
5 Didn't help. Will try 10.

**Comment by ghubwow** [comment]
10 seems to have helped a bit, I think; it's not every-single-time now, just most.

**Comment by arkayenro** [comment]
feel free to comment out the line completely, just add two minus signs to the beginning

its not overly important and i can probably get away with removing the functionality if its causing zoning issues

**Comment by andrasterawr** [comment]
Took mine to 15 and I don't seem to be getting the error at all anymore. 10 was about half and half.

**Comment by ghubwow** [comment]
Couldn't find a setting that let it go error-free so I remmed out the line as suggested.  After doing that, this new beauty happens:

1x ArkInventory\ArkInventoryStorage.lua:3766: script ran too long
ArkInventory\ArkInventoryStorage.lua:3766: in function `ObjectStringDecode'
ArkInventory\ArkInventoryStorage.lua:3576: in function `ObjectInfoArray'
ArkInventory\ArkInventoryStorage.lua:3563: in function `ObjectInfoQuality'
ArkInventory\ArkInventoryStorage.lua:1665: in function `ScanBag'
ArkInventory\ArkInventoryStorage.lua:1370: in function `Scan'
ArkInventory\ArkInventoryStorage.lua:366: in function <ArkInventory\ArkInventoryStorage.lua:357>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...Externals\curse\svn\Ace3-AceBucket\AceBucket-3.0-3.lua:116: in function `func'
...y\Externals\curse\svn\Ace3-AceTimer\AceTimer-3.0-17.lua:55: in function <...y\Externals\curse\svn\Ace3-AceTimer\AceTimer-3.0.lua:48>

Locals:
nil

**Comment by ghubwow** [comment]
3.07.30 still enjoying this. Please, for the love of God, make it stop.

1x ArkInventory\ArkInventoryTooltip.lua:403: script ran too long
ArkInventory\ArkInventoryTooltip.lua:403: in function `TooltipFind'
ArkInventory\ArkInventory-30730.lua:3408: in function `ItemCategoryGetDefaultActual'
ArkInventory\ArkInventory-30730.lua:3603: in function `ItemCategoryGetDefault'
ArkInventory\ArkInventory-30730.lua:3702: in function `ItemCategoryGet'
ArkInventory\ArkInventoryStorage.lua:1698: in function `ScanBag'
ArkInventory\ArkInventoryStorage.lua:1370: in function `Scan'
ArkInventory\ArkInventoryStorage.lua:1345: in function `ScanLocation'
ArkInventory\ArkInventoryStorage.lua:1199: in function <ArkInventory\ArkInventoryStorage.lua:1192>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...Externals\curse\svn\Ace3-AceBucket\AceBucket-3.0-3.lua:116: in function `func'
...y\Externals\curse\svn\Ace3-AceTimer\AceTimer-3.0-17.lua:55: in function <...y\Externals\curse\svn\Ace3-AceTimer\AceTimer-3.0.lua:48>

Locals:
nil

**Comment by arkayenro** [comment]
try the latest alpha and see if it stops - there is some debug output in it though

**Comment by ghubwow** [comment]
3.07.31 gives this during combat and sometimes just after: 
ArkInventory\ArkInventory-30731.lua:10181: script ran too long
ArkInventory\ArkInventory-30731.lua:10181: in function `ThreadTimer_Update'
[string "*:OnUpdate"]:4: in function <[string "*:OnUpdate"]:1>

Locals:

**Comment by ghubwow** [comment]
Received this while opening ArkInv. Not combat, sitting in a rest area: 

1x ArkInventory\ArkInventory-30731.lua:10181: script ran too long
ArkInventory\ArkInventory-30731.lua:10181: in function `ThreadTimer_Update'
[string "*:OnUpdate"]:4: in function <[string "*:OnUpdate"]:1>

Locals:
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 window-1 = <no value>
}
(for control) = "window-1"
id = "window-1"
thread = <no value>
(*temporary) = false
(*temporary) = "ArkInventory\ArkInventoryStorage.lua:3635: script ran too long"
(*temporary) = false
(*temporary) = "ArkInventory\ArkInventoryStorage.lua:3635: script ran too long"
(*temporary) = "script ran too long"
pairs = <function> defined =[C]:-1
type = <function> defined =[C]:-1
error = <function> defined =[C]:-1

**Comment by arkayenro** [comment]
try the 655 alpha

**Comment by ghubwow** [comment]
w/ 655 alpha, received this on login: 

1x ArkInventory\ArkInventory-30730.lua:2961: script ran too long
ArkInventory\ArkInventory-30730.lua:2961: in function `CategoryGenerate'
ArkInventory\ArkInventory-30730.lua:3765: in function `ItemCacheClear'
ArkInventory\ArkInventoryStorage.lua:3469: in function `ScanChanged'
ArkInventory\ArkInventoryStorage.lua:1679: in function `ScanBag'
ArkInventory\ArkInventoryStorage.lua:1370: in function `Scan'
ArkInventory\ArkInventoryStorage.lua:366: in function <ArkInventory\ArkInventoryStorage.lua:357>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...Externals\curse\svn\Ace3-AceBucket\AceBucket-3.0-3.lua:116: in function `func'
...y\Externals\curse\svn\Ace3-AceTimer\AceTimer-3.0-17.lua:55: in function <...y\Externals\curse\svn\Ace3-AceTimer\AceTimer-3.0.lua:48>

Locals:
nil

**Comment by ghubwow** [comment]
With 655 alpha, received this on taking a portal out of Dalaran

1x ...rfaceArkInventoryRules\ArkInventoryRules-10003.lua:195: script ran too long
...rfaceArkInventoryRules\ArkInventoryRules-10003.lua:195: in function `AppliesToItem'
ArkInventory\ArkInventory-30730.lua:3640: in function `ItemCategoryGetRule'
ArkInventory\ArkInventory-30730.lua:3676: in function `ItemCategoryGetPrimary'
ArkInventory\ArkInventory-30730.lua:3704: in function `ItemCategoryGet'
ArkInventory\ArkInventoryStorage.lua:1698: in function `ScanBag'
ArkInventory\ArkInventoryStorage.lua:1370: in function `Scan'
ArkInventory\ArkInventoryStorage.lua:1345: in function `ScanLocation'
ArkInventory\ArkInventoryStorage.lua:1199: in function <ArkInventory\ArkInventoryStorage.lua:1192>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...Externals\curse\svn\Ace3-AceBucket\AceBucket-3.0-3.lua:116: in function `func'
...y\Externals\curse\svn\Ace3-AceTimer\AceTimer-3.0-17.lua:55: in function <...y\Externals\curse\svn\Ace3-AceTimer\AceTimer-3.0.lua:48>

Locals:
nil

**Comment by arkayenro** [comment]
try the 656 alpha, its got adjustable timeout settings so you can lower the value until it works for you

**Comment by ghubwow** [comment]
Seems you took out the adjustable timer that would have handled OOC, checking with 659.

659 on login

1x ArkInventory\ArkInventoryTooltip.lua:62: script ran too long
ArkInventory\ArkInventoryTooltip.lua:62: in function <ArkInventory\ArkInventoryTooltip.lua:58>
(tail call): ?
ArkInventory\ArkInventoryStorage.lua:1641: in function `ScanBag'
ArkInventory\ArkInventoryStorage.lua:1370: in function `Scan'
ArkInventory\ArkInventoryStorage.lua:1345: in function `ScanLocation'
ArkInventory\ArkInventoryStorage.lua:1199: in function <ArkInventory\ArkInventoryStorage.lua:1192>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...Externals\curse\svn\Ace3-AceBucket\AceBucket-3.0-3.lua:116: in function `func'
...y\Externals\curse\svn\Ace3-AceTimer\AceTimer-3.0-17.lua:55: in function <...y\Externals\curse\svn\Ace3-AceTimer\AceTimer-3.0.lua:48>

Locals:
nil

**Comment by arkayenro** [comment]
@ghubwow what have you got the out of combat timeout value set to?

**Comment by ghubwow** [comment]
Out of combat value yielding?  No idea what it is, the option was removed: 
"* removed - config options for out of combat yielding"

**Comment by arkayenro** [comment]
config > workarounds > threads

same place the old setting was, just theres now two of them

**Comment by ghubwow** [comment]
I'll have to redo some testing; something odd was going on with the updates. Working from a cold install now -- that saved var file was > 10yrs old, too, but the new on is a quarter the size so...guess it was time. :p

**Comment by ghubwow** [comment]
Ok, haven't seen any more of those errors since setting to 50.
