### ISSUE TITLE
Tracked Currencies show green boxes instead of icons.

### ISSUE THREAD

**Issue by ashkashlitwin** [arkayenro/arkinventory#943]
![image](https://user-images.githubusercontent.com/19734305/27152686-82c00c3c-5103-11e7-98c1-445e874102f7.png)
![image](https://user-images.githubusercontent.com/19734305/27152691-86fa7148-5103-11e7-936f-85d1a0011be5.png)

**Comment by arkayenro** [comment]
fixed in 3.07.28
