### ISSUE TITLE
Mount bag window is showing "no data"

### ISSUE THREAD

**Issue by Draven17** [arkayenro/arkinventory#946]
Everytime I open the mount window it is showing none of my mounts and a lua error message appears.
**Version:** 3.02.54_BETA_17-00-Cataclysm

**Message:** ..\AddOns\ArkInventory\ArkInventory.lua line 2361:
   attempt to perform arithmetic on local 'v11' (a nil value)
**Debug:**
   [C]: ?
   ArkInventory\ArkInventory.lua:2361: ItemSortKeyGenerate()
   ArkInventory\ArkInventory.lua:5218: Frame_Bar_DrawItems()
   ArkInventory\ArkInventory.lua:5036: Frame_Container_Draw()
   ArkInventory\ArkInventory.lua:4200: Frame_Main_Draw()
   ArkInventory\ArkInventory.lua:3562: Frame_Main_DrawLocation()
   ArkInventory\ArkInventory.lua:3553: Frame_Main_Generate()
   ArkInventory\ArkInventory.lua:4299: Frame_Main_Show()
   ArkInventory\ArkInventory.lua:4264: Frame_Main_Toggle()
   [string "ARKINV_TOGGLE_MOUNT"]:1:
      [string "ARKINV_TOGGLE_MOUNT"]:1

**Comment by arkayenro** [comment]
are you really running a version from six years ago?  3.02.54_BETA_17-00-Cataclysm

you may want to upgrade to a more current one that supports legion

**Comment by Draven17** [comment]
the thing is that i am currently playing on a private server with some friends. i alos tried (for some reason) a new version of the addon and i got even more error  messages.

**Comment by Draven17** [comment]
oh it works now. ok i have no idea why but it works.

**Comment by arkayenro** [comment]
blizzard changes a lot of stuff between versions so you should probably match the toc level to make sure you get the correct version of AI to work on your server
