### ISSUE TITLE
Patch: Auto sell inprovements

### ISSUE THREAD

**Issue by AntiBlueQuirk** [arkayenro/arkinventory#948]
I made some modifications to the mod to improve the functionality of the Junk items feature.

Added features:

- Items in a bar called "Junk" are now treated as junk items to sell. (configurable)
- The items that the addon sells, destroys or refuses to destroy can be listed so you get a summary of what all happened. (configurable, disabled by default)
- Items with Uncommon rarity or above are never destroyed (configurable)
- Selling/destruction messages are colorized

All new configurable options (3 in total: "Delete uncommon", "List Items", "Include "Junk" bar") are included with the other Auto sell configuration options.

All new strings are included in the enUS localization, though I'm not easily capable of including them in other localizations. (Unless you're okay with Google Translate.)

Since the code isn't available in the repository, I'm unable to create a pull request, but I created a patch file with git diff that you should be able to apply.

[aimod.txt](https://github.com/arkayenro/arkinventory/files/1083225/aimod.txt)

**Comment by arkayenro** [comment]
localisations for new stuff i tend to leave empty (so they get english) up until someone volunteers a translation.  i dont trust the computer translations enough as they have no context

i use svn so the git diff will take a bit to merge manually but should be ok.  at some point i have to work out if git can easily replace my svn workflow or if i have to adjust

btw, not a fan of the bar name = sell thing as people forget and hide the names and then when they go to assign stuff to that bar later on it disappears and if they dont notice it ends up being a problem.  its why ive left the sell/destroy code as basic as possible and prefer users pick a proper junk sell mod with all the bells and whistles

**Comment by AntiBlueQuirk** [comment]
If you're not comfortable with the bar name thing being on, you could disable it by default. However, I think being able to auto-sell items in certain bars is a very powerful feature, especially when combined with the rules system.

That being said, I've thought about it, and I don't think selling by bar name is a good idea. Not only is it kind of "magic numbery", but it causes localization problems. If you'd like to ignore that part of that patch go ahead. I've come up with a better way to handle it, I think.

**Comment by arkayenro** [comment]
currently the sell function looks for the junk/trash category (or anything that is poor quality), a better way would be to add a flag to each rule that people can tick to mark items it collects as sellable, that way they can keep things on the right bars but also sell them

its still just as dangerous but at least this way i could add tooltip text and warnings on the menus

**Comment by arkayenro** [comment]
btw, the list thing wont work as the API doesnt actually tell you if the item was sold/destroyed - its why occasionally youll see junk items still remaining

its also why the how much everything sold it for isnt calculated until afterwards

**Comment by AntiBlueQuirk** [comment]
I was thinking of a flag on the bars instead of the rules, but that would work too. (or you could put flags on both.)

Autojunking items is a dangerous feature no matter what, which is why it's disabled by default. But you've already got some good safeties in place. Adding warnings to tooltips would help even more.

Yeah, I noticed that the selling was a best-effort thing because the apis are asynchronous, but it was a feature I really wanted anyway. The message should probably say "Selling", not "Sold".

**Comment by arkayenro** [comment]
theres an alpha on curse if you want to test it

i still need to add in the list option though

**Comment by AntiBlueQuirk** [comment]
It looks good, but it crashes at `ArkInventoryJunk.lua:64`: `"attempt to compare number with nil"`
Changing `ArkInventory.db.option.junk.quality` to `ArkInventory.db.option.junk.raritycutoff` fixes this, but it still doesn't work quite right. After setting the rule as a auto-sell rule and visiting a vendor, nothing happens.

`ArkInventoryJunk.lua:62` gets the category data from `cat = ArkInventory.db.option.category[cat_type].data[cat_code]` then line 64 checks whether it's a junk rule with `cat.junk`. However on `ArkInventoryMenu.lua:964` (and `1600`) the junk rule status is set with `codex.catset.category.junk[cat_z][cat_code]`. This doesn't look like the same reference to me. Is it correct?

**Comment by arkayenro** [comment]
nope, its wrong.  i started to make the category autosell global and then changed it to be part of the categoryset.  that what i get for uploading code at 1am

**Comment by AntiBlueQuirk** [comment]
Alright, seems to work at first glance. I'll have to do some more extensive testing to make sure it all works properly but all the basic features seem to work. I was a bit confused about the test feature at first. I didn't realize it was preventing item selling at first, so you might want to put a notification at the end when it's on. 

If you're worried about the list option being misleading, you could add up what you think it should sell for as you go along, then compare the expected sell value with the actual value at the end, and show a message if the values don't match. It might be wrong if the user does anyrhing while you're auto-selling, but should work most of the time, and would be simple to implement. (The proper way, I think would be to track the items you're trying to sell, and check that they actually get sold.)

Other than that, I'm pretty happy with it so far. :)
