### ISSUE TITLE
Wiki: Broken Links

### ISSUE THREAD

**Issue by nitz** [arkayenro/arkinventory#949]
Hey, just found some broken links when I was looking for the rules functions. The links in the second paragraph on the [https://github.com/arkayenro/arkinventory/wiki/Rules](Rules) page link to 'RuleFunctions' and 'ExampleRules', but the pages that exist are 'RuleFunction' (no 's'), and 'Rule_Examples'.

Just thought you might want to fix those!

Cheers

**Comment by arkayenro** [comment]
thanks, fixed
