### ISSUE TITLE
corrupted tooltips cause ArkInventory to stop working

### ISSUE THREAD

**Issue by joevt** [arkayenro/arkinventory#951]
Mac users are currently experiencing an issue with recurring corrupted tooltips. Blizzard made a patch recently so the client does not crash when interacting with these items (usually while doing mouseover), but are still working on fixing the corrupted tooltips.
https://us.battle.net/forums/en/wow/topic/20755617018

Sometimes an item with corrupted tooltip info can cause ArkInventory to stop working (items will not get sorted and displayed). The following line has an error because s[v] is a function instead of a string:
```lua
				sx = string.format( "%s %s", sx, s[v] )
```

One fix is to replace the following line:
```lua
			if s[v] then
```
with this:
```lua
			if type(s[v]) == 'string' then
```

The function comes from this line:
```lua
				t = _G[info.equiploc]
```
where info.equiploc is somehow set to "ClearCursor" which is the name of a function (obviously not a valid equipment location name).

So another fix would be to replace the following line:
```lua
			if info.equiploc and info.equiploc ~= "" and _G[info.equiploc] then
```
with this:
```lua
			if info.equiploc and info.equiploc ~= "" and type(_G[info.equiploc] == 'string') then
```

**Comment by Obsouleet** [comment]
I can confirm this - very annoying. Have to use an older version until this is fixed.

**Comment by arkayenro** [comment]
blizzard was supposed to have fixed the bug 3 days ago

there also would be no "older" version of ai to go back to as that code hasnt changed for a long time

**Comment by arkayenro** [comment]
btw, if there was an error generated could you please post it?

**Comment by Obsouleet** [comment]
I get multiple errors:
`[C]: in function `LoadAddOn'
ArkInventory\ArkInventory-30727.lua:9385: in function `LoadAddOn'
ArkInventory\ArkInventory-30727.lua:9398: in function `BlizzardAPIHook'
ArkInventory\ArkInventory-30727.lua:2288: in function <ArkInventory\ArkInventory.lua:2281>
(tail call): ?`

`1x ArkInventory\ArkInventory-30730.lua:2959: script ran too long
ArkInventory\ArkInventory-30730.lua:2959: in function `CategoryGenerate'
ArkInventory\ArkInventory-30730.lua:3765: in function `ItemCacheClear'
ArkInventory\ArkInventoryStorage.lua:3469: in function `ScanChanged'
ArkInventory\ArkInventoryStorage.lua:1679: in function `ScanBag'
ArkInventory\ArkInventoryStorage.lua:1370: in function `Scan'
ArkInventory\ArkInventoryStorage.lua:366: in function <ArkInventory\ArkInventoryStorage.lua:357>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...Externals\curse\svn\Ace3-AceBucket\AceBucket-3.0-3.lua:116: in function `func'
...y\Externals\curse\svn\Ace3-AceTimer\AceTimer-3.0-17.lua:55: in function <...y\Externals\curse\svn\Ace3-AceTimer\AceTimer-3.0.lua:48>

Locals:
nil`

`6x [string "safecall Dispatcher[2]"]:9: script ran too long
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...Externals\curse\svn\Ace3-AceBucket\AceBucket-3.0-3.lua:116: in function `func'
...y\Externals\curse\svn\Ace3-AceTimer\AceTimer-3.0-17.lua:55: in function <...y\Externals\curse\svn\Ace3-AceTimer\AceTimer-3.0.lua:48>

Locals:
func = <function> defined @ArkInventory\ArkInventoryStorage.lua:357
(*temporary) = false
(*temporary) = nil
(*temporary) = "script ran too long"
method = <function> defined @ArkInventory\ArkInventoryStorage.lua:357
arg1 = <table> {
 StartupChecks = <function> defined @ArkInventory\ArkInventory.lua:10065
 EVENT_WOW_PLAYER_SKILLS = <function> defined @ArkInventory\ArkInventoryStorage.lua:285
 LocationIsControlled = <function> defined `

These errors appear sinc Version 3.07.29. Earlyer versions are safe.

**Comment by arkayenro** [comment]
the first error is because it could not load the Blizzard_Collections addon which seems a bit odd as its an internal blizzard addon that is part of the game

the other two are an out of combat timer issue that shouldnt be related to corrupt tooltips

**Comment by joevt** [comment]
I don't remember the error. Anyway, the corrupted tooltip problem has been fixed by Blizzard so I don't think this is a problem anymore. But if you want to reproduce the error, I suppose you could get the error by forcing t to be a function.

You could make the suggested change so that it checks for string type which also has the original effect of checking for not null; or you can just close this issue.

**Comment by arkayenro** [comment]
ive covered most of the sort options with better logic in 3.07.32  just in case it happens again, hopefully that should stop it
