### ISSUE TITLE
Script ran too long

### ISSUE THREAD

**Issue by the2pit** [arkayenro/arkinventory#955]
I have tried this before and after clearing cache folders, errors folder and all other addons. no change

Date: 2017-07-06 11:00:05
ID: 1
Error occured in: Global
Count: 1
Message: ...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua line 393:
   script ran too long
Debug:
   ...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:393: TooltipFind()
   ...nterface\AddOns\ArkInventory\ArkInventoryTooltip.lua:497: TooltipContains()
   ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:1658: ScanBag()
   ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:1370: Scan()
   ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:366:
      ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:357
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[2]"]:9:
      [string "safecall Dispatcher[2]"]:5
   (tail call): ?
   ...nterface\AddOns\Ace3\AceBucket-3.0\AceBucket-3.0.lua:116: func()
   Ace3\AceTimer-3.0\AceTimer-3.0.lua:55:
      Ace3\AceTimer-3.0\AceTimer-3.0.lua:48
Locals:
None

**Comment by arkayenro** [comment]
try the latest alpha and see if it helps

**Comment by arkayenro** [comment]
fixed in 3.07.31
