### ISSUE TITLE
Flashing Bags

### ISSUE THREAD

**Issue by jeremyregnerus** [arkayenro/arkinventory#958]
I used the automatic update this morning from Curse, so I'm not sure which version this started happening. Although based on the change log, I'm guessing *3.07.31 (09-JUL-2017)*.

ArkInventory is now flashing every time something is added or removed from my bags, as in the entire frame dissapears and is then redrawn. This is true even when adding to the stack of an item.

**Comment by arkayenro** [comment]
increase the out of combat thread timer (config > workarounds) until it stops - although you might end up getting a script ran too long error
