### ISSUE TITLE
IGNORED (PET JOURNAL OPEN)

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#959]
Recently upgraded to the latest version and I see this ArkInventory message.  It seems to happen the first time I open the Mounts/Pet Journal/Toy Box/etc. window using Shift-P.  I can't seem to make it show up afterwards.  Is this some sort of debugging message that's been added for new functionality?

**Comment by hollo6** [comment]
It shows up for me every time I open that panel.

**Comment by arkayenro** [comment]
it'll be gone in the next release

**Comment by arkayenro** [comment]
fixed in 3.07.32
