### ISSUE TITLE
Arkinventory in Testmode

### ISSUE THREAD

**Issue by mcfishy66** [arkayenro/arkinventory#960]
Ik keep getting this msg on opening AI.
WARNING> testmode is enabled in your config, no items were actually destroyed or sold.
How do i solve this? 
Many thanks

**Comment by arkayenro** [comment]
*3.07.29 (22-JUN-2017)*
 * added - config option for testing auto sell mode (this is enabled by default, if you currently have auto sell enabled it will display a warning and wont sell anything until you disable this)

go into the config and disable the auto sell test mode (presuming you want it to auto sell)
