### ISSUE TITLE
Ilvl on icons

### ISSUE THREAD

**Issue by Panzaghor** [arkayenro/arkinventory#964]
I started using the add-on this week and so far it has been awesome but i can't seem to find an option to display ilvl on the item icon and i would like to know if there's an option for that, i tried using oilvl but for some reason it's not working with ark inv

**Comment by arkayenro** [comment]
yep, its in with all the other item options in the style area

**Comment by Panzaghor** [comment]
Thank you for the quick answer and for the great add-on that you've been working on for so long
