### ISSUE TITLE
Unable to locate Mythic keystone

### ISSUE THREAD

**Issue by kaseyd24** [arkayenro/arkinventory#965]
This maybe an issue that was resolved, but when searching for mythic keystones, they do not show up even though I know they are there.

**Comment by arkayenro** [comment]
right click on the refresh icon and enable hidden items as they must just be flagged as hidden

if they are just unhide their category

**Comment by kaseyd24** [comment]
Yup, and reset as well. 
Thank you for the response by the way, I know its insignificant, but its just an annoyance now lol.

![wowscrnshot_081717_134021](https://user-images.githubusercontent.com/31021551/29425611-e54364e6-8351-11e7-986e-ff4f9996c478.jpg)

**Comment by arkayenro** [comment]
oh, do mythic keystones actually have "keystone" in their name (thats a name search, not a full item search)

**Comment by kaseyd24** [comment]
I'm confused, everything has something in their name to search, I.E flask, hearthstone etc.  Why is the word keystone different?  and I did a name search I believe and arrived at this.
![wowscrnshot_082317_214606](https://user-images.githubusercontent.com/31021551/29645640-e02159fa-884c-11e7-9242-9800bfdfb3cc.jpg)

**Comment by kaseyd24** [comment]
Any update?

**Comment by arkayenro** [comment]
i know this is really old but i think i finally fixed it in the latest alpha

**Comment by kaseyd24** [comment]
Yes You DID.. sorry for the late response..
