### ISSUE TITLE
Caged Battle Pets not displaying

### ISSUE THREAD

**Issue by aaron9eee** [arkayenro/arkinventory#969]
I'm having an issue with caged battle pets not displaying an icon _(other than Blizzards big yellow 'W' placeholder icon)_ nor having tooltips. 
With all addons disabled, I can see the correct icons and tooltips, and with only ArkInventory enabled they appear as below:
![arkinventoryerror](https://user-images.githubusercontent.com/31742091/30177685-6f2ff9c0-93bb-11e7-8864-ee86eb23eda4.jpg)

**Comment by arkayenro** [comment]
there used to be an issue with the guild bank and caged battle pets, the api didnt return all the information but i just tested it with one of my pets and it seems to be ok now.

maybe pick up a pet and move it to another slot and see if it updates the icon

**Comment by aaron9eee** [comment]
I moved the pets around in my bags, and while I was clicked on one, I could
see the correct icon for it...but as soon as I set it down the big W
returned. No tooltip at any time.

**Comment by anteos59** [comment]
I have the exact same problem

**Comment by aaron9eee** [comment]
I routinely have two instances of WoW running. This bug only seems to
affect the instance that was opened second.

**Comment by arkayenro** [comment]
see #978 

should be fixed in 3.07.38
