### ISSUE TITLE
arkInventory not up to date on wowinterface.com

### ISSUE THREAD

**Issue by SonGokuSSJ** [arkayenro/arkinventory#970]
Can you please also upload the latest arkInventory version on wowinterface.com? Not everyone uses curse.

**Comment by arkayenro** [comment]
having password issues, its being a pain, ill work it out eventually

**Comment by SonGokuSSJ** [comment]
Thank you for your effort. As I only have about 3 Addons, which are on curse only, I can download them via browser for the time being. You can therefore concentrate on features and bug request (and free time!) and give this issue low priority.
