### ISSUE TITLE
My outfits rule isnt working.

### ISSUE THREAD

**Issue by FatalScroll** [arkayenro/arkinventory#972]
So i made this rule for an outfit

outfit ( "Kitty Gear" )

but when i have it in my bag it either (depending on the piece) sorts it to my soul bound items or just my general items area (heirlooms)

**Comment by arkayenro** [comment]
are you using an outfit mod or just the standard blizzard interface?

**Comment by FatalScroll** [comment]
Tried both with blizzardui and outfitters mod. Neither worked

**Comment by FatalScroll** [comment]
nvm apparently Im an idiot that didnt enable it.
