### ISSUE TITLE
Error on opening and cannot create new rule v 3.07.24

### ISSUE THREAD

**Issue by ScreaminPinata** [arkayenro/arkinventory#974]
Thought I would submit some information since I like the rule capabilities in this add on and would like to see it live on.

Not sure if swatter information is helpful but I get this error when opening ArkInventory. 

Date: 2017-10-07 08:00:45
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ArkInventory\ArkInventory.lua line 4815:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: PlaySound()
   ArkInventory\ArkInventory.lua:4815: Frame_Main_OnShow()
   [string "*:OnShow"]:1:
      [string "*:OnShow"]:1
   [C]: Show()
   ArkInventory\ArkInventory.lua:4787: Frame_Main_Show()
   ArkInventory\ArkInventory.lua:4766: Frame_Main_Toggle()
   ArkInventory\ArkInventory.lua:8917:
      ArkInventory\ArkInventory.lua:8905
   (tail call): ?
   ..\FrameXML\MainMenuBarBagButtons.lua:21: BagSlotButton_OnClick()
   [string "*:OnClick"]:4:
      [string "*:OnClick"]:1
Locals:
(*temporary) = "igBackPackOpen"

AddOns:
  Swatter, v7.5.5724 (TasmanianThylacine)
  ArkInventory, v30724
  ArkInventoryRules, v10003
  ArkInventoryRulesExample, v10000
  ArkInventoryRulesTSMGroup, v10601
  ArkInventoryRulesExample, v1.00
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=f0)

I get this error when I open the rules window.
Date: 2017-10-07 08:12:16
ID: 2
Error occured in: Global
Count: 1
Message: [string "*:OnShow"] line 1:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: PlaySound()
   [string "*:OnShow"]:1:
      [string "*:OnShow"]:1
   [C]: Show()
   ArkInventory\ArkInventoryRules.lua:23: Frame_Rules_Show()
   ArkInventory\ArkInventoryRules.lua:34: Frame_Rules_Toggle()
   ArkInventory\ArkInventoryMenu.lua:112: func()
   ...e\AddOns\ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua:722:
      ...e\AddOns\ArkInventory\Libs\ArkDewdrop\ArkDewdrop.lua:661
Locals:
(*temporary) = "igMainMenuOptionCheckBoxOn"

AddOns:
  Swatter, v7.5.5724 (TasmanianThylacine)
  ArkInventory, v30724
  ArkInventoryRules, v10003
  ArkInventoryRulesExample, v10000
  ArkInventoryRulesTSMGroup, v10601
  ArkInventoryRulesExample, v1.00
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=f0)

![image](https://user-images.githubusercontent.com/32597014/31309194-1859c44e-ab37-11e7-9f2e-513e01ea2f19.png)

And finally this is the error when I click on the "add" button in the rules window.

Date: 2017-10-07 08:12:36
ID: 3
Error occured in: Global
Count: 1
Message: [string "*:OnClick"] line 1:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: PlaySound()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
(*temporary) = "igMainMenuOptionCheckBoxOn"

AddOns:
  Swatter, v7.5.5724 (TasmanianThylacine)
  ArkInventory, v30724
  ArkInventoryRules, v10003
  ArkInventoryRulesExample, v10000
  ArkInventoryRulesTSMGroup, v10601
  ArkInventoryRulesExample, v1.00
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=f0)

**Comment by arkayenro** [comment]
blizzard changed the way sounds are played so you need to upgrade to the latest version as its been fixed in there.
