### ISSUE TITLE
Cannot Set Bar Width

### ISSUE THREAD

**Issue by Zaef** [arkayenro/arkinventory#975]
I know how to set the Width of the bag window, but I have 5 bars, one for each bag I have.

I want each bag to have a Width of 4 so it's laid out similar to the Blizzard UI.

How do I do this?
![untitled](https://user-images.githubusercontent.com/32754930/31526463-eebf50f6-af94-11e7-98c1-eef42580128c.png)

**Comment by arkayenro** [comment]
at the moment you cant.  i'd have to allow you to set a bar width and redo the layout code

it was on the things to do, i just havent gotten around to it yet

**Comment by arkayenro** [comment]
ok, it was a bit easier than i thought so min/max bar widths will be in the next release

**Comment by Zaef** [comment]
That's awesome!! Ty SO much. Will there be instructions how to do it?

**Comment by arkayenro** [comment]
nope, it should be fairly straight forward.

edit mode > bar number > width > min or max > enter a value

**Comment by Zaef** [comment]
Awesome! Cannot wait for the next release! Approximate date?

**Comment by arkayenro** [comment]
theres an alpha on curse right now if you want to test it

**Comment by Zaef** [comment]
I cannot find the Alpha to test. Sorry, I'm not terribly savvy at this sort
of thing, but would very much like to try it out so I can have all my bags
w/4 columns.

**Comment by arkayenro** [comment]
try here for manual download https://www.wowace.com/projects/ark-inventory/files

**Comment by arkayenro** [comment]
added in 3.07.36
