### ISSUE TITLE
Error - Restack

### ISSUE THREAD

**Issue by xXAntiAuraXx** [arkayenro/arkinventory#976]
When Im Restacking, Im getting this error:
 ...\ArkInventoryRestack.lua:432: bad argument #1 to 'band' (number expected, got nil)

I already reinstalled ArkInventory(yes, I deleted all settings in WTF-Folder for Arkinventory)

**Comment by arkayenro** [comment]
i've changed the code to handle null responses so it should be fixed next release

**Comment by xXAntiAuraXx** [comment]
Error is still there

**Comment by arkayenro** [comment]
youre using the alpha?

**Comment by AntiAura** [comment]
No, I downloaded the newest Version fromm curse

**Comment by arkayenro** [comment]
3.07.35 or 3.07.36 (ALPHA) [r675-alpha in the curse file listings]?

its only fixed (maybe) in 3.07.36 (ALPHA)

**Comment by xXAntiAuraXx** [comment]
Thank you! I used 35 from Curse.
