### ISSUE TITLE
Battle Pet icons

### ISSUE THREAD

**Issue by AkaraBWR** [arkayenro/arkinventory#978]
I'm sorry if this issue is discussed elsewhere, or it's an obvious setting that I'm missing for some reason. 

At some point my battle pet icons are showing as the default Warcraft Icon instead of their designated icon. Example in the picture. 

This still happens even when the only addon loaded in ArkInventory. 
![battle pets](https://user-images.githubusercontent.com/32828917/31856348-25054602-b684-11e7-9ee6-6d6e6dab2f9b.png)

**Comment by arkayenro** [comment]
move them to another slot and see if that picks them up, sometimes they can get stuck with no data

**Comment by AkaraBWR** [comment]
@arkayenro I have tried that and it doesn't work.

**Comment by arkayenro** [comment]
is it in the vault or somewhere else?  pet cages have issues in the vault

**Comment by AkaraBWR** [comment]
@arkayenro No, this happens everywhere no matter where my pets are. The picture above is just in my player bag. But this happens on every character, on every account. Doesn't matter if it's in my player bag, guild vault, bank, nothing. It's all the same icon if it's a caged pet.

**Comment by hollo6** [comment]
Just started having this issue, for no apparent reason. Disabling and reenabling TSM fixed it for me.

**Comment by hollo6** [comment]
Just figured it out what this is caused for me. When multiboxing (2 accounts but for the same e-mail), only the account I first log in can use the pet journal, the other says it is locked. And then this second account has the problem of not being able to read the battle pet icon data, I'm guessing because the entire journal is locked.

**Comment by arkayenro** [comment]
ah, that explains a lot.  seeing as AI doesnt really do anything on the battlepet side apart from scan and summon it shouldnt matter if the journal is locked or not so i've removed that part of the code and it will now scan regardless, which should give you back all the icons

**Comment by arkayenro** [comment]
should be fixed in 3.07.38
