### ISSUE TITLE
Suggestion: TSM - Item already on AH..

### ISSUE THREAD

**Issue by Manniala** [arkayenro/arkinventory#979]
Hey.

I have not found this, and wonder if it could be implemented in the feature.

I post a looooot of items on the AH, and i have many items that i got 2-3 off each type, but i always only post 1 at a time, so i often have many laying in the gbank on MyAhChar (yep thats its name), but to find out if i have an item in the gbank that is not on the AH after i posted all my 1000+ that day, i have to manually hover over each item to see what the tool-tip tells me, so wonder if there is a way for your addone to have a rule to look if an item is on the AH or not, and if not then put them in a group.

I hope this can be some thing that you would consider to put in.

Thx :)

**Comment by joevt** [comment]
You can create an add-on that adds functions that can be used by ArkInventory's rules.

First you need to figure out what add-on keeps track of items in the AH, how that's stored in the saved variables, and how to access that information. Search for the item id or name in the WTF folder to see where in the Saved Variables the information is stored. Then you can use that add-on's information in your ArkInventory rule add-on.

I made an ArkInventory rule add-on that uses CanIMogIt to help me sort items that I've learned or not learned, so I know if I can sell it or if I should mail it to an alt to learn the appearance.
[ArkInventoryRules_CanIMogIt.zip](https://github.com/arkayenro/arkinventory/files/1405433/ArkInventoryRules_CanIMogIt.zip)

The add-on adds three functions ciminotlearned, ciminotlearnable, and cimilearned which return either true or false.

For you, I think you would create a function countinah which returns how many of the item are in the AH.

**Comment by Manniala** [comment]
Thx :D 

I'm not a big coder here, and i looked at  Tradeskillmaster (the AH addone i use), but the TSM file in the savedvariable folder is 45mb big, for one of the files, but i think the other big one is only the database for items that is currently on the AH, but i will have to find a item that is not on the AH, log out, make a copy of all TSM files, then login, post that item and logout again, and compare the files, or search for that IS of the item, to be sure where it is located. i will give it a try, how hard can it be right :D hehe

But thx for the .zip :)

**Comment by Manniala** [comment]
And naah was not that easy :D Might have to wait til other give it a try that got skills for this :D
