### ISSUE TITLE
LUA errors when opening and closing bags

### ISSUE THREAD

**Issue by TgrHwke** [arkayenro/arkinventory#980]
I get these errors when opening and closing my bags.  The addon still works, displays, and sorts.

Opening:

Message: Interface\AddOns\ArkInventory\ArkInventory.lua:4815: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Time: 10/25/17 00:52:36
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventory.lua:4815: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: ?
[C]: in function `PlaySound'
Interface\AddOns\ArkInventory\ArkInventory.lua:4815: in function `Frame_Main_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[C]: in function `Show'
Interface\AddOns\ArkInventory\ArkInventory.lua:4787: in function `Frame_Main_Show'
Interface\AddOns\ArkInventory\ArkInventory.lua:4766: in function `Frame_Main_Toggle'
Interface\AddOns\ArkInventory\ArkInventory.lua:8987: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:8982>
(tail call): ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Closing:

Message: Interface\AddOns\ArkInventory\ArkInventory.lua:4891: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Time: 10/25/17 00:52:50
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventory.lua:4891: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: ?
[C]: in function `PlaySound'
Interface\AddOns\ArkInventory\ArkInventory.lua:4891: in function `Frame_Main_OnHide'
[string "*:OnHide"]:1: in function <[string "*:OnHide"]:1>
[C]: in function `Hide'
Interface\AddOns\ArkInventory\ArkInventory.lua:4867: in function `Frame_Main_Hide'
Interface\AddOns\ArkInventory\ArkInventory.lua:4764: in function `Frame_Main_Toggle'
Interface\AddOns\ArkInventory\ArkInventory.lua:8987: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:8982>
(tail call): ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:

**Comment by arkayenro** [comment]
are you using an old version?  the playsound api change was fixed in 3.07.35

**Comment by TgrHwke** [comment]
According to the Curse installer I am using version "3.07.35-nolib".

**Comment by arkayenro** [comment]
weird. with wow closed can you use the installer to remote AI (not the savedvariables - maybe take a backup of them just in case) then reinstall it
