### ISSUE TITLE
Issues when doing timewalking dungeon

### ISSUE THREAD

**Issue by eFse7en** [arkayenro/arkinventory#981]
Hi, I'm having issues with ArkInventory when doing timewalking Northrend dungeons. It is spamming with errors after some while. I would expect it breaks after I loot some item and it refreshes, as the issue starts to appear after about 30s in the dungeon and persists until reloading.

![image](https://user-images.githubusercontent.com/33643124/32757039-a6d7ad80-c8dd-11e7-810d-36e20f832e1a.png)
![image](https://user-images.githubusercontent.com/33643124/32757125-146ca33c-c8de-11e7-922c-a2da26080df7.png)

After leaving the dungeon issues is still there, and I suppose it triggers every time the bags are refreshed (example after using AP items):
![image](https://user-images.githubusercontent.com/33643124/32757154-3f4881ac-c8de-11e7-9304-5d28c7366862.png)

Issue is gone after reloading until I join time-walking dungeon again.

I am not having the issue when running LFR and I think it also doesn't occur during legion heroic.

**Comment by arkayenro** [comment]
it looks like another mod has tainted the gametooltip and its breaking arkinventory

youll need to work out where the taint comes from and have that author fix it.  considering its a dungeon then its most likely a raid/dungeon boss/mob marker mod or something like that.

read this https://github.com/arkayenro/arkinventory/wiki/Taint and see how you go

**Comment by eFse7en** [comment]
Thank you for a quick reply. I will try verifying which addon is causing a taint.
