### ISSUE TITLE
Error on load after d/c: ArkInventory.lua:7853: attempt to index field 'favourite' (a nil value)

### ISSUE THREAD

**Issue by cameronpm** [arkayenro/arkinventory#982]

**Comment by cameronpm** [comment]
![arkinventory_outfit_bug](https://user-images.githubusercontent.com/1286356/32984292-d4e8cc36-ccf7-11e7-8e9c-c22e27e375e9.png)

**Comment by cameronpm** [comment]
![arkinventory_load_error](https://user-images.githubusercontent.com/1286356/32984297-e359cfae-ccf7-11e7-90c3-d8a4adec3199.png)

**Comment by arkayenro** [comment]
are you using 3.07.36?

**Comment by cameronpm** [comment]
Yep. Not reproducible, just some race condition on load I guess.
