### ISSUE TITLE
item level sort improperly sorts ilvl 1000 legendaries

### ISSUE THREAD

**Issue by Burzolog** [arkayenro/arkinventory#984]
As of today new legendaries drop at ilvl 1000. Arkinventory appears to be sorting them between ilvls 100 and 101, rather than after ilvl 999.

![wowscrnshot_112817_234844](https://user-images.githubusercontent.com/707448/33359927-fbaa5e88-d496-11e7-9d97-4b885d7d75c1.jpg)
![wowscrnshot_112817_234845](https://user-images.githubusercontent.com/707448/33359928-fbb6adc8-d496-11e7-8a2d-49c6ab0d2102.jpg)
![wowscrnshot_112817_234846](https://user-images.githubusercontent.com/707448/33359929-fbc430ba-d496-11e7-9309-a7e6469c807a.jpg)

**Comment by arkayenro** [comment]
the sortkey is a string blob of various bits of data and ilvl was only set for 3 characters so its going to sort stupidly now its actually 4.  i'll fix it for next release

change ArkInventory.lua line 2780 to this if you want to fix it now
s["itemstatlevel"] = string.format( "%04i", t or 0 )

**Comment by arkayenro** [comment]
fixed in 3.07.37
