### ISSUE TITLE
Error Appears while Cursor is over Raid-Frames

### ISSUE THREAD

**Issue by Plusader** [arkayenro/arkinventory#987]
Message: Interface\FrameXML\UnitFrame.lua:469: Usage: GameTooltip:SetUnit("unit"[, hideStatus])
Time: 01/04/18 03:48:59
Count: 35
Stack: Interface\FrameXML\UnitFrame.lua:469: Usage: GameTooltip:SetUnit("unit"[, hideStatus])
...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:317: in function <...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:300>
[C]: ?
[C]: in function `SetUnit'
Interface\FrameXML\UnitFrame.lua:469: in function `UnitFrame_UpdateTooltip'
Interface\FrameXML\UnitFrame.lua:455: in function <Interface\FrameXML\UnitFrame.lua:442>

Locals: errMsg = "Interface\FrameXML\UnitFrame.lua:469: Usage: GameTooltip:SetUnit("unit"[, hideStatus])"
isTSMError = false
tsmErrMsg = nil
AceGUI = <table> {
 objPools = <table> {
 }
 RegisterAsContainer = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:521
 RegisterWidgetType = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:559
 WidgetBase = <table> {
 }
 RegisterAsWidget = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:537
 counts = <table> {
 }
 LayoutRegistry = <table> {
 }
 GetLayout = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:583
 GetWidgetVersion = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:613
 Create = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:172
 GetWidgetCount = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:607
 GetNextWidgetNum = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:596
 WidgetRegistry = <table> {
 }
 WidgetVersions = <table> {
 }
 RegisterLayout = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:573
 Release = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:206
 ClearFocus = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:257
 WidgetContainerBase = <table> {
 }
 SetFocus = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:247
}
TSM = <table> {
 Operations = <table> {
 }
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:398
 _author = "Sapu94, Bart39"
 DeleteCustomPriceSource = <function> defined @Interface\AddOns\TradeSkillMaster\CoreAPI\Prices.lua:56
 EnableModule = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:363
 modules = <table> {
 }
 baseName = "TradeSkillMaster"
 IterateEmbeds = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:473
 CreateGroupTree = <function> defined @Interface\AddOns\TradeSkillMaster\GUI\TSMFrames\GroupTree.lua:291
 SecureHookScript = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceHook\AceHook-3.0.lua:410
 GetAuctionPlayer = <function> defined @Interface\AddOns\TradeSkillMaster\GUI\AuctionFrame.lua:45
 RawHookScript = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceHook\AceHook-3.0.lua:395
 _desc = "Core addon for the TradeSkillMaster suite. Does nothing without modules installed."
 Printf = <function> defined @Interface\AddOns\TradeSkillMaster\CoreAPI\Modules.lua:147
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:440
 NO_SOUND_KEY = "TSM_NO_SOUND"
 LDBIcon = <table> {
 }
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:482
 LOG_INFO = <function> defined @Interface\AddOns\TradeSkillMaster\Debug\Logging.lua:376
 Delay

**Comment by arkayenro** [comment]
not an AI issue, its just one of the shared libraries.

AI does a post hook on SetUnit for battlepet stuff but that just gets called afterwards, not before, and this looks like the someone has either done a secure hook or remapped the SetUnit function.

disable AI and mouseover the raid frame and another mod will get blamed (whichever loaded that shared library first), might not be the actual cause though.  thats the downside to shared libraries
