### ISSUE TITLE
Bag Upgrade Not Displaying...

### ISSUE THREAD

**Issue by Raejyn** [arkayenro/arkinventory#989]
https://worldofwarcraft.com/en-us/news/21366969/upgrade-your-account-security-and-get-a-backpack-upgrade

You get 4 slots, arkinventory still showing 20 rather than 24. Not sure if it'll affect anything else yet.

**Comment by arkayenro** [comment]
the backpack is normally 16 slots, add 4 slots for the authenticator and thats only 20, not 24

disable AI and open the backpack to check
