### ISSUE TITLE
Caged Battle Pet Icons are  wrong or not Loaded?

### ISSUE THREAD

**Issue by fuba82** [arkayenro/arkinventory#992]
Hi there,

Seems since patch 7.3.5 the Icons from Caged Battlepets are not loaded correcty anymone:

**Ark Inventory - Stout Alemental -> NOT Caged (click to enlarge):**
![001](https://user-images.githubusercontent.com/11580974/35476041-a60905c8-03a9-11e8-897a-4e63701cbd5b.png)

**ElvUI - Stout Alemental -> NOT Caged (click to enlarge):**
![002](https://user-images.githubusercontent.com/11580974/35476042-a62c8cc8-03a9-11e8-9c03-39f7f15261ac.png)

**Ark Inventory - Sunfire Kaliri -> Caged (click to enlarge):**
![003](https://user-images.githubusercontent.com/11580974/35476043-a64a97a4-03a9-11e8-9933-07cb3c3eea27.png)

**ElvUI - Sunfire Kaliri -> Caged (click to enlarge):**
![004](https://user-images.githubusercontent.com/11580974/35476044-a66ba9d0-03a9-11e8-8f50-1b49fc8e1906.png)

As you can see the Icons are Ingame and work with Default Bags and also with ElvUI Bags but not with ArkInventory?

Maybe you can take a look on it?

**Comment by arkayenro** [comment]
try 3.07.40 and see if that helps

**Comment by q3fuba** [comment]
> try 3.07.40 and see if that helps
still the same with 3.07.40 :/

i will try to reset everything later but i hope i dont need to do it :D

**Comment by q3fuba** [comment]
ok i've done now:

1. Resetted all Settings by delete ArkInventory.lua from WTF folder
2. Re-Set some Runes, Settings, Styles...
3. Logged Out
4. Logged In
5. Same Error -> Icons are gone / WoW Icon
6. All the work for nothing...
7. i will Re-Apply my Backup now and hope you will fix this soon ;)

**Comment by arkayenro** [comment]
could you try [r697-alpha](https://www.wowace.com/projects/ark-inventory/files/2531977/download), it has some pet code changes that might fix it

**Comment by fuba82** [comment]
sure i'll test it soon

**Comment by fuba82** [comment]
I am sad to say it is still not working :(  
I have disabled ALL other Addons except ArkInventory and deleted the Cache folder too.  
I have also added a copare Picture from the Auction House so you can see it is working ingame.  

![wowscrnshot_021718_162946](https://user-images.githubusercontent.com/11580974/36342500-dfe860ac-13ff-11e8-9e11-afd7b2e134ff.jpg)
![wowscrnshot_021718_162951](https://user-images.githubusercontent.com/11580974/36342498-dfa0235a-13ff-11e8-8d0a-40d94490a53f.jpg)
![wowscrnshot_021718_163001](https://user-images.githubusercontent.com/11580974/36342499-dfc4f5e0-13ff-11e8-8988-66c1d3bd7ed9.jpg)
