### ISSUE TITLE
Stack compression indicator

### ISSUE THREAD

**Issue by AcidWeb** [arkayenro/arkinventory#995]
I'm aware that codebase don't allow to sum number of items in all stacks but maybe there is a way to display some notification on non-hidden item icons that some stacks are hidden?

BTW - Great job. It is rather rare to see addon supported so long.

**Comment by arkayenro** [comment]
actually it does allow for it.  item totals are already calculated.

what it doesnt allow for is a (single) virtual stack (because i dont want to rebuild the whole thing against secure templates along with all the extra code to do all the basic functions).

the threading may actually help here as item counts would need to be calculated for each item as they are found, not only when moused over, and they take a large chunk of cpu

it really depends on what type of notification would work to make it obvious there are more of the item available, just hidden

**Comment by AcidWeb** [comment]
Huh apparently I made too shallow dive in your code :-)

I can only guess but I expect that most of users use stack limit 0 or 1. From UX standpoint I would say that adding "+" to item count would be enough.

**Comment by arkayenro** [comment]
ive got the basics working but it takes a shitload of cpu for the initial load

one thing that doesnt work is if your stacks are not full, eg a 2+2 stack of something that can stack to 20 it doesnt see properly.  so i think ill need to update the itemcount function to also record the number of slots each item has taken up.  at least that way ill have a direct count to compare against

**Comment by arkayenro** [comment]
i think ive got it working ok, you can download it from here [r694-alpha](https://www.wowace.com/projects/ark-inventory/files/2530597/download)

**Comment by AcidWeb** [comment]
It works but... too well :-) I see that "+1" is displayed on items that can't have stacks when O have multiple copies of them in bags.

**Comment by AcidWeb** [comment]
```
Message: Interface\AddOns\ArkInventory\ArkInventory.lua:10328: Interface\AddOns\ArkInventory\ArkInventory.lua:6874: attempt to index field '?' (a nil value)
Time: 02/12/18 19:06:15
Count: 3
Stack: Interface\AddOns\ArkInventory\ArkInventory.lua:10328: Interface\AddOns\ArkInventory\ArkInventory.lua:6874: attempt to index field '?' (a nil value)
Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
[C]: ?
[C]: ?
Interface\AddOns\ArkInventory\ArkInventory.lua:10328: in function `ThreadResume'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: errorMessage = "Interface\AddOns\ArkInventory\ArkInventory.lua:10328: Interface\AddOns\ArkInventory\ArkInventory.lua:6874: attempt to index field '?' (a nil value)"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_TYPE_ERROR = 0
```

**Comment by AcidWeb** [comment]
Also I got tons of:
```
Message: Interface\AddOns\ArkInventory\ArkInventoryMedia.lua:116: ERROR: ARKINV_RulesFrameType:SetFont(): invalid fontHeight: 0, height must be > 0
Time: 02/12/18 19:06:03
Count: 1
Stack: Interface\AddOns\ArkInventory\ArkInventoryMedia.lua:116: ERROR: ARKINV_RulesFrameType:SetFont(): invalid fontHeight: 0, height must be > 0
(tail call): ?
[C]: in function `SetFont'
Interface\AddOns\ArkInventory\ArkInventoryMedia.lua:116: in function `MediaObjectFontSet'
Interface\AddOns\ArkInventory\ArkInventoryMedia.lua:154: in function `MediaFrameFontSet'
Interface\AddOns\ArkInventory\ArkInventoryMedia.lua:162: in function `MediaFrameFontSet'
Interface\AddOns\ArkInventory\ArkInventoryMedia.lua:177: in function `MediaAllFontSet'
Interface\AddOns\ArkInventory\ArkInventoryMedia.lua:184: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...\Libraries\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:239: in function `?'
Interface\AddOns\WeakAuras\Types.lua:1352: in main chunk

Locals: <none>
```
But it look like is not connected with this topic.

**Comment by arkayenro** [comment]
i'll add some more checking code to not include items that only stack to 1, or maybe just ignore equipable items?

the first error is probably related, i saw a similar error when i was building the new code - i've probably missed some logic around the array and part of it is nil

the second is due to a fix i added for the font sizes in the same alpha

i'll fix them when i get home

**Comment by AcidWeb** [comment]
👍 

First solution sound reasonable. All things that are not affected by stack compression should be ignored here.

**Comment by arkayenro** [comment]
try [r695-alpha](https://www.wowace.com/projects/ark-inventory/files/2530885/download) and see if thats better

**Comment by AcidWeb** [comment]
No more LUA errors. Indicator work correctly.

As I have very high-end computer can't judge performance impact. But I see that right after logging even without opening bag AI use up to 50mb of memory. After first garbage collection it drop to 8. Not checked that before so can't say it is connected with new features.
