### ISSUE TITLE
Add ilevel limit

### ISSUE THREAD

**Issue by AcidWeb** [arkayenro/arkinventory#996]
Small suggestion - add option to set minimal ilevel that trigger ilvl display on item icon.

**Comment by arkayenro** [comment]
thats pretty simple, will be in the next release

**Comment by arkayenro** [comment]
its in the same [r694-alpha](https://www.wowace.com/projects/ark-inventory/files/2530597/download) alpha with the stacklimit enhancement if you want to test this part out as well

**Comment by AcidWeb** [comment]
It works - thank you.
