### ISSUE TITLE
Rule based on age possible?

### ISSUE THREAD

**Issue by Fraktyl** [arkayenro/arkinventory#998]
Is there anyway to add a rule that we can move items less than a certain age to a specific bag?

Right now I set up a tt scan for "You can trade this item with players" for at the end of a raid night we pass out gear, etc.

No stress if not.  Love the addon!

**Comment by arkayenro** [comment]
rules can only apply to static item attributes, which age isnt.

there is a new items category that should do what you want, just set the number of minutes you want for it in the config

**Comment by Bachsau** [comment]
The point of using ArkInventory is that it abstracts item management from the physical bags they actually reside in, so there generally is no need to move anything at all or even care about it.
