### ISSUE TITLE
"frame" error when Restack button is clicked

### ISSUE THREAD

**Issue by MortonSaltMug** [arkayenro/arkinventory#999]
Date: 2018-02-15 12:10:13
ID: 1
Error occured in: Global
Count: 22
Message: ..\AddOns\ArkInventory\ArkInventory.lua line 7668:
   attempt to index local 'frame' (a nil value)
Debug:
   ArkInventory\ArkInventory.lua:7668: Frame_Item_Update_Lock()
   ArkInventory\ArkInventory.lua:2632: ObjectLockChanged()
   ...nterface\AddOns\ArkInventory\ArkInventoryStorage.lua:439: ?()
   ...urse\svn\CallbackHandler-1.0\CallbackHandler-1.0.lua:145:
      ...urse\svn\CallbackHandler-1.0\CallbackHandler-1.0.lua:145
   [string "safecall Dispatcher[3]"]:4:
      [string "safecall Dispatcher[3]"]:4
   [C]: ?
   [string "safecall Dispatcher[3]"]:13: ?()
   ...urse\svn\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: Fire()
   ...y\Externals\curse\svn\Ace3-AceEvent\AceEvent-3.0.lua:120:
      ...y\Externals\curse\svn\Ace3-AceEvent\AceEvent-3.0.lua:119
   [C]: resume()
   ArkInventory\ArkInventory.lua:10254: ThreadResume()
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1
Locals:
None
AddOns:
  Swatter, v7.3.1 (<%codename%>)
  ArkInventory, v30740
  ArkInventoryRules, v10003
  BlizRuntimeLib_enUS v7.3.5.70300 <none>
  (ck=7e)

**Comment by arkayenro** [comment]
this should be fixed next release

**Comment by arkayenro** [comment]
linking #1001 and #1002

**Comment by arkayenro** [comment]
fixed in 3.07.41
